/* ================= ARCADE ================= */
const ART=(bg,inner)=>'<rect width="120" height="72" fill="'+bg+'"/>'+inner;
/* ---------- Ball Breaker ---------- */
G.push({id:'ballbreak',name:'Ball Breaker',kind:'arcade',levels:true,tint:'#1D1A2F',blurb:'Aim, fire a stream of bouncing balls, and break the numbered blocks before they reach the bottom.',fmt:b=>'round '+b,
art:ART('#1D1A2F','<g font-family="Arial Black" font-size="10" text-anchor="middle"><rect x="10" y="8" width="22" height="16" rx="3" fill="#F2352A"/><text x="21" y="20" fill="#fff">12</text><rect x="36" y="8" width="22" height="16" rx="3" fill="#FF9F43"/><text x="47" y="20" fill="#fff">7</text><rect x="62" y="28" width="22" height="16" rx="3" fill="#2BB673"/><text x="73" y="40" fill="#fff">3</text></g><path d="M60 66L40 30" stroke="#fff" stroke-dasharray="3 3"/><circle cx="60" cy="66" r="4" fill="#fff"/>'),
run(root,c){const W=420,H=620,CO=7,CS=W/CO;const[cv,x]=mk(W,H,'width:min(100%,420px)');const L=c.level==null?1:c.level;const C=[{minB:1,maxB:4,hpMul:1,dbl:.15,plus:1,steel:0,pre:0,dead:9},{minB:2,maxB:6,hpMul:1.3,dbl:.3,plus:.65,steel:.14,pre:1,dead:9},{minB:3,maxB:7,hpMul:1.5,dbl:.35,plus:.5,steel:.24,pre:2,dead:8}][L]||{};const DEAD=C.dead;
  root.append(cv,el('p',{class:'hint'},'Drag to aim, let go to fire. Every block shows how many hits it needs. Grab the green circles for extra balls.'+(L>0?' Grey steel blocks can’t be broken, so bounce around them. Every 10th round is a boss row.':'')+(L===2?' Hard: blocks are much tougher, extra balls are rarer and you have one row less.':'')));
  let fdir={x:0,y:-1},blocks,balls=[],nBalls,ox,round,aim=null,firing=false,queue=0,fireT=0,firstLand=null,state='play',plus;
  let fireAge=0;function reset(){blocks=[];plus=[];nBalls=1;ox=W/2;round=0;state='play';for(let i=0;i<=C.pre;i++)newRow()}
  function newRow(){round++;blocks.forEach(b=>b.r++);plus.forEach(p=>p.r++);blocks=blocks.filter(b=>!(b.steel&&b.r>=DEAD-1));plus=plus.filter(p=>p.r<DEAD);const cols=shuffle([...Array(CO).keys()]);const boss=L>0&&round%10===0;const span=Math.min(C.maxB-C.minB,round/3|0);const n=boss?CO:Math.min(CO,C.minB+rand(span+1));const hp0=Math.max(1,Math.round(round*C.hpMul));let st=0;for(let i=0;i<n;i++){const steel=!boss&&st<2&&i>0&&Math.random()<C.steel;if(steel)st++;blocks.push({c:cols[i],r:1,hp:steel?Infinity:boss?hp0*2:hp0*(Math.random()<C.dbl?2:1),steel,boss})}if(n<CO&&Math.random()<C.plus)plus.push({c:cols[n],r:1});if(boss){beep(220,.25,'sawtooth',.05)}if(blocks.some(b=>!b.steel&&b.r>=DEAD)){state='over';c.best(round);beep(150,.4,'sawtooth')}c.stat('Round '+round+' · '+nBalls+' balls · '+['Easy','Normal','Hard'][L])}
  const bx=b=>({x:b.c*CS+3,y:b.r*CS*.9+3,w:CS-6,h:CS*.9-6});
  function step(dt){if(firing){fireAge+=dt;if(fireAge>10)balls.forEach(b=>{if(!b.done)b.vy+=260*dt});fireT-=dt;if(queue>0&&fireT<=0){fireT=.07;queue--;balls.push({x:ox,y:H-20,vx:fdir.x*640,vy:fdir.y*640,done:false})}}
    balls.forEach(b=>{if(b.done)return;for(let k=0;k<4;k++){const d=dt/4;b.x+=b.vx*d;b.y+=b.vy*d;if(b.x<6){b.x=6;b.vx=Math.abs(b.vx)}if(b.x>W-6){b.x=W-6;b.vx=-Math.abs(b.vx)}if(b.y<6){b.y=6;b.vy=Math.abs(b.vy)}
      for(const bl of blocks){if(bl.hp<=0)continue;const r=bx(bl);if(b.x>r.x-6&&b.x<r.x+r.w+6&&b.y>r.y-6&&b.y<r.y+r.h+6){const ox2=Math.min(b.x-(r.x-6),r.x+r.w+6-b.x),oy=Math.min(b.y-(r.y-6),r.y+r.h+6-b.y);if(ox2<oy)b.vx*=-1;else b.vy*=-1;b.x+=b.vx*d;b.y+=b.vy*d;if(bl.steel)beep(160,.02,'square',.02);else{bl.hp--;beep(300+Math.random()*400,.02,'square',.02)}break}}
      plus.forEach(p=>{if(!p.got&&Math.hypot(b.x-(p.c*CS+CS/2),b.y-(p.r*CS*.9+CS*.45))<16){p.got=true;nBalls++;beep(900,.05,'triangle',.04)}});
      if(b.y>H-20&&b.vy>0){b.done=true;if(firstLand==null)firstLand=b.x}}});blocks=blocks.filter(b=>b.hp>0);plus=plus.filter(p=>!p.got);
    if(firing&&queue===0&&balls.every(b=>b.done)){firing=false;balls=[];ox=clamp(firstLand??ox,10,W-10);firstLand=null;newRow()}}
  function draw(){x.fillStyle='#1D1A2F';x.fillRect(0,0,W,H);x.strokeStyle='rgba(255,255,255,.08)';x.beginPath();x.moveTo(0,DEAD*CS*.9);x.lineTo(W,DEAD*CS*.9);x.stroke();if(DEAD<9){x.fillStyle='rgba(242,53,42,.08)';x.fillRect(0,DEAD*CS*.9,W,H-DEAD*CS*.9-40)}
    blocks.forEach(bl=>{const r=bx(bl);if(bl.steel){const g=x.createLinearGradient(r.x,r.y,r.x,r.y+r.h);g.addColorStop(0,'#a7adb8');g.addColorStop(1,'#5c626d');x.fillStyle=g;x.beginPath();x.roundRect?x.roundRect(r.x,r.y,r.w,r.h,4):x.rect(r.x,r.y,r.w,r.h);x.fill();x.fillStyle='#3d424b';[[5,5],[r.w-5,5],[5,r.h-5],[r.w-5,r.h-5]].forEach(([a,b2])=>{x.beginPath();x.arc(r.x+a,r.y+b2,2.2,0,7);x.fill()});x.strokeStyle='rgba(255,255,255,.35)';x.lineWidth=1.5;x.beginPath();x.moveTo(r.x+8,r.y+r.h-8);x.lineTo(r.x+r.w-8,r.y+8);x.stroke();return}const h=(bl.hp*9+200)%360;x.fillStyle='hsl('+h+' 80% 55%)';x.beginPath();x.roundRect?x.roundRect(r.x,r.y,r.w,r.h,6):x.rect(r.x,r.y,r.w,r.h);x.fill();if(bl.boss){x.strokeStyle='#FFD23F';x.lineWidth=3;x.stroke()}if(bl.r>=DEAD-1){x.strokeStyle='rgba(255,60,50,'+(.5+.5*Math.sin(performance.now()/120))+')';x.lineWidth=3;x.stroke()}x.fillStyle='#fff';x.font='800 16px Figtree';x.textAlign='center';x.textBaseline='middle';x.fillText((bl.boss?'👑':'')+bl.hp,r.x+r.w/2,r.y+r.h/2)});
    plus.forEach(p=>{x.strokeStyle='#2BB673';x.lineWidth=3;x.beginPath();x.arc(p.c*CS+CS/2,p.r*CS*.9+CS*.45,10,0,7);x.stroke();x.fillStyle='#2BB673';x.fillText('+',p.c*CS+CS/2,p.r*CS*.9+CS*.45)});
    x.fillStyle='#fff';balls.forEach(b=>{if(!b.done){x.beginPath();x.arc(b.x,b.y,6,0,7);x.fill()}});if(!firing){x.beginPath();x.arc(ox,H-20,7,0,7);x.fill();x.font='700 12px Figtree';x.fillText('×'+nBalls,ox+18,H-10)}
    if(aim&&!firing){let px=ox,py=H-20,vx=aim.x,vy=aim.y;x.fillStyle='rgba(255,255,255,.5)';for(let i=0;i<40;i++){px+=vx*9;py+=vy*9;if(px<6||px>W-6)vx*=-1;if(py<6)vy*=-1;x.beginPath();x.arc(px,py,2.5,0,7);x.fill()}}
    x.fillStyle='#FFD23F';x.font='800 16px "JetBrains Mono"';x.textAlign='left';x.fillText('ROUND '+round,12,H-8);x.textAlign='right';x.fillStyle='rgba(255,255,255,.5)';x.font='700 12px Figtree';x.fillText(['EASY','NORMAL','HARD'][L],W-12,H-8);if(state==='over')banner(x,W,H,'Round '+round,'The blocks reached the bottom. Tap to retry')}
  const aimAt=e=>{const p=canvasPos(cv,e);let dx=p.x-ox,dy=p.y-(H-20);if(dy>-10)dy=-10;const L=Math.hypot(dx,dy);aim={x:dx/L,y:dy/L}};
  c.on(cv,'pointerdown',e=>{if(state==='over'){reset();return}if(!firing)aimAt(e)});c.on(cv,'pointermove',e=>{if(aim&&!firing&&e.buttons)aimAt(e)});c.on(cv,'pointerup',()=>{if(aim&&!firing&&state==='play'){fdir=aim;firing=true;fireAge=0;queue=nBalls;fireT=0;balls=[];sweep(300,700,.15,'triangle',.04)}aim=null});
  reset();c.loop(dt=>{if(state==='play')step(Math.min(.03,dt/1000));draw()})}});
/* ---------- Color Valley ---------- */
G.push({id:'colorvalley',name:'Color Valley',kind:'arcade',levels:true,tint:'#3a2a6a',blurb:'Hop upward through spinning color rings. You can only pass through your own color.',fmt:b=>b+' pts',
art:ART('#1D1A2F','<g fill="none" stroke-width="7"><path d="M40 36a20 20 0 0 1 20-20" stroke="#F2352A"/><path d="M60 16a20 20 0 0 1 20 20" stroke="#FFD23F"/><path d="M80 36a20 20 0 0 1-20 20" stroke="#2BB673"/><path d="M60 56a20 20 0 0 1-20-20" stroke="#2d6fd6"/></g><circle cx="60" cy="64" r="5" fill="#FFD23F"/>'),
run(root,c){const W=400,H=640;const[cv,x]=mk(W,H,'width:min(100%,400px)');root.append(cv,el('p',{class:'hint'},'Tap, click or press Space to hop. Pass only through the part of each ring that matches your ball. Stars are points, and the rainbow orbs change your color.'));
  const CC=['#F2352A','#FFD23F','#2BB673','#2d6fd6'];let ball,obs,cam,score,state='ready',best=c.best()||0;
  function reset(){ball={y:H-120,vy:0,c:rand(4)};obs=[];cam=0;score=0;for(let i=0;i<6;i++)addObs(H-360-i*300);state='ready'}
  function addObs(y){const k=obs.length%3;const sp=(c.pick(1.2,1.7,2.3))*Math.min(1.5,1+score*.02)*(Math.random()<.5?1:-1);obs.push({y,type:k===2?'bar':'ring',a:Math.random()*6,sp,r:k===1?90:70,star:true,sw:true})}
  function hop(){if(state==='over'){reset();return}state='play';ball.vy=-420;beep(700,.04,'triangle',.03)}
  function colAt(o,ang){const a=((ang-o.a)%(Math.PI*2)+Math.PI*4)%(Math.PI*2);return Math.floor(a/(Math.PI/2))}
  function step(dt){if(state!=='play')return;ball.vy+=1200*dt;ball.y+=ball.vy*dt;const sy=ball.y-cam;if(sy<H*.45)cam=ball.y-H*.45;if(sy>H+20)die();
    obs.forEach(o=>{o.a+=o.sp*dt;if(o.type==='ring'){const d=Math.abs(ball.y-o.y);if(Math.abs(d-o.r)<12){const ang=ball.y<o.y?-Math.PI/2:Math.PI/2;if(colAt(o,ang)!==ball.c)die()}}else{if(Math.abs(ball.y-o.y)<10){const off=((o.a*60)%(W)+W)%W;const seg=Math.floor(((W/2-off+W*2)%W)/(W/4));if(seg!==ball.c)die()}}
      if(o.star&&Math.abs(ball.y-o.y)<16){o.star=false;score++;beep(1000,.06,'triangle',.04)}if(o.sw&&ball.y<o.y-150&&ball.y>o.y-170){o.sw=false;let nc=rand(4);if(nc===ball.c)nc=(nc+1)%4;ball.c=nc;beep(500,.08,'sine',.04)}});
    if(obs[0].y-cam>H+120){obs.shift();addObs(obs[obs.length-1].y-300)}c.stat('Color Valley · '+score)}
  function die(){if(state!=='play')return;state='over';best=c.best(score);noise(.4,'lowpass',500,.3)}
  function draw(){x.fillStyle='#1D1A2F';x.fillRect(0,0,W,H);obs.forEach(o=>{const y=o.y-cam;if(y<-120||y>H+120)return;if(o.type==='ring'){for(let k=0;k<4;k++){x.strokeStyle=CC[k];x.lineWidth=14;x.beginPath();x.arc(W/2,y,o.r,o.a+k*Math.PI/2+.02,o.a+(k+1)*Math.PI/2-.02);x.stroke()}}else{const off=((o.a*60)%W+W)%W;for(let k=-1;k<5;k++){x.fillStyle=CC[(k%4+4)%4];x.fillRect(off+k*W/4-W,y-7,W/4,14);x.fillRect(off+k*W/4,y-7,W/4,14)}}
      if(o.star){x.fillStyle='#fff';x.font='22px sans-serif';x.textAlign='center';x.textBaseline='middle';x.fillText('★',W/2,y)}if(o.sw){const sy=y-160;for(let k=0;k<4;k++){x.fillStyle=CC[k];x.beginPath();x.moveTo(W/2,sy);x.arc(W/2,sy,11,k*Math.PI/2,(k+1)*Math.PI/2);x.fill()}}});
    x.fillStyle=CC[ball.c];x.beginPath();x.arc(W/2,ball.y-cam,10,0,7);x.fill();x.fillStyle='#fff';x.font='800 26px Figtree';x.textAlign='left';x.fillText(score,16,36);if(state==='ready')banner(x,W,H,'Color Valley','Tap to hop');if(state==='over')banner(x,W,H,score+' stars','Best '+best+' · tap to retry')}
  c.on(cv,'pointerdown',e=>{e.preventDefault();hop()});c.on(document,'keydown',e=>{if(e.key===' '){e.preventDefault();hop()}});reset();c.loop(dt=>{step(Math.min(.03,dt/1000));draw()})}});
/* ---------- Go Down ---------- */
G.push({id:'godown',name:'Go Down',kind:'arcade',levels:true,tint:'#7FC8F8',blurb:'Platforms keep rising. Roll left and right to drop through the gaps, and stay away from the spikes on top.',fmt:b=>b+' m',
art:ART('#7FC8F8','<path d="M0 0l6 8 6-8 6 8 6-8 6 8 6-8 6 8 6-8 6 8 6-8 6 8 6-8 6 8 6-8 6 8 6-8 6 8 6-8 6 8 6-8" fill="#F2352A"/><rect x="0" y="30" width="50" height="7" fill="#1D1A2F"/><rect x="70" y="30" width="50" height="7" fill="#1D1A2F"/><rect x="20" y="56" width="100" height="7" fill="#1D1A2F"/><circle cx="60" cy="42" r="6" fill="#FFD23F" stroke="#1D1A2F" stroke-width="2"/>'),
run(root,c){const W=400,H=620;const[cv,x]=mk(W,H,'width:min(100%,400px)');root.append(cv);const keys=holdPad(root,[['l','◀'],['r','▶']]);root.append(el('p',{class:'hint'},'A/D or ←/→ to roll. Fall through the gaps. Red platforms are spiky, and the ceiling is too!'));
  let P,plats,sp,depth,state='ready',pressed={};
  function reset(){P={x:W/2,y:200,vx:0,vy:0};plats=[];for(let i=0;i<8;i++)addPlat(260+i*90);sp=c.pick(55,75,95);depth=0;state='ready'}
  function addPlat(y){const gw=c.pick(96,82,70);const prev=plats[plats.length-1];const lastSpike=prev&&prev.spike;const spike=plats.length>3&&!lastSpike&&Math.random()<c.pick(.1,.18,.26);const pc=prev?prev.gx+prev.gw/2:W/2;const shift=spike?45:c.pick(170,150,130);const cx=clamp(pc+(Math.random()*2-1)*shift,20+gw/2,W-20-gw/2);plats.push({y,gx:cx-gw/2,gw,spike})}
  function step(dt){if(state!=='play')return;sp=Math.min(sp+dt*1.2,c.pick(115,140,165));const L=pressed.a||pressed.arrowleft||keys.l,R=pressed.d||pressed.arrowright||keys.r;P.vx+=((R?1:0)-(L?1:0))*2600*dt;P.vx*=Math.pow(.012,dt);P.x=clamp(P.x+P.vx*dt,10,W-10);P.vy+=900*dt;P.y+=P.vy*dt;
    plats.forEach(p=>{p.y-=sp*dt;if(P.vy>=0&&P.y+10>=p.y&&P.y+10<=p.y+14+P.vy*dt&&!(P.x>p.gx+6&&P.x<p.gx+p.gw-6)){if(p.spike){die();return}P.y=p.y-10;P.vy=0}});depth+=sp*dt/30;
    if(plats[0].y<-20){plats.shift();addPlat(plats[plats.length-1].y+90)}if(P.y<28||P.y>H+20)die();c.stat('Go Down · '+Math.floor(depth)+' m')}
  function die(){if(state!=='play')return;state='over';c.best(Math.floor(depth));noise(.4,'lowpass',500,.3)}
  function draw(){x.fillStyle='#7FC8F8';x.fillRect(0,0,W,H);plats.forEach(p=>{x.fillStyle=p.spike?'#F2352A':'#1D1A2F';x.fillRect(0,p.y,p.gx,12);x.fillRect(p.gx+p.gw,p.y,W-p.gx-p.gw,12);if(p.spike){x.fillStyle='#fff';for(let i=4;i<W;i+=12)if(i<p.gx||i>p.gx+p.gw){x.beginPath();x.moveTo(i,p.y);x.lineTo(i+6,p.y-7);x.lineTo(i+12,p.y);x.fill()}}});
    x.fillStyle='#F2352A';x.beginPath();x.moveTo(0,0);for(let i=0;i<=W;i+=16){x.lineTo(i,0);x.lineTo(i+8,20)}x.lineTo(W,0);x.fill();x.fillStyle='#FFD23F';x.strokeStyle='#1D1A2F';x.lineWidth=3;x.beginPath();x.arc(P.x,P.y,10,0,7);x.fill();x.stroke();
    x.fillStyle='#1D1A2F';x.font='800 18px "JetBrains Mono"';x.textAlign='left';x.fillText(Math.floor(depth)+' m',12,H-12);if(state==='ready')banner(x,W,H,'Go Down','Press a direction to start');if(state==='over')banner(x,W,H,Math.floor(depth)+' m','Tap to retry')}
  c.on(document,'keydown',e=>{pressed[e.key.toLowerCase()]=1;if(state==='ready')state='play';if(state==='over'&&e.key===' ')reset()});c.on(document,'keyup',e=>{pressed[e.key.toLowerCase()]=0});c.on(cv,'pointerdown',()=>{if(state==='over')reset();else if(state==='ready')state='play'});
  reset();c.loop(dt=>{if(state==='ready'&&(keys.l||keys.r))state='play';step(Math.min(.03,dt/1000));draw()})}});
/* ---------- Teo's Escape ---------- */
G.push({id:'teoescape',name:'Teo’s Escape',kind:'arcade',tint:'#FF9F43',blurb:'Teo is making a run for it! Jump over crates, slide under drones, and grab coins.',fmt:b=>b+' m',
art:ART('#FFE27A','<rect y="54" width="120" height="18" fill="#8a5a2b"/><rect x="74" y="40" width="14" height="14" fill="#FF9F43" stroke="#1D1A2F" stroke-width="2"/><circle cx="34" cy="38" r="8" fill="#2d6fd6" stroke="#1D1A2F" stroke-width="2.5"/><circle cx="37" cy="36" r="2" fill="#fff"/><path d="M30 46l-4 8M38 46l4 8" stroke="#1D1A2F" stroke-width="3"/>'),
run(root,c){const W=820,H=360,GY=300;const[cv,x]=mk(W,H,'width:100%');root.append(cv);const keys=holdPad(root,[['j','⤒ Jump'],['s','⤓ Slide']]);root.append(el('p',{class:'hint'},'Space/↑ to jump (twice for a double jump), ↓ to slide. Crates are low, drones fly high.'));
  let T0,P,obs,coins,sp,dist,nc,state='ready',jl=false,pressed={},cT=0;
  function reset(){P={y:GY,vy:0,jumps:0,slide:0};obs=[];coins=[];sp=320;dist=0;nc=0;state='ready';cT=1}
  function step(dt){if(state!=='play')return;sp+=dt*8;dist+=sp*dt/40;const J=pressed[' ']||pressed.arrowup||pressed.w||keys.j,D=pressed.arrowdown||pressed.s||keys.s;if(J&&!jl&&P.jumps<2){P.vy=-560;P.jumps++;beep(600,.05,'triangle',.04)}jl=J;P.slide=D&&P.y>=GY?.3:Math.max(0,P.slide-dt);if(D&&P.y<GY)P.vy+=2400*dt;P.vy+=1700*dt;P.y+=P.vy*dt;if(P.y>=GY){P.y=GY;P.vy=0;P.jumps=0}
    cT-=dt;if(cT<=0){cT=clamp(1.3-sp/1500,.5,1.3)+Math.random()*.5;const k=Math.random();obs.push(k<.55?{x:W+20,w:34,h:34+rand(2)*22,y:GY,kind:'crate'}:k<.85?{x:W+20,w:56,h:24,y:GY-46,kind:'drone'}:{x:W+20,w:80,h:26,y:GY,kind:'pit'});if(Math.random()<.6)for(let i=0;i<4;i++)coins.push({x:W+120+i*30,y:GY-40-Math.random()*60})}
    obs.forEach(o=>o.x-=sp*dt);coins.forEach(q=>q.x-=sp*dt);const ph=P.slide>0?26:52;const pr={x:80,y:P.y-ph,w:30,h:ph};
    for(const o of obs){if(o.kind==='pit'){if(P.y>=GY&&pr.x+pr.w>o.x+8&&pr.x<o.x+o.w-8)die()}else{const oy=o.y-o.h;if(pr.x+pr.w>o.x&&pr.x<o.x+o.w&&pr.y+pr.h>oy&&pr.y<o.y)die()}}
    coins.forEach(q=>{if(!q.got&&Math.abs(q.x-95)<20&&Math.abs(q.y-(P.y-ph/2))<30){q.got=true;nc++;beep(1200,.04,'triangle',.04)}});obs=obs.filter(o=>o.x>-100);coins=coins.filter(q=>q.x>-20&&!q.got);c.stat('Teo’s Escape · '+Math.floor(dist)+' m')}
  function die(){if(state!=='play')return;state='over';c.best(Math.floor(dist)+nc*5);noise(.4,'lowpass',400,.3)}
  function draw(){x.fillStyle='#FFE27A';x.fillRect(0,0,W,H);x.fillStyle='rgba(255,159,67,.3)';for(let i=0;i<6;i++){const bx=((i*180-dist*6)%1080+1080)%1080-140;x.fillRect(bx,120,90,GY-120)}x.fillStyle='#8a5a2b';x.fillRect(0,GY,W,H-GY);
    obs.forEach(o=>{if(o.kind==='pit'){x.fillStyle='#1D1A2F';x.fillRect(o.x,GY,o.w,H-GY)}else if(o.kind==='crate'){x.fillStyle='#FF9F43';x.strokeStyle='#1D1A2F';x.lineWidth=3;x.fillRect(o.x,o.y-o.h,o.w,o.h);x.strokeRect(o.x,o.y-o.h,o.w,o.h);x.beginPath();x.moveTo(o.x,o.y-o.h);x.lineTo(o.x+o.w,o.y);x.stroke()}else{x.fillStyle='#5A5470';x.fillRect(o.x,o.y-o.h,o.w,o.h);x.fillStyle='#F2352A';x.beginPath();x.arc(o.x+o.w/2,o.y-o.h/2,5,0,7);x.fill();x.strokeStyle='#1D1A2F';x.beginPath();x.moveTo(o.x-8,o.y-o.h-4);x.lineTo(o.x+o.w+8,o.y-o.h-4);x.stroke()}});
    coins.forEach(q=>{x.fillStyle='#FFD23F';x.strokeStyle='#1D1A2F';x.lineWidth=2;x.beginPath();x.arc(q.x,q.y,8,0,7);x.fill();x.stroke()});
    const ph=P.slide>0?26:52;x.fillStyle='#2d6fd6';x.strokeStyle='#1D1A2F';x.lineWidth=3;x.beginPath();x.roundRect?x.roundRect(80,P.y-ph,30,ph,10):x.rect(80,P.y-ph,30,ph);x.fill();x.stroke();x.fillStyle='#fff';x.beginPath();x.arc(100,P.y-ph+12,4,0,7);x.fill();
    x.fillStyle='#1D1A2F';x.font='800 18px "JetBrains Mono"';x.textAlign='left';x.fillText(Math.floor(dist)+' m · 🪙 '+nc,14,26);if(state==='ready')banner(x,W,H,'Teo’s Escape','Press Space or tap Jump to run');if(state==='over')banner(x,W,H,Math.floor(dist)+' m','Caught! Tap to run again')}
  c.on(document,'keydown',e=>{const k=e.key.toLowerCase();pressed[k]=1;if([' ','arrowup','arrowdown'].includes(k))e.preventDefault();if(state==='ready'&&(k===' '||k==='arrowup'))state='play';else if(state==='over'&&k===' ')reset()});c.on(document,'keyup',e=>{pressed[e.key.toLowerCase()]=0});c.on(cv,'pointerdown',()=>{if(state==='over')reset();else if(state==='ready')state='play'});
  reset();c.loop(dt=>{if(state==='ready'&&keys.j)state='play';step(Math.min(.03,dt/1000));draw()})}});
/* ---------- Let's Park (draw the path) ---------- */
G.push({id:'letspark',name:'Let’s Park',kind:'arcade',levels:true,tint:'#5A5470',blurb:'Draw a path from each car to its matching parking spot, then press Go. Don’t let them crash!',fmt:b=>'level '+b,
art:ART('#5A5470','<rect x="84" y="8" width="20" height="26" fill="none" stroke="#F2352A" stroke-width="2.5" stroke-dasharray="4 3"/><rect x="14" y="40" width="14" height="22" rx="3" fill="#F2352A"/><path d="M21 38q10-26 73-16" fill="none" stroke="#F2352A" stroke-width="3"/><rect x="50" y="42" width="14" height="22" rx="3" fill="#2d6fd6"/>'),
run(root,c){const W=600,H=600;const[cv,x]=mk(W,H,'width:min(100%,600px)');const row=el('div',{class:'row'});const go=el('button',{class:'btn primary',type:'button'},'▶ Go');const clr=el('button',{class:'btn',type:'button'},'Clear paths');row.append(go,clr);root.append(cv,row,el('p',{class:'hint'},'Drag from each car to the spot of the same color. When every car has a path, press Go. Cars move at the same speed, so plan who goes first!'));
  const CC=['#F2352A','#2d6fd6','#2BB673','#FFD23F'];let lvl=Math.max(1,S.get('lp_lv',1)),cars,spots,walls,drawing=null,state='plan',t=0,msg='';
  function build(){const n=Math.min(4,1+Math.floor((lvl+1)/3));cars=[];spots=[];walls=[];state='plan';t=0;const used=[];const freeAt=(px,py,r)=>used.every(u=>Math.hypot(u[0]-px,u[1]-py)>r);
    for(let i=0;i<Math.min(3,lvl-1);i++){const w=60+Math.random()*120,h=24;const wx=100+Math.random()*(W-260),wy=180+Math.random()*(H-360);walls.push({x:wx,y:wy,w:Math.random()<.5?w:h,h:Math.random()<.5?h:w})}
    const inWall=(px,py,r)=>walls.some(w=>px>w.x-r&&px<w.x+w.w+r&&py>w.y-r&&py<w.y+w.h+r);
    for(let i=0;i<n;i++){let px,py;do{px=60+Math.random()*(W-120);py=H-80-Math.random()*120}while(!freeAt(px,py,70)||inWall(px,py,30));used.push([px,py]);cars.push({c:i,x:px,y:py,a:-Math.PI/2,path:null,sx:px,sy:py,done:false});do{px=60+Math.random()*(W-120);py=70+Math.random()*140}while(!freeAt(px,py,80)||inWall(px,py,40));used.push([px,py]);spots.push({c:i,x:px,y:py})}c.stat('Let’s Park · Level '+lvl)}
  function simulate(dt){t+=dt;const spd=110;let moving=false;cars.forEach(k=>{if(k.done||!k.path)return;const L=k.path;k.pi=k.pi||0;let rem=spd*dt;while(rem>0&&k.pi<L.length-1){const a=L[k.pi],b=L[k.pi+1];const seg=Math.hypot(b[0]-a[0],b[1]-a[1]);const along=k.prog||0;if(along+rem<seg){k.prog=along+rem;rem=0}else{rem-=seg-along;k.prog=0;k.pi++}}const a=L[Math.min(k.pi,L.length-1)],b=L[Math.min(k.pi+1,L.length-1)];const seg=Math.hypot(b[0]-a[0],b[1]-a[1])||1;const f=(k.prog||0)/seg;k.x=a[0]+(b[0]-a[0])*f;k.y=a[1]+(b[1]-a[1])*f;if(seg>1)k.a=Math.atan2(b[1]-a[1],b[0]-a[0]);if(k.pi>=L.length-1)k.done=true;else moving=true});
    for(let i=0;i<cars.length;i++)for(let j=i+1;j<cars.length;j++){if(Math.hypot(cars[i].x-cars[j].x,cars[i].y-cars[j].y)<28){state='fail';msg='Crash!';noise(.4,'lowpass',400,.3);return}}
    for(const k of cars)if(walls.some(w=>k.x>w.x-8&&k.x<w.x+w.w+8&&k.y>w.y-8&&k.y<w.y+w.h+8)){state='fail';msg='Hit a wall!';noise(.4,'lowpass',400,.3);return}
    if(!moving){const ok=cars.every(k=>{const s=spots[k.c];return Math.hypot(k.x-s.x,k.y-s.y)<18});if(ok){state='won';msg='All parked!';S.set('lp_lv',Math.max(S.get('lp_lv',1),lvl+1));c.best(lvl);[523,659,784].forEach((q,i)=>c.after(()=>beep(q,.15,'triangle',.06),i*100))}else{state='fail';msg='Someone missed their spot'}}}
  function draw(){x.fillStyle='#5A5470';x.fillRect(0,0,W,H);x.strokeStyle='rgba(255,255,255,.12)';x.lineWidth=2;for(let i=0;i<W;i+=60){x.beginPath();x.moveTo(i,0);x.lineTo(i,H);x.stroke()}
    walls.forEach(w=>{x.fillStyle='#8c86a3';x.fillRect(w.x,w.y,w.w,w.h);x.strokeStyle='#1D1A2F';x.strokeRect(w.x,w.y,w.w,w.h)});
    spots.forEach(s=>{x.setLineDash([6,5]);x.strokeStyle=CC[s.c];x.lineWidth=3;x.strokeRect(s.x-16,s.y-24,32,48);x.setLineDash([]);x.fillStyle=CC[s.c];x.font='800 14px Figtree';x.textAlign='center';x.fillText('P',s.x,s.y+5)});
    cars.forEach(k=>{if(k.path){x.strokeStyle=CC[k.c];x.globalAlpha=.6;x.lineWidth=5;x.lineJoin='round';x.beginPath();k.path.forEach((p,i)=>i?x.lineTo(p[0],p[1]):x.moveTo(p[0],p[1]));x.stroke();x.globalAlpha=1}});
    cars.forEach(k=>{x.save();x.translate(k.x,k.y);x.rotate(k.a+Math.PI/2);x.fillStyle=CC[k.c];x.strokeStyle='#1D1A2F';x.lineWidth=2.5;x.beginPath();x.roundRect?x.roundRect(-12,-20,24,40,6):x.rect(-12,-20,24,40);x.fill();x.stroke();x.fillStyle='#9fd6ff';x.fillRect(-8,-12,16,9);x.restore()});
    x.fillStyle='#fff';x.font='700 16px "JetBrains Mono"';x.textAlign='left';x.fillText('LEVEL '+lvl,14,26);if(state==='won'||state==='fail')banner(x,W,H,msg,state==='won'?'Tap for level '+(lvl+1):'Tap to try again')}
  c.on(cv,'pointerdown',e=>{if(state==='won'){lvl++;build();return}if(state==='fail'){cars.forEach(k=>{k.x=k.sx;k.y=k.sy;k.pi=0;k.prog=0;k.done=false;k.a=-Math.PI/2});state='plan';return}if(state!=='plan')return;const p=canvasPos(cv,e);const k=cars.find(q=>Math.hypot(q.x-p.x,q.y-p.y)<26);if(k){drawing=k;k.path=[[k.x,k.y]];cv.setPointerCapture(e.pointerId)}});
  c.on(cv,'pointermove',e=>{if(!drawing)return;const p=canvasPos(cv,e);const L=drawing.path;const l=L[L.length-1];if(Math.hypot(p.x-l[0],p.y-l[1])>8)L.push([p.x,p.y])});
  c.on(cv,'pointerup',()=>{if(drawing){const s=spots[drawing.c],L=drawing.path,l=L[L.length-1];if(Math.hypot(l[0]-s.x,l[1]-s.y)<30)L.push([s.x,s.y]);else drawing.path=null}drawing=null});
  go.addEventListener('click',()=>{if(state==='plan'&&cars.every(k=>k.path)){state='run';cars.forEach(k=>{k.pi=0;k.prog=0})}else if(state==='plan'){beep(200,.1,'square',.04)}});clr.addEventListener('click',()=>{if(state==='plan')cars.forEach(k=>k.path=null)});
  build();c.loop(dt=>{if(state==='run')simulate(Math.min(.03,dt/1000));draw()})}});
/* ---------- Geometry Rush ---------- */
G.push({id:'georush',name:'Geometry Rush',kind:'arcade',levels:true,tint:'#2d6fd6',blurb:'Your square races forward on its own. Tap to jump over spikes and land on blocks. How far can you get?',fmt:b=>b+'%',
art:ART('#2d6fd6','<rect y="54" width="120" height="18" fill="#1D1A2F"/><rect x="24" y="34" width="16" height="16" fill="#FFD23F" stroke="#1D1A2F" stroke-width="2.5" transform="rotate(20 32 42)"/><path d="M60 54l7-14 7 14zM74 54l7-14 7 14z" fill="#fff" stroke="#1D1A2F" stroke-width="2"/><rect x="96" y="38" width="16" height="16" fill="#7FC8F8" stroke="#1D1A2F" stroke-width="2"/>'),
run(root,c){const W=820,H=380,GY=300,U=34;const[cv,x]=mk(W,H,'width:100%');root.append(cv,el('p',{class:'hint'},'Click, tap or Space to jump (hold to keep bouncing). Spikes kill you. You can land on blocks. Reach 100%!'));
  let lvl,P,cam,att=0,state='ready',hold=false,best=c.best()||0,parts=[];
  function genLevel(seed){const L=[];let xx=12;const R=()=>{seed=(seed*9301+49297)%233280;return seed/233280};const len=c.pick(160,200,240);while(xx<len){const r=R();if(r<.35){L.push({t:'spike',x:xx,y:0});if(R()<.4)L.push({t:'spike',x:xx+1,y:0});if(R()<c.pick(.1,.25,.4))L.push({t:'spike',x:xx+2,y:0});xx+=6+R()*3|0}else if(r<.65){const h=1+(R()*2|0),w=2+(R()*3|0);for(let i=0;i<w;i++)for(let j=0;j<h;j++)L.push({t:'block',x:xx+i,y:j});if(R()<.5)L.push({t:'spike',x:xx+w+1,y:0});xx+=w+6}else if(r<.8){for(let i=0;i<3;i++)for(let k=0;k<3;k++)L.push({t:'block',x:xx+i*4+k,y:i});L.push({t:'spike',x:xx+5,y:0},{t:'spike',x:xx+9,y:0});xx+=16}else xx+=4}return{L,len}}
  function canBeat(lv,sp){const dt=1/60,end=lv.len*U,memo=new Set(),st=[[0,0,0,1,0,0]];let n=0;while(st.length&&n<600000){let[px,py,vy,on,f,jmp]=st.pop();for(;;){n++;if(px>=end)return true;
      if(on&&!jmp){const k=f+'_'+Math.round(py);if(memo.has(k))break;memo.add(k);st.push([px,py,vy,1,f,1])}
      px+=sp*dt;vy-=2600*dt;if(on&&jmp)vy=820;jmp=0;on=0;py+=vy*dt;f++;if(py<=0){py=0;vy=0;on=1}let dead=false;
      for(const o of lv.L){if(o.t!=='block')continue;const ox=o.x*U,oy=o.y*U;if(px+U>ox+2&&px<ox+U-2&&py<oy+U&&py+U>oy){if(vy<=0&&py>oy+U-22){py=oy+U;vy=0;on=1}else{dead=true;break}}}
      if(!dead)for(const o of lv.L){if(o.t!=='spike')continue;const ox=o.x*U+U/2,oy=o.y*U;if(Math.abs(px+U/2-ox)<U*.55&&py<oy+U*.6&&py+U>oy){dead=true;break}}if(dead)break}}return false}
  function reset(){let sd=S.get('gr_seed',0),lv=genLevel(1234+sd),tries=0;while(!canBeat(lv,c.pick(270,310,350))&&tries<25){tries++;sd++;lv=genLevel(1234+sd)}S.set('gr_seed',sd);lvl=lv;P={x:0,y:0,vy:0,rot:0,on:true};cam=0;att++;parts=[];state='play'}
  function solidAt(px,py){return lvl.L.some(o=>o.t==='block'&&px>o.x*U&&px<o.x*U+U&&py>o.y*U&&py<o.y*U+U)}
  function step(dt){if(state!=='play')return;const sp=c.pick(270,310,350);P.x+=sp*dt;P.vy-=2600*dt;const J=hold;if(J&&P.on){P.vy=820;P.on=false}P.y+=P.vy*dt;P.on=false;if(P.y<=0){P.y=0;P.vy=0;P.on=true}
    for(const o of lvl.L){if(o.t!=='block')continue;const ox=o.x*U,oy=o.y*U;if(P.x+U>ox+2&&P.x<ox+U-2&&P.y<oy+U&&P.y+U>oy){if(P.vy<=0&&P.y>oy+U-22){P.y=oy+U;P.vy=0;P.on=true}else{die();return}}}
    for(const o of lvl.L){if(o.t!=='spike')continue;const ox=o.x*U+U/2,oy=o.y*U;if(Math.abs(P.x+U/2-ox)<U*.55&&P.y<oy+U*.6&&P.y+U>oy){die();return}}
    if(!P.on)P.rot+=dt*7;else P.rot=Math.round(P.rot/(Math.PI/2))*(Math.PI/2);cam=P.x-200;const pc=Math.min(100,Math.floor(P.x/(lvl.len*U)*100));if(pc>=100){state='won';best=c.best(100);S.set('gr_seed',S.get('gr_seed',0)+1);[523,659,784,1046].forEach((q,i)=>c.after(()=>beep(q,.15,'triangle',.06),i*100))}c.stat('Geometry Rush · '+pc+'% · attempt '+att)}
  function die(){state='dead';const pc=Math.min(100,Math.floor(P.x/(lvl.len*U)*100));best=c.best(pc);noise(.3,'highpass',1500,.2);for(let i=0;i<20;i++)parts.push({x:P.x+U/2,y:P.y+U/2,vx:(Math.random()-.5)*400,vy:Math.random()*500,l:1});setTimeout(()=>{if(state==='dead')reset()},900)}
  function draw(){const g=x.createLinearGradient(0,0,0,H);g.addColorStop(0,'#2d6fd6');g.addColorStop(1,'#1D1A2F');x.fillStyle=g;x.fillRect(0,0,W,H);x.fillStyle='rgba(255,255,255,.06)';for(let i=0;i<14;i++){const bx=((i*140-cam*.3)%1960+1960)%1960-140;x.fillRect(bx,100,70,GY-100)}x.fillStyle='#1D1A2F';x.fillRect(0,GY,W,H-GY);x.strokeStyle='#7FC8F8';x.lineWidth=2;x.beginPath();x.moveTo(0,GY);x.lineTo(W,GY);x.stroke();
    const sx=v=>v-cam,sy=v=>GY-v;lvl.L.forEach(o=>{const px=sx(o.x*U);if(px<-U||px>W)return;if(o.t==='block'){x.fillStyle='#7FC8F8';x.strokeStyle='#fff';x.lineWidth=2;x.fillRect(px,sy(o.y*U+U),U,U);x.strokeRect(px+2,sy(o.y*U+U)+2,U-4,U-4)}else{x.fillStyle='#fff';x.strokeStyle='#1D1A2F';x.beginPath();x.moveTo(px+3,sy(o.y*U));x.lineTo(px+U/2,sy(o.y*U+U*.85));x.lineTo(px+U-3,sy(o.y*U));x.closePath();x.fill();x.stroke()}});
    const fx=sx(lvl.len*U);x.fillStyle='#2BB673';x.fillRect(fx,0,8,GY);if(state!=='dead'){x.save();x.translate(sx(P.x)+U/2,sy(P.y)-U/2);x.rotate(P.rot);x.fillStyle='#FFD23F';x.strokeStyle='#1D1A2F';x.lineWidth=3;x.fillRect(-U/2,-U/2,U,U);x.strokeRect(-U/2,-U/2,U,U);x.fillStyle='#1D1A2F';x.fillRect(-8,-6,5,5);x.fillRect(4,-6,5,5);x.fillRect(-7,5,14,3);x.restore()}
    parts.forEach(p=>{p.l-=.02;p.x+=p.vx*.016;p.vy-=900*.016;p.y+=p.vy*.016;x.fillStyle='rgba(255,210,63,'+Math.max(0,p.l)+')';x.fillRect(sx(p.x),sy(p.y),6,6)});
    const pc=Math.min(100,Math.floor(P.x/(lvl.len*U)*100));x.fillStyle='rgba(255,255,255,.2)';x.fillRect(W/2-150,12,300,10);x.fillStyle='#2BB673';x.fillRect(W/2-150,12,3*pc,10);x.fillStyle='#fff';x.font='800 14px "JetBrains Mono"';x.textAlign='center';x.fillText(pc+'% · attempt '+att+' · best '+best+'%',W/2,40);if(state==='ready')banner(x,W,H,'Geometry Rush','Tap or press Space to jump');if(state==='won')banner(x,W,H,'100%! Level complete','Tap for a new level')}
  const down=()=>{hold=true;if(state==='ready'||state==='won'){att=0;reset()}},up=()=>{hold=false};c.on(cv,'pointerdown',e=>{e.preventDefault();down()});c.on(window,'pointerup',up);c.on(document,'keydown',e=>{if(e.key===' '||e.key==='ArrowUp'){e.preventDefault();down()}});c.on(document,'keyup',e=>{if(e.key===' '||e.key==='ArrowUp')up()});
  lvl=genLevel(1234+S.get('gr_seed',0));P={x:0,y:0,vy:0,rot:0,on:true};cam=-200;c.loop(dt=>{step(Math.min(.025,dt/1000));draw()})}});
/* ---------- Virus Attack ---------- */
G.push({id:'virus',name:'Virus Attack',kind:'arcade',levels:true,tint:'#6EE7B7',blurb:'Viruses are swarming the healthy cells! Tap and swipe to pop them, grab power-ups, and beat a boss every fifth wave.',fmt:b=>'wave '+b,
art:ART('#e6fff4','<g stroke="#1D1A2F" stroke-width="2"><circle cx="40" cy="36" r="13" fill="#6EE7B7"/><circle cx="80" cy="28" r="9" fill="#F2352A"/><circle cx="74" cy="54" r="7" fill="#B9A7FF"/></g><g stroke="#1D1A2F" stroke-width="2"><path d="M40 20v-6M40 52v6M24 36h-6M56 36h6M29 25l-4-4M51 47l4 4M51 25l4-4M29 47l-4 4"/></g><circle cx="36" cy="33" r="2" fill="#1D1A2F"/><circle cx="44" cy="33" r="2" fill="#1D1A2F"/>'),
run(root,c){const W=700,H=500;const[cv,x]=mk(W,H,'width:100%;touch-action:none');root.append(cv,el('p',{class:'hint'},'Protect the blue cells! Tap or swipe across viruses to pop them before they infect a cell. Grab power-ups: ❄️ freeze, 💥 bomb, ⚡ chain zap, 💊 heal a cell.'));
  const VT={basic:{r:15,hp:1,sp:38,c:'#6EE7B7',pts:10},fast:{r:10,hp:1,sp:80,c:'#FFD23F',pts:15},armor:{r:19,hp:3,sp:24,c:'#B9A7FF',pts:25},split:{r:16,hp:1,sp:34,c:'#FF9F43',pts:15},mini:{r:8,hp:1,sp:60,c:'#FF8FB1',pts:5},boss:{r:44,hp:22,sp:16,c:'#F2352A',pts:200}};
  let wave=Math.max(1,S.get('vir_w',1)),state='ready',vs=[],cells=[],pops=[],ups=[],rbc=[],toSpawn=0,spawnT=0,killed=0,need=0,score=0,combo=0,comboT=0,freeze=0,down=false,lastP=null,shake=0,bossOut=false;
  for(let i=0;i<22;i++)rbc.push({x:Math.random()*W,y:Math.random()*H,r:10+Math.random()*10,sp:14+Math.random()*20,a:Math.random()*6});
  function start(){vs=[];pops=[];ups=[];killed=0;combo=0;freeze=0;need=10+wave*5;toSpawn=need;spawnT=.5;bossOut=wave%5!==0;cells=[];const n=6;for(let i=0;i<n;i++){const a=i/n*Math.PI*2;cells.push({x:W/2+Math.cos(a)*170,y:H/2+Math.sin(a)*120,r:30,inf:0,dead:false,ph:Math.random()*6})}state='play'}
  function pickType(){const w=wave,r=Math.random();if(w>=3&&r<.18)return'fast';if(w>=4&&r<.3)return'armor';if(w>=2&&r<.45)return'split';return'basic'}
  function spawn(t,px,py){const T=VT[t];let x0=px,y0=py;if(x0==null){const e=Math.random()*4|0;x0=e===0?-20:e===1?W+20:Math.random()*W;y0=e===2?-20:e===3?H+20:Math.random()*H;if(e<2)y0=Math.random()*H}vs.push({t,x:x0,y:y0,r:T.r,hp:T.hp+(t==='boss'?wave:0),hp0:T.hp+(t==='boss'?wave:0),sp:T.sp*(1+wave*.04)*c.pick(.8,1,1.2),ph:Math.random()*6,tg:null,latch:0,hitCd:0,mt:0})}
  function kill(v,i){vs.splice(i,1);killed++;combo++;comboT=1.2;score+=VT[v.t].pts*(1+Math.floor(combo/5));pops.push({x:v.x,y:v.y,l:1,c:VT[v.t].c,r:v.r});beep(420+Math.min(combo,20)*40,.05,'triangle',.05);
    if(v.t==='split')for(let k=0;k<2;k++)spawn('mini',v.x+(k?12:-12),v.y);if(v.t==='boss'){shake=.5;for(let k=0;k<3;k++)ups.push(mkUp(v.x+(k-1)*40,v.y))}else if(Math.random()<.09)ups.push(mkUp(v.x,v.y))}
  function mkUp(x0,y0){return{x:x0,y:y0,k:pick(['freeze','bomb','zap','heal']),l:7}}
  function hitAt(px,py,rad){let hit=false;for(let i=vs.length-1;i>=0;i--){const v=vs[i];if(v.hitCd>0)continue;if(Math.hypot(v.x-px,v.y-py)<v.r+(rad||16)){v.hp--;v.hitCd=.12;hit=true;if(v.hp<=0)kill(v,i);else{beep(260,.04,'square',.04);v.x+=(v.x-px)*.15;v.y+=(v.y-py)*.15}}}return hit}
  function useUp(u){if(u.k==='freeze'){freeze=3.5;beep(1200,.3,'sine',.06)}else if(u.k==='bomb'){for(let i=vs.length-1;i>=0;i--)if(Math.hypot(vs[i].x-u.x,vs[i].y-u.y)<140){vs[i].hp-=3;if(vs[i].hp<=0)kill(vs[i],i)}pops.push({x:u.x,y:u.y,l:1,c:'#FF9F43',r:120});shake=.4;noise(.4,'lowpass',400,.3)}else if(u.k==='zap'){const tg=vs.slice().sort((a,b)=>Math.hypot(a.x-u.x,a.y-u.y)-Math.hypot(b.x-u.x,b.y-u.y)).slice(0,7);zaps=tg.map(v=>[u.x,u.y,v.x,v.y]);zapT=.3;tg.forEach(v=>{v.hp-=2;const i=vs.indexOf(v);if(v.hp<=0&&i>=0)kill(v,i)});noise(.25,'highpass',2000,.25)}else{const cc=cells.find(q=>q.dead)||cells.reduce((a,b)=>a.inf>b.inf?a:b);cc.dead=false;cc.inf=0;beep(880,.2,'triangle',.06)}}
  let zaps=[],zapT=0;
  function step(dt){rbc.forEach(b=>{b.x+=b.sp*dt;b.a+=dt;if(b.x>W+30)b.x=-30});if(state!=='play')return;comboT-=dt;if(comboT<=0)combo=0;freeze-=dt;zapT-=dt;shake=Math.max(0,shake-dt);
    spawnT-=dt;if(toSpawn>0&&spawnT<=0){spawnT=Math.max(.35,1.3-wave*.07)*c.pick(1.3,1,.8);toSpawn--;spawn(pickType());if(wave>2&&Math.random()<.3&&toSpawn>0){toSpawn--;spawn(pickType())}}
    if(!bossOut&&killed>=need*.5){bossOut=true;spawn('boss');need+=1}
    const alive=cells.filter(q=>!q.dead);
    vs.forEach(v=>{v.hitCd-=dt;v.ph+=dt*3;if(freeze>0)return;if(!v.tg||v.tg.dead)v.tg=alive.length?alive.reduce((a,b)=>Math.hypot(a.x-v.x,a.y-v.y)<Math.hypot(b.x-v.x,b.y-v.y)?a:b):null;const tg=v.tg;if(!tg)return;const dx=tg.x-v.x,dy=tg.y-v.y,d=Math.hypot(dx,dy);
      if(d>tg.r+v.r*.6){const wob=Math.sin(v.ph*1.3)*.5;v.x+=(dx/d*Math.cos(wob)-dy/d*Math.sin(wob))*v.sp*dt;v.y+=(dy/d*Math.cos(wob)+dx/d*Math.sin(wob))*v.sp*dt}else{tg.inf+=dt*(v.t==='boss'?.9:.35)*c.pick(.7,1,1.3);if(v.t==='boss'){v.mt-=dt;if(v.mt<=0){v.mt=2.2;spawn('mini',v.x,v.y)}}}});
    if(vs.some(v=>v.t==='boss')){for(const v of vs)if(v.t==='boss'){v.mt-=dt*.5;if(v.mt<=0){v.mt=3;spawn('mini',v.x,v.y)}}}
    cells.forEach(q=>{q.ph+=dt;if(!q.dead&&q.inf>=1){q.dead=true;shake=.3;noise(.5,'lowpass',250,.3);for(let k=0;k<3;k++)spawn('basic',q.x+(Math.random()-.5)*30,q.y+(Math.random()-.5)*30);vs.forEach(v=>{if(v.tg===q)v.tg=null})}else if(!q.dead)q.inf=Math.max(0,q.inf-dt*.03)});
    ups.forEach(u=>u.l-=dt);ups=ups.filter(u=>u.l>0);pops.forEach(p=>p.l-=dt*2);pops=pops.filter(p=>p.l>0);
    if(cells.every(q=>q.dead)){state='over';c.stat('Overrun on wave '+wave+' · score '+score)}
    else if(killed>=need&&toSpawn<=0&&!vs.some(v=>v.t==='boss')){state='won';vs=[];wave++;S.set('vir_w',wave);c.best(wave-1);[523,659,784].forEach((q,i)=>c.after(()=>beep(q,.15,'triangle',.06),i*100))}
    c.stat('Virus Attack · wave '+wave+' · score '+score)}
  const UPI={freeze:'❄️',bomb:'💥',zap:'⚡',heal:'💊'};
  function draw(){x.save();if(shake>0)x.translate((Math.random()-.5)*shake*20,(Math.random()-.5)*shake*20);const g=x.createLinearGradient(0,0,0,H);g.addColorStop(0,'#ffd9de');g.addColorStop(1,'#ffc2cb');x.fillStyle=g;x.fillRect(-20,-20,W+40,H+40);
    rbc.forEach(b=>{x.save();x.translate(b.x,b.y);x.scale(1,.6+.2*Math.sin(b.a));x.fillStyle='rgba(226,72,90,.35)';x.beginPath();x.arc(0,0,b.r,0,7);x.fill();x.fillStyle='rgba(180,40,60,.25)';x.beginPath();x.arc(0,0,b.r*.45,0,7);x.fill();x.restore()});
    if(freeze>0){x.fillStyle='rgba(127,200,248,.25)';x.fillRect(0,0,W,H)}
    cells.forEach(q=>{x.save();x.translate(q.x,q.y);const s=1+Math.sin(q.ph*2)*.04;x.scale(s,s);if(q.dead){x.fillStyle='#8c86a3';x.globalAlpha=.5}else{x.fillStyle=q.inf>0?'rgb('+(127+q.inf*80|0)+','+(200-q.inf*40|0)+','+(248-q.inf*150|0)+')':'#7FC8F8'}x.strokeStyle='#1D1A2F';x.lineWidth=3;x.beginPath();x.arc(0,0,q.r,0,7);x.fill();x.stroke();x.fillStyle='#2d6fd6';x.beginPath();x.arc(4,-3,q.r*.35,0,7);x.fill();if(!q.dead){x.fillStyle='#1D1A2F';x.beginPath();x.arc(-9,-6,3,0,7);x.arc(-1,-6,3,0,7);x.fill();x.beginPath();x.arc(-5,4,5,q.inf>.3?Math.PI:0,q.inf>.3?0:Math.PI);x.stroke()}if(q.inf>0&&!q.dead){x.strokeStyle='#F2352A';x.lineWidth=4;x.beginPath();x.arc(0,0,q.r+7,-Math.PI/2,-Math.PI/2+q.inf*Math.PI*2);x.stroke()}x.restore()});
    vs.forEach(v=>{const T=VT[v.t];x.save();x.translate(v.x,v.y);x.rotate(v.ph*.3);x.strokeStyle='#1D1A2F';x.lineWidth=2.5;const n=v.t==='boss'?14:8;for(let k=0;k<n;k++){const a=k/n*Math.PI*2;x.beginPath();x.moveTo(Math.cos(a)*v.r,Math.sin(a)*v.r);x.lineTo(Math.cos(a)*(v.r+7),Math.sin(a)*(v.r+7));x.stroke();x.fillStyle=T.c;x.beginPath();x.arc(Math.cos(a)*(v.r+8),Math.sin(a)*(v.r+8),v.t==='boss'?5:3,0,7);x.fill();x.stroke()}
      x.fillStyle=T.c;x.beginPath();x.arc(0,0,v.r*(1+Math.sin(v.ph)*.06),0,7);x.fill();x.stroke();if(v.t==='armor'){x.strokeStyle='#5A5470';x.lineWidth=4;for(let k=0;k<v.hp;k++){x.beginPath();x.arc(0,0,v.r-3-k*4,0,7);x.stroke()}}x.rotate(-v.ph*.3);x.fillStyle='#1D1A2F';const e=v.r*.3;x.beginPath();x.arc(-e,-e*.4,v.r*.14,0,7);x.arc(e,-e*.4,v.r*.14,0,7);x.fill();x.strokeStyle='#1D1A2F';x.lineWidth=2;x.beginPath();x.moveTo(-e*1.4,-e*1.1);x.lineTo(-e*.4,-e*.7);x.moveTo(e*1.4,-e*1.1);x.lineTo(e*.4,-e*.7);x.stroke();x.restore();
      if(v.hp0>1){x.fillStyle='#1D1A2F';x.fillRect(v.x-v.r,v.y-v.r-14,v.r*2,5);x.fillStyle='#F2352A';x.fillRect(v.x-v.r,v.y-v.r-14,v.r*2*v.hp/v.hp0,5)}});
    ups.forEach(u=>{x.globalAlpha=u.l<2?(Math.sin(u.l*20)>0?1:.4):1;x.fillStyle='#FFFDF6';x.strokeStyle='#1D1A2F';x.lineWidth=3;x.beginPath();x.arc(u.x,u.y,18,0,7);x.fill();x.stroke();x.font='20px sans-serif';x.textAlign='center';x.textBaseline='middle';x.fillText(UPI[u.k],u.x,u.y+1);x.globalAlpha=1});x.textBaseline='alphabetic';
    if(zapT>0){x.strokeStyle='#FFE27A';x.lineWidth=3;zaps.forEach(([a,b,c2,d])=>{x.beginPath();x.moveTo(a,b);for(let k=1;k<6;k++)x.lineTo(a+(c2-a)*k/6+(Math.random()-.5)*14,b+(d-b)*k/6+(Math.random()-.5)*14);x.lineTo(c2,d);x.stroke()})}
    pops.forEach(p=>{x.strokeStyle=p.c;x.globalAlpha=p.l;x.lineWidth=4;x.beginPath();x.arc(p.x,p.y,(1-p.l)*p.r*1.5+p.r*.5,0,7);x.stroke();x.globalAlpha=1});x.restore();
    x.fillStyle='#1D1A2F';x.font='800 15px "JetBrains Mono", monospace';x.textAlign='left';x.fillText('WAVE '+wave+' · '+Math.min(killed,need)+'/'+(need||0)+' · cells '+cells.filter(q=>!q.dead).length+'/'+cells.length+' · '+score+' pts',12,24);if(combo>=5){x.textAlign='right';x.fillStyle='#F2352A';x.fillText(combo+'× COMBO',W-12,24)}
    if(state==='ready')banner(x,W,H,'Virus Attack','Tap to start wave '+wave);if(state==='won')banner(x,W,H,'Wave cleared!','Tap for wave '+wave+(wave%5===0?' · BOSS WAVE':''));if(state==='over')banner(x,W,H,'Overrun!','Tap to retry wave '+wave)}
  function press(p){for(let i=ups.length-1;i>=0;i--){const u=ups[i];if(Math.hypot(u.x-p.x,u.y-p.y)<28){ups.splice(i,1);useUp(u);return}}hitAt(p.x,p.y,18)}
  c.on(cv,'contextmenu',e=>e.preventDefault());c.on(cv,'pointerdown',e=>{e.preventDefault();if(state!=='play'){start();return}down=true;const p=canvasPos(cv,e);lastP=p;press(p)});
  c.on(cv,'pointermove',e=>{if(!down||state!=='play')return;const p=canvasPos(cv,e);const d=Math.hypot(p.x-lastP.x,p.y-lastP.y),n=Math.ceil(d/10);for(let k=1;k<=n;k++)hitAt(lastP.x+(p.x-lastP.x)*k/n,lastP.y+(p.y-lastP.y)*k/n,12);lastP=p});['pointerup','pointercancel','pointerleave'].forEach(ev=>c.on(cv,ev,()=>down=false));
  c.loop(dt=>{step(Math.min(.033,dt/1000));draw()})}});
