/* ================= MOONBLADE: first-person night sword fighting ================= */
const MB_ART=['tex:forest','tex:mud','tex:grass','tex:planks','tex:darkwood','tex:cobble','tex:stonewall','tex:roof','tex:bamboo','tex:rock','img:fol_bamboo.png','img:fol_maple.png','img:fol_broad.png','hdr:night','glb:katana','glb:lantern','glb:barrel','glb:crate','glb:katanastand','glb:paperlamp','chr:readyplayer.me','chr:Soldier','chr:Michelle'];
function moonblade(root,c){return withArt(root,c,MB_ART,()=>{
const st3=Stage3D(root,c,{lock:true,dragLook:true,fov:74,far:500,fireLabel:'SLASH',altLabel:'BLOCK',jumpLabel:'DODGE'});
const K=bigKit(st3,c,{id:'mb',exposure:1.2});
const{T,V3,PI,rnd,clamp,lerp,pick,lin,angDiff,scene,camera,input,wrap,mat,T_,ctex,Merger,addBox,H,SFX,snd}=K;const TWO=PI*2;scene.add(camera);wrap.classList.add('mbg');
if(!document.getElementById('mb-css')){const s2=document.createElement('style');s2.id='mb-css';s2.textContent=`.mbg .bk-bars{display:none}.mbg .bk-note{top:auto;bottom:110px}.mb-hud{position:absolute;left:16px;bottom:44px;width:min(360px,45%);pointer-events:none}.mb-bar{height:8px;border-radius:4px;background:rgba(0,0,0,.55);margin-top:5px;overflow:hidden;border:1px solid rgba(255,255,255,.2)}.mb-bar i{display:block;height:100%}
.mb-post{position:absolute;left:50%;transform:translateX(-50%);height:7px;border-radius:4px;background:rgba(0,0,0,.4);overflow:hidden}.mb-post i{position:absolute;top:0;bottom:0;background:linear-gradient(90deg,#ffb030,#ff5020)}
.mb-eb{position:absolute;left:50%;top:14px;transform:translateX(-50%);width:min(520px,70%);text-align:center;font:800 14px Georgia,serif;color:#f0e0c0;text-shadow:0 2px 6px #000;pointer-events:none;display:none}.mb-eb .mb-bar i{background:linear-gradient(90deg,#8a1a1a,#d83a2a)}
.mb-info{position:absolute;right:16px;top:14px;text-align:right;font:700 13px Georgia,serif;color:#f0e0c0;text-shadow:0 2px 6px #000;pointer-events:none}.mb-gourd{position:absolute;left:16px;bottom:16px;font:800 15px system-ui;color:#fff;text-shadow:0 2px 6px #000;pointer-events:none}
.mb-peril{position:absolute;left:50%;top:38%;transform:translate(-50%,-50%);font:900 46px serif;color:#ff2020;text-shadow:0 0 18px #f00;opacity:0;pointer-events:none;transition:opacity .08s}
.mb-db{position:absolute;left:50%;top:58%;transform:translateX(-50%);font:900 16px system-ui;color:#fff;background:rgba(160,20,20,.8);padding:5px 12px;border-radius:6px;display:none;pointer-events:none}
.mb-card h2{font-family:Georgia,serif}.mb-up{display:flex;justify-content:space-between;align-items:center;gap:10px;padding:6px 8px;border-radius:8px;background:rgba(255,255,255,.05);margin:4px 0;font:600 13px system-ui}`;document.head.append(s2)}
const HUD={};(()=>{const w=el('div',{class:'mb-hud'});const bar=(col)=>{const b=el('div',{class:'mb-bar'});const i=el('i');i.style.background=col;b.append(i);w.append(b);return i};HUD.post=el('div',{class:'mb-post',style:'width:min(260px,40%);top:60%'});HUD.postI=el('i');HUD.post.append(HUD.postI);HUD.hp=bar('linear-gradient(90deg,#3ac85a,#7ae07a)');HUD.sp=bar('linear-gradient(90deg,#4a8aff,#b0d0ff)');
  HUD.eb=el('div',{class:'mb-eb'});HUD.ebN=el('div');HUD.ebB=el('div',{class:'mb-bar'});HUD.ebI=el('i');HUD.ebB.append(HUD.ebI);HUD.ebP=el('div',{class:'mb-post',style:'position:relative;width:60%;margin:5px auto 0;left:auto;transform:none'});HUD.ebPI=el('i');HUD.ebP.append(HUD.ebPI);HUD.eb.append(HUD.ebN,HUD.ebB,HUD.ebP);
  HUD.info=el('div',{class:'mb-info'});HUD.gourd=el('div',{class:'mb-gourd'});HUD.peril=el('div',{class:'mb-peril'},'危');HUD.db=el('div',{class:'mb-db'},'DEATHBLOW — click');K.hud.append(w,HUD.post,HUD.eb,HUD.info,HUD.gourd,HUD.peril,HUD.db);K.H.map.style.display='none';K.H.tr.style.display='none'})();
/* ---------- chapters ---------- */
const CH=[{n:'Ashes of the Village',th:'village',intro:'The Shadow Clan burned Master Ishida\'s village under the new moon. Some of them stayed to loot what was left.',waves:[['bandit','bandit'],['bandit','bandit','bandit']],boss:{k:'brute',n:'Kuro the Butcher',hp:320,post:180},tut:1},
  {n:'Bamboo Whispers',th:'bamboo',intro:'Kuro\'s last words named the bamboo grove. The wind there carries footsteps that don\'t belong to animals.',waves:[['ninja','bandit'],['ninja','ninja','bandit']],boss:{k:'ninja',n:'The Twin Shadows',hp:220,post:140,twin:1}},
  {n:'The Red Bridge',th:'bridge',intro:'The only road to the temple crosses the red bridge. The clan\'s spearmen hold it.',waves:[['spear','spear'],['archer','spear','bandit']],boss:{k:'spear',n:'Genda of the Long Spear',hp:360,post:220}},
  {n:'Temple of Lanterns',th:'temple',intro:'The monks are gone. Something wearing their robes waits among the lanterns.',waves:[['bandit','spear','ninja'],['brute','bandit','archer']],boss:{k:'spear',n:'The Iron Staff Monk',hp:420,post:260,staff:1}},
  {n:'Rain on the Fields',th:'fields',intro:'Rain hides the sound of arrows. The ronin Hayate hunts you through the flooded rice paddies.',waves:[['archer','archer','ninja'],['ninja','bandit','bandit','archer']],boss:{k:'bandit',n:'Hayate the Wandering Blade',hp:420,post:300,duel:1}},
  {n:'The Burning Pagoda',th:'pagoda',intro:'They set the pagoda alight to draw you out. The Oni waits in the flames.',waves:[['brute','bandit','bandit'],['brute','ninja','spear']],boss:{k:'brute',n:'The Red Oni',hp:560,post:320,oni:1}},
  {n:'Castle Gate',th:'castle',intro:'General Takeda guards the gate of Kagemura Castle with his finest samurai.',waves:[['spear','bandit','archer','bandit'],['brute','spear','ninja','archer']],boss:{k:'bandit',n:'General Takeda',hp:520,post:340,duel:1,armor:1}},
  {n:'Blood Moon',th:'moon',intro:'On the tower under the blood moon, Lord Shade, who killed your master, draws his blade.',waves:[],boss:{k:'bandit',n:'Lord Shade',hp:760,post:400,duel:1,final:1}}];
/* ---------- world ---------- */
let ARENA=null;const AR={r:22,rect:null};
const mStone=K.pbr('stonewall',0xb8b0a8)||mat('stone','#8a8680',{map:'rock'}),mWoodD=K.pbr('darkwood',0xc8b8a8)||mat('woodd','#5a3a24',{map:'wood'}),mWoodR=mat('woodr','#a8281e',{map:'wood'}),mRoofT=mat('rooft','#2a2a30',{map:'roof'}),mThatch=mat('thatch','#8a7a4a',{map:'dirt'}),mPaper=new T.MeshStandardMaterial({color:lin(0xf0e0c0),emissive:lin(0xffb060),emissiveIntensity:1.1,roughness:.9,side:T.DoubleSide});
const LIGHTS=[],FIRESP=[];
function lantern(g,x,y,z,hang){const l=new T.Mesh(new T.CylinderGeometry(.22,.22,.5,10),mPaper);l.position.set(x,y,z);g.add(l);const cap=new T.Mesh(new T.CylinderGeometry(.25,.25,.06,10),mWoodD);cap.position.set(x,y+.27,z);g.add(cap);if(!hang){const p=new T.Mesh(new T.CylinderGeometry(.05,.06,y-.25,6),mWoodD);p.position.set(x,(y-.25)/2,z);g.add(p)}if(LIGHTS.length<10){const L=new T.PointLight(0xffa050,2.4,16,1.6);L.position.set(x,y,z);g.add(L);LIGHTS.push(L)}}
function house(g,x,z,ry,burnt){const h=new T.Group();h.position.set(x,0,z);h.rotation.y=ry;const b=new T.Mesh(new T.BoxGeometry(6,3,5),burnt?mat('burnw','#2a2420'):mWoodD);b.position.y=1.5;b.castShadow=true;h.add(b);const rf=new T.Mesh(new T.ConeGeometry(5.2,2.4,4),burnt?mat('burnr','#1a1614'):mThatch);rf.rotation.y=PI/4;rf.scale.set(1.2,1,1);rf.position.y=4.2;rf.castShadow=true;h.add(rf);const dr=new T.Mesh(new T.PlaneGeometry(1.4,2),mPaper);dr.position.set(0,1.1,2.51);h.add(dr);g.add(h);return h}
function torii(g,x,z,ry){const t=new T.Group();t.position.set(x,0,z);t.rotation.y=ry;for(const s of[-1,1]){const p=new T.Mesh(new T.CylinderGeometry(.22,.26,5,10),mWoodR);p.position.set(s*2.2,2.5,0);p.castShadow=true;t.add(p)}const top=new T.Mesh(new T.BoxGeometry(6.4,.35,.5),mWoodR);top.position.y=5.1;t.add(top);const top2=new T.Mesh(new T.BoxGeometry(5.6,.25,.35),mWoodR);top2.position.y=4.3;t.add(top2);const cap=new T.Mesh(new T.BoxGeometry(7,.2,.7),mat('blk','#1a1a1a'));cap.position.y=5.35;t.add(cap);g.add(t)}
function pagoda(g,x,z,burning){const p=new T.Group();p.position.set(x,0,z);for(let i=0;i<4;i++){const s=5-i*.8;const b=new T.Mesh(new T.BoxGeometry(s,2.4,s),mWoodR);b.position.y=1.2+i*3;b.castShadow=true;p.add(b);const r=new T.Mesh(new T.ConeGeometry(s*.95,1.2,4),mRoofT);r.rotation.y=PI/4;r.position.y=3+i*3;p.add(r)}const sp=new T.Mesh(new T.CylinderGeometry(.08,.12,3,6),mat('gold2','#c8a040',{metalness:.8}));sp.position.y=14;p.add(sp);g.add(p);if(burning)for(let i=0;i<6;i++)FIRESP.push(new V3(x+rnd(-2.5,2.5),rnd(1,11),z+rnd(-2.5,2.5)))}
function buildArena(ch){if(ARENA){scene.remove(ARENA);ARENA.traverse(o=>{if(o.geometry)o.geometry.dispose()})}ARENA=new T.Group();scene.add(ARENA);K.clearWorld();LIGHTS.length=0;FIRESP.length=0;AR.rect=null;const th=ch.th,g=ARENA;
  const gtex={village:'dirt',bamboo:'grass',bridge:'wood',temple:'rock',fields:'grass',pagoda:'dirt',castle:'rock',moon:'rock'}[th];const rg={village:'mud',bamboo:'forest',bridge:'planks',temple:'cobble',fields:'mud',pagoda:'mud',castle:'cobble',moon:'stonewall'}[th],rep=(k,s)=>{const t0=K.realTex(k,s);if(!t0)return null;const t=t0.clone();t.needsUpdate=true;t.repeat.set(40,40);return t};
  const rgc=rep(rg,'c')||(K.realTex(rg==='forest'?'grass':rg,'c')?rep(rg==='forest'?'grass':rg,'c'):null);
  const ground=new T.Mesh(new T.CircleGeometry(80,48),rgc?new T.MeshStandardMaterial({map:rgc,normalMap:rep(rg,'n'),roughnessMap:rep(rg,'r'),color:lin(th==='moon'?0x8a7a7a:0xc8c0b8),roughness:1}):new T.MeshStandardMaterial({map:(()=>{const t=T_(gtex).clone();t.needsUpdate=true;t.repeat.set(30,30);return t})(),color:lin(th==='moon'?0x6a5a5a:th==='temple'?0x9a9690:0x8a8a7a),roughness:.95}));ground.rotation.x=-PI/2;ground.receiveShadow=true;g.add(ground);
  const ring=(n,r,fn)=>{for(let i=0;i<n;i++){const a=i/n*TWO+rnd(-.05,.05);fn(Math.cos(a)*r,Math.sin(a)*r,a)}};
  if(th==='village'||th==='pagoda'){ring(9,27,(x,z,a)=>house(g,x,z,-a+PI/2,Math.random()<.6));ring(7,23,(x,z)=>{if(Math.random()<.6)FIRESP.push(new V3(x,rnd(1,4),z))});ring(6,18,(x,z)=>lantern(g,x,1.8,z));if(th==='pagoda')pagoda(g,0,-30,true)}
  if(th==='bamboo'){const n=1400;const bg=new T.CylinderGeometry(.07,.08,12,6);bg.translate(0,6,0);const bmR=K.pbr('bamboo',0xb8c890);const im=new T.InstancedMesh(bg,bmR||new T.MeshStandardMaterial({color:lin(0x6a8a3a),roughness:.7}),n);const lmB=K.leafMat('bamboo',0xa8c890);const lim=lmB?new T.InstancedMesh(K.crownGeo(1.6,4.5,10,7.5,5),lmB,n):null;const o3=new T.Object3D();let k=0;for(let i=0;i<n*3&&k<n;i++){const a=rnd(0,TWO),r=rnd(21,60);o3.position.set(Math.cos(a)*r,0,Math.sin(a)*r);o3.rotation.set(rnd(-.06,.06),rnd(0,6),rnd(-.06,.06));o3.scale.set(1,rnd(.8,1.3),1);o3.updateMatrix();im.setMatrixAt(k,o3.matrix);if(lim)lim.setMatrixAt(k,o3.matrix);k++}im.count=k;im.castShadow=true;g.add(im);if(lim){lim.count=k;lim.castShadow=true;lim.customDepthMaterial=lmB.userData.depth;g.add(lim)}ring(5,17,(x,z)=>lantern(g,x,1.4,z))}
  if(th==='bridge'){AR.rect=[5,24];const water=new T.Mesh(new T.PlaneGeometry(300,300),new T.MeshStandardMaterial({color:lin(0x0a1a2a),roughness:.1,metalness:.3}));water.rotation.x=-PI/2;water.position.y=-4;g.add(water);ground.visible=false;const deck=new T.Mesh(new T.BoxGeometry(10,.5,50),mWoodD);deck.position.y=-.25;deck.receiveShadow=true;g.add(deck);for(const s of[-1,1]){const rail=new T.Mesh(new T.BoxGeometry(.2,1.1,50),mWoodR);rail.position.set(s*5,.55,0);g.add(rail);for(let z=-24;z<=24;z+=4){const p=new T.Mesh(new T.CylinderGeometry(.12,.12,1.4,8),mWoodR);p.position.set(s*5,.7,z);g.add(p)}for(let z=-20;z<=20;z+=10)lantern(g,s*5,1.6,z,true)}for(const s of[-1,1]){const bank=new T.Mesh(new T.BoxGeometry(80,4,30),mat('bank','#3a4a2a',{map:'grass'}));bank.position.set(0,-2,s*40);g.add(bank)}torii(g,0,-26,0);torii(g,0,26,0)}
  if(th==='temple'){const hall=new T.Group();const b=new T.Mesh(new T.BoxGeometry(18,6,10),mWoodD);b.position.y=3;hall.add(b);const r=new T.Mesh(new T.BoxGeometry(22,1,14),mRoofT);r.position.y=6.5;hall.add(r);hall.position.set(0,0,-30);g.add(hall);torii(g,0,24,0);ring(12,19,(x,z)=>lantern(g,x,1.6,z));const lmS=K.leafMat('maple',0xffb8d0);const tree=lmS?new T.Mesh(K.crownGeo(4.5,5,60,0,21),lmS):new T.Mesh(new T.IcosahedronGeometry(4,1),new T.MeshStandardMaterial({color:lin(0xe890b0),flatShading:true}));tree.position.set(14,lmS?4.5:7,-18);if(lmS){tree.customDepthMaterial=lmS.userData.depth;tree.castShadow=true}g.add(tree);const tr=new T.Mesh(new T.CylinderGeometry(.4,.6,6,8),mWoodD);tr.position.set(14,3,-18);g.add(tr)}
  if(th==='fields'){for(let i=0;i<30;i++){const w=new T.Mesh(new T.PlaneGeometry(8,8),new T.MeshStandardMaterial({color:lin(0x2a3a3a),roughness:.05,metalness:.4}));w.rotation.x=-PI/2;const a=rnd(0,TWO),r=rnd(24,60);w.position.set(Math.cos(a)*r,.03,Math.sin(a)*r);g.add(w)}ring(4,26,(x,z,a)=>house(g,x,z,-a+PI/2,false));ring(6,18,(x,z)=>lantern(g,x,1.6,z))}
  if(th==='castle'){for(let i=0;i<24;i++){const a=i/24*TWO;if(Math.abs(a-PI/2)<.25)continue;const w=new T.Mesh(new T.BoxGeometry(6.2,7,2.5),mStone);w.position.set(Math.cos(a)*26,3.5,Math.sin(a)*26);w.rotation.y=-a+PI/2;w.castShadow=true;g.add(w)}const gate=new T.Mesh(new T.BoxGeometry(10,9,3),mWoodD);gate.position.set(0,4.5,-28);g.add(gate);const roof=new T.Mesh(new T.ConeGeometry(9,4,4),mRoofT);roof.rotation.y=PI/4;roof.position.set(0,11,-28);g.add(roof);ring(10,20,(x,z)=>lantern(g,x,1.8,z));ring(6,24,(x,z)=>FIRESP.push(new V3(x,2.2,z)))}
  if(th==='moon'){ground.material.color=lin(0x4a3a3a);const edge=new T.Mesh(new T.CylinderGeometry(23,20,40,40,1,true),mStone);edge.position.y=-20;g.add(edge);ring(8,20,(x,z)=>lantern(g,x,1.4,z));for(let i=0;i<4;i++){const p=new T.Mesh(new T.CylinderGeometry(.35,.4,6,8),mWoodR);const a=i/4*TWO+PI/4;p.position.set(Math.cos(a)*21,3,Math.sin(a)*21);g.add(p)}}
  if(th!=='bridge'){for(let i=0;i<36;i++){const a=i/36*TWO;addBox(Math.cos(a)*AR.r-1.5,0,Math.sin(a)*AR.r-1.5,Math.cos(a)*AR.r+1.5,4,Math.sin(a)*AR.r+1.5,'bld')}}else{addBox(-6,0,-26,-5,4,26,'bld');addBox(5,0,-26,6,4,26,'bld');addBox(-6,0,-26,6,4,-25,'bld');addBox(-6,0,25,6,4,26,'bld')}
  // sky
  if(K.sky)scene.remove(K.sky);const red=th==='moon';K.sky=K.skyDome({top:red?0x1a0406:0x04060e,hor:red?0x4a1010:th==='pagoda'||th==='village'?0x2a1410:0x0e1424,bot:0x050505,stars:red?.4:1,moon:1,sun:[-.4,.35,-.8],sunC:red?0xff3020:0xe8f0ff});
  if(!K.moonS){K.moonS=new T.Sprite(new T.SpriteMaterial({map:T_('glow'),color:0xffffff,fog:false,depthWrite:false}));scene.add(K.moonS)}K.moonS.material.color.set(red?0xff3a2a:0xdde8ff);K.moonS.scale.setScalar(red?90:55);K.moonS.position.set(-160,140,-320);
  if(!K.lt)K.lt=K.sunLight({size:30,int:.9,hemi:.55,col:0x9ab0e0,dir:[-.4,.7,-.6],sky:0x3a4a7a,gnd:0x1a1410});K.lt.sun.color.set(red?0xff6a5a:0x9ab0e0).convertSRGBToLinear();K.lt.sun.intensity=red?1.1:.95;K.lt.hemi.intensity=.55;
  scene.fog=new T.FogExp2(lin(red?0x2a0a0a:th==='fields'?0x1a2028:0x0a0e18),th==='fields'?.03:.02);K.renderer.toneMappingExposure=1.55;if(K.env('night',{int:red?.25:.4}))K.lt.hemi.intensity=.35;W.rain=th==='fields'?1:0;W.petals=th==='temple'||th==='moon'}
const W={rain:0,petals:false};
/* ---------- persistent progress ---------- */
const PROG=Object.assign({ch:0,pts:0,xp:0,up:{hp:0,post:0,dmg:0,gourd:0,spirit:0},best:{}},K.SAVE.get('prog',{}));const saveProg=()=>{K.SAVE.set('prog',PROG);c.best(PROG.ch*1000+PROG.xp)};
const UPG={hp:{n:'Vitality',d:'+25 max health',max:4},post:{n:'Iron Stance',d:'+25 max posture',max:4},dmg:{n:'Honed Edge',d:'+15% damage',max:4},gourd:{n:'Healing Gourd',d:'+1 gourd charge',max:3},spirit:{n:'Moon Focus',d:'Spirit meter fills 30% faster',max:3}};
/* ---------- player ---------- */
const P={pos:new V3(),yaw:0,pitch:0,vy:0,onG:true,hp:100,maxHp:100,post:0,maxPost:100,spirit:0,stam:100,gourd:3,gourdMax:3,atk:null,combo:0,block:false,blockT:9,dodge:0,dodgeV:new V3(),iframe:0,stun:0,dead:false,heal:0,lock:null,hold:0,swipe:{x:0,y:0},hits:0,parries:0,dmgTaken:0};
const dmgMul=()=>1+PROG.up.dmg*.15;
function resetPlayer(){P.maxHp=100+PROG.up.hp*25;P.maxPost=100+PROG.up.post*25;P.gourdMax=3+PROG.up.gourd;Object.assign(P,{hp:P.maxHp,post:0,spirit:0,stam:100,gourd:P.gourdMax,atk:null,combo:0,block:false,blockT:9,dodge:0,iframe:0,stun:0,dead:false,heal:0,lock:null,hits:0,parries:0,dmgTaken:0,vy:0});P.pos.set(0,0,AR.rect?18:12);P.yaw=0;P.pitch=0}
/* viewmodel: katana */
const VM=new T.Group();camera.add(VM);const SW=new T.Group();VM.add(SW);(()=>{const blade=new T.Mesh(new T.BoxGeometry(.012,.04,.95),new T.MeshStandardMaterial({color:lin(0xe8eef4),metalness:1,roughness:.12,emissive:lin(0x203050),emissiveIntensity:.3}));blade.position.z=-.62;SW.add(blade);const edge=new T.Mesh(new T.BoxGeometry(.004,.012,.95),new T.MeshBasicMaterial({color:0xffffff}));edge.position.set(0,.022,-.62);SW.add(edge);const tsuba=new T.Mesh(new T.CylinderGeometry(.06,.06,.012,12),mat('tsuba','#c8a040',{metalness:.8,roughness:.3}));tsuba.rotation.x=PI/2;tsuba.position.z=-.13;SW.add(tsuba);const hilt=new T.Mesh(new T.CylinderGeometry(.018,.018,.26,8),mat('wrap2','#1a1a24'));hilt.rotation.x=PI/2;SW.add(hilt);
  const hm=mat('hand','#c89878',{roughness:.7}),sl=mat('sleeve2','#1e2230');for(const z of[.06,-.06]){const h=new T.Mesh(new T.SphereGeometry(.045,8,6),hm);h.scale.set(1,1.2,1.3);h.position.set(0,-.01,z);SW.add(h)}const arm=new T.Mesh(new T.CylinderGeometry(.05,.06,.5,8),sl);arm.rotation.x=PI/2;arm.position.set(.03,-.05,.3);SW.add(arm);SW.userData.blade=blade;
  // scanned katana (Poly Haven) in place of the box blade when loaded
  const rk=K.propAlong('katana',1.15,.22);if(rk){rk.rotation.y=PI;rk.traverse(m=>{if(m.isMesh)m.castShadow=false});SW.add(rk);[blade,edge,tsuba,hilt].forEach(m=>m.visible=false)}})();
const trail=new T.Mesh(new T.PlaneGeometry(1,1),new T.MeshBasicMaterial({color:0xaad8ff,transparent:true,opacity:0,blending:T.AdditiveBlending,depthWrite:false,side:T.DoubleSide}));VM.add(trail);
/* sword poses: [x,y,z,rx,ry,rz] */
const POSE={idle:[.28,-.3,-.45,.25,-.25,-.45],block:[0,-.12,-.5,.05,-1.4,-1.5],slashR0:[.45,-.02,-.4,.5,-.9,-1.2],slashR1:[-.35,-.38,-.5,-.3,.5,-2.2],slashL0:[-.4,-.04,-.42,.5,.9,1.1],slashL1:[.4,-.36,-.5,-.3,-.5,2.1],overhead0:[.05,.2,-.3,1.3,0,-.1],overhead1:[.02,-.45,-.55,-.7,0,-.1],thrust0:[.2,-.25,-.25,.05,0,-.3],thrust1:[.05,-.18,-.8,.05,0,-.3],heavy0:[.5,.15,-.2,.9,-1,-1.6],heavy1:[-.45,-.42,-.55,-.4,.7,-2.4],kick0:[.3,-.35,-.4,.2,-.3,-.5],kick1:[.3,-.35,-.4,.2,-.3,-.5],moon0:[.6,-.1,-.3,.2,-1.6,-1.6],moon1:[-.6,-.1,-.3,.2,1.6,-1.6],db0:[.1,.25,-.3,1.4,0,0],db1:[0,-.3,-.9,.1,0,0]};
const cur=[.28,-.3,-.45,.25,-.25,-.45];
function swordTo(p,k){for(let i=0;i<6;i++)cur[i]+=(p[i]-cur[i])*k;SW.position.set(cur[0],cur[1],cur[2]);SW.rotation.set(cur[3],cur[4],cur[5],'YXZ')}
const ATK={light:{dur:.42,hit:.2,dmg:18,post:12,st:9,reach:2.7},heavy:{dur:.78,hit:.5,dmg:42,post:34,st:18,reach:2.9},kick:{dur:.45,hit:.22,dmg:4,post:26,st:10,reach:1.9},moon:{dur:.7,hit:.35,dmg:60,post:70,st:0,reach:4.3},db:{dur:.9,hit:.5,dmg:0,post:0,st:0,reach:3.2}};
function startAtk(kind,dir){if(P.atk||P.stun>0||P.heal>0)return;const A=ATK[kind];if(P.stam<A.st*.5)return;P.stam-=A.st;let pose=dir;if(kind==='light'){if(!pose){pose=['slashR','slashL','overhead'][P.combo%3];P.combo++}}else pose=kind;P.atk={kind,pose,t:0,hitDone:false,A};K.SFX.swing(P.pos);if(kind==='moon'){P.spirit=0;K.snd({tone:300,tone2:900,tdur:.6,wave:'sine',tvol:.5,vol:.35})}}
function atkHit(){const a=P.atk,A=a.A;const f=new V3(-Math.sin(P.yaw),0,-Math.cos(P.yaw));let any=false;
  for(const e of EN){if(e.dead)continue;const to=e.pos.clone().sub(P.pos).setY(0);const d=to.length();if(d>A.reach+e.r)continue;if(a.kind!=='moon'&&to.normalize().dot(f)<.35)continue;any=true;
    if(a.kind==='db'){deathblow(e);continue}
    const blocked=a.kind!=='moon'&&e.canBlock&&e.guardUp&&!e.broken&&e.stun<=0&&Math.random()<e.guard*(a.kind==='heavy'?.5:1)&&!e.atk;
    const dm=A.dmg*dmgMul(),pm=A.post*dmgMul();if(blocked){e.post+=pm*(a.kind==='heavy'?1.4:1);if(a.kind==='heavy')hurtE(e,dm*.25,false);sparks(e,1);K.SFX.clang(e.pos);e.blockFx=.2;if(a.kind==='light'){P.atk.recoil=1}}else{if(a.kind==='kick'){e.post+=pm;e.stun=Math.max(e.stun,.5);e.atk=null;K.SFX.punch(e.pos);e.pos.addScaledVector(f,1.2)}else{hurtE(e,dm,true);e.post+=pm*.5;P.spirit=Math.min(100,P.spirit+(6+(a.kind==='heavy'?8:0))*(1+PROG.up.spirit*.3))}}
    if(e.post>=e.maxPost&&!e.broken){e.broken=2.6;e.atk=null;e.stun=2.6;K.snd({tone:180,tone2:90,tdur:.4,wave:'square',tvol:.3,vol:.3});K.note('Posture broken — strike for a deathblow!','#ff6a4a')}}
  if(!any)K.snd({noise:1,ft:'bandpass',f:1200,q:1,dur:.15,vol:.12})}
function hurtE(e,d,flinch){e.hp-=d;P.hits++;K.burst(e.pos.x,e.pos.y+1.3*e.sc,e.pos.z,14,4,.5,.07,.03,0x9a0a0a,0x3a0000,1,9,1);K.SFX.slash(e.pos);K.hitmark(e.hp<=0);if(flinch&&!e.superArmor){e.act='hit';e.actK=0;if(!e.atk||e.atk.t<e.atk.windup*.6)e.atk=null;e.stun=Math.max(e.stun,.25)}if(e.hp<=0)killE(e)}
function deathblow(e){if(e.boss&&e.hp>e.maxHp*.3){e.hp-=e.maxHp*.34;e.post=0;e.broken=0;e.stun=1;K.banner('DEATHBLOW','','#ff3a2a',1200);K.CAM.shake=.6;hurtE(e,0,true);slowmo=.6;return}K.banner('DEATHBLOW','','#ff3a2a',1200);slowmo=.7;K.CAM.shake=.7;e.hp=0;killE(e,true);K.burst(e.pos.x,e.pos.y+1.3,e.pos.z,50,6,.8,.08,.04,0xaa0a0a,0x2a0000,1,9,1);P.spirit=Math.min(100,P.spirit+25)}
function sparks(e,k){const p=e.pos.clone().add(new V3(0,1.3*e.sc,0)).lerp(camera.position,.35);K.burst(p.x,p.y,p.z,14*k,6,.25,.05,.02,0xfff0a0,0xff8020,1,12,1);K.flash(p,0xffd080,6*k,6,.08)}
let slowmo=0;
/* ================= enemies ================= */
const EN=[],PROJ=[];
const ET={bandit:{hp:70,post:70,spd:3.6,dmg:14,reach:2.4,guard:.35,wind:.5,look:()=>({shirt:pick([0x5a4a3a,0x3a3a42,0x6a5a4a]),jacket:pick([0x2a2a30,0x4a3a2a]),pants:0x2a2a2a,skin:pick([0xd8a888,0xc89878]),hair:0x1a1008,hairStyle:pick(['long','s'])}),w:'katana'},
  ninja:{hp:55,post:55,spd:5.2,dmg:12,reach:2.2,guard:.5,wind:.38,look:()=>({shirt:0x141418,pants:0x141418,skin:0xd8a888,hair:0x0a0a0a,mask:0x141418,hairStyle:'s'}),w:'katana',kunai:1},
  spear:{hp:85,post:80,spd:3.2,dmg:16,reach:3.4,guard:.45,wind:.55,look:()=>({shirt:0x6a1a1a,vest:0x1a1a1a,pants:0x2a1a1a,skin:0xc89878,hair:0x1a1008,hat:0x2a2420}),w:'spear'},
  brute:{hp:170,post:120,spd:2.8,dmg:26,reach:2.9,guard:.1,wind:.8,look:()=>({shirt:0x6a4a3a,pants:0x3a2a1a,skin:0xa87858,hair:0x1a1008,hairStyle:'bald',bulk:1.5}),w:'club',sc:1.25,armor:1},
  archer:{hp:50,post:50,spd:3.4,dmg:10,reach:1.8,guard:.1,wind:.5,look:()=>({shirt:0x4a5a3a,pants:0x3a3a2a,skin:0xd8a888,hair:0x1a1008,hat:0x8a7a4a}),w:'katana',bow:1}};
const BLOOKS={'Kuro the Butcher':{shirt:0x3a1a1a,pants:0x1a1a1a,skin:0xa87858,hairStyle:'bald',bulk:1.7},'The Twin Shadows':{shirt:0x2a0a2a,pants:0x2a0a2a,skin:0xd8a888,mask:0x6a0a2a},'Genda of the Long Spear':{shirt:0x8a1a1a,vest:0xc8a040,pants:0x1a1a1a,skin:0xc89878,hat:0x1a1a1a},'The Iron Staff Monk':{shirt:0xd87a1a,pants:0xd87a1a,skin:0xc89878,hairStyle:'bald'},'Hayate the Wandering Blade':{shirt:0x3a4a6a,jacket:0x2a3a5a,pants:0x2a2a3a,skin:0xd8a888,hair:0x1a1008,hairStyle:'long',hat:0x8a7a4a},'The Red Oni':{shirt:0xa81a1a,pants:0x3a1a1a,skin:0xc8201a,mask:0xc8201a,bulk:1.8,hairStyle:'long',hair:0xe8e8e8},'General Takeda':{shirt:0x1a1a1a,vest:0x8a1a1a,jacket:0x1a1a1a,pants:0x1a1a1a,skin:0xc89878,hat:0x8a1a1a,gloves:0x1a1a1a},'Lord Shade':{shirt:0x0a0a0e,jacket:0x0a0a0e,pants:0x0a0a0e,skin:0xe8d8c8,hair:0xe8e8e8,hairStyle:'long',mask:0x2a0a0a,gloves:0x0a0a0e}};
function weaponMesh(w,sc){if(w==='spear'){const g=new T.Group();const p=new T.Mesh(new T.CylinderGeometry(.025,.025,2.4,6),mWoodD);p.rotation.x=PI/2;p.position.z=.5;g.add(p);const tip=new T.Mesh(new T.ConeGeometry(.04,.3,4),mat('steel3','#c8ccd4',{metalness:.9,roughness:.2}));tip.rotation.x=PI/2;tip.position.z=1.8;g.add(tip);g.rotation.x=-PI/2;g.position.y=-.05;return g}if(w==='club'){const g=K.gunMesh('bat');g.scale.setScalar(1.6);return g}return K.gunMesh('katana')}
function spawnE(kind,x,z,o){o=o||{};const S=ET[kind];const sc=(o.sc||S.sc||1);const lk=Object.assign({},o.look||S.look());if(!lk.model)lk.model=kind==='brute'||(o.boss&&/Takeda|Shade|Oni/.test(o.name||''))?'soldier':'rpm';const ch=K.human(Object.assign({scale:sc},lk));scene.add(ch.g);K.holdItem(ch,weaponMesh(o.w||S.w));const e={kind,ch,S,pos:new V3(x,0,z),yaw:0,hp:o.hp||S.hp,maxHp:o.hp||S.hp,post:0,maxPost:o.post||S.post,spd:(o.spd||S.spd),dmg:(o.dmg||S.dmg),reach:S.reach*(o.reachK||1)*(sc>1.2?1.15:1),guard:o.guard||S.guard,wind:S.wind,sc,r:.4*sc,atk:null,cool:rnd(1,2.5),stun:0,broken:0,dead:false,deadT:0,act:null,actK:0,strafe:Math.random()<.5?1:-1,guardUp:true,canBlock:true,boss:!!o.boss,name:o.name||null,superArmor:!!(o.boss||S.armor),blockFx:0,phase:1,combo:0,ai:o.ai||null};e.yaw=Math.atan2(P.pos.x-x,P.pos.z-z);EN.push(e);return e}
function killE(e,db){if(e.dead)return;e.dead=true;e.deadT=0;e.hp=0;e.ch.fallBack=Math.random()<.5;e.ch.g.rotation.y=e.yaw;K.decal(new V3(e.pos.x,.03,e.pos.z),new V3(0,1,0),rnd(1.2,2),'blood',.85,90);RUN.kills++;RUN.xp+=e.boss?150:e.kind==='brute'?40:25;if(e.boss&&e.twinOf===undefined){}}
let tokens=0;
function eAttack(e){const S=e.S;let perilous=false,type='slashR',wind=e.wind;const r=Math.random();
  if(e.kind==='spear'){type='thrust';perilous=r<(e.boss?.35:.2);if(e.boss&&r<.5)wind*=.8}else if(e.kind==='brute'){type=r<.5?'overhead':'slashR';perilous=r<.35}else if(e.kind==='ninja'){type=pick(['slashR','slashL','thrust']);perilous=r<.15;wind*=.85}else{type=pick(['slashR','slashL','overhead']);perilous=r<(e.boss?.22:.1)}
  if(e.boss&&e.phase>1)wind*=.8;e.atk={type,t:0,windup:wind*(perilous?1.35:1),dur:wind*(perilous?1.35:1)+.35,perilous,hit:false,dmg:e.dmg*(perilous?1.5:1)};if(perilous){HUD.peril.style.opacity=1;setTimeout(()=>HUD.peril.style.opacity=0,380);K.snd({tone:1400,tone2:900,tdur:.3,wave:'triangle',tvol:.35,vol:.3})}else K.snd({pos:e.pos,noise:1,ft:'highpass',f:5000,dur:.08,vol:.15})}
function eStrike(e){const a=e.atk;const to=P.pos.clone().sub(e.pos).setY(0);const d=to.length();const inFront=new V3(Math.sin(e.yaw),0,Math.cos(e.yaw)).dot(to.normalize())>.4;if(d>e.reach+.5||!inFront){K.SFX.swing(e.pos);return}
  if(P.iframe>0){K.note('Dodged!','#aee8ff');return}
  if(P.block&&!a.perilous){if(P.blockT<.2){P.parries++;e.post+=30*(e.boss?.8:1);e.stun=Math.max(e.stun,.55);e.atk=null;sparks(e,2.2);K.snd({tone:2200,tone2:1600,tdur:.35,wave:'triangle',tvol:.5,vol:.4});K.SFX.clang(e.pos);P.post=Math.max(0,P.post-5);P.spirit=Math.min(100,P.spirit+14*(1+PROG.up.spirit*.3));if(e.post>=e.maxPost&&!e.broken){e.broken=2.6;e.stun=2.6;K.note('Posture broken — strike for a deathblow!','#ff6a4a')}return}
    P.post+=a.dmg*1.3;sparks(e,1);K.SFX.clang(e.pos);K.CAM.shake=Math.max(K.CAM.shake,.2);if(P.post>=P.maxPost){P.post=P.maxPost*.4;P.stun=1.1;hurtP(a.dmg*.6);K.note('Guard broken!','#ff6a4a')}return}
  hurtP(a.dmg)}
function hurtP(d){if(P.dead||P.god)return;P.hp-=d;P.dmgTaken+=d;K.SFX.hurt();K.hurtFx(.7);K.CAM.shake=Math.max(K.CAM.shake,.45);P.atk=null;P.heal=0;if(P.hp<=0){P.hp=0;P.dead=true;K.banner('DEATH','','#c8201a',2400);K.SFX.fail();setTimeout(()=>chapterEnd(false),2200)}}
function stepE(e,dt){const C=e.ch;if(e.dead){e.deadT+=dt;K.ragdoll(C,null,dt);C.g.position.copy(e.pos);return}
  e.cool-=dt;e.stun=Math.max(0,e.stun-dt);if(e.broken>0){e.broken-=dt;if(e.broken<=0){e.post=e.maxPost*.5}}else if(!e.atk)e.post=Math.max(0,e.post-dt*(e.hp/e.maxHp>.5?8:4));e.blockFx=Math.max(0,e.blockFx-dt);if(e.act){e.actK+=dt*4;if(e.actK>=1)e.act=null}
  const to=P.pos.clone().sub(e.pos).setY(0);const d=to.length();const want=Math.atan2(to.x,to.z);let spd=0,st='idle',up='guard',mv=null;
  if(e.boss&&e.phase===1&&e.hp<e.maxHp*.5){e.phase=2;e.stun=1.2;K.banner(e.name.toUpperCase(),'grows desperate','#ff5a3a',2000);e.spd*=1.2;e.guard=Math.min(.8,e.guard+.15);scream(e)}
  if(e.stun>0){st='idle';up=e.broken>0?null:'guard';if(e.broken>0){C.g.rotation.x=0}}
  else if(e.atk){const a=e.atk;a.t+=dt;e.yaw+=angDiff(e.yaw,want)*Math.min(1,dt*(a.t<a.windup*.7?6:1));const k=a.t<a.windup?.22*(a.t/a.windup):.22+.78*Math.min(1,(a.t-a.windup)/(a.dur-a.windup));e.act=a.type==='thrust'?'thrust':a.type;e.actK=k;if(!a.hit&&a.t>=a.windup+.06){a.hit=true;eStrike(e)}if(e.atk&&a.t>=a.dur){e.atk=null;e.cool=rnd(.6,1.6)*(e.boss?.8:1);tokens=Math.max(0,tokens-1);if(e.boss&&Math.random()<.45&&e.combo<2){e.combo++;e.cool=.05}else e.combo=0}}
  else{e.yaw+=angDiff(e.yaw,want)*Math.min(1,dt*6);const S=e.S;
    if(S.bow&&d>5){if(d<9){mv=e.pos.clone().sub(to.clone().normalize());spd=S.spd}else if(d>16){mv=P.pos;spd=S.spd}else{mv=e.pos.clone().add(new V3(-to.z,0,to.x).normalize().multiplyScalar(e.strafe));spd=1.5}if(e.cool<=0){e.cool=rnd(1.8,3);shootArrowE(e)}up=null}
    else{const opt=e.reach-.4;const maxAtk=EN.filter(o=>!o.dead&&o.atk).length;if(d>opt+.3){mv=P.pos;spd=d>7?e.spd*1.4:e.spd}else if(d<opt-.8){mv=e.pos.clone().sub(to.clone().normalize());spd=2}else{mv=e.pos.clone().add(new V3(-to.z,0,to.x).normalize().multiplyScalar(e.strafe));spd=1.3;if(Math.random()<dt*.3)e.strafe*=-1}
      if(S.kunai&&d>6&&e.cool<=0&&Math.random()<.02){e.cool=2;shootArrowE(e,true)}
      if(d<e.reach+.3&&e.cool<=0&&(maxAtk<(e.boss?3:2))&&P.hp>0)eAttack(e)}}
  if(mv&&spd>0){const dx=mv.x-e.pos.x,dz=mv.z-e.pos.z,L=Math.hypot(dx,dz);if(L>.05){e.pos.x+=dx/L*spd*dt;e.pos.z+=dz/L*spd*dt}for(const o of EN){if(o===e||o.dead)continue;const ox=e.pos.x-o.pos.x,oz=e.pos.z-o.pos.z,od=Math.hypot(ox,oz),rr=e.r+o.r+.2;if(od<rr&&od>1e-3){e.pos.x+=ox/od*(rr-od)*.5;e.pos.z+=oz/od*(rr-od)*.5}}K.collide(e.pos,e.r,0,1.8);st=spd>4?'run':spd>1.6?'walk':'walk'}
  const pd=Math.hypot(e.pos.x-P.pos.x,e.pos.z-P.pos.z);if(pd<e.r+.45){const n=e.pos.clone().sub(P.pos).setY(0).normalize();e.pos.addScaledVector(n,e.r+.45-pd)}
  K.pose(C,st,dt,spd,{up:e.atk?null:up,act:e.act,k:e.actK,fast:!!e.atk});C.g.position.copy(e.pos);C.g.rotation.set(0,e.yaw,0);if(e.broken>0){C.P.hips.position.y-=.25;C.P.torso.rotation.x=.5}}
function scream(e){K.snd({pos:e.pos,tone:140,tone2:70,tdur:.8,wave:'sawtooth',tvol:.4,vol:.4,range:60})}
const arrowG=(()=>{const g=new T.CylinderGeometry(.012,.012,.8,4);g.rotateX(PI/2);return g})(),kunaiG=new T.OctahedronGeometry(.08);
function shootArrowE(e,kunai){const o=e.pos.clone().add(new V3(0,1.45*e.sc,0));const tgt=P.pos.clone().add(new V3(rnd(-.3,.3),1.3,rnd(-.3,.3)));const v=tgt.sub(o).normalize().multiplyScalar(kunai?24:28);const m=new T.Mesh(kunai?kunaiG:arrowG,mat('arr','#8a8a8a',{metalness:.5}));m.position.copy(o);scene.add(m);PROJ.push({m,v,t:0,dmg:kunai?9:12});K.SFX.whoosh(o)}
function stepProj(dt){for(let i=PROJ.length-1;i>=0;i--){const p=PROJ[i];p.t+=dt;p.m.position.addScaledVector(p.v,dt);p.m.lookAt(p.m.position.clone().add(p.v));const d=p.m.position.distanceTo(new V3(P.pos.x,P.pos.y+1.3,P.pos.z));if(d<.7){if(P.iframe>0){}else if(P.block){if(P.blockT<.25){K.snd({tone:2200,tdur:.2,wave:'triangle',tvol:.4,vol:.3});p.v.multiplyScalar(-1);p.reflect=1;continue}K.SFX.clang(P.pos);P.post+=8}else hurtP(p.dmg);scene.remove(p.m);PROJ.splice(i,1);continue}
    if(p.reflect)for(const e of EN){if(!e.dead&&p.m.position.distanceTo(e.pos.clone().add(new V3(0,1.3,0)))<.8){hurtE(e,25,true);scene.remove(p.m);PROJ.splice(i,1);break}}if(p.t>3&&PROJ[i]===p){scene.remove(p.m);PROJ.splice(i,1)}}}
/* ================= chapter flow ================= */
const RUN={ch:null,ci:0,wave:-1,t:0,kills:0,xp:0,state:'menu',pause:0,boss:null,tut:0};
function clearEnemies(){EN.forEach(e=>scene.remove(e.ch.g));EN.length=0;PROJ.forEach(p=>scene.remove(p.m));PROJ.length=0}
function startChapter(i){const ch=CH[i];RUN.ch=ch;RUN.ci=i;RUN.wave=-1;RUN.t=0;RUN.kills=0;RUN.xp=0;RUN.state='intro';RUN.boss=null;clearEnemies();buildArena(ch);resetPlayer();K.cine(true);
  K.banner('CHAPTER '+(i+1),ch.n,'#e8dcc0',3500);K.say([{who:'',col:'#e8dcc0',text:ch.intro,voice:false,dur:Math.max(4,ch.intro.length*.05)}],()=>{K.cine(false);RUN.state='fight';RUN.pause=.8;if(ch.tut)tutorial()})}
function tutorial(){const tips=['Left click to slash. Swipe the mouse left, right or up as you click to choose the cut.','Hold right click to block. Tap it just before a hit lands to PARRY.','Red 危 attacks cannot be blocked. Press Space to dodge them.','Hits and parries fill the enemy\'s posture bar. When it breaks, strike for a DEATHBLOW.','Hold left click for a heavy cut. F kicks through a guard. E drinks from your gourd. Q unleashes Moon Slash when your spirit is full.'];tips.forEach((t,k)=>setTimeout(()=>{if(RUN.state==='fight')K.note(t,'#aee8ff')},800+k*5200))}
function spawnWave(list){const n=list.length;list.forEach((k,j)=>{const a=j/n*TWO+rnd(-.3,.3)+PI;let x=Math.sin(a)*15,z=Math.cos(a)*15;if(AR.rect){x=rnd(-3,3);z=-18+j*2.5*(j%2?1:-1)*0-j*1.6}spawnE(k,x,z,{})});K.note('Wave '+(RUN.wave+1)+' — '+n+' enemies','#ff9a6a')}
function spawnBoss(){const b=RUN.ch.boss,s=ET[b.k];const z=AR.rect?-16:-12;const look=BLOOKS[b.n];const e=spawnE(b.k,0,z,{hp:b.hp,post:b.post,boss:true,name:b.n,look,sc:b.oni?1.45:b.k==='brute'?1.4:1.05,spd:s.spd*(b.duel?1.25:1.05),dmg:s.dmg*(b.final?1.35:1.15),guard:b.duel?.62:s.guard+.15,reachK:b.staff?1.1:1});RUN.boss=e;if(b.twin){const e2=spawnE(b.k,4,z,{hp:b.hp,post:b.post,boss:true,name:b.n,look,spd:s.spd*1.1,dmg:s.dmg*1.1,guard:.55});e2.twin=1;RUN.boss2=e2}
  K.banner(b.n.toUpperCase(),b.final?'The man who killed your master':'','#ff5a3a',3000);scream(e);HUD.eb.style.display='block'}
function stepChapter(dt){if(RUN.state!=='fight')return;RUN.t+=dt;if(RUN.pause>0){RUN.pause-=dt;return}const alive=EN.filter(e=>!e.dead).length;if(alive)return;const ch=RUN.ch;
  if(RUN.wave<ch.waves.length-1){RUN.wave++;spawnWave(ch.waves[RUN.wave]);RUN.pause=1;return}if(!RUN.boss){RUN.wave++;spawnBoss();RUN.pause=1;return}chapterEnd(true)}
function chapterEnd(won){if(RUN.state==='done')return;RUN.state='done';HUD.eb.style.display='none';if(document.pointerLockElement)document.exitPointerLock();const ch=RUN.ch,i=RUN.ci;
  if(won){const first=PROG.ch<=i;if(first){PROG.ch=i+1;PROG.pts+=1}PROG.xp+=RUN.xp;while(PROG.xp>=(PROG.lvlXp||300)){PROG.xp-=(PROG.lvlXp||300);PROG.pts++;PROG.lvlXp=(PROG.lvlXp||300)+100}const t=Math.round(RUN.t);const prev=PROG.best[i];PROG.best[i]=prev?Math.min(prev,t):t;saveProg();
    const grade=P.dmgTaken<20?'S':P.dmgTaken<60?'A':P.dmgTaken<120?'B':'C';K.menu('<h2 style="font-family:Georgia,serif">'+(ch.boss.final?'THE BLOOD MOON FADES':'CHAPTER COMPLETE')+'</h2><p>'+ch.n+'</p><p>Grade <b style="font-size:26px;color:#ffd23f">'+grade+'</b> · Time '+Math.floor(t/60)+':'+String(t%60).padStart(2,'0')+' · Kills '+RUN.kills+' · Parries '+P.parries+' · Damage taken '+Math.round(P.dmgTaken)+'</p><p>+'+RUN.xp+' XP'+(first?' · +1 skill point':'')+'</p>'+(ch.boss.final?'<p style="font-family:Georgia,serif">Master Ishida is avenged. Kaito sheathes his blade as the moon turns white again.</p>':''),[[i<CH.length-1?'Next chapter':'Chapters',()=>{K.menuOff();if(i<CH.length-1)startChapter(i+1);else mainMenu()},'pri'],['Skills ('+PROG.pts+')',()=>skillMenu()],['Chapters',()=>mainMenu()]])}
  else K.menu('<h2 style="font-family:Georgia,serif">YOU HAVE FALLEN</h2><p>'+ch.n+'</p><p style="opacity:.7">Tip: parry (tap block right before a hit) breaks posture much faster than trading blows.</p>',[['Try again',()=>{K.menuOff();startChapter(i)},'pri'],['Skills ('+PROG.pts+')',()=>skillMenu()],['Chapters',()=>mainMenu()]])}
function skillMenu(){const card=K.menu('<h2 style="font-family:Georgia,serif">SKILLS</h2><p>Skill points: <b>'+PROG.pts+'</b> · XP to next point: '+((PROG.lvlXp||300)-PROG.xp)+'</p>',[]);for(const k in UPG){const u=UPG[k],lv=PROG.up[k];const row=el('div',{class:'mb-up'});row.append(el('div',null,el('b',null,u.n+' '+'●'.repeat(lv)+'○'.repeat(u.max-lv)),el('br'),el('small',null,u.d)));const b=el('button',{type:'button',class:'bk-btn'+(PROG.pts>0&&lv<u.max?'':' no')},'Learn');b.onclick=e=>{e.stopPropagation();if(PROG.pts<=0||lv>=u.max)return;PROG.pts--;PROG.up[k]++;saveProg();K.SFX.ui();skillMenu()};row.append(b);card.append(row)}const bk=el('button',{type:'button',class:'bk-btn pri'},'Back');bk.onclick=e=>{e.stopPropagation();mainMenu()};card.append(bk)}
function mainMenu(){RUN.state='menu';HUD.eb.style.display='none';const card=K.menu('<h2 style="font-family:Georgia,serif;font-size:38px;letter-spacing:.06em">MOONBLADE</h2><p>You are Kaito, last student of Master Ishida. Under a new moon the Shadow Clan burned your village and killed your master. Eight nights of vengeance, one blade.</p><p style="opacity:.7">First-person sword fighting: aimed cuts, blocks and perfect parries, posture breaks and deathblows, dodges, kicks and the Moon Slash.</p>',[]);const grid=el('div',{class:'sc-lv',style:'display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:8px;margin:10px 0'});
  CH.forEach((ch,i)=>{const lock=i>PROG.ch;const b=el('button',{type:'button',class:'bk-btn'+(lock?' no':''),style:'display:block;margin:0;text-align:left;white-space:normal'});b.innerHTML='<b>'+(lock?'🔒 ':'')+(i+1)+'. '+ch.n+'</b><br><small>'+(PROG.best[i]?'Best '+Math.floor(PROG.best[i]/60)+':'+String(PROG.best[i]%60).padStart(2,'0'):lock?'Locked':'Not cleared')+'</small>';b.onclick=e=>{e.stopPropagation();if(lock)return;K.menuOff();startChapter(i)};grid.append(b)});card.append(grid);const sb=el('button',{type:'button',class:'bk-btn pri'},'Skills ('+PROG.pts+')');sb.onclick=e=>{e.stopPropagation();skillMenu()};card.append(sb)}
/* ================= player update ================= */
let lmbLatch=false,rmbLatch=false,swipeHist=[];
function stepPlayer(dt){const I=input,k=I.keys;if(P.dead||RUN.state!=='fight')return;
  const sens=.0022;P.yaw-=I.mdx*sens;P.pitch=clamp(P.pitch-I.mdy*sens,-1.2,1.2);swipeHist.push([I.mdx,I.mdy,performance.now()]);while(swipeHist.length&&performance.now()-swipeHist[0][2]>180)swipeHist.shift();
  if(P.lock&&(P.lock.dead||P.lock.pos.distanceTo(P.pos)>18))P.lock=null;if(P.lock){const w=Math.atan2(-(P.lock.pos.x-P.pos.x),-(P.lock.pos.z-P.pos.z));P.yaw+=angDiff(P.yaw,w)*Math.min(1,dt*10);P.pitch+=(-.08-P.pitch)*Math.min(1,dt*5)}
  P.stun=Math.max(0,P.stun-dt);P.iframe=Math.max(0,P.iframe-dt);P.blockT+=dt;
  let mx=(k.d||k.arrowright?1:0)-(k.a||k.arrowleft?1:0)+I.joy.x,mz=(k.w||k.arrowup?1:0)-(k.s||k.arrowdown?1:0)-I.joy.y;const ml=Math.hypot(mx,mz);if(ml>1){mx/=ml;mz/=ml}const fw=new V3(-Math.sin(P.yaw),0,-Math.cos(P.yaw)),rt=new V3(Math.cos(P.yaw),0,-Math.sin(P.yaw));const dir=fw.clone().multiplyScalar(mz).addScaledVector(rt,mx);
  const blockHeld=(I.right||I.alt)&&P.stun<=0&&!P.atk&&P.heal<=0;if(blockHeld&&!P.block)P.blockT=0;P.block=blockHeld;
  const sprint=k.shift&&P.stam>5&&!P.block&&ml>.1;let spd=P.stun>0?0:P.block?2:P.atk?1.2:sprint?6.4:4;if(sprint)P.stam-=12*dt;
  const dg=k[' ']||I.jumpBtn;if(dg&&!P.dgL&&P.dodge<=0&&P.stam>12&&P.stun<=0){P.dodge=.32;P.iframe=.36;P.stam-=15;P.dodgeV=(ml>.1?dir.clone().normalize():fw.clone().multiplyScalar(-1)).multiplyScalar(13);P.atk=null;K.SFX.whoosh(P.pos)}P.dgL=dg;
  if(P.dodge>0){P.dodge-=dt;P.pos.addScaledVector(P.dodgeV,dt);P.dodgeV.multiplyScalar(1-dt*6)}else if(ml>.05)P.pos.addScaledVector(dir.clone().normalize(),spd*Math.min(1,ml)*dt);
  K.collide(P.pos,.35,0,1.8);if(!AR.rect){const r=Math.hypot(P.pos.x,P.pos.z);if(r>AR.r-1.6){P.pos.x*=(AR.r-1.6)/r;P.pos.z*=(AR.r-1.6)/r}}else{P.pos.x=clamp(P.pos.x,-4.3,4.3);P.pos.z=clamp(P.pos.z,-24,24)}
  if(!P.atk&&!P.block&&P.dodge<=0)P.stam=Math.min(100,P.stam+22*dt);P.post=Math.max(0,P.post-dt*(P.block?4:14));
  // attacks
  const lmb=(I.down&&I.locked)||I.fire;const brokenNear=EN.find(e=>!e.dead&&e.broken>0&&e.pos.distanceTo(P.pos)<3.3);HUD.db.style.display=brokenNear?'block':'none';
  if(lmb){P.hold+=dt}if(!lmb&&lmbLatch){if(brokenNear){startAtk('db')}else if(P.hold>.35)startAtk('heavy');else{let sx=0,sy=0;swipeHist.forEach(s=>{sx+=s[0];sy+=s[1]});let d=null;if(Math.abs(sx)>Math.abs(sy)&&Math.abs(sx)>25)d=sx>0?'slashL':'slashR';else if(sy<-25)d='overhead';else if(sy>25)d='thrust';startAtk('light',d)}P.hold=0}lmbLatch=lmb;
  if(k.f&&!P.fL)startAtk('kick');P.fL=k.f;if(k.q&&!P.qL&&P.spirit>=100)startAtk('moon');P.qL=k.q;
  if(k.e&&!P.eL&&P.gourd>0&&P.heal<=0&&!P.atk&&P.hp<P.maxHp){P.gourd--;P.heal=1;K.snd({noise:1,f:600,dur:.4,vol:.25})}P.eL=k.e;if(P.heal>0){P.heal-=dt;P.hp=Math.min(P.maxHp,P.hp+45*dt)}
  if(k.r&&!P.rL){if(P.lock)P.lock=null;else{let b=null,bd=16;for(const e of EN){if(e.dead)continue;const d=e.pos.distanceTo(P.pos);const to=e.pos.clone().sub(P.pos).normalize();if(d<bd&&to.dot(fw)>.3){bd=d;b=e}}P.lock=b}}P.rL=k.r;
  if(P.atk){const a=P.atk;a.t+=dt*(a.recoil?.6:1);if(!a.hitDone&&a.t>=a.A.hit){a.hitDone=true;atkHit()}if(a.t>=a.A.dur)P.atk=null}
  // camera & viewmodel
  const bob=ml>.1&&P.dodge<=0?Math.sin(performance.now()/(sprint?95:130))*.035:0;camera.position.set(P.pos.x,1.62+bob-(P.dodge>0?.15:0),P.pos.z);camera.rotation.set(P.pitch,P.yaw,0,'YXZ');if(K.CAM.shake>0){K.CAM.shake=Math.max(0,K.CAM.shake-dt*2.5);const s=K.CAM.shake*K.CAM.shake*.06;camera.position.x+=rnd(-s,s);camera.position.y+=rnd(-s,s)}
  if(P.atk){const a=P.atk;const ph=a.t/a.A.dur;const p0=POSE[a.pose+'0']||POSE.idle,p1=POSE[a.pose+'1']||POSE.idle;const hitPh=a.A.hit/a.A.dur;if(ph<hitPh*.8)swordTo(p0,Math.min(1,dt*18));else if(ph<hitPh*1.5)swordTo(p1,Math.min(1,dt*(a.kind==='heavy'?20:26)));else swordTo(POSE.idle,Math.min(1,dt*8));trail.material.opacity=ph>hitPh*.7&&ph<hitPh*1.4?.35:0;trail.position.set(0,-.2,-1.2);trail.scale.set(2,.9,1);trail.rotation.z=a.pose==='overhead'||a.pose==='db'?PI/2:a.pose==='slashL'?.4:-.4}
  else{swordTo(P.block?POSE.block:P.heal>0?[.4,-.6,-.4,.4,-.2,-.5]:POSE.idle,Math.min(1,dt*14));trail.material.opacity=0}
  SW.userData.blade.material.emissiveIntensity=P.spirit>=100?.9+Math.sin(performance.now()/120)*.3:.3}
/* ================= ambience ================= */
function ambient(dt){const cp=camera.position;for(const f of FIRESP){if(f.distanceTo(cp)>60)continue;if(Math.random()<.5)K.emit(K.FX,f.x+rnd(-.4,.4),f.y,f.z+rnd(-.4,.4),rnd(-.2,.2),rnd(1.5,3),rnd(-.2,.2),.7,.6,.1,0xffc050,0xff2000,1,-1,1);if(Math.random()<.15)K.emit(K.SM,f.x,f.y+1,f.z,rnd(-.3,.3),2,rnd(-.3,.3),4,.8,4,0x3a3430,0x1a1816,.4,-.3,.5);if(Math.random()<.2)K.emit(K.FX,f.x,f.y+1,f.z,rnd(-1,1),rnd(2,4),rnd(-1,1),3,.06,.02,0xffa040,0xff4000,1,-.3,.3)}
  if(W.rain)for(let i=0;i<10;i++)K.emit(K.SM,cp.x+rnd(-12,12),cp.y+rnd(5,10),cp.z+rnd(-12,12),0,-24,0,.6,.05,.05,0xaabbcc,0xaabbcc,.45,0,0);if(W.petals&&Math.random()<.5)K.emit(K.SM,cp.x+rnd(-14,14),cp.y+rnd(3,8),cp.z+rnd(-14,14),rnd(-.6,.6),-.8,rnd(-.6,.6),6,.1,.1,RUN.ch&&RUN.ch.th==='moon'?0xc81a2a:0xf8b0c8,null,.9,0,.2);
  if(RUN.ch&&(RUN.ch.th==='bamboo'||RUN.ch.th==='fields')&&Math.random()<.4)K.emit(K.FX,cp.x+rnd(-15,15),rnd(.5,3),cp.z+rnd(-15,15),rnd(-.3,.3),rnd(-.1,.2),rnd(-.3,.3),3,.08,.05,0xd8ff6a,0x6aff2a,1,0,.2);LIGHTS.forEach((L,i)=>L.intensity=2.3+Math.sin(performance.now()/110+i*7)*.25)}
/* ================= HUD & loop ================= */
let windL=null;
function updHUD(){HUD.hp.style.width=P.hp/P.maxHp*100+'%';HUD.sp.style.width=P.spirit+'%';HUD.sp.style.background=P.spirit>=100?'linear-gradient(90deg,#7ab8ff,#ffffff)':'linear-gradient(90deg,#3a6aaf,#7ab8ff)';const pp=P.post/P.maxPost;HUD.postI.style.left=(50-pp*50)+'%';HUD.postI.style.right=(50-pp*50)+'%';HUD.post.style.opacity=pp>.02?1:0;
  const b=RUN.boss&&!RUN.boss.dead?RUN.boss:RUN.boss2&&!RUN.boss2.dead?RUN.boss2:null;const tg=b||P.lock||EN.filter(e=>!e.dead).sort((a,c2)=>a.pos.distanceTo(P.pos)-c2.pos.distanceTo(P.pos))[0];if(tg&&tg.pos.distanceTo(P.pos)<(b?60:9)){HUD.eb.style.display='block';HUD.ebN.textContent=tg.name||({bandit:'Bandit',ninja:'Shadow Ninja',spear:'Spearman',brute:'Brute',archer:'Archer'}[tg.kind]);HUD.ebI.style.width=tg.hp/tg.maxHp*100+'%';const ep=Math.min(1,tg.post/tg.maxPost);HUD.ebPI.style.left=(50-ep*50)+'%';HUD.ebPI.style.right=(50-ep*50)+'%';HUD.ebPI.style.background=tg.broken>0?'#ff2020':''}else HUD.eb.style.display='none';
  HUD.gourd.textContent='🍶 '+P.gourd+'/'+P.gourdMax+(P.spirit>=100?'   🌕 Q — Moon Slash':'');HUD.info.innerHTML=RUN.ch?('Chapter '+(RUN.ci+1)+'<br><small>'+RUN.ch.n+'</small><br><small>'+(RUN.boss?'Boss':'Wave '+Math.max(1,RUN.wave+1)+'/'+RUN.ch.waves.length)+'</small>'):''}
K.keys([['W A S D','Move'],['Shift','Sprint'],['LMB','Slash (swipe to aim)'],['Hold LMB','Heavy cut'],['RMB','Block · tap to parry'],['Space','Dodge'],['F','Kick'],['R','Lock on'],['E','Heal'],['Q','Moon Slash'],['P','Pause']]);
K.touchBtn('HEAVY',v=>{if(!v&&RUN.state==='fight')startAtk('heavy')},true);K.touchBtn('KICK',()=>startAtk('kick'));K.touchBtn('HEAL',()=>{input.keys.e=true;setTimeout(()=>input.keys.e=false,100)});K.touchBtn('MOON',()=>{if(P.spirit>=100)startAtk('moon')});K.touchBtn('LOCK',()=>{input.keys.r=true;setTimeout(()=>input.keys.r=false,100)});
c.on(document,'keydown',e=>{if(e.key.toLowerCase()==='p'&&RUN.state==='fight'){if(K.H.menu.classList.contains('on'))K.menuOff();else K.menu('<h2 style="font-family:Georgia,serif">PAUSED</h2><p>'+RUN.ch.n+'</p>',[['Resume',()=>K.menuOff(),'pri'],['Restart chapter',()=>{K.menuOff();startChapter(RUN.ci)}],['Chapters',()=>mainMenu()]])}});
buildArena(CH[0]);resetPlayer();mainMenu();
function update(dtRaw){let dt=Math.min(dtRaw,.05);if(slowmo>0){slowmo-=dtRaw;dt*=.3}if(K.H.menu.classList.contains('on')&&RUN.state!=='done'){if(RUN.state==='menu'){camera.position.set(Math.sin(performance.now()/8000)*10,3,Math.cos(performance.now()/8000)*10);camera.lookAt(0,1.5,0)}return}
  stepPlayer(dt);for(const e of EN)stepE(e,dt);stepProj(dt);stepChapter(dt);ambient(dt);updHUD();if(!windL)windL=K.loop({noise:1,f:300});if(windL)windL.set(.03+W.rain*.06)}
st3.onFrame(update);
window.__MB=window.__BK={P,EN,RUN,CH,PROG,K,startChapter,startAtk,spawnE,chapterEnd,sim(n,dt){for(let i=0;i<n;i++)update(dt||1/30);return this.tick()},tick(){return{hp:P.hp|0,state:RUN.state,wave:RUN.wave,en:EN.filter(e=>!e.dead).length,boss:RUN.boss?RUN.boss.hp|0:null,kills:RUN.kills}}};
return()=>{K.dispose();st3.dispose()}})}
G.push({id:'moonblade',name:'Moonblade',kind:'game',wide:true,big:true,major:true,tags:['sword','samurai','first-person','night'],tint:'#0e1224',
  blurb:'First-person samurai sword fighting at night. Aim your cuts with the mouse, block and parry, break enemy posture for deathblows, and dodge red unblockable attacks. Fight through 8 chapters of bandits, ninjas and spearmen to 8 boss duels, and unlock skills along the way.',fmt:b=>Math.floor(b/1000)+'/8 chapters',
  art:'<defs><linearGradient id="mbS" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#05081a"/><stop offset="1" stop-color="#2a1a3a"/></linearGradient></defs><rect width="120" height="72" fill="url(#mbS)"/><circle cx="84" cy="22" r="13" fill="#e8f0ff"/><circle cx="84" cy="22" r="20" fill="#e8f0ff" opacity=".12"/><path d="M0 60l20-8 20 6 22-10 22 8 36-6v22H0z" fill="#0a0a14"/><path d="M18 66L96 14" stroke="#dfe8f2" stroke-width="2.4"/><path d="M18 66l6-3" stroke="#c8a040" stroke-width="5"/><path d="M12 70l8-5" stroke="#1a1a24" stroke-width="4"/>',
  run(root,c){return moonblade(root,c)}});
