/* ================= BOARD & CLASSIC ================= */
/* ---------- Chess ---------- */
G.push({id:'chess',name:'Master Chess',kind:'board',levels:true,tint:'#e8c48a',blurb:'Full-rules chess against the computer: castling, en passant, promotion, check and mate.',fmt:b=>b+' wins',
art:'<rect width="120" height="72" fill="#e8c48a"/><g fill="#8a5a2b">'+[0,1,2,3,4,5].map(i=>[0,1,2].map(j=>(i+j)%2?'<rect x="'+(i*20)+'" y="'+(j*24)+'" width="20" height="24"/>':'').join('')).join('')+'</g><text x="30" y="52" font-size="40" text-anchor="middle">♞</text><text x="86" y="54" font-size="44" text-anchor="middle" fill="#fff" stroke="#1D1A2F" stroke-width="1.5">♛</text>',
run(root,c){
  const SZ=560,Q=SZ/8;const[cv,x]=mk(SZ,SZ,'width:min(100%,560px)');const status=el('p',{class:'hint',style:'font-weight:700'});const row=el('div',{class:'row'});const nb=el('button',{class:'btn',type:'button'},'New game'),ub=el('button',{class:'btn',type:'button'},'Undo move');row.append(nb,ub);root.append(cv,status,row);
  const V={p:100,n:320,b:330,r:500,q:900,k:0};const PST={p:[0,0,0,0,0,0,0,0,50,50,50,50,50,50,50,50,10,10,20,30,30,20,10,10,5,5,10,25,25,10,5,5,0,0,0,20,20,0,0,0,5,-5,-10,0,0,-10,-5,5,5,10,10,-20,-20,10,10,5,0,0,0,0,0,0,0,0],n:[-50,-40,-30,-30,-30,-30,-40,-50,-40,-20,0,0,0,0,-20,-40,-30,0,10,15,15,10,0,-30,-30,5,15,20,20,15,5,-30,-30,0,15,20,20,15,0,-30,-30,5,10,15,15,10,5,-30,-40,-20,0,5,5,0,-20,-40,-50,-40,-30,-30,-30,-30,-40,-50],b:[-20,-10,-10,-10,-10,-10,-10,-20,-10,0,0,0,0,0,0,-10,-10,0,5,10,10,5,0,-10,-10,5,5,10,10,5,5,-10,-10,0,10,10,10,10,0,-10,-10,10,10,10,10,10,10,-10,-10,5,0,0,0,0,5,-10,-20,-10,-10,-10,-10,-10,-10,-20],r:[0,0,0,0,0,0,0,0,5,10,10,10,10,10,10,5,-5,0,0,0,0,0,0,-5,-5,0,0,0,0,0,0,-5,-5,0,0,0,0,0,0,-5,-5,0,0,0,0,0,0,-5,-5,0,0,0,0,0,0,-5,0,0,0,5,5,0,0,0],q:[-20,-10,-10,-5,-5,-10,-10,-20,-10,0,0,0,0,0,0,-10,-10,0,5,5,5,5,0,-10,-5,0,5,5,5,5,0,-5,0,0,5,5,5,5,0,-5,-10,5,5,5,5,5,0,-10,-10,0,5,0,0,0,0,-10,-20,-10,-10,-5,-5,-10,-10,-20],k:[-30,-40,-40,-50,-50,-40,-40,-30,-30,-40,-40,-50,-50,-40,-40,-30,-30,-40,-40,-50,-50,-40,-40,-30,-30,-40,-40,-50,-50,-40,-40,-30,-20,-30,-30,-40,-40,-30,-30,-20,-10,-20,-20,-20,-20,-20,-20,-10,20,20,0,0,0,0,20,20,20,30,10,0,0,10,30,20]};
  const GLY={K:'♔',Q:'♕',R:'♖',B:'♗',N:'♘',P:'♙',k:'♚',q:'♛',r:'♜',b:'♝',n:'♞',p:'♟'};
  let B,turn,cast,ep,hist,sel=null,moves=[],last=null,over=false,thinking=false,wins=S.get('chess_w',0);
  const isW=p=>p&&p===p.toUpperCase(),col=p=>p?(isW(p)?'w':'b'):null;
  function reset(){B=('rnbqkbnr'+'pppppppp'+'.'.repeat(32)+'PPPPPPPP'+'RNBQKBNR').split('').map(ch=>ch==='.'?null:ch);turn='w';cast={K:1,Q:1,k:1,q:1};ep=-1;hist=[];sel=null;moves=[];last=null;over=false;upd()}
  function attacked(sq,by){const r=sq>>3,f=sq&7;const at=(rr,ff)=>rr>=0&&rr<8&&ff>=0&&ff<8?B[rr*8+ff]:undefined;const pd=by==='w'?1:-1;for(const df of[-1,1]){const p=at(r+pd,f+df);if(p&&col(p)===by&&p.toLowerCase()==='p')return true}
    for(const[dr,df]of[[1,2],[2,1],[-1,2],[-2,1],[1,-2],[2,-1],[-1,-2],[-2,-1]]){const p=at(r+dr,f+df);if(p&&col(p)===by&&p.toLowerCase()==='n')return true}
    for(const[dr,df]of[[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]]){let rr=r+dr,ff=f+df,n=1;while(rr>=0&&rr<8&&ff>=0&&ff<8){const p=B[rr*8+ff];if(p){if(col(p)===by){const t=p.toLowerCase();if(t==='q'||(t==='r'&&(!dr||!df))||(t==='b'&&dr&&df)||(t==='k'&&n===1))return true}break}rr+=dr;ff+=df;n++}}return false}
  function gen(side,capsOnly){const out=[];for(let s=0;s<64;s++){const p=B[s];if(!p||col(p)!==side)continue;const t=p.toLowerCase(),r=s>>3,f=s&7;const add=(to,extra)=>{const tp=B[to];if(tp&&col(tp)===side)return false;if(capsOnly&&!tp&&!(extra&&extra.ep))return !tp;out.push(Object.assign({f:s,t:to,cap:tp||(extra&&extra.ep?(side==='w'?'p':'P'):null)},extra||{}));return !tp};
      if(t==='p'){const d=side==='w'?-1:1,r1=r+d;if(r1>=0&&r1<8){if(!B[r1*8+f]&&!capsOnly){out.push({f:s,t:r1*8+f,promo:r1===0||r1===7});const sr=side==='w'?6:1;if(r===sr&&!B[(r+2*d)*8+f])out.push({f:s,t:(r+2*d)*8+f,dbl:1})}for(const df of[-1,1]){const ff=f+df;if(ff<0||ff>7)continue;const to=r1*8+ff;if(B[to]&&col(B[to])!==side)out.push({f:s,t:to,cap:B[to],promo:r1===0||r1===7});else if(to===ep)out.push({f:s,t:to,ep:1,cap:side==='w'?'p':'P'})}}}
      else if(t==='n'||t==='k'){const D=t==='n'?[[1,2],[2,1],[-1,2],[-2,1],[1,-2],[2,-1],[-1,-2],[-2,-1]]:[[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]];for(const[dr,df]of D){const rr=r+dr,ff=f+df;if(rr>=0&&rr<8&&ff>=0&&ff<8)add(rr*8+ff)}
        if(t==='k'&&!capsOnly){const o=side==='w'?'w':'b',R0=side==='w'?56:0,op=side==='w'?'b':'w';if(s===R0+4&&!attacked(s,op)){if(cast[side==='w'?'K':'k']&&!B[R0+5]&&!B[R0+6]&&B[R0+7]&&B[R0+7].toLowerCase()==='r'&&!attacked(R0+5,op)&&!attacked(R0+6,op))out.push({f:s,t:R0+6,castle:'k'});if(cast[side==='w'?'Q':'q']&&!B[R0+3]&&!B[R0+2]&&!B[R0+1]&&B[R0]&&B[R0].toLowerCase()==='r'&&!attacked(R0+3,op)&&!attacked(R0+2,op))out.push({f:s,t:R0+2,castle:'q'})}}}
      else{const D=t==='r'?[[1,0],[-1,0],[0,1],[0,-1]]:t==='b'?[[1,1],[1,-1],[-1,1],[-1,-1]]:[[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]];for(const[dr,df]of D){let rr=r+dr,ff=f+df;while(rr>=0&&rr<8&&ff>=0&&ff<8){if(!add(rr*8+ff))break;rr+=dr;ff+=df}}}}return out}
  function make(m){const st={B:B.slice(),turn,cast:Object.assign({},cast),ep,last};const p=B[m.f];B[m.t]=m.promo?(isW(p)?'Q':'q'):p;B[m.f]=null;if(m.ep)B[m.t+(isW(p)?8:-8)]=null;if(m.castle){const R0=isW(p)?56:0;if(m.castle==='k'){B[R0+5]=B[R0+7];B[R0+7]=null}else{B[R0+3]=B[R0];B[R0]=null}}
    ep=m.dbl?(m.f+m.t)/2:-1;if(p==='K'){cast.K=cast.Q=0}if(p==='k'){cast.k=cast.q=0}[[56,'Q'],[63,'K'],[0,'q'],[7,'k']].forEach(([sq,k])=>{if(m.f===sq||m.t===sq)cast[k]=0});turn=turn==='w'?'b':'w';return st}
  function unmake(st){B=st.B;turn=st.turn;cast=st.cast;ep=st.ep;last=st.last}
  const kingSq=side=>B.indexOf(side==='w'?'K':'k');const inCheck=side=>attacked(kingSq(side),side==='w'?'b':'w');
  function legal(side){return gen(side).filter(m=>{const st=make(m);const ok=!inCheck(side);unmake(st);return ok})}
  function evalB(){let s=0;for(let i=0;i<64;i++){const p=B[i];if(!p)continue;const t=p.toLowerCase();const w=isW(p);s+=(V[t]+PST[t][w?i:(7-(i>>3))*8+(i&7)])*(w?1:-1)}return s}
  let nodes=0;function search(d,a,b,side){nodes++;if(d===0)return quiesce(a,b,side,3);const ms=legal(side);if(!ms.length)return inCheck(side)?-99999+(10-d):0;ms.sort((m1,m2)=>(m2.cap?V[m2.cap.toLowerCase()]*10-V[B[m2.f].toLowerCase()]:0)-(m1.cap?V[m1.cap.toLowerCase()]*10-V[B[m1.f].toLowerCase()]:0));for(const m of ms){const st=make(m);const v=-search(d-1,-b,-a,side==='w'?'b':'w');unmake(st);if(v>=b)return v;if(v>a)a=v}return a}
  function quiesce(a,b,side,q){const stand=evalB()*(side==='w'?1:-1);if(stand>=b||q===0)return stand;if(stand>a)a=stand;const ms=gen(side,true).filter(m=>m.cap);for(const m of ms){const st=make(m);if(inCheck(side)){unmake(st);continue}const v=-quiesce(-b,-a,side==='w'?'b':'w',q-1);unmake(st);if(v>=b)return v;if(v>a)a=v}return a}
  function aiMove(){const side='b';const ms=legal(side);if(!ms.length)return;const depth=c.pick(1,2,3);let best=null,bv=-1e9;shuffle(ms);nodes=0;for(const m of ms){const st=make(m);const v=-search(depth-1,-1e9,-bv,'w')+(c.level===0?Math.random()*60:c.level===1?Math.random()*12:0);unmake(st);if(v>bv){bv=v;best=m}}play(best)}
  function play(m){hist.push(make(m));last=[m.f,m.t];beep(m.cap?300:500,.06,'triangle',.05);upd()}
  function upd(){const ms=legal(turn);let t='';if(!ms.length){over=true;if(inCheck(turn)){t=turn==='w'?'Checkmate. The computer wins.':'Checkmate! You win!';if(turn==='b'){wins++;S.set('chess_w',wins);c.best(wins)}}else t='Stalemate. It’s a draw.'}else t=(turn==='w'?'Your move (white)':'Computer is thinking…')+(inCheck(turn)?' · CHECK!':'');status.textContent=t;c.stat('Chess · wins '+wins);draw();if(!over&&turn==='b'){thinking=true;setTimeout(()=>{if(!alive)return;aiMove();thinking=false},250)}}
  function draw(){for(let r=0;r<8;r++)for(let f=0;f<8;f++){const s=r*8+f;x.fillStyle=(r+f)%2?'#b07a44':'#f0dcb4';x.fillRect(f*Q,r*Q,Q,Q);if(last&&(last[0]===s||last[1]===s)){x.fillStyle='rgba(255,210,63,.45)';x.fillRect(f*Q,r*Q,Q,Q)}if(sel===s){x.fillStyle='rgba(110,231,183,.55)';x.fillRect(f*Q,r*Q,Q,Q)}}
    const ks=kingSq(turn);if(inCheck(turn)){x.fillStyle='rgba(242,53,42,.5)';x.fillRect((ks&7)*Q,(ks>>3)*Q,Q,Q)}
    moves.forEach(m=>{const r=m.t>>3,f=m.t&7;x.fillStyle='rgba(29,26,47,.28)';x.beginPath();x.arc(f*Q+Q/2,r*Q+Q/2,B[m.t]?Q*.45:Q*.15,0,7);B[m.t]?(x.lineWidth=5,x.strokeStyle='rgba(29,26,47,.35)',x.stroke()):x.fill()});
    x.textAlign='center';x.textBaseline='middle';x.font=(Q*.8)+'px serif';for(let s=0;s<64;s++){const p=B[s];if(!p)continue;const px=(s&7)*Q+Q/2,py=(s>>3)*Q+Q/2+4;const g=GLY[p.toLowerCase()];x.fillStyle=isW(p)?'#fffdf6':'#1D1A2F';x.strokeStyle=isW(p)?'#1D1A2F':'#fffdf6';x.lineWidth=2;x.strokeText(g,px,py);x.fillText(g,px,py)}
    x.font='600 11px Figtree, sans-serif';x.fillStyle='rgba(29,26,47,.6)';for(let i=0;i<8;i++){x.fillText('abcdefgh'[i],i*Q+Q-8,SZ-8);x.fillText(String(8-i),8,i*Q+10)}}
  let alive=true;c.on(cv,'pointerdown',e=>{if(over||turn!=='w'||thinking)return;const p=canvasPos(cv,e);const s=Math.floor(p.y/Q)*8+Math.floor(p.x/Q);const m=moves.find(q=>q.t===s);if(sel!=null&&m){sel=null;moves=[];play(m);return}if(B[s]&&col(B[s])==='w'){sel=s;moves=legal('w').filter(q=>q.f===s)}else{sel=null;moves=[]}draw()});
  nb.addEventListener('click',reset);ub.addEventListener('click',()=>{if(thinking||hist.length<2)return;unmake(hist.pop());unmake(hist.pop());sel=null;moves=[];over=false;upd()});
  reset();return()=>{alive=false}}});
/* ---------- Checkers ---------- */
G.push({id:'checkers',name:'Master Checkers',kind:'board',levels:true,tint:'#F2352A',blurb:'Classic checkers against the computer. Jumps are mandatory, and reaching the far side crowns a king.',fmt:b=>b+' wins',
art:'<rect width="120" height="72" fill="#1D1A2F"/><g fill="#F2352A">'+[0,1,2,3,4,5].map(i=>[0,1,2].map(j=>(i+j)%2?'<rect x="'+(i*20)+'" y="'+(j*24)+'" width="20" height="24"/>':'').join('')).join('')+'</g><circle cx="30" cy="36" r="12" fill="#fff" stroke="#1D1A2F" stroke-width="3"/><circle cx="70" cy="36" r="12" fill="#3a3552" stroke="#fff" stroke-width="3"/><text x="70" y="41" font-size="14" text-anchor="middle" fill="#FFD23F">♛</text>',
run(root,c){
  const SZ=560,Q=SZ/8;const[cv,x]=mk(SZ,SZ,'width:min(100%,560px)');const status=el('p',{class:'hint',style:'font-weight:700'});const nb=el('button',{class:'btn',type:'button'},'New game');root.append(cv,status,el('div',{class:'row'},nb));
  let B,turn,sel=null,opts=[],over=false,busy=false,wins=S.get('chk_w',0),alive=true;
  function reset(){B=Array(64).fill(0);for(let s=0;s<64;s++){const r=s>>3,f=s&7;if((r+f)%2){if(r<3)B[s]=-1;else if(r>4)B[s]=1}}turn=1;sel=null;opts=[];over=false;upd()}
  function jumps(bd,s,side,path,caps,out){const p=bd[s];const king=Math.abs(p)===2;const dirs=king?[-1,1]:[side===1?-1:1];let found=false;for(const dr of dirs)for(const df of[-1,1]){const r=(s>>3)+dr,f=(s&7)+df,r2=r+dr,f2=f+df;if(r2<0||r2>7||f2<0||f2>7)continue;const m=r*8+f,t=r2*8+f2;if(bd[m]&&Math.sign(bd[m])===-side&&!caps.includes(m)&&!bd[t]){found=true;const nb=bd.slice();nb[t]=nb[s];nb[s]=0;jumps(nb,t,side,path.concat(t),caps.concat(m),out)}}if(!found&&caps.length)out.push({path,caps})}
  function allMoves(bd,side){const J=[],M=[];for(let s=0;s<64;s++){if(Math.sign(bd[s])!==side)continue;const out=[];jumps(bd,s,side,[s],[],out);J.push(...out);const king=Math.abs(bd[s])===2;const dirs=king?[-1,1]:[side===1?-1:1];for(const dr of dirs)for(const df of[-1,1]){const r=(s>>3)+dr,f=(s&7)+df;if(r<0||r>7||f<0||f>7)continue;const t=r*8+f;if(!bd[t])M.push({path:[s,t],caps:[]})}}return J.length?J:M}
  function apply(bd,m){const nb=bd.slice();const s=m.path[0],t=m.path[m.path.length-1];nb[t]=nb[s];nb[s]=0;m.caps.forEach(q=>nb[q]=0);if(nb[t]===1&&t<8)nb[t]=2;if(nb[t]===-1&&t>55)nb[t]=-2;return nb}
  function ev(bd){let s=0;for(let i=0;i<64;i++){const p=bd[i];if(!p)continue;const r=i>>3;s+=p===1?100+(7-r)*3:p===2?170:p===-1?-(100+r*3):-170}return s}
  function mm(bd,d,a,b,side){const ms=allMoves(bd,side);if(!ms.length)return side===1?-9999:9999;if(d===0)return ev(bd);if(side===1){let v=-1e9;for(const m of ms){v=Math.max(v,mm(apply(bd,m),d-1,a,b,-1));a=Math.max(a,v);if(a>=b)break}return v}else{let v=1e9;for(const m of ms){v=Math.min(v,mm(apply(bd,m),d-1,a,b,1));b=Math.min(b,v);if(a>=b)break}return v}}
  function ai(){const ms=allMoves(B,-1);if(!ms.length)return;const d=c.pick(2,4,6);let best=null,bv=1e9;shuffle(ms).forEach(m=>{const v=mm(apply(B,m),d-1,-1e9,1e9,1)+(c.level===0?Math.random()*40:0);if(v<bv){bv=v;best=m}});B=apply(B,best);beep(best.caps.length?300:500,.06,'triangle',.05);turn=1;upd()}
  function upd(){const ms=allMoves(B,turn);if(!ms.length){over=true;status.textContent=turn===1?'No moves left. The computer wins.':'You win! 🎉';if(turn===-1){wins++;S.set('chk_w',wins);c.best(wins)}}else status.textContent=turn===1?'Your move (white pieces, moving up)'+(ms[0].caps.length?' · you must jump!':''):'Computer is thinking…';c.stat('Checkers · wins '+wins);draw();if(!over&&turn===-1){busy=true;setTimeout(()=>{if(alive){ai();busy=false}},350)}}
  function draw(){for(let s=0;s<64;s++){const r=s>>3,f=s&7;x.fillStyle=(r+f)%2?'#3a3552':'#e8c48a';x.fillRect(f*Q,r*Q,Q,Q)}if(sel!=null){x.fillStyle='rgba(110,231,183,.5)';x.fillRect((sel&7)*Q,(sel>>3)*Q,Q,Q)}opts.forEach(m=>{const t=m.path[m.path.length-1];x.fillStyle='rgba(255,210,63,.55)';x.beginPath();x.arc((t&7)*Q+Q/2,(t>>3)*Q+Q/2,Q*.18,0,7);x.fill()});
    for(let s=0;s<64;s++){const p=B[s];if(!p)continue;const cx=(s&7)*Q+Q/2,cy=(s>>3)*Q+Q/2;x.fillStyle='rgba(0,0,0,.35)';x.beginPath();x.arc(cx+2,cy+4,Q*.38,0,7);x.fill();x.fillStyle=p>0?'#fffdf6':'#F2352A';x.strokeStyle='#1D1A2F';x.lineWidth=3;x.beginPath();x.arc(cx,cy,Q*.38,0,7);x.fill();x.stroke();x.beginPath();x.arc(cx,cy,Q*.26,0,7);x.stroke();if(Math.abs(p)===2){x.fillStyle='#FFD23F';x.font=(Q*.4)+'px serif';x.textAlign='center';x.textBaseline='middle';x.fillText('♛',cx,cy+2)}}}
  c.on(cv,'pointerdown',e=>{if(over||turn!==1||busy)return;const p=canvasPos(cv,e);const s=Math.floor(p.y/Q)*8+Math.floor(p.x/Q);const m=opts.find(q=>q.path[q.path.length-1]===s);if(sel!=null&&m){B=apply(B,m);sel=null;opts=[];beep(m.caps.length?300:500,.06,'triangle',.05);turn=-1;upd();return}if(B[s]>0){const all=allMoves(B,1);opts=all.filter(q=>q.path[0]===s);sel=opts.length?s:null}else{sel=null;opts=[]}draw()});
  nb.addEventListener('click',reset);reset();return()=>{alive=false}}});
/* ---------- Four Colors (card game) ---------- */
G.push({id:'fourcolors',name:'Four Colors',kind:'board',levels:true,tint:'#2BB673',blurb:'Match the color or the number, play skips, reverses and +2s, and empty your hand before three computer players.',fmt:b=>b+' wins',
art:'<rect width="120" height="72" fill="#2BB673"/><g stroke="#1D1A2F" stroke-width="2.5"><rect x="22" y="14" width="26" height="40" rx="5" fill="#F2352A" transform="rotate(-12 35 34)"/><rect x="40" y="12" width="26" height="40" rx="5" fill="#FFD23F" transform="rotate(-3 53 32)"/><rect x="58" y="12" width="26" height="40" rx="5" fill="#2d6fd6" transform="rotate(6 71 32)"/><rect x="76" y="14" width="26" height="40" rx="5" fill="#fff" transform="rotate(14 89 34)"/></g><text x="71" y="38" font-family="Arial Black" font-size="14" fill="#fff" text-anchor="middle" transform="rotate(6 71 32)">7</text>',
run(root,c){
  const W=900,H=560;const[cv,x]=mk(W,H,'width:100%');root.append(cv);const CC=['#F2352A','#FFD23F','#2BB673','#2d6fd6'],CN=['red','yellow','green','blue'];
  let deck,disc,hands,turn,dir,cur,state,pending=0,msg='',msgT=0,chooser=false,wins=S.get('fc_w',0),hover=-1,drewThisTurn=false;const NAMES=['You','Robo','Bubbles','Captain'];
  function newDeck(){const d=[];for(let k=0;k<4;k++){d.push({c:k,v:0});for(let v=1;v<=9;v++){d.push({c:k,v},{c:k,v})}['skip','rev','+2'].forEach(s=>d.push({c:k,v:s},{c:k,v:s}))}for(let i=0;i<4;i++)d.push({c:-1,v:'wild'},{c:-1,v:'+4'});return shuffle(d)}
  const draw1=()=>{if(!deck.length){const top=disc.pop();deck=shuffle(disc.map(q=>q.v==='wild'||q.v==='+4'?{c:-1,v:q.v}:q));disc=[top]}return deck.pop()};
  function start(){deck=newDeck();hands=[[],[],[],[]];for(let i=0;i<7;i++)hands.forEach(h=>h.push(draw1()));let top=draw1();while(top.c<0){deck.unshift(top);top=draw1()}disc=[top];cur=top.c;turn=0;dir=1;state='play';chooser=false;drewThisTurn=false;msg='Your turn';msgT=2}
  const top=()=>disc[disc.length-1];const ok=cd=>cd.c<0||cd.c===cur||cd.v===top().v;
  function next(skip){turn=(turn+dir*(skip?2:1)+8)%4;drewThisTurn=false;if(turn!==0)setTimeout(aiTurn,c.pick(900,700,550))}
  function playCard(p,i,chosen){const cd=hands[p].splice(i,1)[0];disc.push(cd);cur=cd.c<0?chosen:cd.c;beep(500+p*80,.07,'triangle',.05);
    if(!hands[p].length){state='over';if(p===0){wins++;S.set('fc_w',wins);c.best(wins)}msg=p===0?'You win! 🎉':NAMES[p]+' wins!';msgT=99;return}if(hands[p].length===1){msg=NAMES[p]+': FOUR!';msgT=1.4;beep(900,.2,'square',.05)}
    let skip=false;if(cd.v==='skip')skip=true;if(cd.v==='rev'){dir*=-1;msg='Reverse!';msgT=1}if(cd.v==='+2'||cd.v==='+4'){const vic=(turn+dir+4)%4;for(let k=0;k<(cd.v==='+2'?2:4);k++)hands[vic].push(draw1());msg=NAMES[vic]+' draws '+(cd.v==='+2'?2:4)+'!';msgT=1.2;skip=true}next(skip)}
  function aiTurn(){if(state!=='play'||turn===0)return;const h=hands[turn];const lvl=c.level;let idx=h.map((q,i)=>i).filter(i=>ok(h[i]));if(!idx.length){h.push(draw1());const i=h.length-1;if(ok(h[i])){idx=[i]}else{next(false);return}}
    idx.sort((a,b)=>{const s=q=>(q.c<0?-3:0)+(typeof q.v==='string'?(lvl>0?2:0):0)+(lvl>1&&hands[0].length<=2&&(q.v==='+2'||q.v==='+4'||q.v==='skip')?9:0);return s(h[b])-s(h[a])});const i=lvl===0?pick(idx):idx[0];let ch=0;if(h[i].c<0){const cnt=[0,0,0,0];h.forEach(q=>{if(q.c>=0)cnt[q.c]++});ch=cnt.indexOf(Math.max(...cnt))}playCard(turn,i,ch)}
  function cardAt(i,n){const w=64,gap=Math.min(70,(W-160)/Math.max(1,n));const x0=W/2-(gap*(n-1)+w)/2;return{x:x0+i*gap,y:H-120,w,h:96}}
  function card(cd,px,py,w,h,faceUp,lift){x.save();x.translate(px,py-(lift?14:0));x.fillStyle='rgba(0,0,0,.25)';x.fillRect(3,4,w,h);x.fillStyle=faceUp?(cd.c<0?'#1D1A2F':CC[cd.c]):'#1D1A2F';x.strokeStyle='#fff';x.lineWidth=3;x.beginPath();x.roundRect?x.roundRect(0,0,w,h,8):x.rect(0,0,w,h);x.fill();x.stroke();
    if(faceUp){x.fillStyle='#fff';x.beginPath();x.ellipse(w/2,h/2,w*.36,h*.3,-.5,0,7);x.fill();const lab=cd.v==='rev'?'⇄':cd.v==='skip'?'⊘':cd.v==='wild'?'★':String(cd.v);x.fillStyle=cd.c<0?'#1D1A2F':CC[cd.c];x.font='900 '+(lab.length>1?20:28)+'px Figtree, sans-serif';x.textAlign='center';x.textBaseline='middle';x.fillText(lab,w/2,h/2+1);if(cd.c<0){CC.forEach((cl,k)=>{x.fillStyle=cl;x.fillRect(6+k*((w-12)/4),h-14,(w-12)/4,8)})}x.fillStyle='#fff';x.font='800 12px Figtree';x.textAlign='left';x.fillText(lab,6,14)}else{x.fillStyle='#F2352A';x.font='900 14px Figtree';x.textAlign='center';x.fillText('4C',w/2,h/2+5)}x.restore()}
  function render(){x.fillStyle='#1f7a45';x.fillRect(0,0,W,H);x.fillStyle='rgba(255,255,255,.06)';x.beginPath();x.ellipse(W/2,H/2-20,300,170,0,0,7);x.fill();
    [[1,70,H/2-60,'v'],[2,W/2,40,'h'],[3,W-70,H/2-60,'v']].forEach(([p,cx2,cy2,o])=>{const n=hands[p].length;for(let i=0;i<Math.min(n,12);i++){if(o==='v')card(null,cx2-24,cy2-60+i*10,48,70,false);else card(null,cx2-n*8+i*16-24,cy2,48,70,false)}x.fillStyle=turn===p&&state==='play'?'#FFD23F':'#fff';x.font='800 14px Figtree';x.textAlign='center';x.fillText(NAMES[p]+' · '+n,o==='v'?cx2:cx2,o==='v'?cy2+100:cy2+92)});
    card(null,W/2-90,H/2-80,70,100,false);x.fillStyle='#fff';x.font='700 12px Figtree';x.textAlign='center';x.fillText('DRAW',W/2-55,H/2+36);card(top(),W/2+10,H/2-80,70,100,true);x.fillStyle=CC[cur];x.beginPath();x.arc(W/2+120,H/2-30,16,0,7);x.fill();x.strokeStyle='#fff';x.lineWidth=3;x.stroke();x.fillStyle='#fff';x.font='700 12px Figtree';x.fillText(CN[cur],W/2+120,H/2+2);x.fillText(dir>0?'↻':'↺',W/2+120,H/2-60);
    hands[0].forEach((cd,i)=>{const r=cardAt(i,hands[0].length);card(cd,r.x,r.y,r.w,r.h,true,i===hover&&turn===0&&ok(cd))});
    if(turn===0&&state==='play'&&!chooser){x.fillStyle='#FFD23F';x.font='800 15px Figtree';x.textAlign='center';x.fillText(drewThisTurn?'Play the card you drew, or click the draw pile to pass':'Your turn: click a matching card, or click the draw pile',W/2,H-138)}
    if(chooser){x.fillStyle='rgba(0,0,0,.6)';x.fillRect(0,0,W,H);CC.forEach((cl,k)=>{x.fillStyle=cl;x.fillRect(W/2-170+k*88,H/2-40,76,76);x.strokeStyle='#fff';x.strokeRect(W/2-170+k*88,H/2-40,76,76)});x.fillStyle='#fff';x.font='800 20px Figtree';x.textAlign='center';x.fillText('Pick a color',W/2,H/2-60)}
    if(msgT>0){x.fillStyle='rgba(29,26,47,.75)';x.fillRect(W/2-170,H/2+40,340,40);x.fillStyle='#FFD23F';x.font='800 20px Figtree';x.textAlign='center';x.fillText(msg,W/2,H/2+67)}if(state==='over')banner(x,W,H,msg,'Click to deal again');c.stat('Four Colors · wins '+wins)}
  let pendingI=-1;c.on(cv,'pointermove',e=>{const p=canvasPos(cv,e);hover=-1;hands&&hands[0].forEach((cd,i)=>{const r=cardAt(i,hands[0].length);if(p.x>r.x&&p.x<r.x+Math.min(r.w,cardAt(i+1,hands[0].length).x-r.x||r.w)&&p.y>r.y-14&&p.y<r.y+r.h)hover=i})});
  c.on(cv,'pointerdown',e=>{const p=canvasPos(cv,e);if(state==='over'){start();return}if(turn!==0)return;if(chooser){for(let k=0;k<4;k++){if(p.x>W/2-170+k*88&&p.x<W/2-94+k*88&&p.y>H/2-40&&p.y<H/2+36){chooser=false;playCard(0,pendingI,k);return}}return}
    if(p.x>W/2-90&&p.x<W/2-20&&p.y>H/2-80&&p.y<H/2+20){if(drewThisTurn){next(false);return}hands[0].push(draw1());drewThisTurn=true;beep(400,.05,'triangle',.04);if(!ok(hands[0][hands[0].length-1]))next(false);return}
    for(let i=hands[0].length-1;i>=0;i--){const r=cardAt(i,hands[0].length);if(p.x>r.x&&p.x<r.x+r.w&&p.y>r.y-14&&p.y<r.y+r.h){const cd=hands[0][i];if(!ok(cd)){beep(180,.08,'square',.04);return}if(drewThisTurn&&i!==hands[0].length-1)return;if(cd.c<0){chooser=true;pendingI=i}else playCard(0,i,cd.c);return}}});
  start();c.loop(dt=>{if(msgT>0&&msgT<50)msgT-=dt/1000;render()})}});
