/* ================= BOARD & CLASSIC 2 ================= */
if(typeof CanvasRenderingContext2D!=='undefined'&&!CanvasRenderingContext2D.prototype.roundRect)CanvasRenderingContext2D.prototype.roundRect=function(x,y,w,h,r){r=Math.min(r,w/2,h/2);this.moveTo(x+r,y);this.arcTo(x+w,y,x+w,y+h,r);this.arcTo(x+w,y+h,x,y+h,r);this.arcTo(x,y+h,x,y,r);this.arcTo(x,y,x+w,y,r);this.closePath();return this};
/* ---- Solitaire (Klondike) ---- */
G.push({id:'solitaire',name:'Solitaire',kind:'board',levels:true,tint:'#2BB673',blurb:'Classic Klondike solitaire. Build the four suits up from Ace to King. Tap a card, then tap where it should go.',fmt:b=>b+' wins',
art:'<rect width="120" height="72" fill="#2BB673"/><g stroke="#1D1A2F" stroke-width="2"><rect x="16" y="14" width="26" height="36" rx="3" fill="#fff"/><rect x="36" y="22" width="26" height="36" rx="3" fill="#fff"/><rect x="56" y="30" width="26" height="36" rx="3" fill="#fff"/><rect x="86" y="10" width="22" height="30" rx="3" fill="#2d6fd6"/></g><text x="21" y="28" font-family="Arial Black" font-size="11" fill="#F2352A">A♥</text><text x="41" y="36" font-family="Arial Black" font-size="11" fill="#1D1A2F">K♠</text><text x="61" y="44" font-family="Arial Black" font-size="11" fill="#F2352A">Q♦</text>',
run(root,c){const W=760,H=640,CW=90,CH=124,GAP=(W-7*CW)/8;const[cv,x]=mk(W,H,'width:min(100%,760px);touch-action:manipulation');const row=el('div',{class:'row'});const nb=el('button',{class:'btn',type:'button'},'New game'),ub=el('button',{class:'btn',type:'button'},'↶ Undo'),ab=el('button',{class:'btn',type:'button'},'⚡ Auto-finish');row.append(nb,ub,ab);root.append(cv,row,el('p',{class:'hint'},c.pick('Easy: draw 1, unlimited passes.','Normal: draw 1.','Hard: draw 3.')+' Tap a card to pick it up, then tap a pile to drop it. Double-tap sends a card to the foundations.'));
  const SU=['♠','♥','♦','♣'],RK=['A','2','3','4','5','6','7','8','9','10','J','Q','K'];const red=s=>s===1||s===2;const draw=c.pick(1,1,3);
  let stock,waste,found,tab,sel=null,hist=[],moves=0,won=false,t0=0,lastTap={t:0,k:''},anim=[];
  function deal(){const d=[];for(let s=0;s<4;s++)for(let r=0;r<13;r++)d.push({s,r,up:false});shuffle(d);tab=[];for(let i=0;i<7;i++){tab.push(d.splice(0,i+1));tab[i][i].up=true}stock=d;waste=[];found=[[],[],[],[]];sel=null;hist=[];moves=0;won=false;t0=performance.now();c.stat('Solitaire · new deal')}
  const snap=()=>JSON.stringify({stock,waste,found,tab});function save(){hist.push(snap());if(hist.length>200)hist.shift()}
  const tx=i=>GAP+i*(CW+GAP),TY=170;
  function tabY(col,k){let y=TY;for(let j=0;j<k;j++)y+=col[j].up?(col.length>12?24:30):12;return y}
  function hitTest(px,py){if(py>=20&&py<=20+CH){if(px>=tx(0)&&px<=tx(0)+CW)return{p:'stock'};if(px>=tx(1)&&px<=tx(1)+CW+(draw===3?40:0))return{p:'waste'};for(let f=0;f<4;f++)if(px>=tx(3+f)&&px<=tx(3+f)+CW)return{p:'found',i:f}}
    for(let i=0;i<7;i++){if(px<tx(i)||px>tx(i)+CW)continue;const col=tab[i];if(!col.length)return py>=TY?{p:'tab',i,k:0,empty:true}:null;for(let k=col.length-1;k>=0;k--){const y=tabY(col,k);if(py>=y&&py<=y+CH)return{p:'tab',i,k}}return py>=TY?{p:'tab',i,k:col.length-1,below:true}:null}return null}
  const canFound=(card,f)=>{const F=found[f];return F.length?F[F.length-1].s===card.s&&F[F.length-1].r===card.r-1:card.r===0};
  const canTab=(card,i)=>{const col=tab[i];if(!col.length)return card.r===12;const t=col[col.length-1];return t.up&&red(t.s)!==red(card.s)&&t.r===card.r+1};
  function selCards(){if(!sel)return[];if(sel.p==='waste')return[waste[waste.length-1]];if(sel.p==='found')return[found[sel.i][found[sel.i].length-1]];return tab[sel.i].slice(sel.k)}
  function removeSel(){if(sel.p==='waste')waste.pop();else if(sel.p==='found')found[sel.i].pop();else{tab[sel.i].splice(sel.k);const col=tab[sel.i];if(col.length&&!col[col.length-1].up){col[col.length-1].up=true}}}
  function toFound(src){const cards=src==='waste'?[waste[waste.length-1]]:null;return cards}
  function autoOne(from){const card=from.p==='waste'?waste[waste.length-1]:from.p==='tab'?tab[from.i][tab[from.i].length-1]:null;if(!card||!card.up)return false;for(let f=0;f<4;f++)if(canFound(card,f)){save();sel=from.p==='waste'?{p:'waste'}:{p:'tab',i:from.i,k:tab[from.i].length-1};removeSel();found[f].push(card);sel=null;moves++;beep(700+card.r*30,.05,'triangle',.04);return true}return false}
  function tap(px,py){if(won){deal();return}const h=hitTest(px,py);if(!h){sel=null;return}const now=performance.now();const key=h.p+(h.i??'')+(h.k??'');const dbl=now-lastTap.t<380&&lastTap.k===key;lastTap={t:now,k:key};
    if(h.p==='stock'){sel=null;save();if(stock.length){for(let k=0;k<draw&&stock.length;k++){const cd=stock.pop();cd.up=true;waste.push(cd)}beep(400,.03,'triangle',.03)}else if(waste.length){stock=waste.reverse().map(cd=>(cd.up=false,cd));waste=[];beep(250,.05,'triangle',.03)}moves++;return}
    if(dbl&&(h.p==='waste'||(h.p==='tab'&&h.k===tab[h.i].length-1))){sel=null;autoOne(h);checkWin();return}
    if(sel){const cards=selCards();let ok=false;if(h.p==='found'&&cards.length===1&&canFound(cards[0],h.i)){save();removeSel();found[h.i].push(cards[0]);ok=true}else if(h.p==='tab'&&!(sel.p==='tab'&&sel.i===h.i)&&canTab(cards[0],h.i)){save();removeSel();tab[h.i].push(...cards);ok=true}
      if(ok){moves++;beep(600,.04,'triangle',.04);sel=null;checkWin();return}sel=null}
    if(h.p==='waste'&&waste.length)sel={p:'waste'};else if(h.p==='found'&&found[h.i].length)sel={p:'found',i:h.i};else if(h.p==='tab'&&!h.empty){const cd=tab[h.i][h.k];if(cd&&cd.up)sel={p:'tab',i:h.i,k:h.k};else if(cd&&!cd.up&&h.k===tab[h.i].length-1){save();cd.up=true}}}
  function checkWin(){if(found.every(f=>f.length===13)){won=true;const n=c.best((S.get('sol_w',0)||0)+1);S.set('sol_w',(S.get('sol_w',0)||0)+1);[523,659,784,1046].forEach((q,i)=>c.after(()=>beep(q,.15,'triangle',.06),i*110));c.stat('Solitaire · won in '+moves+' moves!')}}
  function autoFinish(){let guard=0;const step=()=>{if(guard++>60)return;let did=false;if(waste.length&&autoOne({p:'waste'}))did=true;else for(let i=0;i<7;i++)if(tab[i].length&&autoOne({p:'tab',i})){did=true;break}if(!did&&stock.length&&tab.every(col=>col.every(cd=>cd.up))){for(let k=0;k<draw&&stock.length;k++){const cd=stock.pop();cd.up=true;waste.push(cd)}did=true}else if(!did&&!stock.length&&waste.length&&tab.every(col=>col.every(cd=>cd.up))){stock=waste.reverse().map(cd=>(cd.up=false,cd));waste=[];did=true}if(did){checkWin();if(!won)c.after(step,70)}};step()}
  nb.addEventListener('click',deal);ub.addEventListener('click',()=>{if(hist.length){const o=JSON.parse(hist.pop());stock=o.stock;waste=o.waste;found=o.found;tab=o.tab;sel=null}});ab.addEventListener('click',autoFinish);
  c.on(cv,'pointerdown',e=>{e.preventDefault();const p=canvasPos(cv,e);tap(p.x,p.y)});
  function card(cd,px,py,hi){x.save();x.shadowColor='rgba(0,0,0,.25)';x.shadowBlur=4;x.shadowOffsetY=2;x.fillStyle=cd.up?'#fffdf6':'#2d6fd6';x.beginPath();x.roundRect(px,py,CW,CH,8);x.fill();x.restore();x.strokeStyle=hi?'#FFD23F':'#1D1A2F';x.lineWidth=hi?4:2;x.beginPath();x.roundRect(px,py,CW,CH,8);x.stroke();
    if(!cd.up){x.strokeStyle='rgba(255,255,255,.35)';x.lineWidth=2;for(let k=8;k<CW+CH;k+=10){x.beginPath();x.moveTo(px+Math.min(k,CW-6),py+Math.max(6,k-CW+6));x.lineTo(px+Math.max(6,k-CH+6),py+Math.min(k,CH-6));x.stroke()}return}
    x.fillStyle=red(cd.s)?'#D8261C':'#1D1A2F';x.font='800 20px Figtree, sans-serif';x.textAlign='left';x.textBaseline='top';x.fillText(RK[cd.r],px+7,py+6);x.font='20px sans-serif';x.fillText(SU[cd.s],px+7,py+28);x.font='44px sans-serif';x.textAlign='center';x.textBaseline='middle';x.fillText(SU[cd.s],px+CW/2,py+CH/2+12);x.textBaseline='alphabetic'}
  function slot(px,py,t){x.strokeStyle='rgba(255,255,255,.5)';x.lineWidth=2;x.setLineDash([6,5]);x.beginPath();x.roundRect(px,py,CW,CH,8);x.stroke();x.setLineDash([]);if(t){x.fillStyle='rgba(255,255,255,.5)';x.font='36px sans-serif';x.textAlign='center';x.textBaseline='middle';x.fillText(t,px+CW/2,py+CH/2);x.textBaseline='alphabetic'}}
  c.loop(()=>{const g=x.createRadialGradient(W/2,H/2,100,W/2,H/2,600);g.addColorStop(0,'#2e9a58');g.addColorStop(1,'#1e6b3c');x.fillStyle=g;x.fillRect(0,0,W,H);
    if(stock.length)card(stock[stock.length-1],tx(0),20);else slot(tx(0),20,'↺');
    if(waste.length){const n=Math.min(draw,waste.length);for(let k=0;k<n;k++){const cd=waste[waste.length-n+k];card(cd,tx(1)+k*20,20,sel&&sel.p==='waste'&&k===n-1)}}else slot(tx(1),20);
    for(let f=0;f<4;f++){const F=found[f];if(F.length)card(F[F.length-1],tx(3+f),20,sel&&sel.p==='found'&&sel.i===f);else slot(tx(3+f),20,SU[f])}
    for(let i=0;i<7;i++){const col=tab[i];if(!col.length){slot(tx(i),TY,'K');continue}col.forEach((cd,k)=>card(cd,tx(i),tabY(col,k),sel&&sel.p==='tab'&&sel.i===i&&k>=sel.k))}
    x.fillStyle='rgba(255,255,255,.85)';x.font='700 14px Figtree, sans-serif';x.textAlign='left';x.fillText('Moves '+moves+' · '+Math.floor((performance.now()-t0)/1000)+'s · wins '+(S.get('sol_w',0)||0),GAP,H-12);
    if(won)banner(x,W,H,'You won!','Tap for a new deal')});
  deal()}});

/* ---- Battleship ---- */
G.push({id:'battleship',name:'Battleship',kind:'board',levels:true,tint:'#2d6fd6',blurb:'Hide your fleet, hunt down the computer’s ships, and sink them all before it finds yours.',fmt:b=>b+' wins',
art:'<rect width="120" height="72" fill="#2d6fd6"/><g stroke="rgba(255,255,255,.35)"><path d="M0 18h120M0 36h120M0 54h120M30 0v72M60 0v72M90 0v72"/></g><rect x="34" y="40" width="52" height="10" rx="5" fill="#8c86a3" stroke="#1D1A2F" stroke-width="2"/><rect x="52" y="32" width="14" height="8" fill="#8c86a3" stroke="#1D1A2F" stroke-width="2"/><circle cx="96" cy="18" r="6" fill="#F2352A"/><circle cx="18" cy="56" r="4" fill="#fff"/>',
run(root,c){const N=10,SHIPS=[5,4,3,3,2];const wrap=el('div',{style:'display:flex;flex-wrap:wrap;gap:14px;justify-content:center;width:100%'});const msg=el('p',{class:'big-text',style:'text-align:center;min-height:1.4em'});const row=el('div',{class:'row'});const sh=el('button',{class:'btn',type:'button'},'🔀 Move my ships'),ng=el('button',{class:'btn primary',type:'button'},'New game');row.append(sh,ng);
  root.append(msg,wrap,row,el('p',{class:'hint'},'Tap a square on the enemy waters to fire. Red means hit, white means miss. '+c.pick('Easy: the computer fires randomly.','Normal: the computer hunts around hits.','Hard: the computer hunts smart and never wastes shots.')));
  let me,ai,turn,over,started,aiQ=[];
  function place(){const g=Array(N*N).fill(-1);const ships=[];SHIPS.forEach((L,si)=>{for(let t=0;t<500;t++){const hz=Math.random()<.5,x0=rand(hz?N-L+1:N),y0=rand(hz?N:N-L+1);const cells=[];for(let k=0;k<L;k++)cells.push((y0+(hz?0:k))*N+x0+(hz?k:0));if(cells.every(i=>g[i]<0)){cells.forEach(i=>g[i]=si);ships.push({cells,hits:0});break}}});return{g,ships,shot:Array(N*N).fill(0)}}
  function grid(title,enemy){const box=el('div',{style:'flex:1 1 300px;max-width:420px'});box.append(el('h4',{style:'margin:0 0 6px;text-align:center'},title));const gd=el('div',{style:'display:grid;grid-template-columns:repeat(10,1fr);gap:2px;background:#1D1A2F;border:3px solid #1D1A2F;border-radius:8px;overflow:hidden'});const cells=[];for(let i=0;i<N*N;i++){const b=el('button',{type:'button','aria-label':(enemy?'enemy ':'my ')+'square '+(i%N+1)+','+(Math.floor(i/N)+1),style:'aspect-ratio:1;border:0;padding:0;background:#7FC8F8;font-size:clamp(10px,2.4vw,18px);cursor:'+(enemy?'crosshair':'default')});if(enemy)b.addEventListener('click',()=>fire(i));cells.push(b);gd.append(b)}box.append(gd);wrap.append(box);return cells}
  let myC,aiC;function build(){wrap.innerHTML='';myC=grid('Your fleet',false);aiC=grid('Enemy waters',true)}
  function paint(){for(let i=0;i<N*N;i++){const m=me.g[i],s=me.shot[i];myC[i].style.background=s?(m>=0?(me.ships[m].hits>=me.ships[m].cells.length?'#5A5470':'#F2352A'):'#dbe9f7'):(m>=0?'#8c86a3':'#7FC8F8');myC[i].textContent=s?(m>=0?'💥':'•'):'';const a=ai.g[i],t=ai.shot[i];aiC[i].style.background=t?(a>=0?(ai.ships[a].hits>=ai.ships[a].cells.length?'#5A5470':'#F2352A'):'#dbe9f7'):(over&&a>=0?'#b9c7d8':'#7FC8F8');aiC[i].textContent=t?(a>=0?'💥':'•'):''}
    const left=b=>b.ships.filter(s2=>s2.hits<s2.cells.length).length;if(!over)msg.textContent=turn==='me'?'Your turn: fire! (enemy ships left: '+left(ai)+')':'Enemy is aiming…'}
  function newGame(){me=place();ai=place();turn='me';over=false;started=false;aiQ=[];build();paint()}
  function hit(b,i){b.shot[i]=1;const s=b.g[i];if(s<0)return'miss';const sh2=b.ships[s];sh2.hits++;return sh2.hits>=sh2.cells.length?'sunk':'hit'}
  function fire(i){if(over||turn!=='me'||ai.shot[i])return;started=true;const r=hit(ai,i);beep(r==='miss'?300:r==='sunk'?120:180,.15,r==='miss'?'sine':'sawtooth',.06);if(r!=='miss')noise(.3,'lowpass',400,.3);msg.textContent=r==='sunk'?'💥 You sunk a ship!':r==='hit'?'💥 Hit!':'Splash, miss.';
    if(ai.ships.every(s2=>s2.hits>=s2.cells.length)){over=true;paint();msg.textContent='🏆 You sank the whole fleet!';const w=(S.get('bs_w',0)||0)+1;S.set('bs_w',w);c.best(w);return}turn='ai';paint();c.after(aiTurn,650)}
  function aiPick(){const lvl=c.level;const free=[];for(let i=0;i<N*N;i++)if(!me.shot[i])free.push(i);if(lvl===0)return pick(free);
    aiQ=aiQ.filter(i=>!me.shot[i]);if(aiQ.length)return aiQ.shift();if(lvl===2){const par=free.filter(i=>((i%N)+Math.floor(i/N))%2===0);if(par.length)return pick(par)}return pick(free)}
  function aiTurn(){if(over)return;const i=aiPick();const r=hit(me,i);if(r!=='miss'){noise(.3,'lowpass',300,.3);const x0=i%N,y0=Math.floor(i/N);const nb=[[1,0],[-1,0],[0,1],[0,-1]].map(([dx,dy])=>[x0+dx,y0+dy]).filter(([a,b])=>a>=0&&b>=0&&a<N&&b<N).map(([a,b])=>b*N+a).filter(j=>!me.shot[j]);if(r==='hit'){if(c.level===2){const prevHits=aiQ.length?[]:[];aiQ=nb.concat(aiQ)}else aiQ=aiQ.concat(nb)}else if(r==='sunk'&&c.level===2)aiQ=[]}
    if(me.ships.every(s2=>s2.hits>=s2.cells.length)){over=true;paint();msg.textContent='The computer sank your fleet. Try again!';return}turn='me';paint()}
  sh.addEventListener('click',()=>{if(started){msg.textContent='You can only move ships before the first shot.';return}me=place();paint()});ng.addEventListener('click',newGame);newGame();c.stat('Battleship')}});

/* ---- Mancala ---- */
G.push({id:'mancala',name:'Mancala',kind:'board',levels:true,tint:'#8a5a2b',blurb:'The ancient seed-sowing game. Scoop a pit, sow the seeds around the board, capture your rival’s seeds, and fill your store.',fmt:b=>b+' wins',
art:'<rect width="120" height="72" fill="#FFE27A"/><rect x="6" y="14" width="108" height="44" rx="22" fill="#b07a44" stroke="#1D1A2F" stroke-width="2.5"/><g fill="#6b4524"><ellipse cx="18" cy="36" rx="7" ry="16"/><ellipse cx="102" cy="36" rx="7" ry="16"/><circle cx="36" cy="27" r="6"/><circle cx="52" cy="27" r="6"/><circle cx="68" cy="27" r="6"/><circle cx="84" cy="27" r="6"/><circle cx="36" cy="45" r="6"/><circle cx="52" cy="45" r="6"/><circle cx="68" cy="45" r="6"/><circle cx="84" cy="45" r="6"/></g><g fill="#6EE7B7"><circle cx="35" cy="45" r="2"/><circle cx="38" cy="47" r="2"/><circle cx="52" cy="27" r="2"/></g>',
run(root,c){const W=820,H=360;const[cv,x]=mk(W,H,'width:100%');const msg=el('p',{class:'big-text',style:'text-align:center;min-height:1.4em'});const nb=el('button',{class:'btn',type:'button'},'New game');root.append(msg,cv,nb,el('p',{class:'hint'},'Tap one of your pits (bottom row). Seeds are sown one per pit, counter-clockwise, into your store but not the computer’s. Land in your store: go again. Land in an empty pit on your side: capture the seeds opposite. Most seeds wins.'));
  // indices: 0-5 player pits, 6 player store, 7-12 ai pits, 13 ai store
  let B,turn,busy=false,hl=-1,seedCols=[];const COLS=['#6EE7B7','#FF8FB1','#FFD23F','#7FC8F8','#B9A7FF','#FF9F43','#F2352A'];
  function reset(){B=[4,4,4,4,4,4,0,4,4,4,4,4,4,0];turn=0;busy=false;msg.textContent='Your turn: tap a pit on the bottom row.';seedCols=Array(14).fill(0).map(()=>Array.from({length:60},()=>pick(COLS)))}
  function sim(b,p,pit){b=b.slice();let n=b[pit];b[pit]=0;let i=pit;while(n>0){i=(i+1)%14;if(p===0&&i===13)continue;if(p===1&&i===6)continue;b[i]++;n--}let extra=false;if(p===0&&i===6)extra=true;if(p===1&&i===13)extra=true;
    if(!extra&&b[i]===1&&(p===0?i<6:i>6&&i<13)){const op=12-i;if(b[op]>0){b[p===0?6:13]+=b[op]+1;b[op]=0;b[i]=0}}
    let over=false;const s0=b.slice(0,6).reduce((a,v)=>a+v,0),s1=b.slice(7,13).reduce((a,v)=>a+v,0);if(s0===0||s1===0){b[6]+=s0;b[13]+=s1;for(let k=0;k<6;k++){b[k]=0;b[k+7]=0}over=true}return{b,extra,over,last:i}}
  const moves=(b,p)=>{const r=[];for(let k=0;k<6;k++){const i=p===0?k:k+7;if(b[i]>0)r.push(i)}return r};
  function mm(b,p,d,a,bb){const ms=moves(b,p);if(d===0||!ms.length)return b[13]-b[6];let best=p===1?-1e9:1e9;for(const m of ms){const r=sim(b,p,m);const np=r.over?p:(r.extra?p:1-p);const v=r.over?(r.b[13]-r.b[6])*10:mm(r.b,np,d-1,a,bb);if(p===1){if(v>best)best=v;a=Math.max(a,v)}else{if(v<best)best=v;bb=Math.min(bb,v)}if(a>=bb)break}return best}
  function aiMove(){const ms=moves(B,1);const depth=c.pick(1,4,7);let best=null,bv=-1e9;for(const m of ms){const r=sim(B,1,m);const v=r.over?(r.b[13]-r.b[6])*10:mm(r.b,r.extra?1:0,depth,-1e9,1e9)+(c.level===0?(Math.random()-.5)*12:0);if(v>bv){bv=v;best=m}}return best}
  function play(pit,p){busy=true;hl=pit;const r=sim(B,p,pit);let n=B[pit];B[pit]=0;let i=pit;const steps=[];while(n>0){i=(i+1)%14;if(p===0&&i===13)continue;if(p===1&&i===6)continue;steps.push(i);n--}
    let k=0;const tick=()=>{if(k<steps.length){B[steps[k]]++;hl=steps[k];beep(500+k*40,.04,'triangle',.04);k++;c.after(tick,110)}else{B=r.b;hl=-1;if(r.over){finish();return}
        if(r.extra){msg.textContent=p===0?'Landed in your store: go again!':'The computer goes again…';}turn=r.extra?p:1-p;busy=false;if(turn===1){msg.textContent=r.extra&&p===1?'The computer goes again…':'Computer is thinking…';c.after(()=>{const m=aiMove();if(m!=null)play(m,1)},550)}else if(!r.extra)msg.textContent='Your turn.'}};tick()}
  function finish(){busy=true;const a=B[6],b=B[13];msg.textContent=a>b?'🏆 You win '+a+' to '+b+'!':a<b?'The computer wins '+b+' to '+a+'.':'A tie, '+a+' each!';if(a>b){const w=(S.get('man_w',0)||0)+1;S.set('man_w',w);c.best(w)}turn=-1}
  const pitPos=i=>i===6?{x:W-60,y:H/2,store:1}:i===13?{x:60,y:H/2,store:1}:i<6?{x:150+i*104,y:250}:{x:150+(12-i)*104,y:110};
  c.on(cv,'pointerdown',e=>{e.preventDefault();if(turn===-1){reset();return}if(busy||turn!==0)return;const p=canvasPos(cv,e);for(let k=0;k<6;k++){const q=pitPos(k);if(Math.hypot(p.x-q.x,p.y-q.y)<46&&B[k]>0){play(k,0);return}}});nb.addEventListener('click',reset);
  c.loop(()=>{x.fillStyle='#FFE27A';x.fillRect(0,0,W,H);x.fillStyle='#b07a44';x.strokeStyle='#1D1A2F';x.lineWidth=4;x.beginPath();x.roundRect(14,20,W-28,H-40,90);x.fill();x.stroke();
    for(let i=0;i<14;i++){const q=pitPos(i);x.fillStyle=i===hl?'#8a5a2b':'#6b4524';x.beginPath();if(q.store)x.ellipse(q.x,q.y,40,120,0,0,7);else x.arc(q.x,q.y,44,0,7);x.fill();if(turn===0&&!busy&&i<6&&B[i]>0){x.strokeStyle='#FFD23F';x.lineWidth=3;x.stroke()}
      const n=B[i];for(let k=0;k<Math.min(n,40);k++){const a=k*2.4,r=q.store?Math.min(30,4+k*1.1):Math.min(32,3+Math.sqrt(k)*7);const sx=q.x+Math.cos(a)*r*(q.store?.8:1),sy=q.y+Math.sin(a)*r*(q.store?2.6:1);x.fillStyle=seedCols[i][k%60];x.beginPath();x.arc(sx,sy,6,0,7);x.fill();x.strokeStyle='rgba(0,0,0,.35)';x.lineWidth=1.5;x.stroke()}
      x.fillStyle='#fff';x.font='800 20px Figtree, sans-serif';x.textAlign='center';x.fillText(n,q.x,q.store?q.y+150:(i<6?q.y+70:q.y-54))}
    x.fillStyle='#1D1A2F';x.font='800 15px Figtree, sans-serif';x.fillText('YOU ▶',W-60,H-8);x.fillText('◀ COMPUTER',80,16)});
  reset();c.stat('Mancala')}});

/* ---- Dots and Boxes ---- */
G.push({id:'dotsboxes',name:'Dots & Boxes',kind:'board',levels:true,tint:'#FF8FB1',blurb:'Take turns drawing lines. Close a box to claim it and go again. Don’t hand the computer a long chain!',fmt:b=>b+' wins',
art:'<rect width="120" height="72" fill="#FFFDF6"/><g fill="#1D1A2F"><circle cx="30" cy="16" r="3"/><circle cx="60" cy="16" r="3"/><circle cx="90" cy="16" r="3"/><circle cx="30" cy="46" r="3"/><circle cx="60" cy="46" r="3"/><circle cx="90" cy="46" r="3"/></g><rect x="30" y="16" width="30" height="30" fill="#FF8FB1" opacity=".6"/><g stroke="#2d6fd6" stroke-width="4"><path d="M30 16h30M30 16v30M60 16v30M30 46h30"/></g><path d="M60 16h30" stroke="#F2352A" stroke-width="4"/>',
run(root,c){const n=c.pick(4,5,6),W=560,H=560,M=60,step=(W-2*M)/n;const[cv,x]=mk(W,H,'width:min(100%,560px);touch-action:manipulation');const msg=el('p',{class:'big-text',style:'text-align:center;min-height:1.4em'});const nb=el('button',{class:'btn',type:'button'},'New game');root.append(msg,cv,nb,el('p',{class:'hint'},'Tap between two dots to draw a line. Finish the fourth side of a box to win it and take another turn.'));
  // edges: horizontal h[r][c] (r 0..n, c 0..n-1), vertical v[r][c] (r 0..n-1, c 0..n)
  let h,v,own,turn,score,last=null,over,busy;
  function reset(){h=Array.from({length:n+1},()=>Array(n).fill(0));v=Array.from({length:n},()=>Array(n+1).fill(0));own=Array.from({length:n},()=>Array(n).fill(0));turn=1;score=[0,0,0];over=false;busy=false;msg.textContent='Your turn (blue).'}
  const sides=(r,cc)=>h[r][cc]+h[r+1][cc]+v[r][cc]+v[r][cc+1];
  function apply(e,p){if(e.t==='h')h[e.r][e.c]=p;else v[e.r][e.c]=p;last=e;let got=0;const chk=(r,cc)=>{if(r>=0&&cc>=0&&r<n&&cc<n&&!own[r][cc]&&sides(r,cc)===4){own[r][cc]=p;got++}};if(e.t==='h'){chk(e.r-1,e.c);chk(e.r,e.c)}else{chk(e.r,e.c-1);chk(e.r,e.c)}score[p]+=got;return got}
  function all(){const r=[];for(let a=0;a<=n;a++)for(let b=0;b<n;b++)if(!h[a][b])r.push({t:'h',r:a,c:b});for(let a=0;a<n;a++)for(let b=0;b<=n;b++)if(!v[a][b])r.push({t:'v',r:a,c:b});return r}
  function boxesOf(e){return e.t==='h'?[[e.r-1,e.c],[e.r,e.c]]:[[e.r,e.c-1],[e.r,e.c]]}
  const valid=([r,cc])=>r>=0&&cc>=0&&r<n&&cc<n;
  function completes(e){return boxesOf(e).filter(valid).some(([r,cc])=>!own[r][cc]&&sides(r,cc)===3)}
  function risky(e){return boxesOf(e).filter(valid).some(([r,cc])=>!own[r][cc]&&sides(r,cc)===2)}
  function aiPick(){const es=all();const lvl=c.level;const comp=es.filter(completes);if(comp.length&&(lvl>0||Math.random()<.7))return pick(comp);const safe=es.filter(e=>!risky(e));if(safe.length&&lvl>0)return pick(safe);if(lvl<2)return pick(es);
    // hard: give away the smallest chain
    let best=null,bs=1e9;for(const e of es){const H0=h.map(r=>r.slice()),V0=v.map(r=>r.slice()),O0=own.map(r=>r.slice()),S0=score.slice();apply(e,2);let give=0;let guard=0;while(guard++<60){const cp=all().find(completes);if(!cp)break;give+=apply(cp,1)}h=H0;v=V0;own=O0;score=S0;if(give<bs){bs=give;best=e}}return best}
  function nearest(px,py){let best=null,bd=22;for(let a=0;a<=n;a++)for(let b=0;b<n;b++){const d=Math.hypot(px-(M+(b+.5)*step),py-(M+a*step));if(d<bd&&!h[a][b]){bd=d;best={t:'h',r:a,c:b}}}for(let a=0;a<n;a++)for(let b=0;b<=n;b++){const d=Math.hypot(px-(M+b*step),py-(M+(a+.5)*step));if(d<bd&&!v[a][b]){bd=d;best={t:'v',r:a,c:b}}}return best}
  function afterMove(got,p){beep(got?880:500,.06,'triangle',.05);if(score[1]+score[2]===n*n){over=true;msg.textContent=score[1]>score[2]?'🏆 You win '+score[1]+' to '+score[2]+'!':score[1]<score[2]?'The computer wins '+score[2]+' to '+score[1]+'.':'A tie!';if(score[1]>score[2]){const w=(S.get('db_w',0)||0)+1;S.set('db_w',w);c.best(w)}return}
    if(!got)turn=3-p;msg.textContent=turn===1?(got?'Box! Go again.':'Your turn (blue).'):'Computer’s turn…';if(turn===2){busy=true;c.after(aiStep,420)}}
  function aiStep(){if(over)return;const e=aiPick();const got=apply(e,2);busy=false;afterMove(got,2)}
  c.on(cv,'pointerdown',e=>{e.preventDefault();if(over){reset();return}if(busy||turn!==1)return;const p=canvasPos(cv,e);const ed=nearest(p.x,p.y);if(!ed)return;const got=apply(ed,1);afterMove(got,1)});nb.addEventListener('click',reset);
  c.loop(()=>{x.fillStyle='#FFFDF6';x.fillRect(0,0,W,H);for(let a=0;a<n;a++)for(let b=0;b<n;b++)if(own[a][b]){x.fillStyle=own[a][b]===1?'rgba(45,111,214,.3)':'rgba(242,53,42,.3)';x.fillRect(M+b*step+3,M+a*step+3,step-6,step-6);x.font=(step*.4|0)+'px sans-serif';x.textAlign='center';x.textBaseline='middle';x.fillText(own[a][b]===1?'😀':'🤖',M+(b+.5)*step,M+(a+.5)*step)}x.textBaseline='alphabetic';
    const line=(x1,y1,x2,y2,p,isLast)=>{x.strokeStyle=p===1?'#2d6fd6':p===2?'#F2352A':'rgba(29,26,47,.08)';x.lineWidth=p?7:5;x.lineCap='round';x.beginPath();x.moveTo(x1,y1);x.lineTo(x2,y2);x.stroke();if(isLast){x.strokeStyle='#FFD23F';x.lineWidth=2;x.stroke()}};
    for(let a=0;a<=n;a++)for(let b=0;b<n;b++)line(M+b*step,M+a*step,M+(b+1)*step,M+a*step,h[a][b],last&&last.t==='h'&&last.r===a&&last.c===b);for(let a=0;a<n;a++)for(let b=0;b<=n;b++)line(M+b*step,M+a*step,M+b*step,M+(a+1)*step,v[a][b],last&&last.t==='v'&&last.r===a&&last.c===b);
    x.fillStyle='#1D1A2F';for(let a=0;a<=n;a++)for(let b=0;b<=n;b++){x.beginPath();x.arc(M+b*step,M+a*step,6,0,7);x.fill()}
    x.font='800 20px Figtree, sans-serif';x.textAlign='left';x.fillStyle='#2d6fd6';x.fillText('You '+score[1],M,34);x.textAlign='right';x.fillStyle='#F2352A';x.fillText(score[2]+' Computer',W-M,34);if(over)banner(x,W,H,score[1]>score[2]?'You win!':score[1]<score[2]?'Computer wins':'Tie!','Tap to play again')});
  reset();c.stat('Dots & Boxes')}});
