/* ================= STRESS TOYS ================= */
G.push({id:'toy_screen',name:'Screen Smasher',kind:'smash',wide:true,tint:'#3a3552',blurb:'Wreck a fake computer desktop with a hammer, paintball gun, termites, a flamethrower and more. No real computers harmed.',fmt:b=>b+'%',
art:'<rect width="120" height="72" fill="#3a3552"/><rect x="14" y="8" width="92" height="52" rx="4" fill="#7FC8F8" stroke="#1D1A2F" stroke-width="3"/><rect x="22" y="16" width="40" height="28" fill="#FFFDF6" stroke="#1D1A2F" stroke-width="2"/><path d="M72 26l8 6-6 4 10 8M80 32l10-6M74 36l-8 10" stroke="#1D1A2F" stroke-width="2" fill="none"/><circle cx="92" cy="48" r="6" fill="#FF8FB1" stroke="#1D1A2F" stroke-width="1.5"/><circle cx="38" cy="38" r="4" fill="#2BB673"/><rect x="50" y="60" width="20" height="6" fill="#8c86a3" stroke="#1D1A2F" stroke-width="2"/>',
run(root,c){const W=960,H=600;const cv=el('canvas',{class:'board',width:W,height:H,style:'width:100%;cursor:crosshair;touch-action:none'});const bar=el('div',{class:'toolbar'});const note=el('p',{class:'hint'},'Pick a tool and click, hold or drag on the screen. Nothing here is real, so go wild.');root.append(cv,bar,note);const x=cv.getContext('2d');
  const base=document.createElement('canvas');base.width=W;base.height=H;const bx=base.getContext('2d');const dmg=document.createElement('canvas');dmg.width=W;dmg.height=H;const dx=dmg.getContext('2d');
  const T=[['hammer','🔨','Hammer'],['gun','🎯','Paintball'],['machine','💥','Rapid fire'],['flame','🔥','Flamethrower'],['saw','🪚','Chainsaw'],['termite','🐜','Termites'],['stamp','⭐','Stamps'],['laser','🔴','Laser']];let tool='hammer',down=false,last=null,ants=[],parts=[],marks=0,shake=0,fireT=0;
  function desk(){const g=bx.createLinearGradient(0,0,W,H);g.addColorStop(0,'#6b4aa8');g.addColorStop(1,'#2d6fd6');bx.fillStyle=g;bx.fillRect(0,0,W,H);bx.fillStyle='rgba(255,255,255,.08)';for(let i=0;i<10;i++){bx.beginPath();bx.arc(Math.random()*W,Math.random()*H,60+Math.random()*120,0,7);bx.fill()}
    const icon=(ix,iy,col,label)=>{bx.fillStyle=col;bx.strokeStyle='#1D1A2F';bx.lineWidth=3;bx.fillRect(ix,iy,46,40);bx.strokeRect(ix,iy,46,40);bx.fillStyle='#fff';bx.font='600 12px Figtree, sans-serif';bx.textAlign='center';bx.fillText(label,ix+23,iy+58)};
    icon(24,24,'#FFD23F','Homework');icon(24,104,'#FF9F43','Chores.txt');icon(24,184,'#6EE7B7','Recycle');icon(24,264,'#FF8FB1','Photos');
    const win=(wx,wy,ww,wh,title,body)=>{bx.fillStyle='#FFFDF6';bx.strokeStyle='#1D1A2F';bx.lineWidth=3;bx.fillRect(wx,wy,ww,wh);bx.strokeRect(wx,wy,ww,wh);bx.fillStyle='#B9A7FF';bx.fillRect(wx,wy,ww,28);bx.strokeRect(wx,wy,ww,28);bx.fillStyle='#1D1A2F';bx.font='700 14px Figtree, sans-serif';bx.textAlign='left';bx.fillText(title,wx+10,wy+19);['#F2352A','#FFD23F','#2BB673'].forEach((cl,i)=>{bx.fillStyle=cl;bx.beginPath();bx.arc(wx+ww-16-i*20,wy+14,6,0,7);bx.fill();bx.stroke()});body(wx,wy+28,ww,wh-28)};
    win(160,60,420,300,'Homework_FINAL_final2.doc',(wx,wy,ww)=>{bx.fillStyle='#1D1A2F';bx.font='700 18px Figtree, sans-serif';bx.fillText('Essay: Why I Love Homework',wx+16,wy+34);bx.fillStyle='#c9c2da';for(let i=0;i<9;i++)bx.fillRect(wx+16,wy+54+i*22,ww-40-(i%3)*60,8)});
    win(610,120,300,240,'Calculator',(wx,wy)=>{bx.fillStyle='#1D1A2F';bx.fillRect(wx+14,wy+12,272,40);bx.fillStyle='#6EE7B7';bx.font='700 24px "JetBrains Mono", monospace';bx.textAlign='right';bx.fillText('58008',wx+276,wy+42);bx.textAlign='left';for(let r=0;r<3;r++)for(let k=0;k<4;k++){bx.fillStyle='#e8e1d0';bx.fillRect(wx+14+k*68,wy+64+r*46,60,38);bx.strokeRect(wx+14+k*68,wy+64+r*46,60,38)}});
    win(300,390,360,150,'Reminder',(wx,wy)=>{bx.fillStyle='#1D1A2F';bx.font='700 20px Figtree, sans-serif';bx.fillText('⚠ Math test tomorrow!!',wx+20,wy+50);bx.font='14px Figtree, sans-serif';bx.fillText('Snooze · Snooze · Snooze',wx+20,wy+84)});
    bx.fillStyle='#1D1A2F';bx.fillRect(0,H-40,W,40);bx.fillStyle='#FFD23F';bx.fillRect(8,H-32,90,24);bx.fillStyle='#1D1A2F';bx.font='800 14px Figtree, sans-serif';bx.textAlign='center';bx.fillText('Start',53,H-15);bx.fillStyle='#fff';bx.textAlign='right';bx.fillText('3:14 PM',W-14,H-15);
    dx.clearRect(0,0,W,H);marks=0;ants=[]}
  const cut=(fn)=>{bx.save();bx.globalCompositeOperation='destination-out';fn(bx);bx.restore()};
  function crack(px,py,s){s=s||1;dx.strokeStyle='rgba(255,255,255,.9)';dx.lineWidth=1.6;const n=8+rand(6);for(let i=0;i<n;i++){let a=Math.random()*Math.PI*2,r=0,qx=px,qy=py;dx.beginPath();dx.moveTo(px,py);while(r<(60+Math.random()*90)*s){r+=10+Math.random()*14;a+=(Math.random()-.5)*.5;qx=px+Math.cos(a)*r;qy=py+Math.sin(a)*r;dx.lineTo(qx,qy)}dx.stroke()}for(let k=1;k<3;k++){dx.beginPath();for(let i=0;i<=n;i++){const a=i/n*Math.PI*2,r=k*22*s+Math.random()*8;i?dx.lineTo(px+Math.cos(a)*r,py+Math.sin(a)*r):dx.moveTo(px+Math.cos(a)*r,py+Math.sin(a)*r)}dx.stroke()}cut(b=>{b.beginPath();b.arc(px,py,10*s,0,7);b.fill()});marks+=3}
  function splat(px,py,col,r){dx.fillStyle=col;dx.beginPath();dx.arc(px,py,r,0,7);dx.fill();for(let i=0;i<9;i++){const a=Math.random()*7,d=r*(.8+Math.random()*1.4);dx.beginPath();dx.arc(px+Math.cos(a)*d,py+Math.sin(a)*d,r*(.15+Math.random()*.3),0,7);dx.fill()}for(let i=0;i<2;i++){dx.fillRect(px-r*.3+Math.random()*r*.6,py,4,r*(1+Math.random()*2))}marks++}
  function hole(px,py,r){cut(b=>{b.beginPath();b.arc(px,py,r,0,7);b.fill()});dx.strokeStyle='rgba(29,26,47,.8)';dx.lineWidth=2;dx.beginPath();dx.arc(px,py,r+2,0,7);dx.stroke();for(let i=0;i<5;i++){const a=Math.random()*7;dx.beginPath();dx.moveTo(px+Math.cos(a)*r,py+Math.sin(a)*r);dx.lineTo(px+Math.cos(a)*(r+8+Math.random()*14),py+Math.sin(a)*(r+8+Math.random()*14));dx.stroke()}marks++}
  function scorch(px,py){const g=dx.createRadialGradient(px,py,2,px,py,34);g.addColorStop(0,'rgba(29,26,47,.55)');g.addColorStop(1,'rgba(29,26,47,0)');dx.fillStyle=g;dx.beginPath();dx.arc(px,py,34,0,7);dx.fill();for(let i=0;i<3;i++)parts.push({x:px,y:py,vx:(Math.random()-.5)*3,vy:-2-Math.random()*3,l:.5,col:pick(['#FFD23F','#FF9F43','#F2352A']),r:6+Math.random()*8});if(Math.random()<.2)cut(b=>{b.beginPath();b.arc(px+(Math.random()-.5)*10,py+(Math.random()-.5)*10,6,0,7);b.fill()});marks+=.2}
  function sawLine(a,b2){cut(bb=>{bb.lineWidth=10;bb.lineCap='round';bb.beginPath();bb.moveTo(a.x,a.y);bb.lineTo(b2.x,b2.y);bb.stroke()});for(let i=0;i<3;i++)parts.push({x:b2.x,y:b2.y,vx:(Math.random()-.5)*8,vy:-Math.random()*6,l:.35,col:'#FFE27A',r:3});marks+=.3}
  const pos=e=>canvasPos(cv,e);
  function act(p,first){if(tool==='hammer'&&first){crack(p.x,p.y,1);shake=8;noise(.25,'highpass',2500,.2);noise(.15,'lowpass',300,.2)}
    else if(tool==='gun'&&first){splat(p.x,p.y,pick(['#F2352A','#FFD23F','#2BB673','#FF8FB1','#7FC8F8','#FF9F43']),16+Math.random()*10);noise(.08,'lowpass',900,.15)}
    else if(tool==='stamp'&&first){dx.font='64px sans-serif';dx.textAlign='center';dx.fillText(pick(['⭐','😂','💩','👍','🍕','👻','🦆','🔥']),p.x,p.y+22);beep(500,.05,'triangle',.05);marks++}
    else if(tool==='laser'){cut(b=>{b.beginPath();b.arc(p.x,p.y,5,0,7);b.fill()});const g=dx.createRadialGradient(p.x,p.y,4,p.x,p.y,14);g.addColorStop(0,'rgba(242,53,42,.8)');g.addColorStop(1,'rgba(242,53,42,0)');dx.fillStyle=g;dx.beginPath();dx.arc(p.x,p.y,14,0,7);dx.fill();marks+=.1;if(Math.random()<.3)beep(1800+Math.random()*400,.03,'sawtooth',.02)}
    else if(tool==='termite'&&first){for(let i=0;i<5;i++)ants.push({x:p.x,y:p.y,a:Math.random()*7,l:6+Math.random()*4});beep(900,.05,'square',.03)}}
  c.on(cv,'pointerdown',e=>{cv.setPointerCapture(e.pointerId);down=true;last=pos(e);act(last,true);fireT=0});c.on(cv,'pointermove',e=>{const p=pos(e);if(down){if(tool==='saw'&&last){sawLine(last,p);if(Math.random()<.3)noise(.06,'bandpass',300,.12)}else if(tool==='laser'){const d=Math.hypot(p.x-last.x,p.y-last.y);for(let k=0;k<d;k+=4)act({x:last.x+(p.x-last.x)*k/d,y:last.y+(p.y-last.y)*k/d})}}last=p});
  const up=()=>{down=false};c.on(cv,'pointerup',up);c.on(cv,'pointercancel',up);
  c.loop(dt=>{const s=dt/1000;if(down&&last){fireT-=s;if(tool==='machine'&&fireT<=0){fireT=.07;hole(last.x+(Math.random()-.5)*30,last.y+(Math.random()-.5)*30,4+Math.random()*3);shake=4;noise(.05,'lowpass',1200,.12)}if(tool==='flame'&&fireT<=0){fireT=.03;scorch(last.x+(Math.random()-.5)*20,last.y+(Math.random()-.5)*20);if(Math.random()<.2)noise(.1,'bandpass',400,.08)}}
    ants.forEach(a=>{a.l-=s;a.a+=(Math.random()-.5)*.6;a.x+=Math.cos(a.a)*1.6;a.y+=Math.sin(a.a)*1.6;if(a.x<0||a.x>W)a.a=Math.PI-a.a;if(a.y<0||a.y>H)a.a=-a.a;cut(b=>{b.beginPath();b.arc(a.x,a.y,5,0,7);b.fill()});marks+=.02});ants=ants.filter(a=>a.l>0);
    parts.forEach(p=>{p.l-=s;p.x+=p.vx;p.y+=p.vy;p.vy+=.2});parts=parts.filter(p=>p.l>0);
    x.save();if(shake>0){x.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);shake*=.8;if(shake<.4)shake=0}
    x.fillStyle='#0d0a22';x.fillRect(-10,-10,W+20,H+20);x.fillStyle='rgba(255,255,255,.6)';for(let i=0;i<40;i++){x.fillRect((i*137)%W,(i*89)%H,2,2)}x.fillStyle='#F2352A';x.font='700 13px "JetBrains Mono", monospace';x.textAlign='center';x.fillText('ERROR 404: SCREEN NOT FOUND',W/2,H/2);
    x.drawImage(base,0,0);x.drawImage(dmg,0,0);ants.forEach(a=>{x.font='18px sans-serif';x.fillText('🐜',a.x,a.y+6)});parts.forEach(p=>{x.globalAlpha=clamp(p.l*2,0,1);x.fillStyle=p.col;x.beginPath();x.arc(p.x,p.y,p.r,0,7);x.fill()});x.globalAlpha=1;x.restore();
    const pct=Math.min(100,Math.round(marks/1.6));c.best(pct);c.stat('Screen Smasher · stress relieved '+pct+'%')});
  function renderBar(){bar.innerHTML='';T.forEach(([id,ic,name])=>{const b=el('button',{class:'tool'+(tool===id?' on':''),type:'button'},el('span',{class:'ti'},ic),el('small',null,name));b.addEventListener('click',()=>{tool=id;renderBar()});bar.append(b)});const r=el('button',{class:'tool',type:'button'},el('span',{class:'ti'},'🖥️'),el('small',null,'New screen'));r.addEventListener('click',desk);bar.append(r)}
  desk();renderBar()}});
