import os,sys
D=os.path.dirname(os.path.abspath(__file__))
s=open(D+'/orig.html').read()
open(D+'/geoguess.js','w').write(open(D+'/geoguess_src.js').read().replace('/*WAI_LOCS*/[]',open(D+'/wai_locs.json').read()))
open(D+'/geo.js','w').write(open(D+'/geo_src.js').read().replace('/*GEO_META*/',open(D+'/../t/geo_meta.js').read()))
css=open(D+'/heroes.css').read()
js=''.join(open(D+'/'+f).read()+'\n' for f in ['kit.js','roam.js','speed.js','flight.js','strength.js','size.js','ice.js','havoc.js','drive.js','racer.js','wanted.js','simpledrive.js','board.js','arcade.js','casual.js','puzzle2.js','physics.js','bonk.js','buddy.js','geo.js','info.js','info2.js','music2.js','info3.js','board2.js','geo2.js','io2.js','cooking.js','sims.js','escape.js','geoguess.js','jetpack.js','gunsim.js','octagon.js','stillshot.js','fishing.js','flightsim.js','fighter.js','tx1.js','tx2.js','tx3.js','tx4.js','tx5.js','tx6.js','escape3d.js','powers.js','bk.js','crime.js','hollow.js','contract.js','blade.js','palm.js','wizard.js','io.js','toys.js','chill.js'] if os.path.exists(D+'/'+f))
def rep(a,b,cnt=1):
    global s
    assert s.count(a)>=1,a
    s=s.replace(a,b,cnt)
rep('<small><span id="count">54</span> games · no sign-up · no ads · your best scores stay on this device</small>','<small><span id="count">54</span> games · no sign-up · no ads · your best scores stay on this device</small>\n      <ul class="perks"><li><b>🌐 Nothing to download</b>It’s a website. Open it and play.</li><li><b>💻 No gaming PC needed</b>Runs on phones, tablets, Chromebooks and school laptops.</li><li><b>🎮 Over 200 games</b><span id="count2">200+</span> games, from chess to 3D racing.</li></ul>')
rep("$('#count').textContent=G.length;","$('#count').textContent=G.length;{const c2=$('#count2');if(c2)c2.textContent=G.length}")
rep("id:'c4',levels:true,name:'Four in a Row',kind:'game'","id:'c4',levels:true,name:'Four in a Row',kind:'board'")
rep('\n</style>','\n'+css.strip()+'\n</style>')
js=js.replace('/*KAIJU*/',open(D+'/kaiju.js').read())
rep('/* ---------------- 3D SPORTS ---------------- */',js+'/* ================= END SUPERHEROES ================= */\n/* ---------------- 3D SPORTS ---------------- */')
rep('<button class="btn" data-f="game" type="button">Games</button>','<button class="btn" data-f="hero" type="button">Superheroes</button>\n    <button class="btn" data-f="io" type="button">.io games</button>\n    <button class="btn" data-f="game" type="button">Games</button>')
rep("shooter:'3D Shooter'};","shooter:'3D Shooter',hero:'Superhero',smash:'Smash',geo:'Geography',info:'Cool Info',io:'.io',arcade:'Arcade',casual:'Casual',board:'Board & Classic',cooking:'Cooking',sim:'Simulators',escape:'Escape Room'};")
rep("['puzzle','Puzzles','Brain-benders, from sudoku to jigsaws'],","['puzzle','Puzzles','Brain-benders, from sudoku to jigsaws'],['geo','Geography','Maps, flags and capitals'],['info','Cool Info','Birthdays, planets, facts and live stats'],['smash','Smash & Physics','Wreck stuff, bonk buddies, smash screens'],['arcade','Arcade','Quick-reflex classics: bounce, dodge, dash and park'],['casual','Casual & Friv','Quirky one-more-go games'],['board','Board & Classic','Chess, checkers, cards and Connect Four'],['cooking','Cooking','Run a pizzeria, a burger bar and a cupcake café'],['sim','Simulators','Farm, run a business, build a town'],")
rep('<button class="btn" data-f="puzzle" type="button">Puzzles</button>','<button class="btn" data-f="puzzle" type="button">Puzzles</button>\n    <button class="btn" data-f="smash" type="button">Smash</button>\n    <button class="btn" data-f="geo" type="button">Geography</button>\n    <button class="btn" data-f="info" type="button">Cool info</button>\n    <button class="btn" data-f="arcade" type="button">Arcade</button>\n    <button class="btn" data-f="casual" type="button">Casual</button>\n    <button class="btn" data-f="board" type="button">Board &amp; classic</button>\n    <button class="btn" data-f="cooking" type="button">Cooking</button>\n    <button class="btn" data-f="sim" type="button">Simulators</button>')
rep("const SEC=[['shooter',","const SEC=[['hero','Superheroes','Pick a power and save the city, comic-book style'],['escape','Escape Rooms','Search every corner, crack the locks and break out'],['io','.io Games','Eat, grow and take over the map (with bots)'],['shooter',")
rep('Hit the sign and it sends you somewhere fun: a 3D shooter,','Hit the sign and it sends you somewhere fun: a superhero mission, a giant monster rampage,')
if len(sys.argv)>1: s=s.replace('/*DBGH*/','window.__HX={KZ,get vmi(){return vmi},get deadBlocks(){return deadBlocks},get crowd(){return crowd},get beams(){return beams},get lzHit(){return lzHit},camPos:()=>[camera.position.x,camera.position.y,camera.position.z,camera.fov],rinfo:()=>({calls:RND.info.render.calls,tri:RND.info.render.triangles,pr:RND.getPixelRatio()}),prof(){const t0=performance.now();for(let i=0;i<5;i++)RND.render(scene,camera);return (performance.now()-t0)/5},P,cam,get blds(){return blds},stats,get dA(){return dActive.length},get heat(){return heat},set heat(v){heat=v},get enemies(){return enemies},aimAt(x,y,z){const d=new T.Vector3(x,y,z).sub(camera.position);cam.yaw=Math.atan2(-d.x,-d.z);cam.pitch=clamp(Math.asin(d.y/d.length()),cam.pmin,cam.pmax)}};')
if len(sys.argv)>1: s=s.replace('RM.reset(i<0);','RM.reset(i<0);window.__RM=RM;window.__RP=()=>P;try{window.__RB=()=>city.boxes}catch(e){}')
if len(sys.argv)>1: s=s.replace('function explode(p,r,pw,byPlayer){','function explode(p,r,pw,byPlayer){(window.__booms=window.__booms||[]).push([p.x|0,p.y|0,p.z|0]);',1)
if len(sys.argv)>1: s=s.replace('/*DBGK*/','window.__K=K;window.__city=()=>city;window.__P=()=>P;');s=s.replace('/*DBGI*/','window.__ice={P,get fires(){return fires},get trail(){return trail},get F(){return F}};');s=s.replace('/*DBGAG*/','window.__ag={sim(sec){const dt=1/60;for(let t=0;t<sec;t+=dt){if(state===\'count\'){count-=dt;if(count<=0)state=\'race\'}cars.forEach(k=>{if(k.ai)aiDrive(k,dt)});if(this.bot){const{S,N}=TR;const k=me;const u=Math.max(0,k.u||0);const look=Math.round(clamp(u*.55,8,36)/DS);const q=S[(k.i+look)%N];const tx=q.x-Math.cos(q.h)*q.lo,tz=q.z+Math.sin(q.h)*q.lo;const dx=tx-k.x,dz=tz-k.z;const fl=dx*Math.sin(k.psi)+dz*Math.cos(k.psi),ll=dx*Math.cos(k.psi)-dz*Math.sin(k.psi);const ld=Math.hypot(fl,ll);const dm=.52*clamp(1-u/95,.2,1);k.delta=clamp(Math.atan(2*2.65*Math.sin(Math.atan2(ll,fl))/ld),-dm,dm);let vt=1e9;for(let m=0;m<100;m+=3){const q2=S[(k.i+m)%N];vt=Math.min(vt,Math.sqrt(q2.v*q2.v*this.bot*this.bot+2*8*m*DS))}if(state===\'count\')vt=0;if(u<vt-1){k.thr=1;k.brk=0}else if(u>vt+.5){k.thr=0;k.brk=clamp(.5+(u-vt)*.2,0,1)}else{k.thr=.4;k.brk=0}autoShift(k)}for(let s=0;s<4;s++){stepCar(me,dt/4,this.as||{abs:true,tcs:true,stm:true});collide()}if(state===\'race\'){raceT+=dt;cars.forEach(k=>{if(k.hasStarted)k.lapT+=dt})}cars.forEach(k=>tick(k,dt))}return cars.map(k=>({lap:k.lap,i:k.i,best:k.best,d:+k.d.toFixed(1),u:+(k.u||0).toFixed(1),fin:k.finished}))},scene,renderer,get me(){return me},get cars(){return cars},sun,hemi,T};');s=s.replace('/*DBGV*/','window.__VAIM=()=>{const t=boss||jets[0];if(!t)return;const d=t.p.clone().sub(camera.position);cam.yaw=Math.atan2(-d.x,-d.z);cam.pitch=clamp(Math.asin(d.y/d.length()),cam.pmin,cam.pmax)};window.__VV={P,get people(){return people},get air(){return air},get burning(){return burning},get tornados(){return tornados},get proj(){return proj},get score(){return score},get st(){return{carsN,pplN,scared,airN,fireN,collapsed}},setVillain,get VL(){return VL},F,get mi(){return mi},cam,city,makeAir,aimAt(x,y,z){const d=new T.Vector3(x,y,z).sub(camera.position);cam.yaw=Math.atan2(-d.x,-d.z);cam.pitch=clamp(Math.asin(d.y/d.length()),cam.pmin,cam.pmax)}};');s=s.replace('/*DBG*/','window.__hs={P,setSize,get solids(){return solids},get F(){return F}};')
if len(sys.argv)>1: s=s.replace('/*DBGT*/','window.__TF={P,fields,get tank(){return tank},get money(){return money},setT:v=>{tspd=v}};')
if len(sys.argv)>1: s=s.replace("const stage=$('#stage')","window.__G=G;const stage=$('#stage')",1)
rep('      <div class="plate">Random game</div>','      <div class="plate" id="rndPlate">Random game</div>\n      <div class="seg" id="rndMode" role="group" aria-label="What the random button picks"><button type="button" data-m="simple">Simple</button><button type="button" data-m="big">Big games</button><button type="button" data-m="all">Everything</button></div>')
rep('<button class="btn on" data-f="all" type="button">All</button>','<button class="btn on" data-f="all" type="button">All</button>\n    <button class="btn" data-f="simple" type="button">Simple</button>\n    <button class="btn" data-f="big" type="button">Big 3D &amp; story</button>')
rep("function surprise(){const pool=G.filter(g=>g!==current);openGame(pick(pool))}","const isBig=g=>g.big!=null?g.big:(g.kind==='hero'||g.kind==='shooter'||/with3D|runShooter/.test(String(g.run)));let rndMode=S.get('rndMode','all');\nfunction syncRnd(){document.querySelectorAll('#rndMode button').forEach(b=>b.classList.toggle('on',b.dataset.m===rndMode));$('#rndPlate').textContent=rndMode==='simple'?'Random simple game':rndMode==='big'?'Random big game':'Random game (anything)'}\ndocument.querySelectorAll('#rndMode button').forEach(b=>b.addEventListener('click',()=>{rndMode=b.dataset.m;S.set('rndMode',rndMode);beep(500,.05,'triangle');syncRnd()}));syncRnd();\nfunction rnd01(){try{const u=new Uint32Array(1);crypto.getRandomValues(u);return u[0]/4294967296}catch(e){return Math.random()}}\nfunction surprise(){const MAJOR=new Set(['openroad','apexgt','wanted','zsurv','stillshot','fishing','flightsim','skyfront','rumble','breach','royale','e3_study','e3_sub','e3_cabin','kart','octagon','jetpack','sim_farm','sim_town','geo_wai']);const isMajor=g=>g.major||g.kind==='hero'||MAJOR.has(g.id);let pool=G.filter(g=>g!==current&&(rndMode==='all'||(rndMode==='big'?isMajor(g):!isBig(g)))&&poolOK(g));if(!pool.length)pool=G.filter(g=>g!==current&&poolOK(g));if(!pool.length)pool=G.filter(g=>g!==current);let seen=S.get('rndSeen',[]);const keep=Math.floor(pool.length*.6);let fresh=pool.filter(g=>!seen.includes(g.id));if(!fresh.length){seen=[];fresh=pool}const g=fresh[Math.floor(rnd01()*fresh.length)];seen.push(g.id);if(seen.length>keep)seen=seen.slice(-keep);S.set('rndSeen',seen);spinTo(g)}")
rep("const list=G.filter(g=>(filter==='all'||g.kind===filter","const list=G.filter(g=>(filter==='all'||(filter==='simple'&&!isBig(g))||(filter==='big'&&isBig(g))||g.kind===filter")
rep("const grouped=filter==='all'&&!query;","const grouped=(filter==='all'||filter==='simple'||filter==='big')&&!query;")
rep(".press{display:flex;flex-direction:column;align-items:center;gap:18px}",".press{display:flex;flex-direction:column;align-items:center;gap:14px}\n#rndMode button{font-size:13px}")
rep('Melodies in Guess the Song, the piano and the chord pad are public-domain compositions and folk songs, played by Detour’s own synthesizer.','Classical melodies and folk songs in the music games are public domain, played by Detour’s own synthesizer. Guess the Song, Beat Lanes, Tap Tiles and Learn Piano also use very short, simplified snippets of well-known songs and film and game themes for a name-that-tune quiz. Song titles, artist names and years are used only to identify quiz answers, and all rights stay with their owners.')
rep('100 free games, puzzles, sports and music toys for when you are bored.','Over 200 free browser games: superheroes, driving, puzzles, sports, music, arcade and more. No download, runs on any device.')
rep('function renderGrid(){',"/* instant input: game buttons fire on press, not release */(function(){let fast=null,fastT=0;document.addEventListener('pointerdown',e=>{try{if(typeof unlockAudio==='function')unlockAudio()}catch(er){}if(e.pointerType==='touch'||e.button!==0)return;const t=e.target.closest&&e.target.closest('#arena button');if(!t||t.disabled||t.closest('.no-fast'))return;fast=t;fastT=performance.now();t.click()},true);document.addEventListener('click',e=>{if(fast&&e.isTrusted&&performance.now()-fastT<1500&&(e.target===fast||fast.contains(e.target)||!fast.isConnected)){e.stopImmediatePropagation();e.preventDefault();fast=null}},true)})();\nfunction renderGrid(){")
rep('</style>','#arena,#arena *{touch-action:manipulation}#arena canvas{touch-action:none}#arena button:active{transform:translateY(1px)}</style>')
# site name set by the owner on Netlify: Detourr
# --- positioning: one button, endless detours (satisfying, cool, interesting stuff) ---
import re as _re
rep('<h1>Bored in class? Take a detour.</h1>','<h1>Bored? Take a detour.</h1>')
rep("Hit the sign and it sends you somewhere fun: a superhero mission, a giant monster rampage, a sports challenge, a brain-bending puzzle, a music toy, or something deeply weird. Most games have easy, normal and hard modes.","One button, endless places to go. Hit the sign and land somewhere good: a satisfying toy, a weird little game, a fact that breaks your brain, a quick puzzle, or a full superhero rampage when you want chaos. Then hit it again. There’s always another detour.")
rep('<li><b>🌐 Nothing to download</b>It’s a website. Open it and play.</li><li><b>💻 No gaming PC needed</b>Runs on phones, tablets, Chromebooks and school laptops.</li><li><b>🎮 Over 200 games</b><span id="count2">200+</span> games, from chess to 3D racing.</li>','<li><b>🔀 One button, endless detours</b>Satisfying, weird, clever or chaotic. Something new every press.</li><li><b>🎮 <span id="count2">200+</span> games, toys &amp; cool stuff</b>From ten-second toys and mind-blowing facts to giant 3D rampages.</li><li><b>🌐 Nothing to download</b>Works on phones, tablets, Chromebooks and school laptops.</li>')
s=_re.sub(r"const SEC=\[\['hero','Superheroes'.*?\]\];",lambda m:"const SEC="+str([['hero','Superheroes','Pick a power and wreck the city, comic-book style'],['toy','Satisfying Toys','Things to poke, drag, pop and watch'],['info','Cool Info','Facts, stats and mind-blowing numbers'],['weird','Weird','Games that make no sense, in the best way'],['game','Quick Games','Short bursts of fun'],['casual','Casual & Friv','Quirky one-more-go games'],['escape','Escape Rooms','Search every corner, crack the locks and break out'],['geo','Geography','Street View, maps, flags and capitals'],['puzzle','Puzzles','Brain-benders, from sudoku to jigsaws'],['io','.io Games','Eat, grow and take over the map (with bots)'],['smash','Smash & Physics','Wreck stuff, bonk buddies, smash screens'],['music','Music','Make noise, find the beat, name the tune'],['chill','Chill Stuff','Low-key ways to pass the time'],['arcade','Arcade','Quick-reflex classics: bounce, dodge, dash and park'],['board','Board & Classic','Chess, checkers, cards and Connect Four'],['cooking','Cooking','Run a pizzeria, a burger bar and a cupcake café'],['sim','Simulators','Farm, run a business, build a town'],['sports','Sports','3D games for every season'],['shooter','3D Shooters','Story missions in first and third person']]).replace('"',"\\'")+";",s,count=1,flags=_re.S)
for _k in ['chill','weird','info','toy']:
    _m=_re.search(r'\n\s*<button class="btn" data-f="'+_k+'" type="button">[^<]*</button>',s)
    if _m:
        s=s[:_m.start()]+s[_m.end():]
        _h=_re.search(r'<button class="btn" data-f="hero" type="button">[^<]*</button>',s)
        s=s[:_h.end()]+'\n    '+_m.group(0).strip()+s[_h.end():]
s=s.replace('data-f="toy" type="button">Toys</button>','data-f="toy" type="button">✨ Satisfying toys</button>',1)
s=_re.sub(r'<title>[^<]*</title>','<title>Detour: 200+ Free Games, Satisfying Toys &amp; Cool Stuff · No Download</title>',s,count=1)
s=_re.sub(r'<meta name="description" content="[^"]*">','<meta name="description" content="Bored? Hit the button. 200+ free games, satisfying toys, weird mini-games, cool facts, Street View guessing and superhero rampages. No download, no sign-up, works on school laptops and phones.">',s,count=1)
s=_re.sub(r'<meta property="og:title" content="[^"]*">','<meta property="og:title" content="Detour: 200+ free games, satisfying toys and cool stuff">',s,count=1)
s=_re.sub(r'<meta property="og:description" content="[^"]*">','<meta property="og:description" content="Satisfying toys, weird little games, mind-blowing facts, escape rooms and giant 3D rampages. One button, endless detours. Free, no sign-up, works on any phone.">',s,count=1)
import re as _re
s=_re.sub(r'Detour(?!r)','Detourr',s)
s=_re.sub(r'DETOUR(?![R_])','DETOURR',s)
s=_re.sub(r"(?<!['\w])detour(?=s?\b)",'detourr',s)
out=sys.argv[1] if len(sys.argv)>1 else os.path.join(D,'..','..','index.html')
# ---- In progress section: games waiting for the owner's review. Move ids out of WIP_IDS to publish them.
WIP_IDS=['neonharbor','hollow','contract','moonblade','ironpalm','spellbound']
rep("const stage=$('#stage')","const WIP_IDS="+repr(WIP_IDS)+";const WIP=G.filter(g=>WIP_IDS.includes(g.id));WIP.forEach(g=>G.splice(G.indexOf(g),1));const stage=$('#stage')")
rep("const list=G.filter(g=>(filter==='all'||","const list=(filter==='wip'?WIP:G).filter(g=>(filter==='all'||filter==='wip'||")
rep("const start=G.find(g=>g.id===h);","const start=G.find(g=>g.id===h)||WIP.find(g=>g.id===h);")
rep('<button class="btn fy" data-f="ideas" type="button">','<button class="btn fy" data-f="wip" type="button">🚧 In progress</button>\n    <button class="btn fy" data-f="ideas" type="button">')
open(out,'w').write(s)
print('ok',len(s))
