/* ================= CASUAL & FRIV ================= */
/* ---------- Babel Tower (physics balancing) ---------- */
G.push({id:'babel',name:'Babel Tower',kind:'casual',levels:true,tint:'#e8c48a',blurb:'Blocks swing from a crane. Drop them to build the tallest tower you can without it toppling.',fmt:b=>b+' m',
art:'<rect width="120" height="72" fill="#FFE9B8"/><path d="M60 0v14" stroke="#1D1A2F" stroke-width="2"/><rect x="50" y="14" width="22" height="10" fill="#F2352A" stroke="#1D1A2F" stroke-width="2"/><g stroke="#1D1A2F" stroke-width="2"><rect x="44" y="60" width="34" height="12" fill="#8a5a2b"/><rect x="48" y="48" width="26" height="12" fill="#FF9F43"/><rect x="52" y="36" width="20" height="12" fill="#2d6fd6"/></g>',
run(root,c){return withMatter(root,c,()=>{const Mt=window.Matter,{Engine,Bodies,Body,Composite}=Mt;const W=520,H=640;const[cv,x]=mk(W,H,'width:min(100%,520px)');root.append(cv,el('p',{class:'hint'},'Tap, click or press Space to drop the swinging block. Stack them as high as you can. Three blocks falling off the platform and you’re done.'));
  let eng,blocks,hang,t,cam,lost,state,maxH,best=c.best()||0;const COLS=['#F2352A','#FF9F43','#FFD23F','#2BB673','#2d6fd6','#B9A7FF','#FF8FB1'];
  function reset(){eng=Engine.create();eng.gravity.y=1;Composite.add(eng.world,Bodies.rectangle(W/2,H-40,220,40,{isStatic:true,friction:1,label:'base'}));blocks=[];t=0;cam=0;lost=0;maxH=0;state='play';newHang()}
  function newHang(){const kinds=[[90,34],[70,40],[120,26],[60,60],[100,30]];const [w,h]=pick(kinds.slice(0,c.pick(3,4,5)));hang={w,h,col:pick(COLS),tri:c.level>0&&Math.random()<.15}}
  function drop(){if(state!=='play'||!hang)return;const px=W/2+Math.sin(t*c.pick(1.3,1.8,2.3))*c.pick(110,140,170);const py=cam+70;const b=hang.tri?Bodies.polygon(px,py,3,hang.w*.55,{friction:.9,density:.002}):Bodies.rectangle(px,py,hang.w,hang.h,{friction:.9,density:.002,chamfer:{radius:3}});b.plugin.col=hang.col;Composite.add(eng.world,b);blocks.push(b);hang=null;beep(400,.06,'triangle',.05);setTimeout(()=>{if(state==='play')newHang()},650)}
  function step(dt){if(state!=='play')return;t+=dt;Engine.update(eng,dt*1000);let top=H-60;blocks.forEach(b=>{if(b.position.y>H+50&&!b.plugin.gone){b.plugin.gone=1;lost++;noise(.3,'lowpass',300,.3);if(lost>=3){state='over';c.best(Math.floor(maxH))}}else if(!b.plugin.gone&&b.speed<.3)top=Math.min(top,b.bounds.min.y)});maxH=Math.max(maxH,(H-60-top)/40);const want=Math.min(0,top-260);cam+=(want-cam)*.05;c.stat('Babel Tower · '+maxH.toFixed(1)+' m')}
  function draw(){const g=x.createLinearGradient(0,0,0,H);g.addColorStop(0,'#9fd6ff');g.addColorStop(1,'#FFE9B8');x.fillStyle=g;x.fillRect(0,0,W,H);x.save();x.translate(0,-cam);
    x.fillStyle='#5A5470';x.fillRect(W/2-110,H-60,220,40);for(let h=1;h<40;h++){const y=H-60-h*40;if(y<cam-40||y>cam+H)continue;x.fillStyle='rgba(29,26,47,.25)';x.fillRect(0,y,14,2);x.font='10px "JetBrains Mono"';x.fillText(h+'m',16,y+4)}
    blocks.forEach(b=>{if(b.plugin.gone)return;x.fillStyle=b.plugin.col;x.strokeStyle='#1D1A2F';x.lineWidth=2.5;x.beginPath();b.vertices.forEach((v,i)=>i?x.lineTo(v.x,v.y):x.moveTo(v.x,v.y));x.closePath();x.fill();x.stroke()});
    if(hang){const px=W/2+Math.sin(t*c.pick(1.3,1.8,2.3))*c.pick(110,140,170),py=cam+70;x.strokeStyle='#1D1A2F';x.lineWidth=2;x.beginPath();x.moveTo(W/2,cam);x.lineTo(px,py-hang.h/2);x.stroke();x.fillStyle=hang.col;if(hang.tri){x.beginPath();for(let k=0;k<3;k++){const a=-Math.PI/2+k*2*Math.PI/3;x.lineTo(px+Math.cos(a)*hang.w*.55,py+Math.sin(a)*hang.w*.55)}x.closePath();x.fill();x.stroke()}else{x.fillRect(px-hang.w/2,py-hang.h/2,hang.w,hang.h);x.strokeRect(px-hang.w/2,py-hang.h/2,hang.w,hang.h)}}
    x.restore();x.fillStyle='#1D1A2F';x.font='800 18px "JetBrains Mono"';x.textAlign='left';x.fillText(maxH.toFixed(1)+' m   '+'❤'.repeat(3-lost),14,28);if(state==='over')banner(x,W,H,maxH.toFixed(1)+' m','Your tower fell! Tap to rebuild')}
  c.on(cv,'pointerdown',()=>{if(state==='over')reset();else drop()});c.on(document,'keydown',e=>{if(e.key===' '){e.preventDefault();state==='over'?reset():drop()}});reset();c.loop(dt=>{step(Math.min(.033,dt/1000));draw()});return()=>{}})}});
/* ---------- Monster Rush (gravity-flip runner) ---------- */
G.push({id:'monsterrush',name:'Monster Rush',kind:'casual',tint:'#B9A7FF',blurb:'A hungry little monster sprints through a cave. Flip gravity to run on the ceiling, dodge spikes and gobble candy.',fmt:b=>b+' m',
art:'<rect width="120" height="72" fill="#3a2a6a"/><rect width="120" height="10" fill="#1D1A2F"/><rect y="62" width="120" height="10" fill="#1D1A2F"/><path d="M70 62l6-10 6 10zM90 10l6 10 6-10z" fill="#fff"/><circle cx="36" cy="50" r="10" fill="#6EE7B7" stroke="#1D1A2F" stroke-width="2.5"/><circle cx="40" cy="47" r="3" fill="#fff"/><circle cx="41" cy="47" r="1.5" fill="#1D1A2F"/><circle cx="58" cy="34" r="4" fill="#FF8FB1"/>',
run(root,c){const W=820,H=400,TOP=40,BOT=360;const[cv,x]=mk(W,H,'width:100%');root.append(cv,el('p',{class:'hint'},'Tap, click or Space to flip gravity. Avoid the spikes on the floor and ceiling, and eat candy for points.'));
  let M,obs,candy,sp,dist,score,state='ready',flipCd=0;
  function reset(){M={y:BOT-16,vy:0,g:1,ph:0};obs=[];candy=[];sp=300;dist=0;score=0;state='play'}
  function flip(){if(state!=='play'){reset();return}if(flipCd>0)return;M.g*=-1;flipCd=.12;beep(M.g>0?400:700,.05,'triangle',.04)}
  function step(dt){if(state!=='play')return;flipCd-=dt;sp=Math.min(sp+dt*6,c.pick(460,540,620));dist+=sp*dt/40;M.vy+=M.g*2600*dt;M.y+=M.vy*dt;if(M.y>BOT-16){M.y=BOT-16;M.vy=0}if(M.y<TOP+16){M.y=TOP+16;M.vy=0}M.ph+=dt*sp/30;
    const lo=obs[obs.length-1];if(!lo||lo.x+lo.n*24<W-Math.max(200,sp*.62)-Math.random()*180){const onTop=Math.random()<.5;const n=1+rand(3);obs.push({x:W+30,top:onTop,n,moving:dist>200&&Math.random()<.25,ph:0});if(Math.random()<.6)candy.push({x:W+140,y:onTop?BOT-40:TOP+40})}
    obs.forEach(o=>{o.x-=sp*dt;if(o.moving){o.ph+=dt*3}});candy.forEach(q=>q.x-=sp*dt);
    for(const o of obs){const w=o.n*24;if(160+14>o.x&&160-14<o.x+w){const sy=o.top?TOP:BOT;const reach=o.moving?(36+Math.sin(o.ph)*20):30;if(o.top?M.y-16<sy+reach:M.y+16>sy-reach){die();return}}}
    candy.forEach(q=>{if(!q.got&&Math.abs(q.x-160)<24&&Math.abs(q.y-M.y)<30){q.got=true;score+=10;beep(1100,.05,'triangle',.05)}});obs=obs.filter(o=>o.x>-100);candy=candy.filter(q=>q.x>-20&&!q.got);c.stat('Monster Rush · '+Math.floor(dist)+' m')}
  function die(){state='over';c.best(Math.floor(dist)+score);noise(.4,'lowpass',400,.3)}
  function draw(){x.fillStyle='#3a2a6a';x.fillRect(0,0,W,H);x.fillStyle='rgba(185,167,255,.15)';for(let i=0;i<10;i++){const bx=((i*110-dist*4)%1100+1100)%1100-60;x.beginPath();x.arc(bx,H/2,30+i%3*14,0,7);x.fill()}x.fillStyle='#1D1A2F';x.fillRect(0,0,W,TOP);x.fillRect(0,BOT,W,H-BOT);
    obs.forEach(o=>{const reach=o.moving?(36+Math.sin(o.ph)*20):30;x.fillStyle=o.moving?'#F2352A':'#fff';x.strokeStyle='#1D1A2F';x.lineWidth=2;for(let k=0;k<o.n;k++){const bx=o.x+k*24;x.beginPath();if(o.top){x.moveTo(bx,TOP);x.lineTo(bx+12,TOP+reach);x.lineTo(bx+24,TOP)}else{x.moveTo(bx,BOT);x.lineTo(bx+12,BOT-reach);x.lineTo(bx+24,BOT)}x.closePath();x.fill();x.stroke()}});
    candy.forEach(q=>{x.fillStyle='#FF8FB1';x.strokeStyle='#1D1A2F';x.lineWidth=2;x.beginPath();x.arc(q.x,q.y,9,0,7);x.fill();x.stroke();x.fillStyle='#fff';x.fillRect(q.x-2,q.y-6,3,5)});
    x.save();x.translate(160,M.y);x.scale(1,M.g);x.fillStyle='#6EE7B7';x.strokeStyle='#1D1A2F';x.lineWidth=3;x.beginPath();x.arc(0,0,16,0,7);x.fill();x.stroke();x.fillStyle='#fff';x.beginPath();x.arc(5,-4,6,0,7);x.fill();x.fillStyle='#1D1A2F';x.beginPath();x.arc(7,-4,3,0,7);x.fill();x.beginPath();x.moveTo(-2,6);x.lineTo(12,6);x.stroke();const lg=Math.sin(M.ph)*6;x.beginPath();x.moveTo(-6,14);x.lineTo(-6+lg,22);x.moveTo(6,14);x.lineTo(6-lg,22);x.stroke();x.restore();
    x.fillStyle='#fff';x.font='800 18px "JetBrains Mono"';x.textAlign='left';x.fillText(Math.floor(dist)+' m  🍬 '+score,14,28);if(state==='ready')banner(x,W,H,'Monster Rush','Tap to run');if(state==='over')banner(x,W,H,Math.floor(dist)+' m · '+score+' candy','Ouch! Tap to run again')}
  c.on(cv,'pointerdown',e=>{e.preventDefault();flip()});c.on(document,'keydown',e=>{if(e.key===' '||e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();flip()}});reset();state='ready';c.loop(dt=>{step(Math.min(.03,dt/1000));draw()})}});
/* ---------- Gunmach ---------- */
G.push({id:'gunmach',name:'Gunmach',kind:'casual',levels:true,tint:'#FF9F43',blurb:'A tiny, grumpy mech with a big gun versus waves of goofy blobs. Pick an upgrade after every wave.',fmt:b=>'wave '+b,
art:'<rect width="120" height="72" fill="#e8e1d0"/><g stroke="#1D1A2F" stroke-width="2.5"><rect x="42" y="26" width="26" height="22" rx="4" fill="#FF9F43"/><rect x="66" y="32" width="22" height="7" fill="#5A5470"/><path d="M46 48l-4 10M64 48l4 10"/></g><circle cx="52" cy="34" r="3" fill="#1D1A2F"/><circle cx="100" cy="20" r="8" fill="#6EE7B7" stroke="#1D1A2F" stroke-width="2"/><circle cx="96" cy="56" r="6" fill="#FF8FB1" stroke="#1D1A2F" stroke-width="2"/>',
run(root,c){const W=820,H=520;const[cv,x]=mk(W,H,'width:100%');root.append(cv);const keys=holdPad(root,[['l','◀'],['u','▲'],['d','▼'],['r','▶']]);root.append(el('p',{class:'hint'},'WASD or arrows to walk, aim with the mouse and hold click to fire (on a phone it auto-aims and fires). Survive each wave, then pick an upgrade.'));
  let P,bul,en,wave,left,state='ready',ms={x:W/2,y:H/2,down:false},pressed={},up,pick3=null,parts=[];
  function reset(){P={x:W/2,y:H/2,hp:100,cd:0,inv:0,face:0};bul=[];en=[];wave=0;up={rate:1,dmg:1,spd:1,multi:1,pierce:0,hpMax:100};nextWave()}
  function nextWave(){wave++;left=6+wave*4;state='play';c.stat('Gunmach · wave '+wave)}
  function spawn(){const side=rand(4);const px=side===0?-20:side===1?W+20:Math.random()*W,py=side===2?-20:side===3?H+20:Math.random()*H;const k=Math.random();const kind=wave>2&&k<.2?'tank':wave>1&&k<.45?'zip':'blob';en.push({x:px,y:py,kind,hp:kind==='tank'?5+wave:kind==='zip'?1:2+wave*.4|0,r:kind==='tank'?24:kind==='zip'?11:16,sp:(kind==='zip'?150:kind==='tank'?45:75)*(1+wave*.04),ph:Math.random()*6,col:kind==='tank'?'#B9A7FF':kind==='zip'?'#FFD23F':'#6EE7B7'})}
  let spT=0;function step(dt){if(state!=='play')return;const L=pressed.a||pressed.arrowleft||keys.l,R=pressed.d||pressed.arrowright||keys.r,U=pressed.w||pressed.arrowup||keys.u,D=pressed.s||pressed.arrowdown||keys.d;const sp=190*up.spd;P.x=clamp(P.x+((R?1:0)-(L?1:0))*sp*dt,20,W-20);P.y=clamp(P.y+((D?1:0)-(U?1:0))*sp*dt,20,H-20);P.inv-=dt;P.cd-=dt;
    let tx=ms.x,ty=ms.y,fire=ms.down;if(touchMode&&en.length){let bd=1e9;en.forEach(e=>{const d=Math.hypot(e.x-P.x,e.y-P.y);if(d<bd){bd=d;tx=e.x;ty=e.y}});fire=true}P.face=Math.atan2(ty-P.y,tx-P.x);
    if(fire&&P.cd<=0){P.cd=.22/up.rate;for(let k=0;k<up.multi;k++){const a=P.face+(k-(up.multi-1)/2)*.18;bul.push({x:P.x+Math.cos(a)*20,y:P.y+Math.sin(a)*20,vx:Math.cos(a)*620,vy:Math.sin(a)*620,p:up.pierce})}beep(900,.02,'square',.02)}
    spT-=dt;if(spT<=0&&left>0&&en.length<8+wave){spT=Math.max(.25,1.1-wave*.07);spawn();left--}
    bul.forEach(b=>{b.x+=b.vx*dt;b.y+=b.vy*dt});en.forEach(e=>{e.ph+=dt*5;const a=Math.atan2(P.y-e.y,P.x-e.x);const wig=e.kind==='zip'?Math.sin(e.ph)*1.2:0;e.x+=Math.cos(a+wig)*e.sp*dt;e.y+=Math.sin(a+wig)*e.sp*dt;if(Math.hypot(e.x-P.x,e.y-P.y)<e.r+14&&P.inv<=0){P.hp-=e.kind==='tank'?20:10;P.inv=.7;noise(.2,'lowpass',400,.25);if(P.hp<=0){state='over';c.best(wave-1)}}
      bul.forEach(b=>{if(b.dead)return;if(Math.hypot(b.x-e.x,b.y-e.y)<e.r+4){e.hp-=up.dmg;if(b.p>0)b.p--;else b.dead=true;if(e.hp<=0&&!e.dead){e.dead=true;for(let i=0;i<8;i++)parts.push({x:e.x,y:e.y,vx:(Math.random()-.5)*300,vy:(Math.random()-.5)*300,l:.5,col:e.col});beep(300+Math.random()*300,.05,'triangle',.04)}}})});
    bul=bul.filter(b=>!b.dead&&b.x>-20&&b.x<W+20&&b.y>-20&&b.y<H+20);en=en.filter(e=>!e.dead);parts.forEach(p=>{p.l-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt});parts=parts.filter(p=>p.l>0);
    if(left<=0&&!en.length){state='upgrade';c.best(wave);const ALL=[['rate','Faster trigger',u=>u.rate*=1.3],['dmg','Bigger bullets',u=>u.dmg+=1],['multi','Extra barrel',u=>u.multi+=1],['pierce','Piercing rounds',u=>u.pierce+=1],['spd','Zoomier legs',u=>u.spd*=1.2],['heal','Repair kit',u=>{}]];pick3=shuffle(ALL.slice()).slice(0,3)}}
  function draw(){x.fillStyle='#e8e1d0';x.fillRect(0,0,W,H);x.strokeStyle='rgba(29,26,47,.06)';for(let i=0;i<W;i+=40){x.beginPath();x.moveTo(i,0);x.lineTo(i,H);x.stroke()}for(let j=0;j<H;j+=40){x.beginPath();x.moveTo(0,j);x.lineTo(W,j);x.stroke()}
    en.forEach(e=>{x.save();x.translate(e.x,e.y);x.fillStyle=e.col;x.strokeStyle='#1D1A2F';x.lineWidth=2.5;x.beginPath();x.ellipse(0,0,e.r*(1+Math.sin(e.ph)*.08),e.r*(1-Math.sin(e.ph)*.08),0,0,7);x.fill();x.stroke();const a=Math.atan2(P.y-e.y,P.x-e.x);x.fillStyle='#fff';x.beginPath();x.arc(Math.cos(a)*e.r*.35,Math.sin(a)*e.r*.35-3,e.r*.25,0,7);x.fill();x.fillStyle='#1D1A2F';x.beginPath();x.arc(Math.cos(a)*e.r*.45,Math.sin(a)*e.r*.45-3,e.r*.12,0,7);x.fill();x.restore()});
    parts.forEach(p=>{x.fillStyle=p.col;x.globalAlpha=p.l*2;x.fillRect(p.x,p.y,5,5);x.globalAlpha=1});x.fillStyle='#1D1A2F';bul.forEach(b=>{x.beginPath();x.arc(b.x,b.y,4+up.dmg,0,7);x.fill()});
    if(P){x.save();x.translate(P.x,P.y);if(P.inv>0&&Math.floor(P.inv*20)%2)x.globalAlpha=.4;x.fillStyle='#FF9F43';x.strokeStyle='#1D1A2F';x.lineWidth=3;x.beginPath();x.roundRect?x.roundRect(-15,-14,30,26,5):x.rect(-15,-14,30,26);x.fill();x.stroke();x.fillStyle='#1D1A2F';x.fillRect(-8,-6,5,5);x.fillRect(3,-6,5,5);x.rotate(P.face);x.fillStyle='#5A5470';for(let k=0;k<up.multi;k++)x.fillRect(8,-4+(k-(up.multi-1)/2)*6,22,6);x.restore()}
    x.fillStyle='#1D1A2F';x.font='800 16px "JetBrains Mono"';x.textAlign='left';x.fillText('WAVE '+wave+'   HP '+Math.max(0,Math.ceil(P?P.hp:0)),14,24);
    if(state==='upgrade'){x.fillStyle='rgba(29,26,47,.7)';x.fillRect(0,0,W,H);x.fillStyle='#FFD23F';x.font='32px "Bagel Fat One", sans-serif';x.textAlign='center';x.fillText('Wave '+wave+' cleared! Pick an upgrade',W/2,150);pick3.forEach((u,i)=>{const bx=W/2-270+i*190;x.fillStyle='#fff';x.fillRect(bx,200,170,110);x.fillStyle='#1D1A2F';x.font='800 17px Figtree';x.fillText(u[1],bx+85,260)})}
    if(state==='ready')banner(x,W,H,'Gunmach','Click to deploy');if(state==='over')banner(x,W,H,'Mech down!','You reached wave '+wave+' · click to reboot')}
  let touchMode=false;c.on(cv,'pointermove',e=>{const p=canvasPos(cv,e);ms.x=p.x;ms.y=p.y});c.on(cv,'pointerdown',e=>{touchMode=e.pointerType==='touch';const p=canvasPos(cv,e);ms.x=p.x;ms.y=p.y;ms.down=true;if(state==='ready'||state==='over'){reset();return}if(state==='upgrade'){pick3.forEach((u,i)=>{const bx=W/2-270+i*190;if(p.x>bx&&p.x<bx+170&&p.y>200&&p.y<310){u[2](up);if(u[0]==='heal')P.hp=100;else P.hp=Math.min(100,P.hp+20);nextWave()}})}});c.on(window,'pointerup',()=>ms.down=false);
  c.on(document,'keydown',e=>{pressed[e.key.toLowerCase()]=1});c.on(document,'keyup',e=>{pressed[e.key.toLowerCase()]=0});P={x:W/2,y:H/2,hp:100,face:0};up={multi:1,dmg:1};en=[];bul=[];wave=0;c.loop(dt=>{step(Math.min(.03,dt/1000));draw()})}});
/* ---------- Sticky Goo ---------- */
G.push({id:'stickygoo',name:'Sticky Goo',kind:'casual',levels:true,tint:'#6EE7B7',blurb:'A blob of goo that sticks to everything. Stretch it back and fling it to the star, avoiding spikes.',fmt:b=>'level '+b,
art:'<rect width="120" height="72" fill="#1D1A2F"/><rect x="0" y="60" width="120" height="12" fill="#5A5470"/><path d="M30 60q-4-14 6-18" stroke="#6EE7B7" stroke-width="3" fill="none"/><ellipse cx="38" cy="40" rx="10" ry="8" fill="#6EE7B7" stroke="#fff" stroke-width="2"/><text x="96" y="30" font-size="20" fill="#FFD23F">★</text><path d="M60 60l5-8 5 8 5-8 5 8z" fill="#F2352A"/>',
run(root,c){const W=820,H=520;const[cv,x]=mk(W,H,'width:100%');root.append(cv,el('p',{class:'hint'},'Drag back from the goo and let go to fling it. It sticks to any wall, floor or ceiling it touches. Reach the star in as few flings as you can. Red spikes pop you.'));
  let lvl=Math.max(1,S.get('goo_lv',1)),goo,walls,spikes,star,drag=null,flings,state='play',trail=[];
  function build(){const R=(()=>{let s=lvl*7919;return()=>{s=(s*9301+49297)%233280;return s/233280}})();walls=[{x:0,y:H-20,w:W,h:20},{x:0,y:0,w:W,h:20},{x:0,y:0,w:20,h:H},{x:W-20,y:0,w:20,h:H}];spikes=[];
    const n=Math.min(7,2+lvl);for(let i=0;i<n;i++){const vert=R()<.5;const w=vert?24:80+R()*140,h=vert?80+R()*160:24;walls.push({x:120+R()*(W-300),y:60+R()*(H-200),w,h})}
    for(let i=0;i<Math.min(8,lvl);i++){const w=walls[4+(i%(walls.length-4))]||walls[0];spikes.push({x:w.x+R()*Math.max(10,w.w-40),y:w.y-14,w:40,h:14})}for(let i=0;i<Math.min(6,lvl-1);i++)spikes.push({x:140+R()*(W-300),y:H-34,w:50,h:14});
    goo={x:50,y:H-34,vx:0,vy:0,stuck:true};star={x:W-70,y:60+R()*(H-160)};for(let k=0;k<12;k++){const w=walls.slice(4).find(w=>star.x>w.x-34&&star.x<w.x+w.w+34&&star.y>w.y-34&&star.y<w.y+w.h+34);if(!w)break;star.y=w.y-44;if(star.y<60){star.y=60+R()*(H-160);star.x=W-70-R()*120}}spikes=spikes.filter(sp=>Math.hypot(sp.x+sp.w/2-star.x,sp.y-star.y)>60&&!(sp.x<90&&sp.y>H-60));flings=0;state='play';trail=[];c.stat('Sticky Goo · level '+lvl)}
  function step(dt){if(state!=='play'||goo.stuck)return;for(let k=0;k<4;k++){const d=dt/4;goo.vy+=900*d;goo.x+=goo.vx*d;goo.y+=goo.vy*d;for(const w of walls){if(goo.x>w.x-12&&goo.x<w.x+w.w+12&&goo.y>w.y-12&&goo.y<w.y+w.h+12){const dl=goo.x-(w.x-12),dr=w.x+w.w+12-goo.x,du=goo.y-(w.y-12),dd=w.y+w.h+12-goo.y;const m=Math.min(dl,dr,du,dd);if(m===dl)goo.x=w.x-12;else if(m===dr)goo.x=w.x+w.w+12;else if(m===du)goo.y=w.y-12;else goo.y=w.y+w.h+12;goo.stuck=true;goo.vx=goo.vy=0;noise(.12,'lowpass',500,.2);return}}
    for(const s of spikes)if(goo.x>s.x-8&&goo.x<s.x+s.w+8&&goo.y>s.y-8&&goo.y<s.y+s.h+8){state='fail';noise(.4,'highpass',1200,.3);return}if(Math.hypot(goo.x-star.x,goo.y-star.y)<30){state='won';S.set('goo_lv',Math.max(S.get('goo_lv',1),lvl+1));c.best(lvl);[523,659,784].forEach((q,i)=>c.after(()=>beep(q,.15,'triangle',.06),i*100));return}}trail.push([goo.x,goo.y]);if(trail.length>24)trail.shift()}
  function draw(){x.fillStyle='#1D1A2F';x.fillRect(0,0,W,H);walls.forEach(w=>{x.fillStyle='#5A5470';x.fillRect(w.x,w.y,w.w,w.h)});spikes.forEach(s=>{x.fillStyle='#F2352A';for(let i=0;i<s.w;i+=10){x.beginPath();x.moveTo(s.x+i,s.y+s.h);x.lineTo(s.x+i+5,s.y);x.lineTo(s.x+i+10,s.y+s.h);x.fill()}});
    x.fillStyle='#FFD23F';x.font='36px sans-serif';x.textAlign='center';x.textBaseline='middle';x.fillText('★',star.x,star.y+Math.sin(performance.now()/300)*3);x.strokeStyle='rgba(110,231,183,.35)';x.lineWidth=6;x.beginPath();trail.forEach((p,i)=>i?x.lineTo(p[0],p[1]):x.moveTo(p[0],p[1]));x.stroke();
    if(drag){const dx=drag.x-goo.x,dy=drag.y-goo.y,L=Math.min(140,Math.hypot(dx,dy));const a=Math.atan2(dy,dx);x.strokeStyle='#6EE7B7';x.lineWidth=10;x.lineCap='round';x.beginPath();x.moveTo(goo.x,goo.y);x.lineTo(goo.x+Math.cos(a)*L,goo.y+Math.sin(a)*L);x.stroke();let px=goo.x,py=goo.y,vx=-Math.cos(a)*L*6,vy=-Math.sin(a)*L*6;x.fillStyle='rgba(255,255,255,.4)';for(let i=0;i<30;i++){vy+=900*.03;px+=vx*.03;py+=vy*.03;if(i%2){x.beginPath();x.arc(px,py,3,0,7);x.fill()}}}
    const sq=goo.stuck?1:1+Math.min(.3,Math.hypot(goo.vx,goo.vy)/2000);x.fillStyle='#6EE7B7';x.strokeStyle='#fff';x.lineWidth=3;x.beginPath();x.ellipse(goo.x,goo.y,13*sq,13/sq,Math.atan2(goo.vy,goo.vx),0,7);x.fill();x.stroke();x.fillStyle='#1D1A2F';x.beginPath();x.arc(goo.x-4,goo.y-2,2.5,0,7);x.arc(goo.x+4,goo.y-2,2.5,0,7);x.fill();
    x.fillStyle='#fff';x.font='700 16px "JetBrains Mono"';x.textAlign='left';x.fillText('LEVEL '+lvl+'   flings '+flings,28,44);if(state==='won')banner(x,W,H,'Got it in '+flings+'! '+'★'.repeat(flings<=2?3:flings<=4?2:1),'Tap for level '+(lvl+1));if(state==='fail')banner(x,W,H,'Popped!','Tap to try again')}
  c.on(cv,'pointerdown',e=>{if(state==='won'){lvl++;build();return}if(state==='fail'){build();return}if(!goo.stuck)return;const p=canvasPos(cv,e);drag=p;cv.setPointerCapture(e.pointerId)});c.on(cv,'pointermove',e=>{if(drag)drag=canvasPos(cv,e)});
  c.on(cv,'pointerup',()=>{if(!drag)return;const dx=drag.x-goo.x,dy=drag.y-goo.y,L=Math.min(140,Math.hypot(dx,dy));drag=null;if(L<15)return;const a=Math.atan2(dy,dx);goo.vx=-Math.cos(a)*L*6;goo.vy=-Math.sin(a)*L*6;goo.stuck=false;goo.x+=goo.vx*.02;goo.y+=goo.vy*.02;flings++;sweep(300,800,.2,'sine',.05)});
  build();c.loop(dt=>{step(Math.min(.03,dt/1000));draw()})}});
/* ---------- Sky Race ---------- */
G.push({id:'skyrace',name:'Sky Race',kind:'casual',levels:true,tint:'#7FC8F8',blurb:'A quick air race against three rival planes. Fly through the gold rings for speed boosts and dodge the storm clouds.',fmt:b=>b+' wins',
art:'<rect width="120" height="72" fill="#7FC8F8"/><ellipse cx="80" cy="20" rx="14" ry="6" fill="#fff"/><circle cx="96" cy="44" r="10" fill="none" stroke="#FFD23F" stroke-width="3"/><g transform="translate(30 36)"><path d="M0 0h26l6 4-6 4H0z" fill="#F2352A" stroke="#1D1A2F" stroke-width="2"/><path d="M10 0l-4-10h6l6 10z" fill="#FF9F43" stroke="#1D1A2F" stroke-width="2"/></g>',
run(root,c){const W=820,H=460,LEN=9000;const[cv,x]=mk(W,H,'width:100%');root.append(cv);const keys=holdPad(root,[['u','▲ Climb']]);root.append(el('p',{class:'hint'},'Hold click, Space or the Climb button to climb, let go to dive. Rings give a speed boost and storm clouds slow you down. First to the finish line wins!'));
  const COL=['#F2352A','#2d6fd6','#2BB673','#FFD23F'];let planes,rings,clouds,cam,state='ready',hold=false,t=0,wins=S.get('sr_w',0),order=[];
  function reset(){planes=COL.map((col,i)=>({x:0,y:120+i*60,vy:0,sp:0,col,ai:i>0,boost:0,skill:c.pick(.9,.97,1.03)*(.96+Math.random()*.08),done:null,tgtY:200}));rings=[];clouds=[];for(let xx=600;xx<LEN;xx+=300+Math.random()*250)rings.push({x:xx,y:80+Math.random()*(H-160)});for(let xx=900;xx<LEN;xx+=500+Math.random()*400)clouds.push({x:xx,y:60+Math.random()*(H-120),r:40+Math.random()*30});cam=0;t=-3;order=[];state='count'}
  function fly(p,up,dt){const base=320*(p.ai?p.skill:1);p.sp+=((base+(p.boost>0?180:0))-p.sp)*Math.min(1,dt*1.5);p.boost-=dt;p.vy+=(up?-900:600)*dt;p.vy=clamp(p.vy,-320,320);p.y=clamp(p.y+p.vy*dt,24,H-24);if(p.y>=H-24||p.y<=24)p.vy*=.3;p.x+=p.sp*dt;
    rings.forEach(r=>{if(Math.abs(r.x-p.x)<14&&Math.abs(r.y-p.y)<32){if(!r.hit)r.hit=new Set();if(!r.hit.has(p)){r.hit.add(p);p.boost=1;if(!p.ai)beep(1000,.08,'triangle',.05)}}});clouds.forEach(cl=>{if(Math.hypot(cl.x-p.x,cl.y-p.y)<cl.r)p.sp*=Math.pow(.25,dt)});
    if(p.x>=LEN&&p.done==null){p.done=t;order.push(p);if(!p.ai){state='done';const pos=order.indexOf(p)+1;if(pos===1){wins++;S.set('sr_w',wins);c.best(wins)}}}}
  function step(dt){if(state==='count'){t+=dt;if(t>=0)state='play';return}if(state!=='play'&&state!=='done')return;t+=dt;planes.forEach(p=>{if(p.done!=null&&p.x>LEN+400)return;let up=false;if(!p.ai)up=hold||keys.u;else{const nr=rings.find(r=>r.x>p.x+40);const ncl=clouds.find(cl=>cl.x>p.x&&cl.x-p.x<300);let ty=nr?nr.y:H/2;if(ncl&&Math.abs(ncl.y-ty)<ncl.r+20)ty=ncl.y>H/2?ncl.y-ncl.r-40:ncl.y+ncl.r+40;up=p.y+p.vy*.25>ty}fly(p,up,dt)});const me=planes[0];cam=me.x-200;c.stat('Sky Race · wins '+wins)}
  function draw(){const g=x.createLinearGradient(0,0,0,H);g.addColorStop(0,'#4a8fd6');g.addColorStop(1,'#cfe8ff');x.fillStyle=g;x.fillRect(0,0,W,H);x.fillStyle='rgba(255,255,255,.5)';for(let i=0;i<8;i++){const bx=((i*150-cam*.2)%1200+1200)%1200-100;x.beginPath();x.ellipse(bx,60+i*40%200,50,14,0,0,7);x.fill()}
    const sx=v=>v-cam;x.fillStyle='#2BB673';x.fillRect(0,H-14,W,14);const fx=sx(LEN);for(let j=0;j<H;j+=20){x.fillStyle=(j/20)%2?'#fff':'#1D1A2F';x.fillRect(fx,j,10,20)}
    clouds.forEach(cl=>{const px=sx(cl.x);if(px<-100||px>W+100)return;x.fillStyle='rgba(58,53,82,.75)';[[0,0],[-cl.r*.5,6],[cl.r*.5,6]].forEach(([a,b])=>{x.beginPath();x.arc(px+a,cl.y+b,cl.r*.6,0,7);x.fill()});x.fillStyle='#FFD23F';x.font='20px sans-serif';x.fillText('⚡',px-8,cl.y+26)});
    rings.forEach(r=>{const px=sx(r.x);if(px<-50||px>W+50)return;x.strokeStyle=r.hit&&r.hit.has(planes[0])?'rgba(255,210,63,.3)':'#FFD23F';x.lineWidth=5;x.beginPath();x.ellipse(px,r.y,10,32,0,0,7);x.stroke()});
    planes.slice().reverse().forEach(p=>{const px=sx(p.x);if(px<-60||px>W+60)return;x.save();x.translate(px,p.y);x.rotate(clamp(p.vy/700,-.5,.5));x.fillStyle=p.col;x.strokeStyle='#1D1A2F';x.lineWidth=2.5;x.beginPath();x.moveTo(-22,-6);x.lineTo(16,-6);x.lineTo(26,0);x.lineTo(16,6);x.lineTo(-22,6);x.closePath();x.fill();x.stroke();x.beginPath();x.moveTo(-4,-6);x.lineTo(-12,-20);x.lineTo(2,-20);x.lineTo(8,-6);x.fill();x.stroke();x.beginPath();x.moveTo(-22,-6);x.lineTo(-28,-16);x.lineTo(-18,-6);x.fill();x.stroke();if(p.boost>0){x.fillStyle='rgba(255,159,67,.8)';x.beginPath();x.moveTo(-22,-4);x.lineTo(-40-Math.random()*10,0);x.lineTo(-22,4);x.fill()}x.restore()});
    const me=planes[0];const pos=planes.slice().sort((a,b)=>(a.done??1e9)-(b.done??1e9)||b.x-a.x).indexOf(me)+1;x.fillStyle='#1D1A2F';x.font='800 18px "JetBrains Mono"';x.textAlign='left';x.fillText('P'+pos+'/4 · '+Math.max(0,Math.floor((LEN-me.x)/10))+' m to go',14,28);x.fillStyle='rgba(29,26,47,.2)';x.fillRect(W-230,16,210,10);planes.forEach(p=>{x.fillStyle=p.col;x.fillRect(W-230+Math.min(1,p.x/LEN)*206,14,5,14)});
    if(state==='count'&&t<0){x.fillStyle='#fff';x.font='64px "Bagel Fat One", sans-serif';x.textAlign='center';x.fillText(Math.ceil(-t),W/2,H/2)}if(state==='ready')banner(x,W,H,'Sky Race','Tap to start');if(state==='done'){const p2=order.indexOf(me)+1;banner(x,W,H,['','🏆 1st place!','2nd place','3rd place','4th place'][p2],'Tap to race again')}}
  c.on(cv,'pointerdown',e=>{e.preventDefault();if(state==='ready'||state==='done'){reset();return}hold=true});c.on(window,'pointerup',()=>hold=false);c.on(document,'keydown',e=>{if(e.key===' '){e.preventDefault();if(state==='ready'||state==='done')reset();hold=true}});c.on(document,'keyup',e=>{if(e.key===' ')hold=false});
  planes=[];rings=[];clouds=[];cam=0;reset();state='ready';c.loop(dt=>{step(Math.min(.03,dt/1000));draw()})}});
/* ---------- Paint Boy ---------- */
G.push({id:'paintboy',name:'Paint Boy',kind:'casual',levels:true,tint:'#FF8FB1',blurb:'Paint Boy slides until he hits a wall, painting every tile he rolls over. Paint the whole maze!',fmt:b=>'level '+b,
art:'<rect width="120" height="72" fill="#1D1A2F"/><g fill="#FF8FB1"><rect x="20" y="12" width="16" height="16"/><rect x="36" y="12" width="16" height="16"/><rect x="52" y="12" width="16" height="16"/><rect x="52" y="28" width="16" height="16"/></g><g fill="#3a3552"><rect x="52" y="44" width="16" height="16"/><rect x="68" y="44" width="16" height="16"/><rect x="84" y="44" width="16" height="16"/></g><circle cx="60" cy="52" r="6" fill="#FFD23F" stroke="#fff" stroke-width="2"/>',
run(root,c){const W=560,H=560;const[cv,x]=mk(W,H,'width:min(100%,560px)');const rs=el('button',{class:'btn',type:'button'},'↺ Restart level');root.append(cv,rs,el('p',{class:'hint'},'Arrow keys, WASD or swipe to roll. You only stop at walls. Paint every tile to finish the level. Every level can be finished, and you can always get back to where you started. Stuck? Press R or Restart.'));
  let lvl=Math.max(1,S.get('pb_lv',1)),G2,N,P,painted,moving=null,moves,state='play',hue=0;
  function build(){N=Math.min(13,6+Math.floor(lvl/2));G2=Array(N*N).fill(1);let px=1+rand(N-2),py=1+rand(N-2);G2[py*N+px]=0;const sx=px,sy=py;const steps=10+lvl*4;for(let i=0;i<steps;i++){const[dx,dy]=pick([[1,0],[-1,0],[0,1],[0,-1]]);const len=1+rand(N-2);let k=0;while(k<len){const nx=px+dx,ny=py+dy;if(nx<1||ny<1||nx>N-2||ny>N-2)break;px=nx;py=ny;G2[py*N+px]=0;k++}}
    // keep only tiles you can paint AND still come back from (strongly connected stop graph), repeat until stable
    for(let it=0;it<30;it++){const adj=new Map(),radj=new Map(),seen=new Set([sy*N+sx]),q=[[sx,sy]];while(q.length){const[a,b]=q.shift();const u=b*N+a;adj.set(u,[]);for(const[dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){let cx=a,cy=b;const tiles=[];while(G2[(cy+dy)*N+cx+dx]===0){cx+=dx;cy+=dy;tiles.push(cy*N+cx)}if(!tiles.length)continue;const v=cy*N+cx;adj.get(u).push([v,tiles]);if(!radj.has(v))radj.set(v,[]);radj.get(v).push(u);if(!seen.has(v)){seen.add(v);q.push([cx,cy])}}}
      const back=new Set([sy*N+sx]),bq=[sy*N+sx];while(bq.length){const v=bq.pop();(radj.get(v)||[]).forEach(u=>{if(!back.has(u)){back.add(u);bq.push(u)}})}const good=new Set([...seen].filter(u=>back.has(u)));const cov=new Set([sy*N+sx]);good.forEach(u=>adj.get(u).forEach(([v,tl])=>{if(good.has(v))tl.forEach(t=>cov.add(t))}));
      let ch=false;for(let i=0;i<N*N;i++)if(G2[i]===0&&!cov.has(i)){G2[i]=1;ch=true}if(!ch)break}
    if(G2.filter(v=>v===0).length<N*1.5&&(build.tries=(build.tries||0)+1)<30)return build();build.tries=0;
    P={x:sx,y:sy,sx,sy,px:sx,py:sy};painted=new Set([sy*N+sx]);moves=0;state='play';hue=(lvl*47)%360;c.stat('Paint Boy · level '+lvl)}
  function restart(){P.x=P.sx;P.y=P.sy;painted=new Set([P.y*N+P.x]);moves=0;moving=null;state='play'}function go(dx,dy){if(state!=='play'||moving)return;let cx=P.x,cy=P.y;const path=[];while(G2[(cy+dy)*N+cx+dx]===0){cx+=dx;cy+=dy;path.push([cx,cy])}if(!path.length)return;moving={path,i:0,t:0};moves++;beep(500,.04,'triangle',.03)}
  function step(dt){if(!moving)return;moving.t+=dt*28;while(moving.t>=1&&moving.i<moving.path.length){moving.t-=1;const[a,b]=moving.path[moving.i++];P.x=a;P.y=b;painted.add(b*N+a)}if(moving.i>=moving.path.length){moving=null;const total=G2.filter(v=>v===0).length;if(painted.size>=total){state='won';S.set('pb_lv',Math.max(S.get('pb_lv',1),lvl+1));c.best(lvl);[523,659,784,1046].forEach((q,i)=>c.after(()=>beep(q,.12,'triangle',.06),i*90))}}}
  function draw(){const Q=W/N;x.fillStyle='#1D1A2F';x.fillRect(0,0,W,H);for(let i=0;i<N*N;i++){const gx=i%N,gy=i/N|0;if(G2[i])continue;x.fillStyle=painted.has(i)?'hsl('+((hue+gx*6+gy*6)%360)+' 85% 65%)':'#3a3552';x.fillRect(gx*Q+1,gy*Q+1,Q-2,Q-2)}
    let px=P.x,py=P.y;if(moving&&moving.i<moving.path.length){const[a,b]=moving.path[moving.i];const pa=moving.i?moving.path[moving.i-1]:[P.x,P.y];px=pa[0]+(a-pa[0])*moving.t;py=pa[1]+(b-pa[1])*moving.t}x.fillStyle='#FFD23F';x.strokeStyle='#fff';x.lineWidth=3;x.beginPath();x.arc(px*Q+Q/2,py*Q+Q/2,Q*.34,0,7);x.fill();x.stroke();x.fillStyle='#1D1A2F';x.beginPath();x.arc(px*Q+Q/2-Q*.1,py*Q+Q/2-Q*.05,Q*.05,0,7);x.arc(px*Q+Q/2+Q*.1,py*Q+Q/2-Q*.05,Q*.05,0,7);x.fill();
    const total=G2.filter(v=>v===0).length;x.fillStyle='#fff';x.font='700 15px "JetBrains Mono"';x.textAlign='left';x.fillText('LEVEL '+lvl+'  ·  '+Math.floor(painted.size/total*100)+'%  ·  moves '+moves,10,H-10);if(state==='won')banner(x,W,H,'Painted!','Tap for level '+(lvl+1))}
  c.on(document,'keydown',e=>{const k=e.key.toLowerCase();if(k==='r'){restart();return}const m={arrowleft:[-1,0],a:[-1,0],arrowright:[1,0],d:[1,0],arrowup:[0,-1],w:[0,-1],arrowdown:[0,1],s:[0,1]}[k];if(m){e.preventDefault();go(...m)}});let sw=null;c.on(cv,'pointerdown',e=>{if(state==='won'){lvl++;build();return}sw=canvasPos(cv,e)});c.on(cv,'pointerup',e=>{if(!sw)return;const p=canvasPos(cv,e);const dx=p.x-sw.x,dy=p.y-sw.y;sw=null;if(Math.max(Math.abs(dx),Math.abs(dy))<20)return;Math.abs(dx)>Math.abs(dy)?go(Math.sign(dx),0):go(0,Math.sign(dy))});
  rs.addEventListener('click',()=>{if(state==='won'){lvl++;build()}else restart()});build();c.loop(dt=>{step(Math.min(.05,dt/1000));draw()})}});
/* ---------- Crazy Wheel ---------- */
G.push({id:'crazywheel',name:'Crazy Wheel',kind:'casual',levels:true,tint:'#1D1A2F',blurb:'Fire pins into a spinning wheel. Time every shot so no two pins touch. The wheel gets crazier every level.',fmt:b=>'level '+b,
art:'<rect width="120" height="72" fill="#fffdf6"/><circle cx="60" cy="28" r="14" fill="#1D1A2F"/><g stroke="#1D1A2F" stroke-width="2"><path d="M60 42v14M72 36l10 8M48 36l-10 8M74 22l12-4"/></g><circle cx="60" cy="58" r="3" fill="#1D1A2F"/><circle cx="84" cy="46" r="3" fill="#1D1A2F"/><circle cx="36" cy="46" r="3" fill="#1D1A2F"/><circle cx="88" cy="17" r="3" fill="#1D1A2F"/><circle cx="60" cy="66" r="3" fill="#F2352A"/>',
run(root,c){const W=480,H=640,CX=W/2,CY=230,R=80,PL=110;const[cv,x]=mk(W,H,'width:min(100%,480px)');root.append(cv,el('p',{class:'hint'},'Tap, click or Space to fire a pin. If it hits another pin, the level resets.'));
  let lvl=Math.max(1,S.get('cw_lv',1)),pins,left,ang,sp,t,state='play',fly=null,flash=0;
  function build(){const pre=Math.min(10,1+Math.floor(lvl/2));pins=[];for(let i=0;i<pre;i++)pins.push(i/pre*Math.PI*2+Math.random()*.2);left=Math.min(6+Math.min(14,lvl),18-pre);ang=0;t=0;sp=1.4+lvl*.08;state='play';fly=null;c.stat('Crazy Wheel · level '+lvl)}
  function speed(){if(lvl<4)return sp;if(lvl<8)return sp*(1+.6*Math.sin(t*1.3));return sp*Math.sin(t*.9+Math.sin(t*2.1))*1.6}
  function fire(){if(state==='won'){lvl++;build();return}if(state==='fail'){build();return}if(fly||left<=0)return;fly={y:H-80};beep(700,.03,'square',.03)}
  function step(dt){if(state!=='play')return;t+=dt;ang+=speed()*dt;if(fly){fly.y-=1600*dt;if(fly.y<=CY+R+PL){fly=null;const a=((Math.PI/2-ang)%(Math.PI*2)+Math.PI*4)%(Math.PI*2);if(pins.some(p=>{const d=Math.abs(((a-p+Math.PI*3)%(Math.PI*2))-Math.PI);return d<.12})){state='fail';flash=1;noise(.4,'lowpass',400,.3)}else{pins.push(a);left--;if(left===0){state='won';S.set('cw_lv',Math.max(S.get('cw_lv',1),lvl+1));c.best(lvl);[523,659,784].forEach((q,i)=>c.after(()=>beep(q,.15,'triangle',.06),i*100))}}}}}
  function draw(){x.fillStyle=flash>0?'#F2352A':state==='won'?'#2BB673':'#fffdf6';flash=Math.max(0,flash-.03);x.fillRect(0,0,W,H);x.strokeStyle='#1D1A2F';x.lineWidth=2;pins.forEach(p=>{const a=p+ang;const ex=CX+Math.cos(a)*(R+PL),ey=CY+Math.sin(a)*(R+PL);x.beginPath();x.moveTo(CX+Math.cos(a)*R,CY+Math.sin(a)*R);x.lineTo(ex,ey);x.stroke();x.fillStyle='#1D1A2F';x.beginPath();x.arc(ex,ey,8,0,7);x.fill()});
    x.fillStyle='#1D1A2F';x.beginPath();x.arc(CX,CY,R,0,7);x.fill();x.fillStyle='#fff';x.font='44px "Bagel Fat One", sans-serif';x.textAlign='center';x.textBaseline='middle';x.fillText(lvl,CX,CY);
    if(fly){x.beginPath();x.moveTo(CX,fly.y);x.lineTo(CX,fly.y+PL*.3);x.stroke();x.fillStyle='#F2352A';x.beginPath();x.arc(CX,fly.y+PL*.3,8,0,7);x.fill()}for(let i=0;i<Math.min(left,8);i++){x.fillStyle=i===0&&!fly?'#F2352A':'#1D1A2F';x.beginPath();x.arc(CX,H-80+i*20,8,0,7);x.fill()}if(left>8){x.fillStyle='#1D1A2F';x.font='700 14px Figtree';x.fillText('+'+(left-8),CX+26,H-80)}
    if(state==='won')banner(x,W,H,'Level '+lvl+' done!','Tap for level '+(lvl+1));if(state==='fail')banner(x,W,H,'Pins crashed!','Tap to retry level '+lvl)}
  c.on(cv,'pointerdown',e=>{e.preventDefault();fire()});c.on(document,'keydown',e=>{if(e.key===' '){e.preventDefault();fire()}});build();c.loop(dt=>{step(Math.min(.03,dt/1000));draw()})}});
/* ---------- Mitoza (surreal growing toy) ---------- */
G.push({id:'mitoza',name:'Mitoza',kind:'casual',big:false,tint:'#1D1A2F',blurb:'A strange little garden. Click to plant seeds, and watch cells divide, stems wander and odd creatures bloom.',fmt:null,
art:'<rect width="120" height="72" fill="#1D1A2F"/><path d="M40 72q-4-20 10-34t4-30" stroke="#6EE7B7" stroke-width="3" fill="none"/><circle cx="54" cy="8" r="7" fill="#FF8FB1"/><circle cx="46" cy="36" r="5" fill="#B9A7FF"/><circle cx="80" cy="48" r="9" fill="#FFD23F"/><circle cx="88" cy="42" r="6" fill="#FFD23F"/><circle cx="80" cy="46" r="2" fill="#1D1A2F"/>',
run(root,c){const W=820,H=520;const[cv,x]=mk(W,H,'width:100%');root.append(cv,el('p',{class:'hint'},'Click the ground to plant. Click a cell to make it divide. Click a bloom to make it burst into new seeds. Just relax and poke things.'));
  let things=[],t=0,count=0;const NOTES=[262,294,330,392,440,523,587,659];
  function seed(px){const hue=Math.random()*360;things.push({type:'stem',x:px,y:H-40,a:-Math.PI/2+(Math.random()-.5)*.3,len:0,max:120+Math.random()*200,hue,pts:[[px,H-40]],wig:Math.random()*6});beep(pick(NOTES),.2,'sine',.05);count++}
  function cell(px,py,r,hue){things.push({type:'cell',x:px,y:py,r,tr:r,hue,ph:Math.random()*6,vx:(Math.random()-.5)*20,vy:-10-Math.random()*20,eye:Math.random()<.4})}
  function step(dt){t+=dt;things.forEach(o=>{if(o.type==='stem'&&o.len<o.max){const g=40*dt;o.len+=g;o.a+=Math.sin(t*2+o.wig)*dt*1.4;const l=o.pts[o.pts.length-1];o.pts.push([l[0]+Math.cos(o.a)*g,l[1]+Math.sin(o.a)*g]);if(Math.random()<dt*1.2)cell(l[0],l[1],5+Math.random()*6,(o.hue+40)%360);if(o.len>=o.max){things.push({type:'bloom',x:l[0],y:l[1],r:0,tr:16+Math.random()*16,hue:(o.hue+180)%360,petals:5+rand(5),ph:0});beep(pick(NOTES)*2,.3,'triangle',.04)}}
    if(o.type==='cell'){o.ph+=dt*2;o.r+=(o.tr-o.r)*dt*2;o.x+=o.vx*dt;o.y+=o.vy*dt;o.vx*=Math.pow(.6,dt);o.vy=o.vy*Math.pow(.6,dt)+Math.sin(t+o.ph)*2*dt;if(o.y<30)o.vy=Math.abs(o.vy)}if(o.type==='bloom'){o.ph+=dt;o.r+=(o.tr-o.r)*dt*2}});if(things.length>700)things.splice(0,things.length-700);c.stat('Mitoza · '+count+' seeds planted')}
  function draw(){const g=x.createLinearGradient(0,0,0,H);g.addColorStop(0,'#1D1A2F');g.addColorStop(1,'#3a2a6a');x.fillStyle=g;x.fillRect(0,0,W,H);x.fillStyle='rgba(255,255,255,.4)';for(let i=0;i<40;i++){x.fillRect((i*197)%W,(i*83)%(H/2),1.5,1.5)}x.fillStyle='#2a1f4a';x.beginPath();x.moveTo(0,H);for(let i=0;i<=W;i+=20)x.lineTo(i,H-40+Math.sin(i*.02+t*.3)*6);x.lineTo(W,H);x.fill();
    things.forEach(o=>{if(o.type==='stem'){x.strokeStyle='hsl('+o.hue+' 70% 60%)';x.lineWidth=4;x.lineCap='round';x.beginPath();o.pts.forEach((p,i)=>i?x.lineTo(p[0],p[1]):x.moveTo(p[0],p[1]));x.stroke()}});
    things.forEach(o=>{if(o.type==='cell'){const w=Math.sin(o.ph)*.12;x.fillStyle='hsla('+o.hue+',75%,65%,.85)';x.beginPath();x.ellipse(o.x,o.y,o.r*(1+w),o.r*(1-w),0,0,7);x.fill();x.fillStyle='hsla('+o.hue+',75%,35%,.8)';x.beginPath();x.arc(o.x,o.y,o.r*.3,0,7);x.fill();if(o.eye&&o.r>6){x.fillStyle='#fff';x.beginPath();x.arc(o.x,o.y-o.r*.1,o.r*.35,0,7);x.fill();x.fillStyle='#1D1A2F';x.beginPath();x.arc(o.x+Math.sin(t)*o.r*.1,o.y-o.r*.1,o.r*.18,0,7);x.fill()}}
      else if(o.type==='bloom'){for(let k=0;k<o.petals;k++){const a=k/o.petals*Math.PI*2+o.ph*.4;x.fillStyle='hsl('+((o.hue+k*12)%360)+' 80% 65%)';x.beginPath();x.ellipse(o.x+Math.cos(a)*o.r*.7,o.y+Math.sin(a)*o.r*.7,o.r*.55,o.r*.28,a,0,7);x.fill()}x.fillStyle='#FFD23F';x.beginPath();x.arc(o.x,o.y,o.r*.35,0,7);x.fill();x.fillStyle='#1D1A2F';x.beginPath();x.arc(o.x-o.r*.12,o.y,o.r*.07,0,7);x.arc(o.x+o.r*.12,o.y,o.r*.07,0,7);x.fill()}});
    if(!count){x.fillStyle='rgba(255,255,255,.7)';x.font='600 18px Figtree';x.textAlign='center';x.fillText('Click the ground to plant something…',W/2,H/2)}}
  c.on(cv,'pointerdown',e=>{const p=canvasPos(cv,e);for(let i=things.length-1;i>=0;i--){const o=things[i];if(o.type==='cell'&&Math.hypot(o.x-p.x,o.y-p.y)<o.r+4){o.tr=o.r*.7;cell(o.x+o.r,o.y,o.r*.7,(o.hue+30)%360);things[things.length-1].vx=40;o.vx=-40;beep(pick(NOTES),.12,'sine',.05);return}if(o.type==='bloom'&&Math.hypot(o.x-p.x,o.y-p.y)<o.r+4){things.splice(i,1);for(let k=0;k<6;k++)cell(o.x,o.y,4+Math.random()*5,(o.hue+k*30)%360);for(let k=0;k<2;k++)seed(clamp(o.x+(Math.random()-.5)*200,20,W-20));noise(.2,'highpass',2000,.08);return}}seed(p.x)});
  for(let i=0;i<3;i++)seed(150+i*260);c.loop(dt=>{step(Math.min(.05,dt/1000));draw()})}});
