/* ================= OPEN ROAD: first-person scenic driving ================= */
G.push({id:'openroad',name:'Open Road',kind:'sports',levels:true,wide:true,tint:'#FF9F43',blurb:'First-person driving on an endless road through hills and forests. Cruise into the sunset, or race the clock through checkpoints.',fmt:b=>b+' km',
art:'<defs><linearGradient id="orS" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#3a2a6a"/><stop offset=".6" stop-color="#FF8FB1"/><stop offset="1" stop-color="#FFD23F"/></linearGradient></defs><rect width="120" height="72" fill="url(#orS)"/><circle cx="84" cy="30" r="9" fill="#FFF3C4"/><path d="M0 40l18-8 16 6 20-10 18 9 22-7 26 8v34H0z" fill="#5A5470"/><path d="M0 46l24-4 30 5 28-6 38 6v25H0z" fill="#2f7a3a"/><path d="M50 44h10l40 28H20z" fill="#3a3552"/><path d="M55 48h2l2 6h-4zM54 58h4l2 10h-7z" fill="#FFD23F"/><path d="M0 60q60-14 120 0v12H0z" fill="#1D1A2F"/><circle cx="36" cy="66" r="8" fill="none" stroke="#8c86a3" stroke-width="3"/>',
run(root,c){return with3D(root,c,()=>{
  const st3=Stage3D(root,c,{lock:false,dragLook:true,fov:68,far:2400,fireLabel:'GAS',altLabel:'BRAKE',jumpLabel:'DRIFT'});const{T,scene,camera,input,wrap,hud}=st3;
  /* ---------- noise + terrain ---------- */
  const seed=Math.random()*1000;const hs=(x,y)=>{const s=Math.sin(x*127.1+y*311.7+seed*1.7)*43758.5453;return s-Math.floor(s)};
  const vn=(x,y)=>{const xi=Math.floor(x),yi=Math.floor(y),xf=x-xi,yf=y-yi,u=xf*xf*(3-2*xf),v=yf*yf*(3-2*yf);const a=hs(xi,yi),b=hs(xi+1,yi),c2=hs(xi,yi+1),d=hs(xi+1,yi+1);return(a+(b-a)*u+(c2-a)*v+(a-b-c2+d)*u*v)*2-1};
  const fbm=(x,y)=>vn(x,y)*.6+vn(x*2.1+3,y*2.1)*.28+vn(x*4.3,y*4.3+7)*.12;
  const TER=(x,z)=>fbm(x*.0022,z*.0022)*80+fbm(x*.011+5,z*.011)*10;
  /* ---------- endless road ---------- */
  const SEG=4,KMAX=1/210,R=[{x:0,y:TER(0,0)*.7,z:0,h:0}];
  function grow(n){for(let k=0;k<n;k++){const L=R[R.length-1],i=R.length;const kc=(vn(i*.0055,seed)*.85+vn(i*.019+40,seed)*.4)*KMAX*Math.min(1,i/60);const h=L.h+kc*SEG;const x=L.x+Math.sin(h)*SEG,z=L.z+Math.cos(h)*SEG;const want=TER(x,z)*.7;R.push({x,y:L.y+clamp((want-L.y)*.035,-.075*SEG,.075*SEG),z,h})}}
  grow(400);
  const roadAt=s=>{while(R.length<s+3)grow(200);const i=clamp(Math.floor(s),0,R.length-2),f=s-i,a=R[i],b=R[i+1];return{x:a.x+(b.x-a.x)*f,y:a.y+(b.y-a.y)*f,z:a.z+(b.z-a.z)*f,h:a.h+(b.h-a.h)*f}};
  function near(x,z,hint){let best=hint|0,bd=1e18;const lo=Math.max(0,best-45),hi=Math.min(R.length-2,best+45);for(let i=lo;i<=hi;i++){const p=R[i];const d=(p.x-x)**2+(p.z-z)**2;if(d<bd){bd=d;best=i}}
    let i=best;let a=R[i],b=R[i+1];let ex=b.x-a.x,ez=b.z-a.z;let t=((x-a.x)*ex+(z-a.z)*ez)/(ex*ex+ez*ez);if(t<0&&i>0){i--;a=R[i];b=R[i+1];ex=b.x-a.x;ez=b.z-a.z;t=((x-a.x)*ex+(z-a.z)*ez)/(ex*ex+ez*ez)}t=clamp(t,0,1);const s=i+t,p=roadAt(s);const d=(x-p.x)*-Math.cos(p.h)+(z-p.z)*Math.sin(p.h);return{s,d,p,i:best}}
  const blendW=d=>{const a=clamp((Math.abs(d)-6.8)/42,0,1);return a*a*(3-2*a)};
  const hAt=(p,x,z,d)=>{const w=blendW(d);return p.y*(1-w)+TER(x,z)*w-(Math.abs(d)>5.7?.08:0)};
  const groundY=(x,z,hint)=>{const q=near(x,z,hint);return{y:hAt(q.p,x,z,q.d),q}};
  /* ---------- materials ---------- */
  const roadTex=tex(T,128,256,(x,w,h)=>{x.fillStyle='#8a8478';x.fillRect(0,0,w,h);x.fillStyle='#3d3a44';x.fillRect(w*.13,0,w*.74,h);for(let i=0;i<900;i++){x.fillStyle=Math.random()<.5?'rgba(255,255,255,.05)':'rgba(0,0,0,.08)';x.fillRect(Math.random()*w,Math.random()*h,2,2)}x.fillStyle='#f2efe6';x.fillRect(w*.16,0,w*.025,h);x.fillRect(w*.815,0,w*.025,h);x.fillStyle='#FFD23F';x.fillRect(w*.49,0,w*.02,h*.38)},1,1);roadTex.wrapT=T.RepeatWrapping;roadTex.anisotropy=4;
  const roadM=new T.MeshLambertMaterial({map:roadTex}),terM=new T.MeshLambertMaterial({vertexColors:true});
  const trunkG=new T.CylinderGeometry(.25,.35,3,6);trunkG.translate(0,1.5,0);const pineG=new T.ConeGeometry(2.2,7,7);pineG.translate(0,6,0);const roundG=new T.IcosahedronGeometry(3,0);roundG.translate(0,5.2,0);const rockG=new T.DodecahedronGeometry(1.4,0);const postG=new T.BoxGeometry(.14,1.1,.14);postG.translate(0,.55,0);
  const trunkM=new T.MeshLambertMaterial({color:0x6b4a2f}),pineM=new T.MeshLambertMaterial({color:0xffffff}),roundM=new T.MeshLambertMaterial({color:0xffffff}),rockM=new T.MeshLambertMaterial({color:0x8c86a3}),postM=new T.MeshLambertMaterial({color:0xf2efe6,emissive:0x000000});
  /* ---------- chunks ---------- */
  const CH=40,LAT=[-160,-112,-78,-54,-37,-25,-16,-10,-6.8,-5.6,5.6,6.8,10,16,25,37,54,78,112,160];const chunks=new Map();const col=new T.Color();let cpEvery=250;
  function buildChunk(ci){const a=ci*CH;roadAt(a+CH+2);const g=new T.Group();const rows=CH+1,cols=LAT.length;
    const pos=new Float32Array(rows*cols*3),cl=new Float32Array(rows*cols*3),idx=[];
    for(let r=0;r<rows;r++){const p=R[a+r],nx=-Math.cos(p.h),nz=Math.sin(p.h);for(let k=0;k<cols;k++){const d=LAT[k],x=p.x+nx*d,z=p.z+nz*d,y=hAt(p,x,z,d);const o=(r*cols+k)*3;pos[o]=x;pos[o+1]=y;pos[o+2]=z;
      const n=vn(x*.02,z*.02),m=vn(x*.004+9,z*.004);const ad=Math.abs(d);if(ad<7.2)col.setRGB(.55,.5,.4);else{col.setRGB(.28+n*.05+m*.04,.5+n*.08-Math.max(0,y-40)*.004,.2+m*.05);if(y>55){const t2=clamp((y-55)/25,0,1);col.lerp(new T.Color(.55,.52,.5),t2*.7)}}cl[o]=col.r;cl[o+1]=col.g;cl[o+2]=col.b}}
    for(let r=0;r<rows-1;r++)for(let k=0;k<cols-1;k++){if(LAT[k]===-5.6)continue;const i0=r*cols+k,i1=i0+1,i2=i0+cols,i3=i2+1;idx.push(i0,i1,i2,i1,i3,i2)}
    const tg=new T.BufferGeometry();tg.setAttribute('position',new T.BufferAttribute(pos,3));tg.setAttribute('color',new T.BufferAttribute(cl,3));tg.setIndex(idx);tg.computeVertexNormals();g.add(new T.Mesh(tg,terM));
    const rp=new Float32Array(rows*6),ru=new Float32Array(rows*4),ri=[];for(let r=0;r<rows;r++){const p=R[a+r],nx=-Math.cos(p.h),nz=Math.sin(p.h);[-5.7,5.7].forEach((d,k)=>{const o=(r*2+k)*3;rp[o]=p.x+nx*d;rp[o+1]=p.y+.02;rp[o+2]=p.z+nz*d;ru[(r*2+k)*2]=k;ru[(r*2+k)*2+1]=(a+r)/3});if(r<rows-1){const i0=r*2;ri.push(i0,i0+1,i0+2,i0+1,i0+3,i0+2)}}
    const rg=new T.BufferGeometry();rg.setAttribute('position',new T.BufferAttribute(rp,3));rg.setAttribute('uv',new T.BufferAttribute(ru,2));rg.setIndex(ri);rg.computeVertexNormals();g.add(new T.Mesh(rg,roadM));
    // trees, rocks, posts
    const o=new T.Object3D();const NT=90;const tk=new T.InstancedMesh(trunkG,trunkM,NT),pn=new T.InstancedMesh(pineG,pineM,NT),rd=new T.InstancedMesh(roundG,roundM,NT),rk=new T.InstancedMesh(rockG,rockM,14),ps=new T.InstancedMesh(postG,postM,16);let nt=0,npn=0,nrd=0,nrk=0,nps=0;const solid=[];col.setRGB(.2,.45,.2);for(let i=0;i<NT;i++){pn.setColorAt(i,col);rd.setColorAt(i,col)}
    for(let k=0;k<NT*2&&nt<NT;k++){const s=a+Math.random()*CH,p=roadAt(s);const sd=Math.random()<.5?-1:1,d=sd*(13+Math.pow(Math.random(),1.4)*140);const x=p.x-Math.cos(p.h)*d,z=p.z+Math.sin(p.h)*d;if(vn(x*.008,z*.008)<-.15)continue;const y=hAt(p,x,z,d);if(y>70)continue;const sc=.7+Math.random()*.7;o.position.set(x,y-.2,z);o.rotation.set(0,Math.random()*6,0);o.scale.set(sc,sc*(.8+Math.random()*.5),sc);o.updateMatrix();tk.setMatrixAt(nt,o.matrix);nt++;solid.push({x,z,r:.45*sc+.9});
      const pine=y>18||vn(x*.01+3,z*.01)>0;col.setHSL(pine?.33+Math.random()*.04:.22+Math.random()*.08,.45+Math.random()*.2,pine?.22+Math.random()*.08:.3+Math.random()*.1);if(pine){pn.setMatrixAt(npn,o.matrix);pn.setColorAt(npn,col);npn++}else{rd.setMatrixAt(nrd,o.matrix);rd.setColorAt(nrd,col);nrd++}}
    for(let k=0;k<14;k++){const s=a+Math.random()*CH,p=roadAt(s);const d=(Math.random()<.5?-1:1)*(9+Math.random()*60);const x=p.x-Math.cos(p.h)*d,z=p.z+Math.sin(p.h)*d;o.position.set(x,hAt(p,x,z,d),z);const sc=.5+Math.random()*1.5;o.scale.set(sc,sc*.7,sc);o.rotation.set(Math.random(),Math.random()*6,0);o.updateMatrix();rk.setMatrixAt(nrk++,o.matrix);if(sc>.9)solid.push({x,z,r:sc*1.1+.9})}
    for(let s=a;s<a+CH;s+=5){[-6.4,6.4].forEach(d=>{const p=R[s];const x=p.x-Math.cos(p.h)*d,z=p.z+Math.sin(p.h)*d;o.position.set(x,p.y,z);o.rotation.set(0,0,0);o.scale.set(1,1,1);o.updateMatrix();if(nps<16)ps.setMatrixAt(nps++,o.matrix)})}
    tk.count=nt;pn.count=npn;rd.count=nrd;rk.count=nrk;ps.count=nps;[tk,pn,rd,rk,ps].forEach(m=>{if(m.instanceColor)m.instanceColor.needsUpdate=true;g.add(m)});
    if(mode==='trial'){for(let s=a;s<a+CH;s++){if(s>0&&s%cpEvery===0){const p=R[s];const arch=new T.Group();const mat=new T.MeshLambertMaterial({color:0xFF9F43,emissive:0x552200});[-7.2,7.2].forEach(d=>{const m=new T.Mesh(new T.BoxGeometry(.5,6,.5),mat);m.position.set(d,3,0);arch.add(m)});const ban=new T.Mesh(new T.BoxGeometry(15,1.4,.3),new T.MeshBasicMaterial({map:cpTex}));ban.position.y=6;arch.add(ban);arch.position.set(p.x,p.y,p.z);arch.rotation.y=p.h;g.add(arch)}}}
    g.userData.solid=solid;scene.add(g);chunks.set(ci,g)}
  const cpTex=tex(T,256,32,(x,w,h)=>{for(let i=0;i<16;i++){x.fillStyle=i%2?'#1D1A2F':'#fff';x.fillRect(i*w/16,0,w/16,h)}x.fillStyle='#FF9F43';x.fillRect(w*.3,4,w*.4,h-8);x.fillStyle='#fff';x.font='900 20px Figtree, sans-serif';x.textAlign='center';x.textBaseline='middle';x.fillText('CHECKPOINT',w/2,h/2+1)});
  function updChunks(s,all){const cur=Math.floor(s/CH);let built=0;for(let ci=Math.max(0,cur-1);ci<=cur+6;ci++){if(!chunks.has(ci)&&(all||built<1)){buildChunk(ci);built++}}for(const[ci,g]of chunks){if(ci<cur-1||ci>cur+7){scene.remove(g);g.traverse(o=>{if(o.geometry&&o.geometry!==trunkG&&o.geometry!==pineG&&o.geometry!==roundG&&o.geometry!==rockG&&o.geometry!==postG)o.geometry.dispose()});chunks.delete(ci)}}}
  function clearChunks(){for(const[ci,g]of chunks){scene.remove(g);g.traverse(o=>{if(o.isMesh&&!o.isInstancedMesh&&o.geometry)o.geometry.dispose()})}chunks.clear()}
  /* ---------- sky, mountains, stars ---------- */
  const skyU={top:{value:new T.Color()},hor:{value:new T.Color()},sunDir:{value:new T.Vector3()},sunCol:{value:new T.Color()}};
  const sky=new T.Mesh(new T.SphereGeometry(2000,32,16),new T.ShaderMaterial({uniforms:skyU,side:T.BackSide,depthWrite:false,fog:false,vertexShader:'varying vec3 vP;void main(){vP=normalize(position);gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'uniform vec3 top,hor,sunCol,sunDir;varying vec3 vP;void main(){float h=clamp(vP.y,0.,1.);vec3 c=mix(hor,top,pow(h,.55));float s=max(dot(vP,normalize(sunDir)),0.);c+=sunCol*(pow(s,900.)*3.+pow(s,10.)*.35);gl_FragColor=vec4(c,1.);}'}));sky.renderOrder=-2;scene.add(sky);
  const mts=new T.Group();const mCols=[.55,.8];mCols.forEach((sh,L)=>{const N=140,pos=[],ix=[];const Rr=1500-L*260;for(let i=0;i<=N;i++){const a=i/N*Math.PI*2;const hgt=(160+vn(i*.13+L*9,2)*120+vn(i*.5,L)*40)*(1-L*.35);pos.push(Math.sin(a)*Rr,-40,Math.cos(a)*Rr,Math.sin(a)*Rr,hgt,Math.cos(a)*Rr);if(i<N){const k=i*2;ix.push(k,k+1,k+2,k+1,k+3,k+2)}}const gg=new T.BufferGeometry();gg.setAttribute('position',new T.Float32BufferAttribute(pos,3));gg.setIndex(ix);const m=new T.Mesh(gg,new T.MeshBasicMaterial({color:0x6a6a8a,fog:false,side:T.DoubleSide}));m.userData.sh=sh;m.renderOrder=-1;mts.add(m)});scene.add(mts);
  const stG=new T.BufferGeometry();{const a=[];for(let i=0;i<700;i++){const u=Math.random()*2-1,th=Math.random()*6.283,r=Math.sqrt(1-u*u);if(u<.05)continue;a.push(r*Math.cos(th)*1900,u*1900,r*Math.sin(th)*1900)}stG.setAttribute('position',new T.Float32BufferAttribute(a,3))}const stars=new T.Points(stG,new T.PointsMaterial({color:0xffffff,size:2.2,sizeAttenuation:false,transparent:true,opacity:0,fog:false}));scene.add(stars);
  const hemi=new T.HemisphereLight(0xffffff,0x3a4a30,.8),sun=new T.DirectionalLight(0xffffff,.8);scene.add(hemi,sun,sun.target);scene.fog=new T.Fog(0xffffff,160,1100);
  const TOD=[{n:'Midday',top:0x2f6fd0,hor:0xbfe2ff,fog:0xcfe6f7,sun:0xfff4e0,el:1.1,si:.95,hi:.85,gnd:0x4a5a30,far:1100},{n:'Golden hour',top:0x3a64b8,hor:0xffd9a0,fog:0xf2d6b0,sun:0xffc070,el:.28,si:.9,hi:.7,gnd:0x5a4a30,far:1000},{n:'Sunset',top:0x2a2a6a,hor:0xff8a5a,fog:0xd08a78,sun:0xff7040,el:.05,si:.6,hi:.5,gnd:0x3a2a40,far:850},{n:'Night',top:0x05071a,hor:0x1a2350,fog:0x10152e,sun:0x9fb0ff,el:.7,si:.18,hi:.22,gnd:0x10101a,far:420}];
  let todI=1,todT=1,todAuto=false;const cA=new T.Color(),cB=new T.Color();
  function applyTod(dt){if(todAuto){todT=(todT+dt/90)%TOD.length}else todT+=(todI-todT)*Math.min(1,dt*1.5);const i0=Math.floor(todT)%TOD.length,i1=(i0+1)%TOD.length,f=todT-Math.floor(todT);const A=TOD[i0],B=TOD[i1];const mix=(a,b)=>cA.setHex(a).lerp(cB.setHex(b),f);
    skyU.top.value.copy(mix(A.top,B.top));skyU.hor.value.copy(mix(A.hor,B.hor));skyU.sunCol.value.copy(mix(A.sun,B.sun)).multiplyScalar(i0===3&&f<.5||i1===3&&f>.5?.15:1);scene.fog.color.copy(mix(A.fog,B.fog));const el2=A.el+(B.el-A.el)*f;const far=A.far+(B.far-A.far)*f;scene.fog.far=far;scene.fog.near=far*.12;
    sun.color.copy(mix(A.sun,B.sun));sun.intensity=A.si+(B.si-A.si)*f;hemi.intensity=A.hi+(B.hi-A.hi)*f;hemi.groundColor.copy(mix(A.gnd,B.gnd));hemi.color.copy(mix(A.hor,B.hor)).lerp(new T.Color(0xffffff),.5);
    const night=(i0===3?1-f:0)+(i1===3?f:0);stars.material.opacity=night;mts.children.forEach(m=>m.material.color.copy(skyU.hor.value).lerp(skyU.top.value,.35).multiplyScalar(m.userData.sh));
    const sd=new T.Vector3(Math.sin(.9),Math.sin(el2),Math.cos(.9)).normalize();skyU.sunDir.value.copy(sd);lightsOn=night>.35||(todAuto?false:todI===2);postM.emissive.setHex(night>.35?0x886644:0);return sd}
  let lightsOn=false,lightsForce=null;
  /* ---------- cars ---------- */
  const CARS=[{n:'Hatchback',col:0xFF9F43,vmax:50,acc:9.5,grip:9.5,steer:.62,off:.6,desc:'Nimble and friendly.'},{n:'GT Coupé',col:0xF2352A,vmax:80,acc:15,grip:10.5,steer:.5,off:.45,desc:'Very fast. Brake for corners!'},{n:'Rally',col:0x2d6fd6,vmax:62,acc:12,grip:10,steer:.6,off:.9,desc:'Grips on grass and dirt.'}];let carI=S.get('or_car',0),spec=CARS[carI];
  function carMesh(colr){const g=new T.Group();const bm=new T.MeshLambertMaterial({color:colr});const dk=new T.MeshLambertMaterial({color:0x1D1A2F});const gl=new T.MeshLambertMaterial({color:0x2a3a5a,emissive:0x0a1020});
    const body=new T.Mesh(new T.BoxGeometry(1.9,.62,4.3),bm);body.position.y=.62;g.add(body);const cab=new T.Mesh(new T.BoxGeometry(1.62,.55,2.1),gl);cab.position.set(0,1.18,-.25);g.add(cab);const roof=new T.Mesh(new T.BoxGeometry(1.6,.08,1.9),bm);roof.position.set(0,1.48,-.3);g.add(roof);
    [[-.85,1.35],[.85,1.35],[-.85,-1.4],[.85,-1.4]].forEach(([x,z])=>{const w=new T.Mesh(new T.CylinderGeometry(.36,.36,.3,12),dk);w.rotation.z=Math.PI/2;w.position.set(x,.36,z);g.add(w)});
    const hl=new T.MeshBasicMaterial({color:0xfff4d0}),tl=new T.MeshBasicMaterial({color:0xff2a2a});[-.62,.62].forEach(x=>{const a=new T.Mesh(new T.BoxGeometry(.4,.16,.05),hl);a.position.set(x,.72,2.16);g.add(a);const b=new T.Mesh(new T.BoxGeometry(.4,.14,.05),tl);b.position.set(x,.74,-2.16);g.add(b)});return g}
  let myCar=null;const headL=[new T.SpotLight(0xfff0d0,0,90,.45,.5,1.2),new T.SpotLight(0xfff0d0,0,90,.45,.5,1.2)];headL.forEach(l=>{scene.add(l,l.target)});
  // cockpit (attached to camera)
  scene.add(camera);const dash=new T.Group();camera.add(dash);let wheel,hood;
  function buildDash(){dash.clear();const dk=new T.MeshLambertMaterial({color:0x221f30}),bm=new T.MeshLambertMaterial({color:spec.col});hood=new T.Mesh(new T.BoxGeometry(2.2,.1,2.4),bm);hood.position.set(.38,-.78,-2.1);hood.rotation.x=.08;dash.add(hood);
    const board=new T.Mesh(new T.BoxGeometry(2.6,.34,.7),dk);board.position.set(.38,-.52,-.85);dash.add(board);const top=new T.Mesh(new T.BoxGeometry(2.6,.1,.3),dk);top.position.set(.38,.62,-.7);dash.add(top);
    wheel=new T.Group();const rim=new T.Mesh(new T.TorusGeometry(.2,.028,8,28),new T.MeshLambertMaterial({color:0x111018}));wheel.add(rim);[0,2.1,4.2].forEach(a=>{const sp=new T.Mesh(new T.BoxGeometry(.2,.03,.03),rim.material);sp.rotation.z=a;sp.position.set(Math.cos(a)*.1,Math.sin(a)*.1,0);wheel.add(sp)});wheel.position.set(0,-.42,-.55);wheel.rotation.x=-.35;dash.add(wheel);
    const mir=new T.Mesh(new T.BoxGeometry(.32,.09,.03),dk);mir.position.set(.38,.5,-.62);dash.add(mir);dash.traverse(o=>{o.renderOrder=5})}
  /* ---------- traffic ---------- */
  const traffic=[];const TCOL=[0xffffff,0x7FC8F8,0x6EE7B7,0xFFD23F,0xB9A7FF,0x8c86a3,0x3a3552];
  function spawnTraffic(t,sBase,first){t.dir=Math.random()<.5?1:-1;t.s=sBase+(first?40+Math.random()*300:220+Math.random()*260);t.v=(t.dir>0?16+Math.random()*6:20+Math.random()*6)/SEG}
  /* ---------- state ---------- */
  const car={x:0,z:0,y:0,yaw:0,vx:0,vz:0,steer:0,pitch:0,roll:0,s:0,hint:0,odo:0,vy:0,lat:7.5,dsc:0};let mode='cruise',state='menu',cam3=false,look=0,tLeft=0,nextCp=0,cps=0,shake=0,best=c.best()||0,camBob=0;
  const Q=el('div',{style:'position:absolute;left:14px;top:12px;color:#fff;font:700 14px "JetBrains Mono",monospace;text-shadow:0 2px 0 rgba(0,0,0,.5);pointer-events:none;line-height:1.5'});const big=el('div',{style:'position:absolute;left:0;right:0;top:38%;text-align:center;color:#fff;font:34px "Bagel Fat One",sans-serif;text-shadow:0 3px 0 #1D1A2F;pointer-events:none;transition:opacity .4s;opacity:0'});
  const spd=el('canvas',{width:180,height:180,style:'position:absolute;right:12px;bottom:12px;width:140px;height:140px;pointer-events:none'});hud.append(Q,big,spd);const sx=spd.getContext('2d');
  let bigT=0;const say=(t,d)=>{big.textContent=t;big.style.opacity=1;bigT=d||1.5};
  function drawSpeedo(kmh,gear,rpm){const x=sx;x.clearRect(0,0,180,180);x.fillStyle='rgba(20,18,32,.72)';x.beginPath();x.arc(90,90,86,0,7);x.fill();x.strokeStyle='rgba(255,255,255,.85)';x.lineWidth=3;const mx=Math.ceil(spec.vmax*3.6/40)*40;for(let v=0;v<=mx;v+=20){const a=Math.PI*.75+v/mx*Math.PI*1.5;const r0=v%40?70:64;x.beginPath();x.moveTo(90+Math.cos(a)*r0,90+Math.sin(a)*r0);x.lineTo(90+Math.cos(a)*78,90+Math.sin(a)*78);x.stroke();if(v%40===0){x.fillStyle='#fff';x.font='600 12px Figtree, sans-serif';x.textAlign='center';x.textBaseline='middle';x.fillText(v,90+Math.cos(a)*52,90+Math.sin(a)*52)}}
    x.strokeStyle='#FF9F43';x.lineWidth=5;x.beginPath();x.arc(90,90,82,Math.PI*.75,Math.PI*.75+clamp(rpm/7000,0,1)*Math.PI*1.5);x.stroke();const a=Math.PI*.75+clamp(kmh/mx,0,1.05)*Math.PI*1.5;x.strokeStyle='#F2352A';x.lineWidth=4;x.beginPath();x.moveTo(90,90);x.lineTo(90+Math.cos(a)*70,90+Math.sin(a)*70);x.stroke();x.fillStyle='#fff';x.beginPath();x.arc(90,90,6,0,7);x.fill();
    x.font='800 26px "JetBrains Mono", monospace';x.textAlign='center';x.fillText(Math.round(kmh),90,128);x.font='600 11px Figtree, sans-serif';x.fillText('km/h · '+gear,90,148)}
  /* ---------- engine sound ---------- */
  let eng=null;function engStart(){if(eng||muted)return;try{const A=ac();const o1=A.createOscillator(),o2=A.createOscillator(),f=A.createBiquadFilter(),g=A.createGain();o1.type='sawtooth';o2.type='square';f.type='lowpass';f.frequency.value=700;g.gain.value=0;o1.connect(f);o2.connect(f);f.connect(g);g.connect(A.destination);o1.start();o2.start();eng={A,o1,o2,f,g}}catch(e){eng=null}}
  function engStop(){if(!eng)return;try{eng.g.gain.value=0;eng.o1.stop();eng.o2.stop();eng.g.disconnect()}catch(e){}eng=null}
  /* ---------- flow ---------- */
  function reset(){clearChunks();Object.assign(car,{x:-1.8,z:0,yaw:0,vx:0,vz:0,steer:0,s:0,hint:0,odo:0});const g0=groundY(0,0,0);car.y=g0.y;updChunks(0,true);traffic.forEach(t=>scene.remove(t.m));traffic.length=0;for(let i=0;i<7;i++){const t={m:carMesh(pick(TCOL))};scene.add(t.m);spawnTraffic(t,0,true);traffic.push(t)}
    if(myCar)scene.remove(myCar);myCar=carMesh(spec.col);scene.add(myCar);buildDash();tLeft=c.pick(70,55,45);nextCp=cpEvery;cps=0;state='play';engStart();say(mode==='trial'?'GO! Reach the checkpoints':'Enjoy the drive',1.6)}
  function menu(){state='menu';engStop();const ov=st3.overlay('<small class="kick">3D driving · first person</small><h2>Open Road</h2><p>An endless road through hills, forests and mountains, seen from the driver’s seat. Pick a car and a time of day.</p><p class="ctl"><b>Controls:</b> W/↑ gas, S/↓ brake and reverse, A/D steer, Space or Shift handbrake: tap it into a corner to drift, and the car straightens itself out when you let go. C switches between cockpit and chase camera, T changes the time of day, H toggles headlights. Drag the mouse to look around. P pauses. On a phone: steer with the left thumb, hold GAS and BRAKE.</p>',[['Cruise (no timer)',()=>{mode='cruise';reset()},true],['Time trial',()=>{mode='trial';reset()}]]);
    const card=ov.querySelector('.ovc');const rowC=el('div',{class:'row',style:'justify-content:center;flex-wrap:wrap'});CARS.forEach((k,i)=>{const b=el('button',{class:'btn'+(i===carI?' on':''),type:'button',title:k.desc},k.n);b.addEventListener('click',e=>{e.stopPropagation();carI=i;spec=CARS[i];S.set('or_car',i);rowC.querySelectorAll('.btn').forEach(q=>q.classList.toggle('on',q===b))});rowC.append(b)});
    const rowT=el('div',{class:'row',style:'justify-content:center;flex-wrap:wrap'});[...TOD.map((t,i)=>[t.n,i]),['Auto cycle',-1]].forEach(([n,i])=>{const b=el('button',{class:'btn'+((i===-1?todAuto:!todAuto&&i===todI)?' on':''),type:'button'},n);b.addEventListener('click',e=>{e.stopPropagation();if(i<0)todAuto=true;else{todAuto=false;todI=i;todT=i}rowT.querySelectorAll('.btn').forEach(q=>q.classList.toggle('on',q===b))});rowT.append(b)});
    const rowL=card.querySelector('.row');card.insertBefore(el('p',{class:'ctl',style:'margin:8px 0 2px'},el('b',null,'Car')),rowL);card.insertBefore(rowC,rowL);card.insertBefore(el('p',{class:'ctl',style:'margin:8px 0 2px'},el('b',null,'Time of day')),rowL);card.insertBefore(rowT,rowL);
    if(best)card.insertBefore(el('p',{class:'ctl'},'Best time-trial distance: '+best+' km'),rowL)}
  function endTrial(){state='over';engStop();const km=+(car.odo/1000).toFixed(1);best=c.best(km);st3.overlay('<h2>Out of time!</h2><p>You drove '+km+' km and made '+cps+' checkpoint'+(cps===1?'':'s')+'. Best: '+best+' km.</p>',[['Drive again',()=>reset(),true],['Menu',menu]])}
  const keyL={};c.on(document,'keydown',e=>{const k=e.key.toLowerCase();if(keyL[k])return;keyL[k]=1;if(state!=='play')return;if(k==='c'){cam3=!cam3}if(k==='t'){todAuto=false;todI=(Math.round(todT)+1)%TOD.length;say(TOD[todI].n,1)}if(k==='h'){lightsForce=!(lightsForce==null?lightsOn:lightsForce);say('Headlights '+(lightsForce?'on':'off'),.8)}if(k==='p'){engStop();st3.overlay('<small class="kick">Paused</small><h2>Pulled over</h2>',[['Resume',()=>{engStart()},true],['Menu',menu]])}});c.on(document,'keyup',e=>{keyL[e.key.toLowerCase()]=0});
  const smokeTex=(()=>{const cv=document.createElement('canvas');cv.width=cv.height=64;const g=cv.getContext('2d');const gr=g.createRadialGradient(32,32,0,32,32,32);gr.addColorStop(0,'rgba(235,235,235,.9)');gr.addColorStop(1,'rgba(235,235,235,0)');g.fillStyle=gr;g.fillRect(0,0,64,64);return new T.CanvasTexture(cv)})();const smokeP=[];let smokeI=0;for(let i=0;i<70;i++){const m=new T.Sprite(new T.SpriteMaterial({map:smokeTex,transparent:true,depthWrite:false,opacity:0}));m.visible=false;scene.add(m);smokeP.push(m)}
  /* ---------- main loop ---------- */
  const tmp=new T.Vector3(),eul=new T.Euler(0,0,0,'YXZ');
  st3.onFrame((dt,now)=>{const sd=applyTod(dt);const I=input,K=I.keys;const play=state==='play'&&!wrap.classList.contains('paused');
    if(play){const thr=(K.w||K.arrowup||I.fire?1:0),brk=(K.s||K.arrowdown||I.alt?1:0),hb=K[' ']||I.jumpBtn||K.shift?1:0;const stIn=clamp((K.d||K.arrowright?1:0)-(K.a||K.arrowleft?1:0)+(Math.abs(I.joy.x)>.08?I.joy.x:0),-1,1);
      const fx=Math.sin(car.yaw),fz=Math.cos(car.yaw),rx=-Math.cos(car.yaw),rz=Math.sin(car.yaw);let vf=car.vx*fx+car.vz*fz,vr=car.vx*rx+car.vz*rz;const q=near(car.x,car.z,car.hint);car.hint=q.i;car.s=q.s;const off=Math.abs(q.d)>6.2;
      car.steer+=(stIn-car.steer)*Math.min(1,dt*(stIn?3.2:5));const ang=car.steer*spec.steer/(1+Math.abs(vf)*.045);
      if(thr)vf+=spec.acc*(1-Math.pow(clamp(vf/spec.vmax,0,1),2))*dt*(off?.7:1);if(brk){if(vf>.5)vf-=24*dt;else vf=Math.max(-9,vf-6*dt)}if(!thr&&!brk)vf-=Math.sign(vf)*Math.min(Math.abs(vf),(.35+(off?2.5:0))*dt);
      vf-=Math.sign(vf)*(.00045*vf*vf+(off?.004*vf*vf:0))*dt*(off?1:1);vf-=9.8*Math.sin(car.pitch)*dt*.7;if(hb)vf-=Math.sign(vf)*Math.min(Math.abs(vf),(Math.abs(stIn)>.2?1.6:6)*dt);
      const gmax=spec.grip*(off?(1-(1-spec.off)*.6):1)*(hb?.55:1);let w=vf*Math.tan(ang)/2.6;if(Math.abs(w*vf)>gmax)w=Math.sign(w)*gmax/Math.max(1,Math.abs(vf));if(hb&&Math.abs(vf)>8)w*=1.5;car.yaw-=w*dt;
      const latT=(hb?1.2:off?2.6+spec.off*3:7.5);car.lat+=(latT-car.lat)*Math.min(1,dt*(hb?8:1.6));vr*=Math.exp(-car.lat*dt);if(!hb&&Math.abs(vr)>1.5&&vf>5){car.yaw+=Math.atan2(vr,Math.abs(vf))*dt*1.4}const nfx=Math.sin(car.yaw),nfz=Math.cos(car.yaw),nrx=-Math.cos(car.yaw),nrz=Math.sin(car.yaw);car.vx=nfx*vf+nrx*vr;car.vz=nfz*vf+nrz*vr;
      car.x+=car.vx*dt;car.z+=car.vz*dt;{const cc=Math.floor(car.s/CH);for(const ci of [cc-1,cc,cc+1]){const g=chunks.get(ci);if(!g)continue;for(const o of g.userData.solid){const dx=car.x-o.x,dz=car.z-o.z,dd=Math.hypot(dx,dz);if(dd<o.r+1){const nx=dx/(dd||1),nz=dz/(dd||1);car.x=o.x+nx*(o.r+1);car.z=o.z+nz*(o.r+1);const rel=car.vx*nx+car.vz*nz;if(rel<0){const hit=-rel;car.vx-=1.3*rel*nx;car.vz-=1.3*rel*nz;car.vx*=.4;car.vz*=.4;if(hit>6){shake=.8;noise(.4,'lowpass',300,.35);say(pick(['TIMBER!','OUCH!','CRUNCH!']),.9);if(mode==='trial')tLeft-=2}}}}}}if(Math.abs(q.d)>150){const p=q.p;car.x+=(p.x-car.x)*dt;car.z+=(p.z-car.z)*dt}
      const sp=Math.hypot(car.vx,car.vz);car.odo+=Math.max(0,vf)*dt;if(off&&sp>8)shake=Math.max(shake,.05+sp*.002);const slide=Math.abs(vr);if(slide>3&&sp>6){if(Math.random()<.35)beep(180+Math.random()*80,.05,'sawtooth',.012);for(let k2=0;k2<2;k2++){const m=smokeP[smokeI++%smokeP.length];const side=k2?1:-1;m.position.set(car.x-fx*1.6+rx*side*.8,car.y+.3,car.z-fz*1.6+rz*side*.8);m.userData.t=1;m.material.opacity=.45;m.scale.setScalar(.8);m.visible=true}car.dsc+=slide*dt*2}else if(car.dsc>0){if(car.dsc>30)say('DRIFT +'+Math.round(car.dsc),.9);car.dsc=0}
      smokeP.forEach(m=>{if(!m.visible)return;m.userData.t-=dt*.9;m.position.y+=dt*.6;m.scale.multiplyScalar(1+dt*1.8);m.material.opacity=Math.max(0,m.userData.t*.45);if(m.userData.t<=0)m.visible=false});
      // traffic
      traffic.forEach(t=>{t.s+=t.dir*t.v*dt;if(t.s<car.s-60||t.s>car.s+520||t.s<2)spawnTraffic(t,car.s,false);const p=roadAt(t.s);const d=t.dir>0?1.8:-1.8;t.x=p.x-Math.cos(p.h)*d;t.z=p.z+Math.sin(p.h)*d;t.m.position.set(t.x,p.y,t.z);t.m.rotation.y=p.h+(t.dir>0?0:Math.PI);
        const dx=car.x-t.x,dz=car.z-t.z,dd=Math.hypot(dx,dz);if(dd<2.6){const nx=dx/(dd||1),nz=dz/(dd||1);car.x=t.x+nx*2.6;car.z=t.z+nz*2.6;const rel=car.vx*nx+car.vz*nz;if(rel<0){car.vx-=1.6*rel*nx;car.vz-=1.6*rel*nz;car.vx*=.55;car.vz*=.55;shake=.6;noise(.35,'lowpass',400,.3);say('CRASH!',.9);if(mode==='trial'){tLeft-=3}}}});
      // checkpoints
      if(mode==='trial'){tLeft-=dt;if(car.s>=nextCp){nextCp+=cpEvery;cps++;const add=c.pick(40,34,28);tLeft+=add;say('CHECKPOINT +'+add+'s',1.4);[660,880,1100].forEach((f,i)=>c.after(()=>beep(f,.1,'triangle',.06),i*80))}if(tLeft<=0)endTrial()}
      updChunks(car.s);
      // engine sound
      if(eng&&!muted){const gears=[0,.16,.3,.46,.62,.8,1.01];const fr=clamp(Math.abs(vf)/spec.vmax,0,1);let gi=1;while(gi<6&&fr>gears[gi])gi++;const rpm=900+clamp((fr-gears[gi-1])/(gears[gi]-gears[gi-1]),0,1)*5200+(thr&&fr<.02?600:0);const f0=rpm/60*2;const tt=eng.A.currentTime;eng.o1.frequency.setTargetAtTime(f0,tt,.05);eng.o2.frequency.setTargetAtTime(f0*.5,tt,.05);eng.f.frequency.setTargetAtTime(400+rpm*.25,tt,.05);eng.g.gain.setTargetAtTime(.025+thr*.03,tt,.08);car.rpm=rpm;car.gear=vf<-.5?'R':String(gi)}else if(eng)eng.g.gain.value=0;
      const kmh=Math.abs(vf)*3.6;drawSpeedo(kmh,car.gear||'1',car.rpm||900);
      Q.innerHTML=(mode==='trial'?'<span style="font-size:22px;color:'+(tLeft<10?'#F2352A':'#FFD23F')+'">⏱ '+Math.max(0,tLeft).toFixed(1)+'s</span><br>Next checkpoint '+Math.max(0,((nextCp-car.s)*SEG/1000)).toFixed(2)+' km<br>':'')+'Trip '+(car.odo/1000).toFixed(2)+' km'+(off?'<br><span style="color:#FFD23F">Off road!</span>':'')+'<br><span style="opacity:.75;font-size:12px">'+(cam3?'Chase cam':'Cockpit')+' · C camera · T time · P pause</span>'}
    else if(state==='menu'){car.yaw+=dt*.05}
    // ground follow + pose
    const gC=groundY(car.x,car.z,car.hint),fx=Math.sin(car.yaw),fz=Math.cos(car.yaw),rx=-Math.cos(car.yaw),rz=Math.sin(car.yaw);const yF=groundY(car.x+fx*1.4,car.z+fz*1.4,car.hint).y,yB=groundY(car.x-fx*1.4,car.z-fz*1.4,car.hint).y,yR=groundY(car.x+rx*.9,car.z+rz*.9,car.hint).y,yL=groundY(car.x-rx*.9,car.z-rz*.9,car.hint).y;
    const gy=(yF+yB+yR+yL)/4;car.vy+=((gy-car.y)*90-car.vy*14)*dt;car.y+=car.vy*dt;if(car.y<gy-.3){car.y=gy-.3;car.vy=0}car.pitch+=(Math.atan2(yF-yB,2.8)-car.pitch)*Math.min(1,dt*10);car.roll+=(Math.atan2(yR-yL,1.8)-car.roll)*Math.min(1,dt*10);
    if(myCar){myCar.position.set(car.x,car.y,car.z);eul.set(-car.pitch,car.yaw,-car.roll,'YXZ');myCar.rotation.copy(eul);myCar.visible=cam3}
    // headlights
    const lon=lightsForce!=null?lightsForce:lightsOn;headL.forEach((l,i)=>{const s2=i?.6:-.6;l.intensity=lon&&myCar?2.2:0;l.position.set(car.x+fx*2+rx*s2,car.y+.8,car.z+fz*2+rz*s2);l.target.position.set(car.x+fx*30+rx*s2*2,car.y-1,car.z+fz*30+rz*s2*2)});
    // camera
    const sp=Math.hypot(car.vx,car.vz);if(I.down&&!I.touch||I.touch&&I.mdx)look=clamp(look-I.mdx*.004,-2.2,2.2);else look*=Math.pow(.02,dt);shake=Math.max(0,shake-dt*1.5);camBob+=dt*sp*.25;
    if(cam3||state!=='play'){const back=state==='play'?7.5:9,up=state==='play'?2.8:3.2;const cy=car.yaw+(state==='play'?look:0);tmp.set(car.x-Math.sin(cy)*back,car.y+up,car.z-Math.cos(cy)*back);const gq=groundY(tmp.x,tmp.z,car.hint).y;tmp.y=Math.max(tmp.y,gq+1.2);camera.position.lerp(tmp,Math.min(1,dt*(state==='play'?6:2)));camera.lookAt(car.x+fx*4,car.y+1.2,car.z+fz*4);dash.visible=false}
    else{const ex=.38,ey=1.18,ez=-.1;camera.position.set(car.x+rx*-ex+fx*ez,car.y+ey+Math.sin(camBob)*.012*Math.min(1,sp/20),car.z+rz*-ex+fz*ez);eul.set(car.pitch+(Math.random()-.5)*shake*.05,car.yaw+Math.PI+look,car.roll*.8+(Math.random()-.5)*shake*.03,'YXZ');camera.rotation.copy(eul);dash.visible=true;if(wheel)wheel.rotation.z=-car.steer*2.2}
    const fovT=68+clamp(sp/spec.vmax,0,1.2)*12;if(Math.abs(camera.fov-fovT)>.1){camera.fov+=(fovT-camera.fov)*Math.min(1,dt*2);camera.updateProjectionMatrix()}
    sky.position.copy(camera.position);mts.position.set(camera.position.x,0,camera.position.z);stars.position.copy(camera.position);sun.position.copy(camera.position).addScaledVector(sd,200);sun.target.position.copy(camera.position);
    if(bigT>0){bigT-=dt;if(bigT<=0)big.style.opacity=0}c.stat('Open Road · '+(mode==='trial'?'Time trial':'Cruise')+' · '+(car.odo/1000).toFixed(1)+' km')});
  updChunks(0,true);car.y=groundY(0,0,0).y;camera.position.set(-6,car.y+4,-8);menu();
  return()=>{engStop();st3.dispose()}})}});
