/* ================= COOL INFO 2 ================= */
function chipRow(opts,cur,on,multi){const row=el('div',{class:'row',style:'flex-wrap:wrap;gap:6px;justify-content:center'});const bs=opts.map((o,i)=>{const b=el('button',{type:'button',class:'btn',style:'font-size:14px;padding:6px 11px'},o);b.addEventListener('click',()=>{on(i);paint()});row.append(b);return b});function paint(){const s=cur();bs.forEach((b,i)=>b.classList.toggle('primary',multi?s.includes(i):s===i))}paint();row.paint=paint;return row}
const fmtN=(n,d)=>n.toLocaleString('en-US',{maximumFractionDigits:d||0,minimumFractionDigits:d||0});
function fmtDur(h){if(!isFinite(h))return'forever';const m=h*60;if(m<1)return fmtN(m*60,1)+' seconds';if(h<1)return fmtN(m,m<10?1:0)+' minutes';if(h<48)return fmtN(h,h<10?1:0)+' hours';const d=h/24;if(d<365*2)return fmtN(d,d<10?1:0)+' days';const y=d/365.25;if(y<1e6)return fmtN(y,y<10?1:0)+' years';if(y<1e9)return fmtN(y/1e6,1)+' million years';return fmtN(y/1e9,1)+' billion years'}
const savedBday=()=>{const s=S.get('bday','');return s?new Date(s+'T12:00:00'):null};

/* ---- World Clock ---- */
const CLOCKS=[['Honolulu','Pacific/Honolulu','🌺'],['Los Angeles','America/Los_Angeles','🎬'],['Denver','America/Denver','🏔️'],['Chicago','America/Chicago','🌭'],['Mexico City','America/Mexico_City','🌮'],['New York','America/New_York','🗽'],['Toronto','America/Toronto','🍁'],['São Paulo','America/Sao_Paulo','⚽'],['Reykjavík','Atlantic/Reykjavik','🌋'],['London','Europe/London','💂'],['Lagos','Africa/Lagos','🥁'],['Paris','Europe/Paris','🥐'],['Berlin','Europe/Berlin','🥨'],['Rome','Europe/Rome','🍕'],['Cairo','Africa/Cairo','🐫'],['Johannesburg','Africa/Johannesburg','🦁'],['Nairobi','Africa/Nairobi','🦒'],['Moscow','Europe/Moscow','🪆'],['Dubai','Asia/Dubai','🏙️'],['Mumbai','Asia/Kolkata','🏏'],['Bangkok','Asia/Bangkok','🛺'],['Singapore','Asia/Singapore','🦁'],['Beijing','Asia/Shanghai','🐼'],['Seoul','Asia/Seoul','🎤'],['Tokyo','Asia/Tokyo','🗼'],['Sydney','Australia/Sydney','🦘'],['Auckland','Pacific/Auckland','🥝']];
function tzParts(d,tz){const p={};try{new Intl.DateTimeFormat('en-US',{timeZone:tz,year:'numeric',month:'numeric',day:'numeric',hour:'numeric',minute:'numeric',second:'numeric',hour12:false,weekday:'short'}).formatToParts(d).forEach(x=>p[x.type]=x.value)}catch(e){return null}const h=(+p.hour)%24;return{h,m:+p.minute,s:+p.second,wd:p.weekday,off:Math.round((Date.UTC(+p.year,+p.month-1,+p.day,h,+p.minute)-Math.floor(d.getTime()/6e4)*6e4)/6e4)}}
function doing(h){return h<6?['😴','Probably asleep']:h<8?['🥣','Breakfast time']:h<12?['💼','Morning: school and work']:h<13?['🥪','Lunchtime']:h<17?['📚','Afternoon']:h<19?['🍝','Dinner time']:h<22?['📺','Evening chill']:['🌙','Getting late']}
G.push({id:'info_clock',name:'World Clock',kind:'info',wide:true,tint:'#7FC8F8',blurb:'What time is it in Tokyo right now? Is your friend in London asleep? Live clocks for 27 cities, plus a time-travel slider for planning calls.',
art:'<rect width="120" height="72" fill="#7FC8F8"/><g stroke="#1D1A2F" stroke-width="2.5"><circle cx="32" cy="36" r="20" fill="#FFFDF6"/><circle cx="88" cy="36" r="20" fill="#1D1A2F"/></g><path d="M32 36V22M32 36l9 5" stroke="#1D1A2F" stroke-width="3" stroke-linecap="round"/><path d="M88 36V24M88 36l-8 6" stroke="#FFD23F" stroke-width="3" stroke-linecap="round"/><circle cx="100" cy="22" r="3" fill="#FFE27A"/>',
run(root,c){const you=Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC';let shift=0;
  const sl=el('input',{type:'range',min:-12,max:24,step:.5,value:0,style:'width:100%','aria-label':'Time travel hours'});const lab=el('b');const grid=el('div',{class:'igrid',style:'grid-template-columns:repeat(auto-fill,minmax(260px,1fr))'});
  root.append(el('div',{class:'card',style:'width:100%'},el('div',{class:'row',style:'justify-content:space-between;flex-wrap:wrap'},el('span',null,'⏩ Time travel: drag to see what time it will be everywhere'),lab),sl),grid);c.on(sl,'input',()=>{shift=+sl.value;tick(true)});
  const list=[['You ('+you.split('/').pop().replace(/_/g,' ')+')',you,'📍']].concat(CLOCKS);
  const cells=list.map(([n,tz,ic])=>{const cv=el('canvas',{width:120,height:120,style:'width:84px;height:84px;flex:none'});const t=el('div',{class:'ibig mono',style:'font-size:24px'}),s=el('small'),o=el('small');const card=el('div',{class:'icard',style:'display:flex;gap:10px;align-items:center;padding:10px'},cv,el('div',null,el('h4',null,ic+' '+n),t,s,el('br'),o));grid.append(card);return{n,tz,cv,x:cv.getContext('2d'),t,s,o,card}});
  function face(x,h,m,s){const night=h<6||h>=19;x.clearRect(0,0,120,120);x.fillStyle=night?'#1D1A2F':'#FFFDF6';x.strokeStyle='#1D1A2F';x.lineWidth=5;x.beginPath();x.arc(60,60,55,0,7);x.fill();x.stroke();x.fillStyle=night?'#8c86a3':'#1D1A2F';for(let i=0;i<12;i++){const a=i/12*Math.PI*2;x.beginPath();x.arc(60+Math.sin(a)*45,60-Math.cos(a)*45,i%3?2:4,0,7);x.fill()}
    const hand=(a,l,w,col)=>{x.strokeStyle=col;x.lineWidth=w;x.lineCap='round';x.beginPath();x.moveTo(60,60);x.lineTo(60+Math.sin(a)*l,60-Math.cos(a)*l);x.stroke()};hand(((h%12)+m/60)/12*Math.PI*2,28,7,night?'#FFD23F':'#1D1A2F');hand((m+s/60)/60*Math.PI*2,40,5,night?'#FFFDF6':'#1D1A2F');hand(s/60*Math.PI*2,44,2,'#F2352A');x.fillStyle='#F2352A';x.beginPath();x.arc(60,60,5,0,7);x.fill();
    x.font='20px sans-serif';x.textAlign='center';x.fillText(night?'🌙':'☀️',60,92)}
  let last=0;function tick(force){const d=new Date(Date.now()+shift*36e5);const me=tzParts(d,you);lab.textContent=shift?(shift>0?'+':'')+shift+' hours from now':'Right now';
    cells.forEach(q=>{const p=tzParts(d,q.tz);if(!p){q.card.style.display='none';return}face(q.x,p.h,p.m,p.s);if(force||Date.now()-last>400){const[e,w]=doing(p.h);q.t.textContent=pad2(p.h%12||12)+':'+pad2(p.m)+(p.h<12?' am':' pm');q.s.textContent=p.wd+' · '+e+' '+w;const df=me?(p.off-me.off)/60:0;q.o.textContent=q.tz===you?'Your time zone':df===0?'Same time as you':(df>0?'+':'')+df+' h from you'}});if(force||Date.now()-last>400)last=Date.now()}
  c.loop(()=>tick(false));tick(true);c.stat('World Clock')}});

/* ---- Countdowns ---- */
function nthDow(y,m,dow,n){const d=new Date(y,m,1,0,0,0);const off=(dow-d.getDay()+7)%7;return new Date(y,m,1+off+(n-1)*7)}
function easter(y){const a=y%19,b=Math.floor(y/100),c2=y%100,d=Math.floor(b/4),e=b%4,f=Math.floor((b+8)/25),g=Math.floor((b-f+1)/3),h=(19*a+b-d-g+15)%30,i=Math.floor(c2/4),k=c2%4,l=(32+2*e+2*i-h-k)%7,m=Math.floor((a+11*h+22*l)/451),mo=Math.floor((h+l-7*m+114)/31),da=((h+l-7*m+114)%31)+1;return new Date(y,mo-1,da)}
const HOLI=[['New Year’s Day','🎆',y=>new Date(y,0,1)],['Valentine’s Day','💘',y=>new Date(y,1,14)],['St. Patrick’s Day','☘️',y=>new Date(y,2,17)],['April Fools’ Day','🤡',y=>new Date(y,3,1)],['Easter','🐣',easter],['Mother’s Day (US)','💐',y=>nthDow(y,4,0,2)],['Father’s Day (US)','👔',y=>nthDow(y,5,0,3)],['First day of summer','🏖️',y=>new Date(y,5,21)],['Fourth of July','🎇',y=>new Date(y,6,4)],['Halloween','🎃',y=>new Date(y,9,31)],['Thanksgiving (US)','🦃',y=>nthDow(y,10,4,4)],['Christmas','🎄',y=>new Date(y,11,25)],['New Year’s Eve','🥳',y=>new Date(y,11,31)]];
G.push({id:'info_countdown',name:'Countdowns',kind:'info',wide:true,tint:'#FF8FB1',blurb:'Live countdowns to Christmas, Halloween, summer, your birthday and anything else you add, ticking by the second.',
art:'<rect width="120" height="72" fill="#FF8FB1"/><rect x="14" y="16" width="92" height="40" rx="6" fill="#1D1A2F" stroke="#FFFDF6" stroke-width="2"/><text x="60" y="43" text-anchor="middle" font-family="JetBrains Mono,monospace" font-weight="700" font-size="17" fill="#FFD23F">12:04:59</text><text x="102" y="14" font-size="14">🎄</text>',
run(root,c){let custom=S.get('cd_custom',[]);const yr=el('div',{class:'card',style:'width:100%'});const grid=el('div',{class:'igrid'});
  const nm=el('input',{class:'typein',placeholder:'Event name (e.g. Summer camp)',style:'max-width:260px'}),dt=el('input',{type:'date',class:'typein',style:'max-width:200px'}),add=el('button',{class:'btn primary',type:'button'},'Add countdown');
  root.append(yr,el('div',{class:'bdform'},nm,dt,add),grid);add.addEventListener('click',()=>{if(!nm.value.trim()||!dt.value){(nm.value.trim()?dt:nm).focus();return}custom.push({n:nm.value.trim().slice(0,40),d:dt.value});S.set('cd_custom',custom);nm.value='';dt.value='';build()});
  let items=[];function nextOf(fn){const now=new Date();const t0=new Date(now.getFullYear(),now.getMonth(),now.getDate());let d=fn(now.getFullYear());if(d<t0)d=fn(now.getFullYear()+1);return d}
  function build(){grid.innerHTML='';items=HOLI.map(([n,e,fn])=>({n,e,d:nextOf(fn)}));const b=savedBday();if(b)items.push({n:'Your birthday',e:'🎂',d:nextOf(y=>new Date(y,b.getMonth(),b.getDate())),me:1});
    custom.forEach((q,i)=>{const d=new Date(q.d+'T00:00:00');if(isNaN(d))return;items.push({n:q.n,e:'⭐',d,ci:i})});items.sort((a,b2)=>a.d-b2.d);
    items.forEach(q=>{q.big=el('div',{class:'ibig mono'});q.sub=el('p');const kids=[q.big,el('p',null,q.d.toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'})),q.sub];if(q.ci!=null){const x=el('button',{class:'btn',type:'button',style:'font-size:12px;padding:3px 8px'},'Remove');x.addEventListener('click',()=>{custom.splice(q.ci,1);S.set('cd_custom',custom);build()});kids.push(x)}grid.append(infoCard(q.e+' '+q.n,kids,q.me?'#FF8FB1':q.ci!=null?'#B9A7FF':null))});if(!b)grid.append(infoCard('🎂 Your birthday',[el('p',null,'Enter your birthday in Birthday Time Machine or Planet Age and it will show up here too.')]));tick()}
  function tick(){const now=new Date();const y0=new Date(now.getFullYear(),0,1),y1=new Date(now.getFullYear()+1,0,1);const pc=(now-y0)/(y1-y0)*100;const doy=Math.floor((now-y0)/864e5)+1;
    yr.innerHTML='<b>'+now.getFullYear()+' is '+pc.toFixed(3)+'% over.</b> Today is day '+doy+' of '+Math.round((y1-y0)/864e5)+'.<div style="height:14px;border:3px solid #1D1A2F;border-radius:8px;margin-top:6px;overflow:hidden;background:#fff"><div style="height:100%;width:'+pc+'%;background:#FF8FB1"></div></div>';
    items.forEach(q=>{let s=Math.max(0,(q.d-now)/1000);const today=q.d-now<=0&&now-q.d<864e5;const D=Math.floor(s/86400);s-=D*86400;const h=Math.floor(s/3600);s-=h*3600;const m=Math.floor(s/60);s=Math.floor(s-m*60);q.big.textContent=today?'🎉 Today!':D+'d '+pad2(h)+':'+pad2(m)+':'+pad2(s);q.sub.textContent=today?'It’s happening!':D<1?'Less than a day to go!':D===1?'Tomorrow!':fmtN(D*24+h)+' hours · '+Math.ceil(D/7)+' weeks'})}
  let acc=0;c.loop(dt=>{acc+=dt;if(acc>=250){acc=0;tick()}});build();c.stat('Countdowns')}});

/* ---- Moon Phase ---- */
const SYN=29.530588853,MOON0=Date.UTC(2000,0,6,18,14);
function moonAt(d){let age=((d.getTime()-MOON0)/864e5)%SYN;if(age<0)age+=SYN;const f=age/SYN;const ill=(1-Math.cos(f*Math.PI*2))/2;const q=SYN/4,i=age<1||age>SYN-1?0:Math.abs(age-q)<1?2:Math.abs(age-2*q)<1?4:Math.abs(age-3*q)<1?6:age<q?1:age<2*q?3:age<3*q?5:7;const N=[['New moon','🌑'],['Waxing crescent','🌒'],['First quarter','🌓'],['Waxing gibbous','🌔'],['Full moon','🌕'],['Waning gibbous','🌖'],['Last quarter','🌗'],['Waning crescent','🌘']];return{age,f,ill,name:N[i][0],ic:N[i][1]}}
function drawMoon(x,cx,cy,R,f,south){x.save();x.translate(cx,cy);if(south)x.scale(-1,1);x.fillStyle='#2a2640';x.beginPath();x.arc(0,0,R,0,7);x.fill();
  const lit='#FFF3C4',dark='#2a2640';const wax=f<.5,k=Math.cos(f*Math.PI*2),rx=Math.abs(k)*R;x.fillStyle=lit;x.beginPath();x.arc(0,0,R,wax?-Math.PI/2:Math.PI/2,wax?Math.PI/2:Math.PI*1.5);x.closePath();x.fill();const gib=(f>.25&&f<.75);x.fillStyle=gib?lit:dark;x.beginPath();x.ellipse(0,0,Math.max(.01,rx)+(gib?0:.5),R+.5,0,0,Math.PI*2);x.fill();
  x.globalAlpha=.13;x.fillStyle='#1D1A2F';[[-.3,-.25,.22],[.25,.1,.3],[-.1,.45,.16],[.4,-.45,.12],[-.5,.2,.1]].forEach(([a,b,r])=>{x.beginPath();x.arc(a*R,b*R,r*R,0,7);x.fill()});x.globalAlpha=1;x.strokeStyle='#1D1A2F';x.lineWidth=Math.max(1.5,R*.04);x.beginPath();x.arc(0,0,R,0,7);x.stroke();x.restore()}
G.push({id:'info_moon',name:'Moon Phase',kind:'info',wide:true,tint:'#2a2640',blurb:'See the Moon tonight, on your birthday or on any date: its phase, how much is lit, and when the next full moon is.',
art:'<rect width="120" height="72" fill="#1D1A2F"/><circle cx="60" cy="36" r="24" fill="#2a2640" stroke="#FFFDF6" stroke-width="2"/><path d="M60 12a24 24 0 0 1 0 48a12 24 0 0 0 0-48z" fill="#FFF3C4"/><circle cx="18" cy="14" r="1.5" fill="#fff"/><circle cx="100" cy="58" r="1.5" fill="#fff"/><circle cx="104" cy="16" r="1" fill="#fff"/>',
run(root,c){let day=new Date(),south=S.get('moon_south',false);const inp=el('input',{type:'date',class:'typein',style:'max-width:200px',value:day.toISOString().slice(0,10)});const tb=el('button',{class:'btn',type:'button'},'Tonight'),bb=el('button',{class:'btn',type:'button'},'My birthday'),hb=el('button',{class:'btn',type:'button'});
  const cv=el('canvas',{class:'board',width:960,height:360,style:'width:100%;background:#1D1A2F'});const x=cv.getContext('2d');const info=el('div',{class:'igrid'});const strip=el('canvas',{width:960,height:150,style:'width:100%;background:#1D1A2F;border-radius:12px'});const sx=strip.getContext('2d');
  root.append(el('div',{class:'bdform'},inp,tb,bb,hb),cv,info,el('h4',{style:'margin:4px 0'},'This month'),strip);
  const set=d=>{if(isNaN(d))return;day=d;inp.value=d.getFullYear()+'-'+pad2(d.getMonth()+1)+'-'+pad2(d.getDate());render()};c.on(inp,'change',()=>set(new Date(inp.value+'T21:00:00')));tb.addEventListener('click',()=>set(new Date()));bb.addEventListener('click',()=>{const b=savedBday();if(b){b.setHours(21);set(b)}else bb.textContent='Set your birthday in Planet Age first'});
  const hl=()=>hb.textContent=south?'🌏 Southern hemisphere view':'🌍 Northern hemisphere view';hl();hb.addEventListener('click',()=>{south=!south;S.set('moon_south',south);hl();render()});
  const st=Array.from({length:140},()=>[Math.random()*960,Math.random()*360,Math.random()*1.6+.3]);
  function render(){const m=moonAt(day);info.innerHTML='';const nf=((.5-m.f+1)%1)*SYN,nn=((1-m.f)%1)*SYN;const fd=d=>new Date(day.getTime()+d*864e5).toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric',year:'numeric'});
    info.append(infoCard(m.ic+' '+m.name,[el('div',{class:'ibig'},Math.round(m.ill*100)+'% lit'),el('p',null,'The Moon is '+m.age.toFixed(1)+' days into its 29.5-day cycle.')],'#FFF3C4'),infoCard('🌕 Next full moon',[el('div',{class:'ibig'},nf<.6?'Tonight!':'in '+Math.round(nf)+' days'),el('p',null,'Around '+fd(nf)+'.')],'#FFD23F'),infoCard('🌑 Next new moon',[el('div',{class:'ibig'},nn<.6?'Tonight!':'in '+Math.round(nn)+' days'),el('p',null,'Around '+fd(nn)+'. Best nights for stargazing are near a new moon.')],'#8c86a3'),
      infoCard('🤓 Why it changes',[el('p',null,'The Moon doesn’t make light. We see the half lit by the Sun, and as it orbits Earth we see more or less of that lit half. '+(south?'South of the equator the Moon looks flipped, so it fills in from the left.':'In the north it fills in from the right, then empties from the right.'))],'#7FC8F8'));
    sx.clearRect(0,0,960,150);const y=day.getFullYear(),mo=day.getMonth(),dn=new Date(y,mo+1,0).getDate();const w=960/dn;for(let i=1;i<=dn;i++){const d=new Date(y,mo,i,21);const mm=moonAt(d);const cx=(i-.5)*w;drawMoon(sx,cx,58,Math.min(14,w*.42),mm.f,south);sx.fillStyle=i===day.getDate()?'#FFD23F':'#8c86a3';sx.font='700 '+(w<30?11:14)+'px Figtree, sans-serif';sx.textAlign='center';sx.fillText(i,cx,100);if(i===day.getDate()){sx.strokeStyle='#FFD23F';sx.lineWidth=3;sx.strokeRect(cx-w/2+2,30,w-4,82)}}
    sx.fillStyle='#FFFDF6';sx.font='700 16px Figtree, sans-serif';sx.textAlign='left';sx.fillText(MON[mo]+' '+y,10,20);beep(700,.05,'triangle',.03)}
  c.loop((dt,now)=>{const m=moonAt(day);x.fillStyle='#1D1A2F';x.fillRect(0,0,960,360);x.fillStyle='#fff';st.forEach(([a,b,r])=>{x.globalAlpha=.35+.35*Math.sin(now/700+a);x.fillRect(a,b,r,r)});x.globalAlpha=1;const g=x.createRadialGradient(480,180,100,480,180,190);g.addColorStop(0,'rgba(255,243,196,'+(.08+m.ill*.18)+')');g.addColorStop(1,'rgba(255,243,196,0)');x.fillStyle=g;x.fillRect(280,0,400,360);drawMoon(x,480,180,130,m.f,south);
    x.fillStyle='#FFFDF6';x.font='700 22px Figtree, sans-serif';x.textAlign='left';x.fillText(day.toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'}),24,40);x.fillStyle='#FFD23F';x.fillText(m.ic+' '+m.name,24,72)});
  render();c.stat('Moon Phase')}});

/* ---- Space Trip ---- */
const TRIP_D=[['The Moon','🌕',384400],['Venus (closest)','♀️',38.2e6],['Mars (closest)','🔴',54.6e6],['The Sun','☀️',149.6e6],['Jupiter (closest)','🪐',588e6],['Saturn (closest)','💍',1.2e9],['Neptune (closest)','🔵',4.3e9],['Pluto (closest)','🥶',4.28e9],['Voyager 1 (right now, about)','🛰️',25.4e9],['Alpha Centauri (nearest star system)','⭐',4.13e13],['Center of the Milky Way','🌌',2.46e17],['Andromeda Galaxy','🌀',2.4e19]];
const TRIP_V=[['Walking','🚶',5],['Bicycle','🚲',20],['Car on the highway','🚗',110],['Bullet train','🚄',320],['Jet airliner','✈️',900],['Fastest jet ever','🛩️',3540],['Apollo spacecraft','🚀',39900],['Parker Solar Probe (fastest spacecraft)','☀️',692000],['Speed of light','💡',1079252849]];
G.push({id:'info_trip',name:'Space Trip',kind:'info',wide:true,tint:'#B9A7FF',blurb:'How long would it take to walk to the Moon? Drive to the Sun? Fly a jet to Pluto? Pick a ride and a destination.',
art:'<rect width="120" height="72" fill="#1D1A2F"/><circle cx="18" cy="54" r="12" fill="#2d6fd6" stroke="#fff" stroke-width="2"/><circle cx="102" cy="18" r="9" fill="#F2352A" stroke="#fff" stroke-width="2"/><path d="M30 48Q60 20 92 22" stroke="#FFD23F" stroke-width="2" stroke-dasharray="4 4" fill="none"/><text x="52" y="38" font-size="16">🚀</text>',
run(root,c){let di=S.get('trip_d',0),vi=S.get('trip_v',2);const out=el('div',{class:'igrid'});const cv=el('canvas',{class:'board',width:960,height:200,style:'width:100%;background:#1D1A2F'});const x=cv.getContext('2d');
  const dr=chipRow(TRIP_D.map(d=>d[1]+' '+d[0]),()=>di,i=>{di=i;S.set('trip_d',i);calc()}),vr=chipRow(TRIP_V.map(v=>v[1]+' '+v[0]),()=>vi,i=>{vi=i;S.set('trip_v',i);calc()});
  root.append(el('h4',{style:'margin:0'},'Where to?'),dr,el('h4',{style:'margin:6px 0 0'},'How are you getting there?'),vr,cv,out);let t0=0,prog=0;
  function calc(){const[dn,de,km]=TRIP_D[di],[vn,ve,kmh]=TRIP_V[vi];const h=km/kmh;out.innerHTML='';t0=performance.now();prog=0;const yrs=h/24/365.25;const b=savedBday();const age=b?(Date.now()-b)/(365.25*864e5):null;
    const lines=[el('div',{class:'ibig'},fmtDur(h)),el('p',null,fmtN(km>=1e9?km/1e9:km>=1e6?km/1e6:km,km>=1e6?1:0)+(km>=1e9?' billion':km>=1e6?' million':'')+' km at '+fmtN(kmh)+' km/h.')];
    if(yrs<1e7)lines.push(el('p',null,'Leave today and you’d arrive around '+(yrs<3?new Date(Date.now()+h*36e5).toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'}):'the year '+fmtN(new Date().getFullYear()+yrs))+'.'));
    out.append(infoCard(ve+' → '+de+' '+dn,lines,'#B9A7FF'));
    const extra=[];if(age!=null&&yrs>.05)extra.push(yrs+age<110?'You’d be '+Math.round(age+yrs)+' when you get there.':'That’s '+fmtN(yrs/80,yrs/80<10?1:0)+' lifetimes. Pack a lot of snacks.');extra.push('Snacks needed (3 meals a day): '+(h/8<1e15?fmtN(Math.max(1,h/8)):'more than all the food ever made')+'.');if(kmh<1000&&yrs>1)extra.push('Walking or driving to space isn’t possible, of course, but it shows just how far away it is.');if(vi===8)extra.push(h<1?'Light makes this trip before you can say “Are we there yet?”':'Even light, the fastest thing there is, takes '+fmtDur(h)+'. When you look at it, you see it as it was that long ago.');
    out.append(infoCard('🤔 To put that in perspective',extra.map(t=>el('p',null,t)),'#FFD23F'));beep(500+vi*60,.08,'triangle',.04)}
  c.loop((dt,now)=>{prog=Math.min(1,(now-t0)/2600);const e=1-Math.pow(1-prog,3);x.fillStyle='#1D1A2F';x.fillRect(0,0,960,200);for(let i=0;i<60;i++){x.fillStyle='rgba(255,255,255,'+(.3+.3*Math.sin(i*7.1+now/800))+')';x.fillRect((i*157.3)%960,(i*71.7)%200,1.5,1.5)}
    const a=80,b2=880;x.strokeStyle='rgba(255,210,63,.5)';x.setLineDash([8,8]);x.lineWidth=2;x.beginPath();x.moveTo(a,100);x.lineTo(b2,100);x.stroke();x.setLineDash([]);x.font='56px sans-serif';x.textAlign='center';x.textBaseline='middle';x.fillText('🌍',a,100);x.fillText(TRIP_D[di][1],b2,100);x.font='40px sans-serif';x.save();x.translate(a+(b2-a)*e,100+Math.sin(now/200)*4);x.fillText(TRIP_V[vi][1],0,-38);x.restore();
    x.fillStyle='#FFFDF6';x.font='700 16px Figtree, sans-serif';x.textAlign='left';x.textBaseline='alphabetic';x.fillText(prog<1?'Travelling… (sped up a little)':'Arrived after '+fmtDur(TRIP_D[di][2]/TRIP_V[vi][2]),16,188)});
  calc();c.stat('Space Trip')}});

/* ---- Animal Race ---- */
const RACERS=[['Peregrine falcon (diving)','🦅',389],['Cheetah','🐆',112],['Pronghorn','🦌',88],['Lion','🦁',80],['Greyhound','🐕',72],['Kangaroo','🦘',71],['Ostrich','🐦',70],['Racehorse','🐎',70],['Grizzly bear','🐻',56],['House cat','🐈',48],['Usain Bolt (top speed)','🏃',44.7],['Elephant','🐘',40],['Dolphin','🐬',35],['T. rex (estimated)','🦖',27],['Squirrel','🐿️',20],['Chicken','🐔',14],['You, jogging','🧍',10],['Tortoise','🐢',.3],['Sloth','🦥',.27],['Garden snail','🐌',.05]];
G.push({id:'info_race',name:'Animal Race',kind:'info',wide:true,tint:'#6EE7B7',blurb:'Race a cheetah against a racehorse, a T. rex, Usain Bolt and a snail. Real top speeds, real finishing times.',
art:'<rect width="120" height="72" fill="#6EE7B7"/><path d="M0 24h120M0 48h120" stroke="#1D1A2F" stroke-width="2" stroke-dasharray="6 4"/><rect x="106" y="0" width="6" height="72" fill="#1D1A2F"/><text x="66" y="20" font-size="16">🐆</text><text x="40" y="44" font-size="16">🐎</text><text x="8" y="68" font-size="16">🐌</text>',
run(root,c){let pick2=S.get('race_pick',[1,7,10,13,19]),dist=S.get('race_d',1);const DI=[['100 m',100],['1 km',1000],['Marathon (42.2 km)',42195]];
  const rr=chipRow(RACERS.map(r=>r[1]+' '+r[0]),()=>pick2,i=>{const k=pick2.indexOf(i);if(k>=0){if(pick2.length>2)pick2.splice(k,1)}else{if(pick2.length>=6)pick2.shift();pick2.push(i)}S.set('race_pick',pick2);reset()},true);const dr=chipRow(DI.map(d=>d[0]),()=>dist,i=>{dist=i;S.set('race_d',i);reset()});
  const go=el('button',{class:'btn primary',type:'button',style:'font-size:20px;padding:10px 28px'},'🏁 Race!');const cv=el('canvas',{class:'board',width:960,height:360,style:'width:100%;background:#6EE7B7'});const x=cv.getContext('2d');const res=el('div',{class:'igrid'});
  root.append(el('h4',{style:'margin:0'},'Pick 2 to 6 racers'),rr,dr,go,cv,res);let t=-1,T=4,fin=[];
  function reset(){t=-1;fin=[];res.innerHTML=''}go.addEventListener('click',()=>{t=0;fin=[];res.innerHTML='';beep(440,.15,'square',.05);setTimeout(()=>beep(440,.15,'square',.05),300);setTimeout(()=>beep(880,.3,'square',.06),600)});
  c.loop((dt,now)=>{const L=pick2.map(i=>RACERS[i]);const D=DI[dist][1];const times=L.map(r=>D/(r[2]/3.6));const tf=Math.min(...times);const sc=T/tf;if(t>=0)t+=dt/1000;const rt=t<.9?0:(t-.9)/sc;
    x.fillStyle='#6EE7B7';x.fillRect(0,0,960,360);const lh=320/L.length;x.fillStyle='#1D1A2F';x.fillRect(880,20,8,320);for(let k=0;k<8;k++){x.fillStyle=k%2?'#fff':'#1D1A2F';x.fillRect(888,20+k*40,8,40)}
    L.forEach((r,i)=>{const y=20+i*lh;x.strokeStyle='rgba(29,26,47,.35)';x.setLineDash([10,8]);x.beginPath();x.moveTo(0,y+lh);x.lineTo(960,y+lh);x.stroke();x.setLineDash([]);const f=Math.min(1,rt/times[i]);const px=60+820*f;
      x.font=Math.min(44,lh*.7)+'px sans-serif';x.textAlign='center';x.textBaseline='middle';x.save();x.translate(px,y+lh/2+(f<1&&t>.9?Math.sin(now/60+i)*3:0));x.scale(-1,1);x.fillText(r[1],0,0);x.restore();x.fillStyle='#1D1A2F';x.font='700 13px Figtree, sans-serif';x.textAlign='left';x.fillText(r[0],6,y+12);
      if(f>=1&&!fin.includes(i)&&t>=0){fin.push(i);beep(500+fin.length*120,.1,'triangle',.05);if(fin.length===L.length)showRes(L,times)}});
    x.fillStyle='#1D1A2F';x.font='700 18px Figtree, sans-serif';x.textAlign='left';x.textBaseline='alphabetic';x.fillText(t<0?'Press Race!':t<.9?'Ready… set…':'Race time: '+fmtDur(rt/3600)+' (sped up)',10,356)});
  function showRes(L,times){res.innerHTML='';L.map((r,i)=>[r,times[i]]).sort((a,b)=>a[1]-b[1]).forEach(([r,tm],k)=>res.append(infoCard(['🥇','🥈','🥉','4th','5th','6th'][k]+' '+r[1]+' '+r[0],[el('div',{class:'ibig mono'},fmtDur(tm/3600)),el('p',null,'Top speed about '+fmtN(r[2],r[2]<1?2:0)+' km/h ('+fmtN(r[2]*.621,r[2]<1?2:0)+' mph).'+(tm>tf0(times)*3?' Finishes '+fmtDur((tm-tf0(times))/3600)+' after the winner.':''))],k===0?'#FFD23F':null)))}
  const tf0=a=>Math.min(...a);c.stat('Animal Race')}});

/* ---- Earth Right Now ---- */
const NOWS=[['👶','babies born',4.3,'about 4.3 every second'],['📈','more people on Earth',2.3,'births minus deaths'],['⚡','lightning strikes',44,'about 44 a second worldwide'],['🔎','Google searches',99000,'about 8.5 billion a day'],['📧','emails sent',4000000,'about 350 billion a day, lots of them spam'],['▶️','hours of video uploaded to YouTube',8.3,'about 500 hours every minute'],['🍕','slices of pizza eaten in the US',350,'a famous estimate'],['☕','cups of coffee drunk',26000,'about 2.25 billion a day'],['🧴','plastic bottles bought',16700,'about a million a minute'],['🌳','trees cut down',480,'about 15 billion a year'],['☄️','kg of space dust falling on Earth',.56,'about 48 tonnes a day'],['🌍','km Earth travelled around the Sun',29.78,'about 30 km every second'],['🌀','km the Sun travelled around the galaxy',230,'about 230 km every second'],['🌐','km the equator spun',.4651,'Earth spins at about 1,670 km/h at the equator']];
G.push({id:'info_now',name:'Earth Right Now',kind:'info',wide:true,tint:'#2BB673',blurb:'Watch the world happen live: babies born, lightning strikes, Google searches, pizza slices and how far Earth has flown through space since you got here.',
art:'<rect width="120" height="72" fill="#2BB673"/><circle cx="36" cy="36" r="22" fill="#2d6fd6" stroke="#1D1A2F" stroke-width="2.5"/><path d="M24 26q8-6 14 2t12 0M22 44q10 4 16-4" stroke="#6EE7B7" stroke-width="5" fill="none" stroke-linecap="round"/><text x="66" y="32" font-family="JetBrains Mono,monospace" font-weight="700" font-size="12" fill="#FFFDF6">+4,213</text><text x="66" y="50" font-family="JetBrains Mono,monospace" font-weight="700" font-size="12" fill="#FFD23F">⚡ 44/s</text>',
run(root,c){let mode=0;const t0=Date.now();const grid=el('div',{class:'igrid'});const mr=chipRow(['Since you opened this page','Today so far'],()=>mode,i=>{mode=i});const note=el('p',{class:'hint'},'All numbers are estimates based on yearly averages, so treat them as “roughly this many”.');
  root.append(mr,grid,note);const cells=NOWS.map(([e,n,r,why])=>{const b=el('div',{class:'ibig mono'});grid.append(infoCard(e+' '+n,[b,el('p',null,why+'.')]));return{b,r}});
  c.loop(()=>{const now=Date.now();const md=new Date();md.setHours(0,0,0,0);const s=(mode?now-md.getTime():now-t0)/1000;cells.forEach(q=>{const v=q.r*s;q.b.textContent=fmtN(v,q.r<1||v<100&&q.r<50?1:0)})});c.stat('Earth Right Now')}});

/* ---- Pet Years ---- */
const PETS=[['Small dog','🐩',4,'under 10 kg, like a chihuahua or pug'],['Medium dog','🐕',5,'10 to 25 kg, like a beagle or collie'],['Large dog','🦮',6,'25 to 45 kg, like a labrador'],['Giant dog','🐕‍🦺',7,'over 45 kg, like a Great Dane'],['Cat','🐈',4,'indoor or outdoor']];
function petAge(k,a){const per=PETS[k][2];if(a<=0)return 0;if(a<1)return 15*Math.sqrt(a);if(a<2)return 15+9*(a-1);return 24+per*(a-2)}
function lifeStage(h){return h<3?'a baby':h<12?'a kid':h<20?'a teenager':h<35?'a young adult':h<55?'a grown-up':h<70?'a wise older adult':'a proper senior citizen'}
G.push({id:'info_pets',name:'Pet Years',kind:'info',wide:true,tint:'#FF9F43',blurb:'How old is your dog or cat in human years? (Hint: it isn’t just times seven.) Plus your own age in dog years.',
art:'<rect width="120" height="72" fill="#FF9F43"/><text x="14" y="50" font-size="34">🐕</text><text x="60" y="30" font-family="Arial Black" font-size="14" fill="#1D1A2F">3 yrs</text><text x="60" y="54" font-family="Arial Black" font-size="14" fill="#FFFDF6">= 28</text>',
run(root,c){let k=S.get('pet_k',1),age=S.get('pet_a',3);const ai=el('input',{type:'range',min:.25,max:20,step:.25,value:age,style:'width:100%','aria-label':'Pet age'});const al=el('b');const out=el('div',{class:'igrid'});const cv=el('canvas',{class:'board',width:960,height:260,style:'width:100%;background:#FFFDF6'});const x=cv.getContext('2d');
  const pr=chipRow(PETS.map(p=>p[1]+' '+p[0]),()=>k,i=>{k=i;S.set('pet_k',i);render()});root.append(pr,el('div',{class:'card',style:'width:100%'},el('div',{class:'row',style:'justify-content:space-between'},el('span',null,'Your pet’s age'),al),ai),out,cv);c.on(ai,'input',()=>{age=+ai.value;S.set('pet_a',age);render()});
  function render(){const h=petAge(k,age);al.textContent=(age<1?Math.round(age*12)+' months':fmtN(age,age%1?2:0).replace(/\.?0+$/,'')+' years');out.innerHTML='';const p=PETS[k];
    const lines=[el('div',{class:'ibig'},'≈ '+Math.round(h)+' human years'),el('p',null,'That’s like '+lifeStage(h)+'. ('+p[3]+'.)')];if(k<4)lines.push(el('p',null,'A newer DNA-based formula from UC San Diego gives about '+Math.max(0,Math.round(16*Math.log(Math.max(age,.1))+31))+' years.'));
    out.append(infoCard(p[1]+' '+p[0],lines,'#FF9F43'),infoCard('🤓 Why not just ×7?',[el('p',null,'Pets grow up super fast: a one-year-old dog is already like a 15-year-old teenager. After that they age more slowly, and bigger dogs age faster than small ones.')],'#7FC8F8'));
    const b=savedBday();if(b){const my=(Date.now()-b)/(365.25*864e5);let lo=0,hi=40;for(let i=0;i<40;i++){const m=(lo+hi)/2;if(petAge(k,m)<my)lo=m;else hi=m}out.append(infoCard('🧍 You in '+(k<4?'dog':'cat')+' years',[el('div',{class:'ibig'},fmtN(lo,1)+' years old'),el('p',null,'You’re '+Math.floor(my)+' human years old. Using the old “×7” rule you’d be '+fmtN(my/7,1)+'.')],'#FF8FB1'))}
    x.fillStyle='#FFFDF6';x.fillRect(0,0,960,260);x.strokeStyle='#1D1A2F';x.lineWidth=2;x.beginPath();x.moveTo(60,220);x.lineTo(930,220);x.moveTo(60,220);x.lineTo(60,20);x.stroke();x.fillStyle='#1D1A2F';x.font='700 13px Figtree, sans-serif';x.textAlign='center';for(let a=0;a<=20;a+=2)x.fillText(a,60+a/20*870,238);x.fillText('pet years',495,256);x.textAlign='right';for(let v=0;v<=140;v+=20){x.fillText(v,54,224-v/140*200)}
    PETS.forEach((q,i)=>{x.strokeStyle=i===k?'#F2352A':'rgba(29,26,47,.2)';x.lineWidth=i===k?4:2;x.beginPath();for(let a=0;a<=20;a+=.1){const px=60+a/20*870,py=220-Math.min(150,petAge(i,a))/140*200;a?x.lineTo(px,py):x.moveTo(px,py)}x.stroke()});x.setLineDash([6,6]);x.strokeStyle='#2d6fd6';x.lineWidth=2;x.beginPath();x.moveTo(60,220);x.lineTo(930,220-140/140*200*(20*7/140));x.stroke();x.setLineDash([]);x.fillStyle='#2d6fd6';x.textAlign='left';x.fillText('the old “×7” rule',640,70);
    const px=60+age/20*870,py=220-Math.min(150,h)/140*200;x.fillStyle='#F2352A';x.beginPath();x.arc(px,py,8,0,7);x.fill();x.font='28px sans-serif';x.textAlign='center';x.fillText(p[1],px,py-16)}
  render();c.stat('Pet Years')}});

/* ---- Price Time Machine ---- */
const PRICE_Y=[1940,1950,1960,1970,1980,1990,2000,2010,2020,2025];
const PRICES=[['🎬','Movie ticket',[.24,.46,.69,1.55,2.69,4.23,5.39,7.89,9.16,11.3]],['⛽','Gallon of gas',[.18,.27,.31,.36,1.19,1.16,1.51,2.79,2.17,3.15]],['🍞','Loaf of bread',[.08,.14,.2,.25,.5,.7,.91,1.37,1.5,1.9]],['🥚','Dozen eggs',[.33,.6,.57,.61,.84,1,.96,1.79,1.48,3.8]],['🍫','Candy bar',[.05,.05,.05,.1,.25,.45,.55,.85,1.19,1.9]],['✉️','Postage stamp',[.03,.03,.04,.06,.15,.25,.33,.44,.55,.78]],['💵','Minimum wage (per hour)',[.3,.75,1,1.6,3.1,3.8,5.15,7.25,7.25,7.25]],['🚗','New car',[850,1510,2600,3450,7200,16000,24750,29217,38000,49000]]];
const CPI=[14,24.1,29.6,38.8,82.4,130.7,172.2,218.1,258.8,321.5];
function yInterp(arr,y,geo){y=clamp(y,PRICE_Y[0],PRICE_Y[PRICE_Y.length-1]);let i=0;while(i<PRICE_Y.length-2&&y>PRICE_Y[i+1])i++;const t=(y-PRICE_Y[i])/(PRICE_Y[i+1]-PRICE_Y[i]);return geo?arr[i]*Math.pow(arr[i+1]/arr[i],t):arr[i]+(arr[i+1]-arr[i])*t}
const money2=v=>v<1?Math.round(v*100)+'¢':'$'+fmtN(v,v<100?2:0);
G.push({id:'info_prices',name:'Price Time Machine',kind:'info',wide:true,tint:'#FFD23F',blurb:'What did a movie ticket, a candy bar or a gallon of gas cost the year you (or your grandparents) were born? Slide through 85 years of prices.',
art:'<rect width="120" height="72" fill="#FFD23F"/><rect x="12" y="14" width="96" height="44" rx="6" fill="#FFFDF6" stroke="#1D1A2F" stroke-width="2.5"/><text x="60" y="34" text-anchor="middle" font-family="Arial Black" font-size="12" fill="#1D1A2F">1960 🎬 69¢</text><text x="60" y="51" text-anchor="middle" font-family="Arial Black" font-size="12" fill="#F2352A">2025 $11.30</text>',
run(root,c){const b=savedBday();let yr=S.get('price_y',b?clamp(b.getFullYear(),1940,2025):1980);const sl=el('input',{type:'range',min:1940,max:2025,step:1,value:yr,style:'width:100%','aria-label':'Year'});const yl=el('div',{class:'ibig',style:'text-align:center'});const grid=el('div',{class:'igrid'});const infl=el('div',{class:'card',style:'width:100%;text-align:center'});
  const qb=el('div',{class:'row',style:'flex-wrap:wrap;gap:6px;justify-content:center'});[['My birth year',b?b.getFullYear():null],['1950s',1955],['1970s',1975],['1990s',1995],['2000s',2005]].forEach(([n,y])=>{if(!y)return;const bt=el('button',{class:'btn',type:'button',style:'font-size:14px;padding:6px 11px'},n);bt.addEventListener('click',()=>{sl.value=clamp(y,1940,2025);set()});qb.append(bt)});
  root.append(yl,sl,qb,infl,grid,el('p',{class:'hint'},'Approximate US averages. Years between the data points are estimated.'));c.on(sl,'input',set);
  function set(){yr=+sl.value;S.set('price_y',yr);yl.textContent='It’s '+yr;const cpi=yInterp(CPI,yr,true),now=CPI[CPI.length-1];infl.innerHTML='<b>$1 in '+yr+'</b> could buy about as much as <b>'+money2(now/cpi)+'</b> today. That’s inflation: prices creep up a little every year.';grid.innerHTML='';
    PRICES.forEach(([e,n,a])=>{const then=yInterp(a,yr,true),today=a[a.length-1];const adj=then*now/cpi;grid.append(infoCard(e+' '+n,[el('div',{class:'ibig'},money2(then)),el('p',null,'Today: '+money2(today)+' ('+(today/then>=1.95?Math.round(today/then)+'× more':today>then?Math.round((today/then-1)*100)+'% more':'about the same')+').'),el('p',null,n.startsWith('Minimum')?'Adjusted for inflation that’s like '+money2(adj)+' an hour today.':'Adjusted for inflation it would cost '+money2(adj)+' today.')]))})}
  set();c.stat('Price Time Machine')}});
