/* ================= COOL INFO 3 ================= */
/* ---- Secret Codes ---- */
const MORSE={a:'.-',b:'-...',c:'-.-.',d:'-..',e:'.',f:'..-.',g:'--.',h:'....',i:'..',j:'.---',k:'-.-',l:'.-..',m:'--',n:'-.',o:'---',p:'.--.',q:'--.-',r:'.-.',s:'...',t:'-',u:'..-',v:'...-',w:'.--',x:'-..-',y:'-.--',z:'--..',0:'-----',1:'.----',2:'..---',3:'...--',4:'....-',5:'.....',6:'-....',7:'--...',8:'---..',9:'----.','.':'.-.-.-',',':'--..--','?':'..--..','!':'-.-.--'};
const NATO=['Alfa','Bravo','Charlie','Delta','Echo','Foxtrot','Golf','Hotel','India','Juliett','Kilo','Lima','Mike','November','Oscar','Papa','Quebec','Romeo','Sierra','Tango','Uniform','Victor','Whiskey','X-ray','Yankee','Zulu'];
const BRAILLE={a:1,b:3,c:9,d:25,e:17,f:11,g:27,h:19,i:10,j:26,k:5,l:7,m:13,n:29,o:21,p:15,q:31,r:23,s:14,t:30,u:37,v:39,w:58,x:45,y:61,z:53};
G.push({id:'info_codes',name:'Secret Codes',kind:'info',wide:true,tint:'#1D1A2F',blurb:'Type your name or a secret message and see it in Morse code (with sound!), binary, Braille, the pilot alphabet and more.',
art:'<rect width="120" height="72" fill="#1D1A2F"/><text x="60" y="30" text-anchor="middle" font-family="JetBrains Mono,monospace" font-weight="700" font-size="14" fill="#6EE7B7">·− −··· −·−·</text><text x="60" y="52" text-anchor="middle" font-family="JetBrains Mono,monospace" font-size="11" fill="#FFD23F">01001000 01101001</text>',
run(root,c){const inp=el('input',{class:'typein',placeholder:'Type a message…',value:S.get('codes_txt','Hello'),maxlength:'60','aria-label':'Message'});const out=el('div',{class:'igrid'});const lamp=el('div',{style:'width:34px;height:34px;border-radius:50%;background:#3a3552;border:3px solid #1D1A2F;flex:none'});const play=el('button',{class:'btn primary',type:'button'},'▶ Play Morse');
  const dec=el('input',{class:'typein',placeholder:'Decode Morse: e.g. .... ..  (space between letters, / between words)','aria-label':'Morse to decode'});const decOut=el('div',{class:'ibig mono',style:'min-height:1.2em'});
  root.append(inp,el('div',{class:'row',style:'align-items:center'},play,lamp),out,el('h4',{style:'margin:8px 0 0'},'🕵️ Decoder'),dec,decOut);
  const R=()=>{const t=inp.value;S.set('codes_txt',t);const lo=t.toLowerCase();out.innerHTML='';
    const morse=[...lo].map(ch=>ch===' '?'/':MORSE[ch]||'').filter(Boolean).join(' ');const bin=[...t].map(ch=>ch.charCodeAt(0).toString(2).padStart(8,'0')).join(' ');const nato=[...lo].filter(ch=>/[a-z]/.test(ch)).map(ch=>NATO[ch.charCodeAt(0)-97]).join(' · ');
    const br=[...lo].map(ch=>ch===' '?' ':BRAILLE[ch]?String.fromCharCode(0x2800+BRAILLE[ch]):ch).join('');const rot=t.replace(/[a-z]/gi,ch=>{const b=ch<='Z'?65:97;return String.fromCharCode((ch.charCodeAt(0)-b+13)%26+b)});const hex=[...t].map(ch=>ch.charCodeAt(0).toString(16).toUpperCase().padStart(2,'0')).join(' ');const rev=[...t].reverse().join('');const pig=t.split(/\s+/).map(w=>{const m=w.match(/^([^aeiouAEIOU]*)(.*)$/);return m&&m[2]?m[2]+m[1]+'ay':w+'way'}).join(' ');
    [['📡 Morse code',morse,'Used by telegraphs and ships. SOS is ··· −−− ···.'],['💻 Binary',bin,'How computers store each letter: eight 1s and 0s per character.'],['✈️ Pilot alphabet (NATO)',nato,'Pilots spell words this way so letters can’t be misheard.'],['⠃ Braille',br,'Raised dots that people read with their fingertips.'],['🔄 ROT13 cipher',rot,'Every letter shifted 13 places. Do it twice and you’re back!'],['🔢 Hexadecimal',hex,'Base 16, used for colours and computer memory.'],['🪞 Mirror writing',rev,'Leonardo da Vinci famously wrote notes backwards.'],['🐷 Pig Latin',pig,'Move the first consonants to the end and add “ay”.']].forEach(([h,v,n])=>out.append(infoCard(h,[el('div',{class:'mono',style:'font-size:18px;word-break:break-word;line-height:1.4'},v||'—'),el('p',{style:'opacity:.75;font-size:13px'},n)])))};
  c.on(inp,'input',R);R();
  let playing=false;play.addEventListener('click',()=>{if(playing)return;const lo=inp.value.toLowerCase();const u=.085;let t=0;const seq=[];for(const ch of lo){if(ch===' '){t+=u*4;continue}const m=MORSE[ch];if(!m)continue;for(const s of m){const d=s==='.'?u:u*3;seq.push([t,d]);t+=d+u}t+=u*2}playing=true;play.textContent='📡 Sending…';
    seq.forEach(([st,d])=>{c.after(()=>{lamp.style.background='#FFD23F';lamp.style.boxShadow='0 0 18px #FFD23F';beep(700,d,'sine',.08)},st*1000);c.after(()=>{lamp.style.background='#3a3552';lamp.style.boxShadow=''},(st+d)*1000)});c.after(()=>{playing=false;play.textContent='▶ Play Morse'},t*1000+100)});
  const inv={};Object.keys(MORSE).forEach(k=>inv[MORSE[k]]=k);c.on(dec,'input',()=>{decOut.textContent=dec.value.trim().split(/\s*\/\s*|\s{3,}/).map(w=>w.trim().split(/\s+/).map(code=>inv[code.replace(/[−–]/g,'-').replace(/[·•]/g,'.')]||(code?'?':'')).join('')).join(' ').toUpperCase()});c.stat('Secret Codes')}});

/* ---- Million vs Billion ---- */
G.push({id:'info_big',name:'Million vs Billion',kind:'info',wide:true,tint:'#FFD23F',blurb:'A million seconds is 11 days. A billion seconds is 31 years. Feel how giant numbers really are with seconds, money stacks, steps and more.',
art:'<rect width="120" height="72" fill="#FFD23F"/><rect x="14" y="56" width="16" height="4" fill="#2BB673" stroke="#1D1A2F" stroke-width="1.5"/><rect x="44" y="40" width="16" height="20" fill="#2BB673" stroke="#1D1A2F" stroke-width="1.5"/><rect x="74" y="8" width="16" height="52" fill="#2BB673" stroke="#1D1A2F" stroke-width="1.5"/><text x="22" y="52" text-anchor="middle" font-family="Arial Black" font-size="8">1M</text><text x="52" y="36" text-anchor="middle" font-family="Arial Black" font-size="8">1B</text><text x="100" y="20" font-family="Arial Black" font-size="8">1T</text>',
run(root,c){const NUMS=[['Thousand',1e3],['Million',1e6],['Billion',1e9],['Trillion',1e12]];let a=S.get('big_a',1),b=S.get('big_b',2);const ra=chipRow(NUMS.map(n=>n[0]),()=>a,i=>{a=i;S.set('big_a',i);R()}),rb=chipRow(NUMS.map(n=>n[0]),()=>b,i=>{b=i;S.set('big_b',i);R()});
  const cv=el('canvas',{class:'board',width:960,height:220,style:'width:100%;background:#FFFDF6'});const x=cv.getContext('2d');const out=el('div',{class:'igrid'});root.append(el('h4',{style:'margin:0'},'Compare…'),ra,el('h4',{style:'margin:4px 0 0'},'…with'),rb,cv,out);
  const dur=s=>{const y=s/31557600;if(y>=1)return(y>=1000?Math.round(y).toLocaleString('en-US'):y.toFixed(y<10?1:0))+' years';const d=s/86400;if(d>=1)return d.toFixed(d<10?1:0)+' days';const h=s/3600;if(h>=1)return h.toFixed(1)+' hours';return (s/60).toFixed(1)+' minutes'};
  const len=m=>m>=1000?(m/1000).toLocaleString('en-US',{maximumFractionDigits:m<1e4?1:0})+' km':m>=1?m.toFixed(m<10?1:0)+' m':(m*100).toFixed(1)+' cm';
  const FACTS=[['⏱️','seconds would take',n=>dur(n)],['💵','$100 bills stacked up would be',n=>len(n/100*.00011)+' tall'],['🚶','steps would walk you',n=>len(n*.75)],['🍚','grains of rice would weigh',n=>{const kg=n*.00002;return kg>=1000?(kg/1000).toLocaleString('en-US',{maximumFractionDigits:0})+' tonnes':kg>=1?kg.toFixed(1)+' kg':(kg*1000).toFixed(1)+' g'}],['📄','sheets of paper would stack',n=>len(n*.0001)+' high'],['❤️','heartbeats is about',n=>dur(n/80*60)+' of your life'],['🧱','LEGO bricks lined up would stretch',n=>len(n*.032)]];
  let t0=0;function R(){t0=performance.now();out.innerHTML='';[a,b].forEach((i,k)=>{const[nm,n]=NUMS[i];out.append(infoCard('One '+nm.toLowerCase()+' ('+n.toLocaleString('en-US')+')',FACTS.map(([e,t,f])=>el('p',null,e+' A '+nm.toLowerCase()+' '+t+' ',el('b',null,f(n)))),k?'#FF8FB1':'#2BB673'))});const big=Math.max(NUMS[a][1],NUMS[b][1]),small=Math.min(NUMS[a][1],NUMS[b][1]);out.append(infoCard('🤯 The difference',[el('div',{class:'ibig'},'×'+(big/small).toLocaleString('en-US')),el('p',null,'A '+NUMS[Math.max(a,b)][0].toLowerCase()+' is '+(big/small).toLocaleString('en-US')+' times bigger. If a '+NUMS[Math.min(a,b)][0].toLowerCase()+' seconds is '+dur(small)+', a '+NUMS[Math.max(a,b)][0].toLowerCase()+' seconds is '+dur(big)+'.')],'#FFD23F'));beep(500+a*100,.08,'triangle',.04)}
  c.loop((dt,now)=>{const p=Math.min(1,(now-t0)/1500),e=1-Math.pow(1-p,3);x.fillStyle='#FFFDF6';x.fillRect(0,0,960,220);const va=NUMS[a][1],vb=NUMS[b][1],mx=Math.max(va,vb);[[va,a,'#2BB673',40],[vb,b,'#FF8FB1',120]].forEach(([v,i,col,y])=>{const w=Math.max(2,900*(v/mx)*e);x.fillStyle=col;x.fillRect(30,y,w,56);x.strokeStyle='#1D1A2F';x.lineWidth=3;x.strokeRect(30,y,w,56);x.fillStyle='#1D1A2F';x.font='800 20px Figtree, sans-serif';x.textAlign='left';x.fillText(NUMS[i][0]+(w<200?'  (tiny sliver!)':''),w<200?40+w:42,y+36)});x.font='600 13px Figtree, sans-serif';x.fillText('Bars drawn to scale',30,212)});
  R();c.stat('Million vs Billion')}});

/* ---- How Old Is It? ---- */
const OLDIES=[['☀️','The Sun',-4.6e9],['🌍','Planet Earth',-4.54e9],['🦖','Dinosaurs went extinct',-6.6e7],['🧍','First modern humans',-300000],['🪨','Stonehenge',-3000],['🔺','Great Pyramid of Giza',-2560],['🏛️','Colosseum',80],['🧱','Most of today’s Great Wall (Ming)',1400],['🇺🇸','United States of America',1776],['🇨🇦','Canada',1867],['📞','The telephone',1876],['💡','Edison’s light bulb',1879],['🥤','Coca-Cola',1886],['🗽','Statue of Liberty',1886],['🗼','Eiffel Tower',1889],['🏅','Modern Olympic Games',1896],['✈️','First airplane flight',1903],['🚢','Titanic sank',1912],['📺','Electronic television',1927],['⚽','First FIFA World Cup',1930],['🏀','The NBA',1946],['🎢','Disneyland',1955],['🧱','The modern LEGO brick',1958],['🌕','First Moon landing',1969],['🕹️','Pong video game',1972],['🎬','Star Wars (first film)',1977],['🍄','Super Mario Bros.',1985],['🌐','The World Wide Web',1991],['🧸','Toy Story',1995],['⚡','Pokémon',1996],['📚','First Harry Potter book',1997],['🔎','Google',1998],['▶️','YouTube',2005],['📱','The iPhone',2007],['📸','Instagram',2010],['⛏️','Minecraft (full release)',2011],['🎵','TikTok (Douyin)',2016],['🦙','Fortnite',2017],['🤖','ChatGPT',2022]];
G.push({id:'info_old',name:'How Old Is It?',kind:'info',wide:true,tint:'#B9A7FF',blurb:'How old are the pyramids, the iPhone, YouTube and the Moon landing, and what existed when you were born? Plus a which-is-older quiz.',fmt:b=>b+' streak',
art:'<rect width="120" height="72" fill="#B9A7FF"/><path d="M8 50H112" stroke="#1D1A2F" stroke-width="3"/><g font-size="18"><text x="10" y="40">🔺</text><text x="46" y="40">🗼</text><text x="86" y="40">📱</text></g><g fill="#1D1A2F"><circle cx="20" cy="50" r="4"/><circle cx="56" cy="50" r="4"/><circle cx="96" cy="50" r="4"/></g>',
run(root,c){let mode=0;const mr=chipRow(['📜 Timeline','🤔 Which is older?'],()=>mode,i=>{mode=i;R()});const body=el('div',{style:'width:100%'});root.append(mr,body);const NOW=new Date().getFullYear();const b=savedBday();const by=b?b.getFullYear():null;
  const age=y=>{const a=NOW-y;return a>=1e9?(a/1e9).toFixed(2)+' billion years':a>=1e6?(a/1e6).toFixed(0)+' million years':a.toLocaleString('en-US')+' years'};const yr=y=>y<0?(y<=-1e6?age(y)+' ago':(-y).toLocaleString('en-US')+' BC'):'AD '+y;
  let streak=0,lock=false;
  function R(){body.innerHTML='';if(mode===0){const g=el('div',{class:'igrid'});OLDIES.forEach(([e,n,y])=>{const before=by!=null&&y<=by;g.append(infoCard(e+' '+n,[el('div',{class:'ibig',style:'font-size:22px'},age(y)+' old'),el('p',null,y<0?yr(y):'Since '+y+'.'),by!=null&&y>1800?el('p',null,before?'✅ Around when you were born':'🆕 Arrived '+(y-by)+' years after you were born'):''],by!=null&&y>1800?(before?'#6EE7B7':'#FF8FB1'):null))});if(by==null)body.append(el('p',{class:'hint'},'Enter your birthday in Birthday Time Machine to see what existed when you were born.'));body.append(g);return}
    const pair=shuffle(OLDIES.slice()).slice(0,2);if(pair[0][2]===pair[1][2])return R();const q=el('p',{class:'big-text',style:'text-align:center'},'Which is older? (streak '+streak+')');const row=el('div',{class:'choices'});const res=el('p',{class:'hint',style:'font-size:16px;color:var(--ink);font-weight:600'});lock=false;
    pair.forEach(p=>{const bt=el('button',{class:'btn',type:'button',style:'font-size:20px;min-height:90px'},p[0]+' '+p[1]);bt.addEventListener('click',()=>{if(lock)return;lock=true;const ok=p[2]===Math.min(pair[0][2],pair[1][2]);if(ok){streak++;c.best(streak);bt.classList.add('right');beep(880,.12,'triangle')}else{streak=0;bt.classList.add('wrong');beep(150,.25,'sawtooth')}res.textContent=pair.map(q2=>q2[1]+': '+age(q2[2])+' old').join(' · ');c.after(R,2000)});row.append(bt)});body.append(q,row,res)}
  R();c.stat('How Old Is It?')}});
