/* ================= .IO GAMES ================= */
const IO_NAMES=['Blobby','Sir Snacks','Noodle','Mr. Wobble','Jelly','Chonk','Dot','Muffin','Pixel','Bubba','Gloop','Sprinkles','Nugget','Zoomer','Pudding','Waffles','Beans','Captain Crumb','Toast','Mochi','Pickle','Bean Boss','Gumdrop','Squish'];
const IO_COLS=['#F2352A','#FF9F43','#FFD23F','#2BB673','#6EE7B7','#7FC8F8','#2d6fd6','#B9A7FF','#FF8FB1','#c9e89a','#e8c48a','#8c86a3'];
function ioCanvas(root){const W=960,H=600;const cv=el('canvas',{class:'board',width:W,height:H,style:'width:100%;touch-action:none;cursor:crosshair;background:#FFFDF6'});root.append(cv);return{cv,x:cv.getContext('2d'),W,H}}
function ioPointer(c,cv,W,H){const p={x:W/2+100,y:H/2,down:false,moved:false};const set=e=>{const q=canvasPos(cv,e);p.x=q.x;p.y=q.y;p.moved=true};c.on(cv,'pointermove',set);c.on(cv,'pointerdown',e=>{set(e);p.down=true;try{cv.setPointerCapture(e.pointerId)}catch(_){}});c.on(window,'pointerup',()=>{p.down=false});return p}
function ioBoard(x,W,list,title){x.save();x.fillStyle='rgba(29,26,47,.72)';const h=24+list.length*18;x.fillRect(W-190,10,180,h);x.fillStyle='#FFD23F';x.font='800 13px Figtree, sans-serif';x.textAlign='left';x.fillText(title||'Leaderboard',W-180,28);list.forEach(([n,v,me],i)=>{x.fillStyle=me?'#6EE7B7':'#fff';x.font=(me?'800':'600')+' 13px Figtree, sans-serif';x.fillText((i+1)+'. '+n,W-180,46+i*18);x.textAlign='right';x.fillText(v,W-18,46+i*18);x.textAlign='left'});x.restore()}
function ioOver(x,W,H,t1,t2){x.save();x.fillStyle='rgba(29,26,47,.75)';x.fillRect(0,H/2-70,W,140);x.textAlign='center';x.font='42px "Bagel Fat One", sans-serif';x.lineWidth=6;x.strokeStyle='#1D1A2F';x.strokeText(t1,W/2,H/2);x.fillStyle='#FFD23F';x.fillText(t1,W/2,H/2);x.fillStyle='#FFFDF6';x.font='600 18px Figtree, sans-serif';x.fillText(t2,W/2,H/2+38);x.restore()}

/* ---------- Blob Feast (agar-style) ---------- */
G.push({id:'io_blob',name:'Blob Feast',kind:'io',wide:true,tint:'#7FC8F8',blurb:'Eat pellets, eat smaller blobs, avoid bigger ones. Split to pounce. Like agar.io, with bots.',fmt:b=>b+' mass',
art:'<rect width="120" height="72" fill="#FFFDF6"/><g stroke="#e8e1d0"><path d="M0 18h120M0 36h120M0 54h120M20 0v72M40 0v72M60 0v72M80 0v72M100 0v72"/></g><circle cx="48" cy="38" r="20" fill="#2BB673" stroke="#1f8a56" stroke-width="3"/><circle cx="90" cy="24" r="10" fill="#FF8FB1" stroke="#d96b8c" stroke-width="3"/><g fill="#FFD23F"><circle cx="20" cy="14" r="3"/><circle cx="84" cy="56" r="3" fill="#B9A7FF"/><circle cx="104" cy="44" r="3" fill="#FF9F43"/><circle cx="16" cy="60" r="3" fill="#7FC8F8"/></g>',
run(root,c){const{cv,x,W,H}=ioCanvas(root);const ptr=ioPointer(c,cv,W,H);root.append(el('p',{class:'hint'},'Move the mouse (or drag) to steer. Space splits your blob to pounce, W shoots out a bit of mass. Eat things at least 25% smaller than you.'));
  const WS=3000,R=m=>6+Math.sqrt(m)*4;let players=[],pellets=[],viruses=[],me=null,dead=false,deadT=0,killer='',best=0,shake=0;
  const keys={};c.on(document,'keydown',e=>{const k=e.key.toLowerCase();if(k===' '){e.preventDefault();if(!keys[' '])split(me)}if(k==='w'&&!keys.w)eject(me);keys[k]=true});c.on(document,'keyup',e=>{keys[e.key.toLowerCase()]=false});
  let tapT=0;c.on(cv,'pointerdown',()=>{const n=performance.now();if(n-tapT<300)split(me);tapT=n});
  const pel=()=>({x:Math.random()*WS,y:Math.random()*WS,c:pick(IO_COLS),r:4+Math.random()*2});
  for(let i=0;i<900;i++)pellets.push(pel());for(let i=0;i<14;i++)viruses.push({x:200+Math.random()*(WS-400),y:200+Math.random()*(WS-400),m:100});
  function spawn(p,m){let cx,cy,t=0;do{cx=200+Math.random()*(WS-400);cy=200+Math.random()*(WS-400);t++}while(t<50&&players.some(o=>o!==p&&!o.dead&&o.cells.some(q=>Math.hypot(q.x-cx,q.y-cy)<(p.bot?500:700))));p.cells=[{x:cx,y:cy,m:m||10,vx:0,vy:0,merge:0}];p.dead=false;p.maxM=m||10;p.safe=p.bot?0:3}
  function mkPlayer(name,col,bot){const p={name,col,bot,cells:[],dead:false,maxM:10,ai:{t:0,tx:0,ty:0,wander:Math.random()*6}};spawn(p,bot?10+Math.random()*120:10);players.push(p);return p}
  me=mkPlayer('You','#2BB673',false);shuffle(IO_NAMES).slice(0,17).forEach((n,i)=>mkPlayer(n,IO_COLS[i%IO_COLS.length],true));
  const mass=p=>p.cells.reduce((s,q)=>s+q.m,0);
  function split(p){if(!p||p.dead||p.cells.length>=8)return;const add=[];p.cells.forEach(q=>{if(q.m<36||p.cells.length+add.length>=8)return;const tx=p===me?toWorld().x:p.ai.tx,ty=p===me?toWorld().y:p.ai.ty;const a=Math.atan2(ty-q.y,tx-q.x);q.m/=2;q.merge=12;add.push({x:q.x+Math.cos(a)*R(q.m),y:q.y+Math.sin(a)*R(q.m),m:q.m,vx:Math.cos(a)*900,vy:Math.sin(a)*900,merge:12})});p.cells.push(...add);if(p===me&&add.length)sweep(300,900,.15,'triangle',.05)}
  function eject(p){if(!p||p.dead)return;p.cells.forEach(q=>{if(q.m<30)return;const tx=toWorld().x,ty=toWorld().y;const a=Math.atan2(ty-q.y,tx-q.x);q.m-=12;pellets.push({x:q.x+Math.cos(a)*(R(q.m)+14),y:q.y+Math.sin(a)*(R(q.m)+14),c:p.col,r:9,m:10,vx:Math.cos(a)*600,vy:Math.sin(a)*600})});beep(500,.04,'triangle',.03)}
  let cam={x:0,y:0,z:1};const toWorld=()=>({x:cam.x+(ptr.x-W/2)/cam.z,y:cam.y+(ptr.y-H/2)/cam.z});
  function ai(p,dt){const a=p.ai;a.t-=dt;if(a.t>0)return;a.t=.2+Math.random()*.2;const c0=p.cells.reduce((b,q)=>q.m>b.m?q:b,p.cells[0]);const my=c0.m;let fx=0,fy=0,prey=null,pd=1e9;
    players.forEach(o=>{if(o===p||o.dead)return;o.cells.forEach(q=>{const d=Math.hypot(q.x-c0.x,q.y-c0.y);if(q.m>my*1.25&&d<R(q.m)+320){fx-=(q.x-c0.x)/d*(600/d);fy-=(q.y-c0.y)/d*(600/d)}else if(q.m*1.3<my&&d<450&&d<pd){pd=d;prey=q}})});
    if(Math.hypot(fx,fy)>.5){a.tx=c0.x+fx*200;a.ty=c0.y+fy*200}else if(prey){a.tx=prey.x;a.ty=prey.y;if(pd<260&&my>prey.m*2.8&&p.cells.length<3&&Math.random()<.25){split(p)}}else{let bp=null,bd=1e9;for(let k=0;k<40;k++){const q=pellets[rand(pellets.length)];const d=Math.hypot(q.x-c0.x,q.y-c0.y);if(d<bd){bd=d;bp=q}}if(bp){a.tx=bp.x;a.ty=bp.y}}
    a.tx=clamp(a.tx,50,WS-50);a.ty=clamp(a.ty,50,WS-50)}
  function die(p,by){p.dead=true;p.cells=[];if(p===me){dead=true;deadT=0;killer=by?by.name:'something';best=Math.max(best,Math.round(me.maxM));c.best(Math.round(me.maxM));noise(.5,'lowpass',300,.3)}else c.after(()=>{if(!p.dead)return;spawn(p,10+Math.random()*60)},3000)}
  c.on(cv,'pointerup',()=>{if(dead&&deadT>1){spawn(me,10);dead=false}});
  c.loop(dtm=>{const dt=Math.min(.05,dtm/1000);
    players.forEach(p=>{if(p.dead)return;if(p.bot)ai(p,dt);const t=p===me?toWorld():{x:p.ai.tx,y:p.ai.ty};
      p.cells.forEach(q=>{const r=R(q.m);const dx=t.x-q.x,dy=t.y-q.y,d=Math.hypot(dx,dy)||1;const sp=320*Math.pow(q.m,-.22)*Math.min(1,d/(r*.8));q.x+=(dx/d*sp+q.vx)*dt;q.y+=(dy/d*sp+q.vy)*dt;q.vx*=Math.pow(.02,dt);q.vy*=Math.pow(.02,dt);q.x=clamp(q.x,r*.5,WS-r*.5);q.y=clamp(q.y,r*.5,WS-r*.5);q.merge=Math.max(0,q.merge-dt);if(q.m>150)q.m*=1-.002*dt*Math.log10(q.m)});
      for(let i=0;i<p.cells.length;i++)for(let j=i+1;j<p.cells.length;j++){const a=p.cells[i],b=p.cells[j];const dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||.01,ra=R(a.m),rb=R(b.m);if(a.merge>0||b.merge>0){if(d<ra+rb){const k=(ra+rb-d)*.5;a.x-=dx/d*k;a.y-=dy/d*k;b.x+=dx/d*k;b.y+=dy/d*k}}else if(d<Math.max(ra,rb)*.6){a.m+=b.m;b.m=0}}p.cells=p.cells.filter(q=>q.m>0);
      p.cells.forEach(q=>{const r=R(q.m);for(let i=pellets.length-1;i>=0;i--){const pe=pellets[i];if(Math.abs(pe.x-q.x)>r||Math.abs(pe.y-q.y)>r)continue;if(Math.hypot(pe.x-q.x,pe.y-q.y)<r){q.m+=pe.m||1;pellets.splice(i,1);if(!pe.m)pellets.push(pel());if(p===me&&Math.random()<.3)beep(900+Math.random()*600,.02,'sine',.02)}}
        viruses.forEach(v=>{if(q.m>v.m*1.2&&Math.hypot(v.x-q.x,v.y-q.y)<r){v.x=200+Math.random()*(WS-400);v.y=200+Math.random()*(WS-400);const n=Math.min(8-p.cells.length,6);if(n>0){const each=q.m/(n+1);q.m=each;q.merge=14;for(let k=0;k<n;k++){const a=k/n*6.28;p.cells.push({x:q.x,y:q.y,m:each,vx:Math.cos(a)*700,vy:Math.sin(a)*700,merge:14})}if(p===me){shake=10;noise(.3,'lowpass',500,.25)}}}})});
      const m=mass(p);p.maxM=Math.max(p.maxM,m)});
    pellets.forEach(pe=>{if(pe.vx){pe.x+=pe.vx*dt;pe.y+=pe.vy*dt;pe.vx*=Math.pow(.01,dt);pe.vy*=Math.pow(.01,dt);if(Math.abs(pe.vx)<1)pe.vx=0}});
    // eat each other
    const all=[];players.forEach(p=>{if(!p.dead)p.cells.forEach(q=>all.push([q,p]))});all.sort((a,b)=>b[0].m-a[0].m);
    for(let i=0;i<all.length;i++){const[a,pa]=all[i];if(a.m<=0)continue;const ra=R(a.m);for(let j=i+1;j<all.length;j++){const[b,pb]=all[j];if(b.m<=0||pa===pb)continue;if(a.m<b.m*1.25||pb.safe>0)continue;const d=Math.hypot(a.x-b.x,a.y-b.y);if(d<ra-R(b.m)*.35){a.m+=b.m;b.m=0;b.by=pa;if(pa===me){pw_pop(b,'+'+Math.round(b.m||0));beep(300,.08,'square',.05)}}}}
    players.forEach(p=>{if(p.dead)return;p.safe=Math.max(0,(p.safe||0)-dt);let by=null;p.cells.forEach(q=>{if(q.m<=0&&q.by)by=q.by});p.cells=p.cells.filter(q=>q.m>0);if(!p.cells.length)die(p,by)});
    // camera
    if(!me.dead&&me.cells.length){let sx=0,sy=0,sm=0,tr=0;me.cells.forEach(q=>{sx+=q.x*q.m;sy+=q.y*q.m;sm+=q.m;tr+=R(q.m)});cam.x+=(sx/sm-cam.x)*.15;cam.y+=(sy/sm-cam.y)*.15;const tz=clamp(1.6/(1+tr/140),.35,1.3);cam.z+=(tz-cam.z)*.05}else deadT+=dt;
    // draw
    x.save();x.fillStyle='#FFFDF6';x.fillRect(0,0,W,H);if(shake>0){x.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);shake*=.85}x.translate(W/2,H/2);x.scale(cam.z,cam.z);x.translate(-cam.x,-cam.y);
    x.strokeStyle='#ece6d6';x.lineWidth=1/cam.z;const g=50,x0=Math.floor((cam.x-W/2/cam.z)/g)*g,y0=Math.floor((cam.y-H/2/cam.z)/g)*g;x.beginPath();for(let gx=x0;gx<cam.x+W/2/cam.z;gx+=g){x.moveTo(gx,y0);x.lineTo(gx,cam.y+H/2/cam.z)}for(let gy=y0;gy<cam.y+H/2/cam.z;gy+=g){x.moveTo(x0,gy);x.lineTo(cam.x+W/2/cam.z,gy)}x.stroke();x.strokeStyle='#F2352A';x.lineWidth=6;x.strokeRect(0,0,WS,WS);
    const vis=(px,py,r)=>Math.abs(px-cam.x)<W/2/cam.z+r&&Math.abs(py-cam.y)<H/2/cam.z+r;
    pellets.forEach(pe=>{if(!vis(pe.x,pe.y,10))return;x.fillStyle=pe.c;x.beginPath();x.arc(pe.x,pe.y,pe.r,0,7);x.fill()});
    const cells=all.filter(([q])=>q.m>0).sort((a,b)=>a[0].m-b[0].m);
    const drawV=v=>{if(!vis(v.x,v.y,80))return;x.fillStyle='#2BB673';x.strokeStyle='#1f8a56';x.lineWidth=4;x.beginPath();const r=R(v.m);for(let k=0;k<=40;k++){const a=k/40*6.283,rr=r+(k%2?6:-2);k?x.lineTo(v.x+Math.cos(a)*rr,v.y+Math.sin(a)*rr):x.moveTo(v.x+Math.cos(a)*rr,v.y+Math.sin(a)*rr)}x.fill();x.stroke()};
    cells.forEach(([q,p])=>{if(q.m<100)return;});viruses.forEach(v=>{if(!cells.some(([q])=>q.m>v.m*1.2))drawV(v)});
    cells.forEach(([q,p])=>{const r=R(q.m);if(!vis(q.x,q.y,r))return;if(p.safe>0&&Math.sin(performance.now()/90)>0)x.globalAlpha=.5;const wob=p===me?1:1;x.fillStyle=p.col;x.strokeStyle='rgba(29,26,47,.35)';x.lineWidth=Math.max(3,r*.08);x.beginPath();for(let k=0;k<=32;k++){const a=k/32*6.283,rr=r*(1+Math.sin(a*5+performance.now()/300+q.m)*.015*wob);k?x.lineTo(q.x+Math.cos(a)*rr,q.y+Math.sin(a)*rr):x.moveTo(q.x+Math.cos(a)*rr,q.y+Math.sin(a)*rr)}x.fill();x.stroke();x.globalAlpha=1;
      if(r>16){x.fillStyle='#fff';x.strokeStyle='#1D1A2F';x.lineWidth=Math.max(2,r*.06);x.font='800 '+Math.max(12,r*.32)+'px Figtree, sans-serif';x.textAlign='center';x.textBaseline='middle';x.strokeText(p.name,q.x,q.y);x.fillText(p.name,q.x,q.y);if(r>30){x.font='700 '+Math.max(10,r*.2)+'px Figtree, sans-serif';x.strokeText(Math.round(q.m),q.x,q.y+r*.36);x.fillText(Math.round(q.m),q.x,q.y+r*.36)}}});
    viruses.forEach(v=>{if(cells.some(([q])=>q.m>v.m*1.2))drawV(v)});
    x.restore();
    const lb=players.filter(p=>!p.dead).map(p=>[p.name,Math.round(mass(p)),p===me]).sort((a,b)=>b[1]-a[1]);const myRank=lb.findIndex(r=>r[2]);ioBoard(x,W,lb.slice(0,8).concat(myRank>=8?[lb[myRank]]:[]),'Leaderboard');
    x.fillStyle='#1D1A2F';x.font='700 16px "JetBrains Mono", monospace';x.textAlign='left';x.fillText('MASS '+Math.round(mass(me))+'   BEST '+Math.round(me.maxM),16,28);
    if(dead)ioOver(x,W,H,'Eaten by '+killer+'!','You reached '+Math.round(me.maxM)+' mass. Click to play again.');c.stat('Blob Feast · mass '+Math.round(mass(me)))});
  function pw_pop(){} }});

/* ---------- Noodle (slither-style) ---------- */
G.push({id:'io_noodle',name:'Noodle',kind:'io',wide:true,tint:'#1D1A2F',blurb:'Slither around, gobble glowing orbs and grow huge. Make other snakes crash into you. Like slither.io, with bots.',fmt:b=>b+' length',
art:'<rect width="120" height="72" fill="#1D1A2F"/><g fill="#6EE7B7" stroke="#1D1A2F" stroke-width="1.5"><circle cx="20" cy="50" r="7"/><circle cx="30" cy="44" r="7"/><circle cx="40" cy="40" r="7"/><circle cx="50" cy="40" r="7"/><circle cx="60" cy="44" r="7"/><circle cx="70" cy="46" r="7"/><circle cx="80" cy="42" r="8"/></g><circle cx="83" cy="39" r="2.5" fill="#fff"/><circle cx="84" cy="39" r="1.2" fill="#1D1A2F"/><g fill="#FFD23F"><circle cx="100" cy="30" r="3"/><circle cx="96" cy="58" r="2.5" fill="#FF8FB1"/><circle cx="16" cy="18" r="2.5" fill="#7FC8F8"/></g>',
run(root,c){const{cv,x,W,H}=ioCanvas(root);cv.style.background='#14102a';const ptr=ioPointer(c,cv,W,H);root.append(el('p',{class:'hint'},'Steer with the mouse (or drag). Hold the mouse button or Space to boost (it costs length). If your head touches another snake, you’re out.'));
  const WR=2200;let snakes=[],orbs=[],me=null,dead=false,deadT=0,killer='';const keys={};c.on(document,'keydown',e=>{if(e.key===' ')e.preventDefault();keys[e.key.toLowerCase()]=true});c.on(document,'keyup',e=>{keys[e.key.toLowerCase()]=false});
  const orb=(px,py,v,col)=>{if(px==null){const a=Math.random()*6.283,r=Math.sqrt(Math.random())*(WR-40);px=Math.cos(a)*r;py=Math.sin(a)*r}return{x:px,y:py,v:v||1+Math.random()*2,c:col||`hsl(${rand(360)} 90% 62%)`,ph:Math.random()*6}};
  for(let i=0;i<1100;i++)orbs.push(orb());
  const width=s=>7+Math.sqrt(s.len)*.42;
  function mkSnake(name,hue,bot){let a,r,t=0;do{a=Math.random()*6.283;r=Math.random()*(WR-400);t++}while(t<40&&snakes.some(o=>!o.dead&&Math.hypot(o.pts[0].x-Math.cos(a)*r,o.pts[0].y-Math.sin(a)*r)<(bot?300:700)));const s={name,hue,bot,safe:bot?0:3,pts:[],len:bot?120+Math.random()*500:120,ang:Math.random()*6.283,dead:false,boost:false,dropT:0,ai:{t:0,ta:0},maxLen:0};const hx=Math.cos(a)*r,hy=Math.sin(a)*r;for(let i=0;i<40;i++)s.pts.push({x:hx-Math.cos(s.ang)*i*4,y:hy-Math.sin(s.ang)*i*4});snakes.push(s);return s}
  function reset(){snakes=[];me=mkSnake('You',140,false);shuffle(IO_NAMES).slice(0,15).forEach(n=>mkSnake(n,rand(360),true));dead=false}
  reset();
  let cam={x:0,y:0,z:1};
  function kill(s,by){if(s.dead)return;s.dead=true;for(let i=0;i<s.pts.length;i+=5)orbs.push(orb(s.pts[i].x+(Math.random()-.5)*10,s.pts[i].y+(Math.random()-.5)*10,2+Math.random()*3,`hsl(${s.hue} 90% 62%)`));if(s===me){dead=true;deadT=0;killer=by?by.name:'the edge of the world';c.best(Math.round(me.maxLen));noise(.5,'lowpass',400,.3)}else{if(by===me){beep(700,.1,'square',.06);c.after(()=>beep(1050,.12,'square',.06),90)}c.after(()=>{const i=snakes.indexOf(s);if(i>=0)snakes.splice(i,1);if(!dead||true)mkSnake(pick(IO_NAMES),rand(360),true)},2500)}}
  function hitsBody(px,py,r,self){for(const o of snakes){if(o===self||o.dead||o.safe>0)continue;const ow=width(o)/2;const bb=r+ow+40;const h=o.pts[0];if(Math.abs(h.x-px)>o.len+bb&&Math.abs(h.y-py)>o.len+bb)continue;for(let i=3;i<o.pts.length;i+=2){const q=o.pts[i];const dx=q.x-px,dy=q.y-py;if(dx*dx+dy*dy<(r+ow*.85)*(r+ow*.85))return o}}return null}
  function ai(s,dt){const a=s.ai;a.t-=dt;const h=s.pts[0],w=width(s)/2;if(a.t<=0){a.t=.15+Math.random()*.15;let best=null,bd=1e9;for(let k=0;k<30;k++){const o=orbs[rand(orbs.length)];const d=Math.hypot(o.x-h.x,o.y-h.y)/o.v;if(d<bd){bd=d;best=o}}for(const o of orbs){const d=Math.hypot(o.x-h.x,o.y-h.y);if(d<200&&d/o.v<bd){bd=d/o.v;best=o}}if(best)a.ta=Math.atan2(best.y-h.y,best.x-h.x);
      const look=[0,.5,-.5,1,-1,1.6,-1.6].map(da=>{const an=s.ang+da;let danger=0;[40,90,150].forEach((L,li)=>{const px=h.x+Math.cos(an)*L,py=h.y+Math.sin(an)*L;if(Math.hypot(px,py)>WR-30)danger+=3-li;if(hitsBody(px,py,w+6,s))danger+=3-li});return{an,danger}});if(look[0].danger>0){look.sort((p,q)=>p.danger-q.danger||Math.abs(p.an-s.ang)-Math.abs(q.an-s.ang));a.ta=look[0].an}
      s.boost=s.len>220&&Math.random()<.04}}
  c.on(cv,'pointerup',()=>{if(dead&&deadT>1)reset()});
  c.loop(dtm=>{const dt=Math.min(.05,dtm/1000);
    snakes.forEach(s=>{if(s.dead)return;const h=s.pts[0];let ta;if(s.bot){ai(s,dt);ta=s.ai.ta}else{const wx=cam.x+(ptr.x-W/2)/cam.z,wy=cam.y+(ptr.y-H/2)/cam.z;ta=Math.atan2(wy-h.y,wx-h.x);s.boost=(ptr.down||keys[' '])&&s.len>150}
      let da=ta-s.ang;while(da>Math.PI)da-=6.283;while(da<-Math.PI)da+=6.283;const turn=(5.2-Math.min(2.8,s.len/900))*dt;s.ang+=clamp(da,-turn,turn);const sp=(s.boost?380:190)*dt;
      const nh={x:h.x+Math.cos(s.ang)*sp,y:h.y+Math.sin(s.ang)*sp};s.pts.unshift(nh);let L=0;for(let i=1;i<s.pts.length;i++){L+=Math.hypot(s.pts[i].x-s.pts[i-1].x,s.pts[i].y-s.pts[i-1].y);if(L>s.len){s.pts.length=i+1;break}}
      if(s.boost){s.len=Math.max(150,s.len-60*dt);s.dropT-=dt;if(s.dropT<=0){s.dropT=.12;const t=s.pts[s.pts.length-1];orbs.push(orb(t.x,t.y,1.2,`hsl(${s.hue} 90% 62%)`))}}
      s.maxLen=Math.max(s.maxLen,s.len);const w=width(s)/2;
      for(let i=orbs.length-1;i>=0;i--){const o=orbs[i];const dx=o.x-nh.x,dy=o.y-nh.y;if(Math.abs(dx)>w+60||Math.abs(dy)>w+60)continue;const d=Math.hypot(dx,dy);if(d<w+50){o.x-=dx/d*Math.min(d,300*dt);o.y-=dy/d*Math.min(d,300*dt)}if(d<w+6){s.len+=o.v*4.5;orbs.splice(i,1);if(s===me&&Math.random()<.4)beep(600+o.v*200,.03,'sine',.025)}}
      s.safe=Math.max(0,(s.safe||0)-dt);if(Math.hypot(nh.x,nh.y)>WR){kill(s,null);return}const hit=s.safe>0?null:hitsBody(nh.x,nh.y,w*.8,s);if(hit)kill(s,hit)});
    while(orbs.length<1100)orbs.push(orb());
    if(!me.dead){const h=me.pts[0];cam.x+=(h.x-cam.x)*.2;cam.y+=(h.y-cam.y)*.2;const tz=clamp(1.15-Math.log10(me.len/120)*.35,.45,1.15);cam.z+=(tz-cam.z)*.03}else deadT+=dt;
    x.save();x.fillStyle='#14102a';x.fillRect(0,0,W,H);x.translate(W/2,H/2);x.scale(cam.z,cam.z);x.translate(-cam.x,-cam.y);
    x.strokeStyle='rgba(185,167,255,.08)';x.lineWidth=2;const g=80;const L0=cam.x-W/2/cam.z,T0=cam.y-H/2/cam.z;for(let gx=Math.floor(L0/g)*g;gx<L0+W/cam.z;gx+=g)for(let gy=Math.floor(T0/g)*g;gy<T0+H/cam.z;gy+=g){x.beginPath();for(let k=0;k<6;k++){const a=k/6*6.283;x.lineTo(gx+Math.cos(a)*30,gy+Math.sin(a)*30)}x.closePath();x.stroke()}
    x.strokeStyle='#F2352A';x.lineWidth=10;x.beginPath();x.arc(0,0,WR,0,7);x.stroke();
    const vis=(px,py,r)=>Math.abs(px-cam.x)<W/2/cam.z+r&&Math.abs(py-cam.y)<H/2/cam.z+r;const tt=performance.now()/300;
    x.globalCompositeOperation='lighter';orbs.forEach(o=>{if(!vis(o.x,o.y,20))return;const r=2.5+o.v*1.6+Math.sin(tt+o.ph)*.8;x.fillStyle=o.c;x.globalAlpha=.35;x.beginPath();x.arc(o.x,o.y,r*2.2,0,7);x.fill();x.globalAlpha=1;x.beginPath();x.arc(o.x,o.y,r,0,7);x.fill()});x.globalCompositeOperation='source-over';
    snakes.forEach(s=>{if(s.dead)return;const w=width(s);const st=Math.max(1,Math.round(w*.3/4));for(let i=s.pts.length-1;i>=0;i-=st){const q=s.pts[i];if(!vis(q.x,q.y,w))continue;const stripe=Math.floor(i/(st*3))%2;x.fillStyle=`hsl(${s.hue} ${stripe?80:90}% ${stripe?48:58}%)`;x.beginPath();x.arc(q.x,q.y,w/2,0,7);x.fill();if(s.boost){x.fillStyle=`hsla(${s.hue},100%,70%,.25)`;x.beginPath();x.arc(q.x,q.y,w/2+4,0,7);x.fill()}}
      const h=s.pts[0];[-1,1].forEach(sd=>{const ex=h.x+Math.cos(s.ang)*w*.18+Math.cos(s.ang+sd*1.57)*w*.26,ey=h.y+Math.sin(s.ang)*w*.18+Math.sin(s.ang+sd*1.57)*w*.26;x.fillStyle='#fff';x.beginPath();x.arc(ex,ey,w*.2,0,7);x.fill();x.fillStyle='#1D1A2F';x.beginPath();x.arc(ex+Math.cos(s.ang)*w*.07,ey+Math.sin(s.ang)*w*.07,w*.1,0,7);x.fill()});
      if(vis(h.x,h.y,40)){x.fillStyle='rgba(255,255,255,.85)';x.font='700 13px Figtree, sans-serif';x.textAlign='center';x.fillText(s.name,h.x,h.y-w-8)}});
    x.restore();
    const lb=snakes.filter(s=>!s.dead).map(s=>[s.name,Math.round(s.len),s===me]).sort((a,b)=>b[1]-a[1]);const mr=lb.findIndex(r=>r[2]);ioBoard(x,W,lb.slice(0,8).concat(mr>=8?[lb[mr]]:[]),'Longest');
    x.save();x.fillStyle='rgba(255,255,255,.1)';x.beginPath();x.arc(W-70,H-70,55,0,7);x.fill();x.strokeStyle='rgba(255,255,255,.4)';x.stroke();snakes.forEach(s=>{if(s.dead)return;const h=s.pts[0];x.fillStyle=s===me?'#fff':`hsl(${s.hue} 80% 60%)`;x.beginPath();x.arc(W-70+h.x/WR*52,H-70+h.y/WR*52,s===me?4:2,0,7);x.fill()});x.restore();
    x.fillStyle='#fff';x.font='700 16px "JetBrains Mono", monospace';x.textAlign='left';x.fillText('LENGTH '+Math.round(me.len)+'   BEST '+Math.round(me.maxLen),16,28);
    if(dead)ioOver(x,W,H,killer==='the edge of the world'?'Hit the edge!':'Crashed into '+killer+'!','You reached length '+Math.round(me.maxLen)+'. Click to play again.');c.stat('Noodle · length '+Math.round(me.len))})}});

/* ---------- Absorb (eat smaller balls) ---------- */
G.push({id:'io_absorb',name:'Absorb',kind:'io',wide:true,tint:'#14102a',blurb:'You’re a tiny glowing ball. Soak up anything smaller than you, dodge anything bigger, and grow until you rule the pond.',fmt:b=>'level '+b,
art:'<rect width="120" height="72" fill="#14102a"/><circle cx="60" cy="36" r="12" fill="#6EE7B7"/><circle cx="60" cy="36" r="17" fill="none" stroke="#6EE7B7" stroke-opacity=".4" stroke-width="4"/><circle cx="24" cy="20" r="5" fill="#7FC8F8"/><circle cx="96" cy="54" r="20" fill="#F2352A" fill-opacity=".85"/><circle cx="30" cy="58" r="3" fill="#7FC8F8"/><circle cx="88" cy="14" r="4" fill="#7FC8F8"/>',
run(root,c){const{cv,x,W,H}=ioCanvas(root);cv.style.background='#0d0a22';const ptr=ioPointer(c,cv,W,H);const info=el('p',{class:'hint'},'Steer toward the mouse (or your finger). Blue things are smaller than you: soak them up. Red things are bigger: stay away, or they’ll soak you up.');root.append(info);
  let lvl=Math.max(1,S.get('absorb_lv',1)),me,motes=[],state='play',msgT=0,WS=2400,stars=[...Array(160)].map(()=>({x:Math.random()*W,y:Math.random()*H,z:.2+Math.random()*.8}));
  function start(){WS=1500+lvl*150;motes=[];me={x:WS/2,y:WS/2,vx:0,vy:0,r:10};const n=380+lvl*40;for(let i=0;i<n;i++){let r=Math.random()<.8?2+Math.random()*9:10+Math.pow(Math.random(),2)*(25+lvl*12);const m={x:Math.random()*WS,y:Math.random()*WS,vx:(Math.random()-.5)*20,vy:(Math.random()-.5)*20,r,hunt:lvl>=3&&r>14&&Math.random()<.12+lvl*.02,flee:lvl>=2&&r<10&&Math.random()<.3,ph:Math.random()*6};if(Math.hypot(m.x-me.x,m.y-me.y)<120+r)continue;motes.push(m)}state='play';msgT=2.2}
  start();let cam={x:0,y:0,z:1};
  function absorb(a,b,d){const tr=Math.min(b.r,(a.r+b.r-d)*.5+.3);const nb=b.r-tr;const na=Math.sqrt(a.r*a.r+b.r*b.r-nb*nb);a.r=na;b.r=nb}
  c.on(cv,'pointerup',()=>{if(state==='win'){lvl++;S.set('absorb_lv',lvl);start()}else if(state==='lose')start()});
  c.loop(dtm=>{const dt=Math.min(.05,dtm/1000);msgT-=dt;
    if(state==='play'){const wx=cam.x+(ptr.x-W/2)/cam.z,wy=cam.y+(ptr.y-H/2)/cam.z;const dx=wx-me.x,dy=wy-me.y,d=Math.hypot(dx,dy)||1;const acc=420*Math.min(1,d/80)/Math.pow(me.r/10,.25);me.vx+=dx/d*acc*dt;me.vy+=dy/d*acc*dt;me.vx*=Math.pow(.3,dt);me.vy*=Math.pow(.3,dt)}
    const all=[me,...motes];all.forEach(m=>{if(m!==me){m.ph+=dt;if(m.hunt||m.flee){const dx=me.x-m.x,dy=me.y-m.y,d=Math.hypot(dx,dy)||1;if(d<400){const s=(m.hunt&&m.r>me.r?1:m.flee&&m.r<me.r?-1:0)*60;m.vx+=dx/d*s*dt;m.vy+=dy/d*s*dt}}m.vx*=Math.pow(.8,dt);m.vy*=Math.pow(.8,dt)}m.x+=m.vx*dt;m.y+=m.vy*dt;if(m.x<m.r){m.x=m.r;m.vx=Math.abs(m.vx)}if(m.x>WS-m.r){m.x=WS-m.r;m.vx=-Math.abs(m.vx)}if(m.y<m.r){m.y=m.r;m.vy=Math.abs(m.vy)}if(m.y>WS-m.r){m.y=WS-m.r;m.vy=-Math.abs(m.vy)}});
    if(state==='play'){const r0=me.r;for(const m of motes){if(m.r<=0)continue;const d=Math.hypot(m.x-me.x,m.y-me.y);if(d<m.r+me.r){if(me.r>=m.r)absorb(me,m,d);else absorb(m,me,d)}}const gained=me.r-r0;if(gained>.02&&Math.random()<.5)beep(400+me.r*6+Math.random()*80,.03,'sine',.03);if(gained<-.02&&Math.random()<.4)beep(160,.05,'sawtooth',.03);
      for(let i=0;i<motes.length;i+=3)for(let j=i+1;j<Math.min(motes.length,i+40);j++){const a=motes[i],b=motes[j];if(a.r<=0||b.r<=0)continue;const d=Math.hypot(a.x-b.x,a.y-b.y);if(d<a.r+b.r){if(a.r>=b.r)absorb(a,b,d);else absorb(b,a,d)}}
      motes=motes.filter(m=>m.r>.4);const biggest=motes.reduce((m,q)=>Math.max(m,q.r),0);
      if(me.r<1.5){state='lose';noise(.5,'lowpass',300,.3)}else if(me.r>biggest*1.02&&me.r>30){state='win';c.best(lvl);[523,659,784,1046].forEach((f,i)=>c.after(()=>beep(f,.2,'triangle',.07),i*110))}}
    const tz=clamp(34/(me.r+14)*1.2,.25,1.6);cam.z+=(tz-cam.z)*.03;cam.x+=(me.x-cam.x)*.12;cam.y+=(me.y-cam.y)*.12;
    x.fillStyle='#0d0a22';x.fillRect(0,0,W,H);stars.forEach(s=>{const sx=((s.x-cam.x*s.z*.2)%W+W)%W,sy=((s.y-cam.y*s.z*.2)%H+H)%H;x.fillStyle=`rgba(255,255,255,${s.z*.6})`;x.fillRect(sx,sy,s.z*2,s.z*2)});
    x.save();x.translate(W/2,H/2);x.scale(cam.z,cam.z);x.translate(-cam.x,-cam.y);x.strokeStyle='rgba(185,167,255,.35)';x.lineWidth=4/cam.z;x.strokeRect(0,0,WS,WS);x.globalCompositeOperation='lighter';
    const vis=(m)=>Math.abs(m.x-cam.x)<W/2/cam.z+m.r*2&&Math.abs(m.y-cam.y)<H/2/cam.z+m.r*2;
    motes.forEach(m=>{if(!vis(m))return;const k=clamp(m.r/me.r,0,2);const hue=k<1?200-k*40:k<1.05?60:10;const r=m.r*(1+Math.sin(m.ph*2)*.02);const g=x.createRadialGradient(m.x,m.y,r*.2,m.x,m.y,r*1.7);g.addColorStop(0,`hsla(${hue},95%,70%,.95)`);g.addColorStop(.55,`hsla(${hue},95%,55%,.55)`);g.addColorStop(1,`hsla(${hue},95%,50%,0)`);x.fillStyle=g;x.beginPath();x.arc(m.x,m.y,r*1.7,0,7);x.fill();if(m.hunt){x.strokeStyle='rgba(242,53,42,.8)';x.lineWidth=2/cam.z;x.beginPath();x.arc(m.x,m.y,r*1.25,0,7);x.stroke()}});
    const g=x.createRadialGradient(me.x,me.y,me.r*.2,me.x,me.y,me.r*2);g.addColorStop(0,'rgba(220,255,240,1)');g.addColorStop(.5,'rgba(110,231,183,.7)');g.addColorStop(1,'rgba(110,231,183,0)');x.fillStyle=g;x.beginPath();x.arc(me.x,me.y,me.r*2,0,7);x.fill();x.globalCompositeOperation='source-over';x.restore();
    const big=motes.reduce((m,q)=>Math.max(m,q.r),0);x.fillStyle='#fff';x.font='700 16px "JetBrains Mono", monospace';x.textAlign='left';x.fillText('LEVEL '+lvl+'   SIZE '+me.r.toFixed(1)+'   BIGGEST OTHER '+big.toFixed(1),16,28);
    if(msgT>0&&state==='play'){x.textAlign='center';x.font='40px "Bagel Fat One", sans-serif';x.fillStyle='#6EE7B7';x.fillText('Level '+lvl,W/2,120);x.font='600 16px Figtree, sans-serif';x.fillStyle='#fff';x.fillText(lvl>=3?'Watch out for red-ringed hunters!':lvl>=2?'Some little ones run away now':'Become the biggest thing in the pond',W/2,150)}
    if(state==='win')ioOver(x,W,H,'Biggest in the pond!','Level '+lvl+' cleared. Click for level '+(lvl+1)+'.');if(state==='lose')ioOver(x,W,H,'Absorbed!','Something bigger soaked you up. Click to try again.');c.stat('Absorb · Level '+lvl)})}});

/* ---------- Paper Land (paper.io-style) ---------- */
G.push({id:'io_paper',name:'Paper Land',kind:'io',wide:true,tint:'#FFE27A',blurb:'Leave your land to draw a trail, loop back home to claim everything inside. Cut other trails to knock players out. Like paper.io.',fmt:b=>b+'%',
art:'<rect width="120" height="72" fill="#FFFDF6"/><rect x="14" y="14" width="40" height="34" fill="#6EE7B7"/><path d="M54 30h26v28H38V48" fill="none" stroke="#2BB673" stroke-width="5" stroke-opacity=".6"/><rect x="34" y="42" width="8" height="8" fill="#2BB673" stroke="#1D1A2F" stroke-width="2"/><rect x="74" y="8" width="36" height="24" fill="#FF8FB1"/><rect x="92" y="28" width="8" height="8" fill="#F2352A" stroke="#1D1A2F" stroke-width="2"/>',
run(root,c){const{cv,x,W,H}=ioCanvas(root);const ptr=ioPointer(c,cv,W,H);root.append(el('p',{class:'hint'},'Arrow keys, WASD or the mouse to turn (swipe on a phone). Leave your land, then come back to claim everything you circled. If anyone hits your trail, you’re out, and that includes you.'));
  const N=72,CS=20,own=new Int8Array(N*N).fill(-1),trail=new Int8Array(N*N).fill(-1);const idx=(i,j)=>j*N+i;const DIRS=[[1,0],[0,1],[-1,0],[0,-1]];
  let units=[],me=null,state='play',deadT=0,best=0,killer='';
  function claimSquare(u,ci,cj,r){for(let j=cj-r;j<=cj+r;j++)for(let i=ci-r;i<=ci+r;i++)if(i>=0&&j>=0&&i<N&&j<N)own[idx(i,j)]=u.id}
  function mkUnit(id,name,col,bot){let ci,cj,tries=0;do{ci=4+rand(N-8);cj=4+rand(N-8);tries++}while(tries<200&&units.some(o=>!o.dead&&Math.abs(o.i-ci)<12&&Math.abs(o.j-cj)<12));const u={id,name,col,bot,i:ci,j:cj,dir:rand(4),next:null,t:0,dead:false,trail:[],ai:{st:'home',steps:0,leg:0,turn:1,home:{i:ci,j:cj}},sp:bot?c.pick(6,7,8):8.5};claimSquare(u,ci,cj,2);units[id]=u;return u}
  function reset(){own.fill(-1);trail.fill(-1);units=[];me=mkUnit(0,'You','#2BB673',false);shuffle(IO_NAMES).slice(0,7).forEach((n,k)=>mkUnit(k+1,n,IO_COLS[(k*3+1)%IO_COLS.length],true));state='play'}
  reset();
  function kill(u,by){if(u.dead)return;u.dead=true;u.trail.forEach(k=>{if(trail[k]===u.id)trail[k]=-1});u.trail=[];for(let k=0;k<N*N;k++)if(own[k]===u.id)own[k]=-1;if(u===me){state='dead';deadT=0;killer=by?(by===me?'your own trail':by.name):'the wall';noise(.4,'lowpass',300,.3)}else{if(by===me){beep(700,.1,'square',.06);c.after(()=>beep(1050,.12,'square',.06),90)}c.after(()=>{if(state!=='play')return;const nu=mkUnit(u.id,pick(IO_NAMES),u.col,true)},4000)}}
  function capture(u){u.trail.forEach(k=>{own[k]=u.id;trail[k]=-1});u.trail=[];const seen=new Uint8Array(N*N);const st=[];for(let i=0;i<N;i++){[idx(i,0),idx(i,N-1)].forEach(k=>{if(own[k]!==u.id&&!seen[k]){seen[k]=1;st.push(k)}})}for(let j=0;j<N;j++){[idx(0,j),idx(N-1,j)].forEach(k=>{if(own[k]!==u.id&&!seen[k]){seen[k]=1;st.push(k)}})}
    while(st.length){const k=st.pop();const i=k%N,j=(k/N)|0;DIRS.forEach(([di,dj])=>{const a=i+di,b=j+dj;if(a<0||b<0||a>=N||b>=N)return;const kk=idx(a,b);if(!seen[kk]&&own[kk]!==u.id){seen[kk]=1;st.push(kk)}})}
    let got=0;for(let k=0;k<N*N;k++)if(!seen[k]&&own[k]!==u.id){if(trail[k]>=0&&units[trail[k]]&&trail[k]!==u.id)kill(units[trail[k]],u);own[k]=u.id;got++}
    if(u===me){sweep(400,1200,.25,'triangle',.07)}}
  function step(u){if(u.next!=null&&(u.next+2)%4!==u.dir)u.dir=u.next;u.next=null;const[di,dj]=DIRS[u.dir];const ni=u.i+di,nj=u.j+dj;if(ni<0||nj<0||ni>=N||nj>=N){kill(u,null);return}u.i=ni;u.j=nj;const k=idx(ni,nj);
    if(trail[k]>=0){const victim=units[trail[k]];kill(victim,u);if(u.dead)return}
    units.forEach(o=>{if(o!==u&&!o.dead&&o.i===ni&&o.j===nj){if(own[k]===u.id)kill(o,u);else if(own[k]===o.id)kill(u,o);else{kill(o,u);kill(u,o)}}});if(u.dead)return;
    if(own[k]===u.id){if(u.trail.length)capture(u)}else{trail[k]=u.id;u.trail.push(k)}}
  function ai(u){const a=u.ai;const k=idx(u.i,u.j);const home=own[k]===u.id;const turnTo=d=>{if((d+2)%4!==u.dir)u.next=d};
    const danger=units.some(o=>o!==u&&!o.dead&&u.trail.some(t=>Math.abs((t%N)-o.i)+Math.abs(((t/N)|0)-o.j)<4));
    if(home&&a.st!=='out'){a.st='out';a.leg=0;a.steps=3+rand(c.pick(5,7,9));a.turn=Math.random()<.5?1:3;a.home={i:u.i,j:u.j}}
    if(a.st==='out'){a.steps--;if(a.steps<=0){a.leg++;if(a.leg>=3||danger){a.st='back'}else{turnTo((u.dir+a.turn)%4);a.steps=a.leg===1?3+rand(8):3+rand(6)}}}
    if(a.st==='back'||danger){let best=null,bd=1e9;for(let d=0;d<4;d++){if((d+2)%4===u.dir)continue;const[di,dj]=DIRS[d];const ni=u.i+di,nj=u.j+dj;if(ni<0||nj<0||ni>=N||nj>=N)continue;const kk=idx(ni,nj);if(trail[kk]===u.id)continue;const dd=Math.abs(ni-a.home.i)+Math.abs(nj-a.home.j)-(own[kk]===u.id?50:0);if(dd<bd){bd=dd;best=d}}if(best!=null)turnTo(best);if(home)a.st='home'}
    {const[di,dj]=DIRS[u.next!=null?u.next:u.dir];const ni=u.i+di,nj=u.j+dj;if(ni<1||nj<1||ni>=N-1||nj>=N-1||trail[idx(clamp(ni,0,N-1),clamp(nj,0,N-1))]===u.id){for(let d=0;d<4;d++){if((d+2)%4===u.dir)continue;const[a2,b2]=DIRS[d];const i2=u.i+a2,j2=u.j+b2;if(i2>=1&&j2>=1&&i2<N-1&&j2<N-1&&trail[idx(i2,j2)]!==u.id){u.next=d;break}}}}}
  const keyDir={arrowright:0,d:0,arrowdown:1,s:1,arrowleft:2,a:2,arrowup:3,w:3};c.on(document,'keydown',e=>{const d=keyDir[e.key.toLowerCase()];if(d!=null){me.next=d;e.preventDefault()}});
  let sw=null;c.on(cv,'pointerdown',e=>{sw=canvasPos(cv,e);if(state==='dead'&&deadT>1)reset()});c.on(cv,'pointermove',e=>{if(e.pointerType==='mouse'){const p=canvasPos(cv,e);const dx=p.x-W/2,dy=p.y-H/2;if(Math.hypot(dx,dy)>30)me.next=Math.abs(dx)>Math.abs(dy)?(dx>0?0:2):(dy>0?1:3)}else if(sw){const p=canvasPos(cv,e);const dx=p.x-sw.x,dy=p.y-sw.y;if(Math.hypot(dx,dy)>24){me.next=Math.abs(dx)>Math.abs(dy)?(dx>0?0:2):(dy>0?1:3);sw=p}}});
  let cam={x:0,y:0};
  c.loop(dtm=>{const dt=Math.min(.05,dtm/1000);if(state==='play'){units.forEach(u=>{if(!u||u.dead)return;u.t+=dt*u.sp;while(u.t>=1&&!u.dead){u.t-=1;if(u.bot)ai(u);step(u)}})}else deadT+=dt;
    let mine=0;for(let k=0;k<N*N;k++)if(own[k]===0)mine++;const pct=mine/(N*N)*100;best=Math.max(best,pct);if(state==='play'&&pct>=99){state='won'}
    const tx=(me.i+.5+(me.dead?0:DIRS[me.dir][0]*me.t))*CS,ty=(me.j+.5+(me.dead?0:DIRS[me.dir][1]*me.t))*CS;cam.x+=(tx-cam.x)*.2;cam.y+=(ty-cam.y)*.2;
    x.fillStyle='#e8e1d0';x.fillRect(0,0,W,H);x.save();x.translate(Math.round(W/2-cam.x),Math.round(H/2-cam.y));x.fillStyle='#FFFDF6';x.fillRect(0,0,N*CS,N*CS);
    const i0=Math.max(0,Math.floor((cam.x-W/2)/CS)),i1=Math.min(N,Math.ceil((cam.x+W/2)/CS)),j0=Math.max(0,Math.floor((cam.y-H/2)/CS)),j1=Math.min(N,Math.ceil((cam.y+H/2)/CS));
    for(let j=j0;j<j1;j++)for(let i=i0;i<i1;i++){const k=idx(i,j);if(own[k]>=0&&units[own[k]]){x.fillStyle=units[own[k]].col;x.globalAlpha=.85;x.fillRect(i*CS,j*CS,CS,CS)}if(trail[k]>=0&&units[trail[k]]){x.fillStyle=units[trail[k]].col;x.globalAlpha=.45;x.fillRect(i*CS+3,j*CS+3,CS-6,CS-6)}x.globalAlpha=1}
    x.strokeStyle='rgba(29,26,47,.06)';x.lineWidth=1;x.beginPath();for(let i=i0;i<=i1;i++){x.moveTo(i*CS,j0*CS);x.lineTo(i*CS,j1*CS)}for(let j=j0;j<=j1;j++){x.moveTo(i0*CS,j*CS);x.lineTo(i1*CS,j*CS)}x.stroke();x.strokeStyle='#F2352A';x.lineWidth=4;x.strokeRect(0,0,N*CS,N*CS);
    units.forEach(u=>{if(!u||u.dead)return;const[di,dj]=DIRS[u.dir];const px=(u.i+di*Math.min(1,u.t))*CS,py=(u.j+dj*Math.min(1,u.t))*CS;x.fillStyle=u.col;x.strokeStyle='#1D1A2F';x.lineWidth=3;x.fillRect(px-2,py-2,CS+4,CS+4);x.strokeRect(px-2,py-2,CS+4,CS+4);x.fillStyle='#fff';x.fillRect(px+4+di*3,py+5+dj*3,5,5);x.fillRect(px+11+di*3,py+5+dj*3,5,5);x.fillStyle='#1D1A2F';x.font='700 12px Figtree, sans-serif';x.textAlign='center';x.fillText(u.name,px+CS/2,py-8)});
    x.restore();
    const cnt={};for(let k=0;k<N*N;k++)if(own[k]>=0)cnt[own[k]]=(cnt[own[k]]||0)+1;const lb=units.filter(u=>u&&!u.dead).map(u=>[u.name,((cnt[u.id]||0)/(N*N)*100).toFixed(1)+'%',u===me]).sort((a,b)=>parseFloat(b[1])-parseFloat(a[1]));ioBoard(x,W,lb.slice(0,8),'Land owned');
    x.fillStyle='#1D1A2F';x.font='700 16px "JetBrains Mono", monospace';x.textAlign='left';x.fillText('YOUR LAND '+pct.toFixed(1)+'%   BEST '+best.toFixed(1)+'%',16,28);
    if(state==='dead'){c.best(Math.round(best));ioOver(x,W,H,'Knocked out by '+killer+'!','Best this round: '+best.toFixed(1)+'%. Click to play again.')}if(state==='won'){c.best(100);ioOver(x,W,H,'You own the whole map!','100%. The paper kingdom is yours.')}
    c.stat('Paper Land · '+pct.toFixed(1)+'%')})}});
