/* ================= .IO 2 ================= */
function ioDir(c,cv,W,H){const ptr=ioPointer(c,cv,W,H);const keys={};c.on(document,'keydown',e=>{keys[e.key.toLowerCase()]=true});c.on(document,'keyup',e=>{keys[e.key.toLowerCase()]=false});
  return{ptr,keys,dir(){const kx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),ky=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0);if(kx||ky){const l=Math.hypot(kx,ky);return{x:kx/l,y:ky/l,m:1}}if(!ptr.moved)return{x:0,y:0,m:0};const dx=ptr.x-W/2,dy=ptr.y-H/2,l=Math.hypot(dx,dy);return l<8?{x:0,y:0,m:0}:{x:dx/l,y:dy/l,m:Math.min(1,l/120)}}}}
/* ---- Swallow (hole.io) ---- */
G.push({id:'io_hole',name:'Swallow',kind:'io',wide:true,tint:'#1D1A2F',blurb:'You’re a hole in the ground. Swallow cones, people, cars, trees and whole buildings to grow, and gobble up smaller holes. Biggest hole after two minutes wins.',fmt:b=>b+' size',
art:'<rect width="120" height="72" fill="#8c86a3"/><rect x="10" y="8" width="24" height="20" fill="#FFD23F" stroke="#1D1A2F" stroke-width="2"/><rect x="84" y="40" width="26" height="24" fill="#FF8FB1" stroke="#1D1A2F" stroke-width="2"/><ellipse cx="58" cy="40" rx="22" ry="18" fill="#1D1A2F" stroke="#2BB673" stroke-width="4"/><rect x="50" y="30" width="10" height="7" fill="#7FC8F8" stroke="#1D1A2F" transform="rotate(30 55 33)"/>',
run(root,c){const{cv,x,W,H}=ioCanvas(root);const D=ioDir(c,cv,W,H);root.append(el('p',{class:'hint'},'Move the mouse (or drag, or WASD) to steer your hole. Things smaller than your hole fall in. Avoid bigger holes!'));
  const WS=2600,BLK=260;const TYPES=[['cone',4,'#FF9F43',1],['person',4.5,'#FFD23F',1],['hydrant',5,'#F2352A',1],['bench',8,'#8a5a2b',2],['bin',6,'#2BB673',1],['tree',13,'#2BB673',0],['car',16,'#7FC8F8',2],['van',21,'#ffffff',2],['bus',28,'#FFD23F',2],['house',38,'#FF8FB1',3],['shop',50,'#B9A7FF',3],['tower',72,'#8c86a3',3]];
  let objs=[],holes=[],me,t=120,state='ready',falling=[],cam={x:0,y:0,s:1};
  function mkObj(k,x0,y0){const T0=TYPES[k];return{k,r:T0[1]*(.85+Math.random()*.3),col:T0[2],shape:T0[3],x:x0,y:y0,a:Math.random()*6.28,vx:0,vy:0,mv:T0[0]==='person'||T0[0]==='car'||T0[0]==='van'||T0[0]==='bus',name:T0[0]}}
  function populate(){objs=[];for(let bx0=0;bx0<WS;bx0+=BLK)for(let by0=0;by0<WS;by0+=BLK){const lx=bx0+40,ly=by0+40,L=BLK-80;const r=Math.random();if(r<.25){for(let k=0;k<8;k++)objs.push(mkObj(5,lx+Math.random()*L,ly+Math.random()*L));objs.push(mkObj(3,lx+L/2,ly+L/2))}else if(r<.65){for(let k=0;k<4;k++)objs.push(mkObj(9,lx+30+(k%2)*(L-60),ly+30+Math.floor(k/2)*(L-60)))}else if(r<.9){objs.push(mkObj(10,lx+L*.3,ly+L*.3));objs.push(mkObj(10,lx+L*.7,ly+L*.7));objs.push(mkObj(9,lx+L*.7,ly+L*.3))}else objs.push(mkObj(11,lx+L/2,ly+L/2));
      for(let k=0;k<10;k++){const onX=Math.random()<.5;const px=onX?bx0+Math.random()*BLK:bx0+(Math.random()<.5?18:BLK-18),py=onX?by0+(Math.random()<.5?18:BLK-18):by0+Math.random()*BLK;objs.push(mkObj(pick([0,1,1,1,2,4]),px,py))}
      for(let k=0;k<2;k++){const o=mkObj(pick([6,6,6,7,8]),bx0+(k?BLK/2:4),by0+(k?4:BLK/2));o.dir=k?0:1;o.sp=40+Math.random()*40;objs.push(o)}}}
  function mkHole(name,col,bot){const h={name,col,bot,r:18,x:200+Math.random()*(WS-400),y:200+Math.random()*(WS-400),vx:0,vy:0,dead:false,score:0,ai:{tx:0,ty:0,t:0}};holes.push(h);return h}
  function start(){holes=[];falling=[];populate();me=mkHole('You','#2BB673',false);shuffle(IO_NAMES).slice(0,6).forEach((n,i)=>mkHole(n,IO_COLS[i],true));t=c.pick(150,120,100);state='play'}
  const area=r=>r*r;
  function eat(h,o){falling.push({o,h,t:0});h.r=Math.sqrt(area(h.r)+area(o.r)*.32);h.score+=Math.round(o.r);if(h===me){beep(300+Math.min(900,o.r*12),.05,'triangle',.04);if(o.r>30)noise(.3,'lowpass',300,.2)}}
  function step(dt){if(state!=='play')return;t-=dt;if(t<=0){state='over';const rank=holes.slice().sort((a,b)=>b.r-a.r).indexOf(me)+1;c.best(Math.round(me.r));c.stat('Swallow · #'+rank+' · size '+Math.round(me.r));return}
    for(const h of holes){if(h.dead)continue;let d;if(!h.bot)d=D.dir();else{const ai=h.ai;ai.t-=dt;if(ai.t<=0){ai.t=.6+Math.random()*.8;let best=null,bd=1e9;for(const o of objs){if(o.r<h.r*.8){const dd=Math.hypot(o.x-h.x,o.y-h.y)-o.r*3;if(dd<bd){bd=dd;best=o}}}for(const o of holes)if(o!==h&&!o.dead&&o.r<h.r*.8){const dd=Math.hypot(o.x-h.x,o.y-h.y)-60;if(dd<bd){bd=dd;best=o}}ai.tx=best?best.x:Math.random()*WS;ai.ty=best?best.y:Math.random()*WS;for(const o of holes)if(o!==h&&!o.dead&&o.r>h.r*1.2&&Math.hypot(o.x-h.x,o.y-h.y)<o.r*4){ai.tx=h.x-(o.x-h.x)*3;ai.ty=h.y-(o.y-h.y)*3}}const dx=ai.tx-h.x,dy=ai.ty-h.y,l=Math.hypot(dx,dy)||1;d={x:dx/l,y:dy/l,m:1}}
      const sp=(170-Math.min(80,h.r*.6))*(h.bot?c.pick(.75,.9,1):1);h.vx+=(d.x*sp*d.m-h.vx)*Math.min(1,dt*6);h.vy+=(d.y*sp*d.m-h.vy)*Math.min(1,dt*6);h.x=clamp(h.x+h.vx*dt,h.r,WS-h.r);h.y=clamp(h.y+h.vy*dt,h.r,WS-h.r)}
    for(const o of objs){if(!o.mv)continue;if(o.name==='person'){o.a+=(Math.random()-.5)*dt*2;o.x+=Math.cos(o.a)*14*dt;o.y+=Math.sin(o.a)*14*dt;const nh=holes.find(h=>!h.dead&&Math.hypot(h.x-o.x,h.y-o.y)<h.r+40&&h.r>o.r*1.2);if(nh){const a=Math.atan2(o.y-nh.y,o.x-nh.x);o.x+=Math.cos(a)*30*dt;o.y+=Math.sin(a)*30*dt}}else if(o.dir!=null){if(o.dir)o.y=(o.y+o.sp*dt+WS)%WS;else o.x=(o.x+o.sp*dt+WS)%WS;o.a=o.dir?Math.PI/2:0}o.x=clamp(o.x,0,WS);o.y=clamp(o.y,0,WS)}
    for(const h of holes){if(h.dead)continue;for(let i=objs.length-1;i>=0;i--){const o=objs[i];if(o.r<h.r*.88&&Math.hypot(o.x-h.x,o.y-h.y)<h.r-o.r*.4){objs.splice(i,1);eat(h,o)}}
      for(const o of holes)if(o!==h&&!o.dead&&o.r<h.r*.8&&Math.hypot(o.x-h.x,o.y-h.y)<h.r-o.r*.3){o.dead=true;h.r=Math.sqrt(area(h.r)+area(o.r)*.6);h.score+=Math.round(o.r*3);if(o===me){state='dead';noise(.6,'lowpass',200,.3)}else if(h===me){beep(900,.2,'square',.05)}if(o.bot)setTimeout(()=>{o.dead=false;o.r=18;o.x=Math.random()*WS;o.y=Math.random()*WS},4000)}}
    falling=falling.filter(f=>(f.t+=dt*2.5)<1);if(objs.length<500&&Math.random()<dt*6){objs.push(mkObj(pick([0,1,1,2,4,6]),Math.random()*WS,Math.random()*WS))}
    const ts=clamp(1.5*18/Math.max(18,me.r*.75),.28,1.5);cam.s+=(ts-cam.s)*Math.min(1,dt*2);cam.x=me.x;cam.y=me.y;c.stat('Swallow · size '+Math.round(me.r)+' · '+Math.ceil(t)+'s')}
  function draw(){const s=cam.s;x.setTransform(1,0,0,1,0,0);x.fillStyle='#5A5470';x.fillRect(0,0,W,H);x.setTransform(s,0,0,s,W/2-cam.x*s,H/2-cam.y*s);
    x.fillStyle='#6b6680';x.fillRect(0,0,WS,WS);for(let bx0=0;bx0<WS;bx0+=BLK)for(let by0=0;by0<WS;by0+=BLK){x.fillStyle='#b8e0a0';x.fillRect(bx0+30,by0+30,BLK-60,BLK-60);x.fillStyle='#d8d4e4';x.fillRect(bx0+24,by0+24,BLK-48,6);x.fillRect(bx0+24,by0+BLK-30,BLK-48,6);x.fillRect(bx0+24,by0+24,6,BLK-48);x.fillRect(bx0+BLK-30,by0+24,6,BLK-48)}
    x.strokeStyle='#FFE27A';x.setLineDash([16,16]);x.lineWidth=2;for(let k=0;k<=WS;k+=BLK){x.beginPath();x.moveTo(k,0);x.lineTo(k,WS);x.moveTo(0,k);x.lineTo(WS,k);x.stroke()}x.setLineDash([]);
    const vis=o=>Math.abs(o.x-cam.x)<W/s/2+80&&Math.abs(o.y-cam.y)<H/s/2+80;
    for(const h of holes){if(h.dead||!vis(h))continue;const g=x.createRadialGradient(h.x,h.y,h.r*.3,h.x,h.y,h.r);g.addColorStop(0,'#000');g.addColorStop(.85,'#1D1A2F');g.addColorStop(1,'#3a3552');x.fillStyle=g;x.beginPath();x.arc(h.x,h.y,h.r,0,7);x.fill();x.strokeStyle=h.col;x.lineWidth=Math.max(3,h.r*.08);x.stroke()}
    falling.forEach(f=>{const o=f.o,h=f.h;const k=1-f.t;x.save();x.globalAlpha=k;x.translate(o.x+(h.x-o.x)*f.t,o.y+(h.y-o.y)*f.t);x.rotate(o.a+f.t*3);x.scale(k,k);shape(o);x.restore()});
    for(const o of objs){if(!vis(o))continue;x.save();x.translate(o.x,o.y);x.rotate(o.a);x.fillStyle='rgba(0,0,0,.18)';x.fillRect(-o.r+4,-o.r*.6+4,o.r*2,o.r*1.2);shape(o);x.restore()}
    x.font='700 '+(14/s|0)+'px Figtree, sans-serif';x.textAlign='center';for(const h of holes){if(h.dead||!vis(h))continue;x.fillStyle='#fff';x.fillText(h.name,h.x,h.y-h.r-6/s)}
    x.setTransform(1,0,0,1,0,0);const lb=holes.filter(h=>!h.dead).sort((a,b)=>b.r-a.r).slice(0,6);x.fillStyle='rgba(29,26,47,.7)';x.fillRect(W-180,10,170,24+lb.length*20);x.font='700 14px Figtree, sans-serif';x.textAlign='left';x.fillStyle='#fff';x.fillText('⏱️ '+Math.max(0,Math.ceil(t))+'s',W-170,28);lb.forEach((h,i)=>{x.fillStyle=h===me?'#FFD23F':'#fff';x.fillText((i+1)+'. '+h.name+'  '+Math.round(h.r),W-170,48+i*20)});
    if(state==='ready')banner(x,W,H,'Swallow','Tap to start'),0;if(state==='over'){const rank=holes.slice().sort((a,b)=>b.r-a.r).indexOf(me)+1;banner(x,W,H,rank===1?'🏆 Biggest hole!':'#'+rank+' place','Size '+Math.round(me.r)+' · tap to play again')}if(state==='dead')banner(x,W,H,'Swallowed!','A bigger hole got you · tap to play again')}
  function shape(o){x.fillStyle=o.col;x.strokeStyle='#1D1A2F';x.lineWidth=2;if(o.shape===1){x.beginPath();x.arc(0,0,o.r,0,7);x.fill();x.stroke()}else if(o.shape===0){x.fillStyle='#2BB673';x.beginPath();x.arc(0,0,o.r,0,7);x.fill();x.stroke();x.fillStyle='#6EE7B7';x.beginPath();x.arc(-o.r*.3,-o.r*.3,o.r*.4,0,7);x.fill()}else if(o.shape===2){x.fillRect(-o.r,-o.r*.55,o.r*2,o.r*1.1);x.strokeRect(-o.r,-o.r*.55,o.r*2,o.r*1.1);x.fillStyle='rgba(29,26,47,.45)';x.fillRect(o.r*.2,-o.r*.45,o.r*.5,o.r*.9)}else{x.fillRect(-o.r,-o.r,o.r*2,o.r*2);x.strokeRect(-o.r,-o.r,o.r*2,o.r*2);x.fillStyle='rgba(255,255,255,.35)';for(let i=-o.r+6;i<o.r-6;i+=12)for(let j=-o.r+6;j<o.r-6;j+=12)x.fillRect(i,j,6,6)}}
  c.on(cv,'pointerdown',()=>{if(state!=='play')start()});c.loop(dt=>{step(Math.min(.05,dt/1000));if(me)draw();else{x.fillStyle='#5A5470';x.fillRect(0,0,W,H);banner(x,W,H,'Swallow','Tap to start')}})}});

/* ---- Tank Arena (diep.io) ---- */
G.push({id:'io_tanks',name:'Tank Arena',kind:'io',wide:true,tint:'#7FC8F8',blurb:'Blast shapes for XP, level up, and pour points into reload, damage, speed and armour. Out-gun the bot tanks. Like diep.io.',fmt:b=>'level '+b,
art:'<rect width="120" height="72" fill="#dfe6ee"/><g stroke="#1D1A2F" stroke-width="2.5"><rect x="58" y="30" width="30" height="12" fill="#8c86a3"/><circle cx="54" cy="36" r="16" fill="#2d6fd6"/><rect x="92" y="10" width="14" height="14" fill="#FFD23F"/><path d="M20 52l8-14 8 14z" fill="#F2352A"/></g><circle cx="98" cy="36" r="4" fill="#2d6fd6"/>',
run(root,c){const{cv,x,W,H}=ioCanvas(root);const D=ioDir(c,cv,W,H);const up=el('div',{class:'row',style:'flex-wrap:wrap;gap:6px;justify-content:center'});root.append(up,el('p',{class:'hint'},'WASD to drive, aim with the mouse and hold click to shoot (E toggles auto-fire). On a phone, drag to drive; it aims and fires by itself. Spend level-up points on the buttons (or keys 1–6).'));
  const WS=3000;const ST=[['Reload','⚡'],['Damage','💥'],['Bullet speed','➶'],['Move speed','🏃'],['Max health','❤️'],['Regen','➕']];let tanks=[],shapes=[],bullets=[],me,auto=false,camx=0,camy=0,parts=[];
  const btns=ST.map((s2,i)=>{const b=el('button',{class:'btn',type:'button',style:'font-size:13px;padding:6px 9px'},'');b.addEventListener('click',()=>spend(me,i));up.append(b);return b});
  c.on(document,'keydown',e=>{const k=e.key;if(k>='1'&&k<='6')spend(me,+k-1);if(k.toLowerCase()==='e')auto=!auto});
  const xpFor=l=>Math.round(20*Math.pow(1.35,l));
  function mkTank(name,col,bot){const t={name,col,bot,x:300+Math.random()*(WS-600),y:300+Math.random()*(WS-600),vx:0,vy:0,a:0,lvl:1,xp:0,pts:0,st:[0,0,0,0,0,0],hp:100,cd:0,dead:false,rt:0,score:0,ai:{t:0,tx:0,ty:0},hurtT:9};tanks.push(t);return t}
  const maxHp=t=>100+t.st[4]*25+t.lvl*4;
  function spend(t,i){if(!t||t.pts<=0||t.st[i]>=7)return;t.st[i]++;t.pts--;if(i===4)t.hp+=25;if(t===me){beep(700+i*60,.06,'triangle',.05);paint()}}
  function paint(){btns.forEach((b,i)=>{b.textContent=ST[i][1]+' '+ST[i][0]+' '+'●'.repeat(me.st[i])+'○'.repeat(7-me.st[i]);b.disabled=me.pts<=0||me.st[i]>=7;b.classList.toggle('primary',me.pts>0&&me.st[i]<7)})}
  function mkShape(){const r=Math.random();const k=r<.6?0:r<.9?1:2;const hp=[10,30,120][k];shapes.push({k,x:Math.random()*WS,y:Math.random()*WS,hp,hp0:hp,xp:[10,25,130][k],r:[14,16,26][k],a:Math.random()*6,va:(Math.random()-.5)*.6,vx:(Math.random()-.5)*6,vy:(Math.random()-.5)*6})}
  function start(){tanks=[];shapes=[];bullets=[];me=mkTank('You','#2d6fd6',false);shuffle(IO_NAMES).slice(0,8).forEach((n,i)=>{const b=mkTank(n,['#F2352A','#FF9F43','#B9A7FF','#FF8FB1','#2BB673','#8c86a3','#e8c48a','#c9e89a'][i],true);b.lvl=1+rand(8);b.xp=0;for(let k=0;k<b.lvl-1;k++)spend2(b)});for(let i=0;i<260;i++)mkShape();paint()}
  function spend2(b){b.pts++;const pr=[0,1,1,2,4,3,5];spend(b,pick(pr))}
  function gain(t,xp){t.xp+=xp;t.score+=xp;while(t.xp>=xpFor(t.lvl)&&t.lvl<45){t.xp-=xpFor(t.lvl);t.lvl++;if(t.bot)spend2(t);else{t.pts++;beep(1000,.12,'triangle',.06);paint()}}}
  function fire(t){const rl=Math.max(.1,.55-t.st[0]*.06);if(t.cd>0)return;t.cd=rl;const sp=380+t.st[2]*45,dm=12+t.st[1]*5;bullets.push({x:t.x+Math.cos(t.a)*30,y:t.y+Math.sin(t.a)*30,vx:Math.cos(t.a)*sp+t.vx*.3,vy:Math.sin(t.a)*sp+t.vy*.3,dm,l:1.3,o:t,r:6+t.st[1]*.4});t.vx-=Math.cos(t.a)*8;t.vy-=Math.sin(t.a)*8;if(t===me&&Math.random()<.5)beep(220,.03,'square',.02)}
  function kill(t,by){t.dead=true;for(let i=0;i<16;i++)parts.push({x:t.x,y:t.y,vx:(Math.random()-.5)*300,vy:(Math.random()-.5)*300,l:.6,c:t.col});if(by)gain(by,Math.round(40+t.score*.4));if(t===me){noise(.6,'lowpass',300,.3);c.best(me.lvl)}setTimeout(()=>{t.dead=false;t.x=300+Math.random()*(WS-600);t.y=300+Math.random()*(WS-600);t.lvl=Math.max(1,Math.floor(t.lvl/2));t.xp=0;t.score=0;t.st=[0,0,0,0,0,0];t.pts=t.lvl-1;if(t.bot){const p=t.pts;t.pts=0;for(let k=0;k<p;k++)spend2(t)}t.hp=maxHp(t);if(t===me)paint()},t===me?3000:4000)}
  function step(dt){for(const t of tanks){if(t.dead)continue;t.cd-=dt;t.hurtT+=dt;const mh=maxHp(t);if(t.hurtT>3)t.hp=Math.min(mh,t.hp+dt*(2+t.st[5]*2.5));let mv={x:0,y:0,m:0},shoot=false;
      if(!t.bot){mv=D.dir();const touch=('ontouchstart' in window)&&D.ptr.down;if(touch||!D.ptr.moved){let best=null,bd=600;for(const o of tanks)if(o!==t&&!o.dead){const d=Math.hypot(o.x-t.x,o.y-t.y);if(d<bd){bd=d;best=o}}if(!best)for(const s2 of shapes){const d=Math.hypot(s2.x-t.x,s2.y-t.y);if(d<bd){bd=d;best=s2}}if(best){t.a=Math.atan2(best.y-t.y,best.x-t.x);shoot=true}if(!D.ptr.down&&!Object.values(D.keys).some(Boolean))mv={x:0,y:0,m:0}}else{const wx=camx+(D.ptr.x-W/2),wy=camy+(D.ptr.y-H/2);t.a=Math.atan2(wy-t.y,wx-t.x);shoot=D.ptr.down||auto;if(!Object.values(D.keys).some(Boolean))mv={x:0,y:0,m:0}}}
      else{const ai=t.ai;ai.t-=dt;let tgt=null,bd=500;for(const o of tanks)if(o!==t&&!o.dead){const d=Math.hypot(o.x-t.x,o.y-t.y);if(d<bd){bd=d;tgt=o}}if(tgt&&tgt.lvl>t.lvl+4&&bd<300){mv={x:(t.x-tgt.x)/bd,y:(t.y-tgt.y)/bd,m:1}}else{if(!tgt){let sd=700;for(const s2 of shapes){const d=Math.hypot(s2.x-t.x,s2.y-t.y);if(d<sd){sd=d;tgt=s2}}}if(tgt){const d=Math.hypot(tgt.x-t.x,tgt.y-t.y);t.a+=(Math.atan2(tgt.y-t.y,tgt.x-t.x)-t.a+Math.PI*3)%(Math.PI*2)-Math.PI;t.a=t.a;shoot=d<520;mv=d>220?{x:(tgt.x-t.x)/d,y:(tgt.y-t.y)/d,m:.8}:{x:-(tgt.y-t.y)/d,y:(tgt.x-t.x)/d,m:.5}}else{if(ai.t<=0){ai.t=3;ai.tx=Math.random()*WS;ai.ty=Math.random()*WS}const d=Math.hypot(ai.tx-t.x,ai.ty-t.y)||1;mv={x:(ai.tx-t.x)/d,y:(ai.ty-t.y)/d,m:.7}}}t.a+=0}
      const sp=(170+t.st[3]*18)*(t.bot?c.pick(.8,.95,1.05):1);t.vx+=(mv.x*sp*mv.m-t.vx)*Math.min(1,dt*5);t.vy+=(mv.y*sp*mv.m-t.vy)*Math.min(1,dt*5);t.x=clamp(t.x+t.vx*dt,20,WS-20);t.y=clamp(t.y+t.vy*dt,20,WS-20);if(shoot)fire(t)}
    for(const s2 of shapes){s2.a+=s2.va*dt;s2.x=clamp(s2.x+s2.vx*dt,0,WS);s2.y=clamp(s2.y+s2.vy*dt,0,WS)}
    bullets=bullets.filter(b=>{b.l-=dt;b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.l<=0)return false;for(const s2 of shapes){if(Math.hypot(s2.x-b.x,s2.y-b.y)<s2.r+b.r){s2.hp-=b.dm;s2.vx+=b.vx*.02;s2.vy+=b.vy*.02;if(s2.hp<=0){gain(b.o,s2.xp);for(let i=0;i<6;i++)parts.push({x:s2.x,y:s2.y,vx:(Math.random()-.5)*200,vy:(Math.random()-.5)*200,l:.4,c:['#FFD23F','#F2352A','#7FC8F8'][s2.k]});shapes.splice(shapes.indexOf(s2),1);mkShape()}return false}}
      for(const t of tanks){if(t===b.o||t.dead)continue;if(Math.hypot(t.x-b.x,t.y-b.y)<22+b.r){t.hp-=b.dm*(t.bot&&!b.o.bot?1:c.pick(.6,.85,1.1));t.hurtT=0;t.vx+=b.vx*.04;t.vy+=b.vy*.04;if(t.hp<=0)kill(t,b.o);return false}}return true});
    for(const t of tanks){if(t.dead)continue;for(const s2 of shapes)if(Math.hypot(s2.x-t.x,s2.y-t.y)<s2.r+20){t.hp-=dt*20;t.hurtT=0;s2.hp-=dt*30;const a=Math.atan2(t.y-s2.y,t.x-s2.x);t.vx+=Math.cos(a)*20;t.vy+=Math.sin(a)*20;if(s2.hp<=0){gain(t,s2.xp);shapes.splice(shapes.indexOf(s2),1);mkShape()}if(t.hp<=0){kill(t,null);break}}}
    parts=parts.filter(p=>(p.l-=dt)>0);parts.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt});if(!me.dead){camx+=(me.x-camx)*Math.min(1,dt*8);camy+=(me.y-camy)*Math.min(1,dt*8)}c.stat('Tank Arena · level '+me.lvl+(me.pts?' · '+me.pts+' points to spend!':''))}
  function draw(){x.setTransform(1,0,0,1,0,0);x.fillStyle='#cdd3db';x.fillRect(0,0,W,H);x.translate(W/2-camx,H/2-camy);x.fillStyle='#dfe6ee';x.fillRect(0,0,WS,WS);x.strokeStyle='rgba(0,0,0,.06)';x.lineWidth=1;const g0x=Math.floor((camx-W/2)/25)*25,g0y=Math.floor((camy-H/2)/25)*25;for(let gx=g0x;gx<camx+W/2;gx+=25){x.beginPath();x.moveTo(gx,camy-H/2);x.lineTo(gx,camy+H/2);x.stroke()}for(let gy=g0y;gy<camy+H/2;gy+=25){x.beginPath();x.moveTo(camx-W/2,gy);x.lineTo(camx+W/2,gy);x.stroke()}
    const vis=(px,py)=>Math.abs(px-camx)<W/2+60&&Math.abs(py-camy)<H/2+60;
    for(const s2 of shapes){if(!vis(s2.x,s2.y))continue;x.save();x.translate(s2.x,s2.y);x.rotate(s2.a);x.fillStyle=['#FFD23F','#F2352A','#7FC8F8'][s2.k];x.strokeStyle='#1D1A2F';x.lineWidth=3;x.beginPath();const n=[4,3,5][s2.k];for(let i=0;i<n;i++){const a=i/n*Math.PI*2;i?x.lineTo(Math.cos(a)*s2.r,Math.sin(a)*s2.r):x.moveTo(Math.cos(a)*s2.r,Math.sin(a)*s2.r)}x.closePath();x.fill();x.stroke();x.restore();if(s2.hp<s2.hp0){x.fillStyle='#1D1A2F';x.fillRect(s2.x-16,s2.y+s2.r+6,32,5);x.fillStyle='#2BB673';x.fillRect(s2.x-16,s2.y+s2.r+6,32*s2.hp/s2.hp0,5)}}
    for(const b of bullets){if(!vis(b.x,b.y))continue;x.fillStyle=b.o.col;x.strokeStyle='#1D1A2F';x.lineWidth=2;x.beginPath();x.arc(b.x,b.y,b.r,0,7);x.fill();x.stroke()}
    for(const t of tanks){if(t.dead||!vis(t.x,t.y))continue;const sz=20+t.lvl*.3;x.save();x.translate(t.x,t.y);x.rotate(t.a);x.fillStyle='#8c86a3';x.strokeStyle='#1D1A2F';x.lineWidth=3;x.fillRect(0,-sz*.35,sz*1.7,sz*.7);x.strokeRect(0,-sz*.35,sz*1.7,sz*.7);x.restore();x.fillStyle=t.col;x.strokeStyle='#1D1A2F';x.lineWidth=3;x.beginPath();x.arc(t.x,t.y,sz,0,7);x.fill();x.stroke();
      x.fillStyle='#1D1A2F';x.font='700 13px Figtree, sans-serif';x.textAlign='center';x.fillText(t.name+' · Lv '+t.lvl,t.x,t.y-sz-10);const mh=maxHp(t);if(t.hp<mh){x.fillRect(t.x-22,t.y+sz+8,44,6);x.fillStyle='#2BB673';x.fillRect(t.x-22,t.y+sz+8,44*Math.max(0,t.hp)/mh,6)}}
    parts.forEach(p=>{x.globalAlpha=p.l*2;x.fillStyle=p.c;x.fillRect(p.x-3,p.y-3,6,6)});x.globalAlpha=1;
    x.setTransform(1,0,0,1,0,0);x.fillStyle='rgba(29,26,47,.75)';x.fillRect(W/2-160,H-34,320,20);x.fillStyle='#FFD23F';x.fillRect(W/2-158,H-32,316*me.xp/xpFor(me.lvl),16);x.fillStyle='#fff';x.font='800 13px Figtree, sans-serif';x.textAlign='center';x.fillText('Level '+me.lvl+(me.pts?' · '+me.pts+' upgrade points!':'')+(auto?' · AUTO-FIRE':''),W/2,H-20);
    const lb=tanks.slice().sort((a,b)=>b.score-a.score).slice(0,6);x.fillStyle='rgba(29,26,47,.7)';x.fillRect(W-190,10,180,20+lb.length*20);x.textAlign='left';lb.forEach((t,i)=>{x.fillStyle=t===me?'#FFD23F':'#fff';x.fillText((i+1)+'. '+t.name+'  '+t.score,W-180,28+i*20)});
    const mm=120;x.fillStyle='rgba(29,26,47,.55)';x.fillRect(10,H-mm-10,mm,mm);tanks.forEach(t=>{if(t.dead)return;x.fillStyle=t===me?'#FFD23F':t.col;x.fillRect(10+t.x/WS*mm-2,H-mm-10+t.y/WS*mm-2,4,4)});if(me.dead)banner(x,W,H,'Destroyed!','Respawning with half your levels…')}
  start();c.loop(dt=>{step(Math.min(.05,dt/1000));draw()})}});

/* ---- Sumo Bash ---- */
G.push({id:'io_sumo',name:'Sumo Bash',kind:'io',wide:true,tint:'#7FC8F8',blurb:'Bumper-ball sumo on a shrinking ice ring. Slide, dash and knock everyone else off the edge. Last one standing wins the round.',fmt:b=>b+' wins',
art:'<rect width="120" height="72" fill="#1D1A2F"/><ellipse cx="60" cy="40" rx="50" ry="26" fill="#bfe6ff" stroke="#fff" stroke-width="3"/><circle cx="44" cy="38" r="10" fill="#2BB673" stroke="#1D1A2F" stroke-width="2.5"/><circle cx="72" cy="42" r="12" fill="#F2352A" stroke="#1D1A2F" stroke-width="2.5"/><path d="M54 38h6" stroke="#fff" stroke-width="3"/>',
run(root,c){const{cv,x,W,H}=ioCanvas(root);const D=ioDir(c,cv,W,H);root.append(el('p',{class:'hint'},'Steer with the mouse (or drag, or WASD). Click, tap or Space to DASH and shove. The ring shrinks, so stay in the middle!'));
  let balls=[],R0=270,R=270,state='ready',round=0,wins=S.get('sumo_w',0)||0,msgT=0,msg='',parts=[];const CX=W/2,CY=H/2;
  function start(){round++;R=R0;balls=[];const n=c.pick(4,6,8);const cols=shuffle(['#F2352A','#FF9F43','#FFD23F','#B9A7FF','#FF8FB1','#7FC8F8','#8c86a3','#e8c48a']);for(let i=0;i<n;i++){const a=i/n*Math.PI*2;balls.push({name:i?IO_NAMES[(i*3+round)%IO_NAMES.length]:'You',col:i?cols[i]:'#2BB673',me:!i,x:CX+Math.cos(a)*R*.6,y:CY+Math.sin(a)*R*.6,vx:0,vy:0,r:i?18+Math.random()*6:22,dcd:0,out:0,t:Math.random()*2})}state='play';msg='Round '+round+'!';msgT=1.5}
  function dash(b,dx,dy){if(b.dcd>0||b.out)return;const l=Math.hypot(dx,dy)||1;b.vx+=dx/l*420;b.vy+=dy/l*420;b.dcd=1.1;if(b.me)sweep(300,900,.15,'square',.05)}
  c.on(cv,'pointerdown',()=>{if(state!=='play'){start();return}const me=balls[0];const d=D.dir();dash(me,d.x||me.vx,d.y||me.vy)});c.on(document,'keydown',e=>{if(e.key===' '){e.preventDefault();if(state!=='play'){start();return}const me=balls[0],d=D.dir();dash(me,d.x||me.vx,d.y||me.vy)}});
  function step(dt){msgT-=dt;parts=parts.filter(p=>(p.l-=dt)>0);parts.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt});if(state!=='play')return;R=Math.max(90,R-dt*c.pick(5,7,9));
    for(const b of balls){if(b.out){b.out+=dt;continue}b.dcd-=dt;b.t-=dt;let ax=0,ay=0;if(b.me){const d=D.dir();ax=d.x*d.m;ay=d.y*d.m}else{let tgt=null,bd=1e9;for(const o of balls)if(o!==b&&!o.out){const d=Math.hypot(o.x-b.x,o.y-b.y);if(d<bd){bd=d;tgt=o}}const dc=Math.hypot(b.x-CX,b.y-CY);if(dc>R*.72||!tgt){ax=(CX-b.x)/(dc||1);ay=(CY-b.y)/(dc||1)}else{const tx=tgt.x+(tgt.x-CX)*.2,ty=tgt.y+(tgt.y-CY)*.2;const l=Math.hypot(tx-b.x,ty-b.y)||1;ax=(tx-b.x)/l;ay=(ty-b.y)/l;if(bd<90&&b.t<=0&&Math.random()<c.pick(.3,.5,.7)){b.t=1+Math.random();dash(b,tgt.x-b.x,tgt.y-b.y)}}}
      const acc=c.pick(420,440,460)*(b.me?1.1:1);b.vx+=ax*acc*dt;b.vy+=ay*acc*dt;b.vx*=Math.pow(.55,dt);b.vy*=Math.pow(.55,dt);b.x+=b.vx*dt;b.y+=b.vy*dt;if(Math.hypot(b.x-CX,b.y-CY)>R+b.r*.4){b.out=.001;noise(.4,'lowpass',300,.2);if(b.me){msg='You fell off!';msgT=2}}}
    for(let i=0;i<balls.length;i++)for(let j=i+1;j<balls.length;j++){const a=balls[i],b=balls[j];if(a.out||b.out)continue;const dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy),m=a.r+b.r;if(d<m&&d>0){const nx=dx/d,ny=dy/d,ov=(m-d)/2;a.x-=nx*ov;a.y-=ny*ov;b.x+=nx*ov;b.y+=ny*ov;const ma=a.r*a.r,mb=b.r*b.r;const rel=(a.vx-b.vx)*nx+(a.vy-b.vy)*ny;if(rel>0){const k=1.9*rel/(ma+mb);a.vx-=k*mb*nx;a.vy-=k*mb*ny;b.vx+=k*ma*nx;b.vy+=k*ma*ny;if(rel>200){for(let q=0;q<6;q++)parts.push({x:a.x+nx*a.r,y:a.y+ny*a.r,vx:(Math.random()-.5)*200,vy:(Math.random()-.5)*200,l:.3});beep(160+rel*.2,.05,'square',.04)}}}}
    const alive=balls.filter(b=>!b.out);const me=balls[0];if(me.out&&alive.length<=1||alive.length<=1||me.out&&state==='play'&&me.out>1.2){state='over';if(!me.out&&alive[0]===me){wins++;S.set('sumo_w',wins);c.best(wins);[523,659,784].forEach((q,i)=>c.after(()=>beep(q,.15,'triangle',.06),i*100))}}c.stat('Sumo Bash · '+wins+' wins')}
  function draw(){x.fillStyle='#1D1A2F';x.fillRect(0,0,W,H);x.fillStyle='rgba(127,200,248,.15)';x.beginPath();x.arc(CX,CY,R0+20,0,7);x.fill();const g=x.createRadialGradient(CX,CY,10,CX,CY,R);g.addColorStop(0,'#eaf7ff');g.addColorStop(1,'#a8dcff');x.fillStyle=g;x.beginPath();x.arc(CX,CY,R,0,7);x.fill();x.strokeStyle='#F2352A';x.lineWidth=6;x.stroke();x.strokeStyle='rgba(29,26,47,.12)';x.lineWidth=3;x.beginPath();x.arc(CX,CY,R*.4,0,7);x.stroke();
    for(const b of balls){const s=b.out?Math.max(0,1-b.out*1.5):1;if(s<=0)continue;x.save();x.translate(b.x,b.y);x.scale(s,s);x.fillStyle='rgba(0,0,0,.2)';x.beginPath();x.ellipse(4,b.r*.7,b.r,b.r*.35,0,0,7);x.fill();x.fillStyle=b.col;x.strokeStyle='#1D1A2F';x.lineWidth=3;x.beginPath();x.arc(0,0,b.r,0,7);x.fill();x.stroke();x.fillStyle='rgba(255,255,255,.5)';x.beginPath();x.arc(-b.r*.35,-b.r*.35,b.r*.3,0,7);x.fill();const a=Math.atan2(b.vy,b.vx);x.fillStyle='#1D1A2F';x.beginPath();x.arc(Math.cos(a)*b.r*.4-4,Math.sin(a)*b.r*.4-3,3,0,7);x.arc(Math.cos(a)*b.r*.4+4,Math.sin(a)*b.r*.4-3,3,0,7);x.fill();if(b.dcd>0&&b.dcd>.8){x.strokeStyle='#fff';x.lineWidth=3;x.beginPath();x.arc(0,0,b.r+5,0,7);x.stroke()}x.restore();x.fillStyle='#fff';x.font='700 12px Figtree, sans-serif';x.textAlign='center';if(!b.out)x.fillText(b.name,b.x,b.y-b.r-6)}
    parts.forEach(p=>{x.fillStyle='rgba(255,255,255,'+p.l*3+')';x.fillRect(p.x-2,p.y-2,4,4)});
    x.fillStyle='#fff';x.font='800 16px Figtree, sans-serif';x.textAlign='left';x.fillText('Round '+round+' · wins '+wins+' · left '+balls.filter(b=>!b.out).length,14,26);const me=balls[0];if(me&&!me.out){x.fillStyle=me.dcd>0?'#8c86a3':'#FFD23F';x.fillText(me.dcd>0?'Dash recharging…':'DASH ready (click/Space)',14,48)}
    if(msgT>0){x.fillStyle='#FFD23F';x.font='40px "Bagel Fat One", sans-serif';x.textAlign='center';x.fillText(msg,W/2,90)}if(state==='ready')banner(x,W,H,'Sumo Bash','Tap to start');if(state==='over'){const win=me&&!me.out;banner(x,W,H,win?'🏆 Last one standing!':'Knocked out!',(win?'':'Winner: '+(balls.find(b=>!b.out)||{name:'nobody'}).name+' · ')+'tap for the next round')}}
  c.loop(dt=>{step(Math.min(.04,dt/1000));draw()})}});
