/* ================= SUPERHEROES ================= */
/* Shared comic-book kit: cel shading, ink outlines, halftone sky, comic HUD, hero figure, city builder, flow. */
function heroKit(st3,c,cfg){
  const{T,scene,camera,hud,input,wrap}=st3;
  const gd=new Uint8Array([80,80,80,255,165,165,165,255,255,255,255,255]);const grad=new T.DataTexture(gd,3,1,T.RGBAFormat);grad.minFilter=grad.magFilter=T.NearestFilter;grad.generateMipmaps=false;grad.needsUpdate=true;
  const mc={};const TM=(col,o)=>{if(o)return new T.MeshToonMaterial(Object.assign({color:col,gradientMap:grad},o));return mc[col]||(mc[col]=new T.MeshToonMaterial({color:col,gradientMap:grad}))};
  const inkM=new T.MeshBasicMaterial({color:0x1D1A2F,side:T.BackSide});
  function ink(obj,w){const list=[];obj.traverse(o=>{if(o.isMesh&&!o.userData.ink&&!o.userData.noInk)list.push(o)});list.forEach(o=>{const g=o.geometry;g.computeBoundingBox();const bb=g.boundingBox,cx=(bb.min.x+bb.max.x)/2,cy2=(bb.min.y+bb.max.y)/2,cz=(bb.min.z+bb.max.z)/2;
    const sx=1+w/Math.max(.02,(bb.max.x-bb.min.x)/2),sy=1+w/Math.max(.02,(bb.max.y-bb.min.y)/2),sz=1+w/Math.max(.02,(bb.max.z-bb.min.z)/2);const h=new T.Mesh(g,inkM);h.userData.ink=1;h.scale.set(sx,sy,sz);h.position.set(cx*(1-sx),cy2*(1-sy),cz*(1-sz));o.add(h)});return obj}
  function sky(top,bot,dots){const t=tex(T,256,512,(x,w,h)=>{const g=x.createLinearGradient(0,0,0,h);g.addColorStop(0,top);g.addColorStop(1,bot);x.fillStyle=g;x.fillRect(0,0,w,h);x.fillStyle=dots||'rgba(255,255,255,.22)';for(let y=0;y<h;y+=10)for(let k=0;k<w;k+=10){const r=1+2.6*(y/h);x.beginPath();x.arc(k+(y/10%2)*5,y,r,0,7);x.fill()}});t.wrapS=t.wrapT=T.ClampToEdgeWrapping;t.repeat.set(1,1);scene.background=t;scene.fog=new T.Fog(new T.Color(bot),cfg.fogNear||90,cfg.fogFar||330)}
  function lights(skyc,gndc,sunI){scene.add(new T.HemisphereLight(skyc||0xffffff,gndc||0x6a6080,.75));const sun=new T.DirectionalLight(0xffffff,sunI||.75);sun.position.set(40,80,30);scene.add(sun);return sun}
  /* ---- hero figure ---- */
  function fig(o){const g=new T.Group();const suit=TM(o.suit),trim=TM(o.trim),skin=TM(o.skin||0xf1c7a0),B=o.bulk||1;
    const hips=new T.Group();hips.position.y=.95;g.add(hips);const torso=new T.Group();hips.add(torso);
    const chest=part(T,bx(T,.64*B,.72,.38*B),suit,0,.4,0,torso);part(T,bx(T,.54*B,.14,.4*B),trim,0,.05,0,torso);
    const emb=part(T,new T.CylinderGeometry(.14,.14,.05,o.emblemSides||6),trim,0,.5,.2*B,torso);emb.rotation.x=Math.PI/2;
    if(o.bolt){const bs=new T.Shape();bs.moveTo(.02,.12);bs.lineTo(-.07,-.01);bs.lineTo(0,-.01);bs.lineTo(-.03,-.12);bs.lineTo(.07,.02);bs.lineTo(0,.02);bs.closePath();part(T,new T.ShapeGeometry(bs),TM(o.suit),0,.5,.23*B,torso).userData.noInk=1}
    const neck=new T.Group();neck.position.y=.8;torso.add(neck);const head=part(T,bx(T,.44,.46,.44),skin,0,.25,0,neck);
    part(T,bx(T,.46,.13,.46),TM(o.mask||o.suit),0,.3,0,neck);const eyeM=TM(0xffffff);part(T,bx(T,.1,.06,.02),eyeM,-.1,.3,.235,neck).userData.noInk=1;part(T,bx(T,.1,.06,.02),eyeM,.1,.3,.235,neck).userData.noInk=1;
    if(o.hair!=null)part(T,bx(T,.48,.14,.48),TM(o.hair),0,.52,-.01,neck);if(o.helm)part(T,bx(T,.48,.2,.48),TM(o.helm),0,.48,0,neck);if(o.ears){[-1,1].forEach(s=>{const e=part(T,new T.ConeGeometry(.07,.22,4),TM(o.mask||o.suit),s*.17,.58,0,neck);e.rotation.z=-s*.2})}
    const limb=(len,w,mat,endMat,endLen)=>{const p=new T.Group();const m=part(T,bx(T,w,len,w),mat,0,-len/2,0,p);if(endMat)part(T,bx(T,w*1.12,endLen,w*1.12),endMat,0,-len+endLen/2-.02,0,p);return p};
    const armL=limb(.7,.2*B,suit,trim,.2),armR=limb(.7,.2*B,suit,trim,.2);armL.position.set(-.43*B,.7,0);armR.position.set(.43*B,.7,0);torso.add(armL,armR);
    const legL=limb(.92,.25*B,suit,trim,.28),legR=limb(.92,.25*B,suit,trim,.28);legL.position.set(-.16*B,0,0);legR.position.set(.16*B,0,0);hips.add(legL,legR);
    ink(g,.035);
    let cape=null;if(o.cape!=null){const cg=new T.PlaneGeometry(.72*B,1.25,2,10);cg.translate(0,-.625,0);const cm=new T.MeshToonMaterial({color:o.cape,gradientMap:grad,side:T.DoubleSide});cape=new T.Mesh(cg,cm);cape.userData.noInk=1;cape.position.set(0,.76,-.21*B);torso.add(cape);cape.userData.base=Float32Array.from(cg.attributes.position.array)}
    g.userData={hips,torso,neck,head,armL,armR,legL,legR,cape,t:0};return g}
  function capeAnim(f,lift,t,flap){const cp=f.userData.cape;if(!cp)return;const a=cp.geometry.attributes.position,b=cp.userData.base;for(let i=0;i<a.count;i++){const bx0=b[i*3],d=-b[i*3+1];const k=d/1.25;const ang=lift*1.45*Math.pow(k,.6)+Math.sin(t*(flap||9)+d*4+bx0*3)*.12*(.2+lift)*k;a.setXYZ(i,bx0*(1+k*.25),-Math.cos(ang)*d,-Math.sin(ang)*d)}a.needsUpdate=true}
  function pose(f,m,t,amt){const u=f.userData;amt=amt==null?1:amt;const s=Math.sin(t),cs=Math.cos(t);
    const set=(o,x,y,z)=>{o.rotation.set(x||0,y||0,z||0)};
    if(m==='run'){set(u.legL,s*1.1*amt);set(u.legR,-s*1.1*amt);set(u.armL,-s*1.2*amt,0,.08);set(u.armR,s*1.2*amt,0,-.08);set(u.torso,.18*amt+.1*amt*amt,0,0);u.hips.position.y=.95+Math.abs(cs)*.1*amt}
    else if(m==='sprint'){set(u.legL,s*1.5);set(u.legR,-s*1.5);set(u.armL,1.3,0,.25);set(u.armR,1.3,0,-.25);set(u.torso,.55);u.hips.position.y=.9+Math.abs(cs)*.08}
    else if(m==='fly'){set(u.legL,.1+s*.08);set(u.legR,.14-s*.08);set(u.armR,-2.9,0,-.1);set(u.armL,-.1,0,.3);set(u.torso,0);u.hips.position.y=.95}
    else if(m==='hover'){set(u.legL,.15+s*.1);set(u.legR,-.05-s*.1);set(u.armL,-.2,0,.5);set(u.armR,-.2,0,-.5);set(u.torso,0);u.hips.position.y=.95}
    else if(m==='lift'){set(u.legL,0,0,.15);set(u.legR,0,0,-.15);set(u.armL,-2.9,0,-.3);set(u.armR,-2.9,0,.3);set(u.torso,-.05);u.hips.position.y=.9}
    else if(m==='air'){set(u.legL,-.6);set(u.legR,.3);set(u.armL,-.6,0,.7);set(u.armR,-.6,0,-.7);set(u.torso,.1)}
    else if(m==='skate'){set(u.legL,s*.5*amt-.1);set(u.legR,-s*.5*amt-.1);set(u.armL,-s*.5*amt,0,.6);set(u.armR,s*.5*amt,0,-.6);set(u.torso,.35);u.hips.position.y=.85;u.torso.rotation.y=s*.2*amt}
    else{set(u.legL);set(u.legR);set(u.armL,Math.sin(t*.5)*.05,0,.12);set(u.armR,-Math.sin(t*.5)*.05,0,-.12);set(u.torso);u.hips.position.y=.95+Math.sin(t*.8)*.015}
    u.neck.rotation.x=-u.torso.rotation.x*.6}
  /* ---- city ---- */
  function city(o){const n=o.n||6,blk=o.blk||26,st=o.st||14,cell=blk+st,half=n*cell/2;const grp=new T.Group();scene.add(grp);const boxes=[];
    const road=tex(T,256,256,(x,w,h)=>{x.fillStyle=o.road||'#4a4760';x.fillRect(0,0,w,h);x.fillStyle='rgba(0,0,0,.14)';for(let i=0;i<600;i++)x.fillRect(Math.random()*w,Math.random()*h,2,2);x.fillStyle='#FFD23F';for(let i=4;i<w;i+=26){x.fillRect(0,i,2,13);x.fillRect(w-2,i,2,13);x.fillRect(i,0,13,2);x.fillRect(i,h-2,13,2)}});
    const W0=n*cell+st;road.repeat.set(W0/cell,W0/cell);road.offset.set(-st/(2*cell),-st/(2*cell));const gnd=new T.Mesh(new T.PlaneGeometry(W0,W0),new T.MeshToonMaterial({map:road,gradientMap:grad}));gnd.rotation.x=-Math.PI/2;grp.add(gnd);
    const far=new T.Mesh(new T.PlaneGeometry(1400,1400),TM(o.outer||0x3f8f45));far.rotation.x=-Math.PI/2;far.position.y=-.05;grp.add(far);
    const PAL=o.pal||[0xF2352A,0x7FC8F8,0xFFD23F,0xB9A7FF,0xFF9F43,0x6EE7B7,0xFF8FB1,0xe8e1d0];
    const winT={};const wtex=col=>{if(winT[col])return winT[col];const cs='#'+col.toString(16).padStart(6,'0');return winT[col]=tex(T,64,128,(x,w,h)=>{x.fillStyle=cs;x.fillRect(0,0,w,h);for(let r=0;r<6;r++)for(let k=0;k<3;k++){x.fillStyle='#1D1A2F';x.fillRect(5+k*20,6+r*21,14,15);x.fillStyle=Math.random()<.25?'#FFE27A':'#5c7fbf';x.fillRect(7+k*20,8+r*21,10,11);x.fillStyle='rgba(255,255,255,.5)';x.fillRect(7+k*20,8+r*21,3,11)}x.fillStyle='rgba(0,0,0,.18)';x.fillRect(0,0,3,h)})};
    const walk=TM(0xd8d4e4),roofM=TM(0x5A5470),grass=TM(0x4aa351),trunk=TM(0x8a5a2b),leaf=TM(0x2BB673);
    const smC={};const sideM=(col,rx,ry)=>{const k=col+'_'+rx+'_'+ry;if(smC[k])return smC[k];const t0=wtex(col).clone();t0.needsUpdate=true;t0.repeat.set(rx,ry);return smC[k]=new T.MeshToonMaterial({map:t0,gradientMap:grad})};
    const addB=(x,z,w,d,h,col)=>{const ry=Math.max(1,Math.round(h/8));const sm=sideM(col,Math.max(1,Math.round(w/6)),ry),sm2=sideM(col,Math.max(1,Math.round(d/6)),ry);
      const m=new T.Mesh(bx(T,w,h,d),[sm2,sm2,roofM,roofM,sm,sm]);m.position.set(x,h/2,z);grp.add(m);ink(m,.18);const b={x0:x-w/2,x1:x+w/2,z0:z-d/2,z1:z+d/2,h,m,cx:x,cz:z,w,d,col,extras:[]};boxes.push(b);
      b.extras.push(part(T,bx(T,w+.6,.6,d+.6),TM(0x1D1A2F),x,h+.3,z,grp));if(Math.random()<.35){const tw=part(T,cy(T,1.1,1.1,2.2,10),TM(0x8a5a2b),x+(Math.random()-.5)*(w-4),h+1.7,z+(Math.random()-.5)*(d-4),grp);ink(tw,.08);b.extras.push(tw)}return b};
    const blocks=[];
    for(let i=0;i<n;i++)for(let j=0;j<n;j++){const cx=-half+cell*(i+.5),cz=-half+cell*(j+.5);const kind=o.kind?o.kind(i,j):(Math.random()<.12?'park':'b');blocks.push({i,j,cx,cz,kind});
      if(kind==='void')continue;const sw=part(T,bx(T,blk+2,.3,blk+2),kind==='park'?grass:walk,cx,.15,cz,grp);
      if(kind==='park'||kind==='plaza'){if(kind==='plaza')sw.material=TM(0xe8e1d0);const nt=kind==='park'?7:3;for(let k=0;k<nt;k++){const tx=cx+(Math.random()-.5)*(blk-6),tz=cz+(Math.random()-.5)*(blk-6);part(T,cy(T,.3,.4,2,8),trunk,tx,1.3,tz,grp);ink(part(T,new T.IcosahedronGeometry(1.7,0),leaf,tx,3.4,tz,grp),.1);boxes.push({x0:tx-.4,x1:tx+.4,z0:tz-.4,z1:tz+.4,h:2.2,tree:1})}continue}
      const dc=Math.hypot(cx,cz)/half;const hmul=o.hmul||1;const lots=Math.random()<.4?1:Math.random()<.5?2:4;
      const mkH=()=>Math.round((12+Math.random()*26+(1-Math.min(1,dc))*34)*hmul);
      if(lots===1)addB(cx,cz,blk-2,blk-2,mkH(),pick(PAL));else if(lots===2){const q=(blk-3)/2;const ax=Math.random()<.5;[-1,1].forEach(s=>ax?addB(cx+s*(q/2+.5),cz,q,blk-2,mkH(),pick(PAL)):addB(cx,cz+s*(q/2+.5),blk-2,q,mkH(),pick(PAL)))}else{const q=(blk-3)/2;[[-1,-1],[1,-1],[-1,1],[1,1]].forEach(([a,b2])=>addB(cx+a*(q/2+.5),cz+b2*(q/2+.5),q,q,mkH(),pick(PAL)))}}
    const streets=[];for(let k=0;k<=n;k++)streets.push(-half+cell*k);
    const lim=half+st/2-1;
    CITIES.push({grp,boxes});
    return{grp,boxes,blocks,n,blk,st,cell,half,lim,streets,
      streetPt(){const a=Math.random()<.5,k=pick(streets),t=(Math.random()-.5)*2*half;return a?{x:k+(Math.random()-.5)*(st-4),z:t}:{x:t,z:k+(Math.random()-.5)*(st-4)}},
      node(i,j){return{x:streets[i],z:streets[j]}}}}
  /* ---- endless streaming city ---- */
  function streamCity(o){const blk=o.blk||26,st=o.st||16,cell=blk+st,C=o.chunk||3,R=o.radius||2,seed=o.seed||7;const root=new T.Group();scene.add(root);const boxes=[],chunks=new Map();
    const hr=(i,j,k)=>{let t=(Math.imul(i|0,374761393)+Math.imul(j|0,668265263)+Math.imul((k|0)+seed,982451653))|0;t=Math.imul(t^(t>>>13),1274126177);t^=t>>>16;return(t>>>0)/4294967296};
    const road=tex(T,256,256,(x,w,h)=>{x.fillStyle=o.road||'#4a4760';x.fillRect(0,0,w,h);x.fillStyle='rgba(0,0,0,.14)';for(let i=0;i<600;i++)x.fillRect(Math.random()*w,Math.random()*h,2,2);x.fillStyle='#FFD23F';for(let i=4;i<w;i+=26){x.fillRect(0,i,2,13);x.fillRect(w-2,i,2,13);x.fillRect(i,0,13,2);x.fillRect(i,h-2,13,2)}});
    const K2=(2*R+3)*C|1;road.repeat.set(K2,K2);const gnd=new T.Mesh(new T.PlaneGeometry(K2*cell,K2*cell),new T.MeshToonMaterial({map:road,gradientMap:grad}));gnd.rotation.x=-Math.PI/2;root.add(gnd);
    const PAL=o.pal||[0xF2352A,0x7FC8F8,0xFFD23F,0xB9A7FF,0xFF9F43,0x6EE7B7,0xFF8FB1,0xe8e1d0];
    const winT={};const wtex=col=>{if(winT[col])return winT[col];const cs='#'+col.toString(16).padStart(6,'0');return winT[col]=tex(T,64,128,(x,w,h)=>{x.fillStyle=cs;x.fillRect(0,0,w,h);for(let r=0;r<6;r++)for(let k=0;k<3;k++){x.fillStyle='#1D1A2F';x.fillRect(5+k*20,6+r*21,14,15);x.fillStyle=Math.random()<.25?'#FFE27A':'#5c7fbf';x.fillRect(7+k*20,8+r*21,10,11);x.fillStyle='rgba(255,255,255,.5)';x.fillRect(7+k*20,8+r*21,3,11)}x.fillStyle='rgba(0,0,0,.18)';x.fillRect(0,0,3,h)})};
    const walk=TM(0xd8d4e4),roofM=TM(0x5A5470),grass=TM(0x4aa351),trunk=TM(0x8a5a2b),leaf=TM(0x2BB673),ledge=TM(0x1D1A2F),tank=TM(0x8a5a2b);const water=o.canal?(o.waterMat||new T.MeshToonMaterial({color:0x4DA3E0,gradientMap:grad})):null;
    const smC={};const sideM=(col,rx,ry)=>{const k=col+'_'+rx+'_'+ry;if(smC[k])return smC[k];const t0=wtex(col).clone();t0.needsUpdate=true;t0.repeat.set(rx,ry);return smC[k]=new T.MeshToonMaterial({map:t0,gradientMap:grad})};
    const treeG=cy(T,.3,.4,2,8),leafG=new T.IcosahedronGeometry(1.7,0),slabG=bx(T,blk+2,.3,blk+2);
    function addB(ch,x,z,w,d,h,col,r3){const ry=Math.max(1,Math.round(h/8));const m=new T.Mesh(bx(T,w,h,d),[sideM(col,Math.max(1,Math.round(d/6)),ry),sideM(col,Math.max(1,Math.round(d/6)),ry),roofM,roofM,sideM(col,Math.max(1,Math.round(w/6)),ry),sideM(col,Math.max(1,Math.round(w/6)),ry)]);m.position.set(x,h/2,z);ch.grp.add(m);ink(m,.18);
      const b={x0:x-w/2,x1:x+w/2,z0:z-d/2,z1:z+d/2,h,m,cx:x,cz:z,w,d,col,extras:[],chunk:ch};b.extras.push(part(T,bx(T,w+.6,.6,d+.6),ledge,x,h+.3,z,ch.grp));if(r3<.35){const tw=part(T,cy(T,1.1,1.1,2.2,10),tank,x+(r3-.17)*(w-4),h+1.7,z+(r3*3%1-.5)*(d-4),ch.grp);ink(tw,.08);b.extras.push(tw)}ch.boxes.push(b);boxes.push(b);return b}
    const kindOf=(i,j)=>{if(o.kind)return o.kind(i,j);const r=hr(i,j,1);return r<.1?'park':r<.135?'plaza':r<.15?'stadium':'b'};const stone=TM(0xcfc8b8),pool=TM(0x4DA3E0),seatM=TM(0xd8d4e4),fieldM=TM(0x3f9e4a),lineM=TM(0xffffff);
    function build(ci,cj){const ch={ci,cj,grp:new T.Group(),boxes:[],pins:0};root.add(ch.grp);
      for(let a=0;a<C;a++)for(let b2=0;b2<C;b2++){const i=ci*C+a,j=cj*C+b2;const cx=(i+.5)*cell,cz=(j+.5)*cell;const kind=kindOf(i,j);if(kind==='void')continue;const sw=new T.Mesh(slabG,kind==='park'?grass:walk);sw.position.set(cx,.15,cz);ch.grp.add(sw);
        if(kind==='plaza'){const fb=new T.Mesh(cy(T,5,5.4,1,20),stone);fb.position.set(cx,.6,cz);ch.grp.add(fb);ink(fb,.08);const fw=new T.Mesh(cy(T,4.4,4.4,.2,20),pool);fw.position.set(cx,1.12,cz);ch.grp.add(fw);const fc=new T.Mesh(cy(T,.5,.7,3.4,10),stone);fc.position.set(cx,2.6,cz);ch.grp.add(fc);const fbw=new T.Mesh(cy(T,1.8,.6,.6,14),stone);fbw.position.set(cx,4.4,cz);ch.grp.add(fbw);ink(fbw,.06);const tb={x0:cx-5,x1:cx+5,z0:cz-5,z1:cz+5,h:1.2,tree:1,chunk:ch};ch.boxes.push(tb);boxes.push(tb);
          for(let k=0;k<4;k++){const a=k*Math.PI/2+.4,bx2=cx+Math.cos(a)*10,bz2=cz+Math.sin(a)*10;const bn=new T.Mesh(bx(T,3,.5,1),trunk);bn.position.set(bx2,.8,bz2);bn.rotation.y=-a;ch.grp.add(bn)}for(let k=0;k<4;k++){const tx=cx+(k%2?1:-1)*(blk/2-3),tz=cz+(k<2?1:-1)*(blk/2-3);const tr=new T.Mesh(treeG,trunk);tr.position.set(tx,1.3,tz);ch.grp.add(tr);const lf=new T.Mesh(leafG,leaf);lf.position.set(tx,3.4,tz);ch.grp.add(lf);const t2={x0:tx-.4,x1:tx+.4,z0:tz-.4,z1:tz+.4,h:2.2,tree:1,chunk:ch};ch.boxes.push(t2);boxes.push(t2)}continue}
        if(kind==='stadium'){const fl=new T.Mesh(bx(T,blk-10,.2,blk-10),fieldM);fl.position.set(cx,.32,cz);ch.grp.add(fl);const ln=new T.Mesh(bx(T,.3,.22,blk-12),lineM);ln.position.set(cx,.35,cz);ch.grp.add(ln);const cc=new T.Mesh(new T.RingGeometry(2.4,2.8,24),lineM);cc.rotation.x=-Math.PI/2;cc.position.set(cx,.44,cz);ch.grp.add(cc);
          const q=blk-2,sh=7+hr(i,j,5)*4;addB(ch,cx,cz-q/2+2,q,4,sh,0xd8d4e4,1);addB(ch,cx,cz+q/2-2,q,4,sh,0xd8d4e4,1);addB(ch,cx-q/2+2,cz,4,q-8,sh*.8,0xF2352A,1);addB(ch,cx+q/2-2,cz,4,q-8,sh*.8,0xF2352A,1);[[-1,-1],[1,-1],[-1,1],[1,1]].forEach(([a2,b3])=>{const pl=new T.Mesh(cy(T,.3,.3,sh+10,6),ledge);pl.position.set(cx+a2*(q/2-1),(sh+10)/2,cz+b3*(q/2-1));ch.grp.add(pl);const lt=new T.Mesh(bx(T,2.4,1.2,.4),lineM);lt.position.set(cx+a2*(q/2-1),sh+10,cz+b3*(q/2-1));ch.grp.add(lt)});continue}
        if(kind==='park'){for(let k=0;k<6;k++){const tx=cx+(hr(i,j,10+k)-.5)*(blk-6),tz=cz+(hr(i,j,20+k)-.5)*(blk-6);const tr=new T.Mesh(treeG,trunk);tr.position.set(tx,1.3,tz);ch.grp.add(tr);const lf=new T.Mesh(leafG,leaf);lf.position.set(tx,3.4,tz);ch.grp.add(lf);ink(lf,.1);const tb={x0:tx-.4,x1:tx+.4,z0:tz-.4,z1:tz+.4,h:2.2,tree:1,chunk:ch};ch.boxes.push(tb);boxes.push(tb)}continue}
        const down=.5+.5*Math.sin(i*.37+seed)*Math.cos(j*.31-seed*.5);const hmul=o.hmul||1;const r=hr(i,j,2),lots=r<.4?1:r<.7?2:4;let q2=3;const mkH=()=>Math.round((12+hr(i,j,q2++)*26+down*40)*hmul);const col=()=>PAL[(hr(i,j,q2++)*PAL.length)|0];
        if(lots===1){const sp2=hr(i,j,77)<.12;const bb=addB(ch,cx,cz,blk-2,blk-2,Math.round(mkH()*(sp2?2.1:1)),col(),sp2?1:hr(i,j,40));if(sp2){const an=new T.Mesh(cy(T,.25,.6,14,6),ledge);an.position.set(cx,bb.h+7.6,cz);ch.grp.add(an);bb.extras.push(an);const tp=new T.Mesh(bx(T,(blk-2)*.6,5,(blk-2)*.6),sideM(0xFFD23F,2,1));tp.position.set(cx,bb.h+2.5,cz);ch.grp.add(tp);ink(tp,.1);bb.extras.push(tp)}}else if(lots===2){const q=(blk-3)/2;const ax=hr(i,j,41)<.5;[-1,1].forEach(s=>ax?addB(ch,cx+s*(q/2+.5),cz,q,blk-2,mkH(),col(),hr(i,j,42+s)):addB(ch,cx,cz+s*(q/2+.5),blk-2,q,mkH(),col(),hr(i,j,44+s)))}else{const q=(blk-3)/2;[[-1,-1],[1,-1],[-1,1],[1,1]].forEach(([a2,b3],k)=>addB(ch,cx+a2*(q/2+.5),cz+b3*(q/2+.5),q,q,mkH(),col(),hr(i,j,50+k)))}}
      if(water){for(let a=0;a<C;a++){const k=ci*C+a;if(o.canal(k)){const wm=new T.Mesh(new T.PlaneGeometry(st-2,C*cell),water);wm.rotation.x=-Math.PI/2;wm.position.set(k*cell,.08,(cj*C+C/2)*cell);ch.grp.add(wm)}const k2=cj*C+a;if(o.canal(k2)){const wm=new T.Mesh(new T.PlaneGeometry(C*cell,st-2),water);wm.rotation.x=-Math.PI/2;wm.position.set((ci*C+C/2)*cell,.085,k2*cell);ch.grp.add(wm)}}}
      return ch}
    function drop(key,ch){root.remove(ch.grp);ch.boxes.forEach(b=>{const i=boxes.indexOf(b);if(i>=0)boxes.splice(i,1)});ch.grp.traverse(m=>{if(m.isMesh&&m.geometry&&m.geometry!==slabG&&m.geometry!==treeG&&m.geometry!==leafG&&!m.userData.ink)m.geometry.dispose()});chunks.delete(key)}
    const api={boxes,cell,st,blk,C,R,root,gnd,
      update(px,pz,all){const ci=Math.floor(px/(C*cell)),cj=Math.floor(pz/(C*cell));let made=0;for(let rr=0;rr<=R;rr++)for(let a=-rr;a<=rr;a++)for(let b2=-rr;b2<=rr;b2++){if(Math.max(Math.abs(a),Math.abs(b2))!==rr)continue;const key=(ci+a)+','+(cj+b2);if(!chunks.has(key)){if(!all&&made>=2)continue;chunks.set(key,build(ci+a,cj+b2));made++}}
        for(const[key,ch]of chunks){if(ch.pins>0)continue;if(Math.max(Math.abs(ch.ci-ci),Math.abs(ch.cj-cj))>R+1)drop(key,ch)}
        gnd.position.set((Math.floor(px/cell)+.5)*cell,0,(Math.floor(pz/cell)+.5)*cell)},
      node(i,j){return{x:i*cell,z:j*cell}},nearNode(x,z){return{i:Math.round(x/cell),j:Math.round(z/cell)}},
      streetPt(cx,cz,rmin,rmax){for(let t=0;t<40;t++){const a=Math.random()*6.283,r=rmin+Math.random()*(rmax-rmin);let x=cx+Math.cos(a)*r,z=cz+Math.sin(a)*r;if(Math.random()<.5)x=Math.round(x/cell)*cell+(Math.random()-.5)*(st-5);else z=Math.round(z/cell)*cell+(Math.random()-.5)*(st-5);if(!inBox(x,1,z,boxes,1)&&!(o.canal&&api.canalAt(x,z)))return{x,z}}return{x:Math.round(cx/cell)*cell,z:cz}},
      inBlock(x,z){const lx=((x%cell)+cell)%cell,lz=((z%cell)+cell)%cell;return lx>st/2-1&&lx<cell-st/2+1&&lz>st/2-1&&lz<cell-st/2+1&&kindOf(Math.floor(x/cell),Math.floor(z/cell))!=='void'},
      canalAt(x,z){if(!o.canal)return false;const w=(st-2)/2;const kx=Math.round(x/cell),kz=Math.round(z/cell);return(o.canal(kx)&&Math.abs(x-kx*cell)<w)||(o.canal(kz)&&Math.abs(z-kz*cell)<w)},
      pin(b){if(b&&b.chunk)b.chunk.pins++},unpin(b){if(b&&b.chunk)b.chunk.pins=Math.max(0,b.chunk.pins-1)}};
    CITIES.push({grp:root,boxes});return api}
  /* ---- extra touch button ---- */
  function touchBtn(label,key,pos){const b=el('button',{type:'button',class:'tbtn',style:'background:rgba(255,159,67,.8);width:62px;height:62px;'+(pos||'left:auto;right:170px;bottom:120px')},label);const tc=wrap.querySelector('.tctl');if(tc)tc.append(b);const on=e=>{e.preventDefault();e.stopPropagation();input[key]=true},off=()=>{input[key]=false};c.on(b,'pointerdown',on);['pointerup','pointercancel','pointerleave'].forEach(ev=>c.on(b,ev,off));return b}
  /* ---- on-screen target pointer ---- */
  function pointer(){const arrow=el('div',{class:'cx-arrow'},el('i'),el('span'));hud.append(arrow);arrow.style.display='none';return(tg,label)=>{if(!tg){arrow.style.display='none';return}arrow.style.display='';const W2=wrap.clientWidth,H2=wrap.clientHeight;const v=tg.clone().project(camera);let sx=(v.x+1)/2*W2,sy=(1-v.y)/2*H2;const behind=v.z>1;const on=!behind&&sx>30&&sx<W2-30&&sy>40&&sy<H2-40;arrow.lastChild.textContent=label||'';
    if(on){arrow.style.left=sx+'px';arrow.style.top=(sy-40)+'px';arrow.firstChild.style.transform='rotate(180deg)'}else{let dx=sx-W2/2,dy=sy-H2/2;if(behind){dx=-dx;dy=-dy}const a=Math.atan2(dy,dx);const r=Math.min(W2/2-50,H2/2-50);arrow.style.left=(W2/2+Math.cos(a)*r)+'px';arrow.style.top=(H2/2+Math.sin(a)*r)+'px';arrow.firstChild.style.transform='rotate('+(a+Math.PI/2)+'rad)'}}}
  /* push a point out of boxes (xz), feet y; returns hit box or null */
  function push(p,r,boxes,y,topPad){let hit=null;for(const b of boxes){if(y!=null&&y>=b.h-(topPad||0))continue;if(p.x>b.x0-r&&p.x<b.x1+r&&p.z>b.z0-r&&p.z<b.z1+r){const dl=p.x-(b.x0-r),dr=b.x1+r-p.x,dn=p.z-(b.z0-r),df=b.z1+r-p.z;const m=Math.min(dl,dr,dn,df);if(m===dl){p.x=b.x0-r;p.nx=-1;p.nz=0}else if(m===dr){p.x=b.x1+r;p.nx=1;p.nz=0}else if(m===dn){p.z=b.z0-r;p.nx=0;p.nz=-1}else{p.z=b.z1+r;p.nx=0;p.nz=1}hit=b}}return hit}
  function inBox(x,y,z,boxes,pad){for(const b of boxes)if(y<b.h+(pad||0)&&x>b.x0-(pad||0)&&x<b.x1+(pad||0)&&z>b.z0-(pad||0)&&z<b.z1+(pad||0))return b;return null}
  /* ---- camera orbit ---- */
  const cam={yaw:0,pitch:-.22,dist:cfg.camDist||6.5,h:cfg.camH||1.8,shake:0,pmin:-1.2,pmax:.55,boxes:null,cur:null};
  cam.look=(sens)=>{cam.yaw-=input.mdx*.0032*(sens||1);cam.pitch=clamp(cam.pitch-input.mdy*.0026*(sens||1),cam.pmin,cam.pmax)};
  cam.place=(tgt,dt,dist,h,lerp)=>{const D=dist||cam.dist,H=h==null?cam.h:h;const cp=Math.cos(cam.pitch);const want=new T.Vector3(tgt.x+Math.sin(cam.yaw)*cp*D,tgt.y+H-Math.sin(cam.pitch)*D,tgt.z+Math.cos(cam.yaw)*cp*D);
    if(cam.boxes){const f=new T.Vector3(tgt.x,tgt.y+H,tgt.z);let best=1;for(let k=1;k<=8;k++){const q=k/8;const x=f.x+(want.x-f.x)*q,y=f.y+(want.y-f.y)*q,z=f.z+(want.z-f.z)*q;if(inBox(x,y,z,cam.boxes,.4)||(cam.solid&&cam.solid(x,y,z))){best=Math.max(.12,(k-1)/8);break}}want.lerpVectors(f,want,best)}
    if(want.y<.4)want.y=.4;if(!cam.cur||!lerp)cam.cur=want.clone();else cam.cur.lerp(want,Math.min(1,dt*lerp));camera.position.copy(cam.cur);
    if(cam.shake>0){cam.shake=Math.max(0,cam.shake-dt*2.2);const s=cam.shake*.5;camera.position.x+=(Math.random()-.5)*s;camera.position.y+=(Math.random()-.5)*s;camera.position.z+=(Math.random()-.5)*s}
    camera.lookAt(tgt.x,tgt.y+H*.8,tgt.z)};
  cam.fwd=()=>new T.Vector3(-Math.sin(cam.yaw),0,-Math.cos(cam.yaw));
  cam.dir3=()=>new T.Vector3(-Math.sin(cam.yaw)*Math.cos(cam.pitch),Math.sin(cam.pitch),-Math.cos(cam.yaw)*Math.cos(cam.pitch));
  /* move vector (camera-relative) from keys/joystick */
  const moveIn=()=>{const K=input.keys;let f=(K.w||K.arrowup?1:0)-(K.s||K.arrowdown?1:0),r=(K.d||K.arrowright?1:0)-(K.a||K.arrowleft?1:0);if(input.joy.x||input.joy.y){r+=input.joy.x;f-=input.joy.y}const m=Math.min(1,Math.hypot(f,r));if(m<.08)return{x:0,z:0,m:0,f:0,r:0};const fw=cam.fwd(),rt=new T.Vector3(-fw.z,0,fw.x);const v=fw.multiplyScalar(f).add(rt.multiplyScalar(r)).normalize();return{x:v.x,z:v.z,m,f,r}};
  /* ---- building destruction ---- */
  const CITIES=[],chunks=[],falling=[],chunkG=new T.BoxGeometry(1,1,1),crackM=new T.MeshBasicMaterial({color:0x1D1A2F,transparent:true,opacity:.7,depthWrite:false,side:T.DoubleSide});
  function smash(b,pt,power,opt){if(!b||b.dead||b.tree||b.noSmash)return false;const vol=b.w*b.d*b.h;if(b.hp==null)b.hp=Math.max(40,vol/260);if(!b.bands){b.h0=b.h;b.nb=Math.max(1,Math.round(b.h/14));const per=b.hp*3/b.nb;b.bands=Array.from({length:b.nb},(_,k)=>per*(k===0?1.4:1)+40);b.band0=b.bands.slice()}b.hp-=power;const col=b.col||0x8c86a3;
    const dl=pt.x-b.x0,dr=b.x1-pt.x,dn=pt.z-b.z0,df=b.z1-pt.z,m=Math.min(dl,dr,dn,df);const nx=m===dl?-1:m===dr?1:0,nz=nx?0:(m===dn?-1:1);const fp=new T.Vector3(nx<0?b.x0:nx>0?b.x1:clamp(pt.x,b.x0,b.x1),clamp(pt.y,1,b.h-1),nz<0?b.z0:nz>0?b.z1:clamp(pt.z,b.z0,b.z1));
    const n=Math.min(22,5+(power/6|0));for(let i=0;i<n;i++){const c2=new T.Mesh(chunkG,TM(Math.random()<.3?0x1D1A2F:col));const s2=.4+Math.random()*(1+power/60);c2.scale.set(s2,s2*(.5+Math.random()),s2);c2.position.copy(fp).add(new T.Vector3(nx*.5+(Math.random()-.5)*2,(Math.random()-.5)*2,nz*.5+(Math.random()-.5)*2));scene.add(c2);chunks.push({m:c2,v:new T.Vector3(nx*(6+Math.random()*14)+(Math.random()-.5)*8,3+Math.random()*10,nz*(6+Math.random()*14)+(Math.random()-.5)*8),r:new T.Vector3(Math.random()*6,Math.random()*6,Math.random()*6),l:4+Math.random()*2})}
    for(let i=0;i<6;i++)puff(fp.clone().add(new T.Vector3((Math.random()-.5)*3,(Math.random()-.5)*3,(Math.random()-.5)*3)),0xd8d4e4,1.2+Math.random()*1.5,1.2,new T.Vector3(nx*2,1,nz*2));
    const cs=Math.min(9,2+power/12);const cr=new T.Mesh(new T.CircleGeometry(cs,7),crackM);cr.position.copy(fp).add(new T.Vector3(nx*.08,0,nz*.08));cr.rotation.y=nx?Math.PI/2:0;cr.rotation.z=Math.random()*6;cr.scale.set(1,.7+Math.random()*.5,1);scene.add(cr);(b.cracks=b.cracks||[]).push(cr);
    const bh=b.h0/b.nb;const bk=Math.min(b.bands.length-1,Math.max(0,Math.floor(fp.y/bh)));b.bands[bk]-=power;if(b.bands[bk]<b.band0[bk]*.6&&!crumbling.some(q=>q.b===b&&q.k===bk)){crumbling.push({b,k:bk,y0:bk*bh,y1:Math.min(b.h,(bk+1)*bh)});if(crumbling.length>24)crumbling.shift()}if(b.bands[bk]>0&&bk===0)b.hp=Math.max(b.hp,1);
    if(b.bands[bk]<=0&&bk>0){breakTop(b,bk*bh,fp);b.bands.length=bk;noise(1,'lowpass',120,.45);return 'top'}
    if(b.bands[0]<=0||b.bands.length===1&&b.hp<=0){b.dead=true;CITIES.forEach(C=>{const i=C.boxes.indexOf(b);if(i>=0)C.boxes.splice(i,1)});shatter(b,0,b.h,fp);[b.m,...b.extras,...(b.cracks||[])].forEach(o=>o.parent&&o.parent.remove(o));noise(3,'lowpass',80,.5);H.pow('KRA-KOOOM!',new T.Vector3(b.cx,b.h*.6,b.cz),'#FFD23F');ring(new T.Vector3(b.cx,.4,b.cz),0xd8d4e4,Math.max(b.w,b.d)*.5,Math.max(b.w,b.d)*2,1.2);noise(1.4,'lowpass',160,.5);cam.shake=Math.max(cam.shake,1.2);if(opt&&opt.onCollapse)opt.onCollapse(b);return 'collapse'}
    noise(.35,'lowpass',300+Math.random()*200,.3);return 'hit'}
  const tops=[];
  function cropUV(g,v0,v1){const uv=g.attributes.uv,nm=g.attributes.normal;for(let i=0;i<uv.count;i++){if(Math.abs(nm.getY(i))>.5)continue;uv.setY(i,v0+uv.getY(i)*(v1-v0))}uv.needsUpdate=true}
  function reInk(m){m.children.filter(o=>o.userData.ink).forEach(o=>m.remove(o));ink(m,.18)}
  function breakTop(b,hNew,fp){const hOld=b.h,hTop=hOld-hNew;if(hTop<2||!b.m)return;const f0=hNew/(b.h0||hOld),f1=hOld/(b.h0||hOld);
    const g=new T.BoxGeometry(b.w,hNew,b.d);cropUV(g,0,f0);const old=b.m.geometry;b.m.geometry=g;b.m.position.y-=hTop/2;reInk(b.m);
    b.extras.forEach(e=>e.position.y-=hTop);(b.cracks||[]).forEach(cr=>{if(cr.position.y>hNew){cr.parent&&cr.parent.remove(cr)}});b.cracks=(b.cracks||[]).filter(cr=>cr.position.y<=hNew);b.h=hNew;
    shatter(b,hNew,hOld,fp,f0,f1);
    for(let i=0;i<10;i++)puff(new T.Vector3(b.x0+Math.random()*b.w,hNew,b.z0+Math.random()*b.d),0xd8d4e4,2+Math.random()*2,1.6,new T.Vector3((Math.random()-.5)*3,1,(Math.random()-.5)*3));H.pow(pick(['CRRRACK!','SNAP!','TIMBERRR!']),new T.Vector3(b.cx,hNew+4,b.cz),'#FFD23F');cam.shake=Math.max(cam.shake,.8)}
  const frags=[],crumbling=[];
  function fragUV(g,v0,v1,ux0,ux1,uz0,uz1){const uv=g.attributes.uv,nm=g.attributes.normal;for(let i=0;i<uv.count;i++){if(Math.abs(nm.getY(i))>.5)continue;uv.setY(i,v0+uv.getY(i)*(v1-v0));const ax=Math.abs(nm.getX(i))>.5;const a=ax?uz0:ux0,b2=ax?uz1:ux1;uv.setX(i,a+uv.getX(i)*(b2-a))}uv.needsUpdate=true}
  function shatter(b,y0,y1,fp,f0,f1){const H0=b.h0||y1;const hgt=y1-y0;if(hgt<1)return;const nx=clamp(Math.round(b.w/9),2,3),nz=clamp(Math.round(b.d/9),2,3),ny=clamp(Math.round(hgt/9),2,8);const fw=b.w/nx,fd=b.d/nz,fh=hgt/ny;const mat=b.m.material;const wp=new T.Vector3();b.m.getWorldPosition(wp);
    let dx=b.cx-fp.x,dz=b.cz-fp.z;const L=Math.hypot(dx,dz)||1;dx/=L;dz/=L;const lean=.35+Math.random()*.4;
    for(let iy=0;iy<ny;iy++)for(let ix=0;ix<nx;ix++)for(let iz=0;iz<nz;iz++){if(frags.length>260)break;const g=new T.BoxGeometry(fw*.98,fh*.98,fd*.98);const vy0=(y0+iy*fh)/H0,vy1=(y0+(iy+1)*fh)/H0;fragUV(g,vy0,vy1,ix/nx,(ix+1)/nx,iz/nz,(iz+1)/nz);const m=new T.Mesh(g,mat);m.position.set(b.x0+(ix+.5)*fw,y0+(iy+.5)*fh,b.z0+(iz+.5)*fd);scene.add(m);
      const up=iy/ny;frags.push({m,v:new T.Vector3((ix-(nx-1)/2)*.8+dx*lean*(1+iy*.6),0,(iz-(nz-1)/2)*.8+dz*lean*(1+iy*.6)),w:new T.Vector3((Math.random()-.5)*.8+dz*lean*.5,(Math.random()-.5)*.4,(Math.random()-.5)*.8-dx*lean*.5),delay:iy*.1+Math.random()*.12+(y0>0?0:.05),col:b.col||0x8c86a3,s:Math.max(fw,fd,fh),t:0,cx:b.cx,cz:b.cz})}
    const R=Math.max(b.w,b.d);for(let k=0;k<Math.min(16,6+ny*2);k++)puff(new T.Vector3(b.cx+(Math.random()-.5)*R*1.4,y0+Math.random()*Math.min(hgt,20),b.cz+(Math.random()-.5)*R*1.4),0xcfc8bc,4+Math.random()*5,3+Math.random()*1.5,new T.Vector3((Math.random()-.5)*5,1.5,(Math.random()-.5)*5))}
  function tickFrags(dt){for(let i=frags.length-1;i>=0;i--){const f=frags[i],m=f.m;f.t+=dt;if(f.t<f.delay){m.position.x+=(Math.random()-.5)*.12;continue}f.v.y-=24*dt;m.position.addScaledVector(f.v,dt);m.rotation.x+=f.w.x*dt;m.rotation.y+=f.w.y*dt;m.rotation.z+=f.w.z*dt;if(Math.random()<dt*2.5)puff(m.position.clone(),0xd8d0c4,1.5+Math.random()*2,1.4);if(Math.random()<dt*4){const c2=new T.Mesh(chunkG,TM(Math.random()<.4?0x5A5470:f.col));const s2=.4+Math.random()*.9;c2.scale.set(s2,s2*.7,s2);c2.position.copy(m.position);scene.add(c2);chunks.push({m:c2,v:new T.Vector3((Math.random()-.5)*8,Math.random()*3,(Math.random()-.5)*8),r:new T.Vector3(Math.random()*6,Math.random()*6,Math.random()*6),l:2.5+Math.random()})}
      const floor=Math.min(f.s*.5,4)+(Math.hypot(m.position.x-f.cx,m.position.z-f.cz)<8?2:0);if(m.position.y<=floor){const p=m.position.clone();for(let k=0;k<5;k++){const c2=new T.Mesh(chunkG,TM(Math.random()<.35?0x1D1A2F:f.col));const s2=.8+Math.random()*1.8;c2.scale.set(s2,s2*.7,s2);c2.position.copy(p).add(new T.Vector3((Math.random()-.5)*f.s,Math.random()*2,(Math.random()-.5)*f.s));scene.add(c2);chunks.push({m:c2,v:new T.Vector3((Math.random()-.5)*12+f.v.x,3+Math.random()*7,(Math.random()-.5)*12+f.v.z),r:new T.Vector3(Math.random()*6,Math.random()*6,Math.random()*6),l:3+Math.random()*2})}
        if(Math.random()<.5){const r=new T.Mesh(chunkG,TM(Math.random()<.5?f.col:0x8c86a3));const s2=2+Math.random()*3;r.scale.set(s2*1.3,s2*.55,s2);r.position.set(p.x,s2*.22,p.z);r.rotation.set((Math.random()-.5)*.3,Math.random()*6,(Math.random()-.5)*.3);scene.add(r);ink(r,.08);rubble.push(r);if(rubble.length>220)scene.remove(rubble.shift())}
        puff(p.clone().setY(1.5),0xcfc8bc,3+Math.random()*3,2.4,new T.Vector3((Math.random()-.5)*4,1,(Math.random()-.5)*4));if(Math.random()<.25){noise(.4,'lowpass',120+Math.random()*80,.25);cam.shake=Math.max(cam.shake,.5)}if(K0.onRubble&&Math.random()<.3)K0.onRubble(p,f.s);m.geometry.dispose();scene.remove(m);frags.splice(i,1)}}
    for(const q of crumbling){if(q.b.dead||q.b.h<q.y0+1)continue;if(Math.random()<dt*1.6){const b=q.b;const s=Math.random()*4|0;const y=q.y0+Math.random()*(Math.min(q.y1,b.h)-q.y0);const p=s===0?new T.Vector3(b.x0-.3,y,b.z0+Math.random()*b.d):s===1?new T.Vector3(b.x1+.3,y,b.z0+Math.random()*b.d):s===2?new T.Vector3(b.x0+Math.random()*b.w,y,b.z0-.3):new T.Vector3(b.x0+Math.random()*b.w,y,b.z1+.3);const c2=new T.Mesh(chunkG,TM(Math.random()<.3?0x5A5470:b.col||0x8c86a3));const s2=.3+Math.random()*.8;c2.scale.set(s2,s2,s2);c2.position.copy(p);scene.add(c2);chunks.push({m:c2,v:new T.Vector3((Math.random()-.5)*2,0,(Math.random()-.5)*2),r:new T.Vector3(Math.random()*4,Math.random()*4,Math.random()*4),l:4});if(Math.random()<.4)puff(p,0xd8d0c4,1.2+Math.random(),1.5,new T.Vector3(0,-1,0))}}}
  const rubble=[];
  function tickTops(dt){tickFrags(dt);for(let i=tops.length-1;i>=0;i--){const t=tops[i],m=t.m;t.v.y-=22*dt;m.position.addScaledVector(t.v,dt);m.rotation.x+=t.w.x*dt;m.rotation.y+=t.w.y*dt;m.rotation.z+=t.w.z*dt;t.w.multiplyScalar(1+dt*.6);
      CITIES.forEach(C=>C.boxes.forEach(ob=>{if(t.hit.has(ob)||ob.tree||ob.dead)return;const cx=clamp(m.position.x,ob.x0,ob.x1),cz=clamp(m.position.z,ob.z0,ob.z1);if(Math.hypot(cx-m.position.x,cz-m.position.z)<t.r&&m.position.y-t.hT*.3<ob.h){t.hit.add(ob);smash(ob,new T.Vector3(cx,Math.min(ob.h-1,m.position.y),cz),80+Math.abs(t.v.y)*6);t.v.multiplyScalar(.55)}}));
      if(m.position.y<Math.max(1.5,t.hT*.28)){const p=m.position.clone();for(let k=0;k<Math.min(22,6+t.hT);k++){const c2=new T.Mesh(chunkG,TM(Math.random()<.3?0x1D1A2F:t.col));const s2=.8+Math.random()*2.6;c2.scale.set(s2,s2*.7,s2);c2.position.copy(p).add(new T.Vector3((Math.random()-.5)*t.r*2,Math.random()*3,(Math.random()-.5)*t.r*2));scene.add(c2);chunks.push({m:c2,v:new T.Vector3((Math.random()-.5)*16,4+Math.random()*10,(Math.random()-.5)*16),r:new T.Vector3(Math.random()*6,Math.random()*6,Math.random()*6),l:4+Math.random()*2})}
        for(let k=0;k<5;k++){const r=new T.Mesh(chunkG,TM(k%3?t.col:0x5A5470));const s2=2+Math.random()*3;r.scale.set(s2*1.4,s2*.6,s2);r.position.set(p.x+(Math.random()-.5)*t.r*1.6,s2*.25,p.z+(Math.random()-.5)*t.r*1.6);r.rotation.y=Math.random()*6;scene.add(r);ink(r,.1)}
        for(let k=0;k<8;k++)puff(p.clone().add(new T.Vector3((Math.random()-.5)*t.r*2,1+Math.random()*3,(Math.random()-.5)*t.r*2)),0xd8d4e4,3+Math.random()*3,2,new T.Vector3((Math.random()-.5)*5,2,(Math.random()-.5)*5));ring(new T.Vector3(p.x,.4,p.z),0xd8d4e4,t.r,t.r*3,1);H.pow('KA-THOOM!',p.clone().setY(4),'#FF9F43');noise(1.2,'lowpass',110,.5);cam.shake=Math.max(cam.shake,1.2);
        scene.remove(m);tops.splice(i,1);if(K0.onRubble)K0.onRubble(p,t.r)}}}
  function smashTick(dt){tickTops(dt);for(let i=chunks.length-1;i>=0;i--){const c2=chunks[i];c2.l-=dt;c2.v.y-=25*dt;c2.m.position.addScaledVector(c2.v,dt);c2.m.rotation.x+=c2.r.x*dt;c2.m.rotation.y+=c2.r.y*dt;if(c2.m.position.y<.2){c2.m.position.y=.2;c2.v.y*=-.3;c2.v.x*=.6;c2.v.z*=.6;c2.r.multiplyScalar(.5)}if(c2.l<1)c2.m.scale.multiplyScalar(Math.pow(.05,dt));if(c2.l<=0){scene.remove(c2.m);chunks.splice(i,1)}}
    for(let i=falling.length-1;i>=0;i--){const f=falling[i],b=f.b;f.t+=dt;const drop=Math.min(b.h+2,f.t*f.t*b.h*.35);const objs=[b.m,...b.extras,...(b.cracks||[])];objs.forEach(o=>{if(o.userData.y0==null)o.userData.y0=o.position.y;o.position.y=o.userData.y0-drop;o.position.x+=(Math.random()-.5)*.25});b.m.rotation.z=f.tilt*Math.min(1,f.t);
      if(Math.random()<.6)puff(new T.Vector3(b.cx+(Math.random()-.5)*b.w,1+Math.random()*3,b.cz+(Math.random()-.5)*b.d),0xd8d4e4,2+Math.random()*2.5,1.6,new T.Vector3((Math.random()-.5)*4,2,(Math.random()-.5)*4));
      if(drop>=b.h+2){objs.forEach(o=>o.parent&&o.parent.remove(o));for(let k=0;k<7;k++){const r=new T.Mesh(chunkG,TM(k%3?b.col:0x5A5470));const s2=2+Math.random()*4;r.scale.set(s2*1.4,s2*.6,s2);r.position.set(b.cx+(Math.random()-.5)*b.w*.8,s2*.25,b.cz+(Math.random()-.5)*b.d*.8);r.rotation.y=Math.random()*6;scene.add(r);ink(r,.1)}falling.splice(i,1)}}}
  /* ---- fx ---- */
  const fx=[];const pg=new T.BoxGeometry(1,1,1),sg=new T.IcosahedronGeometry(1,0);
  function burst(p,cols,n,spd,size,life,grav,shape){for(let i=0;i<(n||12);i++){const m=new T.Mesh(shape==='s'?sg:pg,new T.MeshBasicMaterial({color:pick(cols),transparent:true}));m.position.copy(p);const s=(size||.25)*(.6+Math.random()*.8);m.scale.setScalar(s);scene.add(m);const v=new T.Vector3(Math.random()-.5,Math.random()*.9-.2,Math.random()-.5).normalize().multiplyScalar((spd||8)*(.4+Math.random()*.8));fx.push({m,v,l:(life||.7)*(.6+Math.random()*.6),L:life||.7,g:grav==null?14:grav,s,spin:1})}}
  function puff(p,col,size,life,v){const m=new T.Mesh(sg,new T.MeshBasicMaterial({color:col,transparent:true,opacity:.8}));m.position.copy(p);m.scale.setScalar(size||1);scene.add(m);fx.push({m,v:v||new T.Vector3(0,1,0),l:life||.6,L:life||.6,g:0,s:size||1,grow:1})}
  function ring(p,col,r0,r1,life,y){const m=new T.Mesh(new T.RingGeometry(.8,1,40),new T.MeshBasicMaterial({color:col,transparent:true,side:T.DoubleSide,depthWrite:false}));m.rotation.x=-Math.PI/2;m.position.copy(p);if(y!=null)m.position.y=y;scene.add(m);fx.push({m,ring:1,r0,r1,l:life||.5,L:life||.5})}
  function fxTick(dt){smashTick(dt);for(let i=fx.length-1;i>=0;i--){const f=fx[i];f.l-=dt;const k=Math.max(0,f.l/f.L);if(f.ring){const r=f.r1+(f.r0-f.r1)*k;f.m.scale.setScalar(r);f.m.material.opacity=k}else if(f.grow){f.m.position.addScaledVector(f.v,dt);f.m.scale.setScalar(f.s*(1+(1-k)*1.5));f.m.material.opacity=.8*k}else{f.v.y-=f.g*dt;f.m.position.addScaledVector(f.v,dt);f.m.rotation.x+=dt*7;f.m.rotation.y+=dt*5;f.m.scale.setScalar(f.s*Math.max(.1,k));if(f.m.position.y<.05){f.m.position.y=.05;f.v.y*=-.4;f.v.x*=.7;f.v.z*=.7}}
    if(f.l<=0){scene.remove(f.m);f.m.material.dispose();if(f.ring)f.m.geometry.dispose();fx.splice(i,1)}}}
  function ribbon(col,n,w){const N=n||24;const pos=new Float32Array(N*2*3);const g=new T.BufferGeometry();g.setAttribute('position',new T.BufferAttribute(pos,3));const idx=[];for(let i=0;i<N-1;i++){const a=i*2;idx.push(a,a+1,a+2,a+1,a+3,a+2)}g.setIndex(idx);const m=new T.Mesh(g,new T.MeshBasicMaterial({color:col,transparent:true,opacity:.7,side:T.DoubleSide,depthWrite:false}));m.frustumCulled=false;scene.add(m);const pts=[];
    return{m,push(p,up,on){pts.unshift({x:p.x,y:p.y,z:p.z,ux:up.x,uy:up.y,uz:up.z});if(pts.length>N)pts.pop();for(let i=0;i<N;i++){const q=pts[Math.min(i,pts.length-1)];const k=(1-i/N)*(w||.4);pos.set([q.x+q.ux*k,q.y+q.uy*k,q.z+q.uz*k,q.x-q.ux*k,q.y-q.uy*k,q.z-q.uz*k],i*6)}g.attributes.position.needsUpdate=true;m.visible=!!on},clear(){pts.length=0;m.visible=false}}}
  /* ---- HUD ---- */
  const tint=el('div',{class:'cx-tint'}),lines=el('div',{class:'cx-lines'}),cap=el('div',{class:'cx-cap'}),bars=el('div',{class:'cx-bars'}),scoreEl=el('div',{class:'cx-score'}),sayEl=el('div',{class:'cx-say'}),bossEl=el('div',{class:'cx-boss'});bossEl.hidden=true;
  hud.append(tint,lines,cap,bars,scoreEl,sayEl,bossEl);let sayT=0,capS='',scS='',bossBar=null;
  const H={bar(label,col){const b=el('div',{class:'cx-bar',style:'--c:'+col},el('b'),el('span',null,label));bars.append(b);let lt=label;return(fr,txt)=>{b.firstChild.style.width=clamp(fr,0,1)*100+'%';if(txt!=null&&txt!==lt){lt=txt;b.lastChild.textContent=txt}b.classList.toggle('full',fr>=1)}},
    cap(k,t){const s=k+'|'+t;if(s===capS)return;capS=s;cap.innerHTML='';cap.append(el('small',null,k),t)},
    score(n,label){const s=n+'|'+label;if(s===scS)return;scS=s;scoreEl.innerHTML='';scoreEl.append(el('small',null,label||'score'),String(n))},
    say(t,ms){sayEl.textContent=t;sayEl.classList.add('on');sayT=ms||1600},
    lines(a){lines.style.opacity=clamp(a,0,1)},tint(col,a){if(col)tint.style.background=col;tint.style.opacity=clamp(a,0,1)},
    boss(name,fr){if(name==null){bossEl.hidden=true;return}if(bossEl.hidden||bossEl.dataset.n!==name){bossEl.hidden=false;bossEl.dataset.n=name;bossEl.innerHTML='';bossEl.append(el('span',null,name));const b=el('div',{class:'cx-bar',style:'--c:#F2352A'},el('b'),el('span'));bossEl.append(b);bossBar=b}bossBar.firstChild.style.width=clamp(fr,0,1)*100+'%'},
    pow(text,v3,col){const p=v3.clone().project(camera);if(p.z>1)return;const e=el('div',{class:'cx-pow',style:'left:'+((p.x+1)/2*100)+'%;top:'+((1-p.y)/2*100)+'%;--r:'+((Math.random()-.5)*24)+'deg'+(col?';color:'+col:'')},text);hud.append(e);setTimeout(()=>e.remove(),820)},
    tick(dt){sayT-=dt*1000;if(sayT<=0)sayEl.classList.remove('on')}};
  /* ---- radar ---- */
  function radar(range){const cv=el('canvas',{class:'cx-mini',width:140,height:140});hud.append(cv);const x=cv.getContext('2d');return(px,pz,yaw,dots,rects)=>{x.clearRect(0,0,140,140);x.save();x.beginPath();x.arc(70,70,66,0,7);x.clip();x.fillStyle='#FFFDF6';x.fillRect(0,0,140,140);x.translate(70,70);x.rotate(yaw);const s=66/range;
      if(rects){x.fillStyle='#d8d4e4';rects.forEach(b=>{if(Math.abs(b.cx-px)<range+20&&Math.abs(b.cz-pz)<range+20)x.fillRect((b.x0-px)*s,(b.z0-pz)*s,(b.x1-b.x0)*s,(b.z1-b.z0)*s)})}
      dots.forEach(d=>{let dx=(d.x-px)*s,dz=(d.z-pz)*s;const L=Math.hypot(dx,dz);if(L>60){dx*=60/L;dz*=60/L}x.fillStyle=d.col;x.strokeStyle='#1D1A2F';x.lineWidth=2;x.beginPath();x.arc(dx,dz,d.r||5,0,7);x.fill();x.stroke()});x.restore();
      x.fillStyle='#1D1A2F';x.beginPath();x.moveTo(70,62);x.lineTo(76,76);x.lineTo(70,72);x.lineTo(64,76);x.closePath();x.fill();x.lineWidth=4;x.strokeStyle='#1D1A2F';x.beginPath();x.arc(70,70,66,0,7);x.stroke()}}
  /* ---- flow ---- */
  const F={mi:Math.min(S.get(cfg.id+'_lv',0),cfg.issues-1),state:'menu',free:false};
  F.tag=mi=>mi<0?'Free roam':'Issue #'+(mi+1);
  const ov=(html,btns)=>{const o=st3.overlay(html,btns);o.classList.add('cx');return o};
  F.ov=ov;F.paused=()=>wrap.classList.contains('paused');
  F.brief=(M)=>{F.state='menu';F.free=false;const m=M[F.mi];ov('<small class="kick">Issue #'+(F.mi+1)+' of '+M.length+'</small><h2>'+m.name+'</h2>'+m.brief.map(p=>'<p>'+p+'</p>').join('')+(m.goal?'<p class="ctl"><b>Mission:</b> '+m.goal+'</p>':''),[['Go!',()=>{F.state='play';cfg.start(F.mi)},true]])};
  F.win=(M,score,stats,text)=>{if(F.state!=='play'||F.free)return;F.state='done';S.set(cfg.id+'_lv',Math.max(S.get(cfg.id+'_lv',0),Math.min(F.mi+1,M.length-1)));const b=c.best(score);[523,659,784,1046].forEach((f,i)=>c.after(()=>beep(f,.25,'triangle',.08),i*130));const last=F.mi>=M.length-1;
    c.after(()=>ov('<small class="kick">'+(last?'The end… for now':'Issue #'+(F.mi+1)+' complete')+'</small><h2>'+(last?cfg.finale:pick(['KA-POW!','WHAM! Done!','Hero time!','Nailed it!']))+'</h2><p>'+text+'</p><div class="stats3">'+stats.map(([v,l])=>'<span><b>'+v+'</b>'+l+'</span>').join('')+'</div><p class="ctl">Score '+score+' · Best '+b+'</p>',last?[['Play again from issue #1',()=>{F.mi=0;F.brief(M)},true],['Replay this issue',()=>F.brief(M)]]:[['Next issue →',()=>{F.mi++;F.brief(M)},true],['Replay',()=>F.brief(M)]]),1300)};
  F.lose=(M,title,text)=>{if(F.state!=='play')return;if(F.free){F.revive&&F.revive();H.say('Back on your feet!',1400);beep(660,.15,'triangle',.06);return}F.state='dead';sweep(400,90,.6,'sawtooth',.07);c.after(()=>ov('<small class="kick">Oh no!</small><h2>'+title+'</h2><p>'+text+'</p>',[['Try again',()=>F.brief(M),true]]),1100)};
  F.roam=k=>{F.free=true;F.state='play';H.say('Free roam: no missions, no time limits. Press P for the menu.',2600);cfg.start(-1-(k||0))};
  F.roamMenu=()=>{const L=cfg.roamLevels;if(!L)return F.roam(0);F.state='menu';ov('<small class="kick">Free roam</small><h2>Pick a place</h2><p>No missions, no time limits, no losing. Press P any time for the menu.</p>',L.map((n,k)=>[n,()=>F.roam(k),k===0]))};
  const ctlBox=el('div',{style:'position:absolute;right:10px;bottom:78px;max-width:270px;background:rgba(29,26,47,.66);color:#FFFDF6;font:600 10.5px/1.4 Figtree,sans-serif;padding:6px 9px;border-radius:7px;pointer-events:auto;cursor:pointer;z-index:3;user-select:none'});hud.append(ctlBox);let ctlOpen=S.get('ctl_open2',false),ctlLines=[];
  function paintCtl(){ctlBox.innerHTML=ctlOpen?'<div style="display:flex;justify-content:space-between;gap:10px"><b style="color:#FFD23F">🎮 Controls</b><span style="opacity:.75">✕ close (H)</span></div>'+ctlLines.map(l=>'<div>• '+l+'</div>').join(''):'<b style="color:#FFD23F">🎮 Controls</b> <span style="opacity:.75">▸ show (H)</span>'}
  function setCtl(html){const t=el('div',{html:html}).textContent.replace(/\(click the game to lock the mouse\)|\(click to lock\)/g,'').replace(/\s+/g,' ').trim();ctlLines=t.split(/(?<=\.)\s+(?=[A-Z0-9])/).map(x=>x.replace(/\.$/,'').trim()).filter(x=>x&&!/^On a phone/i.test(x));paintCtl()}
  ctlBox.addEventListener('pointerdown',e=>{e.stopPropagation();e.preventDefault();ctlOpen=!ctlOpen;S.set('ctl_open2',ctlOpen);paintCtl()});c.on(document,'keydown',e=>{if(e.key.toLowerCase()==='h'&&!e.repeat&&F.state==='play'){ctlOpen=!ctlOpen;S.set('ctl_open2',ctlOpen);paintCtl()}});
  F.intro=(...a)=>{F._intro=a;F.free=false;F.state='menu';const [M,title,tag,cover,ctl]=a;if(ctl)setCtl(ctl);return ov('<small class="kick">'+tag+'</small><h2>'+title+'</h2>'+cover+'<p class="ctl"><b>Controls:</b> '+ctl+'</p>',[[F.mi>0?'Continue at issue #'+(F.mi+1):'Start',()=>F.brief(M),true]].concat(F.mi>0?[['Start over',()=>{F.mi=0;F.brief(M)}]]:[]).concat([['Free roam',()=>F.roamMenu()]]))};
  const pauseBtns=()=>[['Resume',null,true]].concat([[F.free?'Leave free roam':'Quit to menu',()=>{F.free=false;F.state='menu';H.boss&&H.boss(null);F.intro(...F._intro)}]]);
  c.on(document,'pointerlockchange',()=>{if(!document.pointerLockElement&&F.state==='play'&&!wrap.querySelector('.ov3')&&!input.touch)ov('<small class="kick">Paused</small><h2>Taking a breather</h2><p>Click Resume, then click the game to steer with the mouse again.</p>',pauseBtns())});
  c.on(document,'keydown',e=>{if((e.key==='p'||e.key==='P')&&F.state==='play'&&!wrap.querySelector('.ov3'))ov('<small class="kick">Paused</small><h2>Taking a breather</h2>',pauseBtns())});
  // ---- instanced ambient city life: thousands of pedestrians & vehicles in a handful of draw calls ----
  function crowd(o){const lite=window.matchMedia&&matchMedia('(pointer:coarse)').matches;const nP=Math.round((o.people||800)*(lite?.45:1)),nC=Math.round((o.cars||400)*(lite?.5:1)),snap=o.snap,walkOff=o.walkOff,lane=o.lane||3,R=o.radius||240;
    const box=new T.BoxGeometry(1,1,1);const im=n=>{const m=new T.InstancedMesh(box,new T.MeshLambertMaterial({color:0xffffff}),n);m.instanceMatrix.setUsage(T.DynamicDrawUsage);m.frustumCulled=false;m.castShadow=false;m.receiveShadow=false;scene.add(m);return m};
    const pLeg=im(nP),pBody=im(nP),pHead=im(nP),cBody=im(nC),cCab=im(nC),cWheel=im(nC);
    const C=h=>new T.Color(h),SK=[0xf1c9a5,0xd9a47a,0xa8714a,0x6b4a33,0xffe0bd].map(C),SH=[0xF2352A,0x2BB673,0x7FC8F8,0xFF8FB1,0xB9A7FF,0xFF9F43,0xFFD23F,0xffffff,0x2d6fd6,0x1D1A2F,0x6EE7B7,0xe0a458].map(C),PA=[0x2b2b40,0x3a4a7a,0x5A5470,0x6b4a33,0x1D1A2F,0x8c86a3].map(C);
    const CARC=[0x7FC8F8,0xFF8FB1,0x6EE7B7,0xB9A7FF,0xffffff,0xFF9F43,0x2d6fd6,0xF2352A,0x8c86a3,0x1D1A2F].map(C),WIN=C(0x9fd6ff),TYRE=C(0x1D1A2F),BURNT=C(0x2a2530);
    // [name, body w,h,l, body y, body z, cab w,h,l, cab y, cab z, fixed colour, weight]
    const TY=[['car',1.9,.75,4.2,.75,0,1.6,.62,2.1,1.43,-.2,null,40],['taxi',1.9,.75,4.2,.75,0,1.6,.62,2.1,1.43,-.2,0xFFD23F,10],['pickup',2,.85,4.8,.8,0,1.8,.7,1.6,1.55,.8,null,10],['van',2,1.7,4.8,1.2,0,1.96,.5,1,1.55,1.95,null,12],['bus',2.5,2.5,10.5,1.7,0,2.54,.7,9.6,2.2,0,0xF2352A,7],['truck',2.4,2.5,6,1.95,-1.3,2.3,1.5,1.9,1.35,2.95,null,9],['ambulance',2.1,1.9,5,1.3,0,2.12,.5,1.1,1.7,2.2,0xffffff,4]];
    const TW=TY.reduce((a,t)=>a+t[12],0);const pickTy=()=>{let r=Math.random()*TW;for(const t of TY){r-=t[12];if(r<=0)return t}return TY[0]};
    const ppl=[],cars=[];const Q=new T.Quaternion(),E=new T.Euler(),M=new T.Matrix4(),Vp=new T.Vector3(),Vs=new T.Vector3(),Vo=new T.Vector3(),ZERO=new T.Matrix4().makeScale(0,0,0);
    const ctr=()=>o.center();
    function roadPt(minD,maxD){for(let k=0;k<30;k++){const c0=ctr();let x,z;if(o.spawnPt){const s=o.spawnPt();x=s.x;z=s.z}else{const a=Math.random()*6.283,r=minD+Math.random()*(maxD-minD);x=c0.x+Math.cos(a)*r;z=c0.z+Math.sin(a)*r}if(Math.hypot(x-c0.x,z-c0.z)<minD)continue;const ax=Math.random()<.5?'z':'x';if(ax==='z')x=snap(x);else z=snap(z);if(o.inBounds&&!o.inBounds(x,z))continue;return{x,z,ax}}return null}
    function placeP(q,near){const s=roadPt(near?8:60,R*.95);if(!s){q.st=9;return}const side=Math.random()<.5?-1:1;let x=s.x,z=s.z;if(s.ax==='z')x+=side*walkOff;else z+=side*walkOff;if((o.blocked&&o.blocked(x,z))||(o.slowBlocked&&o.slowBlocked(x,z))){q.st=9;return}Object.assign(q,{x,z,y:0,ax:s.ax,dir:Math.random()<.5?-1:1,side,st:0,sp:1.1+Math.random()*1.2,rx:0,rz:0,t:Math.random()*9})}
    function placeC(q,near){const s=roadPt(near?25:90,R*.95);if(!s||(o.slowBlocked&&o.slowBlocked(s.x,s.z))){q.dead=2;return}const ty=pickTy();q.ty=ty;q.len=ty[3];q.ax=s.ax;q.dir=Math.random()<.5?-1:1;q.x=s.x;q.z=s.z;q.y=0;q.rx=q.rz=0;q.fly=null;q.dead=0;q.burn=0;q.sp=(ty[0]==='bus'||ty[0]==='truck'?7:9)+Math.random()*6;q.v=q.sp;
      const col=ty[11]!=null?C(ty[11]):CARC[(Math.random()*CARC.length)|0];q.col=col;cBody.setColorAt(q.i,col);cCab.setColorAt(q.i,ty[0]==='truck'?col:WIN);cWheel.setColorAt(q.i,TYRE);if(ty[0]==='truck'){cBody.setColorAt(q.i,C(0xe8e1d0))}dirty=true}
    let dirty=true;
    for(let i=0;i<nP;i++){const q={i,v:new T.Vector3()};ppl.push(q);pLeg.setColorAt(i,PA[(Math.random()*PA.length)|0]);pBody.setColorAt(i,SH[(Math.random()*SH.length)|0]);pHead.setColorAt(i,SK[(Math.random()*SK.length)|0])}
    for(let i=0;i<nC;i++){const q={i,v:0};cars.push(q)}
    function reset(){ppl.forEach(q=>placeP(q,true));cars.forEach(q=>placeC(q,true))}
    function yawOf(ax,dir){return ax==='z'?(dir>0?0:Math.PI):(dir>0?Math.PI/2:-Math.PI/2)}
    function put(mesh,i,x,y,z,ox,oy,oz,sx,sy,sz){Vo.set(ox,oy,oz).applyQuaternion(Q);Vp.set(x+Vo.x,y+Vo.y,z+Vo.z);Vs.set(sx,sy,sz);M.compose(Vp,Q,Vs);mesh.setMatrixAt(i,M)}
    let fxBudget=0;
    function flingP(q,px,pz,pw){if(q.st===9||q.st===2)return false;const dx=q.x-px,dz=q.z-pz,d=Math.hypot(dx,dz)||1;const s=Math.min(40,Math.max(6,pw));q.v.set(dx/d*s,8+s*.6,dz/d*s);q.st=2;q.spx=(Math.random()-.5)*14;q.spz=(Math.random()-.5)*9;o.onPerson&&o.onPerson(q);return true}
    function wreckC(q,px,pz,pw){if(q.dead)return false;q.dead=1;q.burn=10+Math.random()*8;const a=Math.atan2(q.x-px,q.z-pz),s=Math.min(1.6,(pw||1));q.fly={vx:Math.sin(a)*9*s,vy:(12+Math.random()*10)*s,vz:Math.cos(a)*9*s,rx:(Math.random()-.5)*7,rz:(Math.random()-.5)*7};cBody.setColorAt(q.i,BURNT);cCab.setColorAt(q.i,BURNT);dirty=true;
      if(fxBudget>0){fxBudget--;burst(new T.Vector3(q.x,1.2,q.z),[0xFF9F43,0xF2352A,0xFFD23F,0x1D1A2F],18,7,.8)}o.onCar&&o.onCar(q);return true}
    function blast(p,r,pw){fxBudget=6;let np=0,nc=0;const r2=r*1.5;for(const q of ppl){if(q.st===9)continue;const d=Math.hypot(q.x-p.x,q.z-p.z,(q.y||0)-(p.y||0)*.5);if(d<r2){if(flingP(q,p.x,p.z,(pw||1)*28*(1-d/r2)+8))np++}else if(d<r2*3&&q.st===0)q.st=1}
      const rc=r*1.15+1;for(const q of cars){if(q.dead)continue;if(Math.hypot(q.x-p.x,q.z-p.z)<rc+q.len*.3&&Math.abs((p.y||0)-q.y)<rc+2){if(wreckC(q,p.x,p.z,pw))nc++}}return{p:np,c:nc}}
    function scare(p,r){for(const q of ppl)if(q.st===0&&Math.hypot(q.x-p.x,q.z-p.z)<r)q.st=1}
    // per-frame
    const lanes=new Map();
    let frame=0;function update(dt){const c0=ctr();frame++;
      // traffic spacing: bucket by lane
      lanes.forEach(a=>a.length=0);for(const q of cars){if(q.dead)continue;const rc=snap(q.ax==='z'?q.x:q.z);const k=q.ax+(rc|0)+':'+q.dir;let a=lanes.get(k);if(!a){a=[];lanes.set(k,a)}a.push(q);q.pos=q.ax==='z'?q.z*q.dir:q.x*q.dir}
      lanes.forEach(a=>{if(a.length<2){if(a[0])a[0].gap=1e9;return}a.sort((u,w)=>u.pos-w.pos);for(let i=0;i<a.length;i++){const n=a[i+1];a[i].gap=n?n.pos-a[i].pos-(n.len+a[i].len)/2:1e9}});
      for(const q of cars){const i=q.i;if(q.dead===2){cBody.setMatrixAt(i,ZERO);cCab.setMatrixAt(i,ZERO);cWheel.setMatrixAt(i,ZERO);if(Math.random()<dt*.5)placeC(q,false);continue}
        if(q.fly){const f=q.fly;f.vy-=30*dt;q.x+=f.vx*dt;q.y+=f.vy*dt;q.z+=f.vz*dt;q.rx+=f.rx*dt;q.rz+=f.rz*dt;if(q.y<0){q.y=0;f.vy*=-.3;f.vx*=.5;f.vz*=.5;f.rx*=.4;f.rz*=.4;if(Math.abs(f.vy)<1.5){q.rx=Math.round(q.rx/Math.PI)*Math.PI;q.rz=Math.round(q.rz/Math.PI)*Math.PI;q.fly=null}}}
        else if(q.dead){q.burn-=dt;if(q.burn>4&&Math.random()<dt*.35)puff(new T.Vector3(q.x,2.4,q.z),0x2a2530,1.8,2,new T.Vector3(0,3,0));if(q.burn<=0&&Math.hypot(q.x-c0.x,q.z-c0.z)>70){placeC(q,false)}}
        else{const want=Math.max(0,Math.min(q.sp,(q.gap-2.5)*1.4));q.v+=(want-q.v)*Math.min(1,dt*3);const ax=q.ax,prev=ax==='z'?q.z:q.x;const cur=prev+q.dir*q.v*dt;if(ax==='z')q.z=cur;else q.x=cur;const node=snap(cur);
          if((prev-node)*(cur-node)<=0&&Math.random()<.33){if(ax==='z')q.z=node;else q.x=node;q.ax=ax==='z'?'x':'z';q.dir=Math.random()<.5?-1:1}
          if(q.ax==='z')q.x=snap(q.x)+q.dir*lane;else q.z=snap(q.z)-q.dir*lane;
          const ahX=q.x+(q.ax==='x'?q.dir*(q.len/2+1.5):0),ahZ=q.z+(q.ax==='z'?q.dir*(q.len/2+1.5):0);if((o.inBounds&&!o.inBounds(ahX,ahZ))||(o.blocked&&o.blocked(ahX,ahZ,1))||(o.slowBlocked&&(frame+i)%20===0&&o.slowBlocked(ahX,ahZ))){q.dir*=-1;q.v=0}
          if(Math.hypot(q.x-c0.x,q.z-c0.z)>R)placeC(q,false)}
        const ty=q.ty;E.set(q.rx,yawOf(q.ax,q.dir),q.rz,'YXZ');Q.setFromEuler(E);put(cBody,i,q.x,q.y,q.z,0,ty[4],ty[5],ty[1],ty[2],ty[3]);put(cCab,i,q.x,q.y,q.z,0,ty[9],ty[10],ty[6],ty[7],ty[8]);put(cWheel,i,q.x,q.y,q.z,0,.38,ty[5]*.5,ty[1]+.12,.76,ty[3]*.72)}
      for(const q of ppl){const i=q.i;if(q.st===9){pLeg.setMatrixAt(i,ZERO);pBody.setMatrixAt(i,ZERO);pHead.setMatrixAt(i,ZERO);if(Math.random()<dt*.6)placeP(q,false);continue}
        q.t+=dt;let yaw=q.ax==='z'?(q.dir>0?0:Math.PI):(q.dir>0?Math.PI/2:-Math.PI/2),bob=0;
        if(q.st===2){q.v.y-=30*dt;q.x+=q.v.x*dt;q.y+=q.v.y*dt;q.z+=q.v.z*dt;q.rx+=q.spx*dt;q.rz+=q.spz*dt;if(q.y<=0){q.y=0;if(q.v.y<-10){q.v.y*=-.3;q.v.x*=.5;q.v.z*=.5}else{q.st=3;q.dn=1+Math.random()*1.5;q.rx=-Math.PI/2;q.rz=0}}}
        else if(q.st===3){q.dn-=dt;q.y=.25;if(q.dn<=0){q.st=1;q.rx=0;q.y=0;const s=snap(q.ax==='z'?q.x:q.z);if(q.ax==='z')q.x=s+q.side*walkOff;else q.z=s+q.side*walkOff}}
        else{const fl=q.st===1;if(fl){const dx=q.x-c0.x,dz=q.z-c0.z;q.dir=q.ax==='z'?(Math.sign(dz)||1):(Math.sign(dx)||1)}const s=fl?7:q.sp;const ax=q.ax,prev=ax==='z'?q.z:q.x,cur=prev+q.dir*s*dt;if(ax==='z')q.z=cur;else q.x=cur;const node=snap(cur);
          if((prev-node)*(cur-node)<=0&&Math.random()<.3){const oth=ax==='z'?q.x:q.z;q.ax=ax==='z'?'x':'z';q.side=Math.sign(oth-snap(oth))||1;if(q.ax==='z')q.x=node+q.side*walkOff;else q.z=node+q.side*walkOff;q.dir=Math.random()<.5?-1:1;yaw=yawOf(q.ax,q.dir)}
          if((o.inBounds&&!o.inBounds(q.x,q.z))||(o.blocked&&o.blocked(q.x,q.z))||(o.slowBlocked&&(frame+i)%20===0&&o.slowBlocked(q.x,q.z))){if(ax==='z')q.z=prev;else q.x=prev;q.dir*=-1}
          bob=Math.abs(Math.sin(q.t*s*2.2))*(fl?.22:.06);yaw=yawOf(q.ax,q.dir)+(fl?Math.sin(q.t*14)*.15:0);if(Math.hypot(q.x-c0.x,q.z-c0.z)>R){placeP(q,false);continue}}
        const flat=q.st===2||q.st===3;if(flat){E.set(q.rx,yaw,q.rz,'YXZ');Q.setFromEuler(E)}else{Q.set(0,Math.sin(yaw/2),0,Math.cos(yaw/2))}const y=q.y+bob;
        put(pLeg,i,q.x,y,q.z,0,.52,0,.6,1.04,.38);put(pBody,i,q.x,y,q.z,0,1.54,0,1.14,1.02,.6);put(pHead,i,q.x,y,q.z,0,2.34,0,.54,.54,.54)}
      [pLeg,pBody,pHead,cBody,cCab,cWheel].forEach(m=>{m.instanceMatrix.needsUpdate=true;if(dirty&&m.instanceColor)m.instanceColor.needsUpdate=true});dirty=false}
    function stats(){let p=0,c=0;ppl.forEach(q=>{if(q.st!==9)p++});cars.forEach(q=>{if(q.dead!==2)c++});return{p,c}}
    return{update,blast,scare,reset,stats,ppl,cars,meshes:[pLeg,pBody,pHead,cBody,cCab,cWheel]}}
  const K0={};return Object.assign(K0,{crowd,streamCity,touchBtn,pointer,smash,T,scene,camera,input,wrap,hud,TM,grad,ink,sky,lights,fig,capeAnim,pose,city,push,inBox,cam,moveIn,burst,puff,ring,fxTick,ribbon,H,radar,F})}
