/* ================= MUSIC 2: song library, Guess the Song, Beat Lanes, Piano Tiles, Learn Piano, Beat Maker ================= */
function NT(n){if(n==='r')return null;const m=/^([A-G])([#b]?)(-?\d)$/.exec(n);return{C:0,D:2,E:4,F:5,G:7,A:9,B:11}[m[1]]+(m[2]==='#'?1:m[2]==='b'?-1:0)+(+m[3]-4)*12}
function MEL(s,d0){return s.trim().split(/\s+/).map(t=>{const[n,d]=t.split(':');return[NT(n),d!=null?+d:(d0||1)]})}
// Short, instantly recognizable hooks: [title, by, bpm, melody, default note length]
const SONGS=[['Seven Nation Army','The White Stripes',124,'E4:1.5 E4:.5 G4:.75 E4:.75 D4:.5 C4:2 B3:2'],
  ['Smoke on the Water','Deep Purple',112,'G3 Bb3 C4:1.5 G3 Bb3 Db4:.5 C4:2 G3 Bb3 C4:1.5 Bb3 G3:2.5'],
  ['Sweet Child O’ Mine','Guns N’ Roses',125,'D4 D5 A4 G4 G5 A4 F#5 A4 D4 D5 A4 G4 G5 A4 F#5 A4 E4 D5 A4 G4 G5 A4 F#5 A4',.5],
  ['Billie Jean','Michael Jackson',117,'F#4 C#4 E4 F#4 E4 C#4 B3 C#4 F#4 C#4 E4 F#4 E4 C#4 B3 C#4',.5],
  ['Take On Me','a-ha',169,'F#5:.5 F#5:.5 D5:.5 B4:1 B4:1 E5:1 E5:1 E5:.5 G#5:.5 G#5:.5 A5:.5 B5:.5 A5:.5 A5:.5 A5:.5 E5:1 D5:1 F#5:1 F#5:1 F#5:.5 E5:.5 E5:.5 F#5:.5 E5:1'],
  ['Axel F','Harold Faltermeyer',118,'F4:1 Ab4:.75 F4:.5 F4:.25 Bb4:.5 F4:.5 Eb4:.5 F4:1 C5:.75 F4:.5 F4:.25 Db5:.5 C5:.5 Ab4:.5 F4:.5 C5:.5 F5:.5 F4:.25 Eb4:.5 Eb4:.25 C4:.5 G4:.5 F4:1.5'],
  ['Never Gonna Give You Up','Rick Astley',113,'A4:.25 B4:.25 D5:.25 B4:.25 F#5:.75 F#5:.75 E5:1.5 A4:.25 B4:.25 D5:.25 B4:.25 E5:.75 E5:.75 D5:.75 C#5:.25 B4:.5 A4:.25 B4:.25 D5:.25 B4:.25 D5:1 E5:.5 C#5:.75 A4:.25 A4:.5 E5:1 D5:2'],
  ['The Imperial March','John Williams (Star Wars)',104,'G4:1 G4:1 G4:1 Eb4:.75 Bb4:.25 G4:1 Eb4:.75 Bb4:.25 G4:2 D5:1 D5:1 D5:1 Eb5:.75 Bb4:.25 F#4:1 Eb4:.75 Bb4:.25 G4:2'],
  ['Star Wars Main Title','John Williams',108,'G4:.33 G4:.33 G4:.34 C5:2 G5:2 F5:.33 E5:.33 D5:.34 C6:2 G5:1 F5:.33 E5:.33 D5:.34 C6:2 G5:1 F5:.33 E5:.33 F5:.34 D5:2'],
  ['Hedwig’s Theme','John Williams (Harry Potter)',80,'B4:.5 E5:.75 G5:.25 F#5:.5 E5:1 B5:.5 A5:1.5 F#5:1.5 E5:.75 G5:.25 F#5:.5 D#5:1 F5:.5 B4:2.5'],
  ['Super Mario Bros. Theme','Koji Kondo (Nintendo)',180,'E5:.5 E5:.5 r:.5 E5:.5 r:.5 C5:.5 E5:1 G5:2 G4:2 C5:1.5 G4:1.5 E4:1.5 A4:1 B4:1 Bb4:.5 A4:1'],
  ['Game of Thrones Theme','Ramin Djawadi',160,'G4:1 C4:1 Eb4:.5 F4:.5 G4:1 C4:1 Eb4:.5 F4:.5 G4:1 C4:1 E4:.5 F4:.5 G4:1 C4:1 E4:.5 F4:.5 G4:3'],
  ['He’s a Pirate','Pirates of the Caribbean',150,'A3:.5 C4:.5 D4:1 D4:1 D4:.5 E4:.5 F4:1 F4:1 F4:.5 G4:.5 E4:1 E4:1 D4:.5 C4:.5 C4:.5 D4:1.5'],
  ['Mission: Impossible Theme','Lalo Schifrin',160,'G4:1.5 G4:1.5 Bb4:1 C5:1 G4:1.5 G4:1.5 F4:1 F#4:1 G4:1.5 G4:1.5 Bb4:1 C5:1 G4:1.5 G4:1.5 F4:1 F#4:1'],
  ['Megalovania','Toby Fox (Undertale)',120,'D4:.25 D4:.25 D5:.5 A4:.75 G#4:.5 G4:.5 F4:.5 D4:.25 F4:.25 G4:.25 C4:.25 C4:.25 D5:.5 A4:.75 G#4:.5 G4:.5 F4:.5 D4:.25 F4:.25 G4:.25'],
  ['Pac-Man Intro','Toru Iwatani (Namco)',140,'B4:.25 B5:.25 F#5:.25 D#5:.25 B5:.125 F#5:.375 D#5:.5 C5:.25 C6:.25 G5:.25 E5:.25 C6:.125 G5:.375 E5:.5 B4:.25 B5:.25 F#5:.25 D#5:.25 B5:.125 F#5:.375 D#5:.5 D#5:.125 E5:.125 F5:.25 F5:.125 F#5:.125 G5:.25 G5:.125 G#5:.125 A5:.25 B5:.5'],
  ['Pink Panther Theme','Henry Mancini',120,'D#4:.25 E4:1 F#4:.25 G4:1 D#4:.25 E4:.5 F#4:.25 G4:.5 C5:.25 B4:.5 E4:.25 G4:.5 B4:.25 A#4:2'],
  ['Jaws Theme','John Williams',100,'E3:.75 F3:.25 r:1 E3:.75 F3:.25 r:1 E3:.5 F3:.5 E3:.5 F3:.5 E3:.25 F3:.25 E3:.25 F3:.25 E3:.25 F3:.25 E3:.25 F3:.25'],
  ['Tetris Theme (Korobeiniki)','Russian folk song',150,'E5:1 B4:.5 C5:.5 D5:1 C5:.5 B4:.5 A4:1 A4:.5 C5:.5 E5:1 D5:.5 C5:.5 B4:1.5 C5:.5 D5:1 E5:1 C5:1 A4:1 A4:2'],
  ['Ode to Joy','Beethoven',120,'E4 E4 F4 G4 G4 F4 E4 D4 C4 C4 D4 E4 E4:1.5 D4:.5 D4:2'],
  ['Für Elise','Beethoven',120,'E5:.5 D#5:.5 E5:.5 D#5:.5 E5:.5 B4:.5 D5:.5 C5:.5 A4:1.5 C4:.5 E4:.5 A4:.5 B4:1.5 E4:.5 G#4:.5 B4:.5 C5:1.5'],
  ['Symphony No. 5','Beethoven',110,'r:.5 G4:.5 G4:.5 G4:.5 Eb4:3 r:.5 F4:.5 F4:.5 F4:.5 D4:3'],
  ['In the Hall of the Mountain King','Edvard Grieg',130,'A3:.5 B3:.5 C4:.5 D4:.5 E4:.5 C4:.5 E4:1 D#4:.5 B3:.5 D#4:1 D4:.5 A#3:.5 D4:1 A3:.5 B3:.5 C4:.5 D4:.5 E4:.5 C4:.5 E4:.5 A4:.5 G4:.5 E4:.5 C4:.5 E4:.5 G4:2'],
  ['Can-Can','Jacques Offenbach',160,'C4:1 D4:.5 F4:.5 E4:.5 D4:.5 G4:1 G4:1 G4:.5 A4:.5 E4:.5 F4:.5 D4:1 D4:1 D4:.5 F4:.5 E4:.5 D4:.5 C4:.5 C5:.5 B4:.5 A4:.5 G4:.5 F4:.5 E4:.5 D4:.5 C4:1'],
  ['William Tell Overture','Gioachino Rossini',150,'G4:.25 G4:.25 G4:.5 G4:.25 G4:.25 G4:.5 G4:.25 G4:.25 C5:.5 D5:.5 E5:.5 G4:.25 G4:.25 G4:.5 G4:.25 G4:.25 C5:.5 E5:.25 E5:.25 D5:.5 B4:.5 G4:.5'],
  ['The Entertainer','Scott Joplin',100,'D4:.25 D#4:.25 E4:.25 C5:.5 E4:.25 C5:.5 E4:.25 C5:1.25 C5:.25 D5:.25 D#5:.25 E5:.25 C5:.25 D5:.25 E5:.5 B4:.25 D5:.5 C5:1.5'],
  ['Happy Birthday','Traditional',110,'G4:.75 G4:.25 A4:1 G4:1 C5:1 B4:2 G4:.75 G4:.25 A4:1 G4:1 D5:1 C5:2'],
  ['Jingle Bells','James Lord Pierpont',140,'E4 E4 E4:2 E4 E4 E4:2 E4 G4 C4:1.5 D4:.5 E4:4'],
  ['Twinkle Twinkle Little Star','Traditional',110,'C4 C4 G4 G4 A4 A4 G4:2 F4 F4 E4 E4 D4 D4 C4:2']].map(([n,by,bpm,s,d0])=>({n,by,bpm,mel:MEL(s,d0)}));
function playSeq(mel,bpm,type,vol,from){if(muted)return 0;try{const a=ac();let t=(from||a.currentTime)+.06;const b=60/bpm;for(const[s,d]of mel){if(s!=null)tone(hz(s),t,Math.max(.14,d*b*.95),type||'triangle',vol||.14);t+=d*b}return(t-a.currentTime)*1000}catch(e){return 0}}
// Real hits for the quiz modes: [title, artist, year, emoji clue]
const HITS=[['Espresso','Sabrina Carpenter',2024,'☕⚡'],['Please Please Please','Sabrina Carpenter',2024,'🙏🙏🙏'],['Manchild','Sabrina Carpenter',2025,'👨👶'],['Birds of a Feather','Billie Eilish',2024,'🐦🪶🤝'],['Bad Guy','Billie Eilish',2019,'😈👦'],['APT.','Rosé & Bruno Mars',2024,'🏢🎶'],['Die With a Smile','Lady Gaga & Bruno Mars',2024,'💀😊'],['Abracadabra','Lady Gaga',2025,'🪄🎩'],['Poker Face','Lady Gaga',2008,'🃏😐'],['Not Like Us','Kendrick Lamar',2024,'🙅‍♂️🫵'],['Good Luck, Babe!','Chappell Roan',2024,'🍀👶'],['Pink Pony Club','Chappell Roan',2020,'💗🐴🎉'],['Beautiful Things','Benson Boone',2024,'✨🎁'],['A Bar Song (Tipsy)','Shaboozey',2024,'🍺🥴'],['Too Sweet','Hozier',2024,'🍭😖'],['Golden','HUNTR/X (KPop Demon Hunters)',2025,'🥇✨🎤'],['Ordinary','Alex Warren',2025,'😐'],['Lose Control','Teddy Swims',2023,'😵‍💫🎛️'],['The Fate of Ophelia','Taylor Swift',2025,'🥀🌊'],['Cruel Summer','Taylor Swift',2019,'😈☀️'],['Anti-Hero','Taylor Swift',2022,'🚫🦸'],['Shake It Off','Taylor Swift',2014,'🫨🙅'],['Flowers','Miley Cyrus',2023,'💐🙋‍♀️'],['Party in the U.S.A.','Miley Cyrus',2009,'🎉🇺🇸'],['vampire','Olivia Rodrigo',2023,'🧛'],['drivers license','Olivia Rodrigo',2021,'🚗🪪'],['As It Was','Harry Styles',2022,'⏪🕰️'],['Watermelon Sugar','Harry Styles',2019,'🍉🍬'],['Levitating','Dua Lipa',2020,'🧍‍♀️⬆️✨'],['Houdini','Dua Lipa',2023,'🎩🔓'],['Blinding Lights','The Weeknd',2019,'🌃💡😎'],['Stay','The Kid LAROI & Justin Bieber',2021,'✋🛑'],['Heat Waves','Glass Animals',2020,'🔥🌊'],['Old Town Road','Lil Nas X',2019,'🤠🐎🛣️'],['Dynamite','BTS',2020,'🧨'],['Kill Bill','SZA',2022,'🗡️💵'],['Paint the Town Red','Doja Cat',2023,'🎨🏙️🔴'],['Greedy','Tate McRae',2023,'🤑'],['Shape of You','Ed Sheeran',2017,'🔷👤'],['Uptown Funk','Mark Ronson ft. Bruno Mars',2014,'🏙️⬆️🕺'],['Happy','Pharrell Williams',2013,'😀👏'],['Rolling in the Deep','Adele',2010,'🌀🌊'],['Easy On Me','Adele',2021,'😌🙏'],['Believer','Imagine Dragons',2017,'🙏✊'],['Sunflower','Post Malone & Swae Lee',2018,'🌻'],['Despacito','Luis Fonsi ft. Daddy Yankee',2017,'🐢🎶'],['Gangnam Style','PSY',2012,'🐴🕺😎'],['Call Me Maybe','Carly Rae Jepsen',2011,'📞🤔'],['Umbrella','Rihanna',2007,'☂️'],['Crazy in Love','Beyoncé ft. Jay-Z',2003,'🤪❤️'],['Hey Ya!','OutKast',2003,'👋😃'],['Mr. Brightside','The Killers',2003,'👨➡️☀️'],['Smells Like Teen Spirit','Nirvana',1991,'👃🧑‍🎤👻'],['Sweet Child O’ Mine','Guns N’ Roses',1987,'🍬👶'],['Thriller','Michael Jackson',1982,'🧟🌕'],['Don’t Stop Believin’','Journey',1981,'🚫🛑🙏'],['Bohemian Rhapsody','Queen',1975,'🎭🎼'],['Somebody That I Used to Know','Gotye ft. Kimbra',2011,'👤🕰️🤷'],['Bad Romance','Lady Gaga',2009,'😈💘'],['Firework','Katy Perry',2010,'🎆']];
const QMODES=[['🔀 Mix','mix'],['🎵 Hum the hook','mel'],['😀 Emoji hits','emoji'],['🎤 Who sang it?','artist'],['📅 What year?','year']];
(()=>{const gi=G.findIndex(g=>g.id==='tune');if(gi<0)return;Object.assign(G[gi],{blurb:'Name that hit! Hear famous hooks, decode emoji song titles, match hits from Sabrina Carpenter, Billie Eilish, Taylor Swift and more to their artists, and guess the year.',fmt:b=>b+'/10',
run(root,c){let mode=S.get('tune_mode',0);const nChoices=c.pick(4,4,6),replays=c.pick(9,3,1),len=c.pick(99,12,6);let round=0,score=0,streak=0,cur=null,left=0,lock=false;
  const disc=el('div',{class:'vinyl'});const q=el('div',{class:'big-text',style:'text-align:center;min-height:1.5em'});const choices=el('div',{class:'choices'});const msg=el('p',{class:'hint',style:'font-size:16px;color:var(--ink);font-weight:600'});
  const play=el('button',{class:'btn primary',type:'button'},'▶ Play again');play.addEventListener('click',()=>{if(left<=0||!cur||cur.kind!=='mel')return;left--;doPlay()});
  const mr=chipRow(QMODES.map(m=>m[0]),()=>mode,i=>{mode=i;S.set('tune_mode',i);round=0;score=0;streak=0;next()});
  function doPlay(){const ms=playSeq(cur.s.mel.slice(0,len),cur.s.bpm);disc.classList.add('spin');c.after(()=>disc.classList.remove('spin'),ms||900);play.textContent='▶ Play again ('+left+' left)';play.disabled=left<=0}
  function mkQ(){const m=QMODES[mode][1]==='mix'?pick(['mel','emoji','artist','year','mel']):QMODES[mode][1];
    if(m==='mel'){const s=pick(SONGS);return{kind:'mel',s,ask:'Which song is this?',ans:s.n,opts:shuffle([s.n,...shuffle(SONGS.filter(o=>o!==s)).slice(0,nChoices-1).map(o=>o.n)]),info:s.n+' · '+s.by}}
    const h=pick(HITS);if(m==='emoji')return{kind:'emoji',ask:h[3],ans:h[0],opts:shuffle([h[0],...shuffle(HITS.filter(o=>o!==h)).slice(0,nChoices-1).map(o=>o[0])]),info:h[0]+' by '+h[1]+' ('+h[2]+')'};
    if(m==='artist'){const others=[...new Set(HITS.map(o=>o[1]).filter(a=>a!==h[1]&&!a.includes(h[1].split(' ')[0])))];return{kind:'artist',ask:'Who sang “'+h[0]+'”?',ans:h[1],opts:shuffle([h[1],...shuffle(others).slice(0,nChoices-1)]),info:h[0]+' by '+h[1]+' ('+h[2]+')'}}
    const ys=new Set([h[2]]);while(ys.size<nChoices){const y=h[2]+(rand(2)?1:-1)*(1+rand(c.pick(8,5,3)));if(y<=2025&&y>1960)ys.add(y)}return{kind:'year',ask:'What year did “'+h[0]+'” by '+h[1]+' come out?',ans:String(h[2]),opts:[...ys].sort().map(String),info:h[0]+' came out in '+h[2]+'.'}}
  function next(){if(round>=10){c.stat('Final '+score+'/10 · Best '+c.best(score)+'/10');q.textContent=score>=9?'🏆 Music genius!':score>=6?'🎧 Nice ears!':'🎶 Keep listening!';msg.textContent='You got '+score+' out of 10.';choices.innerHTML='';choices.append(el('button',{class:'btn primary',type:'button',onclick:()=>{round=0;score=0;streak=0;next()}},'Play again'));play.hidden=true;return}
    cur=mkQ();round++;left=replays;lock=false;play.hidden=cur.kind!=='mel';disc.style.display=cur.kind==='mel'?'':'none';q.style.fontSize=cur.kind==='emoji'?'64px':'';q.textContent=cur.kind==='mel'?'':cur.ask;msg.textContent=cur.kind==='mel'?(soundNote()||'Which song is this?'):cur.kind==='emoji'?'Which hit song do these emoji spell out?':'';
    choices.innerHTML='';cur.opts.forEach(o=>{const b=el('button',{class:'btn',type:'button'},o);b.addEventListener('click',()=>{if(lock)return;lock=true;if(o===cur.ans){score++;streak++;b.classList.add('right');beep(880,.15,'triangle');msg.textContent='Yes! '+cur.info+(streak>2?' 🔥 '+streak+' in a row!':'')}else{streak=0;b.classList.add('wrong');[...choices.children].forEach(x=>{if(x.textContent===cur.ans)x.classList.add('right')});beep(150,.25,'sawtooth');msg.textContent='Nope, it’s '+cur.info}c.stat('Round '+round+'/10 · Score '+score);c.after(next,1900)});choices.append(b)});
    c.stat('Round '+round+'/10 · Score '+score);if(cur.kind==='mel')c.after(doPlay,450)}
  root.append(mr,disc,q,play,msg,choices,el('p',{class:'hint'},c.pick('Easy: whole hooks, replay as much as you like.','Normal: 12 notes, 3 extra listens.','Hard: 6 notes, 1 extra listen, 6 choices, closer years.')+' Hooks are played as simple beeps, not recordings.'));next()}})})();

/* ---- Beat Lanes: play real songs by hitting the notes ---- */
function songLanes(mel){const ss=mel.filter(n=>n[0]!=null).map(n=>n[0]);const lo=Math.min(...ss),hi=Math.max(...ss);const out=[];let t=0,prevS=null,prevL=1;for(const[s,d]of mel){if(s!=null){let l=hi===lo?1:Math.round((s-lo)/(hi-lo)*3);if(prevS!=null&&s!==prevS&&l===prevL)l=clamp(l+(s>prevS?1:-1),0,3);if(prevS!=null&&s===prevS)l=prevL;out.push({b:t,s,l,d});prevS=s;prevL=l}t+=d}return{notes:out,len:t}}
(()=>{const gi=G.findIndex(g=>g.id==='lanes');if(gi<0)return;Object.assign(G[gi],{blurb:'Play real songs, from Seven Nation Army to Megalovania: hit each falling note on the beat and the melody plays itself.',
run(root,c){const W=480,H=600,HY=520,K=['d','f','j','k'],COL=['#F2352A','#FFD23F','#2BB673','#2d6fd6'],lw=W/4;let si=S.get('lanes_song',0)%SONGS.length;
  const sel=el('select',{class:'typein',style:'max-width:360px'},...SONGS.map((s,i)=>el('option',{value:i},s.n+' · '+s.by)));sel.value=si;c.on(sel,'change',()=>{si=+sel.value;S.set('lanes_song',si);state='ready'});
  const[cv,x]=mk(W,H,'width:min(100%,calc(62vh*.8))');const sp=c.pick(.8,1,1.2),fall=c.pick(1800,1400,1050),win=c.pick(150,110,80);
  let notes=[],T=0,t0=0,state='ready',score=0,combo=0,maxc=0,hits=0,total=1,flash=[0,0,0,0],judge='',jt=0,nextBeat=0,end=0,beat=500,pass=0,rating='';
  function start(){const s=SONGS[si];const L=songLanes(s.mel);beat=60000/(s.bpm*sp);notes=[];const reps=L.len<10?3:2;for(let r=0;r<reps;r++)L.notes.forEach(n=>notes.push({t:(4+r*Math.ceil(L.len)+n.b)*beat,l:n.l,s:n.s,d:n.d,hit:false,miss:false}));total=notes.length;end=notes[notes.length-1].t+1500;score=0;combo=0;maxc=0;hits=0;state='run';t0=performance.now()+300;nextBeat=0}
  function press(l){flash[l]=130;if(state!=='run'){start();return}const n=notes.find(n=>!n.hit&&!n.miss&&n.l===l&&Math.abs(n.t-T)<win*1.8);if(!n){combo=Math.max(0,combo-2);return}
    const e=Math.abs(n.t-T);if(e>win){n.miss=true;combo=0;judge='Miss';jt=450;return}n.hit=true;hits++;combo++;maxc=Math.max(maxc,combo);const perfect=e<win*.4;score+=Math.round((perfect?300:150)*(1+Math.floor(combo/10)*.5));judge=perfect?'Perfect!':'Good';jt=450;
    if(!muted)tone(hz(n.s),ac().currentTime,Math.max(.18,n.d*beat/1000*.95),'square',.09),tone(hz(n.s+12),ac().currentTime,Math.max(.15,n.d*beat/1000*.8),'triangle',.07)}
  c.on(document,'keydown',e=>{const i=K.indexOf(e.key.toLowerCase());if(i>=0&&!e.repeat){e.preventDefault();press(i)}});c.on(cv,'pointerdown',e=>{e.preventDefault();const p=canvasPos(cv,e,W,H);press(clamp(Math.floor(p.x/lw),0,3))});
  function draw(){x.fillStyle='#1D1A2F';x.fillRect(0,0,W,H);for(let l=0;l<4;l++){x.fillStyle=flash[l]>0?COL[l]+'55':'rgba(255,255,255,'+(l%2?.03:.06)+')';x.fillRect(l*lw,0,lw,H)}
    const pulse=state==='run'?Math.max(0,1-((T%beat)+beat)%beat/200):0;x.strokeStyle='rgba(255,253,246,'+(.6+pulse*.4)+')';x.lineWidth=3+pulse*3;x.beginPath();x.moveTo(0,HY);x.lineTo(W,HY);x.stroke();
    for(let l=0;l<4;l++){x.strokeStyle=COL[l];x.lineWidth=4;x.beginPath();x.arc(l*lw+lw/2,HY,27,0,7);x.stroke();x.fillStyle='#FFFDF6';x.font='700 16px "JetBrains Mono", monospace';x.textAlign='center';x.fillText(K[l].toUpperCase(),l*lw+lw/2,HY+58)}
    if(state!=='ready')for(const n of notes){if(n.hit)continue;const y=HY-(n.t-T)/fall*HY;if(y<-60||y>H+30)continue;const tail=Math.min(200,n.d*beat/fall*HY*.6);if(n.d>=1){x.fillStyle=COL[n.l]+'66';x.fillRect(n.l*lw+lw/2-7,y-tail,14,tail)}x.fillStyle=n.miss?'#5A5470':COL[n.l];x.beginPath();x.arc(n.l*lw+lw/2,y,23,0,7);x.fill();x.strokeStyle='#FFFDF6';x.lineWidth=3;x.stroke()}
    x.textAlign='center';if(jt>0){x.fillStyle=judge==='Miss'?'#FF8FB1':'#FFD23F';x.font='34px "Bagel Fat One", sans-serif';x.fillText(judge,W/2,HY-130)}
    if(state==='run'){x.fillStyle='rgba(255,253,246,.85)';x.font='700 16px Figtree, sans-serif';x.fillText('♪ '+SONGS[si].n,W/2,28);if(combo>4){x.font='700 20px "JetBrains Mono", monospace';x.fillText(combo+'× combo',W/2,58)}const pr=clamp(T/end,0,1);x.fillStyle='#FFD23F';x.fillRect(0,0,W*pr,5)}
    if(state==='ready')banner(x,W,H,SONGS[si].n,'Press D F J K or tap a lane to start');
    if(state==='done')banner(x,W,H,rating+' '+score+' pts',Math.round(hits/total*100)+'% hit · max combo '+maxc+' · tap to replay')}
  c.loop(dt=>{for(let i=0;i<4;i++)flash[i]-=dt;jt-=dt;
    if(state==='run'){T=performance.now()-t0;while(nextBeat*beat<=T&&nextBeat*beat<end-800){kick();if(nextBeat%2)noise(.06,'bandpass',1800,.1);noise(.03,'highpass',8000,.05);nextBeat++}
      for(const n of notes)if(!n.hit&&!n.miss&&T-n.t>win){n.miss=true;combo=0;judge='Miss';jt=350}
      if(T>end){state='done';const pc=hits/total;rating=pc>.95?'★★★':pc>.8?'★★':pc>.5?'★':'';c.stat('Score '+score+' · '+Math.round(pc*100)+'% hit · Best '+c.best(score))}else c.stat('Score '+score+' · Combo '+combo)}
    draw()});
  root.append(el('div',{class:'bdform'},el('label',null,'Song'),sel),cv,el('p',{class:'hint'},'Every note you hit plays the next bit of the tune. Long notes have a tail. '+c.pick('Easy: slower and forgiving.','Normal.','Hard: faster, tighter timing.')))}})})();

/* ---- Piano Tiles ---- */
G.push({id:'ptiles',name:'Tap Tiles',kind:'music',levels:true,tint:'#1D1A2F',blurb:'Tap only the black tiles as they race down. Each one plays the next note of a famous song. Don’t touch the white!',fmt:b=>b+' tiles',
art:'<rect width="120" height="72" fill="#FFFDF6"/><g stroke="#1D1A2F" stroke-width="2"><path d="M30 0V72M60 0V72M90 0V72"/></g><rect x="0" y="6" width="30" height="24" fill="#1D1A2F"/><rect x="60" y="34" width="30" height="24" fill="#1D1A2F"/><rect x="30" y="60" width="30" height="24" fill="#2d6fd6"/><rect x="90" y="-10" width="30" height="24" fill="#1D1A2F"/>',
run(root,c){const W=400,H=640,RH=150;let si=S.get('pt_song',0)%SONGS.length;const sel=el('select',{class:'typein',style:'max-width:360px'},...SONGS.map((s,i)=>el('option',{value:i},s.n)));sel.value=si;c.on(sel,'change',()=>{si=+sel.value;S.set('pt_song',si);reset()});
  const[cv,x]=mk(W,H,'width:min(100%,calc(64vh*.625));touch-action:none');let rows=[],off=0,speed=0,state='ready',score=0,ni=0,wrong=null,wt=0,lastCol=-1;
  const mel=()=>SONGS[si].mel.filter(n=>n[0]!=null);
  function addRow(){let col;do{col=rand(4)}while(col===lastCol&&Math.random()<.7);lastCol=col;rows.push({col,hit:false})}
  function reset(){rows=[];off=0;score=0;ni=0;state='ready';wrong=null;for(let i=0;i<6;i++)addRow();speed=c.pick(260,340,430)}
  function tap(px,py){if(state==='over'){reset();return}const ri=Math.floor((H-py+off)/RH);const r=rows[ri];if(!r)return;const col=clamp(Math.floor(px/(W/4)),0,3);
    const first=rows.findIndex(q=>!q.hit);if(ri!==first||col!==r.col){if(state==='run'||col!==r.col){lose(ri,col)}return}
    if(state==='ready')state='run';r.hit=true;score++;const m=mel();const n=m[ni%m.length];ni++;if(!muted){const t=ac().currentTime;tone(hz(n[0]),t,.5,'triangle',.16);tone(hz(n[0]-12),t,.4,'sine',.08)}c.stat('Tiles '+score+' · '+SONGS[si].n);if(score%m.length===0){speed*=1.12}}
  function lose(ri,col){state='over';wrong={ri,col};wt=0;beep(110,.5,'sawtooth',.12);c.stat('Tiles '+score+' · Best '+c.best(score))}
  c.on(cv,'pointerdown',e=>{e.preventDefault();const p=canvasPos(cv,e,W,H);tap(p.x,p.y)});c.on(document,'keydown',e=>{const i=['d','f','j','k'].indexOf(e.key.toLowerCase());if(i<0||e.repeat)return;e.preventDefault();const first=rows.findIndex(q=>!q.hit);const y=H-(first*RH-off)-RH/2;tap(i*W/4+W/8,y)});
  c.loop(dt=>{if(state==='run'){off+=speed*dt/1000;speed+=dt*.004;const first=rows.findIndex(q=>!q.hit);if(first>=0&&first*RH-off+RH<0){lose(first,rows[first].col);off=first*RH-10}}
    while(rows.length*RH-off<H+RH)addRow();
    x.fillStyle='#FFFDF6';x.fillRect(0,0,W,H);x.strokeStyle='#d8d4e4';x.lineWidth=2;for(let i=1;i<4;i++){x.beginPath();x.moveTo(i*W/4,0);x.lineTo(i*W/4,H);x.stroke()}
    rows.forEach((r,i)=>{const y=H-(i+1)*RH+off;if(y>H||y<-RH)return;x.fillStyle=r.hit?'#b9c7f0':'#1D1A2F';x.fillRect(r.col*W/4+2,y+2,W/4-4,RH-4);if(!r.hit&&i===rows.findIndex(q=>!q.hit)&&state==='ready'){x.fillStyle='#FFD23F';x.font='700 22px Figtree, sans-serif';x.textAlign='center';x.fillText('START',r.col*W/4+W/8,y+RH/2+8)}});
    if(wrong){wt+=dt;const y=H-(wrong.ri+1)*RH+off;x.fillStyle=Math.floor(wt/150)%2?'#F2352A':'#FF8FB1';x.fillRect(wrong.col*W/4+2,y+2,W/4-4,RH-4)}
    x.fillStyle='#F2352A';x.font='40px "Bagel Fat One", sans-serif';x.textAlign='center';x.fillText(score,W/2,52);
    if(state==='over'&&wt>600)banner(x,W,H,score+' tiles','Tap to try again')});
  reset();root.append(el('div',{class:'bdform'},el('label',null,'Song'),sel),cv,el('p',{class:'hint'},'Tap or press D F J K. Finish the song and it speeds up.'))}});

/* ---- Learn Piano ---- */
const PKEYS={};'zsxdcvgbhnjm'.split('').forEach((k,i)=>PKEYS[k]=i-12);'q2w3er5t6y7u'.split('').forEach((k,i)=>PKEYS[k]=i);'i9o0p'.split('').forEach((k,i)=>PKEYS[k]=12+i);
G.push({id:'pianolearn',name:'Learn Piano',kind:'music',wide:true,tint:'#FFE27A',blurb:'A real playable piano, plus a song teacher that lights up the next key. Learn Für Elise, Seven Nation Army, the Mario theme and more.',
art:'<rect width="120" height="72" fill="#FFE27A"/><g stroke="#1D1A2F" stroke-width="2"><rect x="8" y="16" width="104" height="48" fill="#FFFDF6"/><path d="M23 16V64M38 16V64M53 16V64M68 16V64M83 16V64M98 16V64"/></g><g fill="#1D1A2F"><rect x="18" y="16" width="9" height="28"/><rect x="33" y="16" width="9" height="28"/><rect x="63" y="16" width="9" height="28"/><rect x="78" y="16" width="9" height="28"/><rect x="93" y="16" width="9" height="28"/></g><rect x="38" y="44" width="15" height="20" fill="#2BB673"/>',
run(root,c){const LO=-12,N=37;let si=-1,pos=0,oct=0,right=0,wrongN=0,t0=0;const W=980,H=260;const[cv,x]=mk(W,H,'width:100%;touch-action:none');
  const sel=el('select',{class:'typein',style:'max-width:340px'},el('option',{value:-1},'🎹 Free play'),...SONGS.map((s,i)=>el('option',{value:i},'Learn: '+s.n)));const info=el('p',{class:'big-text',style:'text-align:center;min-height:1.4em'});const demo=el('button',{class:'btn',type:'button'},'▶ Hear it');
  c.on(sel,'change',()=>{si=+sel.value;pos=0;right=0;wrongN=0;shift();upd()});demo.addEventListener('click',()=>{if(si>=0)playSeq(SONGS[si].mel,SONGS[si].bpm)});
  const isB=s=>[1,3,6,8,10].includes(((s%12)+12)%12);const whites=[];for(let s=LO;s<LO+N;s++)if(!isB(s))whites.push(s);const ww=W/whites.length;const down=new Map();let lit={};
  function keyRect(s){if(!isB(s)){const i=whites.indexOf(s);return{x:i*ww,y:0,w:ww,h:H,b:false}}const i=whites.indexOf(s-1);return{x:(i+1)*ww-ww*.3,y:0,w:ww*.6,h:H*.62,b:true}}
  function keyAt(px,py){for(let s=LO;s<LO+N;s++){if(!isB(s))continue;const r=keyRect(s);if(px>=r.x&&px<=r.x+r.w&&py<=r.h)return s}for(const s of whites){const r=keyRect(s);if(px>=r.x&&px<=r.x+r.w)return s}return null}
  function shift(){oct=0;if(si<0)return;const ss=SONGS[si].mel.filter(n=>n[0]!=null).map(n=>n[0]);const lo=Math.min(...ss),hi=Math.max(...ss);while(lo+oct<LO)oct+=12;while(hi+oct>LO+N-1&&lo+oct-12>=LO)oct-=12}
  const target=()=>{if(si<0)return null;const m=SONGS[si].mel.filter(n=>n[0]!=null);return pos<m.length?m[pos][0]+oct:null};
  const NN=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];const nm=s=>NN[((s%12)+12)%12]+(4+Math.floor(s/12));
  function upd(){if(si<0){info.textContent='Play anything! Keys Z to M and Q to P work too.';return}const m=SONGS[si].mel.filter(n=>n[0]!=null);const tg=target();if(tg==null){const acc=Math.round(right/Math.max(1,right+wrongN)*100);info.textContent='🎉 You played '+SONGS[si].n+'! '+acc+'% accuracy. Pick it again to replay.';c.best(acc);beep(880,.2,'triangle',.08);return}info.textContent='Note '+(pos+1)+' of '+m.length+': press the glowing key ('+nm(tg)+')'}
  function hit(s){if(!muted){const t=ac().currentTime;tone(hz(s),t,.9,'triangle',.16);tone(hz(s+12),t,.5,'sine',.04)}lit[s]=250;const tg=target();if(tg==null)return;if(s===tg){pos++;right++;upd()}else{wrongN++;info.animate([{transform:'translateX(-6px)'},{transform:'translateX(6px)'},{transform:'none'}],{duration:200})}}
  c.on(cv,'pointerdown',e=>{e.preventDefault();const p=canvasPos(cv,e,W,H);const s=keyAt(p.x,p.y);if(s!=null){down.set(e.pointerId,s);hit(s)}});c.on(cv,'pointerup',e=>down.delete(e.pointerId));
  c.on(document,'keydown',e=>{if(e.repeat||e.ctrlKey||e.metaKey)return;const s=PKEYS[e.key.toLowerCase()];if(s==null)return;e.preventDefault();hit(s)});
  c.loop((dt,now)=>{for(const k in lit)lit[k]-=dt;const tg=target();x.fillStyle='#1D1A2F';x.fillRect(0,0,W,H);
    for(const s of whites){const r=keyRect(s);x.fillStyle=lit[s]>0?'#FFD23F':s===tg?'rgba(43,182,115,'+(.55+.35*Math.sin(now/150))+')':'#FFFDF6';x.fillRect(r.x+1,0,r.w-2,H-2);if(s%12===0){x.fillStyle='#8c86a3';x.font='700 12px Figtree, sans-serif';x.textAlign='center';x.fillText(nm(s),r.x+r.w/2,H-10)}}
    for(let s=LO;s<LO+N;s++){if(!isB(s))continue;const r=keyRect(s);x.fillStyle=lit[s]>0?'#FF9F43':s===tg?'rgb(43,182,115)':'#1D1A2F';x.fillRect(r.x,0,r.w,r.h);x.strokeStyle='#5A5470';x.strokeRect(r.x,0,r.w,r.h)}
    if(tg!=null){const r=keyRect(tg);x.fillStyle='#F2352A';x.beginPath();x.moveTo(r.x+r.w/2-10,r.b?r.h-30:H-60);x.lineTo(r.x+r.w/2+10,r.b?r.h-30:H-60);x.lineTo(r.x+r.w/2,r.b?r.h-14:H-44);x.fill()}});
  root.append(el('div',{class:'bdform'},sel,demo),info,cv,el('p',{class:'hint'},'Tap the keys, or use your keyboard: Z S X D C V G B H N J M for the low octave and Q 2 W 3 E R 5 T 6 Y 7 U for the next one.'));upd();c.stat('Learn Piano')}});

/* ---- Beat Maker ---- */
const BM_ROWS=[['Kick','#F2352A'],['Snare','#FF9F43'],['Clap','#FFD23F'],['Hi-hat','#6EE7B7'],['Open hat','#7FC8F8'],['Tom','#B9A7FF'],['Bass','#2d6fd6'],['Synth','#FF8FB1']];
const BM_PRE={'Pop':{bpm:112,k:'x...x...x...x...',s:'....x.......x...',c:'................',h:'x.x.x.x.x.x.x.x.',o:'......x.......x.',t:'................',b:'x..x..x.x..x..x.',y:'x...x...x...x...',ch:[0,7,9,5]},'Hip-hop':{bpm:90,k:'x.....x...x.....',s:'....x.......x...',c:'............x...',h:'x.x.x.x.x.x.x.xx',o:'................',t:'..............x.',b:'x.....x...x.....',y:'x.......x.......',ch:[9,5,0,7]},'House':{bpm:124,k:'x...x...x...x...',s:'................',c:'....x.......x...',h:'..x...x...x...x.',o:'..x...x...x...x.',t:'................',b:'..x...x...x...x.',y:'x..x..x...x..x..',ch:[9,5,0,7]},'Trap':{bpm:140,k:'x......x..x.....',s:'........x.......',c:'........x.......',h:'xxxxxxxxx.xxxxxx',o:'................',t:'.............x.x',b:'x......x..x.....',y:'x...............',ch:[9,9,5,7]},'Reggaeton':{bpm:96,k:'x...x...x...x...',s:'...x..x....x..x.',c:'................',h:'x.x.x.x.x.x.x.x.',o:'................',t:'................',b:'x..x..x.x..x..x.',y:'...x..x....x..x.',ch:[9,5,0,7]},'Rock':{bpm:120,k:'x.....x.x.......',s:'....x.......x...',c:'................',h:'x.x.x.x.x.x.x.x.',o:'..............x.',t:'............xxx.',b:'x.x.x.x.x.x.x.x.',y:'x.......x.......',ch:[0,5,7,5]}};
G.push({id:'beatmaker',name:'Beat Studio',kind:'music',wide:true,tint:'#B9A7FF',blurb:'Build your own beat on a 16-step grid: drums, bass and synth. Start from Pop, Hip-hop, House, Trap, Reggaeton or Rock presets.',
art:'<rect width="120" height="72" fill="#1D1A2F"/><g fill="#5A5470">'+Array.from({length:32},(_,i)=>'<rect x="'+(8+(i%8)*13.5)+'" y="'+(10+Math.floor(i/8)*14)+'" width="10" height="10" rx="2"/>').join('')+'</g><g fill="#FFD23F"><rect x="8" y="10" width="10" height="10" rx="2"/><rect x="62" y="10" width="10" height="10" rx="2"/><rect x="35" y="24" width="10" height="10" rx="2"/><rect x="89" y="24" width="10" height="10" rx="2"/></g><g fill="#6EE7B7"><rect x="21.5" y="38" width="10" height="10" rx="2"/><rect x="48.5" y="38" width="10" height="10" rx="2"/><rect x="75.5" y="38" width="10" height="10" rx="2"/><rect x="102.5" y="38" width="10" height="10" rx="2"/></g><g fill="#F2352A"><rect x="8" y="52" width="10" height="10" rx="2"/><rect x="48.5" y="52" width="10" height="10" rx="2"/></g>',
run(root,c){const R=BM_ROWS.length,ST=16;let grid=S.get('bm_grid',null),bpm=S.get('bm_bpm',112),ch=S.get('bm_ch',[0,7,9,5]),swing=false,playing=false,step=0,nextT=0,timer=null;
  const keys=['k','s','c','h','o','t','b','y'];function load(n){const p=BM_PRE[n];grid=keys.map(k=>p[k].split('').map(v=>v==='x'));bpm=p.bpm;ch=p.ch.slice();bs.value=bpm;save();paint()}
  const save=()=>{S.set('bm_grid',grid);S.set('bm_bpm',bpm);S.set('bm_ch',ch)};
  let nb=null;function nbuf(a){if(nb)return nb;const len=a.sampleRate;nb=a.createBuffer(1,len,a.sampleRate);const d=nb.getChannelData(0);for(let i=0;i<len;i++)d[i]=Math.random()*2-1;return nb}
  function nz(a,t,dur,type,f,v){const s=a.createBufferSource();s.buffer=nbuf(a);const fl=a.createBiquadFilter();fl.type=type;fl.frequency.value=f;const g=a.createGain();g.gain.setValueAtTime(v,t);g.gain.exponentialRampToValueAtTime(.0001,t+dur);s.connect(fl);fl.connect(g);g.connect(a.destination);s.start(t);s.stop(t+dur+.02)}
  function osc(a,t,f0,f1,dur,type,v){const o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.setValueAtTime(f0,t);if(f1)o.frequency.exponentialRampToValueAtTime(f1,t+dur*.6);g.gain.setValueAtTime(v,t);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(a.destination);o.start(t);o.stop(t+dur+.02)}
  const root2=s=>ch[Math.floor(s/4)%4];
  function trig(r,t,s){const a=ac();if(r===0)osc(a,t,160,42,.35,'sine',.7);else if(r===1){nz(a,t,.18,'highpass',1500,.35);osc(a,t,190,120,.1,'triangle',.25)}else if(r===2){[0,.012,.024].forEach(d=>nz(a,t+d,.12,'bandpass',1200,.35))}else if(r===3)nz(a,t,.04,'highpass',8000,.18);else if(r===4)nz(a,t,.28,'highpass',7000,.16);else if(r===5)osc(a,t,220,110,.28,'sine',.4);else if(r===6)osc(a,t,hz(root2(s)-24),null,.22,'sawtooth',.14);else if(r===7){const b=root2(s),minor=[9,2,4].includes(b%12);[0,minor?3:4,7].forEach(iv=>osc(a,t,hz(b+iv),null,.3,'triangle',.07))}}
  function sched(){if(!playing)return;const a=ac();const sd=60/bpm/4;while(nextT<a.currentTime+.12){const sw=swing&&step%2?sd*.33:0;if(!muted)for(let r=0;r<R;r++)if(grid[r][step])trig(r,nextT+sw,step);const st=step;setTimeout(()=>{cur=st;paint()},Math.max(0,(nextT-a.currentTime)*1000));nextT+=sd;step=(step+1)%ST}}
  let cur=-1;const pb=el('button',{class:'btn primary',type:'button',style:'min-width:110px'},'▶ Play');pb.addEventListener('click',()=>{playing=!playing;pb.textContent=playing?'■ Stop':'▶ Play';if(playing){const a=ac();step=0;nextT=a.currentTime+.05;}else{cur=-1;paint()}});c.loop(()=>sched());
  const bs=el('input',{type:'range',min:70,max:170,value:bpm,style:'width:160px'});const bl=el('b');c.on(bs,'input',()=>{bpm=+bs.value;save();bl.textContent=bpm+' BPM'});
  const sw=el('button',{class:'btn',type:'button'},'Swing: off');sw.addEventListener('click',()=>{swing=!swing;sw.textContent='Swing: '+(swing?'on':'off')});
  const clr=el('button',{class:'btn',type:'button'},'Clear');clr.addEventListener('click',()=>{grid=grid.map(r=>r.map(()=>false));save();paint()});
  const rnd=el('button',{class:'btn',type:'button'},'🎲 Surprise me');rnd.addEventListener('click',()=>{const pr=[.9,.3,.15,.6,.15,.1,.4,.25];grid=grid.map((r,ri)=>r.map((_,i)=>ri===0?i%4===0||Math.random()<.12:ri===1?i%8===4:Math.random()<pr[ri]*(i%2?.5:1)));ch=pick([[0,7,9,5],[9,5,0,7],[0,5,7,5],[2,9,7,0],[9,7,5,4]]);save();paint()});
  const pre=el('div',{class:'row',style:'flex-wrap:wrap;gap:6px;justify-content:center'});Object.keys(BM_PRE).forEach(n=>{const b=el('button',{class:'btn',type:'button',style:'font-size:14px;padding:6px 11px'},n);b.addEventListener('click',()=>load(n));pre.append(b)});
  const CHN=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];const chRow=el('div',{class:'row',style:'flex-wrap:wrap;gap:6px;justify-content:center;align-items:center'});
  const tbl=el('div',{style:'display:grid;grid-template-columns:78px repeat(16,1fr);gap:4px;width:100%;user-select:none'});const cells=[];
  BM_ROWS.forEach(([n,col],r)=>{const lb=el('button',{type:'button',class:'btn',style:'font-size:12px;padding:4px 6px;min-height:0'},n);lb.addEventListener('click',()=>{if(!muted)trig(r,ac().currentTime,0)});tbl.append(lb);cells[r]=[];for(let s=0;s<ST;s++){const d=el('button',{type:'button','aria-label':n+' step '+(s+1),style:'aspect-ratio:1;min-width:0;border:2px solid #1D1A2F;border-radius:5px;cursor:pointer;padding:0'});d.addEventListener('pointerdown',e=>{e.preventDefault();grid[r][s]=!grid[r][s];if(grid[r][s]&&!muted)trig(r,ac().currentTime,s);save();paint()});tbl.append(d);cells[r][s]=d}});
  function paint(){bl.textContent=bpm+' BPM';BM_ROWS.forEach(([n,col],r)=>{for(let s=0;s<ST;s++){const on=grid[r][s];cells[r][s].style.background=on?col:(Math.floor(s/4)%2?'#3a3552':'#2e2a45');cells[r][s].style.outline=s===cur?'3px solid #FFFDF6':'none'}});chRow.innerHTML='';chRow.append(el('span',{style:'font-weight:800'},'Chords:'));ch.forEach((v,i)=>{const b=el('button',{class:'btn',type:'button',style:'font-size:14px;padding:6px 11px'},CHN[v%12]+([9,2,4].includes(v%12)?'m':''));b.addEventListener('click',()=>{ch[i]=(ch[i]+1)%12;save();paint()});chRow.append(b)})}
  if(!grid||grid.length!==R){load('Pop')}else paint();
  root.append(el('div',{class:'row',style:'flex-wrap:wrap;gap:8px;justify-content:center;align-items:center'},pb,bs,bl,sw,clr,rnd),pre,el('div',{class:'card',style:'width:100%;background:#1D1A2F;padding:10px'},tbl),chRow,el('p',{class:'hint'},'Tap squares to add sounds. Tap a row name to hear it. Tap a chord to change it; bass and synth follow the chords.'));
  c.stat('Beat Studio');return()=>{playing=false}}});
