/* ================= PHYSICS SMASH ================= */
let matterP=null;
function loadMatter(){if(window.Matter)return Promise.resolve(window.Matter);if(matterP)return matterP;matterP=new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/matter-js@0.19.0/build/matter.min.js';s.onload=()=>res(window.Matter);s.onerror=()=>{matterP=null;rej(new Error('physics failed'))};document.head.append(s)});return matterP}
function withMatter(root,c,start){const ld=el('div',{class:'g3load'},el('b',null,'Loading physics…'),el('small',null,'Warming up the smashing engine.'));root.append(ld);let dead=false,cleanup=null;
  loadMatter().then(()=>{if(dead)return;ld.remove();try{cleanup=start()}catch(err){root.append(el('p',{class:'hint'},'This game hit an error: '+err.message));console.error(err)}}).catch(()=>{if(dead)return;ld.innerHTML='';ld.append(el('b',null,'Couldn’t load the physics engine'),el('small',null,'Check your internet connection, then reopen this game.'))});
  return()=>{dead=true;cleanup&&cleanup()}}
const PMAT={glass:{col:'#9fd6ff',hp:3,d:.0012,pts:15,snd:'glass'},wood:{col:'#FF9F43',hp:10,d:.0016,pts:10,snd:'wood'},brick:{col:'#F2352A',hp:15,d:.0022,pts:12,snd:'thud'},stone:{col:'#8c86a3',hp:26,d:.003,pts:20,snd:'thud'},concrete:{col:'#d8d4e4',hp:34,d:.0032,pts:25,snd:'thud'},plastic:{col:'#B9A7FF',hp:6,d:.001,pts:12,snd:'wood'},ceramic:{col:'#FF8FB1',hp:2.2,d:.0014,pts:25,snd:'glass'},tv:{col:'#3a3552',hp:5,d:.0018,pts:40,snd:'glass'}};
function PhysWorld(root,c,o){const Mt=window.Matter;const{Engine,Bodies,Composite,Body,Events,Vector,Query}=Mt;const W=o.w||960,H=o.h||600;
  const cv=el('canvas',{class:'board',width:W,height:H,style:'width:100%;cursor:'+(o.cursor||'crosshair')});root.append(cv);const x=cv.getContext('2d');
  const engine=Engine.create();engine.positionIterations=8;engine.velocityIterations=6;const world=engine.world;
  const pw={Mt,engine,world,cv,x,W,H,pops:[],frags:[],dust:[],steps:[],draws:[],under:[],broke:null,t:0,shake:0};
  pw.add=b=>{Composite.add(world,b);return b};pw.remove=b=>{Composite.remove(world,b)};
  pw.ground=(y,col)=>{const g=pw.add(Bodies.rectangle(W/2,y+60,W*3,120,{isStatic:true,friction:.9}));g.plugin.col=col||'#5A5470';g.plugin.ground=1;return g};
  pw.wall=(xx)=>{const w=pw.add(Bodies.rectangle(xx,H/2-400,100,H+1200,{isStatic:true}));w.plugin.hidden=1;return w};
  pw.block=(bx0,by,w,h,mat,opt)=>{const m=PMAT[mat];const b=pw.add(Bodies.rectangle(bx0,by,w,h,Object.assign({density:m.d,friction:.7,restitution:.05,frictionAir:.005},opt||{})));b.plugin.mat=mat;b.plugin.hp=b.plugin.max=m.hp*Math.sqrt(w*h/1600);b.plugin.col=m.col;b.plugin.brk=1;b.plugin.w=w;b.plugin.h=h;return b};
  pw.pop=(t,px,py,col,big)=>{pw.pops.push({t,x:px,y:py,col:col||'#FFD23F',l:.9,r:(Math.random()-.5)*.4,big})};
  pw.puff=(px,py,n,col)=>{for(let i=0;i<(n||6);i++)pw.dust.push({x:px,y:py,vx:(Math.random()-.5)*4,vy:(Math.random()-.5)*4-1,r:4+Math.random()*8,l:.6+Math.random()*.4,col:col||'rgba(216,212,228,.9)'})};
  const toBreak=[];
  function hit(t,oth,rv){if(!t.plugin.brk||t.isStatic||t.plugin.dead)return;const om=oth.isStatic?t.mass*1.5:oth.mass;const dmg=Math.max(0,rv-(o.thresh||2.2))*Math.min(5,om/t.mass+.25)*(oth.plugin.power||1)*(o.dmgMul||1);if(dmg<=0)return;t.plugin.hp-=dmg;if(t.plugin.hp<=0){t.plugin.dead=1;toBreak.push(t)}}
  Events.on(engine,'collisionStart',e=>{for(const p of e.pairs){const a=p.bodyA.parent,b=p.bodyB.parent;if(a.plugin.frag&&b.plugin.frag)continue;const rv=Vector.magnitude(Vector.sub(a.velocity,b.velocity));if(rv<1.5)continue;hit(a,b,rv);hit(b,a,rv);if(o.onHit)o.onHit(a,b,rv,p)}});
  pw.shatter=(b,quiet)=>{if(b.plugin.gone)return;b.plugin.gone=1;pw.remove(b);const m=PMAT[b.plugin.mat]||{col:b.plugin.col,pts:5,snd:'thud'};const w=b.plugin.w||30,h=b.plugin.h||30;const n=clamp(Math.round(w*h/500),3,9);
    for(let i=0;i<n;i++){const s=Math.max(5,Math.sqrt(w*h/n)*.75);const lx=(Math.random()-.5)*w*.7,ly=(Math.random()-.5)*h*.7;const ca=Math.cos(b.angle),sa=Math.sin(b.angle);const f=Bodies.polygon(b.position.x+lx*ca-ly*sa,b.position.y+lx*sa+ly*ca,3+rand(2),s*.6,{density:.001,frictionAir:.01,collisionFilter:{group:-7}});Body.setVelocity(f,{x:b.velocity.x+(Math.random()-.5)*6,y:b.velocity.y+(Math.random()-.5)*6-2});Body.setAngularVelocity(f,(Math.random()-.5)*.4);f.plugin.frag=1;f.plugin.col=b.plugin.col;f.plugin.l=2.2+Math.random();pw.add(f);pw.frags.push(f)}
    pw.puff(b.position.x,b.position.y,6);if(!quiet){if(m.snd==='glass'){noise(.18,'highpass',3000,.12);beep(2400+Math.random()*800,.05,'triangle',.03)}else if(m.snd==='wood')noise(.14,'bandpass',900,.14);else noise(.2,'lowpass',400,.18)}
    if(pw.broke)pw.broke(b,m)};
  pw.explode=(px,py,R,pow,dmgR)=>{pw.shake=Math.max(pw.shake,14);noise(.6,'lowpass',260,.4);pw.pop(pick(['KA-BOOM!','BLAM!','KRAKOOM!']),px,py-20,'#FFD23F',1);for(let i=0;i<22;i++)pw.dust.push({x:px,y:py,vx:(Math.random()-.5)*14,vy:(Math.random()-.5)*14,r:6+Math.random()*14,l:.5+Math.random()*.5,col:pick(['#FFD23F','#FF9F43','#F2352A','rgba(90,84,112,.8)'])});
    Composite.allBodies(world).forEach(b=>{if(b.isStatic)return;const d=Vector.sub(b.position,{x:px,y:py});const L=Vector.magnitude(d)||1;if(L>R)return;const k=(1-L/R);if(b.plugin.brk&&L<(dmgR||R*.35)){b.plugin.hp-=40*k+10;if(b.plugin.hp<=0&&!b.plugin.dead){b.plugin.dead=1;toBreak.push(b)}}Body.setVelocity(b,{x:b.velocity.x+d.x/L*pow*k,y:b.velocity.y+d.y/L*pow*k-pow*k*.3});Body.setAngularVelocity(b,b.angularVelocity+(Math.random()-.5)*.3*k)})};
  function drawBody(b){if(b.plugin.hidden)return;if(b.plugin.emoji){x.save();x.globalAlpha=b.plugin.l!=null&&b.plugin.l<1?Math.max(0,b.plugin.l):1;x.translate(b.position.x,b.position.y);x.rotate(b.angle+(b.plugin.erot||0));x.font=(b.plugin.esz||32)+'px sans-serif';x.textAlign='center';x.textBaseline='middle';x.fillText(b.plugin.emoji,0,b.plugin.eoy||0);x.restore();x.globalAlpha=1;return}if(b.plugin.draw){b.plugin.draw(x,b);if(b.plugin.face)b.plugin.face(x,b);return}const parts=b.parts.length>1?b.parts.slice(1):[b];x.globalAlpha=b.plugin.frag?clamp(b.plugin.l,0,1):1;
    parts.forEach(p=>{x.beginPath();if(p.circleRadius){x.arc(p.position.x,p.position.y,p.circleRadius,0,7)}else{const v=p.vertices;x.moveTo(v[0].x,v[0].y);for(let i=1;i<v.length;i++)x.lineTo(v[i].x,v[i].y);x.closePath()}x.fillStyle=p.plugin.col||b.plugin.col||'#8c86a3';x.fill();x.lineWidth=b.plugin.frag?2:3;x.strokeStyle='#1D1A2F';x.stroke()});
    if(b.plugin.brk&&b.plugin.hp<b.plugin.max*.6&&!b.circleRadius){x.save();x.translate(b.position.x,b.position.y);x.rotate(b.angle);x.strokeStyle='rgba(29,26,47,.6)';x.lineWidth=2;x.beginPath();const w=(b.plugin.w||20)/2,h=(b.plugin.h||20)/2;x.moveTo(-w*.6,-h*.5);x.lineTo(w*.1,h*.1);x.lineTo(-w*.1,h*.6);x.moveTo(w*.1,h*.1);x.lineTo(w*.6,-h*.3);x.stroke();x.restore()}
    if(b.plugin.mat==='glass'&&!b.plugin.frag){x.save();x.translate(b.position.x,b.position.y);x.rotate(b.angle);x.strokeStyle='rgba(255,255,255,.8)';x.lineWidth=2;x.beginPath();const w=(b.plugin.w||20)/2,h=(b.plugin.h||20)/2;x.moveTo(-w*.5,h*.4);x.lineTo(w*.2,-h*.5);x.stroke();x.restore()}
    if(b.plugin.face)b.plugin.face(x,b);x.globalAlpha=1}
  pw.draw=()=>{x.save();if(pw.shake>0){x.translate((Math.random()-.5)*pw.shake,(Math.random()-.5)*pw.shake);pw.shake*=.85;if(pw.shake<.5)pw.shake=0}
    const g=x.createLinearGradient(0,0,0,H);g.addColorStop(0,o.sky||'#7FC8F8');g.addColorStop(1,o.sky2||'#FFE9B8');x.fillStyle=g;x.fillRect(-20,-20,W+40,H+40);x.fillStyle='rgba(255,255,255,.25)';for(let yy=0;yy<H;yy+=14)for(let xx=(yy/14%2)*7;xx<W;xx+=14){x.beginPath();x.arc(xx,yy,1+yy/H*2.2,0,7);x.fill()}
    pw.under.forEach(f=>f(x));Composite.allBodies(world).forEach(drawBody);pw.draws.forEach(f=>f(x));
    pw.dust.forEach(d=>{x.globalAlpha=clamp(d.l,0,1);x.fillStyle=d.col;x.beginPath();x.arc(d.x,d.y,d.r*(1.4-d.l*.4),0,7);x.fill()});x.globalAlpha=1;
    pw.pops.forEach(p=>{const k=1-p.l/.9;x.save();x.translate(p.x,p.y-k*30);x.rotate(p.r);const s=(p.big?1.6:1)*(k<.2?k/.2*1.2:1);x.scale(s,s);x.globalAlpha=clamp(p.l*2,0,1);x.font='32px "Bagel Fat One", "Arial Black", sans-serif';x.textAlign='center';x.lineWidth=6;x.strokeStyle='#1D1A2F';x.strokeText(p.t,0,0);x.fillStyle=p.col;x.fillText(p.t,0,0);x.restore()});x.globalAlpha=1;x.restore()};
  let acc=0;c.loop(dt=>{acc=Math.min(acc+dt,50);while(acc>=16.667){Engine.update(engine,16.667);pw.t+=16.667;pw.steps.forEach(f=>f());while(toBreak.length)pw.shatter(toBreak.shift());acc-=16.667}
    const s=dt/1000;for(let i=pw.frags.length-1;i>=0;i--){const f=pw.frags[i];f.plugin.l-=s;if(f.plugin.l<=0||f.position.y>H+200){pw.remove(f);pw.frags.splice(i,1)}}
    for(let i=pw.dust.length-1;i>=0;i--){const d=pw.dust[i];d.l-=s;d.x+=d.vx;d.y+=d.vy;d.vx*=.92;d.vy*=.92;if(d.l<=0)pw.dust.splice(i,1)}for(let i=pw.pops.length-1;i>=0;i--){pw.pops[i].l-=s;if(pw.pops[i].l<=0)pw.pops.splice(i,1)}pw.draw()});
  pw.pos=e=>canvasPos(cv,e);
  pw.clear=()=>{Composite.clear(world,false,true);pw.frags=[];pw.dust=[];pw.pops=[]};
  return pw}
function phBanner(x,W,H,t1,t2){x.fillStyle='rgba(29,26,47,.78)';x.fillRect(0,H/2-70,W,140);x.textAlign='center';x.font='44px "Bagel Fat One", sans-serif';x.lineWidth=6;x.strokeStyle='#1D1A2F';x.strokeText(t1,W/2,H/2);x.fillStyle='#FFD23F';x.fillText(t1,W/2,H/2);x.fillStyle='#FFFDF6';x.font='600 20px Figtree, sans-serif';x.fillText(t2,W/2,H/2+40)}
function towerAt(pw,cx,base,floors,wid,mats){const bs=[];let y=base;const colW=18,colH=64,slab=16;for(let f=0;f<floors;f++){const m=mats?pick(mats):pick(['wood','brick','stone','concrete']);bs.push(pw.block(cx-wid/2+colW/2,y-colH/2,colW,colH,m));bs.push(pw.block(cx+wid/2-colW/2,y-colH/2,colW,colH,m));if(wid>90){bs.push(pw.block(cx,y-colH/2,10,colH-4,'glass'))}y-=colH;bs.push(pw.block(cx,y-slab/2,wid+8,slab,f%2?'concrete':m));y-=slab}if(Math.random()<.6)bs.push(pw.block(cx,y-14,wid*.5,28,'glass'));return bs}

G.push({id:'ph_wreck',name:'Wrecking Ball',kind:'smash',wide:true,tint:'#FFD23F',blurb:'Swing a crane’s wrecking ball through a city block. Wreck as much as you can before the whistle.',fmt:b=>b+' pts',
art:'<rect width="120" height="72" fill="#FFD23F"/><path d="M0 8h120" stroke="#1D1A2F" stroke-width="4"/><rect x="34" y="4" width="16" height="9" fill="#FF9F43" stroke="#1D1A2F" stroke-width="2.5"/><path d="M42 12L60 44" stroke="#1D1A2F" stroke-width="2.5"/><circle cx="62" cy="48" r="11" fill="#3a3552" stroke="#1D1A2F" stroke-width="3"/><g stroke="#1D1A2F" stroke-width="2.5"><rect x="80" y="34" width="12" height="38" fill="#F2352A"/><rect x="94" y="26" width="16" height="46" fill="#8c86a3"/><rect x="72" y="52" width="8" height="20" fill="#9fd6ff"/></g><path d="M74 40l-4-6M76 46l-6 0" stroke="#fff" stroke-width="2.5" stroke-linecap="round"/>',
run(root,c){return withMatter(root,c,()=>{
  const hint=el('p',{class:'hint'},'Move the mouse (or drag, or ← →) to drive the crane. Scroll or W/S to lengthen or shorten the cable. Each contract needs a bigger share of the block wrecked, and from contract 3 there’s a green museum you must not hit.');
  let grace=0,st2=false,score=0,tLeft=45,state='play',blocks=[],total=0,broken=0,trolley=480,tx=480,L=250,lv=S.get('wreck_lv',1),keep=[],keepHit=0,goal=60;
  const pw=PhysWorld(root,c,{sky:'#9fd6ff',sky2:'#FFE9B8',onHit:(a,b,rv)=>{if((a===ball||b===ball)&&rv>9){pw.pop(pick(['WHAM!','KRUNCH!','SMASH!','BLAM!']),ball.position.x,ball.position.y-40);pw.shake=Math.max(pw.shake,rv*.5)}}});root.append(hint);
  const{Bodies,Constraint,Composite,Body}=pw.Mt;const{W,H}=pw;pw.ground(H-30,'#5A5470');pw.wall(-50);pw.wall(W+50);{const row=el('div',{class:'row'});[['⬆ Raise ball',-45],['⬇ Lower ball',45]].forEach(([t,dl])=>{const b=el('button',{class:'btn',type:'button'},t);b.addEventListener('click',()=>{L=clamp(L+dl,110,492)});row.append(b)});root.insertBefore(row,hint)}
  const ball=pw.add(Bodies.circle(480,300,34,{density:.05,frictionAir:.001,restitution:.15}));ball.plugin.col='#3a3552';ball.plugin.power=1.6;ball.plugin.face=(x,b)=>{x.fillStyle='rgba(255,255,255,.35)';x.beginPath();x.arc(b.position.x-10,b.position.y-10,9,0,7);x.fill()};
  const rope=pw.add(Constraint.create({pointA:{x:480,y:40},bodyB:ball,length:L,stiffness:.95,damping:.02}));
  function build(){[...blocks,...keep].forEach(b=>{if(!b.plugin.gone)pw.remove(b)});blocks=[];keep=[];keepHit=0;goal=Math.min(92,55+lv*4);const mats=lv<3?['wood','brick']:lv<6?['brick','stone','wood']:['stone','concrete','brick'];const n=3+rand(2);const kI=lv>=3?rand(n):-1;for(let i=0;i<n;i++){const cx=260+i*(620/n)+rand(40);if(i===kI){const kb=towerAt(pw,cx,H-30,2,90,['plastic']);kb.forEach(b=>{b.plugin.keep=1;b.plugin.col='#6EE7B7';b.plugin.hp=b.plugin.max=b.plugin.hp*3});keep.push(...kb)}else blocks.push(...towerAt(pw,cx,H-30,3+rand(Math.min(6,3+lv)),90+rand(70),mats))}total=blocks.length;broken=0;ball.plugin.power=1.6+Math.min(1.2,lv*.08);tLeft=Math.max(35,50-lv);grace=1.5;Body.setPosition(ball,{x:trolley,y:40+L});Body.setVelocity(ball,{x:0,y:0})}
  pw.broke=(b,m)=>{if(b.plugin.keep){if(grace>0)return;keepHit++;score=Math.max(0,score-300);pw.pop('MUSEUM! −300',b.position.x,b.position.y-20,'#F2352A',1);beep(160,.3,'sawtooth',.06);return}if(blocks.includes(b)){broken++;score+=m.pts;if(Math.random()<.25)pw.pop('+'+m.pts,b.position.x,b.position.y,'#fff')}};
  pw.under.push(x=>{x.fillStyle='#1D1A2F';x.fillRect(0,32,W,10);x.strokeStyle='#FFD23F';x.lineWidth=2;for(let i=0;i<W;i+=24){x.beginPath();x.moveTo(i,33);x.lineTo(i+12,41);x.stroke()}});
  pw.draws.push(x=>{const tp=rope.pointA;x.strokeStyle='#1D1A2F';x.lineWidth=4;x.beginPath();x.moveTo(tp.x,tp.y);x.lineTo(ball.position.x,ball.position.y);x.stroke();x.fillStyle='#FF9F43';x.strokeStyle='#1D1A2F';x.lineWidth=3;x.fillRect(tp.x-26,22,52,24);x.strokeRect(tp.x-26,22,52,24);
    x.font='700 16px "JetBrains Mono", monospace';x.textAlign='left';x.fillStyle='#1D1A2F';x.fillText('CONTRACT '+lv+'   TIME '+Math.ceil(Math.max(0,tLeft))+'s   SCORE '+score+'   WRECKED '+Math.round((broken/Math.max(1,total))*100)+'% / '+goal+'%'+(keep.length?'   MUSEUM HITS '+keepHit+'/3':''),16,70);if(keep.length&&state==='play'){const k0=keep.find(b=>!b.plugin.gone);if(k0){x.fillStyle='#1D1A2F';x.font='700 13px Figtree, sans-serif';x.textAlign='center';x.fillText('🏛️ MUSEUM: DON’T WRECK',k0.position.x,k0.bounds.min.y-50)}}
    if(state==='over'){const pc=Math.round(broken/Math.max(1,total)*100);const ok=pc>=goal&&keepHit<3;phBanner(x,W,H,ok?'Contract '+lv+' complete! '+pc+'%':keepHit>=3?'You wrecked the museum!':'Only '+pc+'% (needed '+goal+'%)',ok?'Score '+score+' · click for contract '+(lv+1):'Click to try contract '+lv+' again')}});
  const setX=e=>{const p=pw.pos(e);tx=clamp(p.x,30,W-30)};c.on(pw.cv,'pointermove',setX);c.on(pw.cv,'pointerdown',e=>{setX(e);if(state==='over')reset()});c.on(pw.cv,'wheel',e=>{L=clamp(L+Math.sign(e.deltaY)*20,110,492);e.preventDefault()},{passive:false});
  const keys={};c.on(document,'keydown',e=>{keys[e.key.toLowerCase()]=true});c.on(document,'keyup',e=>{keys[e.key.toLowerCase()]=false});
  pw.steps.push(()=>{if(keys.arrowleft||keys.a)tx=clamp(tx-9,30,W-30);if(keys.arrowright||keys.d)tx=clamp(tx+9,30,W-30);if(keys.w||keys.arrowup)L=clamp(L-4,110,492);if(keys.s||keys.arrowdown)L=clamp(L+4,110,492);trolley+=(tx-trolley)*.12;rope.pointA.x=trolley;rope.length+=(L-rope.length)*.1;
    grace-=1/60;if(state==='play'){tLeft-=1/60;if(tLeft<=0||broken>=total||keepHit>=3){state='over';st2=(Math.round(broken/Math.max(1,total)*100)>=goal&&keepHit<3);if(st2){S.set('wreck_lv',lv+1)}score+=broken>=total?Math.round(Math.max(0,tLeft)*50):0;c.best(score);beep(523,.2,'triangle');c.after(()=>beep(784,.3,'triangle'),160)}}c.stat('Wrecking Ball · '+score+' pts · '+Math.ceil(Math.max(0,tLeft))+'s')});
  function reset(){if(st2){lv++;st2=false}score=0;state='play';build();Body.setPosition(ball,{x:trolley,y:40+L});Body.setVelocity(ball,{x:0,y:0})}
  build();})}});

G.push({id:'ph_castle',name:'Castle Crash',kind:'smash',wide:true,tint:'#6EE7B7',blurb:'Slingshot boulders, bombs, drills and triple-shots at 15+ castles full of grumpy Grumps. Helmets, kings, TNT and wind.',fmt:b=>b+' pts',
art:'<rect width="120" height="72" fill="#6EE7B7"/><rect y="62" width="120" height="10" fill="#5A5470"/><path d="M18 62V40M18 40l-6-8M18 40l6-8" stroke="#8a5a2b" stroke-width="4" stroke-linecap="round"/><circle cx="44" cy="24" r="6" fill="#3a3552" stroke="#1D1A2F" stroke-width="2.5"/><path d="M30 34q6-10 14-10" fill="none" stroke="#1D1A2F" stroke-width="2" stroke-dasharray="3 3"/><g stroke="#1D1A2F" stroke-width="2.5"><rect x="72" y="36" width="8" height="26" fill="#FF9F43"/><rect x="100" y="36" width="8" height="26" fill="#FF9F43"/><rect x="68" y="30" width="44" height="7" fill="#8c86a3"/><rect x="84" y="46" width="12" height="16" fill="#F2352A"/></g><circle cx="90" cy="22" r="8" fill="#2BB673" stroke="#1D1A2F" stroke-width="2.5"/><path d="M84 16l3-5 3 4 3-4 3 5z" fill="#FFD23F" stroke="#1D1A2F" stroke-width="1.5"/>',
run(root,c){return withMatter(root,c,()=>{
  const lvRow=el('div',{class:'row',style:'flex-wrap:wrap;gap:4px'});const hint=el('p',{class:'hint'},'Drag back from the slingshot and let go. Click while a bomb, triple-shot or drill is flying to use its power. Red TNT crates explode when hit.');
  const pw=PhysWorld(root,c,{sky:'#7FC8F8',sky2:'#e8fff4',cursor:'grab'});root.insertBefore(lvRow,pw.cv);root.append(hint);const{Bodies,Body,Composite,Vector}=pw.Mt;const{W,H}=pw;
  pw.ground(H-40,'#2BB673');pw.wall(-60);pw.wall(W+60);
  const SL={x:140,y:H-150},BASE=H-40;let stars=S.get('castle_stars',[]),lvl=Math.min(stars.length+1,S.get('castle_lv',1)),score=0,ammo=[],shot=null,drag=null,grumps=[],blocks=[],wait=0,state='aim',msgT=0,used=false,extra=[],wind=0,startAmmo=0,lvScore=0;
  const AM={b:{r:16,col:'#3a3552',label:'Cannonball',d:.02,pow:1.5},h:{r:23,col:'#5A5470',label:'Heavy boulder: smashes stone',d:.035,pow:2.4},B:{r:17,col:'#F2352A',label:'Bomb: click to blow up',d:.02,pow:1.5},t:{r:12,col:'#FFD23F',label:'Triple: click to split',d:.02,pow:1.5},d:{r:13,col:'#7FC8F8',label:'Drill: click to dash forward',d:.03,pow:4}};
  const GT={n:{r:16,hp:2.5,col:'#2BB673',pts:500},h:{r:17,hp:8,col:'#2BB673',pts:800},k:{r:25,hp:16,col:'#6EE7B7',pts:1500}};
  function grump(xx,y0,type){const g0=GT[type||'n'];const g=pw.add(Bodies.circle(xx,y0-g0.r,g0.r,{density:.0015,friction:.6,restitution:.2}));g.plugin.col=g0.col;g.plugin.brk=1;g.plugin.hp=g.plugin.max=g0.hp;g.plugin.grump=type||'n';
    g.plugin.face=(x,b)=>{const s=g0.r/16;x.save();x.translate(b.position.x,b.position.y);x.rotate(b.angle);x.scale(s,s);x.fillStyle='#fff';[-6,6].forEach(q=>{x.beginPath();x.arc(q,-3,4.2,0,7);x.fill()});x.fillStyle='#1D1A2F';[-6,6].forEach(q=>{x.beginPath();x.arc(q,-2,2,0,7);x.fill()});x.strokeStyle='#1D1A2F';x.lineWidth=2.5;x.beginPath();x.moveTo(-10,-10);x.lineTo(-3,-7);x.moveTo(10,-10);x.lineTo(3,-7);x.moveTo(-5,8);x.quadraticCurveTo(0,4,5,8);x.stroke();
      if(b.plugin.grump==='h'){x.fillStyle=b.plugin.hp<b.plugin.max*.5?'#5A5470':'#8c86a3';x.beginPath();x.arc(0,-6,15,Math.PI,0);x.closePath();x.fill();x.stroke()}
      if(b.plugin.grump==='k'){x.fillStyle='#FFD23F';x.beginPath();x.moveTo(-11,-12);x.lineTo(-11,-24);x.lineTo(-5,-17);x.lineTo(0,-26);x.lineTo(5,-17);x.lineTo(11,-24);x.lineTo(11,-12);x.closePath();x.fill();x.lineWidth=2;x.stroke()}
      if(b.plugin.hp<b.plugin.max*.6){x.strokeStyle='rgba(29,26,47,.6)';x.lineWidth=1.5;x.beginPath();x.moveTo(-12,4);x.lineTo(-6,10);x.stroke()}x.restore()};grumps.push(g);return g}
  const P=(x,y,w,h,m)=>{const b=pw.block(x,y,w,h,m);blocks.push(b);return b};
  const col=(x,y0,h,m)=>P(x,y0-h/2,18,h,m||'wood');const slab=(x,y0,w,m)=>{P(x,y0-8,w,16,m||'wood');return y0-16};const box=(x,y0,s,m)=>{P(x,y0-s/2,s,s,m||'wood');return y0-s};
  function frame(cx,y0,w,h,m,roof){col(cx-w/2+9,y0,h,m);col(cx+w/2-9,y0,h,m);return slab(cx,y0-h,w+10,roof||m)}
  function tower(cx,y0,floors,w,mats,gtype){let y=y0;for(let f=0;f<floors;f++){const m=mats[f%mats.length];const top=frame(cx,y,w,64,m,f%2?'concrete':m);if(gtype&&f<floors)grump(cx,y,f===0?gtype:'n');y=top}return y}
  function pyramid(cx,y0,rows,m,s){s=s||34;for(let r=0;r<rows;r++){const n=rows-r;for(let i=0;i<n;i++)box(cx+(i-(n-1)/2)*s,y0-r*s,s,m)}return y0-rows*s}
  function tnt(x,y0){const b=P(x,y0-16,32,32,'wood');b.plugin.tnt=1;b.plugin.col='#F2352A';b.plugin.hp=b.plugin.max=3;b.plugin.face=(q,bb)=>{q.save();q.translate(bb.position.x,bb.position.y);q.rotate(bb.angle);q.fillStyle='#fff';q.font='900 11px Figtree, sans-serif';q.textAlign='center';q.textBaseline='middle';q.fillText('TNT',0,1);q.restore()};return b}
  const LV=[
    ()=>{const t=frame(640,BASE,120,70,'wood');grump(640,BASE);grump(640,t);return['bbb',0]},
    ()=>{let t=frame(560,BASE,100,70,'wood');grump(560,BASE);t=frame(760,BASE,100,70,'glass','wood');grump(760,BASE);grump(760,t);return['bbt',0]},
    ()=>{const t=pyramid(620,BASE,4,'wood');grump(620,t);frame(820,BASE,90,90,'brick');grump(820,BASE);return['bBb',0]},
    ()=>{const t=tower(700,BASE,3,110,['wood','brick'],'n');grump(700,t);return['bhbt',0]},
    ()=>{const t=frame(700,BASE,130,80,'stone','concrete');grump(700,BASE,'h');tnt(610,BASE);tnt(790,BASE);grump(700,t);return['hBb',0]},
    ()=>{frame(560,BASE,80,160,'brick');frame(840,BASE,80,160,'brick');const y=slab(700,BASE-176,380,'wood');grump(640,y);grump(760,y);tnt(700,BASE);grump(700,BASE-32);return['btdb',0]},
    ()=>{col(520,BASE,150,'stone');col(540,BASE,150,'stone');slab(530,BASE-150,60,'concrete');const t=frame(720,BASE,120,70,'brick','stone');grump(720,BASE,'h');grump(720,t,'k');frame(860,BASE,70,60,'wood');grump(860,BASE);return['hhBd',0]},
    ()=>{[600,700,800,890].forEach((x,i)=>{const t=tower(x,BASE,2+(i%2),60,['glass','wood']);grump(x,t)});return['tttb',1.4]},
    ()=>{const t1=pyramid(600,BASE,4,'stone');grump(600,t1,'h');tnt(730,BASE);const t2=pyramid(860,BASE,3,'stone');grump(860,t2,'h');grump(730,BASE-32);return['hdBb',0]},
    ()=>{tower(560,BASE,2,80,['stone']);const t=tower(720,BASE,3,110,['concrete','stone'],'h');grump(720,t,'k');tower(880,BASE,2,80,['stone']);grump(560,BASE-160);grump(880,BASE-160);return['hBdtb',-1.2]}];
  function gen(n){const mats=[['wood','brick'],['brick','stone'],['stone','concrete']][Math.min(2,Math.floor(n/4))];const k=2+Math.min(3,Math.floor(n/3));const span=(W-500)/k;let hard=0;
    for(let i=0;i<k;i++){const cx=520+i*span+span/2;const r=Math.random();if(r<.35){const t=tower(cx,BASE,2+rand(Math.min(3,1+n/3|0)),70+rand(40),mats,Math.random()<.5?'h':'n');grump(cx,t,Math.random()<.25?'k':'n')}else if(r<.6){const t=pyramid(cx,BASE,3+rand(2),pick(mats),30);grump(cx,t,'h')}else if(r<.8){const t=frame(cx,BASE,100,90,pick(mats),'concrete');grump(cx,BASE,'h');grump(cx,t)}else{tnt(cx-20,BASE);tnt(cx+20,BASE);tnt(cx,BASE-32);grump(cx,BASE-64)}hard++}
    const am=shuffle(['h','B','d','t','b','h']).slice(0,Math.max(3,6-Math.floor(n/3)));return[am.join(''),n>2?(Math.random()<.5?-1:1)*(.6+Math.random()*1.4):0]}
  function build(){Composite.allBodies(pw.world).forEach(b=>{if(!b.isStatic)pw.remove(b)});grumps=[];blocks=[];extra=[];lvScore=0;const def=lvl<=LV.length?LV[lvl-1]():gen(lvl-LV.length+3);ammo=def[0].split('');wind=def[1];startAmmo=ammo.length;state='aim';shot=null;msgT=1.8;renderLv()}
  function renderLv(){lvRow.innerHTML='';const maxL=Math.max(LV.length,stars.length+1);for(let i=1;i<=maxL;i++){const open=i<=stars.length+1;const st=stars[i-1]||0;const b=el('button',{class:'btn'+(i===lvl?' on':''),type:'button',style:'padding:4px 9px;font-size:13px'},(open?i:'🔒')+(st?' '+'★'.repeat(st):''));b.disabled=!open;b.addEventListener('click',()=>{lvl=i;S.set('castle_lv',lvl);build()});lvRow.append(b)}}
  pw.broke=(b,m)=>{if(b.plugin.grump){const g0=GT[b.plugin.grump];score+=g0.pts;lvScore+=g0.pts;pw.pop('+'+g0.pts,b.position.x,b.position.y-10,'#6EE7B7',1);beep(300,.15,'square',.06);grumps=grumps.filter(g=>g!==b)}else{score+=m.pts;lvScore+=m.pts;if(b.plugin.tnt){c.after(()=>pw.explode(b.position.x,b.position.y,160,14,80),30)}}};
  function mkShot(t,pos,v,r){const a=AM[t];const b=pw.add(Bodies.circle(pos.x,pos.y,r||a.r,{density:a.d,frictionAir:0,restitution:t==='d'?.05:.3}));b.plugin.col=a.col;b.plugin.power=a.pow;b.plugin.kind=t;Body.setVelocity(b,v);return b}
  function fire(v){const t=ammo.shift();shot=mkShot(t,SL,v);used=false;state='fly';wait=0;sweep(300,900,.25,'sawtooth',.06)}
  function power(){if(!shot||used)return;const k=shot.plugin.kind;if(k==='b'||k==='h')return;used=true;if(k==='B'){pw.explode(shot.position.x,shot.position.y,170,16,70);pw.remove(shot)}else if(k==='t'){[-.25,.25].forEach(a=>{extra.push(mkShot('t',shot.position,Vector.rotate(shot.velocity,a)))});pw.pop('SPLIT!',shot.position.x,shot.position.y-20);beep(900,.1,'triangle',.06)}else if(k==='d'){const v=shot.velocity,L=Vector.magnitude(v)||1;Body.setVelocity(shot,Vector.mult(v,22/L));shot.plugin.power=7;pw.pop('DRILL!',shot.position.x,shot.position.y-20,'#7FC8F8');sweep(400,1600,.3,'sawtooth',.06)}}
  const pull=p=>{const d=Vector.sub(p,SL);const L=Math.min(110,Vector.magnitude(d));return Vector.mult(Vector.normalise(d),L)};
  c.on(pw.cv,'pointerdown',e=>{const p=pw.pos(e);if(state==='over'){build();return}if(state==='won'){lvl++;S.set('castle_lv',lvl);build();return}if(state==='fly'){power();return}if(state==='aim'&&ammo.length&&Math.hypot(p.x-SL.x,p.y-SL.y)<140){drag=p;pw.cv.setPointerCapture(e.pointerId)}});
  c.on(pw.cv,'pointermove',e=>{if(drag)drag=pw.pos(e)});c.on(pw.cv,'pointerup',()=>{if(drag){const d=pull(drag);drag=null;if(Vector.magnitude(d)>20)fire(Vector.mult(d,-.26))}});
  pw.under.push(x=>{x.strokeStyle='#8a5a2b';x.lineWidth=10;x.lineCap='round';x.beginPath();x.moveTo(SL.x,H-40);x.lineTo(SL.x,SL.y+30);x.moveTo(SL.x,SL.y+30);x.lineTo(SL.x-22,SL.y-10);x.moveTo(SL.x,SL.y+30);x.lineTo(SL.x+22,SL.y-10);x.stroke();x.lineCap='butt';
    if(wind){x.fillStyle='rgba(255,255,255,.7)';for(let i=0;i<14;i++){const yy=60+i*31,xx=((pw.t*.06*wind*60/Math.abs(wind)+i*137)%(W+80)+W+80)%(W+80)-40;x.fillRect(xx,yy,30,2)}}});
  pw.draws.push(x=>{if(state==='aim'&&ammo.length){const d=drag?pull(drag):{x:0,y:0};const bp=Vector.add(SL,d);x.strokeStyle='#1D1A2F';x.lineWidth=4;x.beginPath();x.moveTo(SL.x-22,SL.y-10);x.lineTo(bp.x,bp.y);x.lineTo(SL.x+22,SL.y-10);x.stroke();const a=AM[ammo[0]];x.fillStyle=a.col;x.beginPath();x.arc(bp.x,bp.y,a.r,0,7);x.fill();x.lineWidth=3;x.stroke();
      if(drag&&Vector.magnitude(d)>20){let p={x:bp.x,y:bp.y},v=Vector.mult(d,-.26);const n=lvl<=3?60:lvl<=7?34:20;x.fillStyle='rgba(29,26,47,.5)';for(let i=0;i<n;i++){p={x:p.x+v.x,y:p.y+v.y};v={x:v.x,y:v.y+.2778};if(i%4===0){x.beginPath();x.arc(p.x,p.y,3,0,7);x.fill()}}}}
    x.font='700 16px "JetBrains Mono", monospace';x.textAlign='left';x.fillStyle='#1D1A2F';x.fillText('LEVEL '+lvl+'   SCORE '+score+'   GRUMPS '+grumps.length+(wind?'   WIND '+(wind>0?'→':'←')+' '+Math.abs(wind).toFixed(1):''),16,30);ammo.forEach((a,i)=>{x.fillStyle=AM[a].col;x.beginPath();x.arc(24+i*30,54,AM[a].r*.6,0,7);x.fill();x.strokeStyle='#1D1A2F';x.lineWidth=2;x.stroke()});if(ammo.length&&state==='aim'){x.fillStyle='#1D1A2F';x.font='600 14px Figtree, sans-serif';x.fillText('Next: '+AM[ammo[0]].label,16+ammo.length*30,59)}
    if(msgT>0){x.textAlign='center';x.font='40px "Bagel Fat One", sans-serif';x.lineWidth=6;x.strokeStyle='#1D1A2F';const t='Level '+lvl+(wind?' · windy!':'');x.strokeText(t,W/2,120);x.fillStyle='#FFD23F';x.fillText(t,W/2,120)}
    if(state==='won'){const st=stars[lvl-1]||1;phBanner(x,W,H,'★'.repeat(st)+'☆'.repeat(3-st)+'  Castle crashed!','Score '+score+' · click for level '+(lvl+1))}if(state==='over')phBanner(x,W,H,'Out of ammo!','The Grumps are gloating. Click to retry level '+lvl)});
  pw.steps.push(()=>{msgT-=1/60;grumps.forEach(g=>{if(g.position.y>H+50&&!g.plugin.gone){pw.shatter(g)}});if(shot&&wind&&!shot.plugin.gone)Body.setVelocity(shot,{x:shot.velocity.x+wind*.012,y:shot.velocity.y});extra.forEach(b=>{if(wind)Body.setVelocity(b,{x:b.velocity.x+wind*.012,y:b.velocity.y})});
    if(state==='fly'){wait+=1/60;const sp=shot&&!shot.plugin.gone?Vector.magnitude(shot.velocity):0;const done=()=>{const left=ammo.length;score+=left*1000;const st=1+(left>=1?1:0)+(left>=2?1:0);stars[lvl-1]=Math.max(stars[lvl-1]||0,st);S.set('castle_stars',stars);c.best(score);state='won';renderLv();[523,659,784].forEach((f,i)=>c.after(()=>beep(f,.2,'triangle',.07),i*120))};
      if(!grumps.length&&wait>1.2)done();else if(wait>8||(wait>3&&sp<.4)||(shot&&(shot.position.x>W+80||shot.position.x<-80))){if(shot&&!shot.plugin.gone)pw.remove(shot);extra.forEach(b=>pw.remove(b));extra=[];shot=null;if(!grumps.length)done();else if(!ammo.length){state='over';c.best(score);beep(200,.3,'sawtooth',.06)}else state='aim'}}
    c.stat('Castle Crash · Level '+lvl+' · '+score+' pts')});
  build()})}});

G.push({id:'ph_tnt',name:'Demolition',kind:'smash',wide:true,tint:'#FF9F43',blurb:'Stick TNT on a tower, hit the plunger, and flatten the whole thing below the line.',fmt:b=>'level '+b,
art:'<rect width="120" height="72" fill="#FF9F43"/><path d="M0 58h120" stroke="#F2352A" stroke-width="2.5" stroke-dasharray="6 4"/><g stroke="#1D1A2F" stroke-width="2.5"><rect x="44" y="12" width="34" height="60" fill="#d8d4e4"/><rect x="50" y="20" width="8" height="10" fill="#9fd6ff"/><rect x="64" y="20" width="8" height="10" fill="#9fd6ff"/><rect x="50" y="40" width="22" height="7" rx="2" fill="#F2352A"/></g><text x="61" y="46" font-family="Arial Black" font-size="6" fill="#fff" text-anchor="middle">TNT</text><path d="M20 72V56h12v16" fill="#FFD23F" stroke="#1D1A2F" stroke-width="2.5"/><path d="M26 56V46M20 46h12" stroke="#1D1A2F" stroke-width="3"/>',
run(root,c){return withMatter(root,c,()=>{
  const row=el('div',{class:'row'});const det=el('button',{class:'btn primary',type:'button'},'💥 Detonate');const rs=el('button',{class:'btn',type:'button'},'Reset tower');row.append(det,rs);
  const hint=el('p',{class:'hint'},'Click blocks to stick TNT on them (click again to remove). Then detonate. Everything has to end up below the red line, and from level 3 the green houses next door must survive.');
  const pw=PhysWorld(root,c,{sky:'#FFE27A',sky2:'#FFF6D8',thresh:3});root.append(row,hint);const{Bodies,Body,Composite,Query}=pw.Mt;const{W,H}=pw;
  pw.ground(H-30,'#5A5470');pw.wall(-60);pw.wall(W+60);
  let house=[],lvl=Math.max(1,S.get('tnt_lv',1)),blocks=[],charges=[],maxC=3,state='plan',settle=0,LINE=H-130,score=0;
  function build(){Composite.allBodies(pw.world).forEach(b=>{if(!b.isStatic)pw.remove(b)});blocks=[];charges=[];state='plan';maxC=lvl<3?3:lvl<6?2:2;const fl=2+Math.min(7,lvl);const wid=120+Math.min(4,lvl)*20;const cx=W/2;blocks.push(...towerAt(pw,cx,H-30,fl,wid,lvl<3?['wood','brick']:['brick','stone','concrete']));
    if(lvl>=4)blocks.push(...towerAt(pw,cx-wid-30,H-30,Math.max(2,fl-3),90,['stone','concrete']));if(lvl>=6)blocks.push(...towerAt(pw,cx+wid+30,H-30,Math.max(2,fl-2),90,['stone','concrete']));
    house=[];if(lvl>=3){const sides=lvl>=6?[-1,1]:[Math.random()<.5?-1:1];sides.forEach(sd=>{const hasT=(sd<0&&lvl>=4)||(sd>0&&lvl>=6);const hx=cx+sd*(hasT?wid+30+45+75:wid/2+95);const hb=[pw.block(hx,H-30-22,70,44,'plastic'),pw.block(hx,H-30-44-10,84,20,'plastic')];hb.forEach(b=>{b.plugin.keep=1;b.plugin.col='#6EE7B7';b.plugin.x0=b.position.x;b.plugin.y0=b.position.y;b.plugin.hp=b.plugin.max=8});house.push(...hb)})}
    blocks.forEach(b=>Body.setStatic(b,true));det.disabled=false;LINE=H-30-Math.min(150,70+lvl*8)}
  c.on(pw.cv,'pointerdown',e=>{if(state==='won'){lvl++;S.set('tnt_lv',lvl);build();return}if(state==='fail'){build();return}if(state!=='plan')return;const p=pw.pos(e);const hitB=Query.point(blocks.filter(b=>!b.plugin.gone),p)[0];if(!hitB)return;const ex=charges.find(ch=>ch.b===hitB);if(ex){charges=charges.filter(ch=>ch!==ex);beep(300,.05,'triangle',.05);return}if(charges.length>=maxC){pw.pop('Only '+maxC+'!',p.x,p.y-20,'#fff');return}const ca=Math.cos(-hitB.angle),sa=Math.sin(-hitB.angle);const lx=p.x-hitB.position.x,ly=p.y-hitB.position.y;charges.push({b:hitB,lx:lx*ca-ly*sa,ly:lx*sa+ly*ca});beep(700,.06,'square',.05)});
  const go=()=>{if(state!=='plan'||!charges.length)return;state='boom';det.disabled=true;blocks.forEach(b=>{if(!b.plugin.gone)Body.setStatic(b,false)});let k=0;charges.forEach(ch=>{c.after(()=>{const b=ch.b;const ca=Math.cos(b.angle),sa=Math.sin(b.angle);pw.explode(b.position.x+ch.lx*ca-ch.ly*sa,b.position.y+ch.lx*sa+ch.ly*ca,200,11,60)},k*220+50);k++});charges=[];settle=0};
  det.addEventListener('click',go);rs.addEventListener('click',()=>build());c.on(document,'keydown',e=>{if(e.key===' '||e.key==='Enter'){e.preventDefault();go()}});
  const top=()=>{let m=H;blocks.forEach(b=>{if(!b.plugin.gone&&b.position.y<H+100)m=Math.min(m,b.bounds.min.y)});return m};
  pw.under.push(x=>{x.strokeStyle='#F2352A';x.lineWidth=3;x.setLineDash([12,8]);x.beginPath();x.moveTo(0,LINE);x.lineTo(W,LINE);x.stroke();x.setLineDash([]);x.fillStyle='#F2352A';x.font='700 13px "JetBrains Mono", monospace';x.textAlign='right';x.fillText('FLATTEN BELOW THIS LINE',W-12,LINE-8)});
  pw.draws.push(x=>{charges.forEach(ch=>{const b=ch.b;const ca=Math.cos(b.angle),sa=Math.sin(b.angle);const px=b.position.x+ch.lx*ca-ch.ly*sa,py=b.position.y+ch.lx*sa+ch.ly*ca;x.save();x.translate(px,py);x.rotate(b.angle);x.fillStyle='#F2352A';x.strokeStyle='#1D1A2F';x.lineWidth=2.5;x.fillRect(-15,-8,30,16);x.strokeRect(-15,-8,30,16);x.fillStyle='#fff';x.font='800 9px Figtree, sans-serif';x.textAlign='center';x.fillText('TNT',0,4);x.restore()});
    x.textAlign='left';x.font='700 16px "JetBrains Mono", monospace';x.fillStyle='#1D1A2F';x.fillText('LEVEL '+lvl+'   TNT '+charges.length+'/'+maxC+(state==='boom'?'   settling… '+Math.max(0,Math.ceil(6-settle))+'s':''),16,30);
    if(state==='won')phBanner(x,W,H,'Flattened!','Click for level '+(lvl+1));if(state==='fail')phBanner(x,W,H,hurtHouse()?'The house got wrecked!':'Still standing…',hurtHouse()?'Keep the green houses safe. Click to try again.':'Something’s above the line. Click to try again.');if(house.length&&state==='plan'){x.fillStyle='#1D1A2F';x.font='700 13px Figtree, sans-serif';x.textAlign='center';house.filter((b,i)=>i%2).forEach(b=>x.fillText('🏠 KEEP SAFE',b.position.x,b.bounds.min.y-12))}});
  const hurtHouse=()=>house.some(b=>b.plugin.gone||Math.abs(b.position.x-b.plugin.x0)>25||Math.abs(b.angle)>.5);pw.broke=(b)=>{if(b.plugin.keep&&state==='boom'){state='fail';beep(160,.4,'sawtooth',.06)}};
  pw.steps.push(()=>{if(state==='boom'&&hurtHouse()){state='fail';beep(160,.4,'sawtooth',.06)}if(state==='boom'){settle+=1/60;const t=top();if(settle>1.2&&t>LINE){const still=blocks.every(b=>b.plugin.gone||b.speed<.6);if(still||settle>6){state='won';c.best(lvl);score+=lvl*100;[523,659,784,1046].forEach((f,i)=>c.after(()=>beep(f,.2,'triangle',.07),i*110))}}else if(settle>6){state='fail';beep(200,.3,'sawtooth',.06)}}c.stat('Demolition · Level '+lvl)});
  build()})}});

G.push({id:'ph_dummy',name:'Crash Dummy',kind:'smash',wide:true,tint:'#FF8FB1',blurb:'Grab a crash-test dummy and fling it around a room full of very breakable stuff.',fmt:b=>b+' pts',
art:'<rect width="120" height="72" fill="#FF8FB1"/><rect y="62" width="120" height="10" fill="#8a5a2b"/><g stroke="#1D1A2F" stroke-width="2.5"><circle cx="40" cy="20" r="8" fill="#FFD23F"/><rect x="34" y="28" width="12" height="18" rx="3" fill="#FFD23F"/><path d="M34 32l-12-8M46 32l12-10M37 46l-6 14M43 46l8 12" stroke="#FFD23F" stroke-width="6" stroke-linecap="round"/><path d="M34 32l-12-8M46 32l12-10M37 46l-6 14M43 46l8 12" fill="none"/></g><path d="M36 17l3 3M39 17l-3 3M42 17l3 3M45 17l-3 3" stroke="#1D1A2F" stroke-width="1.5"/><path d="M84 62v-14h12v14" fill="#9fd6ff" stroke="#1D1A2F" stroke-width="2.5"/><path d="M98 38q-6 12 0 24h10q6-12 0-24z" fill="#FF9F43" stroke="#1D1A2F" stroke-width="2.5"/><text x="86" y="30" font-family="Arial Black" font-size="11" fill="#FFD23F" stroke="#1D1A2F" stroke-width="1">CRASH</text>',
run(root,c){return withMatter(root,c,()=>{
  const row=el('div',{class:'row'});const rs=el('button',{class:'btn',type:'button'},'New room');row.append(rs);
  const hint=el('p',{class:'hint'},'Grab the dummy anywhere and fling it. Big crashes and broken stuff score points. Every throw is scored separately.');
  let throwPts=0,best=0,total=0,combo=0,comboT=0,lastOof=0;
  const pw=PhysWorld(root,c,{sky:'#FFE9F0',sky2:'#FFF6D8',cursor:'grab',thresh:2.5,onHit:(a,b,rv,p)=>{const d=a.plugin.dummy?a:b.plugin.dummy?b:null;if(!d||rv<7)return;const o=d===a?b:a;if(o.plugin.dummy)return;const pts=Math.round((rv-6)*8);throwPts+=pts;total+=pts;combo++;comboT=1;if(pw.t-lastOof>120){lastOof=pw.t;pw.pop(pick(['OOF!','BONK!','OUCH!','WHUMP!','SPLAT!','YIKES!','THUD!']),d.position.x,d.position.y-30,rv>14?'#FF8FB1':'#FFD23F',rv>14);pw.shake=Math.max(pw.shake,rv*.4);beep(120+Math.random()*120,.08,'square',.05)}}});
  root.append(row,hint);const{Bodies,Body,Composite,Constraint,Query,Vector}=pw.Mt;const{W,H}=pw;
  let parts=[],joints=[],grab=null,room=[];
  function dummy(x0,y0){parts.forEach(b=>pw.remove(b));joints.forEach(j=>pw.remove(j));parts=[];joints=[];const opt={collisionFilter:{group:-3},density:.002,friction:.6,restitution:.1,frictionAir:.01};const col='#FFD23F';
    const mk=(b)=>{b.plugin.col=col;b.plugin.dummy=1;parts.push(pw.add(b));return b};
    const head=mk(Bodies.circle(x0,y0-58,16,opt));head.plugin.face=(x,b)=>{x.save();x.translate(b.position.x,b.position.y);x.rotate(b.angle);x.strokeStyle='#1D1A2F';x.lineWidth=2;[-6,6].forEach(s=>{x.beginPath();x.moveTo(s-3,-5);x.lineTo(s+3,1);x.moveTo(s+3,-5);x.lineTo(s-3,1);x.stroke()});x.beginPath();x.arc(0,-4,20,0,0);x.stroke();x.fillStyle='#1D1A2F';x.beginPath();x.arc(-16,0,3,0,7);x.fill();x.restore()};
    const torso=mk(Bodies.rectangle(x0,y0-18,26,48,opt));torso.plugin.face=(x,b)=>{x.save();x.translate(b.position.x,b.position.y);x.rotate(b.angle);x.fillStyle='#1D1A2F';x.beginPath();x.arc(0,-6,7,0,7);x.fill();x.fillStyle='#FFD23F';x.beginPath();x.moveTo(0,-6);x.arc(0,-6,7,0,Math.PI/2);x.closePath();x.fill();x.beginPath();x.moveTo(0,-6);x.arc(0,-6,7,Math.PI,Math.PI*1.5);x.closePath();x.fill();x.restore()};
    const limb=(xx,yy,w,h)=>mk(Bodies.rectangle(xx,yy,w,h,Object.assign({chamfer:{radius:5}},opt)));
    const uaL=limb(x0-22,y0-30,10,26),uaR=limb(x0+22,y0-30,10,26),laL=limb(x0-22,y0-4,9,24),laR=limb(x0+22,y0-4,9,24),ulL=limb(x0-8,y0+20,12,30),ulR=limb(x0+8,y0+20,12,30),llL=limb(x0-8,y0+50,11,30),llR=limb(x0+8,y0+50,11,30);
    const J=(a,pa,b,pb)=>{const j=Constraint.create({bodyA:a,pointA:pa,bodyB:b,pointB:pb,stiffness:.7,length:0});j.render.visible=false;joints.push(pw.add(j))};
    J(head,{x:0,y:15},torso,{x:0,y:-25});J(torso,{x:-12,y:-20},uaL,{x:0,y:-12});J(torso,{x:12,y:-20},uaR,{x:0,y:-12});J(uaL,{x:0,y:12},laL,{x:0,y:-11});J(uaR,{x:0,y:12},laR,{x:0,y:-11});J(torso,{x:-7,y:22},ulL,{x:0,y:-14});J(torso,{x:7,y:22},ulR,{x:0,y:-14});J(ulL,{x:0,y:14},llL,{x:0,y:-14});J(ulR,{x:0,y:14},llR,{x:0,y:-14})}
  function furnish(){room.forEach(b=>{if(!b.plugin.gone)pw.remove(b)});room=[];const add=b=>{room.push(b);return b};
    const shelf=(sx,sy,w)=>{const s=pw.add(Bodies.rectangle(sx,sy,w,12,{isStatic:true}));s.plugin.col='#8a5a2b';room.push(s);return s};
    shelf(700,260,220);shelf(250,200,160);shelf(820,420,170);
    const vase=(vx,vy)=>{const b=add(pw.block(vx,vy,22,40,'ceramic',{chamfer:{radius:8}}));b.plugin.col=pick(['#FF8FB1','#B9A7FF','#7FC8F8','#FF9F43'])};
    [620,665,710,755,790].forEach(xx=>vase(xx,230));[210,250,290].forEach(xx=>vase(xx,170));vase(790,390);vase(850,390);
    const tv=add(pw.block(520,H-70,90,60,'tv'));tv.plugin.face=(x,b)=>{x.save();x.translate(b.position.x,b.position.y);x.rotate(b.angle);x.fillStyle='#7FC8F8';x.fillRect(-36,-22,72,40);x.restore()};
    for(let i=0;i<4;i++)for(let j=0;j<3-i%2;j++)add(pw.block(380+j*34+(i%2)*17,H-47-i*34,32,32,'plastic',{})).plugin.col=pick(['#e8c48a','#d4a86a']);
    for(let k=0;k<6;k++)add(pw.block(900-k*2,H-50-k*42,40,40,'glass'));
    const lamp=add(pw.block(120,H-80,14,80,'wood'));add(pw.block(120,H-130,50,22,'ceramic')).plugin.col='#FFD23F';
    const tramp=pw.add(Bodies.rectangle(W/2-90,H-34,120,14,{isStatic:true,restitution:1.4}));tramp.plugin.col='#2BB673';room.push(tramp)}
  pw.broke=(b,m)=>{throwPts+=m.pts*2;total+=m.pts*2;pw.pop('+'+m.pts*2,b.position.x,b.position.y-10,'#fff')};
  const flo=pw.ground(H-30,'#8a5a2b');pw.add(Bodies.rectangle(-40,H/2,100,H*2,{isStatic:true})).plugin.col='#e8c48a';pw.add(Bodies.rectangle(W+40,H/2,100,H*2,{isStatic:true})).plugin.col='#e8c48a';pw.add(Bodies.rectangle(W/2,-40,W*2,100,{isStatic:true})).plugin.col='#e8c48a';
  let mc=null;
  c.on(pw.cv,'pointerdown',e=>{const p=pw.pos(e);const b=Query.point(parts,p)[0]||parts.reduce((m,q)=>Vector.magnitude(Vector.sub(q.position,p))<(m?Vector.magnitude(Vector.sub(m.position,p)):60)?q:m,null);if(!b)return;mc=pw.add(Constraint.create({pointA:p,bodyB:b,pointB:Vector.sub(p,b.position),stiffness:.08,damping:.05,length:0}));mc.render.visible=false;pw.cv.setPointerCapture(e.pointerId);if(throwPts>0){best=Math.max(best,throwPts)}throwPts=0;combo=0});
  let hist=[];c.on(pw.cv,'pointermove',e=>{if(mc){mc.pointA=pw.pos(e);hist.push({t:performance.now(),p:mc.pointA});if(hist.length>8)hist.shift()}});const rel=()=>{if(mc){const now=performance.now();const h0=hist.find(q=>now-q.t<90);const h1=hist[hist.length-1];if(h0&&h1&&h1.t>h0.t){const vx=(h1.p.x-h0.p.x)/(h1.t-h0.t)*16.7*.7,vy=(h1.p.y-h0.p.y)/(h1.t-h0.t)*16.7*.7;const sp=Math.hypot(vx,vy),k=sp>40?40/sp:1;parts.forEach(b=>Body.setVelocity(b,{x:b.velocity.x*.3+vx*k,y:b.velocity.y*.3+vy*k}))}hist=[];pw.remove(mc);mc=null;sweep(400,900,.15,'sine',.04)}};c.on(pw.cv,'pointerup',rel);c.on(pw.cv,'pointercancel',rel);
  rs.addEventListener('click',()=>{furnish();dummy(W/2,H/2);throwPts=0});
  pw.draws.push(x=>{if(mc){x.strokeStyle='#1D1A2F';x.setLineDash([6,5]);x.lineWidth=2;x.beginPath();x.moveTo(mc.pointA.x,mc.pointA.y);const b=mc.bodyB;x.lineTo(b.position.x+mc.pointB.x,b.position.y+mc.pointB.y);x.stroke();x.setLineDash([])}
    x.textAlign='left';x.font='700 16px "JetBrains Mono", monospace';x.fillStyle='#1D1A2F';x.fillText('THIS THROW '+throwPts+'   BEST THROW '+Math.max(best,throwPts)+'   TOTAL '+total,16,80)});
  pw.steps.push(()=>{comboT-=1/60;parts.forEach(b=>{if(b.position.y>H+100||b.position.x<-100||b.position.x>W+100)Body.setPosition(b,{x:W/2,y:H/2})});const bt=Math.max(best,throwPts);c.best(bt);c.stat('Crash Dummy · best throw '+bt)});
  furnish();dummy(W/2,H/2)})}});
