/* ================= MORE PUZZLES ================= */
/* shared level logic (kept top-level so levels can be verified) */
const JELLY_LV=[
 ['#########','#.......#','#.......#','#..r....#','#.###.r.#','#########'],
 ['#########','#.......#','#.g...b.#','#.#...#.#','#.b...g.#','#########'],
 ['##########','#........#','#.r....r.#','#.##..##.#','#...rr...#','##########'],
 ['##########','#........#','#..g..b..#','#..#..#..#','#.b....g.#','#.##..##.#','##########'],
 ['###########','#.........#','#.r.....y.#','#.#.....#.#','#...y.r...#','#..###.##.#','###########'],
 ['###########','#.........#','#.b.g.b.g.#','#.#.#.#.#.#','#.........#','###########'],
 ['###########','#.........#','#..rg.....#','#..##..gr.#','#......##.#','#.........#','###########'],
 ['############','#..........#','#.y..b..y..#','#.#..#..#..#','#....b.....#','#.#.####.#.#','#..........#','############']];
function jellyParse(L){const H=L.length,W=L[0].length,g=[];for(let y=0;y<H;y++)for(let x=0;x<W;x++){const ch=L[y][x];g.push(ch==='#'?'#':ch==='.'?null:ch)}return{W,H,g}}
function jellyGroups(st){const{W,H,g}=st;const id=Array(W*H).fill(-1);let n=0;const groups=[];for(let i=0;i<W*H;i++){if(!g[i]||g[i]==='#'||id[i]>=0)continue;const col=g[i],cells=[],q=[i];id[i]=n;while(q.length){const k=q.pop();cells.push(k);for(const d of[1,-1,W,-W]){const j=k+d;if(j<0||j>=W*H||(d===1&&j%W===0)||(d===-1&&k%W===0))continue;if(g[j]===col&&id[j]<0){id[j]=n;q.push(j)}}}groups.push({col,cells});n++}return{id,groups}}
function jellySettle(st){const{W,H}=st;let moved=true;while(moved){moved=false;const{id,groups}=jellyGroups(st);for(let gi=0;gi<groups.length;gi++){const G2=groups[gi];if(G2.cells.every(k=>{const b=k+W;return b<W*H&&(st.g[b]===null||id[b]===gi)})){const col=G2.col;G2.cells.forEach(k=>st.g[k]=null);G2.cells.forEach(k=>st.g[k+W]=col);moved=true;break}}}return st}
function jellyMove(st,cell,dir){const{W}=st;const{id,groups}=jellyGroups(st);const gi=id[cell];if(gi<0)return null;const G2=groups[gi];if(!G2.cells.every(k=>{const j=k+dir;return st.g[j]===null||id[j]===gi}))return null;const ns={W:st.W,H:st.H,g:st.g.slice()};G2.cells.forEach(k=>ns.g[k]=null);G2.cells.forEach(k=>ns.g[k+dir]=G2.col);return jellySettle(ns)}
function jellyWon(st){const{groups}=jellyGroups(st);const cols={};groups.forEach(G2=>cols[G2.col]=(cols[G2.col]||0)+1);return Object.values(cols).every(v=>v===1)}
const PEB_LV=[
 ['..........','..........','..........','.....#...D','P.o..#...#','##########'],
 ['...........','...........','........#.D','P..o...##.#','###########'],
 ['..........','..........','.........D','...#.....#','Po.#...o.#','##########'],
 ['.............','.............','......#.....D','P.o.o.##...##','#############'],
 ['...........','...........','..........D','......###.#','Po..o.###.#','###########'],
 ['............','............','............','.....#....oD','Po.o.##...##','############'],
 ['.............','.............','.............','.........o...','.........#...','P..oo.##.##.D','#############'],
 ['..............','..............','..............','........o.....','........#...#D','Poo.o...###.##','##############']];
function pebParse(L){const H=L.length,W=L[0].length;let p=null,d=null;const g=[];for(let y=0;y<H;y++)for(let x=0;x<W;x++){const ch=L[y][x];if(ch==='P')p={x,y};if(ch==='D')d={x,y};g.push(ch==='#'?1:ch==='o'?2:0)}return{W,H,g,px:p.x,py:p.y,f:1,carry:0,door:d}}
function pebFall(st,x,y){while(y+1<st.H&&st.g[(y+1)*st.W+x]===0)y++;return y}
function pebStep(st,a){const s={W:st.W,H:st.H,g:st.g.slice(),px:st.px,py:st.py,f:st.f,carry:st.carry,door:st.door};const W=s.W,at=(x,y)=>x<0||x>=W||y<0||y>=s.H?1:s.g[y*W+x];
  if(a==='L'||a==='R'){const dx=a==='L'?-1:1;if(s.f!==dx){s.f=dx;return s}const nx=s.px+dx;if(at(nx,s.py)===0&&(!s.carry||at(nx,s.py-1)===0)){s.px=nx;s.py=pebFall(s,nx,s.py);return s}return s}
  if(a==='U'){const nx=s.px+s.f;if(at(nx,s.py)!==0&&at(nx,s.py-1)===0&&at(s.px,s.py-1)===0&&(!s.carry||(at(s.px,s.py-2)===0&&at(nx,s.py-2)===0))){s.px=nx;s.py=s.py-1;return s}return s}
  if(a==='D'){const nx=s.px+s.f;if(!s.carry){if(at(nx,s.py)===2&&at(nx,s.py-1)===0&&at(s.px,s.py-1)===0){s.g[s.py*W+nx]=0;s.carry=1;const top=s.py-1;void top}}else{if(at(nx,s.py)===0&&at(nx,s.py-1)===0){const yy=pebFall(s,nx,s.py);s.g[yy*W+nx]=2;s.carry=0}else if(at(nx,s.py)!==0&&at(nx,s.py-1)===0){s.g[(s.py-1)*W+nx]=2;s.carry=0}}return s}return s}
const pebWon=s=>s.px===s.door.x&&s.py===s.door.y;
/* ---------- Jelly Buddies ---------- */
G.push({id:'jellies',name:'Jelly Buddies',kind:'puzzle',levels:true,tint:'#FF8FB1',blurb:'Squishy jellies fall with gravity and stick together when colors touch. Slide them until every color is one big blob.',fmt:b=>'level '+b,
art:'<rect width="120" height="72" fill="#3a2a6a"/><rect x="0" y="58" width="120" height="14" fill="#1D1A2F"/><g stroke="#1D1A2F" stroke-width="2.5"><rect x="20" y="40" width="18" height="18" rx="6" fill="#F2352A"/><rect x="38" y="40" width="18" height="18" rx="6" fill="#F2352A"/><rect x="74" y="22" width="18" height="18" rx="6" fill="#2BB673"/><rect x="74" y="40" width="18" height="18" rx="6" fill="#FFD23F"/></g><circle cx="27" cy="47" r="2" fill="#fff"/><circle cx="33" cy="47" r="2" fill="#fff"/>',
run(root,c){const Wc=660,Hc=520;const[cv,x]=mk(Wc,Hc,'width:min(100%,660px)');const row=el('div',{class:'row'});const ub=el('button',{class:'btn',type:'button'},'↶ Undo'),rb=el('button',{class:'btn',type:'button'},'Restart level');row.append(ub,rb);root.append(cv,row,el('p',{class:'hint'},'Drag a jelly left or right (or click it, then press ← →). Jellies of the same color stick together forever. Make each color one single blob.'));
  const CL={r:'#F2352A',g:'#2BB673',b:'#2d6fd6',y:'#FFD23F'};let lvl=Math.min(JELLY_LV.length,Math.max(1,S.get('jl_lv',1))),st,hist,sel=-1,state='play',moves=0,wob=0;
  function load(){st=jellySettle(jellyParse(JELLY_LV[lvl-1]));hist=[];sel=-1;state='play';moves=0;c.stat('Jelly Buddies · level '+lvl)}
  function mv(cell,dir){const ns=jellyMove(st,cell,dir);if(!ns){beep(180,.05,'square',.03);return}hist.push(st);st=ns;moves++;wob=1;sel=cell+dir;beep(400,.05,'sine',.05);if(jellyWon(st)){state='won';S.set('jl_lv',Math.max(S.get('jl_lv',1),Math.min(JELLY_LV.length,lvl+1)));c.best(lvl);[523,659,784,1046].forEach((q,i)=>c.after(()=>beep(q,.12,'triangle',.06),i*90))}}
  function geom(){const Q=Math.min(Wc/st.W,(Hc-40)/st.H);return{Q,ox:(Wc-st.W*Q)/2,oy:(Hc-st.H*Q)/2}}
  function draw(){x.fillStyle='#3a2a6a';x.fillRect(0,0,Wc,Hc);const{Q,ox,oy}=geom();const{id}=jellyGroups(st);wob=Math.max(0,wob-.04);
    for(let i=0;i<st.g.length;i++){const gx=i%st.W,gy=i/st.W|0,v=st.g[i];const px=ox+gx*Q,py=oy+gy*Q;if(v==='#'){x.fillStyle='#1D1A2F';x.fillRect(px,py,Q,Q);continue}if(!v)continue;x.fillStyle=CL[v];const same=d=>st.g[i+d]===v&&id[i+d]===id[i];const r=Q*.28;x.beginPath();const l=px+(same(-1)?0:3),t=py+(same(-st.W)?0:3),rr=px+Q-(same(1)?0:3),bb=py+Q-(same(st.W)?0:3);x.roundRect?x.roundRect(l,t,rr-l,bb-t,[same(-1)||same(-st.W)?0:r,same(1)||same(-st.W)?0:r,same(1)||same(st.W)?0:r,same(-1)||same(st.W)?0:r]):x.rect(l,t,rr-l,bb-t);x.fill();
      if(!same(-st.W)){x.fillStyle='rgba(255,255,255,.35)';x.fillRect(l+6,t+5,(rr-l)*.4,4)}if(!same(-1)&&!same(-st.W)){x.fillStyle='#1D1A2F';x.beginPath();x.arc(px+Q*.35,py+Q*.45+Math.sin(performance.now()/300+i)*wob*2,Q*.06,0,7);x.arc(px+Q*.6,py+Q*.45,Q*.06,0,7);x.fill()}}
    if(sel>=0&&st.g[sel]&&st.g[sel]!=='#'){const{groups}=jellyGroups(st);const gi=jellyGroups(st).id[sel];if(gi>=0){x.strokeStyle='#fff';x.lineWidth=3;groups[gi].cells.forEach(k=>{x.strokeRect(ox+(k%st.W)*Q+2,oy+(k/st.W|0)*Q+2,Q-4,Q-4)})}}
    x.fillStyle='#fff';x.font='700 16px "JetBrains Mono"';x.textAlign='left';x.fillText('LEVEL '+lvl+'/'+JELLY_LV.length+'   moves '+moves,14,24);if(state==='won')banner(x,Wc,Hc,'Squished together!',lvl<JELLY_LV.length?'Tap for level '+(lvl+1):'You beat every level! Tap to replay')}
  let dragS=null;c.on(cv,'pointerdown',e=>{if(state==='won'){lvl=lvl<JELLY_LV.length?lvl+1:1;load();return}const p=canvasPos(cv,e);const{Q,ox,oy}=geom();const gx=Math.floor((p.x-ox)/Q),gy=Math.floor((p.y-oy)/Q);const i=gy*st.W+gx;if(gx>=0&&gy>=0&&gx<st.W&&gy<st.H&&st.g[i]&&st.g[i]!=='#'){sel=i;dragS={x:p.x,cell:i}}});
  c.on(cv,'pointermove',e=>{if(!dragS)return;const p=canvasPos(cv,e);const{Q}=geom();const dx=p.x-dragS.x;if(Math.abs(dx)>Q*.6){const dir=dx>0?1:-1;const before=st;mv(dragS.cell,dir);if(st!==before){dragS={x:p.x,cell:dragS.cell+dir}}else dragS=null}});c.on(window,'pointerup',()=>dragS=null);
  c.on(document,'keydown',e=>{if(sel<0||state!=='play')return;if(e.key==='ArrowLeft'){e.preventDefault();mv(sel,-1)}if(e.key==='ArrowRight'){e.preventDefault();mv(sel,1)}});ub.addEventListener('click',()=>{if(hist.length){st=hist.pop();moves++;state='play'}});rb.addEventListener('click',load);load();c.loop(()=>draw())}});
/* ---------- Pebble Boy (Block-Dude style) ---------- */
G.push({id:'pebble',name:'Pebble Boy',kind:'puzzle',levels:true,tint:'#8c86a3',blurb:'Pick up pebbles, stack them into stairs and climb your way to the door. A classic carry-and-climb puzzle.',fmt:b=>'level '+b,
art:'<rect width="120" height="72" fill="#cfe8ff"/><rect y="60" width="120" height="12" fill="#5A5470"/><rect x="90" y="36" width="14" height="24" fill="#FF9F43" stroke="#1D1A2F" stroke-width="2"/><rect x="70" y="46" width="14" height="14" fill="#5A5470"/><circle cx="54" cy="53" r="7" fill="#8c86a3" stroke="#1D1A2F" stroke-width="2"/><rect x="24" y="40" width="14" height="20" rx="4" fill="#2d6fd6" stroke="#1D1A2F" stroke-width="2"/><circle cx="31" cy="30" r="7" fill="#8c86a3" stroke="#1D1A2F" stroke-width="2"/>',
run(root,c){const Wc=700,Hc=460;const[cv,x]=mk(Wc,Hc,'width:min(100%,700px)');root.append(cv);const keys=holdPad(root,[['L','◀'],['U','⤴ Climb'],['D','⤓ Pick/drop'],['R','▶']]);const row=el('div',{class:'row'});const ub=el('button',{class:'btn',type:'button'},'↶ Undo'),rb=el('button',{class:'btn',type:'button'},'Restart');row.append(ub,rb);root.append(row,el('p',{class:'hint'},'←/→ walk (or turn), ↑ climb one step up, ↓ pick up the pebble in front of you or put it down. You can’t jump, so build stairs!'));
  let lvl=Math.min(PEB_LV.length,Math.max(1,S.get('peb_lv',1))),st,hist,state='play',moves=0;const kl={};
  function load(){st=pebParse(PEB_LV[lvl-1]);hist=[];state='play';moves=0;c.stat('Pebble Boy · level '+lvl)}
  function act(a){if(state!=='play')return;const ns=pebStep(st,a);hist.push(st);st=ns;moves++;beep(a==='D'?300:500,.03,'triangle',.03);if(pebWon(st)){state='won';S.set('peb_lv',Math.max(S.get('peb_lv',1),Math.min(PEB_LV.length,lvl+1)));c.best(lvl);[523,659,784].forEach((q,i)=>c.after(()=>beep(q,.15,'triangle',.06),i*100))}}
  function draw(){x.fillStyle='#cfe8ff';x.fillRect(0,0,Wc,Hc);const Q=Math.min(Wc/st.W,(Hc-30)/st.H),ox=(Wc-st.W*Q)/2,oy=Hc-st.H*Q;for(let i=0;i<st.g.length;i++){const gx=i%st.W,gy=i/st.W|0,v=st.g[i],px=ox+gx*Q,py=oy+gy*Q;if(v===1){x.fillStyle='#5A5470';x.fillRect(px,py,Q,Q);x.strokeStyle='#3a3552';x.strokeRect(px+1,py+1,Q-2,Q-2)}else if(v===2){x.fillStyle='#8c86a3';x.strokeStyle='#1D1A2F';x.lineWidth=2.5;x.beginPath();x.arc(px+Q/2,py+Q/2+2,Q*.42,0,7);x.fill();x.stroke()}}
    const d=st.door;x.fillStyle='#FF9F43';x.strokeStyle='#1D1A2F';x.lineWidth=2.5;x.fillRect(ox+d.x*Q+Q*.15,oy+d.y*Q,Q*.7,Q);x.strokeRect(ox+d.x*Q+Q*.15,oy+d.y*Q,Q*.7,Q);x.fillStyle='#FFD23F';x.beginPath();x.arc(ox+d.x*Q+Q*.7,oy+d.y*Q+Q*.55,3,0,7);x.fill();
    const px=ox+st.px*Q,py=oy+st.py*Q;x.fillStyle='#2d6fd6';x.beginPath();x.roundRect?x.roundRect(px+Q*.2,py+Q*.15,Q*.6,Q*.85,8):x.rect(px+Q*.2,py+Q*.15,Q*.6,Q*.85);x.fill();x.stroke();x.fillStyle='#fff';x.beginPath();x.arc(px+Q/2+st.f*Q*.12,py+Q*.35,Q*.08,0,7);x.fill();if(st.carry){x.fillStyle='#8c86a3';x.beginPath();x.arc(px+Q/2,py-Q*.45,Q*.42,0,7);x.fill();x.stroke()}
    x.fillStyle='#1D1A2F';x.font='700 15px "JetBrains Mono"';x.textAlign='left';x.fillText('LEVEL '+lvl+'/'+PEB_LV.length+'  moves '+moves,12,22);if(state==='won')banner(x,Wc,Hc,'You made it!',lvl<PEB_LV.length?'Tap for level '+(lvl+1):'All levels done! Tap to replay')}
  c.on(document,'keydown',e=>{const m={arrowleft:'L',a:'L',arrowright:'R',d:'R',arrowup:'U',w:'U',arrowdown:'D',s:'D'}[e.key.toLowerCase()];if(m){e.preventDefault();act(m)}});c.on(cv,'pointerdown',()=>{if(state==='won'){lvl=lvl<PEB_LV.length?lvl+1:1;load()}});ub.addEventListener('click',()=>{if(hist.length){st=hist.pop();state='play'}});rb.addEventListener('click',load);
  load();c.loop(()=>{['L','R','U','D'].forEach(k=>{if(keys[k]&&!kl[k])act(k);kl[k]=keys[k]});draw()})}});
/* ---------- Torch Maze ---------- */
G.push({id:'torchmaze',name:'Torch Maze',kind:'puzzle',levels:true,tint:'#1D1A2F',blurb:'A dark maze and a flickering torch. Find the keys, unlock the door, and grab oil before your light runs out.',fmt:b=>'maze '+b,
art:'<rect width="120" height="72" fill="#0b0a14"/><circle cx="50" cy="40" r="26" fill="#FF9F43" opacity=".25"/><path d="M30 20h40v10H40v20h20" stroke="#5A5470" stroke-width="6" fill="none"/><circle cx="50" cy="40" r="5" fill="#FFD23F"/><text x="90" y="30" font-size="14">🔑</text>',
run(root,c){const Wc=640,Hc=640;const[cv,x]=mk(Wc,Hc,'width:min(100%,640px)');root.append(cv);const keys=holdPad(root,[['l','◀'],['u','▲'],['d','▼'],['r','▶']]);root.append(el('p',{class:'hint'},'Arrows/WASD to move. Collect every key 🔑 to open the exit door. Your torch fades over time, so grab oil 🛢 to keep it burning.'));
  let lvl=Math.max(1,S.get('tm_lv',1)),N,G2,P,keysL,oil,door,need,got,light,state='play',seen,mvT=0,pressed={};
  function build(){N=Math.min(41,11+lvl*4)|1;G2=Array(N*N).fill(1);const st=[[1,1]];G2[N+1]=0;while(st.length){const[a,b]=st[st.length-1];const nb=shuffle([[2,0],[-2,0],[0,2],[0,-2]]).filter(([dx,dy])=>{const nx=a+dx,ny=b+dy;return nx>0&&ny>0&&nx<N-1&&ny<N-1&&G2[ny*N+nx]===1});if(!nb.length){st.pop();continue}const[dx,dy]=nb[0];G2[(b+dy/2)*N+a+dx/2]=0;G2[(b+dy)*N+a+dx]=0;st.push([a+dx,b+dy])}
    for(let i=0;i<N*lvl/2;i++){const px=1+rand(N-2),py=1+rand(N-2);if(G2[py*N+px]===1&&((G2[py*N+px-1]===0&&G2[py*N+px+1]===0)||(G2[(py-1)*N+px]===0&&G2[(py+1)*N+px]===0)))G2[py*N+px]=0}
    const cells=[];for(let i=0;i<N*N;i++)if(G2[i]===0)cells.push(i);const far=cells.slice().sort((a,b)=>((b%N)+(b/N|0))-((a%N)+(a/N|0)));door=far[0];need=Math.min(4,1+Math.floor(lvl/2));keysL=shuffle(cells.filter(i=>i!==door&&i!==N+1)).slice(0,need);oil=shuffle(cells.filter(i=>!keysL.includes(i)&&i!==door)).slice(0,2+lvl);P={x:1,y:1,dx:1,dy:1};got=0;light=1;state='play';seen=new Set();c.stat('Torch Maze · maze '+lvl)}
  function move(dx,dy){if(state!=='play')return;const nx=P.x+dx,ny=P.y+dy,i=ny*N+nx;if(G2[i]===1)return;if(i===door&&got<need){beep(180,.08,'square',.04);return}P.x=nx;P.y=ny;const ki=keysL.indexOf(i);if(ki>=0){keysL.splice(ki,1);got++;beep(1000,.1,'triangle',.06)}const oi=oil.indexOf(i);if(oi>=0){oil.splice(oi,1);light=Math.min(1,light+.45);beep(600,.1,'sine',.05)}if(i===door&&got>=need){state='won';S.set('tm_lv',Math.max(S.get('tm_lv',1),lvl+1));c.best(lvl);[523,659,784].forEach((q,k)=>c.after(()=>beep(q,.15,'triangle',.06),k*100))}}
  function step(dt){if(state!=='play')return;light-=dt*c.pick(.012,.018,.026);if(light<=0){state='dark';light=0;noise(.5,'lowpass',200,.2)}P.dx+=(P.x-P.dx)*Math.min(1,dt*16);P.dy+=(P.y-P.dy)*Math.min(1,dt*16);mvT-=dt;const L=pressed.arrowleft||pressed.a||keys.l,R=pressed.arrowright||pressed.d||keys.r,U=pressed.arrowup||pressed.w||keys.u,D=pressed.arrowdown||pressed.s||keys.d;if(mvT<=0&&(L||R||U||D)){mvT=.11;move(R?1:L?-1:0,D?1:U?-1:0===0&&!L&&!R?(D?1:-1):0)}}
  function draw(){const view=13,Q=Wc/view;x.fillStyle='#0b0a14';x.fillRect(0,0,Wc,Hc);const cx=P.dx-view/2+.5,cy=P.dy-view/2+.5;const rad=1.6+light*4.4;for(let gy=Math.floor(cy)-1;gy<cy+view+1;gy++)for(let gx=Math.floor(cx)-1;gx<cx+view+1;gx++){if(gx<0||gy<0||gx>=N||gy>=N)continue;const i=gy*N+gx;const d=Math.hypot(gx-P.x,gy-P.y);if(d<rad)seen.add(i);if(!seen.has(i))continue;const px=(gx-cx)*Q,py=(gy-cy)*Q;x.fillStyle=G2[i]?'#5A5470':'#2a2640';x.fillRect(px,py,Q+1,Q+1);if(i===door){x.fillStyle=got>=need?'#2BB673':'#8a5a2b';x.fillRect(px+Q*.15,py+Q*.1,Q*.7,Q*.8)}if(d<rad){x.font=(Q*.6)+'px sans-serif';x.textAlign='center';x.textBaseline='middle';if(keysL.includes(i))x.fillText('🔑',px+Q/2,py+Q/2);if(oil.includes(i))x.fillText('🛢',px+Q/2,py+Q/2)}}
    const sx=(P.dx-cx)*Q+Q/2,sy=(P.dy-cy)*Q+Q/2;const fl=1+Math.sin(performance.now()/90)*.03;const g=x.createRadialGradient(sx,sy,Q*.5,sx,sy,rad*Q*fl);g.addColorStop(0,'rgba(0,0,0,0)');g.addColorStop(.7,'rgba(11,10,20,.55)');g.addColorStop(1,'rgba(11,10,20,.97)');x.fillStyle=g;x.fillRect(0,0,Wc,Hc);x.fillStyle='rgba(255,159,67,.12)';x.beginPath();x.arc(sx,sy,rad*Q*.6,0,7);x.fill();x.fillStyle='#FFD23F';x.beginPath();x.arc(sx,sy,Q*.3,0,7);x.fill();
    x.fillStyle='#fff';x.font='700 15px "JetBrains Mono"';x.textAlign='left';x.fillText('MAZE '+lvl+'  🔑 '+got+'/'+need,14,24);x.fillStyle='#3a3552';x.fillRect(Wc-174,12,160,12);x.fillStyle=light<.25?'#F2352A':'#FF9F43';x.fillRect(Wc-174,12,160*light,12);if(state==='won')banner(x,Wc,Hc,'Escaped!','Tap for maze '+(lvl+1));if(state==='dark')banner(x,Wc,Hc,'Your torch went out','Tap to try again')}
  c.on(document,'keydown',e=>{const k=e.key.toLowerCase();pressed[k]=1;if(k.startsWith('arrow'))e.preventDefault()});c.on(document,'keyup',e=>{pressed[e.key.toLowerCase()]=0});c.on(cv,'pointerdown',()=>{if(state==='won'){lvl++;build()}else if(state==='dark')build()});build();c.loop(dt=>{step(Math.min(.05,dt/1000));draw()})}});
/* ---------- Hundred Blocks ---------- */
G.push({id:'hundred',name:'Hundred Blocks',kind:'puzzle',tint:'#2d6fd6',blurb:'A 10×10 grid, three pieces at a time, and ticking bombs. Clear rows and columns before a bomb hits zero.',fmt:b=>b+' pts',
art:'<rect width="120" height="72" fill="#1D1A2F"/><g fill="#2d6fd6">'+[0,1,2,3,4,5,6].map(i=>'<rect x="'+(20+i*11)+'" y="10" width="10" height="10"/>').join('')+'</g><g fill="#FFD23F"><rect x="20" y="21" width="10" height="10"/><rect x="31" y="21" width="10" height="10"/></g><circle cx="80" cy="44" r="8" fill="#F2352A"/><text x="80" y="48" font-size="10" fill="#fff" text-anchor="middle" font-family="Arial Black">5</text>',
run(root,c){const Wc=520,Hc=700,N=10,Q=44,OX=(Wc-N*Q)/2,OY=30;const[cv,x]=mk(Wc,Hc,'width:min(100%,520px)');root.append(cv,el('p',{class:'hint'},'Drag pieces onto the grid. Full rows and columns clear. Bombs count down each time you place a piece, so clear their row or column in time!'));
  const SH=[[[0,0]],[[0,0],[1,0]],[[0,0],[0,1]],[[0,0],[1,0],[2,0]],[[0,0],[0,1],[0,2]],[[0,0],[1,0],[0,1],[1,1]],[[0,0],[1,0],[2,0],[3,0]],[[0,0],[0,1],[0,2],[0,3]],[[0,0],[1,0],[2,0],[3,0],[4,0]],[[0,0],[0,1],[0,2],[0,3],[0,4]],[[0,0],[0,1],[1,1]],[[1,0],[0,1],[1,1]],[[0,0],[1,0],[0,1]],[[0,0],[1,0],[1,1]],[[0,0],[1,0],[2,0],[0,1],[1,1],[2,1],[0,2],[1,2],[2,2]],[[0,0],[0,1],[0,2],[1,2],[2,2]],[[2,0],[2,1],[2,2],[1,2],[0,2]]];const COL=['#F2352A','#FF9F43','#FFD23F','#2BB673','#2d6fd6','#B9A7FF','#FF8FB1'];
  let grid,tray,score,placed,drag=null,state='play',best=c.best()||0,pops=[];
  function reset(){grid=Array(N*N).fill(null);score=0;placed=0;state='play';deal()}
  function deal(){tray=[0,1,2].map(i=>({s:pick(SH),col:pick(COL),i}));if(!tray.some(t=>fitsAny(t.s))){over()}}
  const fits=(s,gx,gy)=>s.every(([a,b])=>{const X=gx+a,Y=gy+b;return X>=0&&Y>=0&&X<N&&Y<N&&!grid[Y*N+X]});const fitsAny=s=>{for(let y=0;y<N;y++)for(let x2=0;x2<N;x2++)if(fits(s,x2,y))return true;return false};
  function place(t,gx,gy){t.s.forEach(([a,b])=>grid[(gy+b)*N+gx+a]={col:t.col});score+=t.s.length;placed++;beep(500,.05,'triangle',.04);grid.forEach(q=>{if(q&&q.bomb)q.bomb--});
    if(placed%c.pick(7,6,5)===0){const empty=grid.map((q,i)=>q?-1:i).filter(i=>i>=0);if(empty.length){const i=pick(empty);grid[i]={col:'#1D1A2F',bomb:c.pick(9,8,7)}}}
    const rows=[],cols=[];for(let k=0;k<N;k++){let r=true,cc=true;for(let j=0;j<N;j++){if(!grid[k*N+j])r=false;if(!grid[j*N+k])cc=false}if(r)rows.push(k);if(cc)cols.push(k)}const clear=new Set();rows.forEach(r=>{for(let j=0;j<N;j++)clear.add(r*N+j)});cols.forEach(cc=>{for(let j=0;j<N;j++)clear.add(j*N+cc)});
    if(clear.size){const lines=rows.length+cols.length;score+=lines*10*lines;clear.forEach(i=>{pops.push({i,col:grid[i].col,l:1});grid[i]=null});beep(880,.12,'triangle',.06)}if(grid.some(q=>q&&q.bomb===0)){over('A bomb went off!');return}tray=tray.filter(q=>q!==t);if(!tray.length)deal();else if(!tray.some(q=>fitsAny(q.s)))over();c.stat('Hundred Blocks · '+score)}
  function over(why){state='over';best=c.best(score);noise(.5,'lowpass',300,.3);overMsg=why||'No room left'}let overMsg='';
  const trayPos=i=>({x:Wc/6+i*Wc/3,y:OY+N*Q+90});
  function drawPiece(t,cx,cy,q){const w=Math.max(...t.s.map(p=>p[0]))+1,h=Math.max(...t.s.map(p=>p[1]))+1;t.s.forEach(([a,b])=>{x.fillStyle=t.col;x.fillRect(cx-w*q/2+a*q+1,cy-h*q/2+b*q+1,q-2,q-2)})}
  function draw(){x.fillStyle='#1D1A2F';x.fillRect(0,0,Wc,Hc);for(let i=0;i<N*N;i++){const gx=i%N,gy=i/N|0;const q=grid[i];x.fillStyle=q?q.col:'#2a2640';x.fillRect(OX+gx*Q+1,OY+gy*Q+1,Q-2,Q-2);if(q&&q.bomb!=null){x.fillStyle=q.bomb<=2?'#F2352A':'#FF9F43';x.beginPath();x.arc(OX+gx*Q+Q/2,OY+gy*Q+Q/2,Q*.34,0,7);x.fill();x.fillStyle='#fff';x.font='800 18px Figtree';x.textAlign='center';x.textBaseline='middle';x.fillText(q.bomb,OX+gx*Q+Q/2,OY+gy*Q+Q/2+1)}}
    pops.forEach(p=>{p.l-=.05;x.fillStyle=p.col;x.globalAlpha=Math.max(0,p.l);const s=Q*(1+(1-p.l)*.5);x.fillRect(OX+(p.i%N)*Q+Q/2-s/2,OY+(p.i/N|0)*Q+Q/2-s/2,s,s);x.globalAlpha=1});pops=pops.filter(p=>p.l>0);
    if(drag){const gx=Math.round((drag.x-OX)/Q-drag.w/2),gy=Math.round((drag.y-OY-80)/Q-drag.h/2);if(fits(drag.t.s,gx,gy)){x.globalAlpha=.35;drag.t.s.forEach(([a,b])=>{x.fillStyle=drag.t.col;x.fillRect(OX+(gx+a)*Q+1,OY+(gy+b)*Q+1,Q-2,Q-2)});x.globalAlpha=1}}
    tray.forEach(t=>{if(drag&&drag.t===t)return;const p=trayPos(t.i);x.globalAlpha=fitsAny(t.s)?1:.35;drawPiece(t,p.x,p.y,26);x.globalAlpha=1});if(drag)drawPiece(drag.t,drag.x,drag.y-80,Q);
    x.fillStyle='#fff';x.font='800 20px "JetBrains Mono"';x.textAlign='left';x.fillText(score+'',OX,22);x.textAlign='right';x.fillText('best '+best,OX+N*Q,22);if(state==='over')banner(x,Wc,Hc,overMsg,score+' points · tap to play again')}
  c.on(cv,'pointerdown',e=>{if(state==='over'){reset();return}const p=canvasPos(cv,e);tray.forEach(t=>{const tp=trayPos(t.i);if(Math.abs(p.x-tp.x)<70&&Math.abs(p.y-tp.y)<70){drag={t,x:p.x,y:p.y,w:Math.max(...t.s.map(q=>q[0]))+1,h:Math.max(...t.s.map(q=>q[1]))+1};cv.setPointerCapture(e.pointerId)}})});
  c.on(cv,'pointermove',e=>{if(drag){const p=canvasPos(cv,e);drag.x=p.x;drag.y=p.y}});c.on(cv,'pointerup',()=>{if(!drag)return;const gx=Math.round((drag.x-OX)/Q-drag.w/2),gy=Math.round((drag.y-OY-80)/Q-drag.h/2);if(fits(drag.t.s,gx,gy))place(drag.t,gx,gy);drag=null});
  reset();c.loop(()=>draw())}});
/* ---------- Jello Reversi ---------- */
G.push({id:'jelloreversi',name:'Ojello',kind:'puzzle',levels:true,tint:'#2BB673',blurb:'Reversi with wobbly jello. Trap the computer’s jellies between yours to flip them to your color.',fmt:b=>b+' wins',
art:'<rect width="120" height="72" fill="#2BB673"/><g stroke="#1a5a30" stroke-width="1">'+[1,2,3,4,5].map(i=>'<path d="M'+(i*20)+' 0v72"/>').join('')+[1,2,3].map(i=>'<path d="M0 '+(i*18)+'h120"/>').join('')+'</g><ellipse cx="50" cy="27" rx="8" ry="7" fill="#FF8FB1" stroke="#1D1A2F" stroke-width="2"/><ellipse cx="70" cy="45" rx="8" ry="7" fill="#FF8FB1" stroke="#1D1A2F" stroke-width="2"/><ellipse cx="70" cy="27" rx="8" ry="7" fill="#7FC8F8" stroke="#1D1A2F" stroke-width="2"/><ellipse cx="50" cy="45" rx="8" ry="7" fill="#7FC8F8" stroke="#1D1A2F" stroke-width="2"/>',
run(root,c){const SZ=560,Q=SZ/8;const[cv,x]=mk(SZ,SZ,'width:min(100%,560px)');const status=el('p',{class:'hint',style:'font-weight:700'});const nb=el('button',{class:'btn',type:'button'},'New game');root.append(cv,status,el('div',{class:'row'},nb));
  const WT=[100,-20,10,5,5,10,-20,100,-20,-50,-2,-2,-2,-2,-50,-20,10,-2,-1,-1,-1,-1,-2,10,5,-2,-1,-1,-1,-1,-2,5,5,-2,-1,-1,-1,-1,-2,5,10,-2,-1,-1,-1,-1,-2,10,-20,-50,-2,-2,-2,-2,-50,-20,100,-20,10,5,5,10,-20,100];
  let B,turn,wob,over=false,busy=false,wins=S.get('oj_w',0),alive=true,lastMv=-1;
  function reset(){B=Array(64).fill(0);B[27]=B[36]=-1;B[28]=B[35]=1;turn=1;wob=Array(64).fill(0);over=false;lastMv=-1;upd()}
  function flips(bd,s,side){if(bd[s])return[];const out=[];for(const[dr,df]of[[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]]){let r=(s>>3)+dr,f=(s&7)+df;const line=[];while(r>=0&&r<8&&f>=0&&f<8&&bd[r*8+f]===-side){line.push(r*8+f);r+=dr;f+=df}if(line.length&&r>=0&&r<8&&f>=0&&f<8&&bd[r*8+f]===side)out.push(...line)}return out}
  const movesOf=(bd,side)=>{const m=[];for(let s=0;s<64;s++)if(flips(bd,s,side).length)m.push(s);return m};
  function apply(bd,s,side){const nb=bd.slice();const f=flips(bd,s,side);nb[s]=side;f.forEach(i=>nb[i]=side);return nb}
  function ev(bd){let s=0;for(let i=0;i<64;i++)s+=bd[i]*WT[i];return s+(movesOf(bd,1).length-movesOf(bd,-1).length)*8}
  function mm(bd,d,a,b,side){const ms=movesOf(bd,side);if(d===0)return ev(bd);if(!ms.length){if(!movesOf(bd,-side).length){const t=bd.reduce((p,q)=>p+q,0);return t*1000}return mm(bd,d-1,a,b,-side)}if(side===1){let v=-1e9;for(const m of ms){v=Math.max(v,mm(apply(bd,m,1),d-1,a,b,-1));a=Math.max(a,v);if(a>=b)break}return v}let v=1e9;for(const m of ms){v=Math.min(v,mm(apply(bd,m,-1),d-1,a,b,1));b=Math.min(b,v);if(a>=b)break}return v}
  function play(s,side){const f=flips(B,s,side);B=apply(B,s,side);wob[s]=1;f.forEach((i,k)=>setTimeout(()=>{wob[i]=1},k*40));lastMv=s;beep(side===1?500:350,.06,'sine',.05);turn=-side;upd()}
  function upd(){const my=movesOf(B,1),ai=movesOf(B,-1);const nw=B.filter(v=>v===1).length,nb=B.filter(v=>v===-1).length;if(!my.length&&!ai.length){over=true;const win=nw>nb;status.textContent=(win?'You win! ':nw===nb?'Draw. ':'The computer wins. ')+nw+' – '+nb;if(win){wins++;S.set('oj_w',wins);c.best(wins)}return}if(turn===1&&!my.length){turn=-1}else if(turn===-1&&!ai.length){turn=1}
    status.textContent=(turn===1?'Your move (pink)':'Computer is thinking…')+' · '+nw+' – '+nb;c.stat('Ojello · wins '+wins);if(turn===-1){busy=true;setTimeout(()=>{if(!alive)return;const ms=movesOf(B,-1);let best=ms[0],bv=1e9;const d=c.pick(1,3,5);shuffle(ms).forEach(m=>{const v=(c.level===0?WT[m]*-1+Math.random()*80:mm(apply(B,m,-1),d-1,-1e9,1e9,1));if(v<bv){bv=v;best=m}});play(best,-1);busy=false},450)}}
  function draw(){x.fillStyle='#2BB673';x.fillRect(0,0,SZ,SZ);x.strokeStyle='#1a5a30';x.lineWidth=2;for(let i=1;i<8;i++){x.beginPath();x.moveTo(i*Q,0);x.lineTo(i*Q,SZ);x.moveTo(0,i*Q);x.lineTo(SZ,i*Q);x.stroke()}const hint=turn===1&&!over?movesOf(B,1):[];hint.forEach(s=>{x.fillStyle='rgba(255,255,255,.25)';x.beginPath();x.arc((s&7)*Q+Q/2,(s>>3)*Q+Q/2,Q*.12,0,7);x.fill()});
    for(let s=0;s<64;s++){if(!B[s])continue;wob[s]=Math.max(0,wob[s]-.03);const w=Math.sin(performance.now()/60+s)*wob[s]*.25;const cx=(s&7)*Q+Q/2,cy=(s>>3)*Q+Q/2;x.fillStyle='rgba(0,0,0,.25)';x.beginPath();x.ellipse(cx,cy+6,Q*.38,Q*.2,0,0,7);x.fill();x.fillStyle=B[s]===1?'#FF8FB1':'#7FC8F8';x.strokeStyle='#1D1A2F';x.lineWidth=2.5;x.beginPath();x.ellipse(cx,cy,Q*.38*(1+w),Q*.34*(1-w),0,0,7);x.fill();x.stroke();x.fillStyle='rgba(255,255,255,.55)';x.beginPath();x.ellipse(cx-Q*.12,cy-Q*.12,Q*.1,Q*.06,-.5,0,7);x.fill();if(s===lastMv){x.fillStyle='#1D1A2F';x.beginPath();x.arc(cx,cy,3,0,7);x.fill()}}}
  c.on(cv,'pointerdown',e=>{if(over||turn!==1||busy)return;const p=canvasPos(cv,e);const s=Math.floor(p.y/Q)*8+Math.floor(p.x/Q);if(flips(B,s,1).length)play(s,1);else beep(180,.05,'square',.03)});nb.addEventListener('click',reset);reset();c.loop(()=>draw());return()=>{alive=false}}});
/* ---------- Hex Fit ---------- */
G.push({id:'hexfit',name:'Hexaginta',kind:'puzzle',tint:'#B9A7FF',blurb:'Drop hexagon pieces onto a honeycomb board. Fill any straight line, in any of the three directions, to clear it.',fmt:b=>b+' pts',
art:'<rect width="120" height="72" fill="#1D1A2F"/>'+[[40,20],[54,28],[68,20],[54,44],[40,36],[68,36],[82,28]].map(([a,b],i)=>'<polygon points="'+[0,1,2,3,4,5].map(k=>(a+7*Math.cos(k*Math.PI/3+Math.PI/6)).toFixed(1)+','+(b+7*Math.sin(k*Math.PI/3+Math.PI/6)).toFixed(1)).join(' ')+'" fill="'+(i<4?'#B9A7FF':'#3a3552')+'" stroke="#1D1A2F"/>').join(''),
run(root,c){const Wc=560,Hc=680,R=4,S2=30;const[cv,x]=mk(Wc,Hc,'width:min(100%,560px)');root.append(cv,el('p',{class:'hint'},'Drag a piece onto the board. Any complete straight line of hexes (in any of three directions) clears. The game ends when nothing fits.'));
  const cells=[];for(let q=-R;q<=R;q++)for(let r=Math.max(-R,-q-R);r<=Math.min(R,-q+R);r++)cells.push([q,r]);const key=(q,r)=>q+','+r;const CX=Wc/2,CY=300;const pix=(q,r)=>[CX+S2*Math.sqrt(3)*(q+r/2),CY+S2*1.5*r];
  const SH=[[[0,0]],[[0,0],[1,0]],[[0,0],[0,1]],[[0,0],[1,-1]],[[0,0],[1,0],[2,0]],[[0,0],[0,1],[0,2]],[[0,0],[1,-1],[2,-2]],[[0,0],[1,0],[0,1]],[[0,0],[1,0],[1,-1]],[[0,0],[1,0],[2,0],[3,0]],[[0,0],[1,0],[0,1],[1,-1]],[[0,0],[1,0],[2,-1]],[[0,0],[0,1],[1,1]]];const COL=['#B9A7FF','#FF8FB1','#7FC8F8','#6EE7B7','#FFD23F','#FF9F43'];
  let B,tray,score,drag=null,state='play',best=c.best()||0,pops=[];
  function reset(){B={};score=0;state='play';deal()}function deal(){tray=[0,1,2].map(i=>({s:pick(SH),col:pick(COL),i}));if(!tray.some(t=>anyFit(t.s)))over()}
  const ok=(q,r)=>Math.abs(q)<=R&&Math.abs(r)<=R&&Math.abs(q+r)<=R;const fits=(s,q,r)=>s.every(([a,b])=>ok(q+a,r+b)&&!B[key(q+a,r+b)]);const anyFit=s=>cells.some(([q,r])=>fits(s,q,r));
  function place(t,q,r){t.s.forEach(([a,b])=>B[key(q+a,r+b)]=t.col);score+=t.s.length;beep(500,.05,'triangle',.04);const lines=[];for(let k=-R;k<=R;k++){[c3=>c3[0]===k,c3=>c3[1]===k,c3=>-c3[0]-c3[1]===k].forEach(f=>{const L=cells.filter(f);if(L.every(([a,b])=>B[key(a,b)]))lines.push(L)})}
    if(lines.length){const cl=new Set();lines.forEach(L=>L.forEach(([a,b])=>cl.add(key(a,b))));cl.forEach(k=>{const[a,b]=k.split(',').map(Number);pops.push({q:a,r:b,col:B[k],l:1});delete B[k]});score+=lines.length*lines.length*15;beep(880,.12,'triangle',.06)}tray=tray.filter(q=>q!==t);if(!tray.length)deal();else if(!tray.some(q=>anyFit(q.s)))over();c.stat('Hexaginta · '+score)}
  function over(){state='over';best=c.best(score);noise(.4,'lowpass',300,.3)}
  function hex(px,py,s,fill){x.beginPath();for(let k=0;k<6;k++){const a=k*Math.PI/3+Math.PI/6;x.lineTo(px+s*Math.cos(a),py+s*Math.sin(a))}x.closePath();x.fillStyle=fill;x.fill();x.strokeStyle='#1D1A2F';x.lineWidth=2;x.stroke()}
  const trayPos=i=>[Wc/6+i*Wc/3,590];const snap=(px,py)=>{let best2=null,bd=1e9;cells.forEach(([q,r])=>{const[a,b]=pix(q,r);const d=Math.hypot(a-px,b-py);if(d<bd){bd=d;best2=[q,r]}});return bd<S2*1.2?best2:null};
  function draw(){x.fillStyle='#1D1A2F';x.fillRect(0,0,Wc,Hc);cells.forEach(([q,r])=>{const[a,b]=pix(q,r);hex(a,b,S2-2,B[key(q,r)]||'#2a2640')});pops.forEach(p=>{p.l-=.05;const[a,b]=pix(p.q,p.r);x.globalAlpha=Math.max(0,p.l);hex(a,b,(S2-2)*(1+(1-p.l)*.4),p.col);x.globalAlpha=1});pops=pops.filter(p=>p.l>0);
    if(drag){const sn=snap(drag.x,drag.y-60);if(sn&&fits(drag.t.s,sn[0],sn[1])){x.globalAlpha=.4;drag.t.s.forEach(([a,b])=>{const[px,py]=pix(sn[0]+a,sn[1]+b);hex(px,py,S2-2,drag.t.col)});x.globalAlpha=1}}
    tray.forEach(t=>{const[tx,ty]=drag&&drag.t===t?[drag.x,drag.y-60]:trayPos(t.i);const s=drag&&drag.t===t?S2:18;x.globalAlpha=anyFit(t.s)?1:.35;t.s.forEach(([a,b])=>{hex(tx+s*Math.sqrt(3)*(a+b/2),ty+s*1.5*b,s-2,t.col)});x.globalAlpha=1});
    x.fillStyle='#fff';x.font='800 20px "JetBrains Mono"';x.textAlign='left';x.fillText(score,20,34);x.textAlign='right';x.fillText('best '+best,Wc-20,34);if(state==='over')banner(x,Wc,Hc,'No more room',score+' points · tap to play again')}
  c.on(cv,'pointerdown',e=>{if(state==='over'){reset();return}const p=canvasPos(cv,e);tray.forEach(t=>{const[tx,ty]=trayPos(t.i);if(Math.hypot(p.x-tx,p.y-ty)<70){drag={t,x:p.x,y:p.y};cv.setPointerCapture(e.pointerId)}})});c.on(cv,'pointermove',e=>{if(drag){const p=canvasPos(cv,e);drag.x=p.x;drag.y=p.y}});c.on(cv,'pointerup',()=>{if(!drag)return;const sn=snap(drag.x,drag.y-60);if(sn&&fits(drag.t.s,sn[0],sn[1]))place(drag.t,sn[0],sn[1]);drag=null});
  reset();c.loop(()=>draw())}});
/* ---------- Ancient Blocks ---------- */
G.push({id:'ancient',name:'Ancient Blocks',kind:'puzzle',levels:true,tint:'#c9a36a',blurb:'Fit carved stone pieces into the temple wall so there are no gaps. Rotate pieces to make them fit.',fmt:b=>'level '+b,
art:'<rect width="120" height="72" fill="#e8d3a3"/><path d="M20 62V30l40-20 40 20v32z" fill="#c9a36a" stroke="#1D1A2F" stroke-width="2.5"/><g stroke="#1D1A2F" stroke-width="2"><rect x="34" y="36" width="14" height="14" fill="#8a5a2b"/><rect x="48" y="36" width="14" height="14" fill="#8a5a2b"/><rect x="62" y="36" width="14" height="26" fill="#6b8a5a"/></g>',
run(root,c){const Wc=720,Hc=620;const[cv,x]=mk(Wc,Hc,'width:min(100%,720px)');root.append(cv,el('p',{class:'hint'},'Drag the stones into the carved outline. Right-click or double-tap a stone to rotate it. Fill every gap to open the temple.'));
  let lvl=Math.max(1,S.get('anc_lv',1)),N,region,pieces,board,drag=null,state='play',Q,OX,OY;const COL=['#8a5a2b','#6b8a5a','#a0522d','#7a6a9a','#b08a4a','#5a7a8a','#9a5a5a','#6a6a4a'];
  function build(){N=Math.min(9,4+Math.floor(lvl/2));const target=Math.min(N*N-4,8+lvl*3);const reg=new Set();const c0=Math.floor(N/2)*N+Math.floor(N/2);reg.add(c0);while(reg.size<target){const arr=[...reg];const k=pick(arr);const d=pick([1,-1,N,-N]);const j=k+d;if(j<0||j>=N*N||(d===1&&j%N===0)||(d===-1&&k%N===0))continue;reg.add(j)}region=reg;
    const owner=new Map();const cellsL=shuffle([...reg]);let pid=0;const maxP=lvl<3?3:lvl<6?4:5;for(const cc of cellsL){if(owner.has(cc))continue;const grp=[cc];owner.set(cc,pid);let tries=0;const want=Math.min(maxP,2+rand(maxP-1));while(grp.length<want&&tries++<30){const k=pick(grp);const d=pick([1,-1,N,-N]);const j=k+d;if(!reg.has(j)||owner.has(j)||(d===1&&j%N===0)||(d===-1&&k%N===0))continue;owner.set(j,pid);grp.push(j)}pid++}
    pieces=[];for(let p=0;p<pid;p++){const cs=[...owner].filter(([k,v])=>v===p).map(([k])=>[k%N,k/N|0]);const mx=Math.min(...cs.map(q=>q[0])),my=Math.min(...cs.map(q=>q[1]));let sh=cs.map(([a,b])=>[a-mx,b-my]);for(let r=rand(4);r>0;r--)sh=rot(sh);pieces.push({sh,col:COL[p%COL.length],placed:null,tx:0,ty:0})}
    Q=Math.min(52,340/N);OX=40;OY=(Hc-N*Q)/2;board=new Map();layoutTray();state='play';c.stat('Ancient Blocks · level '+lvl)}
  function rot(sh){const r=sh.map(([a,b])=>[-b,a]);const mx=Math.min(...r.map(q=>q[0])),my=Math.min(...r.map(q=>q[1]));return r.map(([a,b])=>[a-mx,b-my])}
  function layoutTray(){let tx=OX+N*Q+40,ty=40;const rowH=[];pieces.filter(p=>!p.placed).forEach(p=>{const w=(Math.max(...p.sh.map(q=>q[0]))+1)*Q*.7,h=(Math.max(...p.sh.map(q=>q[1]))+1)*Q*.7;if(tx+w>Wc-20){tx=OX+N*Q+40;ty+=Math.max(...rowH,0)+20;rowH.length=0}p.tx=tx;p.ty=ty;tx+=w+20;rowH.push(h)})}
  const canPlace=(p,gx,gy)=>p.sh.every(([a,b])=>{const X=gx+a,Y=gy+b;const k=Y*N+X;return X>=0&&Y>=0&&X<N&&Y<N&&region.has(k)&&!board.has(k)});
  function draw(){x.fillStyle='#e8d3a3';x.fillRect(0,0,Wc,Hc);x.fillStyle='rgba(138,90,43,.15)';for(let i=0;i<30;i++)x.fillRect((i*137)%Wc,(i*71)%Hc,40,3);
    for(let k=0;k<N*N;k++){const gx=k%N,gy=k/N|0;if(!region.has(k))continue;x.fillStyle='#b8966a';x.fillRect(OX+gx*Q+1,OY+gy*Q+1,Q-2,Q-2);x.strokeStyle='rgba(29,26,47,.3)';x.setLineDash([4,3]);x.strokeRect(OX+gx*Q+3,OY+gy*Q+3,Q-6,Q-6);x.setLineDash([])}
    const drawP=(p,px,py,q)=>{p.sh.forEach(([a,b])=>{x.fillStyle=p.col;x.fillRect(px+a*q+1,py+b*q+1,q-2,q-2);x.strokeStyle='#1D1A2F';x.lineWidth=2;x.strokeRect(px+a*q+1,py+b*q+1,q-2,q-2);x.fillStyle='rgba(255,255,255,.15)';x.fillRect(px+a*q+4,py+b*q+4,q*.4,4)})};
    pieces.forEach(p=>{if(p.placed&&p!==(drag&&drag.p))drawP(p,OX+p.placed[0]*Q,OY+p.placed[1]*Q,Q)});pieces.forEach(p=>{if(!p.placed&&p!==(drag&&drag.p))drawP(p,p.tx,p.ty,Q*.7)});
    if(drag){const gx=Math.round((drag.x-drag.ox-OX)/Q),gy=Math.round((drag.y-drag.oy-OY)/Q);if(canPlace(drag.p,gx,gy)){x.globalAlpha=.35;drawP(drag.p,OX+gx*Q,OY+gy*Q,Q);x.globalAlpha=1}drawP(drag.p,drag.x-drag.ox,drag.y-drag.oy,Q)}
    x.fillStyle='#1D1A2F';x.font='700 16px "JetBrains Mono"';x.textAlign='left';x.fillText('LEVEL '+lvl+'   stones left '+pieces.filter(p=>!p.placed).length,20,28);if(state==='won')banner(x,Wc,Hc,'The temple opens!','Tap for level '+(lvl+1))}
  function hitPiece(px,py){for(const p of pieces.slice().reverse()){const bx=p.placed?OX+p.placed[0]*Q:p.tx,by=p.placed?OY+p.placed[1]*Q:p.ty,q=p.placed?Q:Q*.7;if(p.sh.some(([a,b])=>px>bx+a*q&&px<bx+a*q+q&&py>by+b*q&&py<by+b*q+q))return{p,bx,by,q}}return null}
  function rotate(p){if(p.placed){p.placed[2].forEach(k=>board.delete(k));p.placed=null}p.sh=rot(p.sh);layoutTray();beep(600,.04,'triangle',.03)}
  let lastTap=0;c.on(cv,'contextmenu',e=>e.preventDefault());c.on(cv,'pointerdown',e=>{if(state==='won'){lvl++;build();return}const p=canvasPos(cv,e);const h=hitPiece(p.x,p.y);if(!h)return;const now=performance.now();if(e.button===2||now-lastTap<300&&h){rotate(h.p);lastTap=0;return}lastTap=now;if(h.p.placed){h.p.placed[2].forEach(k=>board.delete(k));h.p.placed=null}const scale=Q/h.q;drag={p:h.p,x:p.x,y:p.y,ox:(p.x-h.bx)*scale,oy:(p.y-h.by)*scale};cv.setPointerCapture(e.pointerId)});
  c.on(cv,'pointermove',e=>{if(drag){const p=canvasPos(cv,e);drag.x=p.x;drag.y=p.y}});c.on(cv,'pointerup',()=>{if(!drag)return;const gx=Math.round((drag.x-drag.ox-OX)/Q),gy=Math.round((drag.y-drag.oy-OY)/Q);const p=drag.p;if(canPlace(p,gx,gy)){const ks=p.sh.map(([a,b])=>(gy+b)*N+gx+a);ks.forEach(k=>board.set(k,p));p.placed=[gx,gy,ks];noise(.08,'lowpass',400,.2);if(board.size===region.size){state='won';S.set('anc_lv',Math.max(S.get('anc_lv',1),lvl+1));c.best(lvl);[392,523,659,784].forEach((q,i)=>c.after(()=>beep(q,.18,'triangle',.06),i*110))}}drag=null;layoutTray()});
  build();c.loop(()=>draw())}});
