/* ================= HERO FREE ROAM: city life + hero jobs ================= */
// o: {id, city, pos:()=>({x,y,z}), fly:bool, chase:speed of getaway cars, name}
function heroRoam(K,o){const{T,scene,TM,H}=K;const city=o.city,cell=city.cell;
  const sl=v=>city.half!=null?-city.half+Math.round((v+city.half)/cell)*cell:Math.round(v/cell)*cell;
  const onX=x=>Math.abs(x-sl(x))<city.st/2-1;const lim=city.lim||1e9;
  const inB=(x,y,z,p)=>K.inBox(x,y,z,city.boxes,p);const V3=(x,y,z)=>new T.Vector3(x,y,z);
  const hp=()=>{const p=o.pos();return V3(p.x,p.y,p.z)};const hd=(p,q)=>Math.hypot(p.x-q.x,p.z-q.z);
  let on=false,objs=[],jobs=[],coins=[],race=null,gate=null,gateT=0,jobT=6,cheerT=0,time=0,done=0;
  const add=m=>{scene.add(m);objs.push(m);return m};const drop=m=>{scene.remove(m);const i=objs.indexOf(m);if(i>=0)objs.splice(i,1)};
  const KEY=o.id+'_roam';let pts=S.get(KEY+'_pts',0),coinTot=S.get(KEY+'_coins',0),raceBest=S.get(KEY+'_race',0);
  const RANKS=[[0,'Rookie'],[150,'Sidekick'],[400,'Hero'],[900,'Super Hero'],[1800,'Legend'],[3500,'Living Legend']];const rank=()=>RANKS.filter(r=>pts>=r[0]).pop()[1];
  const panel=el('div',{style:'position:absolute;left:10px;top:92px;background:rgba(29,26,47,.84);color:#FFFDF6;border:2px solid #FFD23F;border-radius:8px;padding:6px 10px;font:600 12px Figtree,sans-serif;max-width:240px;pointer-events:none;line-height:1.4;display:none'});K.hud.append(panel);const ptr=K.pointer();
  function award(n,why,at){const r0=rank();pts+=n;S.set(KEY+'_pts',pts);done++;H.pow('+'+n+' '+why,at||hp().add(V3(0,4,0)),'#FFD23F');beep(660,.1,'triangle',.07);setTimeout(()=>beep(990,.14,'triangle',.07),110);if(rank()!==r0)H.say('Rank up! You are now a '+rank()+'!',2400);cheer(at||hp())}
  function streetPt(rmin,rmax){const P0=hp();for(let k=0;k<40;k++){const a=Math.random()*6.283,r=rmin+Math.random()*(rmax-rmin);let x=P0.x+Math.cos(a)*r,z=P0.z+Math.sin(a)*r;if(Math.random()<.5)x=sl(x)+(Math.random()-.5)*(city.st-6);else z=sl(z)+(Math.random()-.5)*(city.st-6);if(Math.abs(x)>lim||Math.abs(z)>lim)continue;if(!inB(x,1,z,1.5))return{x,z}}return null}
  const beamM=c0=>new T.MeshBasicMaterial({color:c0,transparent:true,opacity:.3,depthWrite:false});
  function beam(c0,h){const m=new T.Mesh(cy(T,1.4,1.4,h,12),beamM(c0));m.userData.noInk=1;return m}
  // ---- people ----
  const pG={leg:bx(T,.62,.85,.36),body:bx(T,.72,.85,.42),head:bx(T,.46,.46,.46),arm:bx(T,.2,.75,.2)};pG.arm.translate(0,-.33,0);
  const shirtM=[0xF2352A,0x7FC8F8,0xFFD23F,0x6EE7B7,0xFF8FB1,0xB9A7FF,0xffffff,0xFF9F43,0x2d6fd6].map(v=>TM(v)),pantsM=[0x2d3a5a,0x3a3552,0x5a3a2a,0x1D1A2F].map(v=>TM(v)),skinM=[0xf1c7a0,0xc68a5a,0x8d5a3a,0xffd9b8].map(v=>TM(v));
  function personMesh(){const g=new T.Group();part(T,pG.leg,pick(pantsM),0,.43,0,g);const sh=pick(shirtM);part(T,pG.body,sh,0,1.28,0,g);part(T,pG.head,pick(skinM),0,1.95,0,g);const aL=part(T,pG.arm,sh,-.47,1.66,0,g),aR=part(T,pG.arm,sh,.47,1.66,0,g);g.scale.setScalar(1.25);g.userData={aL,aR};return g}
  const people=[];function placeP(q){const off=(city.cell-city.blk)/2;for(let k=0;k<12;k++){const p=streetPt(12,170);if(!p)continue;const az=onX(p.x);const s=Math.random()<.5?-1:1;let x=p.x,z=p.z;if(az)x=sl(x)+s*off;else z=sl(z)+s*off;if(inB(x,.5,z,.4))continue;q.g.position.set(x,0,z);q.ax=az?'z':'x';q.dir=Math.random()<.5?-1:1;q.st='walk';q.t=Math.random()*6;q.sp=1.3+Math.random()*.9;q.g.visible=true;q.g.rotation.set(0,0,0);return}q.g.visible=false;q.st='gone'}
  function cheer(at){people.forEach(q=>{if(q.st!=='gone'&&hd(q.g.position,at)<45){q.st='cheer';q.ct=2+Math.random()}});if(Math.random()<.6)H.pow(pick(['HOORAY!','YAY!','MY HERO!','WOOO!']),at.clone().add(V3(4,6,0)),'#fff')}
  function tickPeople(dt,P0,spd){for(const q of people){const g=q.g;q.t+=dt;if(q.st==='gone'){if(Math.random()<dt)placeP(q);continue}const p=g.position;const d=hd(p,P0);if(d>240){placeP(q);continue}
      const u=g.userData;if(q.st==='cheer'){q.ct-=dt;g.rotation.y=Math.atan2(P0.x-p.x,P0.z-p.z);u.aL.rotation.x=-2.8+Math.sin(q.t*14)*.4;u.aR.rotation.x=-2.8+Math.cos(q.t*14)*.4;p.y=Math.abs(Math.sin(q.t*9))*.35;if(q.ct<=0)q.st='walk';continue}
      if(q.st==='hop'){q.vy-=30*dt;p.y+=q.vy*dt;p.x+=q.vx*dt;p.z+=q.vz*dt;if(p.y<=0){p.y=0;q.st='walk';if(Math.random()<.25)H.pow(pick(['WHOA!','HEY!','SO FAST!']),p.clone().add(V3(0,3,0)),'#fff')}continue}
      if(d<7&&spd>25&&Math.abs(P0.y-p.y)<4){const a=Math.atan2(p.x-P0.x,p.z-P0.z);q.st='hop';q.vy=8;q.vx=Math.sin(a)*6;q.vz=Math.cos(a)*6;continue}
      if(d<9&&spd<6&&Math.abs(P0.y-p.y)<6&&Math.random()<dt*.6){q.st='cheer';q.ct=1.5;continue}
      const ox=p.x,oz=p.z;if(q.ax==='z')p.z+=q.dir*q.sp*dt;else p.x+=q.dir*q.sp*dt;if(inB(p.x,.5,p.z,.3)||Math.abs(p.x)>lim||Math.abs(p.z)>lim){p.x=ox;p.z=oz;q.dir*=-1}
      g.rotation.y=q.ax==='z'?(q.dir>0?0:Math.PI):(q.dir>0?Math.PI/2:-Math.PI/2);const ph=q.t*q.sp*2.2;p.y=Math.abs(Math.sin(ph))*.08;u.aL.rotation.x=Math.sin(ph)*.6;u.aR.rotation.x=-Math.sin(ph)*.6}}
  // ---- aircraft (ambient) ----
  const air=[];
  function makeAir(type,falling){const g=add(new T.Group());g.rotation.order='YXZ';let a;const P0=hp();
    if(type==='plane'){const W=TM(0xf4f4f8),S2=TM(pick([0xF2352A,0x2d6fd6,0x2BB673,0xFF9F43,0xB9A7FF]));part(T,cy(T,1.6,1.6,17,12),W,0,0,0,g).rotation.x=Math.PI/2;part(T,sp(T,1.6),W,0,0,8.5,g);const tl=part(T,new T.ConeGeometry(1.6,4,12),W,0,.3,-10.4,g);tl.rotation.x=-Math.PI/2;part(T,bx(T,23,.35,3.2),W,0,-.4,.5,g);part(T,bx(T,.3,3.4,2.6),S2,0,2.2,-10,g);part(T,bx(T,7,.25,2),W,0,.4,-10.4,g);[-1,1].forEach(s=>{part(T,bx(T,.2,.55,15),S2,s*1.58,0,0,g);part(T,cy(T,.7,.7,2.6,10),S2,s*5.5,-1.1,1.3,g).rotation.x=Math.PI/2});
      const h=Math.random()*6.283,off=(Math.random()-.5)*(falling?60:160);const dir=V3(Math.sin(h),0,Math.cos(h)),pp=V3(-dir.z,0,dir.x);g.position.set(P0.x,falling?95+Math.random()*30:135+Math.random()*30,P0.z).addScaledVector(dir,falling?-160:-380).addScaledVector(pp,off);a={v:dir.multiplyScalar(falling?30:48)}}
    else if(type==='heli'){const B=TM(pick([0xFFD23F,0xF2352A,0xffffff])),D=TM(0x1D1A2F);const bd=part(T,sp(T,1),B,0,0,0,g);bd.scale.set(1.8,1.6,2.6);part(T,bx(T,.45,.45,5.5),B,0,.3,-4.2,g);part(T,bx(T,.15,1.6,.8),B,0,.9,-6.8,g);const gl=part(T,sp(T,1),TM(0x9fd6ff),0,.3,1.4,g);gl.scale.set(1.2,1,1.2);[-1,1].forEach(s=>part(T,bx(T,.15,.15,3.6),D,s*1.1,-1.8,0,g));const rot=part(T,bx(T,11,.1,.55),D,0,2.3,0,g);part(T,bx(T,.55,.1,11),D,0,0,0,rot);a={rot,ang:Math.random()*6.283,v:V3()};g.position.set(P0.x+150,60,P0.z)}
    else{const bl=part(T,sp(T,1),TM(0xcfd3e0),0,0,0,g);bl.scale.set(7,7,22);part(T,bx(T,.3,6,5),TM(0xF2352A),0,5,-18,g);part(T,bx(T,2.4,1.6,5),TM(0x5A5470),0,-7.6,2,g);const h=Math.random()*6.283;const dir=V3(Math.sin(h),0,Math.cos(h));g.position.set(P0.x,112,P0.z).addScaledVector(dir,-300);a={v:dir.multiplyScalar(10)}}
    K.ink(g,.06);Object.assign(a,{type,g,p:g.position});if(a.v.lengthSq())g.rotation.y=Math.atan2(a.v.x,a.v.z);if(!falling)air.push(a);return a}
  function tickAir(dt,P0){if(air.filter(a=>a.type==='plane').length<2)makeAir('plane');if(!air.some(a=>a.type==='heli'))makeAir('heli');if(!air.some(a=>a.type==='blimp')&&Math.random()<dt*.05)makeAir('blimp');
    for(let i=air.length-1;i>=0;i--){const a=air[i];if(a.type==='heli'){a.ang+=dt*.18;const goal=V3(P0.x+Math.cos(a.ang)*70,Math.max(40,P0.y+22),P0.z+Math.sin(a.ang)*70);const dv=goal.sub(a.p);const L=dv.length();a.v.lerp(dv.multiplyScalar(L>1?Math.min(90,L*.8)/L:0),Math.min(1,dt*1.5));a.p.addScaledVector(a.v,dt);a.g.rotation.y=Math.atan2(P0.x-a.p.x,P0.z-a.p.z);a.rot.rotation.y+=dt*25}
      else{a.p.addScaledVector(a.v,dt);const dx=a.p.x-P0.x,dz=a.p.z-P0.z;if(dx*dx+dz*dz>480*480&&dx*a.v.x+dz*a.v.z>0){drop(a.g);air.splice(i,1)}}}}
  // ---- fire visuals ----
  const flameG=new T.ConeGeometry(1,2.6,6);flameG.translate(0,1.3,0);const flameM=[0xFFE27A,0xFF8A1F,0xE8321E].map(c0=>new T.MeshBasicMaterial({color:c0,transparent:true,opacity:.9,depthWrite:false}));
  const facePt=b=>{const s=Math.random()*4|0,y=b.h*(.3+Math.random()*.65);return s===0?V3(b.x0,y,b.z0+Math.random()*(b.z1-b.z0)):s===1?V3(b.x1,y,b.z0+Math.random()*(b.z1-b.z0)):s===2?V3(b.x0+Math.random()*(b.x1-b.x0),y,b.z0):V3(b.x0+Math.random()*(b.x1-b.x0),y,b.z1)};
  // ---- jobs ----
  const JOBS=o.fly?['fire','rescue','chase','fire','rescue','plane','cat']:['fire','rescue','chase','fire','chase','cat'];
  function mkPin(c0,txt){const g=add(new T.Group());const b=beam(c0,90);b.position.y=45;g.add(b);const s=part(T,sp(T,1.2),new T.MeshBasicMaterial({color:c0}),0,0,0,g);s.userData.noInk=1;g.userData.s=s;return g}
  function newJob(){const kind=pick(JOBS);const P0=hp();
    if(kind==='fire'){const bs=city.boxes.filter(b=>!b.tree&&!b.dead&&b.h>10&&!b.onFire&&hd({x:b.cx,z:b.cz},P0)>50&&hd({x:b.cx,z:b.cz},P0)<260&&(city.half==null||Math.abs(b.cx)<lim));if(!bs.length)return;const b=pick(bs);b.onFire=1;city.pin&&city.pin(b);const fl=[];for(let k=0;k<7;k++){const m=add(new T.Mesh(flameG,flameM[k%3]));m.position.copy(k<2?V3(b.x0+Math.random()*(b.x1-b.x0),b.h+.3,b.z0+Math.random()*(b.z1-b.z0)):facePt(b));const s=Math.min(4.5,1.6+Math.max(b.w||8,b.d||8)*.09);m.scale.setScalar(s);m.userData.s=s;fl.push(m)}
      jobs.push({kind,ic:'🔥',name:'Put out the fire',b,fl,prog:0,life:90,at:()=>V3(b.cx,b.h+4,b.cz)});H.say('🔥 A building is on fire! Get close to put it out.',2200)}
    else if(kind==='rescue'){let at;if(o.fly){const bs=city.boxes.filter(b=>!b.tree&&!b.dead&&b.h>25&&hd({x:b.cx,z:b.cz},P0)>60&&hd({x:b.cx,z:b.cz},P0)<260);if(!bs.length)return;const b=pick(bs);city.pin&&city.pin(b);at=V3(b.cx+(Math.random()-.5)*(b.x1-b.x0-4),b.h,b.cz+(Math.random()-.5)*(b.z1-b.z0-4));var bld=b}else{const p=streetPt(60,220);if(!p)return;at=V3(p.x,0,p.z);const car=add(toonCar(K,0x8c86a3));car.position.set(p.x+3,1.6,p.z);car.rotation.set(0,Math.random()*6,Math.PI);var wreck=car}
      const g=add(personMesh());g.position.copy(at);const help=add(new T.Mesh(new T.ConeGeometry(.5,1.2,4),new T.MeshBasicMaterial({color:0xF2352A})));help.rotation.x=Math.PI;
      jobs.push({kind,ic:'🆘',name:o.fly?'Rooftop rescue':'Car crash rescue',g,help,wreck,bld,life:120,stage:0,at:()=>g.position.clone().add(V3(0,3,0))});H.say(o.fly?'🆘 Someone is stuck on a rooftop!':'🆘 Someone is trapped after a crash!',2200)}
    else if(kind==='chase'){const p=streetPt(80,200);if(!p)return;const car=add(toonCar(K,0x1D1A2F,true));const ax=onX(p.x)?'z':'x';if(ax==='z')p.x=sl(p.x)+3;else p.z=sl(p.z)+3;car.position.set(p.x,0,p.z);const j={kind,ic:'🚓',name:'Stop the getaway van',car,ax,dir:Math.random()<.5?-1:1,sp:o.chase||30,life:100,stopped:0,at:()=>car.position.clone().add(V3(0,3,0))};jobs.push(j);H.say('🚓 Robbers in a black van! Catch them!',2200)}
    else if(kind==='cat'){const ts=city.boxes.filter(b=>b.tree&&hd({x:(b.x0+b.x1)/2,z:(b.z0+b.z1)/2},P0)>30&&hd({x:(b.x0+b.x1)/2,z:(b.z0+b.z1)/2},P0)<240);if(!ts.length)return;const t=pick(ts);const g=add(new T.Group());const om=TM(0xFF9F43);part(T,bx(T,.7,.5,1),om,0,0,0,g);part(T,bx(T,.5,.5,.5),om,0,.35,.55,g);[-1,1].forEach(s=>part(T,new T.ConeGeometry(.12,.3,4),om,s*.15,.72,.55,g));part(T,bx(T,.12,.12,.8),om,0,.25,-.7,g).rotation.x=.8;K.ink(g,.04);g.position.set((t.x0+t.x1)/2,5.4,(t.z0+t.z1)/2);g.scale.setScalar(1.4);
      jobs.push({kind,ic:'🐱',name:'Cat stuck in a tree',g,life:120,at:()=>g.position.clone().add(V3(0,2,0))});H.say('🐱 A cat is stuck in a tree!',2000)}
    else if(kind==='plane'){const a=makeAir('plane',true);jobs.push({kind,ic:'✈️',name:'Save the falling plane',a,life:80,at:()=>a.p.clone()});H.say('✈️ A plane’s engine is on fire! Fly into it to steady it.',2400)}}
  function endJob(j,ok){const i=jobs.indexOf(j);if(i>=0)jobs.splice(i,1);['g','help','car','wreck'].forEach(k=>{if(j[k])setTimeout(()=>drop(j[k]),ok&&k==='car'?2500:0)});if(j.fl)j.fl.forEach(drop);if(j.b){j.b.onFire=0;city.unpin&&city.unpin(j.b)}if(j.bld)city.unpin&&city.unpin(j.bld);if(j.amb)drop(j.amb);if(j.a)setTimeout(()=>drop(j.a.g),ok?9000:0)}
  function tickJobs(dt,P0,carry){for(const j of jobs.slice()){j.life-=dt;
      if(j.kind==='fire'){const b=j.b;j.fl.forEach(m=>{const s=m.userData.s;m.scale.set(s*(.85+Math.random()*.3),s*(.75+Math.random()*.6),s*(.85+Math.random()*.3))});if(Math.random()<dt*3)K.puff(V3(b.cx+(Math.random()-.5)*6,b.h+2,b.cz+(Math.random()-.5)*6),0x3a3552,3,2.2,V3(0,5,0));
        const cx=clamp(P0.x,b.x0,b.x1),cz=clamp(P0.z,b.z0,b.z1);const d=Math.hypot(P0.x-cx,P0.z-cz);if(d<12&&P0.y<b.h+25){j.prog+=dt/3;if(Math.random()<dt*10)K.puff(facePt(b),0xffffff,2.5,1.2,V3(0,3,0));j.fl.forEach((m,k)=>m.visible=k/j.fl.length>j.prog)}else j.prog=Math.max(0,j.prog-dt*.1);
        if(j.prog>=1){award(40,'Fire out!',j.at());endJob(j,true)}else if(j.life<=0){H.say('The fire crew handled that one.',1600);endJob(j,false)}}
      else if(j.kind==='rescue'){j.help.position.copy(j.g.position).add(V3(0,3.6+Math.sin(time*4)*.3,0));j.help.visible=j.stage===0;
        if(j.stage===0){const u=j.g.userData;u.aL.rotation.x=-2.8+Math.sin(time*12)*.5;u.aR.rotation.x=-2.8+Math.cos(time*12)*.5;if(j.g.position.distanceTo(P0)<(o.fly?5:4.5)){j.stage=1;const p=streetPt(60,150)||{x:P0.x+40,z:P0.z};j.amb=add(new T.Group());const bm=beam(0x2BB673,40);bm.position.y=20;j.amb.add(bm);const van=toonCar(K,0xffffff,true);part(T,bx(T,2.4,.3,.6),TM(0xF2352A),0,3.3,1,van);j.amb.add(van);j.amb.position.set(p.x,0,p.z);if(j.wreck)K.burst(j.wreck.position.clone(),[0x8c86a3,0xFFD23F],16,10,.8);H.say('Got them! Take them to the ambulance.',1800);beep(700,.1,'triangle',.06)}}
        else{j.g.position.set(P0.x,P0.y+(o.fly?-1.6:1.4),P0.z);j.g.rotation.set(o.fly?0:-Math.PI/2,time*.5,0);if(hd(P0,j.amb.position)<8&&P0.y<12){j.g.position.set(j.amb.position.x+2.5,0,j.amb.position.z);j.g.rotation.set(0,0,0);award(50,'Rescued!',j.amb.position.clone().add(V3(0,4,0)));endJob(j,true)}}
        if(j.life<=0&&j.stage===0){H.say('Firefighters reached them. Phew!',1600);endJob(j,false)}}
      else if(j.kind==='chase'){const car=j.car;if(!j.stopped){const s=j.sp,along=j.ax,other=along==='z'?'x':'z';const prev=car.position[along];car.position[along]+=j.dir*s*dt;const cur=car.position[along],node=sl(cur);j.tc=(j.tc||0)-dt;if((prev-node)*(cur-node)<=0&&j.tc<=0&&Math.random()<.55){car.position[along]=node;j.ax=other;j.dir=Math.random()<.5?-1:1;j.tc=.6}if(Math.abs(car.position.x)>lim-4||Math.abs(car.position.z)>lim-4){j.dir*=-1;car.position[j.ax]+=j.dir*2}if(j.ax==='z')car.position.x=sl(car.position.x)+3*j.dir;else car.position.z=sl(car.position.z)-3*j.dir;car.rotation.y=j.ax==='z'?(j.dir>0?0:Math.PI):(j.dir>0?Math.PI/2:-Math.PI/2);if(Math.random()<dt*6)K.puff(car.position.clone().setY(.6),0x8c86a3,.8,.6);
          if(car.position.distanceTo(P0)<(o.fly?6:5.5)&&P0.y<8){j.stopped=1;car.rotation.y+=.8;K.burst(car.position.clone().setY(1.5),[0xFFD23F,0xffffff],20,10,.8);H.pow('BUSTED!',car.position.clone().add(V3(0,5,0)),'#7FC8F8');award(60,'Robbers caught!',car.position.clone().add(V3(0,3,0)));endJob(j,true)}
          else if(j.life<=0||car.position.distanceTo(P0)>380){H.say('The van got away… this time.',1600);endJob(j,false)}}}
      else if(j.kind==='cat'){j.g.rotation.y+=dt;if(hd(j.g.position,P0)<4&&P0.y<12){H.pow('MEOW!',j.g.position.clone().add(V3(0,2,0)),'#FF9F43');award(25,'Kitty saved!',j.g.position.clone());endJob(j,true)}else if(j.life<=0){H.say('The cat climbed down by itself. Cats.',1600);endJob(j,false)}}
      else if(j.kind==='plane'){const a=j.a;if(!j.saved){a.v.y=Math.max(a.v.y-3*dt,-9);a.g.rotation.x=Math.min(.4,a.g.rotation.x+dt*.05);a.g.rotation.z=Math.sin(time*2)*.25;a.p.addScaledVector(a.v,dt);if(Math.random()<dt*14)K.puff(a.p.clone().add(V3(5,0,0)),0x3a3552,2.5,1.8);if(Math.random()<dt*8)K.burst(a.p.clone().add(V3(5.5,-1,1)),[0xFF9F43,0xFFD23F],3,5,.6);
          if(a.p.distanceTo(P0)<14){j.saved=1;a.v.y=6;a.g.rotation.set(0,a.g.rotation.y,0);award(80,'Crash averted!',a.p.clone().add(V3(0,6,0)));j.life=1e9;j.fly=8}else if(a.p.y<3||j.life<=0){a.v.set(0,0,0);K.puff(a.p.clone(),0xd8d4e4,6,2);H.say('A bumpy emergency landing, but everyone is OK!',1800);endJob(j,false)}}
        else{a.p.addScaledVector(a.v,dt);a.v.y=Math.max(0,a.v.y-dt*2);j.fly-=dt;if(j.fly<=0)endJob(j,true)}}}}
  // ---- coins ----
  const coinG=cy(T,1.1,1.1,.25,16),coinM=TM(0xFFD23F);
  function spawnCoins(){coins.forEach(q=>drop(q));coins=[];for(let k=0;k<25;k++){const p=streetPt(30,520);if(!p)continue;let y=1.6;if(o.fly&&Math.random()<.5){const b=K.inBox(p.x,0,p.z,city.boxes,8);y=5+Math.random()*60}const m=add(new T.Mesh(coinG,coinM));m.rotation.x=Math.PI/2;K.ink(m,.06);m.position.set(p.x,y,p.z);coins.push(m)}}
  function tickCoins(dt,P0){for(const m of coins.slice()){m.rotation.z+=dt*3;if(m.position.distanceTo(P0)<(o.fly?4.5:3.8)){coins.splice(coins.indexOf(m),1);drop(m);coinTot++;S.set(KEY+'_coins',coinTot);pts+=5;S.set(KEY+'_pts',pts);beep(1320,.08,'square',.05);setTimeout(()=>beep(1760,.1,'square',.05),70);K.burst(m.position.clone(),[0xFFD23F,0xffffff],10,8,.5);if(!coins.length){H.say('All coins found! A new batch appeared.',2000);spawnCoins()}}}}
  // ---- races ----
  const ringG=new T.TorusGeometry(5,.45,8,28);
  function newGate(){const p=streetPt(40,120);if(!p)return;gate=add(new T.Group());const b=beam(0xffffff,60);b.position.y=30;gate.add(b);const f=new T.Mesh(bx(T,6,4,.3),new T.MeshBasicMaterial({color:0x1D1A2F}));f.position.y=6;gate.add(f);const f2=new T.Mesh(bx(T,3,2,.32),new T.MeshBasicMaterial({color:0xffffff}));f2.position.set(-1.5,7,0);gate.add(f2);const f3=f2.clone();f3.position.set(1.5,5,0);gate.add(f3);gate.position.set(p.x,0,p.z)}
  function startRace(){const pts2=[];let x=gate.position.x,z=gate.position.z;for(let k=0;k<8;k++){let best=null;for(let t=0;t<30;t++){const a=Math.random()*6.283,r=45+Math.random()*40;let nx=x+Math.cos(a)*r,nz=z+Math.sin(a)*r;if(Math.random()<.5)nx=sl(nx);else nz=sl(nz);if(Math.abs(nx)>lim-6||Math.abs(nz)>lim-6||inB(nx,2,nz,3))continue;best={x:nx,z:nz};break}if(!best)best={x:x+30,z};x=best.x;z=best.z;pts2.push(V3(x,o.fly?8+Math.random()*50:3.5,z))}
    const rings=pts2.map((p,k)=>{const m=add(new T.Mesh(ringG,new T.MeshBasicMaterial({color:k?0x6EE7B7:0xFFD23F})));m.position.copy(p);const nx=pts2[k+1]||p;m.lookAt(k<7?nx:pts2[k-1]);m.visible=k<2;return m});race={rings,i:0,t:0};drop(gate);gate=null;H.say('GO! Fly through the rings!'.replace('Fly',o.fly?'Fly':'Run'),1400);beep(880,.3,'square',.07)}
  function tickRace(dt,P0){if(gate){gate.rotation.y+=dt;if(hd(gate.position,P0)<6&&P0.y<12)startRace();return}if(!race){gateT-=dt;if(gateT<=0)newGate();return}race.t+=dt;const r=race.rings[race.i];r.rotation.z+=dt;
    if(r.position.distanceTo(P0)<6.5){beep(700+race.i*60,.1,'triangle',.07);K.burst(r.position.clone(),[0x6EE7B7,0xffffff],14,10,.6);drop(r);race.i++;if(race.rings[race.i+1])race.rings[race.i+1].visible=true;if(race.rings[race.i])race.rings[race.i].material.color.setHex(0xFFD23F);
      if(race.i>=race.rings.length){const t=race.t,best=!raceBest||t<raceBest;if(best){raceBest=t;S.set(KEY+'_race',t)}award(best?60:35,best?'NEW RECORD '+t.toFixed(1)+'s':'Race '+t.toFixed(1)+'s');race=null;gateT=15}}else if(race.t>120){race.rings.forEach(drop);race=null;gateT=10;H.say('Race timed out.',1200)}}
  // ---- public ----
  function reset(active){objs.slice().forEach(drop);objs=[];jobs.forEach(j=>{if(j.b){j.b.onFire=0;city.unpin&&city.unpin(j.b)}if(j.bld)city.unpin&&city.unpin(j.bld)});jobs=[];coins=[];air.length=0;race=null;gate=null;people.length=0;on=!!active;panel.style.display=on?'':'none';ptr(null);if(!on)return;
    for(let k=0;k<(o.people||40);k++){const g=add(personMesh());const q={g};people.push(q);placeP(q)}spawnCoins();jobT=1.5;gateT=3}
  function tick(dt,spd){if(!on)return;time+=dt;const P0=hp();tickPeople(dt,P0,spd||0);tickAir(dt,P0);jobT-=dt;if(jobT<=0){const n=jobs.length;if(n<3)newJob();jobT=jobs.length>n?9+Math.random()*7:1}tickJobs(dt,P0);tickCoins(dt,P0);tickRace(dt,P0);
    let tg=null,tl='';if(race){const r=race.rings[race.i];if(r){tg=r.position;tl='RING '+(race.i+1)+'/8'}}else{const carry=jobs.find(j=>j.kind==='rescue'&&j.stage===1);if(carry){tg=carry.amb.position.clone().add(V3(0,3,0));tl='AMBULANCE '+Math.round(hd(carry.amb.position,P0))+'m'}else{let bd=1e9;jobs.forEach(j=>{const a=j.at();const d=a.distanceTo(P0);if(d<bd){bd=d;tg=a;tl=j.ic+' '+Math.round(d)+'m'}})}}ptr(tg,tl);
    if(Math.floor(time*4)!==Math.floor((time-dt)*4))panel.innerHTML='⭐ <b>'+pts+'</b> hero points · <b>'+rank()+'</b><br>'+(jobs.length?jobs.map(j=>j.ic+' '+j.name+(j.kind==='fire'&&j.prog>0?' '+Math.round(j.prog*100)+'%':j.kind==='rescue'&&j.stage===1?' (to ambulance)':'')+' · '+Math.round(j.at().distanceTo(P0))+'m').join('<br>'):'<i>Patrolling… trouble will pop up soon</i>')+'<br>🪙 Coins '+(25-coins.length)+'/25 · all-time '+coinTot+'<br>🏁 '+(race?'Race: '+race.t.toFixed(1)+'s · ring '+(race.i+1)+'/8':gate?'Race gate nearby (white beam)':'Next race soon')+(raceBest?' · best '+raceBest.toFixed(1)+'s':'')}
  function dots(arr){if(!on)return;jobs.forEach(j=>{const a=j.at();arr.push({x:a.x,z:a.z,col:'#F2352A',r:7})});coins.forEach(m=>arr.push({x:m.position.x,z:m.position.z,col:'#FFD23F',r:3}));if(gate)arr.push({x:gate.position.x,z:gate.position.z,col:'#ffffff',r:6});if(race&&race.rings[race.i])arr.push({x:race.rings[race.i].position.x,z:race.rings[race.i].position.z,col:'#6EE7B7',r:6});air.forEach(a=>arr.push({x:a.p.x,z:a.p.z,col:'#ffffff',r:4}))}
  return{reset,tick,dots,get on(){return on},get jobs(){return jobs},get pts(){return pts},people}}
