/* ================= simple driving games ================= */
function holdPad(root,defs){const keys={};const row=el('div',{class:'row',style:'justify-content:center;gap:10px;margin-top:8px;touch-action:none;user-select:none'});defs.forEach(([k,label])=>{const b=el('button',{class:'btn',type:'button',style:'min-width:64px;font-size:20px'},label);const on=e=>{e.preventDefault();keys[k]=1},off=()=>{keys[k]=0};b.addEventListener('pointerdown',on);['pointerup','pointerleave','pointercancel'].forEach(ev=>b.addEventListener(ev,off));row.append(b)});root.append(row);return keys}
/* ---------- Highway Weave (3D) ---------- */
G.push({id:'hwweave',name:'Highway Weave',kind:'game',wide:true,tint:'#7FC8F8',blurb:'Weave through highway traffic at full speed. Near misses score big.',fmt:b=>b+' m',
art:'<rect width="120" height="72" fill="#6EC56E"/><path d="M40 0h40l30 72H10z" fill="#5A5470"/><path d="M60 4v10M60 22v10M60 40v10M60 58v10" stroke="#fff" stroke-width="2"/><rect x="44" y="18" width="10" height="16" rx="2" fill="#FFD23F" stroke="#1D1A2F" stroke-width="2"/><rect x="64" y="40" width="12" height="20" rx="2" fill="#F2352A" stroke="#1D1A2F" stroke-width="2"/>',
run(root,c){return with3D(root,c,()=>{
  const st3=Stage3D(root,c,{lock:false,fov:60,far:400,fireLabel:'▶',altLabel:'◀',jumpLabel:'NITRO'});const{T,scene,camera,input,wrap,hud}=st3;
  scene.background=new T.Color(0xbfe2ff);scene.fog=new T.Fog(0xbfe2ff,80,300);scene.add(new T.HemisphereLight(0xffffff,0x6a7a5a,.9));const dl=new T.DirectionalLight(0xffffff,.6);dl.position.set(10,30,10);scene.add(dl);
  const LANES=[-5.4,-1.8,1.8,5.4],LM=c2=>new T.MeshLambertMaterial({color:c2});
  const rtx=tex(T,128,256,(x,w,h)=>{x.fillStyle='#4a4a58';x.fillRect(0,0,w,h);x.fillStyle='#fff';[.25,.5,.75].forEach(u=>{x.fillRect(u*w-2,0,4,h*.45)});x.fillStyle='#FFD23F';x.fillRect(3,0,4,h);x.fillRect(w-7,0,4,h)},1,1);rtx.wrapT=T.RepeatWrapping;rtx.repeat.set(1,30);
  const road=new T.Mesh(new T.PlaneGeometry(15,600),new T.MeshLambertMaterial({map:rtx}));road.rotation.x=-Math.PI/2;road.position.z=250;scene.add(road);const gr=new T.Mesh(new T.PlaneGeometry(400,600),LM(0x6EC56E));gr.rotation.x=-Math.PI/2;gr.position.set(0,-.05,250);scene.add(gr);
  function car(col,big){const g=new T.Group();const b=new T.Mesh(new T.BoxGeometry(2,big?2:1,big?7:4),LM(col));b.position.y=big?1.4:.8;g.add(b);if(!big){const cb=new T.Mesh(new T.BoxGeometry(1.7,.7,2),LM(0x9fd6ff));cb.position.set(0,1.6,-.2);g.add(cb)}else{const cb=new T.Mesh(new T.BoxGeometry(2,1.4,1.6),LM(0xe8e1d0));cb.position.set(0,1.1,3.2);g.add(cb)}[[-1,1],[1,1],[-1,-1],[1,-1]].forEach(([a,b2])=>{const w=new T.Mesh(new T.BoxGeometry(.4,.8,.8),LM(0x1D1A2F));w.position.set(a*1.05,.4,b2*(big?2.4:1.3));g.add(w)});const tl=new T.MeshBasicMaterial({color:0xff2020});[-.6,.6].forEach(x=>{const t=new T.Mesh(new T.BoxGeometry(.4,.2,.05),tl);t.position.set(x,big?1:.9,-(big?3.5:2)-.02);g.add(t)});scene.add(g);return g}
  const me=car(0xFF9F43);let nitro=0,lastNear=0,lane=1,lx=0,spd=0,dist=0,state='menu',traffic=[],spawnZ=0,near=0,combo=0,score=0,best=c.best()||0,t=0,shakeT=0;
  const props=[];for(let i=0;i<40;i++){const side=i%2?1:-1;const g=new T.Group();if(i%4<2){const tr=new T.Mesh(new T.BoxGeometry(.5,2,.5),LM(0x7a4a2a));tr.position.y=1;g.add(tr);const l=new T.Mesh(new T.BoxGeometry(2.6,2.6,2.6),LM(pick([0x2BB673,0x3fae5a])));l.position.y=3.2;g.add(l);g.position.x=side*(12+Math.random()*20)}else{const p=new T.Mesh(new T.BoxGeometry(.25,6,.25),LM(0x8c86a3));p.position.y=3;g.add(p);const a=new T.Mesh(new T.BoxGeometry(2,.2,.3),LM(0x8c86a3));a.position.set(-side,6,0);g.add(a);g.position.x=side*8.6}g.position.z=i*10;scene.add(g);props.push(g)}
  const Hd=el('div',{style:'position:absolute;left:14px;top:10px;color:#fff;font:800 18px "JetBrains Mono",monospace;text-shadow:0 2px 0 #1D1A2F;pointer-events:none'}),Big=el('div',{style:'position:absolute;left:0;right:0;top:30%;text-align:center;color:#FFD23F;font:34px "Bagel Fat One",sans-serif;text-shadow:0 3px 0 #1D1A2F;opacity:0;transition:opacity .25s;pointer-events:none'});hud.append(Hd,Big);let bigT=0;const say=(s2,d)=>{Big.textContent=s2;Big.style.opacity=1;bigT=d||.8};
  function start(){traffic.forEach(q=>scene.remove(q.m));traffic=[];lane=1;lastNear=0;nitro=.3;lx=0;spd=18;dist=0;spawnZ=40;score=0;combo=0;near=0;t=0;state='play';me.visible=true}
  let ll=false,rl=false,hbWas=false;
  st3.onFrame(dt=>{const I=input,K=I.keys;if(state==='play'){t+=dt;const L=K.a||K.arrowleft||I.alt,R=K.d||K.arrowright||I.fire;if(L&&!ll)lane=Math.min(3,Math.round(lane)+1);if(R&&!rl)lane=Math.max(0,Math.round(lane)-1);ll=L;rl=R;if(I.joy.x)lane=clamp(lane-I.joy.x*dt*4,0,3);
      const boost=K.w||K.arrowup;const nit=(K.shift||K.n||I.jumpBtn)&&nitro>.02;if(nit){nitro=Math.max(0,nitro-dt*.35)}const hb=!!K[' '];if(hb&&!hbWas&&spd>20)noise(.35,'bandpass',1800,.07);hbWas=hb;const target=clamp(26+t*.35,26,62)*(boost?1.25:1)*(nit&&!hb?1.5:1)*(K.s||K.arrowdown?.7:1)*(hb?.35:1);spd+=(target-spd)*Math.min(1,dt*(hb?4:1.5));dist+=spd*dt;const want=LANES[Math.round(clamp(lane,0,3))];lx+=(want-lx)*Math.min(1,dt*(hb?11:7));
      spawnZ-=spd*dt*0;if(traffic.length<Math.min(14,5+t/10)&&Math.random()<dt*(1.2+t/40)){const ln=rand(4);const zz=90+Math.random()*60;if(!traffic.some(q=>q.ln===ln&&Math.abs(q.z-zz)<14)){const big=Math.random()<.2;traffic.push({m:car(pick([0xffffff,0x2d6fd6,0xF2352A,0x6EE7B7,0xB9A7FF,0x1D1A2F]),big),ln,z:zz,v:14+Math.random()*10-(big?4:0),big,passed:false})}}
      traffic.forEach(q=>{q.z-=(spd-q.v)*dt;const ahead=traffic.find(o=>o!==q&&o.ln===q.ln&&o.z>q.z&&o.z-q.z<9);if(ahead)q.v=Math.min(q.v,ahead.v);q.m.position.set(LANES[q.ln],0,q.z);const dx=Math.abs(LANES[q.ln]-lx),dz=Math.abs(q.z);const len=q.big?4.6:3.2;if(dx<1.9&&dz<len){state='over';shakeT=.5;noise(.8,'lowpass',300,.45);const b=c.best(Math.floor(dist+score));c.after(()=>st3.overlay('<h2>'+Math.floor(dist+score)+' m</h2><p>Crash! '+Math.floor(dist)+' m driven + '+score+' near-miss bonus. Best: '+b+'.</p>',[['Drive again',start,true]]),700)}
        if(!q.passed&&q.z<-len&&dx<3.9){q.passed=true;combo++;lastNear=t;nitro=Math.min(1,nitro+.15);const pts=Math.round(spd*combo*.5);score+=pts;say('NEAR MISS ×'+combo+' +'+pts,.7);beep(700+combo*80,.08,'triangle',.05)}else if(!q.passed&&q.z<-len){q.passed=true}});
      traffic=traffic.filter(q=>{if(q.z<-30){scene.remove(q.m);return false}return true});if(t-lastNear>3)combo=0;
      rtx.offset.y+=spd*dt/20;props.forEach(p=>{p.position.z-=spd*dt;if(p.position.z<-20)p.position.z+=400});}
    me.position.set(lx,0,0);me.rotation.y=(LANES[Math.round(clamp(lane,0,3))]-lx)*(hbWas?.16:.06);shakeT=Math.max(0,shakeT-dt);camera.position.set(lx*.6+(Math.random()-.5)*shakeT,5.2,-10);camera.lookAt(lx*.4,1,14);
    Hd.innerHTML=Math.floor(dist+score)+' m<br><span style="font-size:13px">'+Math.round(spd*3.6)+' km/h · W boost · Shift nitro · Space handbrake</span><div style="width:160px;height:9px;border:2px solid #1D1A2F;border-radius:6px;background:#3a3552;margin-top:4px;overflow:hidden"><i style="display:block;height:100%;width:'+(nitro*100)+'%;background:#FF9F43"></i></div>';if(bigT>0){bigT-=dt;if(bigT<=0)Big.style.opacity=0}c.stat('Highway Weave · '+Math.floor(dist+score)+' m')});
  st3.overlay('<small class="kick">3D arcade · traffic</small><h2>Highway Weave</h2><p>Change lanes to dodge traffic. It gets faster the longer you last, and passing close to a car scores a near-miss bonus that grows with your combo.</p><p class="ctl"><b>Controls:</b> A/D or ←/→ change lanes, hold W to boost, S to ease off, Space for the handbrake (hard stop, sharper slide between lanes). Near misses fill your nitro bar: hold Shift (or NITRO on a phone) to fire it. On a phone: the ◀ ▶ buttons.</p>',[['Hit the road',start,true]]);
  camera.position.set(0,5.2,-10);camera.lookAt(0,1,14);return()=>st3.dispose()})}});
/* ---------- Parking Pro (2D) ---------- */
G.push({id:'parkpro',name:'Parking Pro',kind:'puzzle',levels:true,tint:'#FFD23F',blurb:'Top-down precision parking. Bay, reverse and parallel parking without a scratch.',fmt:b=>'level '+b,
art:'<rect width="120" height="72" fill="#5A5470"/><path d="M20 10v24M40 10v24M60 10v24M80 10v24M100 10v24" stroke="#fff" stroke-width="2"/><rect x="24" y="12" width="12" height="20" rx="2" fill="#2d6fd6"/><rect x="84" y="12" width="12" height="20" rx="2" fill="#6EE7B7"/><rect x="42" y="11" width="16" height="22" fill="none" stroke="#FFD23F" stroke-width="2.5" stroke-dasharray="4 3"/><rect x="45" y="44" width="12" height="20" rx="2" fill="#F2352A" transform="rotate(-20 51 54)"/>',
run(root,c){
  const W=820,H=560;const[cv,x]=mk(W,H,'width:min(100%,820px)');root.append(cv);const keys=holdPad(root,[['l','◀'],['f','▲'],['b','▼'],['r','▶'],['h','HB']]);root.append(el('p',{class:'hint'},'W/S (or ↑/↓) to drive forward and reverse, A/D to steer, Space (or HB) for the handbrake. Stop fully inside the yellow box, lined up, and hold still for a second. Don’t touch anything!'));
  let lvl=Math.max(1,S.get('park_lv',1)),car,obs,spot,state='play',holdT=0,msg='',hits=0,tt=0;const CL=46,CW=22;
  const R=(cx,cy,w,h,a,col)=>({cx,cy,w,h,a:a||0,col});
  function corners(r){const c2=Math.cos(r.a),s=Math.sin(r.a);return[[-1,-1],[1,-1],[1,1],[-1,1]].map(([u,v])=>({x:r.cx+c2*u*r.h/2-s*v*r.w/2,y:r.cy+s*u*r.h/2+c2*v*r.w/2}))}
  function sat(A,B){const pa=corners(A),pb=corners(B);for(const P of[pa,pb])for(let i=0;i<4;i++){const p1=P[i],p2=P[(i+1)%4];const nx=p2.y-p1.y,ny=p1.x-p2.x;let a0=1e9,a1=-1e9,b0=1e9,b1=-1e9;pa.forEach(q=>{const d=q.x*nx+q.y*ny;a0=Math.min(a0,d);a1=Math.max(a1,d)});pb.forEach(q=>{const d=q.x*nx+q.y*ny;b0=Math.min(b0,d);b1=Math.max(b1,d)});if(a1<b0||b1<a0)return false}return true}
  function build(){obs=[];holdT=0;hits=0;tt=0;msg='';state='play';const d=Math.min(12,lvl);const slack=Math.max(6,22-d*1.4);const colors=['#2d6fd6','#6EE7B7','#B9A7FF','#FF8FB1','#e8e1d0','#1D1A2F','#FF9F43'];
    obs.push(R(W/2,6,12,W),R(W/2,H-6,12,W),R(6,H/2,H,12),R(W-6,H/2,H,12));
    const type=d<=3?'bay':d<=6?(d%2?'reverse':'bay'):d<=9?'parallel':pick(['parallel','reverse','bay']);
    if(type==='bay'||type==='reverse'){const n=9,sw=CW+slack+6,x0=(W-n*sw)/2;const target=2+rand(n-4);for(let i=0;i<n;i++){const cx=x0+sw*i+sw/2,cy=70;if(i===target){spot=R(cx,cy,CW+slack,CL+slack*.6,Math.PI/2);continue}if(Math.random()<.85||Math.abs(i-target)===1)obs.push(R(cx+(Math.random()-.5)*(slack*.3),cy+(Math.random()-.5)*6,CW,CL,Math.PI/2+(Math.random()-.5)*.06,pick(colors)))}
      if(d>4){for(let i=0;i<n;i++){if(Math.random()<.6)obs.push(R(x0+sw*i+sw/2,H-80,CW,CL,Math.PI/2,pick(colors)))}}if(d>7)obs.push(R(W/2+(Math.random()-.5)*200,H/2,60,26,0,'#8c86a3'));
      car={x:W/2+(Math.random()-.5)*200,y:H-170,a:type==='reverse'?Math.PI/2:-Math.PI/2,v:0,st:0};spot.need=type==='reverse'?Math.PI/2:-Math.PI/2}
    else{const cy=H-60,gap=CL+Math.max(14,40-d*2.2);let xx=60;const gi=2+rand(3);for(let i=0;i<9;i++){if(i===gi){spot=R(xx+gap/2,cy,CW+8,gap-4,0);xx+=gap;continue}const L=CL+(Math.random()*10-5);obs.push(R(xx+L/2,cy,CW,L,0,pick(colors)));xx+=L+8+Math.random()*6}obs.push(R(W/2,H-24,6,W,0,'#8c86a3'));car={x:spot.cx+120,y:cy-60,a:0,v:0,st:0};spot.need=null}
    obs.forEach(o=>{if(!o.col)o.col='#3a3552'})}
  function draw(){x.fillStyle='#5A5470';x.fillRect(0,0,W,H);x.strokeStyle='rgba(255,255,255,.55)';x.lineWidth=2;
    x.save();x.translate(spot.cx,spot.cy);x.rotate(spot.a);x.fillStyle=holdT>0?'rgba(110,231,183,.35)':'rgba(255,210,63,.15)';x.fillRect(-spot.h/2,-spot.w/2,spot.h,spot.w);x.setLineDash([8,6]);x.strokeStyle='#FFD23F';x.lineWidth=3;x.strokeRect(-spot.h/2,-spot.w/2,spot.h,spot.w);x.setLineDash([]);if(spot.need!=null){x.fillStyle='#FFD23F';x.font='700 12px Figtree, sans-serif';x.textAlign='center';x.fillText(spot.need===-Math.PI/2?'NOSE IN':'REVERSE IN',0,4)}x.restore();
    obs.forEach(o=>{x.save();x.translate(o.cx,o.cy);x.rotate(o.a);x.fillStyle=o.col;x.strokeStyle='#1D1A2F';x.lineWidth=2;if(o.col==='#3a3552'||o.col==='#8c86a3'){x.fillRect(-o.h/2,-o.w/2,o.h,o.w)}else{x.beginPath();x.roundRect?x.roundRect(-o.h/2,-o.w/2,o.h,o.w,5):x.rect(-o.h/2,-o.w/2,o.h,o.w);x.fill();x.stroke();x.fillStyle='rgba(159,214,255,.8)';x.fillRect(-2,-o.w/2+3,o.h*.3,o.w-6)}x.restore()});
    x.save();x.translate(car.x,car.y);x.rotate(car.a);x.fillStyle=hits?'#FF8FB1':'#F2352A';x.strokeStyle='#1D1A2F';x.lineWidth=2.5;x.beginPath();x.roundRect?x.roundRect(-CL/2,-CW/2,CL,CW,6):x.rect(-CL/2,-CW/2,CL,CW);x.fill();x.stroke();x.fillStyle='#9fd6ff';x.fillRect(2,-CW/2+3,CL*.28,CW-6);x.fillStyle='#FFF3C4';x.fillRect(CL/2-3,-CW/2+2,3,5);x.fillRect(CL/2-3,CW/2-7,3,5);[[CL*.32,-1],[CL*.32,1]].forEach(([wx,s])=>{x.save();x.translate(wx,s*CW/2);x.rotate(car.st);x.fillStyle='#1D1A2F';x.fillRect(-5,-2,10,4);x.restore()});x.restore();
    x.fillStyle='#fff';x.font='700 16px "JetBrains Mono", monospace';x.textAlign='left';x.fillText('LEVEL '+lvl+'   '+tt.toFixed(1)+'s',20,34);if(holdT>0){x.fillStyle='#6EE7B7';x.fillText('HOLD STILL… '+Math.ceil((1-holdT)*10)/10,20,56)}
    if(state!=='play')banner(x,W,H,msg,state==='won'?'Tap for level '+(lvl+1):'Tap to try again')}
  function tick(dt){if(state!=='play')return;tt+=dt;const k=(n)=>keys[n];const K=pressed;const f=K.w||K.arrowup||k('f'),b=K.s||K.arrowdown||k('b'),l=K.a||K.arrowleft||k('l'),r=K.d||K.arrowright||k('r');const hb=K[' ']||k('h');if(hb&&!car.hb&&Math.abs(car.v)>50)noise(.25,'bandpass',1800,.06);car.hb=hb;const vmax=f?120:b?-80:0;if(hb)car.v-=clamp(car.v,-520*dt,520*dt);else car.v+=clamp(vmax-car.v,-260*dt,200*dt)*(f||b?1:1.6);car.st+=((l?-1:r?1:0)*.6-car.st)*Math.min(1,dt*6);const nx=car.x+Math.cos(car.a)*car.v*dt,ny=car.y+Math.sin(car.a)*car.v*dt,na=car.a+car.v/(CL*.62)*Math.tan(car.st)*dt*(hb&&Math.abs(car.v)>30?1.8:1);
    const test=R(nx,ny,CW,CL,na);if(obs.some(o=>sat(test,o))){if(Math.abs(car.v)>12){hits++;noise(.25,'lowpass',500,.3);state='lost';msg='Crunch! You touched something.'}car.v=0;return}car.x=nx;car.y=ny;car.a=na;
    const cs=corners(R(car.x,car.y,CW,CL,car.a));const inside=cs.every(p=>{const dx=p.x-spot.cx,dy=p.y-spot.cy,c2=Math.cos(-spot.a),s=Math.sin(-spot.a);const lx=dx*c2-dy*s,ly=dx*s+dy*c2;return Math.abs(lx)<spot.h/2&&Math.abs(ly)<spot.w/2});let ang=Math.abs(((car.a-(spot.need!=null?spot.need:spot.a))%(Math.PI*2)+Math.PI*3)%(Math.PI*2)-Math.PI);if(spot.need==null)ang=Math.min(ang,Math.abs(Math.PI-ang));
    if(inside&&ang<.2&&Math.abs(car.v)<4){holdT+=dt;if(holdT>=1){state='won';const st=tt<c.pick(30,22,16)?3:tt<c.pick(50,36,26)?2:1;msg='Parked! '+'★'.repeat(st)+'☆'.repeat(3-st);S.set('park_lv',Math.max(S.get('park_lv',1),lvl+1));c.best(lvl);[523,659,784].forEach((q,i)=>c.after(()=>beep(q,.15,'triangle',.06),i*100))}}else holdT=0;c.stat('Parking Pro · Level '+lvl)}
  const pressed={};c.on(document,'keydown',e=>{pressed[e.key.toLowerCase()]=1;if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(e.key.toLowerCase()))e.preventDefault()});c.on(document,'keyup',e=>{pressed[e.key.toLowerCase()]=0});
  c.on(cv,'pointerdown',()=>{if(state==='won'){lvl++;build()}else if(state==='lost')build()});
  build();c.loop(dt=>{tick(Math.min(.04,dt/1000));draw()})}});
/* ---------- Hill Climb (2D physics) ---------- */
G.push({id:'hillclimb',name:'Hill Climb',kind:'smash',wide:true,tint:'#2BB673',blurb:'Bouncy physics car on endless hills. Balance the gas, flip for bonus coins, and don’t land on your head.',fmt:b=>b+' m',
art:'<rect width="120" height="72" fill="#9fd6ff"/><path d="M0 56q20-18 40-6t40-10t40 8v24H0z" fill="#2BB673"/><g transform="rotate(-12 60 40)"><rect x="44" y="30" width="32" height="10" rx="3" fill="#F2352A" stroke="#1D1A2F" stroke-width="2"/><circle cx="50" cy="44" r="6" fill="#1D1A2F"/><circle cx="72" cy="44" r="6" fill="#1D1A2F"/><circle cx="60" cy="25" r="5" fill="#f1c7a0" stroke="#1D1A2F" stroke-width="2"/></g><circle cx="98" cy="30" r="5" fill="#FFD23F" stroke="#1D1A2F" stroke-width="2"/>',
run(root,c){return withMatter(root,c,()=>{
  const Mt=window.Matter,{Engine,Bodies,Body,Composite,Constraint,Events}=Mt;const W=900,H=520;const[cv,x]=mk(W,H,'width:100%');root.append(cv);const keys=holdPad(root,[['b','◀ Brake'],['g','Gas ▶']]);root.append(el('p',{class:'hint'},'D/→ gas, A/← brake and reverse. In the air, gas tilts you back and brake tilts you forward. Grab fuel cans before you run dry, and don’t land on your head!'));
  let eng,car,wA,wB,head,terrain=[],items=[],camX=0,fuel=1,dist=0,coins=0,state='menu',flips=0,rotAcc=0,lastA=0,airT=0,msgT=0,msg='',bestX=0;const pressed={};
  const hAt=xx=>{return 380-60*Math.sin(xx*.004)-Math.min(160,xx*.02)*Math.sin(xx*.011+1)*.6-25*Math.sin(xx*.023)+Math.max(0,xx-3000)*.02*Math.sin(xx*.017)};
  let genX=-400;function gen(to){const seg=40;while(genX<to){const x1=genX,x2=genX+seg,y1=hAt(x1),y2=hAt(x2);const len=Math.hypot(seg,y2-y1),ang=Math.atan2(y2-y1,seg);const b=Bodies.rectangle((x1+x2)/2-Math.sin(ang)*40,(y1+y2)/2+Math.cos(ang)*40,len+2,80,{isStatic:true,angle:ang,friction:1,label:'ground'});Composite.add(eng.world,b);terrain.push({b,x1,x2,y1,y2});genX=x2;if(Math.random()<.09)items.push({x:x2,y:y2-40,kind:Math.random()<.25&&x2-(items.filter(i=>i.kind==='fuel').pop()||{x:0}).x>500?'fuel':'coin',got:false})}
    while(terrain.length&&terrain[0].x2<camX-600){Composite.remove(eng.world,terrain.shift().b)}}
  function start(){if(eng)Engine.clear(eng);eng=Engine.create();eng.gravity.y=1.1;terrain=[];items=[];genX=-400;camX=0;gen(1400);const y0=hAt(0)-60;const grp=Body.nextGroup(true);
    car=Bodies.rectangle(0,y0,110,26,{density:.004,collisionFilter:{group:grp},friction:.5,chamfer:{radius:8}});wA=Bodies.circle(-38,y0+26,20,{density:.006,friction:1.2,collisionFilter:{group:grp}});wB=Bodies.circle(40,y0+26,20,{density:.006,friction:1.2,collisionFilter:{group:grp}});head=Bodies.circle(-8,y0-30,11,{density:.001,collisionFilter:{group:grp},label:'head'});
    const sp=(bw,ox)=>[Constraint.create({bodyA:car,pointA:{x:ox,y:12},bodyB:bw,stiffness:.25,damping:.12,length:14}),Constraint.create({bodyA:car,pointA:{x:ox-26,y:0},bodyB:bw,stiffness:.25,damping:.12,length:Math.hypot(26,26)}),Constraint.create({bodyA:car,pointA:{x:ox+26,y:0},bodyB:bw,stiffness:.25,damping:.12,length:Math.hypot(26,26)})];
    const neck=[Constraint.create({bodyA:car,pointA:{x:-14,y:-12},bodyB:head,stiffness:.9,length:20}),Constraint.create({bodyA:car,pointA:{x:0,y:-12},bodyB:head,stiffness:.9,length:22})];
    Composite.add(eng.world,[car,wA,wB,head,...sp(wA,-38),...sp(wB,40),...neck]);fuel=1;dist=0;coins=0;flips=0;rotAcc=0;lastA=0;bestX=0;state='play';
    Events.on(eng,'collisionStart',e=>{for(const p of e.pairs){if(state!=='play')return;const L=[p.bodyA.label,p.bodyB.label];if(L.includes('head')&&L.includes('ground')){crash('Ouch! Landed on your head.')}}})}
  function crash(why){if(state!=='play')return;state='over';msg=why;noise(.5,'lowpass',300,.35);const m=Math.floor(bestX/10);const b=c.best(m);S.set('hc_coins',S.get('hc_coins',0)+coins);c.after(()=>{},10);msgT=0;overTxt=m+' m · '+coins+' coins · '+flips+' flips · best '+b+' m'}let overTxt='';
  const grounded=()=>{const g=w=>terrain.some(t=>w.position.x>t.x1-5&&w.position.x<t.x2+5&&w.position.y+22>hAt(w.position.x)-4);return g(wA)||g(wB)};
  function step(dt){if(state!=='play')return;const K=pressed;const gas=K.d||K.arrowright||keys.g,brk=K.a||K.arrowleft||keys.b;const on=grounded();
    if(fuel>0&&(gas||brk)){const tv=gas?.45:-.3;[wA,wB].forEach(w=>Body.setAngularVelocity(w,w.angularVelocity+(tv-w.angularVelocity)*.12));fuel-=dt*.028}if(!on){airT+=dt;if(gas)Body.setAngularVelocity(car,car.angularVelocity-.0035);if(brk)Body.setAngularVelocity(car,car.angularVelocity+.0035)}else airT=0;
    const da=car.angle-lastA;lastA=car.angle;rotAcc+=da;if(Math.abs(rotAcc)>Math.PI*2-.3){rotAcc=0;flips++;coins+=5;msg=pick(['FLIP! +5','BACKFLIP! +5','WHOA! +5']);msgT=1.2;beep(880,.12,'triangle',.06)}if(on)rotAcc=0;
    Engine.update(eng,dt*1000);gen(car.position.x+1400);bestX=Math.max(bestX,car.position.x);dist=car.position.x;
    items.forEach(it=>{if(!it.got&&Math.hypot(it.x-car.position.x,it.y-car.position.y)<50){it.got=true;if(it.kind==='fuel'){fuel=1;msg='FUEL!';msgT=1;beep(660,.15,'triangle',.06)}else{coins++;beep(1320,.05,'triangle',.05)}}});
    if(fuel<=0&&Math.abs(car.velocity.x)<.3&&on){crash('Out of fuel!')}camX+=(car.position.x-W*.35-camX)*.1;c.stat('Hill Climb · '+Math.floor(bestX/10)+' m')}
  function draw(){const g=x.createLinearGradient(0,0,0,H);g.addColorStop(0,'#7FC8F8');g.addColorStop(1,'#e6f4ff');x.fillStyle=g;x.fillRect(0,0,W,H);const cy=car?Math.min(0,car.position.y-H*.55):0;
    x.fillStyle='rgba(90,84,112,.25)';x.beginPath();x.moveTo(0,H);for(let i=0;i<=W;i+=20)x.lineTo(i,300+40*Math.sin((i+camX*.3)*.006)-cy*.3);x.lineTo(W,H);x.fill();
    x.save();x.translate(-camX,-cy);x.fillStyle='#2BB673';x.strokeStyle='#1D1A2F';x.lineWidth=3;x.beginPath();x.moveTo(camX-10,H+cy+400);for(let xx=Math.floor(camX/20)*20-20;xx<=camX+W+40;xx+=20)x.lineTo(xx,hAt(xx));x.lineTo(camX+W+40,H+cy+400);x.closePath();x.fill();x.beginPath();for(let xx=Math.floor(camX/20)*20-20;xx<=camX+W+40;xx+=20)xx===Math.floor(camX/20)*20-20?x.moveTo(xx,hAt(xx)):x.lineTo(xx,hAt(xx));x.stroke();x.fillStyle='#8a5a2b';for(let xx=Math.floor(camX/20)*20;xx<=camX+W;xx+=20){x.fillRect(xx,hAt(xx)+14,20,H+cy+400)}
    for(let m=Math.ceil(camX/1000)*1000;m<camX+W;m+=1000){x.fillStyle='#fff';x.fillRect(m-2,hAt(m)-60,4,60);x.font='700 14px "JetBrains Mono", monospace';x.fillStyle='#1D1A2F';x.textAlign='center';x.fillText(m/10+' m',m,hAt(m)-66)}
    items.forEach(it=>{if(it.got||it.x<camX-40||it.x>camX+W+40)return;if(it.kind==='coin'){x.fillStyle='#FFD23F';x.beginPath();x.arc(it.x,it.y,10,0,7);x.fill();x.stroke()}else{x.fillStyle='#F2352A';x.fillRect(it.x-12,it.y-16,24,30);x.strokeRect(it.x-12,it.y-16,24,30);x.fillStyle='#fff';x.font='800 10px Figtree';x.fillText('FUEL',it.x,it.y+2)}});
    if(car){[wA,wB].forEach(w=>{x.save();x.translate(w.position.x,w.position.y);x.rotate(w.angle);x.fillStyle='#1D1A2F';x.beginPath();x.arc(0,0,20,0,7);x.fill();x.fillStyle='#8c86a3';x.beginPath();x.arc(0,0,9,0,7);x.fill();x.fillStyle='#1D1A2F';x.fillRect(-2,-9,4,18);x.restore()});
      x.save();x.translate(car.position.x,car.position.y);x.rotate(car.angle);x.fillStyle='#F2352A';x.beginPath();x.roundRect?x.roundRect(-55,-13,110,26,8):x.rect(-55,-13,110,26);x.fill();x.stroke();x.fillStyle='#9fd6ff';x.fillRect(-26,-30,34,17);x.strokeRect(-26,-30,34,17);x.restore();
      x.save();x.translate(head.position.x,head.position.y);x.fillStyle='#f1c7a0';x.beginPath();x.arc(0,0,11,0,7);x.fill();x.stroke();x.fillStyle='#2d6fd6';x.beginPath();x.arc(0,-3,11,Math.PI,0);x.fill();x.fillStyle='#1D1A2F';x.beginPath();x.arc(4,1,1.8,0,7);x.fill();x.restore()}
    x.restore();x.fillStyle='rgba(29,26,47,.6)';x.fillRect(14,14,210,54);x.fillStyle='#fff';x.font='700 15px "JetBrains Mono", monospace';x.textAlign='left';x.fillText(Math.floor(bestX/10)+' m   🪙 '+coins,24,36);x.fillStyle='#3a3552';x.fillRect(24,46,190,12);x.fillStyle=fuel<.25?'#F2352A':'#FFD23F';x.fillRect(24,46,190*Math.max(0,fuel),12);x.fillStyle='#fff';x.font='700 10px Figtree';x.fillText('FUEL',28,56);
    if(msgT>0){x.textAlign='center';x.font='36px "Bagel Fat One", sans-serif';x.fillStyle='#FFD23F';x.strokeStyle='#1D1A2F';x.lineWidth=5;x.strokeText(msg,W/2,110);x.fillText(msg,W/2,110)}
    if(state==='menu')banner(x,W,H,'Hill Climb','Tap or press any key to start');if(state==='over')banner(x,W,H,msg,overTxt+' · tap to retry')}
  c.on(document,'keydown',e=>{pressed[e.key.toLowerCase()]=1;if(state!=='play'&&['d','arrowright',' ','enter'].includes(e.key.toLowerCase()))start();if(e.key.startsWith('Arrow'))e.preventDefault()});c.on(document,'keyup',e=>{pressed[e.key.toLowerCase()]=0});c.on(cv,'pointerdown',()=>{if(state!=='play')start()});
  c.loop(dt=>{const d=Math.min(.033,dt/1000);if(msgT>0)msgT-=d;step(d);draw()});return()=>{}})}});
