/* ================= SIMULATORS ================= */
/* ---------- Tractor Fields (3D farming simulator) ---------- */
G.push({id:'sim_tractor',name:'Tractor Fields',kind:'sim',wide:true,big:true,tint:'#6EC56E',blurb:'A 3D farming simulator. Plow, seed and harvest your fields with a tractor and combine, sell grain at the silo, and grow your farm with new fields and bigger machines.',fmt:b=>'$'+b,
art:'<rect width="120" height="72" fill="#8fd3ff"/><rect y="40" width="120" height="32" fill="#e8c24a"/><path d="M0 48h120M0 56h120M0 64h120" stroke="#c9a13a" stroke-width="2"/><rect x="40" y="26" width="30" height="16" rx="2" fill="#2e8b3a" stroke="#1D1A2F" stroke-width="2"/><rect x="56" y="14" width="14" height="14" fill="#bfe6ff" stroke="#1D1A2F" stroke-width="2"/><circle cx="64" cy="46" r="10" fill="#2b2b33" stroke="#1D1A2F" stroke-width="2"/><circle cx="64" cy="46" r="4" fill="#FFD23F"/><circle cx="42" cy="49" r="6" fill="#2b2b33" stroke="#1D1A2F" stroke-width="2"/><rect x="92" y="16" width="14" height="34" rx="6" fill="#d8d4e4" stroke="#1D1A2F" stroke-width="2"/>',
run(root,c){return with3D(root,c,()=>{
  const st3=Stage3D(root,c,{lock:false,dragLook:true,fov:60,far:700,fireLabel:'TOOL',altLabel:'CROP',jumpLabel:'SPEED'});const{T,scene,camera,input,hud}=st3;
  const LM=col=>new T.MeshLambertMaterial({color:col});
  scene.background=new T.Color(0x9fd8ff);scene.fog=new T.Fog(0x9fd8ff,160,520);scene.add(new T.HemisphereLight(0xffffff,0x7a8a4a,.85));const sun=new T.DirectionalLight(0xfff2d6,.75);sun.position.set(60,120,40);scene.add(sun);
  // ground
  const gtex=tex(T,256,256,(x,w,h)=>{x.fillStyle='#78b04a';x.fillRect(0,0,w,h);for(let i=0;i<2200;i++){x.fillStyle=Math.random()<.5?'rgba(40,90,20,.18)':'rgba(200,230,120,.16)';x.fillRect(Math.random()*w,Math.random()*h,2,3)}},40,40);
  const ground=new T.Mesh(new T.PlaneGeometry(1200,1200),new T.MeshLambertMaterial({map:gtex}));ground.rotation.x=-Math.PI/2;scene.add(ground);
  const dirtM=LM(0xb89a6a);[[0,0,8,236],[0,0,236,8]].forEach(([x,z,w,d])=>{const r=new T.Mesh(new T.PlaneGeometry(w,d),dirtM);r.rotation.x=-Math.PI/2;r.position.set(x,.02,z);scene.add(r)});
  const yard=new T.Mesh(new T.PlaneGeometry(52,40),LM(0xa89272));yard.rotation.x=-Math.PI/2;yard.position.set(0,.03,-2);scene.add(yard);
  // crops & fields
  const CROPS=[{n:'Wheat',seed:2,price:6,t:80,h:1.1,y:1,g0:0x6fbf4a,g1:0xe8c24a},{n:'Corn',seed:3,price:8,t:130,h:2.6,y:1.2,g0:0x4f9f3a,g1:0xd9b64a},{n:'Canola',seed:4,price:11,t:105,h:1.4,y:1,g0:0x5aa845,g1:0xf5d31f}];
  const N=24,CS=2,FS=N*CS,FIELDS=[[-52,-58,0],[52,-58,2500],[-52,58,5000],[52,58,9000]];
  const cropG=new T.BoxGeometry(1,1,1);cropG.translate(0,.5,0);const cropM=new T.MeshLambertMaterial({color:0xffffff});
  const colTmp=new T.Color(),c0=new T.Color(),c1=new T.Color(),M4=new T.Matrix4(),ZERO=new T.Matrix4().makeScale(0,0,0);
  const fields=FIELDS.map(([cx,cz,cost],fi)=>{const cv=document.createElement('canvas');cv.width=cv.height=N*4;const g=cv.getContext('2d');const tx=new T.CanvasTexture(cv);tx.magFilter=T.NearestFilter;
    const m=new T.Mesh(new T.PlaneGeometry(FS,FS),new T.MeshLambertMaterial({map:tx}));m.rotation.x=-Math.PI/2;m.position.set(cx,.05,cz);scene.add(m);
    const inst=new T.InstancedMesh(cropG,cropM,N*N);inst.instanceMatrix.setUsage(T.DynamicDrawUsage);for(let i=0;i<N*N;i++){inst.setMatrixAt(i,ZERO);inst.setColorAt(i,colTmp.set(0x6fbf4a))}scene.add(inst);
    const F={cx,cz,cost,owned:fi===0,s:new Uint8Array(N*N),cr:new Uint8Array(N*N),g:new Float32Array(N*N),cv,g2:g,tx,inst,dirty:true,idirty:true,fi};
    // fence
    const postG=new T.BoxGeometry(.25,1.3,.25),railG=new T.BoxGeometry(FS+2,.12,.12),fm=LM(0x8a5a2b);
    [[0,-FS/2-1,0],[0,FS/2+1,0],[-FS/2-1,0,1],[FS/2+1,0,1]].forEach(([ox,oz,rot])=>{for(const yy of [.55,1.05]){const r=part(T,railG,fm,cx+ox,yy,cz+oz,scene);if(rot)r.rotation.y=Math.PI/2}for(let k=-6;k<=6;k++){if(k===0&&!rot&&oz>0===(cz<0))continue;part(T,postG,fm,cx+ox+(rot?0:k*(FS+2)/12),.65,cz+oz+(rot?k*(FS+2)/12:0),scene)}});
    // for-sale sign
    const sg=tex(T,256,128,(x,w,h)=>{x.fillStyle='#FFFDF6';x.fillRect(0,0,w,h);x.strokeStyle='#1D1A2F';x.lineWidth=10;x.strokeRect(5,5,w-10,h-10);x.fillStyle='#F2352A';x.font='900 44px sans-serif';x.textAlign='center';x.fillText('FOR SALE',w/2,58);x.fillStyle='#1D1A2F';x.font='800 34px sans-serif';x.fillText('$'+cost.toLocaleString(),w/2,104)});
    F.sign=new T.Group();part(T,new T.PlaneGeometry(5,2.5),new T.MeshBasicMaterial({map:sg,side:T.DoubleSide}),0,3,0,F.sign);part(T,postG,fm,-1.8,1.2,0,F.sign).scale.y=1.8;part(T,postG,fm,1.8,1.2,0,F.sign).scale.y=1.8;F.sign.position.set(cx,0,cz+(cz<0?FS/2+3:-FS/2-3));if(cz<0)F.sign.rotation.y=0;scene.add(F.sign);F.sign.visible=!F.owned;return F});
  function paint(F){const g=F.g2;for(let j=0;j<N;j++)for(let i=0;i<N;i++){const k=j*N+i,s=F.s[k];let col;if(!F.owned)col=(i+j)%2?'#86b858':'#80b254';else if(s===0)col=F.g[k]<0?'#c9b06a':'#b9a15a';else if(s===1)col='#6b4a2e';else col='#5a3d26';g.fillStyle=col;g.fillRect(i*4,j*4,4,4);if(F.owned&&s>=1){g.fillStyle='rgba(0,0,0,.18)';g.fillRect(i*4,j*4+1,4,1);g.fillRect(i*4,j*4+3,4,1)}else if(F.owned&&s===0){g.fillStyle='rgba(120,90,30,.35)';g.fillRect(i*4+1,j*4,1,4);g.fillRect(i*4+3,j*4,1,4)}}F.tx.needsUpdate=true}
  function updInst(F){for(let k=0;k<N*N;k++){if(F.s[k]!==2){F.inst.setMatrixAt(k,ZERO);continue}const cr=CROPS[F.cr[k]],g=Math.min(1,F.g[k]);const i=k%N,j=(k/N)|0;const h=.12+g*cr.h;const w=CS*(.35+.5*Math.min(1,g*1.6));M4.makeScale(w,h,w);M4.setPosition(F.cx-FS/2+(i+.5)*CS,.05,F.cz-FS/2+(j+.5)*CS);F.inst.setMatrixAt(k,M4);c0.set(cr.g0);c1.set(cr.g1);colTmp.copy(c0).lerp(c1,clamp((g-.6)/.4,0,1));if(g>=1)colTmp.offsetHSL(0,0,Math.sin(k)*.03);F.inst.setColorAt(k,colTmp)}F.inst.instanceMatrix.needsUpdate=true;F.inst.instanceColor.needsUpdate=true}
  // buildings
  const barn=new T.Group();part(T,bx(T,12,7,10),LM(0xb8322a),0,3.5,0,barn);const roofG=new T.CylinderGeometry(7.4,7.4,10.4,3,1);const roof=part(T,roofG,LM(0x5A5470),0,8.2,0,barn);roof.rotation.set(Math.PI/2,0,Math.PI/2);roof.scale.set(1,1,.5);part(T,bx(T,4,5,.2),LM(0xffffff),0,2.5,5.05,barn);part(T,bx(T,3.4,4.6,.25),LM(0x7a2018),0,2.4,5.1,barn);barn.position.set(-2,0,-16);scene.add(barn);
  const silo=new T.Group();[0,7].forEach(ox=>{part(T,cy(T,3,3,14,16),LM(0xd8d4e4),ox,7,0,silo);part(T,new T.SphereGeometry(3,16,8,0,Math.PI*2,0,Math.PI/2),LM(0x8c86a3),ox,14,0,silo)});part(T,bx(T,2,6,2),LM(0x8c86a3),3.5,9,2.5,silo);part(T,cy(T,.4,.4,6,8),LM(0x5A5470),3.5,6,4.2,silo).rotation.x=-.5;silo.position.set(16,0,4);scene.add(silo);const SILO=new T.Vector3(19.5,0,11);
  const unloadPad=new T.Mesh(new T.RingGeometry(4,5,32),new T.MeshBasicMaterial({color:0xFFD23F,side:T.DoubleSide}));unloadPad.rotation.x=-Math.PI/2;unloadPad.position.copy(SILO).setY(.1);scene.add(unloadPad);
  const shed=new T.Group();part(T,bx(T,12,5,8),LM(0x5c7fbf),0,2.5,0,shed);part(T,bx(T,9,4,.3),LM(0x1D1A2F),0,2,4,shed);part(T,bx(T,12.6,.5,8.6),LM(0x3a3552),0,5.2,0,shed);shed.position.set(-18,0,6);scene.add(shed);const SHED=new T.Vector3(-18,0,13);
  const shopPad=new T.Mesh(new T.RingGeometry(4,5,32),new T.MeshBasicMaterial({color:0x7FC8F8,side:T.DoubleSide}));shopPad.rotation.x=-Math.PI/2;shopPad.position.copy(SHED).setY(.1);scene.add(shopPad);
  const house=new T.Group();part(T,bx(T,9,5,7),LM(0xFFFDF6),0,2.5,0,house);const hr=part(T,new T.CylinderGeometry(5.4,5.4,7.4,3,1),LM(0xb8322a),0,6.3,0,house);hr.rotation.set(Math.PI/2,0,Math.PI/2);hr.scale.set(1,1,.45);[[-2.5,2.6],[2.5,2.6]].forEach(([x,y])=>part(T,bx(T,1.4,1.4,.2),LM(0x9fd6ff),x,y,3.55,house));house.position.set(-24,0,-20);scene.add(house);
  const OBST=[[barn.position.x,barn.position.z,7.5,6],[silo.position.x+3.5,silo.position.z,7.5,4],[shed.position.x,shed.position.z,6.5,4.5],[house.position.x,house.position.z,5,4]];
  // trees (instanced)
  {const tr=[];for(let i=0;i<140;i++){const a=Math.random()*6.283,r=125+Math.random()*120;tr.push([Math.cos(a)*r,Math.sin(a)*r,.8+Math.random()*.8])}for(let i=0;i<14;i++)tr.push([-40+Math.random()*10,-10+Math.random()*20,.9+Math.random()*.4]);
    const tk=new T.InstancedMesh(cy(T,.35,.5,3,6),LM(0x8a5a2b),tr.length),lf=new T.InstancedMesh(new T.IcosahedronGeometry(2.6,0),LM(0x3e9a4a),tr.length);tr.forEach(([x,z,s],i)=>{M4.makeScale(s,s,s);M4.setPosition(x,1.5*s,z);tk.setMatrixAt(i,M4);M4.makeScale(s,s*1.2,s);M4.setPosition(x,4.4*s,z);lf.setMatrixAt(i,M4)});scene.add(tk,lf)}
  // cows in a paddock
  const cows=[];{const pd=[-88,0];const fence=LM(0x8a5a2b);for(let k=0;k<4;k++){const r=part(T,bx(T,k%2?.12:28,.12,k%2?28:.12),fence,pd[0]+(k===1?14:k===3?-14:0),.9,pd[1]+(k===0?-14:k===2?14:0),scene)}for(let i=0;i<6;i++){const g=new T.Group();part(T,bx(T,1.2,1.1,2.2),LM(0xffffff),0,1.3,0,g);part(T,bx(T,.6,.5,.6),LM(0x1D1A2F),.3,1.6,.4,g);part(T,bx(T,.8,.8,.8),LM(0xffffff),0,1.6,1.3,g);[[-.4,-.8],[.4,-.8],[-.4,.8],[.4,.8]].forEach(([x,z])=>part(T,bx(T,.25,.8,.25),LM(0x1D1A2F),x,.4,z,g));g.position.set(pd[0]+(Math.random()-.5)*20,0,pd[1]+(Math.random()-.5)*20);g.rotation.y=Math.random()*6;scene.add(g);cows.push({g,t:Math.random()*9,home:pd})}}
  // vehicles
  const wheelG=cy(T,1,1,1,14);wheelG.rotateZ(Math.PI/2);const tyreM=LM(0x2b2b33),hubM=LM(0xFFD23F),glassM=new T.MeshLambertMaterial({color:0xbfe6ff,transparent:true,opacity:.6});
  function wheel(par,x,y,z,r,w){const g=new T.Group();const t=part(T,wheelG,tyreM,0,0,0,g);t.scale.set(w,r,r);const h=part(T,wheelG,hubM,0,0,0,g);h.scale.set(w*1.05,r*.45,r*.45);g.position.set(x,y,z);par.add(g);return g}
  const tractor=new T.Group();const tg=LM(0x2e8b3a);part(T,bx(T,1.5,1,3.2),tg,0,1.35,.3,tractor);part(T,bx(T,1.2,.9,1.7),tg,0,1.5,1.6,tractor);part(T,bx(T,1.2,.2,1.7),LM(0xFFD23F),0,2,1.6,tractor);const cab=new T.Group();part(T,bx(T,1.6,1.5,1.5),glassM,0,2.6,-.6,cab);part(T,bx(T,1.8,.15,1.8),tg,0,3.4,-.6,cab);tractor.add(cab);part(T,cy(T,.09,.09,1.2,6),LM(0x3a3552),.45,2.6,1.6,tractor);
  const tW=[wheel(tractor,-1,.95,-.7,.95,.55),wheel(tractor,1,.95,-.7,.95,.55),wheel(tractor,-.85,.55,1.7,.55,.35),wheel(tractor,.85,.55,1.7,.55,.35)];
  const plow=new T.Group();const plowBar=part(T,bx(T,1,.25,.5),LM(0x8c86a3),0,.7,0,plow);const tines=[];for(let k=0;k<7;k++){const t2=part(T,new T.ConeGeometry(.18,.8,5),LM(0x5A5470),0,.3,0,plow);t2.rotation.x=Math.PI;tines.push(t2)}plow.position.z=-2.7;tractor.add(plow);
  const seeder=new T.Group();const hop=part(T,bx(T,1,.9,1),LM(0xFFD23F),0,1.1,0,seeder);const sBar=part(T,bx(T,1,.2,.3),LM(0x5A5470),0,.5,.5,seeder);seeder.position.z=-3;tractor.add(seeder);
  const combine=new T.Group();const cr2=LM(0xb8322a);part(T,bx(T,3,2.6,5.4),cr2,0,2.3,-.4,combine);part(T,bx(T,2,1.6,1.8),glassM,0,4.2,1,combine);part(T,bx(T,2.2,.2,2),cr2,0,5.05,1,combine);const tankFill=part(T,bx(T,2.6,1,2.4),LM(0xe8c24a),0,3.7,-1.6,combine);part(T,cy(T,.3,.3,4,8),LM(0x8c86a3),1.8,3.6,-1,combine).rotation.z=1.2;
  const header=new T.Group();const hdr=part(T,bx(T,1,.5,1.4),LM(0xFFD23F),0,.7,0,header);const reel=part(T,cy(T,.6,.6,1,8),LM(0xF2352A),0,1.4,.2,header);reel.rotation.z=Math.PI/2;header.position.z=3.4;combine.add(header);
  const cW=[wheel(combine,-1.7,1.1,1,1.1,.6),wheel(combine,1.7,1.1,1,1.1,.6),wheel(combine,-1.5,.7,-2.4,.7,.45),wheel(combine,1.5,.7,-2.4,.7,.45)];
  scene.add(tractor,combine);
  // state
  const TOOLS=['Plow','Seeder','Combine'];let money=1500,day=1,clock=0,tspd=1,tool=0,crop=0,tank=0,upW=0,upS=0,upT=0,msgT=0,dust=[],saveT=0,market=0,unl=0,earned=0;
  const P={x:0,z:-4,yaw:0,v:0};const capT=()=>[300,700,1500][upT],wid=()=>tool===2?[4,6,8][upW]:[3,4,6][upW];
  const sv=S.get('tf_save',null);if(sv){try{money=sv.m;day=sv.d||1;upW=sv.w||0;upS=sv.sp||0;upT=sv.t||0;earned=sv.e||0;sv.f.forEach((f,i)=>{const F=fields[i];F.owned=f.o;F.sign.visible=!F.owned;if(f.s){for(let k=0;k<N*N;k++){F.s[k]=+f.s[k];F.cr[k]=+f.c[k];F.g[k]=(+f.g[k])/9}}})}catch(e){}}
  function save(){S.set('tf_save',{m:Math.round(money),d:day,w:upW,sp:upS,t:upT,e:earned,f:fields.map(F=>({o:F.owned,s:Array.from(F.s).join(''),c:Array.from(F.cr).join(''),g:Array.from(F.g,v=>Math.max(0,Math.min(9,Math.round(v*9)))).join('')}))});c.best(Math.round(earned))}
  fields.forEach(F=>{paint(F);updInst(F)});
  // HUD
  const panel=el('div',{style:'position:absolute;left:10px;top:10px;background:rgba(255,253,246,.92);border:3px solid #1D1A2F;border-radius:12px;padding:8px 12px;font:700 13px/1.45 Figtree,sans-serif;color:#1D1A2F;pointer-events:none;min-width:210px;box-shadow:3px 3px 0 #1D1A2F'});hud.append(panel);
  const toast=el('div',{style:'position:absolute;left:50%;top:14px;transform:translateX(-50%);background:#1D1A2F;color:#FFD23F;font:800 15px Figtree,sans-serif;padding:7px 14px;border-radius:10px;pointer-events:none;opacity:0;transition:opacity .2s;white-space:nowrap'});hud.append(toast);
  const shop=el('div',{style:'position:absolute;right:10px;top:10px;background:#FFFDF6;border:3px solid #1D1A2F;border-radius:12px;padding:10px;font:700 13px Figtree,sans-serif;color:#1D1A2F;display:none;flex-direction:column;gap:6px;pointer-events:auto;box-shadow:3px 3px 0 #1D1A2F;max-width:230px'});hud.append(shop);
  const hint=el('div',{style:'position:absolute;left:50%;bottom:10px;transform:translateX(-50%);background:rgba(29,26,47,.78);color:#FFFDF6;font:600 12px Figtree,sans-serif;padding:5px 12px;border-radius:8px;pointer-events:none;text-align:center;max-width:90%'});hud.append(hint);
  const say=m=>{toast.textContent=m;toast.style.opacity=1;msgT=2.2};
  const price=i=>Math.round(CROPS[i].price*(1+.25*Math.sin(market*.7+i*2.1))*10)/10;
  function buildShop(){shop.innerHTML='<b style="font-size:15px">🛠️ Farm shop</b>';const add=(label,cost,ok,fn)=>{const b=el('button',{class:'btn',type:'button',style:'font-size:12px;padding:6px 8px;text-align:left;color:#1D1A2F;background:#FFD23F'},label+(cost?' · $'+cost.toLocaleString():''));if(!ok)b.disabled=true;b.addEventListener('pointerdown',e=>{e.stopPropagation();if(money<cost){say('Not enough money');return}money-=cost;fn();beep(880,.1,'triangle',.05);buildShop();save()});shop.append(b)};
    fields.forEach((F,i)=>{if(!F.owned)add('Buy field '+(i+1),F.cost,true,()=>{F.owned=true;F.sign.visible=false;paint(F);say('Field '+(i+1)+' is yours!')})});
    if(upW<2)add('Wider tools ('+['3→4','4→6'][upW]+' rows)',[3000,7000][upW],true,()=>{upW++});if(upS<2)add('Faster engine',[2000,5000][upS],true,()=>{upS++});if(upT<2)add('Bigger grain tank',[2500,6000][upT],true,()=>{upT++});
    const x0=el('small',{style:'color:#5A5470'},'Drive onto the blue ring to shop.');shop.append(x0)}
  let shopOpen=false;
  // input taps
  const tap={};c.on(document,'keydown',e=>{if(e.repeat)return;tap[e.key.toLowerCase()]=1});let fL=false,aL=false,jL=false;
  function setTool(t){tool=t;tractor.visible=tool!==2;combine.visible=tool===2;plow.visible=tool===0;seeder.visible=tool===1;const w=wid();plowBar.scale.x=w*CS;tines.forEach((t2,k)=>{t2.position.x=(k/6-.5)*w*CS*.9});hop.scale.x=w*CS*.8;sBar.scale.x=w*CS;hdr.scale.x=w*CS;reel.scale.y=w*CS;say('🚜 '+TOOLS[tool]);beep(500+tool*120,.06,'square',.04)}
  setTool(0);
  function cellAt(x,z){for(const F of fields){const i=Math.floor((x-F.cx+FS/2)/CS),j=Math.floor((z-F.cz+FS/2)/CS);if(i>=0&&j>=0&&i<N&&j<N)return{F,k:j*N+i}}return null}
  let warnT=0;
  function work(dt){if(Math.abs(P.v)<.6)return;const fw={x:Math.sin(P.yaw),z:Math.cos(P.yaw)},rt={x:Math.cos(P.yaw),z:-Math.sin(P.yaw)};const off=tool===2?3.6:tool===1?-3.2:-2.9;const w=wid()*CS;const bx0=P.x+fw.x*off,bz0=P.z+fw.z*off;let did=0;
    for(let s=-w/2+.5;s<=w/2-.5;s+=.9){const x=bx0+rt.x*s,z=bz0+rt.z*s;const h=cellAt(x,z);if(!h)continue;const F=h.F,k=h.k;if(!F.owned){if(warnT<=0){say('You don’t own this field yet. Buy it at the shop.');warnT=3}continue}
      if(tool===0&&F.s[k]!==1){F.s[k]=1;F.g[k]=0;F.dirty=true;F.idirty=true;did++}
      else if(tool===1&&F.s[k]===1){const cost=CROPS[crop].seed;if(money<cost){if(warnT<=0){say('Out of money for seed!');warnT=3}continue}money-=cost;F.s[k]=2;F.cr[k]=crop;F.g[k]=0;F.dirty=true;F.idirty=true;did++}
      else if(tool===2&&F.s[k]===2&&F.g[k]>=1){const y=CROPS[F.cr[k]].y;if(tank+y>capT()){if(warnT<=0){say('Grain tank full! Unload at the silo (yellow ring).');warnT=3}continue}tank+=y;tankMix[F.cr[k]]+=y;F.s[k]=0;F.g[k]=-1;F.dirty=true;F.idirty=true;did++}}
    if(did&&Math.random()<.6)dust.push(mkDust(bx0,bz0,tool===2?0xe8c24a:0x8a6a44))}
  const tankMix=[0,0,0];
  const dustG=new T.SphereGeometry(.6,6,5);function mkDust(x,z,col){const m=new T.Mesh(dustG,new T.MeshBasicMaterial({color:col,transparent:true,opacity:.55}));m.position.set(x+(Math.random()-.5)*3,.6,z+(Math.random()-.5)*3);scene.add(m);return{m,t:1.2,v:new T.Vector3((Math.random()-.5)*2,1.5+Math.random(),(Math.random()-.5)*2)}}
  let camYaw=0,camDist=16;/*DBGT*/
  st3.onFrame(dt=>{const I=input,K=I.keys;const sdt=dt*tspd;
    // time & growth
    clock+=sdt;market+=sdt/60;if(clock>=120){clock-=120;day++;say('☀️ Day '+day);save()}
    for(const F of fields){if(!F.owned)continue;let ch=false;for(let k=0;k<N*N;k++){if(F.s[k]===2&&F.g[k]<1){F.g[k]=Math.min(1,F.g[k]+sdt/CROPS[F.cr[k]].t);ch=true}}if(ch)F.gT=(F.gT||0)+dt;if(F.gT>.35){F.gT=0;F.idirty=true}}
    // controls
    if(tap['1'])setTool(0);if(tap['2'])setTool(1);if(tap['3'])setTool(2);const fi=!!I.fire,ai=!!I.alt,ji=!!I.jumpBtn;if(fi&&!fL)setTool((tool+1)%3);if((tap.q||(ai&&!aL))){crop=(crop+1)%3;say('🌱 Seed: '+CROPS[crop].n+' ($'+CROPS[crop].seed+'/row-cell)')}if(tap.t||(ji&&!jL)){tspd=tspd===1?4:tspd===4?12:1;say('⏩ Time ×'+tspd)}fL=fi;aL=ai;jL=ji;for(const k in tap)delete tap[k];
    const fwd=(K.w||K.arrowup?1:0)-(K.s||K.arrowdown?1:0)-(I.joy.y||0),str=(K.a||K.arrowleft?1:0)-(K.d||K.arrowright?1:0)-(I.joy.x||0);
    const vmax=(tool===2?7:11)*(1+upS*.25),acc=tool===2?4:6;if(fwd>0)P.v=Math.min(vmax,P.v+acc*fwd*dt);else if(fwd<0)P.v=Math.max(-vmax*.45,P.v+acc*1.4*fwd*dt);else P.v*=Math.pow(.25,dt);
    P.yaw+=str*dt*(tool===2?.9:1.3)*clamp(P.v/4,-1,1);const nx=P.x+Math.sin(P.yaw)*P.v*dt,nz=P.z+Math.cos(P.yaw)*P.v*dt;let blocked=Math.abs(nx)>230||Math.abs(nz)>230;for(const[ox,oz,hw,hd]of OBST)if(Math.abs(nx-ox)<hw&&Math.abs(nz-oz)<hd)blocked=true;if(blocked)P.v*=-.2;else{P.x=nx;P.z=nz}
    work(dt);warnT-=dt;
    const veh=tool===2?combine:tractor;veh.position.set(P.x,0,P.z);veh.rotation.y=P.yaw;veh.position.y=Math.abs(P.v)>1?Math.sin(performance.now()/60)*.03:0;(tool===2?cW:tW).forEach((w,i)=>w.rotation.x+=P.v*dt/(i<2?1:.6));reel.rotation.x+=dt*(Math.abs(P.v)>.5?6:1);tankFill.scale.y=Math.max(.05,tank/capT());tankFill.position.y=3.2+tankFill.scale.y*.5;
    if(Math.random()<dt*3&&Math.abs(P.v)>.2)dust.push(mkDust(P.x-Math.sin(P.yaw)*2,P.z-Math.cos(P.yaw)*2,0xc9b48a));
    dust=dust.filter(d=>{d.t-=dt;d.m.position.addScaledVector(d.v,dt);d.m.scale.setScalar(1+(1.2-d.t));d.m.material.opacity=Math.max(0,d.t*.45);if(d.t<=0){scene.remove(d.m);d.m.material.dispose();return false}return true});
    // silo unload
    const dS=Math.hypot(P.x-SILO.x,P.z-SILO.z);unl=0;if(dS<6&&tank>0){let n=Math.min(tank,dt*90);tank-=n;for(let i=0;i<3&&n>0;i++){const m=Math.min(n,tankMix[i]);tankMix[i]-=m;n-=m;money+=m*price(i);earned+=m*price(i)}if(tank<.01){tank=0;tankMix.fill(0)}unl=1;if(Math.random()<dt*8)beep(300+Math.random()*80,.03,'triangle',.02);if(tank<=0){say('💰 Sold! $'+Math.round(money).toLocaleString());save()}}
    // shop
    const dH=Math.hypot(P.x-SHED.x,P.z-SHED.z);const open=dH<6;if(open!==shopOpen){shopOpen=open;shop.style.display=open?'flex':'none';if(open)buildShop()}
    // cows wander
    cows.forEach(q=>{q.t+=dt;if(q.t>4){q.t=0;q.to=Math.random()*6.28}if(q.to!=null){q.g.rotation.y+=(q.to-q.g.rotation.y)*dt;const p=q.g.position;p.x+=Math.sin(q.g.rotation.y)*dt*.6;p.z+=Math.cos(q.g.rotation.y)*dt*.6;p.x=clamp(p.x,q.home[0]-12,q.home[0]+12);p.z=clamp(p.z,q.home[1]-12,q.home[1]+12)}});
    // redraw fields
    for(const F of fields){if(F.dirty){F.dirty=false;paint(F)}if(F.idirty){F.idirty=false;updInst(F)}}
    // camera
    if(I.down||I.touch){camYaw-=I.mdx*.005}if(I.wheel)camDist=clamp(camDist+I.wheel*2,9,40);camYaw*=Math.pow(.6,dt*(I.down?0:1));const cy2=P.yaw+Math.PI+camYaw;const tx=P.x+Math.sin(cy2)*camDist,tz=P.z+Math.cos(cy2)*camDist;camera.position.lerp(new T.Vector3(tx,camDist*.55+3,tz),Math.min(1,dt*4));camera.lookAt(P.x,2,P.z);
    msgT-=dt;if(msgT<=0)toast.style.opacity=0;
    const owned=fields.filter(F=>F.owned);let ripe=0,grow=0;owned.forEach(F=>{for(let k=0;k<N*N;k++)if(F.s[k]===2){if(F.g[k]>=1)ripe++;else grow++}});
    panel.innerHTML='<div style="font:900 18px Figtree,sans-serif">💰 $'+Math.round(money).toLocaleString()+'</div>Day '+day+' · '+String(6+Math.floor(clock/10)).padStart(2,'0')+':00 · time ×'+tspd+'<br>🚜 '+TOOLS[tool]+' ('+wid()+' rows) · 🌱 '+CROPS[crop].n+'<br>🌾 Grain tank <span style="display:inline-block;width:90px;height:9px;border:2px solid #1D1A2F;border-radius:5px;vertical-align:middle;overflow:hidden"><i style="display:block;height:100%;width:'+(tank/capT()*100)+'%;background:#e8c24a"></i></span> '+Math.round(tank)+'/'+capT()+' t'+'<br>Crops: '+grow+' growing · <b style="color:#2e8b3a">'+ripe+' ripe</b><br><span style="color:#5A5470">Prices: '+CROPS.map((q,i)=>q.n+' $'+price(i)).join(' · ')+'</span>'+(unl?'<br><b style="color:#b8322a">Unloading…</b>':'');
    hint.textContent=tool===0?'Plow: drive over a field to turn the soil. 2 = seeder, 3 = combine.':tool===1?'Seeder: drive over plowed (brown) soil to plant '+CROPS[crop].n+'. Q switches crop, T speeds up time.':'Combine: harvest ripe (golden) crops, then unload at the yellow ring by the silo.';
    c.stat('Tractor Fields · Day '+day+' · $'+Math.round(money).toLocaleString());saveT+=dt;if(saveT>10){saveT=0;save()}});
  st3.overlay('<small class="kick">3D simulator · farming</small><h2>Tractor Fields</h2><p>Your own farm. <b>Plow</b> a field, <b>seed</b> it with wheat, corn or canola, let it grow, then bring out the <b>combine</b> and harvest. Unload grain at the silo when the price is good, and spend the money on new fields and bigger machines. Your farm saves automatically.</p><p class="ctl"><b>Controls:</b> WASD or arrows drive. <b>1</b> plow, <b>2</b> seeder, <b>3</b> combine. <b>Q</b> changes seed, <b>T</b> speeds up time. Drag to look around, scroll to zoom. Drive onto the blue ring for the shop and the yellow ring to sell grain. On a phone: joystick to drive, TOOL / CROP / SPEED buttons.</p>',[['Start farming',()=>{},true]]);
  return()=>{save();st3.dispose()}})}});

/* ---------- Farm Life (2D cozy farm sim) ---------- */
G.push({id:'sim_farm',name:'Farm Life',kind:'sim',wide:true,tint:'#8fd36b',blurb:'A cozy farm sim. Till the soil, plant and water crops, raise chickens and cows, ship your harvest every evening and turn an overgrown plot into a thriving farm.',fmt:b=>'$'+b,
art:'<rect width="120" height="72" fill="#8fd36b"/><rect x="8" y="8" width="30" height="22" fill="#FFFDF6" stroke="#1D1A2F" stroke-width="2"/><path d="M4 10L23 -2L42 10z" fill="#F2352A" stroke="#1D1A2F" stroke-width="2"/><g fill="#8a5a2b"><rect x="50" y="36" width="14" height="12"/><rect x="68" y="36" width="14" height="12"/><rect x="86" y="36" width="14" height="12"/><rect x="50" y="52" width="14" height="12"/><rect x="68" y="52" width="14" height="12"/><rect x="86" y="52" width="14" height="12"/></g><g fill="#2BB673"><circle cx="57" cy="40" r="4"/><circle cx="75" cy="40" r="4"/><circle cx="93" cy="56" r="4"/></g><circle cx="75" cy="57" r="5" fill="#FF9F43" stroke="#1D1A2F" stroke-width="1.5"/><circle cx="20" cy="54" r="7" fill="#fff" stroke="#1D1A2F" stroke-width="2"/><path d="M18 46l2-4 2 4z" fill="#F2352A"/>',
run(root,c){const W=960,H=620,TS=40,CO=24,RO=14;const[cv,x]=mk(W,H,'width:100%;touch-action:none');root.append(cv,el('p',{class:'hint'},'WASD / arrows to walk, Space or E to use your tool on the tile you face, 1–4 to pick a tool. Or just tap a tile: the farmer walks there and does it. Water crops every day, ship produce in the bin, sleep at the house door to start a new day.'));
  const ui=cookUI(cv,c);
  const CROP=[{k:'turnip',n:'Turnip',seed:20,sell:45,days:3,col:'#f4f0ff',top:'#b56bd6'},{k:'carrot',n:'Carrot',seed:30,sell:70,days:4,col:'#FF9F43',top:'#2BB673'},{k:'straw',n:'Strawberry',seed:60,sell:55,days:5,regrow:2,col:'#F2352A',top:'#2BB673'},{k:'tomato',n:'Tomato',seed:50,sell:40,days:6,regrow:3,col:'#e0453a',top:'#2e8b3a'},{k:'corn',n:'Corn',seed:70,sell:60,days:7,regrow:3,col:'#FFD23F',top:'#6fbf4a'},{k:'pumpkin',n:'Pumpkin',seed:80,sell:260,days:8,col:'#f08a24',top:'#2e8b3a'}];
  const TOOLS=[['hoe','⛏️','Hoe'],['can','💧','Watering can'],['seed','🌱','Seeds'],['hand','✋','Hands']];
  // map: 0 grass,1 soil,2 path,3 water,4 solid,5 pen floor
  const map=[],soil={};for(let j=0;j<RO;j++){map.push([]);for(let i=0;i<CO;i++)map[j].push(0)}
  const setR=(i0,j0,i1,j1,v)=>{for(let j=j0;j<=j1;j++)for(let i=i0;i<=i1;i++)map[j][i]=v};
  setR(1,1,4,3,4);setR(0,4,23,4,2);setR(5,0,5,13,2);setR(1,10,3,12,3);setR(0,11,0,12,3);setR(13,0,23,3,5);setR(21,0,23,1,4);setR(13,0,14,1,4);setR(8,1,9,2,4);map[3][6]=4;
  const trees=[[23,6],[23,9],[23,12],[0,7],[1,5],[0,8],[12,13],[20,13],[16,13]];trees.forEach(([i,j])=>map[j][i]=4);
  const BIN=[6,3],SHOP=[8,2],DOOR=[2,3],GATE=[17,4];const inFarm=(i,j)=>i>=6&&i<=22&&j>=5&&j<=12;
  let money=500,day=1,clock=6,weather='sun',tomorrow='sun',tool=0,seedSel=0,canCap=20,can=20,px=3.5,py=4.5,fx=0,fy=1,path=[],pend=null,shopOpen=false,msg='',msgT=0,sleepT=0,walkT=0,earned=0,shipped=[];
  const seeds=[5,0,0,0,0,0],inv={};const animals=[];const drops=[];
  function addAnimal(k){animals.push({k,x:15+Math.random()*6,y:1+Math.random()*2,tx:0,ty:0,t:0,love:0,pet:false})}
  const sv=S.get('farm_save',null);if(sv){try{money=sv.m;day=sv.d;canCap=sv.cc||20;can=canCap;earned=sv.e||0;sv.s.forEach((v,i)=>seeds[i]=v);Object.assign(inv,sv.inv||{});Object.entries(sv.soil||{}).forEach(([k,v])=>{soil[k]=v;const[i,j]=k.split(',').map(Number);map[j][i]=1});(sv.an||[]).forEach(a=>{addAnimal(a.k);animals[animals.length-1].love=a.love||0})}catch(e){}}
  function save(){S.set('farm_save',{m:money,d:day,cc:canCap,e:earned,s:seeds,inv,soil,an:animals.map(a=>({k:a.k,love:a.love}))});c.best(Math.round(earned))}
  const say=m=>{msg=m;msgT=2.4};
  const key=(i,j)=>i+','+j,walkable=(i,j)=>i>=0&&j>=0&&i<CO&&j<RO&&map[j][i]!==4&&map[j][i]!==3&&!(j===4&&i>=13&&i!==GATE[0]&&false);
  // pen fence: row 3/4 boundary between pen (row<=3, i>=13) and path row 4, except the gate
  const blockedMove=(i0,j0,i1,j1)=>{if(!walkable(i1,j1))return true;const pen=(i,j)=>i>=13&&j<=3;if(pen(i0,j0)!==pen(i1,j1)&&!((i0===GATE[0]&&i1===GATE[0])))return true;return false};
  function bfs(ti,tj){const si=Math.floor(px),sj=Math.floor(py);const q=[[si,sj]],prev={};prev[key(si,sj)]=null;const goals=new Set();[[0,1],[1,0],[0,-1],[-1,0],[0,0]].forEach(([a,b])=>{const i=ti+a,j=tj+b;if(walkable(i,j))goals.add(key(i,j))});
    while(q.length){const[i,j]=q.shift();if(goals.has(key(i,j))){const out=[];let k=key(i,j);while(k&&k!==key(si,sj)){const[a,b]=k.split(',').map(Number);out.unshift([a+.5,b+.5]);k=prev[k]}return out}for(const[a,b]of[[0,1],[1,0],[0,-1],[-1,0]]){const ni=i+a,nj=j+b;const k=key(ni,nj);if(k in prev||blockedMove(i,j,ni,nj))continue;prev[k]=key(i,j);q.push([ni,nj])}}return null}
  function act(i,j){if(i<0||j<0||i>=CO||j>=RO)return;
    if(i===DOOR[0]&&j===DOOR[1]||(i>=1&&i<=4&&j>=1&&j<=3)){sleep();return}if(i===BIN[0]&&j===BIN[1]){ship();return}if(i>=8&&i<=9&&j>=1&&j<=2){shopOpen=true;return}
    const d=drops.findIndex(o=>Math.floor(o.x)===i&&Math.floor(o.y)===j);if(d>=0){const o=drops.splice(d,1)[0];inv[o.k]=(inv[o.k]||0)+1;beep(900,.06,'triangle',.05);say('+1 '+o.n);return}
    const an=animals.find(a=>Math.floor(a.x)===i&&Math.floor(a.y)===j);if(an&&tool===3){if(!an.pet){an.pet=true;an.love=Math.min(10,an.love+1);say('❤️ '+(an.k==='cow'?'The cow':'The chicken')+' loves you ('+an.love+'/10)');beep(700,.08,'sine',.05)}else say('Already petted today');return}
    const t=map[j][i];const k=key(i,j),s=soil[k];
    if(t===3){if(tool===1){can=canCap;say('💧 Can refilled');noise(.3,'lowpass',700,.1)}return}
    if(tool===0){if(t===0&&inFarm(i,j)){map[j][i]=1;soil[k]={w:false};noise(.12,'lowpass',400,.15)}else if(t===1&&s&&!s.c){}else if(!inFarm(i,j))say('Till inside the farm plot');return}
    if(tool===1){if(t===1){if(can<=0){say('Can is empty. Refill at the pond');return}can--;s.w=true;noise(.15,'highpass',2500,.06)}return}
    if(tool===2){if(t===1&&!s.c){if(seeds[seedSel]<=0){say('No '+CROP[seedSel].n+' seeds. Buy some at the shop');return}seeds[seedSel]--;s.c={k:seedSel,g:0,ripe:false};beep(600,.05,'triangle',.04)}return}
    if(tool===3){if(s&&s.c&&s.c.ripe){const cr=CROP[s.c.k];inv[cr.k]=(inv[cr.k]||0)+1;beep(880,.07,'triangle',.05);say('+1 '+cr.n);if(cr.regrow){s.c.ripe=false;s.c.g=cr.days-cr.regrow}else s.c=null}}}
  function ship(){let tot=0;const items=[];Object.keys(inv).forEach(k=>{const n=inv[k];if(!n)return;const cr=CROP.find(q=>q.k===k);const pr=cr?cr.sell:k==='egg'?25:k==='gegg'?70:k==='milk'?80:k==='lmilk'?150:0;tot+=n*pr;items.push(n+'× '+(cr?cr.n:{egg:'Egg',gegg:'Golden egg',milk:'Milk',lmilk:'Large milk'}[k]));inv[k]=0});if(!tot){say('Nothing to ship. Harvest something first!');return}shipped.push(tot);say('📦 Shipped '+items.join(', ')+'. Paid tonight: $'+tot);beep(660,.1,'triangle',.05)}
  function sleep(){if(sleepT>0)return;sleepT=1.6;const paid=shipped.reduce((a,b)=>a+b,0);shipped=[];money+=paid;earned+=paid;day++;clock=6;weather=tomorrow;tomorrow=Math.random()<.22?'rain':'sun';
    Object.values(soil).forEach(s=>{if(s.c&&!s.c.ripe&&(s.w||weather==='rain')){s.c.g++;if(s.c.g>=CROP[s.c.k].days)s.c.ripe=true}s.w=weather==='rain'});
    Object.keys(soil).forEach(k=>{const s=soil[k];if(!s.c&&Math.random()<.08){delete soil[k];const[i,j]=k.split(',').map(Number);map[j][i]=0}});
    animals.forEach(a=>{if(!a.pet)a.love=Math.max(0,a.love-1);a.pet=false;const big=a.love>=6&&Math.random()<.5;drops.push({k:a.k==='cow'?(big?'lmilk':'milk'):(big?'gegg':'egg'),n:a.k==='cow'?(big?'Large milk':'Milk'):(big?'Golden egg':'Egg'),x:Math.floor(a.x)+.5,y:Math.floor(a.y)+.5})});
    can=canCap;save();say((paid?'💰 Earned $'+paid+' from shipping. ':'')+'Day '+day+(weather==='rain'?' · 🌧️ Rain waters your crops':''))}
  // input
  const K={};c.on(document,'keydown',e=>{const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(k))e.preventDefault();if(e.repeat)return;K[k]=1;if('1234'.includes(k)&&k.length===1){if(tool===2&&+k===3)seedSel=(seedSel+1)%CROP.length;tool=+k-1}if(k===' '||k==='e'){act(Math.floor(px+fx),Math.floor(py+fy))}if(k==='escape')shopOpen=false});c.on(document,'keyup',e=>{K[e.key.toLowerCase()]=0});
  ui.onDown=p=>{if(shopOpen||sleepT>0)return;if(p.y>=RO*TS)return;const i=Math.floor(p.x/TS),j=Math.floor(p.y/TS);const di=i+.5-px,dj=j+.5-py;if(Math.abs(di)<=1.3&&Math.abs(dj)<=1.3){if(Math.abs(di)>Math.abs(dj)){fx=Math.sign(di);fy=0}else if(dj){fy=Math.sign(dj);fx=0}act(i,j);return}const pth=bfs(i,j);if(pth){path=pth;pend=[i,j]}else say('Can’t get there')};
  // drawing helpers
  function grassTile(i,j){x.fillStyle=(i+j)%2?'#86c95a':'#80c255';x.fillRect(i*TS,j*TS,TS,TS);x.fillStyle='rgba(40,110,30,.35)';const h=(i*7+j*13)%5;for(let k=0;k<3;k++){const gx=i*TS+((h+k*13)%34)+3,gy=j*TS+((h*3+k*11)%30)+6;x.fillRect(gx,gy,2,5);x.fillRect(gx+3,gy+1,2,4)}}
  function drawCrop(s,cx,cy){const cr=CROP[s.c.k],g=s.c.ripe?1:s.c.g/cr.days;x.strokeStyle='#1D1A2F';x.lineWidth=1.5;if(g<.25){x.fillStyle='#4fb35e';x.beginPath();x.ellipse(cx-4,cy+4,4,2.5,-.6,0,7);x.ellipse(cx+4,cy+4,4,2.5,.6,0,7);x.fill();return}
    const h=8+g*14;x.strokeStyle='#2e8b3a';x.lineWidth=3;x.beginPath();x.moveTo(cx,cy+10);x.lineTo(cx,cy+10-h);x.stroke();x.fillStyle=cr.top;[[-6,-h*.5],[6,-h*.7],[-5,-h*.9],[5,-h*.35]].forEach(([a,b])=>{x.beginPath();x.ellipse(cx+a,cy+10+b,6*Math.min(1,g+.3),3,a<0?-.5:.5,0,7);x.fill()});
    if(s.c.ripe){x.fillStyle=cr.col;x.strokeStyle='#1D1A2F';x.lineWidth=1.5;if(cr.k==='pumpkin'){x.beginPath();x.ellipse(cx,cy+8,13,9,0,0,7);x.fill();x.stroke()}else if(cr.k==='corn'){x.beginPath();x.ellipse(cx+5,cy-2,4,9,.2,0,7);x.fill();x.stroke()}else if(cr.k==='carrot'||cr.k==='turnip'){x.beginPath();x.arc(cx,cy+8,7,0,7);x.fill();x.stroke()}else{[[-6,-2],[6,0],[0,6]].forEach(([a,b])=>{x.beginPath();x.arc(cx+a,cy+b,4.5,0,7);x.fill();x.stroke()})}const t=performance.now()/300;x.fillStyle='rgba(255,255,255,.8)';x.beginPath();x.arc(cx+10,cy-12+Math.sin(t)*2,2,0,7);x.fill()}}
  function drawChicken(a){const X=a.x*TS,Y=a.y*TS,b=Math.sin(a.t*8)*1.5;x.fillStyle='#fff';x.strokeStyle='#1D1A2F';x.lineWidth=2;x.beginPath();x.ellipse(X,Y+b,10,8,0,0,7);x.fill();x.stroke();x.beginPath();x.arc(X+(a.dir>0?7:-7),Y-7+b,5,0,7);x.fill();x.stroke();x.fillStyle='#F2352A';x.fillRect(X+(a.dir>0?5:-8),Y-14+b,3,4);x.fillStyle='#FF9F43';x.fillRect(X+(a.dir>0?11:-14),Y-7+b,3,2)}
  function drawCow(a){const X=a.x*TS,Y=a.y*TS;x.fillStyle='#fff';x.strokeStyle='#1D1A2F';x.lineWidth=2;x.beginPath();x.roundRect(X-17,Y-10,34,20,8);x.fill();x.stroke();x.fillStyle='#1D1A2F';x.beginPath();x.arc(X-5,Y-2,5,0,7);x.arc(X+8,Y+3,4,0,7);x.fill();const hx=X+(a.dir>0?20:-20);x.fillStyle='#fff';x.beginPath();x.roundRect(hx-7,Y-14,14,14,5);x.fill();x.stroke();x.fillStyle='#FF8FB1';x.fillRect(hx-5,Y-5,10,4);x.fillStyle='#1D1A2F';[-12,-4,6,12].forEach(o=>x.fillRect(X+o,Y+9,3,6))}
  function drawFarmer(){const X=px*TS,Y=py*TS,b=path.length||K.w||K.a||K.s||K.d||K.arrowup||K.arrowdown||K.arrowleft||K.arrowright?Math.abs(Math.sin(walkT*10))*3:0;x.fillStyle='rgba(0,0,0,.2)';x.beginPath();x.ellipse(X,Y+14,11,4,0,0,7);x.fill();x.strokeStyle='#1D1A2F';x.lineWidth=2;x.fillStyle='#2d6fd6';x.beginPath();x.roundRect(X-8,Y-6-b,16,18,4);x.fill();x.stroke();x.fillStyle='#f1c9a5';x.beginPath();x.arc(X,Y-12-b,7,0,7);x.fill();x.stroke();x.fillStyle='#e8c24a';x.beginPath();x.ellipse(X,Y-17-b,12,4,0,0,7);x.fill();x.stroke();x.beginPath();x.ellipse(X,Y-20-b,7,5,0,Math.PI,0);x.fill();x.stroke();x.font='16px sans-serif';x.textAlign='center';x.fillText(TOOLS[tool][1],X+fx*14+10,Y+fy*10+4-b)}
  c.loop(ms=>{const dt=Math.min(.05,ms/1000);ui.frame();walkT+=dt;
    if(sleepT>0){sleepT-=dt}else if(!shopOpen){clock+=dt*20/150;if(clock>=26){say('You passed out from exhaustion…');sleep()}}
    // movement
    let mx=(K.d||K.arrowright?1:0)-(K.a||K.arrowleft?1:0),my=(K.s||K.arrowdown?1:0)-(K.w||K.arrowup?1:0);if(mx||my){path=[];pend=null}
    if(!mx&&!my&&path.length){const[tx,ty]=path[0];const dx=tx-px,dy=ty-py,d=Math.hypot(dx,dy);if(d<.08){px=tx;py=ty;path.shift();if(!path.length&&pend){const[i,j]=pend;const di=i+.5-px,dj=j+.5-py;if(Math.abs(di)>Math.abs(dj)){fx=Math.sign(di);fy=0}else{fy=Math.sign(dj)||1;fx=0}act(i,j);pend=null}}else{mx=dx/d;my=dy/d}}
    if((mx||my)&&!shopOpen&&sleepT<=0){const sp=4.2*dt;if(Math.abs(mx)>Math.abs(my)){fx=Math.sign(mx);fy=0}else{fy=Math.sign(my);fx=0}const nx=px+mx*sp,ny=py+my*sp;const ci=Math.floor(px),cj=Math.floor(py);const ti=Math.floor(nx+Math.sign(mx)*.3),tj=Math.floor(ny+Math.sign(my)*.3);if(!blockedMove(ci,cj,ti,cj)||ti===ci)px=nx;if(!blockedMove(ci,cj,ci,tj)||tj===cj)py=ny;px=clamp(px,.4,CO-.4);py=clamp(py,.4,RO-.4)}
    animals.forEach(a=>{a.t+=dt;if(a.t>2+Math.random()*3){a.t=0;a.tx=clamp(a.x+(Math.random()-.5)*4,13.6,22.4);a.ty=clamp(a.y+(Math.random()-.5)*3,a.k==='cow'?2.2:1.5,3.5);if(a.tx>20.6&&a.ty<2.2)a.ty=2.4;if(a.tx<15&&a.ty<2.2)a.ty=2.4}const dx=a.tx-a.x,dy=a.ty-a.y,d=Math.hypot(dx,dy);if(d>.05&&a.tx){a.x+=dx/d*dt*(a.k==='cow'?.5:1);a.y+=dy/d*dt*(a.k==='cow'?.5:1);a.dir=Math.sign(dx)||a.dir||1}});
    // draw map
    for(let j=0;j<RO;j++)for(let i=0;i<CO;i++){const t=map[j][i];if(t===0||t===4)grassTile(i,j);else if(t===2){x.fillStyle=(i+j)%2?'#d9c08a':'#d3b983';x.fillRect(i*TS,j*TS,TS,TS);x.fillStyle='rgba(120,90,40,.25)';x.fillRect(i*TS+((i*13)%30)+4,j*TS+((j*7)%30)+4,4,3)}else if(t===5){x.fillStyle=(i+j)%2?'#c9d88a':'#c2d184';x.fillRect(i*TS,j*TS,TS,TS)}else if(t===3){x.fillStyle='#4DA3E0';x.fillRect(i*TS,j*TS,TS,TS);x.strokeStyle='rgba(255,255,255,.5)';x.lineWidth=2;const o=Math.sin(walkT*2+i+j)*4;x.beginPath();x.moveTo(i*TS+8+o,j*TS+14);x.lineTo(i*TS+20+o,j*TS+14);x.moveTo(i*TS+18-o,j*TS+28);x.lineTo(i*TS+30-o,j*TS+28);x.stroke()}
      else if(t===1){const s=soil[key(i,j)];x.fillStyle=s&&(s.w||weather==='rain')?'#5a3a22':'#8a5a34';x.fillRect(i*TS+1,j*TS+1,TS-2,TS-2);x.fillStyle='rgba(0,0,0,.18)';for(let k=6;k<TS;k+=10)x.fillRect(i*TS+4,j*TS+k,TS-8,2);if(s&&s.c)drawCrop(s,i*TS+TS/2,j*TS+TS/2)}}
    // farm plot border
    x.strokeStyle='rgba(138,90,43,.6)';x.setLineDash([6,5]);x.lineWidth=2;x.strokeRect(6*TS,5*TS,17*TS,8*TS);x.setLineDash([]);
    // buildings
    x.fillStyle='#FFFDF6';x.strokeStyle='#1D1A2F';x.lineWidth=3;x.fillRect(1*TS+4,1*TS+14,4*TS-8,3*TS-14);x.strokeRect(1*TS+4,1*TS+14,4*TS-8,3*TS-14);x.fillStyle='#F2352A';x.beginPath();x.moveTo(TS-6,TS+18);x.lineTo(3*TS,4);x.lineTo(5*TS+6,TS+18);x.closePath();x.fill();x.stroke();x.fillStyle='#8a5a2b';x.fillRect(DOOR[0]*TS+8,DOOR[1]*TS+2,24,TS-2);x.strokeRect(DOOR[0]*TS+8,DOOR[1]*TS+2,24,TS-2);x.fillStyle='#9fd6ff';x.fillRect(3*TS+6,2*TS+6,26,20);x.strokeRect(3*TS+6,2*TS+6,26,20);x.fillStyle='#FFD23F';x.beginPath();x.arc(DOOR[0]*TS+28,DOOR[1]*TS+22,2.5,0,7);x.fill();
    x.fillStyle='#8a5a2b';x.fillRect(BIN[0]*TS+4,BIN[1]*TS+12,TS-8,TS-14);x.strokeRect(BIN[0]*TS+4,BIN[1]*TS+12,TS-8,TS-14);x.fillStyle='#b07a44';x.fillRect(BIN[0]*TS+2,BIN[1]*TS+8,TS-4,8);x.strokeRect(BIN[0]*TS+2,BIN[1]*TS+8,TS-4,8);x.font='16px sans-serif';x.textAlign='center';x.fillText('📦',BIN[0]*TS+TS/2,BIN[1]*TS+34);
    x.fillStyle='#FFFDF6';x.fillRect(8*TS+2,1*TS+14,2*TS-4,2*TS-16);x.strokeRect(8*TS+2,1*TS+14,2*TS-4,2*TS-16);for(let k=0;k<5;k++){x.fillStyle=k%2?'#FFFDF6':'#2BB673';x.fillRect(8*TS+k*16,TS,16,16)}x.strokeRect(8*TS,TS,80,16);x.fillStyle='#1D1A2F';x.font='800 12px Figtree, sans-serif';x.fillText('SEEDS',9*TS,2*TS+24);x.font='18px sans-serif';x.fillText('🌱',9*TS,2*TS+8);
    // pen: fence, coop, barn
    x.strokeStyle='#8a5a2b';x.lineWidth=4;x.beginPath();x.moveTo(13*TS,4*TS);x.lineTo(GATE[0]*TS,4*TS);x.moveTo((GATE[0]+1)*TS,4*TS);x.lineTo(24*TS,4*TS);x.moveTo(13*TS,0);x.lineTo(13*TS,4*TS);x.stroke();x.lineWidth=2;for(let i=13;i<=24;i++)if(i!==GATE[0]&&i!==GATE[0]+1){x.fillStyle='#8a5a2b';x.fillRect(i*TS-3,4*TS-8,6,12)}
    x.fillStyle='#e0a458';x.strokeStyle='#1D1A2F';x.lineWidth=3;x.fillRect(21*TS+4,4,3*TS-8,2*TS-8);x.strokeRect(21*TS+4,4,3*TS-8,2*TS-8);x.fillStyle='#1D1A2F';x.fillRect(22*TS+8,TS+6,20,TS-10);x.font='800 11px Figtree';x.fillStyle='#1D1A2F';x.fillText('COOP',22*TS+20,22);
    x.fillStyle='#b8322a';x.fillRect(13*TS+4,4,2*TS-8,2*TS-8);x.strokeRect(13*TS+4,4,2*TS-8,2*TS-8);x.strokeStyle='#fff';x.beginPath();x.moveTo(13*TS+10,10);x.lineTo(15*TS-10,2*TS-10);x.moveTo(15*TS-10,10);x.lineTo(13*TS+10,2*TS-10);x.stroke();
    trees.forEach(([i,j])=>{const X=i*TS+TS/2,Y=j*TS+TS/2;x.fillStyle='#8a5a2b';x.fillRect(X-4,Y,8,16);x.fillStyle='#2e8b3a';x.strokeStyle='#1D1A2F';x.lineWidth=2;x.beginPath();x.arc(X,Y-4,17,0,7);x.fill();x.stroke();x.fillStyle='rgba(255,255,255,.18)';x.beginPath();x.arc(X-6,Y-10,6,0,7);x.fill()});
    drops.forEach(o=>{const X=o.x*TS,Y=o.y*TS+Math.sin(walkT*3)*2;x.font='20px sans-serif';x.textAlign='center';x.fillText(o.k.includes('milk')?'🥛':o.k==='gegg'?'🌟':'🥚',X,Y+7)});
    animals.forEach(a=>a.k==='cow'?drawCow(a):drawChicken(a));
    // facing highlight
    const fi=Math.floor(px+fx),fj=Math.floor(py+fy);x.strokeStyle='rgba(255,255,255,.85)';x.lineWidth=2;x.strokeRect(fi*TS+2,fj*TS+2,TS-4,TS-4);if(pend){x.strokeStyle='#FFD23F';x.strokeRect(pend[0]*TS+2,pend[1]*TS+2,TS-4,TS-4)}
    drawFarmer();
    // weather & night
    if(weather==='rain'){x.strokeStyle='rgba(180,210,255,.6)';x.lineWidth=1.5;for(let k=0;k<70;k++){const rx=(k*137+walkT*300)%W,ry=(k*89+walkT*600)%(RO*TS);x.beginPath();x.moveTo(rx,ry);x.lineTo(rx-4,ry+12);x.stroke()}x.fillStyle='rgba(40,60,110,.15)';x.fillRect(0,0,W,RO*TS)}
    const night=clamp((clock-18)/4,0,.55);if(night>0){x.fillStyle='rgba(20,20,60,'+night+')';x.fillRect(0,0,W,RO*TS)}
    if(sleepT>0){x.fillStyle='rgba(10,10,30,'+Math.min(1,sleepT)+')';x.fillRect(0,0,W,H);x.fillStyle='#FFD23F';x.font='40px "Bagel Fat One", sans-serif';x.textAlign='center';x.fillText('Day '+day,W/2,H/2)}
    // HUD
    x.fillStyle='#1D1A2F';x.fillRect(0,RO*TS,W,H-RO*TS);const hh=Math.floor(clock)%24,mm=Math.floor((clock%1)*6)*10;x.fillStyle='#FFD23F';x.font='800 16px Figtree, sans-serif';x.textAlign='left';x.fillText('💰 $'+Math.round(money)+'   Day '+day+'  '+String(hh).padStart(2,'0')+':'+String(mm).padStart(2,'0')+'  '+(weather==='rain'?'🌧️':'☀️'),10,RO*TS+24);
    x.fillStyle='#FFFDF6';x.font='600 12px Figtree, sans-serif';const invS=Object.entries(inv).filter(([k,n])=>n>0).map(([k,n])=>n+' '+(CROP.find(q=>q.k===k)||{n:{egg:'egg',gegg:'golden egg',milk:'milk',lmilk:'large milk'}[k]}).n).join(', ');x.fillText('Bag: '+(invS||'empty')+(shipped.length?'   · in bin: $'+shipped.reduce((a,b)=>a+b,0):''),10,RO*TS+46);
    TOOLS.forEach(([k,ic,n],i)=>{const bx0=430+i*66;ui.button(bx0,RO*TS+6,60,48,'',()=>{if(tool===2&&i===2)seedSel=(seedSel+1)%CROP.length;tool=i},{on:tool===i});x.font='22px sans-serif';x.textAlign='center';x.fillText(ic,bx0+30,RO*TS+34);x.fillStyle='#1D1A2F';x.font='800 10px Figtree';x.fillText(String(i+1),bx0+8,RO*TS+18);if(i===1){x.fillText(can+'/'+canCap,bx0+30,RO*TS+50)}if(i===2){x.fillText(CROP[seedSel].n.slice(0,6)+' '+seeds[seedSel],bx0+30,RO*TS+50)}x.fillStyle='#FFFDF6'});
    ui.button(W-160,RO*TS+8,70,44,'🛒 Shop',()=>{shopOpen=true},{font:'800 12px Figtree, sans-serif'});ui.button(W-84,RO*TS+8,76,44,'😴 Sleep',()=>sleep(),{font:'800 12px Figtree, sans-serif'});
    if(msgT>0){msgT-=dt;x.font='800 15px Figtree, sans-serif';const tw=Math.min(W-20,x.measureText(msg).width+30);x.fillStyle='rgba(29,26,47,.9)';x.beginPath();x.roundRect(W/2-tw/2,10,tw,34,10);x.fill();x.fillStyle='#FFD23F';x.textAlign='center';x.fillText(msg,W/2,32)}
    if(shopOpen){x.fillStyle='rgba(29,26,47,.55)';x.fillRect(0,0,W,H);x.fillStyle='#FFFDF6';x.strokeStyle='#1D1A2F';x.lineWidth=3;x.beginPath();x.roundRect(170,60,620,470,18);x.fill();x.stroke();x.fillStyle='#1D1A2F';x.font='30px "Bagel Fat One", sans-serif';x.textAlign='center';x.fillText('🌱 Seed & Animal Shop',480,104);x.font='700 14px Figtree, sans-serif';x.fillText('You have $'+Math.round(money)+'. Seeds come in packs of 5.',480,130);
      CROP.forEach((cr,i)=>{const bx0=190+(i%3)*196,by0=150+Math.floor(i/3)*110;ui.button(bx0,by0,184,98,'',()=>{if(money<cr.seed*5){say('Not enough money');return}money-=cr.seed*5;seeds[i]+=5;seedSel=i;beep(880,.08,'triangle',.05)});x.fillStyle='#1D1A2F';x.font='800 15px Figtree, sans-serif';x.fillText(cr.n+' ×5',bx0+92,by0+26);x.font='600 12px Figtree, sans-serif';x.fillText('$'+cr.seed*5+' · '+cr.days+' days'+(cr.regrow?' · regrows':''),bx0+92,by0+48);x.fillText('sells $'+cr.sell+' each · have '+seeds[i],bx0+92,by0+68);x.fillStyle=cr.col;x.beginPath();x.arc(bx0+92,by0+84,7,0,7);x.fill()});
      const nC=animals.filter(a=>a.k==='chicken').length,nW=animals.filter(a=>a.k==='cow').length;
      ui.button(190,380,184,70,'🐔 Chicken $300 ('+nC+'/6)',()=>{if(nC>=6){say('Coop is full');return}if(money<300){say('Not enough money');return}money-=300;addAnimal('chicken');save()},{font:'800 13px Figtree, sans-serif'});ui.button(386,380,184,70,'🐄 Cow $1000 ('+nW+'/3)',()=>{if(nW>=3){say('Barn is full');return}if(money<1000){say('Not enough money');return}money-=1000;addAnimal('cow');save()},{font:'800 13px Figtree, sans-serif'});
      ui.button(582,380,184,70,canCap<40?'💧 Bigger can $600':'💧 Can maxed',()=>{if(canCap>=40)return;if(money<600){say('Not enough money');return}money-=600;canCap=40;can=40;save()},{font:'800 13px Figtree, sans-serif',dis:canCap>=40});
      x.fillStyle='#5A5470';x.font='600 12px Figtree, sans-serif';x.fillText('Animals give eggs or milk every morning. Pet them daily (✋) for golden eggs and large milk.',480,478);ui.button(400,488,160,36,'Close',()=>{shopOpen=false},{col:'#FFD23F'})}
    c.stat('Farm Life · Day '+day+' · $'+Math.round(money))});
  say('Welcome to your farm! Grab the hoe (1) and till the dashed plot.');return()=>save()}});

/* ---------- Lemonade Tycoon (business sim) ---------- */
G.push({id:'sim_lemon',name:'Lemonade Tycoon',kind:'sim',wide:true,tint:'#FFE27A',blurb:'Run a lemonade stand. Read the weather, buy supplies, tune your recipe and price, and build a reputation that brings the whole town to your stand.',fmt:b=>'$'+b,
art:'<rect width="120" height="72" fill="#8fd3ff"/><rect y="52" width="120" height="20" fill="#d8d1c6"/><rect x="34" y="30" width="52" height="26" fill="#FFE27A" stroke="#1D1A2F" stroke-width="2.5"/><path d="M28 30l6-14h52l6 14z" fill="#FF8FB1" stroke="#1D1A2F" stroke-width="2.5"/><path d="M40 16l-2 14M52 16v14M64 16v14M76 16l2 14" stroke="#fff" stroke-width="4"/><rect x="50" y="36" width="10" height="14" rx="2" fill="#fff8b0" stroke="#1D1A2F" stroke-width="2"/><circle cx="100" cy="14" r="8" fill="#FFD23F"/>',
run(root,c){const W=960,H=620;const[cv,x]=mk(W,H,'width:100%;touch-action:none');root.append(cv,el('p',{class:'hint'},'Each morning check the forecast, buy supplies and set your recipe and price. Hot days want more ice and will pay more. Happy customers raise your reputation, which brings more people tomorrow.'));
  const ui=cookUI(cv,c);
  const sv=S.get('lemon_save',null);let day=1,money=20,rep=.3,inv={lem:0,sug:0,ice:0,cup:0},rec={L:4,S:4,I:3,P:.5},up={sign:0,cool:0,fancy:0},best=0,state='prep',fc=null,sim=null,report=null,t=0;
  if(sv){try{({day,money,rep,inv,rec,up}=Object.assign({day,money,rep,inv,rec,up},sv))}catch(e){}}
  function save(){S.set('lemon_save',{day,money,rep,inv,rec,up})}
  const WX=[['☀️','Sunny',1],['⛅','Cloudy',.75],['🌧️','Rainy',.35],['🔥','Hot & hazy',1.15]];
  function forecast(){const w=Math.random()<.18?2:Math.random()<.3?1:Math.random()<.3?3:0;const temp=Math.round(w===3?88+Math.random()*12:w===2?52+Math.random()*14:w===1?62+Math.random()*16:70+Math.random()*20);return{w,temp}}
  fc=forecast();
  const PACK={lem:[12,4,'🍋 Lemons'],sug:[10,3,'🧂 Sugar'],ice:[60,2.5,'🧊 Ice'],cup:[25,2,'🥤 Cups']};
  const ideal=()=>({L:4+(fc.temp>85?1:0),S:4-(fc.temp>85?0:0),I:Math.round(clamp(fc.temp/20,2,6))});
  function quality(){const id=ideal();return clamp(1-(Math.abs(rec.L-id.L)*.13+Math.abs(rec.S-id.S)*.13+Math.abs(rec.I-id.I)*.09),0,1)}
  function startDay(){const base=(30+fc.temp*.9)*WX[fc.w][2]*(.55+rep*.9)*(1+up.sign*.18);sim={clock:9,n:Math.round(base*(.85+Math.random()*.3)),spawned:0,peds:[],sold:0,rev:0,pitcher:0,fb:{great:0,ok:0,sour:0,sweet:0,ice:0,price:0,out:0},repD:0,speed:1};state='sell';beep(660,.08,'triangle',.05)}
  function serve(p){const id=ideal(),q=quality();const tol=(.22+fc.temp/100*.95)*(.55+q*.7)*(1+up.fancy*.1);if(rec.P>tol*(.8+Math.random()*.45)){sim.fb.price++;p.bub='💸';return}
    if(sim.pitcher<=0){if(inv.lem<rec.L||inv.sug<rec.S){sim.fb.out++;p.bub='😢';return}inv.lem-=rec.L;inv.sug-=rec.S;sim.pitcher=10}if(inv.cup<1||inv.ice<rec.I){sim.fb.out++;p.bub='😢';return}
    inv.cup--;inv.ice-=rec.I;sim.pitcher--;sim.sold++;sim.rev+=rec.P;money+=rec.P;beep(900+Math.random()*200,.04,'triangle',.03);
    const dL=rec.L-id.L,dS=rec.S-id.S,dI=rec.I-id.I;let fb='great';if(Math.abs(dI)>=2)fb='ice';else if(dL-dS>=2)fb='sour';else if(dS-dL>=2)fb='sweet';else if(q<.75)fb='ok';sim.fb[fb]++;p.bub={great:'😋',ok:'🙂',sour:'😖',sweet:'🤢',ice:dI>0?'🥶':'🥵'}[fb];const value=q-rec.P/(tol*1.3);sim.repD+=value>.25?.012:value>0?.004:-.01}
  function endDay(){const melt=up.cool?.5:1;const iceLost=Math.round(inv.ice*melt);inv.ice-=iceLost;rep=clamp(rep+sim.repD,0,1);report={sold:sim.sold,rev:sim.rev,fb:sim.fb,iceLost,rep};day++;best=Math.max(best,money);c.best(Math.round(money*100)/100);fc=forecast();state='report';save()}
  const PEDS=['🧑','👩','👨','🧒','👧','👦','👵','👴','🧔','👱','👮','👷','🧕'];
  c.loop(ms=>{const dt=Math.min(.05,ms/1000);t+=dt;ui.frame();
    // scene
    const sky=x.createLinearGradient(0,0,0,360);const wc=state==='sell'?fc.w:0;sky.addColorStop(0,wc===2?'#7a8aa8':wc===1?'#a9c7e8':wc===3?'#ffcf8a':'#7fc8f8');sky.addColorStop(1,wc===2?'#b8c2d4':'#dff2ff');x.fillStyle=sky;x.fillRect(0,0,W,360);
    if(wc!==2){x.fillStyle=wc===3?'#FF9F43':'#FFD23F';x.beginPath();x.arc(820,80,40,0,7);x.fill()}x.fillStyle='rgba(255,255,255,.85)';[[120,70],[420,50],[650,110]].forEach(([cx,cy],i)=>{const o=(t*8*(i+1))%1100-100;[[0,0,24],[26,-8,28],[52,0,20]].forEach(([a,b,r])=>{x.beginPath();x.arc((cx+o)%1060-50+a,cy+b,r,0,7);x.fill()})});
    x.fillStyle='#b9c3de';for(let i=0;i<9;i++){const bh=80+((i*47)%90);x.fillRect(i*110,300-bh,96,bh)}x.fillStyle='#78b04a';x.fillRect(0,300,W,60);x.fillStyle='#d8d1c6';x.fillRect(0,360,W,70);x.fillStyle='#bdb5a8';for(let i=0;i<W;i+=60)x.fillRect(i,360,2,70);x.fillStyle='#5A5470';x.fillRect(0,430,W,H-430);x.fillStyle='#FFD23F';for(let i=20;i<W;i+=80)x.fillRect(i,520,40,6);
    // stand
    const sx=380,sy=330;x.fillStyle='#FFE27A';x.strokeStyle='#1D1A2F';x.lineWidth=3;x.fillRect(sx,sy,200,70);x.strokeRect(sx,sy,200,70);x.fillStyle='#8a5a2b';x.fillRect(sx+10,sy-80,8,80);x.fillRect(sx+182,sy-80,8,80);
    for(let k=0;k<8;k++){x.fillStyle=k%2?'#FFFDF6':(up.fancy?'#B9A7FF':'#FF8FB1');x.beginPath();x.moveTo(sx-10+k*27.5,sy-80);x.lineTo(sx+17.5+k*27.5,sy-80);x.lineTo(sx+22+k*27.5,sy-110);x.lineTo(sx-5+k*27.5,sy-110);x.fill()}x.strokeRect(sx-10,sy-110,220,30);
    x.fillStyle='#1D1A2F';x.font='26px "Bagel Fat One", sans-serif';x.textAlign='center';x.fillText('LEMONADE',sx+100,sy+34);x.font='800 15px Figtree, sans-serif';x.fillText('$'+rec.P.toFixed(2)+' a cup',sx+100,sy+58);
    x.fillStyle='rgba(255,248,176,.9)';x.fillRect(sx+140,sy-40,30,40);x.strokeRect(sx+140,sy-40,30,40);x.fillStyle='#FFD23F';x.beginPath();x.arc(sx+40,sy-10,10,0,7);x.arc(sx+60,sy-12,10,0,7);x.fill();x.stroke();
    if(up.sign){x.fillStyle='#FFFDF6';x.fillRect(sx+230,sy-20,90,60);x.strokeRect(sx+230,sy-20,90,60);x.fillStyle='#F2352A';x.font='800 14px Figtree';x.fillText('ICE COLD!',sx+275,sy+6);x.fillText('🍋🍋🍋',sx+275,sy+28);x.fillStyle='#8a5a2b';x.fillRect(sx+272,sy+40,6,40)}
    if(up.cool){x.fillStyle='#7FC8F8';x.fillRect(sx-60,sy+20,50,50);x.strokeRect(sx-60,sy+20,50,50);x.fillStyle='#fff';x.fillRect(sx-60,sy+20,50,10)}
    x.fillStyle='#1D1A2F';x.fillRect(0,0,W,44);x.fillStyle='#FFD23F';x.font='800 17px Figtree, sans-serif';x.textAlign='left';x.fillText('Day '+day+' · 💰 $'+money.toFixed(2)+' · ⭐ Reputation '+Math.round(rep*100)+'%',12,28);x.textAlign='right';x.fillStyle='#FFFDF6';x.fillText('🍋 '+inv.lem+'  🧂 '+inv.sug+'  🧊 '+inv.ice+'  🥤 '+inv.cup,W-12,28);
    if(state==='sell'){const s=sim;s.clock+=dt*s.speed*9/28;const prog=(s.clock-9)/9;while(s.spawned<s.n*Math.min(1,prog*1.05)){s.spawned++;const dir=Math.random()<.5?1:-1;s.peds.push({x:dir>0?-30:W+30,dir,y:400+Math.random()*24,f:pick(PEDS),sp:40+Math.random()*40,st:'walk',bt:0})}
      s.peds.forEach(p=>{if(p.st==='walk'){p.x+=p.dir*p.sp*dt*s.speed;if(!p.dec&&Math.abs(p.x-(sx+100))<30){p.dec=true;if(Math.random()<.7+rep*.3){p.st='buy';p.bt=.6;serve(p)}}}else{p.bt-=dt*s.speed;if(p.bt<=0){p.st='walk'}}});s.peds=s.peds.filter(p=>p.x>-60&&p.x<W+60);
      s.peds.forEach(p=>{x.font='38px sans-serif';x.textAlign='center';x.fillText(p.f,p.x,p.y+Math.abs(Math.sin(t*8+p.x))*3);if(p.bub){x.fillStyle='#FFFDF6';x.strokeStyle='#1D1A2F';x.lineWidth=2;x.beginPath();x.arc(p.x+18,p.y-46,15,0,7);x.fill();x.stroke();x.font='18px sans-serif';x.fillStyle='#1D1A2F';x.fillText(p.bub,p.x+18,p.y-40)}});
      x.fillStyle='rgba(29,26,47,.85)';x.beginPath();x.roundRect(16,56,260,120,12);x.fill();x.fillStyle='#FFFDF6';x.font='800 16px Figtree, sans-serif';x.textAlign='left';const hh=Math.floor(s.clock),mm=Math.floor((s.clock%1)*60);x.fillText('🕘 '+(hh>12?hh-12:hh)+':'+String(mm).padStart(2,'0')+(hh>=12?' pm':' am')+'  '+WX[fc.w][0]+' '+fc.temp+'°F',28,82);x.font='600 14px Figtree, sans-serif';x.fillText('Cups sold: '+s.sold+' · $'+s.rev.toFixed(2),28,106);x.fillText('Pitcher: '+s.pitcher+'/10 cups left',28,128);if(inv.cup<1||inv.ice<rec.I||(s.pitcher<=0&&(inv.lem<rec.L||inv.sug<rec.S))){x.fillStyle='#FF8FB1';x.fillText('SOLD OUT: buy more tomorrow',28,152)}
      ui.button(W-200,60,180,44,s.speed>1?'⏩ Fast ×4':'▶ Normal speed',()=>{s.speed=s.speed>1?1:4},{font:'800 14px Figtree, sans-serif'});
      if(s.clock>=18&&!s.peds.some(p=>p.st==='buy'))endDay();return}
    x.fillStyle='rgba(29,26,47,.5)';x.fillRect(0,44,W,H-44);x.fillStyle='#FFFDF6';x.strokeStyle='#1D1A2F';x.lineWidth=3;x.beginPath();x.roundRect(60,60,840,540,18);x.fill();x.stroke();x.fillStyle='#1D1A2F';x.textAlign='center';
    if(state==='report'){const r=report;x.font='34px "Bagel Fat One", sans-serif';x.fillText('End of day '+(day-1),480,110);x.font='700 18px Figtree, sans-serif';x.fillText('Sold '+r.sold+' cups for $'+r.rev.toFixed(2)+(r.iceLost?' · '+r.iceLost+' ice melted':''),480,150);
      const fb=r.fb;const lines=[['😋','Loved it',fb.great],['🙂','It was OK',fb.ok],['😖','Too sour',fb.sour],['🤢','Too sweet',fb.sweet],['🧊','Wrong amount of ice',fb.ice],['💸','Too expensive',fb.price],['😢','You were sold out',fb.out]].filter(l=>l[2]);x.font='600 17px Figtree, sans-serif';lines.forEach(([e,n,v],i)=>x.fillText(e+' '+n+': '+v,480,196+i*30));
      x.font='800 18px Figtree, sans-serif';x.fillText('⭐ Reputation now '+Math.round(rep*100)+'%',480,440);ui.button(380,480,200,56,'Next morning ▶',()=>{state='prep'},{col:'#FFD23F'});return}
    // prep screen
    x.font='30px "Bagel Fat One", sans-serif';x.fillText('Morning of day '+day,480,104);x.font='800 18px Figtree, sans-serif';x.fillText('Forecast: '+WX[fc.w][0]+' '+WX[fc.w][1]+', '+fc.temp+'°F',480,134);
    x.textAlign='left';x.font='800 16px Figtree, sans-serif';x.fillText('🛒 Buy supplies',90,176);Object.entries(PACK).forEach(([k,[n,cost,label]],i)=>{const y=190+i*56;x.fillStyle='#1D1A2F';x.font='700 15px Figtree, sans-serif';x.textAlign='left';x.fillText(label+' (have '+inv[k]+')',90,y+30);ui.button(290,y,130,44,'+'+n+' for $'+cost.toFixed(2),()=>{if(money<cost){beep(150,.1,'square',.04);return}money-=cost;inv[k]+=n;beep(700,.05,'triangle',.04)},{font:'800 13px Figtree, sans-serif',dis:money<cost})});
    x.fillStyle='#1D1A2F';x.font='800 16px Figtree, sans-serif';x.textAlign='left';x.fillText('🍹 Recipe & price',480,176);[['L','Lemons per pitcher',1,9,1],['S','Sugar per pitcher',1,9,1],['I','Ice cubes per cup',0,8,1],['P','Price per cup',.05,3,.05]].forEach(([k,label,a,b,st],i)=>{const y=190+i*56;x.fillStyle='#1D1A2F';x.font='700 15px Figtree, sans-serif';x.textAlign='left';x.fillText(label,480,y+20);x.font='900 20px Figtree, sans-serif';x.fillText(k==='P'?'$'+rec.P.toFixed(2):String(rec[k]),480,y+44);ui.button(700,y+4,50,40,'−',()=>{rec[k]=Math.round(clamp(rec[k]-st,a,b)*100)/100});ui.button(760,y+4,50,40,'+',()=>{rec[k]=Math.round(clamp(rec[k]+st,a,b)*100)/100})});
    x.font='800 16px Figtree, sans-serif';x.textAlign='left';x.fillText('🏗️ Upgrades',90,440);[['sign','Big sign · more walk-ups',15],['cool','Cooler · ice melts half as fast',25],['fancy','Fancy stand · people pay more',50]].forEach(([k,label,cost],i)=>{ui.button(90+i*190,452,180,52,up[k]?'✓ '+label.split(' · ')[0]:label.split(' · ')[0]+' $'+cost,()=>{if(up[k]||money<cost)return;money-=cost;up[k]=1;beep(880,.1,'triangle',.05)},{font:'800 13px Figtree, sans-serif',dis:!!up[k]||money<cost,on:!!up[k]});x.fillStyle='#5A5470';x.font='600 11px Figtree, sans-serif';x.textAlign='left';x.fillText(label.split(' · ')[1],96+i*190,518)});
    x.fillStyle='#5A5470';x.font='600 13px Figtree, sans-serif';x.textAlign='left';x.fillText('One pitcher = 10 cups. Hot days: more ice, customers pay more. Rainy days: few customers.',90,556);
    ui.button(660,520,220,64,'Open the stand ▶',()=>{if(inv.cup<1){beep(150,.1,'square',.04);return}startDay()},{col:'#2BB673',font:'800 18px Figtree, sans-serif'});
    c.stat('Lemonade Tycoon · Day '+day+' · $'+money.toFixed(2))});
  return()=>save()}});

/* ---------- Tiny Town (city builder sim) ---------- */
G.push({id:'sim_town',name:'Tiny Town',kind:'sim',wide:true,tint:'#7FC8F8',blurb:'Build a city from an empty valley. Lay roads, zone homes, shops and factories, keep everyone powered, watered and happy, and grow from a village into a metropolis.',fmt:b=>b+' people',
art:'<rect width="120" height="72" fill="#8fd36b"/><path d="M0 40h120M58 0v72" stroke="#5A5470" stroke-width="8"/><rect x="10" y="10" width="16" height="14" fill="#FFFDF6" stroke="#1D1A2F" stroke-width="2"/><path d="M8 12l10-8 10 8z" fill="#F2352A" stroke="#1D1A2F" stroke-width="2"/><rect x="70" y="6" width="18" height="26" fill="#7FC8F8" stroke="#1D1A2F" stroke-width="2"/><rect x="92" y="14" width="18" height="18" fill="#8c86a3" stroke="#1D1A2F" stroke-width="2"/><rect x="100" y="4" width="5" height="12" fill="#5A5470"/><rect x="72" y="48" width="36" height="18" fill="#2BB673" stroke="#1D1A2F" stroke-width="2"/><rect x="10" y="48" width="18" height="18" fill="#FFD23F" stroke="#1D1A2F" stroke-width="2"/>',
run(root,c){const W=960,H=620,TS=32,CO=30,RO=17,TB=RO*TS;const[cv,x]=mk(W,H,'width:100%;touch-action:none');root.append(cv,el('p',{class:'hint'},'Pick a tool, then tap or drag on the map. Homes, shops and factories only grow next to a road with power and water. Parks and schools make people happy, factories pollute. Taxes come in every month.'));
  const ui=cookUI(cv,c);
  const TOOLS=[['road','🛣️','Road',10],['res','🏠','Homes',30],['com','🏪','Shops',40],['ind','🏭','Factory',60],['park','🌳','Park',80],['power','⚡','Power plant',600],['water','💧','Water tower',300],['school','🏫','School',700,150],['stadium','🏟️','Stadium',3000,1500],['bull','🧨','Bulldoze',5]];
  // tiles: {t:'grass'|'tree'|'river'|tool k, lv, age}
  let g=[],money=2500,month=1,pop=0,jobs=0,happy=.7,tool=0,overlay=null,msg='',msgT=0,tick=0,cars=[],smoke=[],drag=null,milestone=0,t=0;
  const MIL=[[100,'Village'],[500,'Town'],[1500,'City'],[4000,'Metropolis'],[8000,'Megalopolis']];
  function fresh(){g=[];for(let j=0;j<RO;j++){g.push([]);for(let i=0;i<CO;i++)g[j].push({t:'grass',lv:0})}let rx=19;for(let j=0;j<RO;j++){rx+=Math.round(Math.random()*2-1)*(j%3===0?1:0);rx=clamp(rx,16,24);g[j][rx].t='river';g[j][rx+1].t='river'}for(let k=0;k<70;k++){const i=rand(CO),j=rand(RO);if(g[j][i].t==='grass')g[j][i].t='tree'}for(let i=0;i<CO;i++)if(g[8][i].t!=='river')g[8][i]={t:'road',lv:0};else g[8][i]={t:'road',lv:0,bridge:1}}
  const sv=S.get('town_save',null);if(sv&&sv.g){try{g=sv.g;money=sv.m;month=sv.mo;milestone=sv.ms||0}catch(e){fresh()}}else fresh();
  function save(){S.set('town_save',{g,m:money,mo:month,ms:milestone});c.best(pop)}
  const at=(i,j)=>i>=0&&j>=0&&i<CO&&j<RO?g[j][i]:null;const nb=(i,j)=>[[1,0],[-1,0],[0,1],[0,-1]].map(([a,b])=>at(i+a,j+b));
  const near=(i,j,type,r)=>{for(let b=-r;b<=r;b++)for(let a=-r;a<=r;a++){const q=at(i+a,j+b);if(q&&q.t===type&&(a*a+b*b)<=r*r)return true}return false};
  const powered=(i,j)=>near(i,j,'power',9),watered=(i,j)=>near(i,j,'water',7);
  const say=m=>{msg=m;msgT=2.6};
  function place(i,j){const q=at(i,j);if(!q)return;const[k,,label,cost,need]=TOOLS[tool];if(need&&pop<need){say(label+' unlocks at '+need+' people');return}
    if(k==='bull'){if(q.t==='grass'||q.t==='river')return;if(money<cost)return say('Not enough money');money-=cost;g[j][i]={t:q.t==='road'&&q.bridge?'river':'grass',lv:0};noise(.2,'lowpass',300,.15);return}
    if(q.t===k)return;if(q.t==='river'&&k!=='road')return say('Only roads (bridges) can go on water');if(q.t!=='grass'&&q.t!=='tree'&&q.t!=='river')return say('Bulldoze it first');const cc=cost+(q.t==='tree'?5:0)+(q.t==='river'?40:0);if(money<cc)return say('Not enough money');money-=cc;g[j][i]={t:k,lv:0,age:0,bridge:q.t==='river'?1:0};beep(500+tool*40,.04,'triangle',.03)}
  const pH=[0,8,20,45],jC=[0,10,25,45],jI=[0,20,40,70];
  function simulate(){let P=0,Jc=0,Ji=0,hp=0,hn=0;for(let j=0;j<RO;j++)for(let i=0;i<CO;i++){const q=g[j][i];if(q.t==='res'){P+=pH[q.lv]}else if(q.t==='com')Jc+=jC[q.lv];else if(q.t==='ind')Ji+=jI[q.lv]}
    const dR=(Jc+Ji)*1.1+60-P,dC=P*.35-Jc+10,dI=P*.45-Ji+15;
    for(let j=0;j<RO;j++)for(let i=0;i<CO;i++){const q=g[j][i];if(q.t!=='res'&&q.t!=='com'&&q.t!=='ind')continue;q.age=(q.age||0)+1;const road=nb(i,j).some(n=>n&&n.t==='road');const pw=powered(i,j),wa=watered(i,j);q.np=!pw;q.nw=!wa;q.nr=!road;if(!road||!pw||!wa){if(q.lv>0&&Math.random()<.08)q.lv--;continue}
      let hap=.6;if(q.t==='res'){if(near(i,j,'park',4))hap+=.2;if(near(i,j,'school',6))hap+=.15;if(near(i,j,'stadium',8))hap+=.15;if(near(i,j,'ind',3))hap-=.35;hp+=hap*pH[q.lv];hn+=pH[q.lv];q.hap=hap}
      const dem=q.t==='res'?dR:q.t==='com'?dC:dI;const cap=q.t==='res'?(hap>.75?3:hap>.5?2:1):3;if(dem>0&&q.lv<cap&&Math.random()<.18)q.lv++;else if(dem<-40&&q.lv>1&&Math.random()<.05)q.lv--;if(q.t==='res'&&hap<.4&&q.lv>1&&Math.random()<.1)q.lv--}
    pop=P;jobs=Jc+Ji;happy=hn?hp/hn:.7;
    // monthly budget
    tick++;if(tick%5===0){month++;let up=0;for(const row of g)for(const q of row){up+={road:.2,power:25,water:12,park:3,school:20,stadium:60}[q.t]||0}const tax=P*1.1+Jc*.5+Ji*.6;money+=tax-up;last={tax,up};if(money<-2000){say('You’re bankrupt! Town loans you $3000.');money+=3000}save()}
    while(milestone<MIL.length&&P>=MIL[milestone][0]){say('🎉 You are now a '+MIL[milestone][1]+'! +$'+(1000*(milestone+1)));money+=1000*(milestone+1);milestone++;beep(660,.15,'triangle',.06);c.after(()=>beep(880,.2,'triangle',.06),150)}}
  let last={tax:0,up:0};let simT=0;
  // input
  function tileAt(p){return[Math.floor(p.x/TS),Math.floor(p.y/TS)]}
  ui.onDown=p=>{if(p.y>=TB)return;const[i,j]=tileAt(p);drag={last:key(i,j)};place(i,j)};ui.onMove=p=>{ui.hover=p.y<TB?tileAt(p):null;if(drag&&ui.down&&p.y<TB){const[i,j]=tileAt(p);const k=key(i,j);if(k!==drag.last){drag.last=k;place(i,j)}}};ui.onUp=()=>{drag=null};const key=(i,j)=>i+','+j;
  c.on(document,'keydown',e=>{const k=e.key;if(k>='0'&&k<='9'){const n=k==='0'?9:+k-1;if(TOOLS[n])tool=n}});
  // drawing
  const ROOF=['#F2352A','#2d6fd6','#8a5a2b','#B9A7FF','#2BB673','#FF9F43'];
  function drawTile(i,j,q){const X=i*TS,Y=j*TS;const h=(i*31+j*17)%7;
    if(q.t==='river'||q.bridge){x.fillStyle='#4DA3E0';x.fillRect(X,Y,TS,TS);x.strokeStyle='rgba(255,255,255,.45)';x.lineWidth=2;const o=Math.sin(t*2+i+j)*3;x.beginPath();x.moveTo(X+6+o,Y+10);x.lineTo(X+16+o,Y+10);x.moveTo(X+14-o,Y+22);x.lineTo(X+26-o,Y+22);x.stroke();if(!q.bridge)return}
    else{x.fillStyle=(i+j)%2?'#8fd36b':'#88cc64';x.fillRect(X,Y,TS,TS);if(q.t==='grass'){if(h===2){x.fillStyle='rgba(40,110,30,.3)';x.fillRect(X+8,Y+12,2,5);x.fillRect(X+20,Y+20,2,5)}return}}
    if(q.t==='tree'){x.fillStyle='#2e8b3a';x.strokeStyle='#1D1A2F';x.lineWidth=1.5;x.beginPath();x.arc(X+16+(h-3),Y+15,10,0,7);x.fill();x.stroke();x.fillStyle='rgba(255,255,255,.2)';x.beginPath();x.arc(X+12+(h-3),Y+11,3,0,7);x.fill();return}
    if(q.t==='road'){x.fillStyle=q.bridge?'#b89a6a':'#5A5470';const n=nb(i,j).map(z=>z&&z.t==='road');x.fillRect(X+6,Y+6,20,20);if(n[0])x.fillRect(X+16,Y+6,16,20);if(n[1])x.fillRect(X,Y+6,16,20);if(n[2])x.fillRect(X+6,Y+16,20,16);if(n[3])x.fillRect(X+6,Y,20,16);x.fillStyle='#FFD23F';if(n[0]&&n[1]&&!n[2]&&!n[3])x.fillRect(X+4,Y+15,8,2),x.fillRect(X+20,Y+15,8,2);if(n[2]&&n[3]&&!n[0]&&!n[1])x.fillRect(X+15,Y+4,2,8),x.fillRect(X+15,Y+20,2,8);return}
    if(q.t==='park'){x.fillStyle='#5cc26a';x.fillRect(X+1,Y+1,TS-2,TS-2);x.fillStyle='#2e8b3a';[[9,10],[22,20],[10,24]].forEach(([a,b])=>{x.beginPath();x.arc(X+a,Y+b,6,0,7);x.fill()});x.fillStyle='#4DA3E0';x.beginPath();x.arc(X+22,Y+9,4,0,7);x.fill();return}
    if(q.t==='power'){x.fillStyle='#8c86a3';x.strokeStyle='#1D1A2F';x.lineWidth=2;x.fillRect(X+3,Y+10,26,20);x.strokeRect(X+3,Y+10,26,20);x.fillStyle='#5A5470';x.fillRect(X+20,Y+1,6,12);x.fillStyle='#FFD23F';x.font='16px sans-serif';x.textAlign='center';x.fillText('⚡',X+12,Y+26);return}
    if(q.t==='water'){x.fillStyle='#8a5a2b';x.fillRect(X+10,Y+16,3,14);x.fillRect(X+19,Y+16,3,14);x.fillStyle='#7FC8F8';x.strokeStyle='#1D1A2F';x.lineWidth=2;x.beginPath();x.ellipse(X+16,Y+12,11,9,0,0,7);x.fill();x.stroke();return}
    if(q.t==='school'){x.fillStyle='#e0a458';x.strokeStyle='#1D1A2F';x.lineWidth=2;x.fillRect(X+2,Y+8,28,22);x.strokeRect(X+2,Y+8,28,22);x.fillStyle='#F2352A';x.beginPath();x.moveTo(X,Y+9);x.lineTo(X+16,Y+1);x.lineTo(X+32,Y+9);x.fill();x.stroke();x.fillStyle='#fff';x.font='12px sans-serif';x.textAlign='center';x.fillText('🏫',X+16,Y+25);return}
    if(q.t==='stadium'){x.fillStyle='#d8d4e4';x.strokeStyle='#1D1A2F';x.lineWidth=2;x.beginPath();x.ellipse(X+16,Y+16,15,13,0,0,7);x.fill();x.stroke();x.fillStyle='#2BB673';x.beginPath();x.ellipse(X+16,Y+16,9,7,0,0,7);x.fill();return}
    // zones
    const zc={res:'#FFE27A',com:'#9fd6ff',ind:'#d8c9a8'}[q.t];x.fillStyle=zc;x.fillRect(X+1,Y+1,TS-2,TS-2);x.strokeStyle='rgba(29,26,47,.25)';x.lineWidth=1;x.strokeRect(X+2.5,Y+2.5,TS-5,TS-5);x.strokeStyle='#1D1A2F';x.lineWidth=2;
    if(q.lv===0){x.fillStyle='rgba(29,26,47,.35)';x.font='800 13px Figtree';x.textAlign='center';x.fillText(q.t==='res'?'R':q.t==='com'?'C':'I',X+16,Y+21)}
    else if(q.t==='res'){if(q.lv===1){x.fillStyle='#FFFDF6';x.fillRect(X+8,Y+14,16,12);x.strokeRect(X+8,Y+14,16,12);x.fillStyle=ROOF[h%6];x.beginPath();x.moveTo(X+5,Y+15);x.lineTo(X+16,Y+5);x.lineTo(X+27,Y+15);x.fill();x.stroke()}else{const hh=q.lv===2?18:26;x.fillStyle=q.lv===2?'#FFFDF6':'#e8e1f0';x.fillRect(X+5,Y+30-hh,22,hh);x.strokeRect(X+5,Y+30-hh,22,hh);x.fillStyle='#7FC8F8';for(let r=0;r<hh/7-1;r++)for(let k=0;k<3;k++)x.fillRect(X+8+k*6,Y+33-hh+r*7,4,4);x.fillStyle=ROOF[h%6];x.fillRect(X+4,Y+28-hh,24,3)}}
    else if(q.t==='com'){const hh=[0,14,20,28][q.lv];x.fillStyle='#FFFDF6';x.fillRect(X+4,Y+30-hh,24,hh);x.strokeRect(X+4,Y+30-hh,24,hh);x.fillStyle='#2d6fd6';x.fillRect(X+4,Y+30-hh,24,4);x.fillStyle='#9fd6ff';x.fillRect(X+8,Y+22,16,6);if(q.lv===3){x.fillStyle='#7FC8F8';for(let r=0;r<3;r++)x.fillRect(X+8,Y+6+r*5,16,3)}}
    else{const hh=[0,14,18,22][q.lv];x.fillStyle='#8c86a3';x.fillRect(X+3,Y+30-hh,26,hh);x.strokeRect(X+3,Y+30-hh,26,hh);x.fillStyle='#5A5470';x.fillRect(X+21,Y+30-hh-8,5,9);if(q.lv>=2)x.fillRect(X+12,Y+30-hh-6,4,7);if(Math.random()<.02*q.lv)smoke.push({x:X+23,y:Y+30-hh-9,t:2})}
    if(q.nr||q.np||q.nw){x.font='11px sans-serif';x.textAlign='center';x.fillText(q.nr?'🚧':q.np?'⚡':'💧',X+26,Y+11)}}
  c.loop(ms=>{const dt=Math.min(.05,ms/1000);t+=dt;ui.frame();simT+=dt;if(simT>1){simT=0;simulate()}
    for(let j=0;j<RO;j++)for(let i=0;i<CO;i++)drawTile(i,j,g[j][i]);
    // coverage overlay
    const tk=TOOLS[tool][0];if(tk==='power'||tk==='water'){x.fillStyle=tk==='power'?'rgba(255,210,63,.18)':'rgba(77,163,224,.2)';for(let j=0;j<RO;j++)for(let i=0;i<CO;i++)if(tk==='power'?powered(i,j):watered(i,j))x.fillRect(i*TS,j*TS,TS,TS)}
    // traffic
    const want=Math.min(80,Math.floor(pop/25));if(cars.length<want&&Math.random()<.3){const rs=[];for(let j=0;j<RO;j++)for(let i=0;i<CO;i++)if(g[j][i].t==='road')rs.push([i,j]);if(rs.length){const[i,j]=pick(rs);cars.push({i,j,x:i+.5,y:j+.5,d:rand(4),col:pick(['#F2352A','#FFFDF6','#2d6fd6','#FFD23F','#2BB673'])})}}
    cars=cars.filter(q=>{const D=[[1,0],[-1,0],[0,1],[0,-1]];const[tx,ty]=[q.i+.5,q.j+.5];const dx=tx-q.x,dy=ty-q.y;if(Math.hypot(dx,dy)<.05){const opts=D.map((d,k)=>[d,k]).filter(([d,k])=>{const n=at(q.i+d[0],q.j+d[1]);return n&&n.t==='road'&&!(k===(q.d^1))});if(!opts.length){const back=D[q.d^1];if(at(q.i+back[0],q.j+back[1])&&at(q.i+back[0],q.j+back[1]).t==='road'){q.d^=1}else return false}else{const[d,k]=pick(opts);q.d=k}q.i+=D[q.d][0];q.j+=D[q.d][1]}else{const s=Math.min(Math.hypot(dx,dy),dt*2.2);q.x+=dx/Math.hypot(dx,dy)*s;q.y+=dy/Math.hypot(dx,dy)*s}
      if(!at(Math.floor(q.x),Math.floor(q.y))||at(Math.floor(q.x),Math.floor(q.y)).t!=='road')return false;const off=q.d<2?(q.d===0?4:-4):(q.d===2?-4:4);x.fillStyle=q.col;x.fillRect(q.x*TS-4+(q.d>1?off:0),q.y*TS-3+(q.d<2?off:0),q.d<2?8:6,q.d<2?6:8);return true});
    smoke=smoke.filter(s=>{s.t-=dt;s.y-=dt*10;s.x+=dt*4;x.fillStyle='rgba(120,120,130,'+(s.t*.25)+')';x.beginPath();x.arc(s.x,s.y,4+(2-s.t)*3,0,7);x.fill();return s.t>0});
    if(ui.hover){const[i,j]=ui.hover;x.strokeStyle='#FFFDF6';x.lineWidth=2;x.strokeRect(i*TS+1,j*TS+1,TS-2,TS-2)}
    // toolbar
    x.fillStyle='#1D1A2F';x.fillRect(0,TB,W,H-TB);TOOLS.forEach(([k,ic,n,cost,need],i)=>{const bx0=6+i*62;const lock=need&&pop<need;ui.button(bx0,TB+5,58,46,'',()=>{tool=i},{on:tool===i,dis:lock});x.font='20px sans-serif';x.textAlign='center';x.fillText(lock?'🔒':ic,bx0+29,TB+30);x.fillStyle='#1D1A2F';x.font='800 9px Figtree';x.fillText('$'+cost,bx0+29,TB+46);x.fillStyle='#FFFDF6'});
    x.fillStyle='#FFD23F';x.font='800 15px Figtree, sans-serif';x.textAlign='left';x.fillText('💰 $'+Math.round(money).toLocaleString()+'  👥 '+pop+'  💼 '+jobs+' jobs  😊 '+Math.round(happy*100)+'%',636,TB+24);x.fillStyle='#FFFDF6';x.font='600 12px Figtree, sans-serif';x.fillText('Month '+month+' · tax +$'+Math.round(last.tax)+' · upkeep −$'+Math.round(last.up)+(milestone<MIL.length?' · next: '+MIL[milestone][1]+' at '+MIL[milestone][0]:''),636,TB+44);
    x.fillText(TOOLS[tool][2]+(TOOLS[tool][4]&&pop<TOOLS[tool][4]?' (unlocks at '+TOOLS[tool][4]+' people)':''),636,TB+62);
    if(msgT>0){msgT-=dt;x.font='800 15px Figtree, sans-serif';const tw=x.measureText(msg).width+30;x.fillStyle='rgba(29,26,47,.9)';x.beginPath();x.roundRect(W/2-tw/2,10,tw,34,10);x.fill();x.fillStyle='#FFD23F';x.textAlign='center';x.fillText(msg,W/2,32)}
    c.stat('Tiny Town · '+pop+' people · $'+Math.round(money))});
  say(sv?'Welcome back, mayor!':'Build homes (2) next to the road, then a power plant (6) and water tower (7).');return()=>save()}});
