function toonCar(K,col,big){const{T,TM}=K;const g=new T.Group();const L=big?5.6:3.6,W=big?2.3:1.8;
  part(T,bx(T,W,big?1.7:.8,L),TM(col),0,big?1.3:.72,0,g);part(T,bx(T,W*.88,big?1.1:.62,L*(big?.3:.48)),TM(big?0x3a3552:0x9fd6ff),0,big?2.6:1.42,big?L*.33:-L*.06,g);
  if(big){part(T,bx(T,W+.04,.3,L*.6),TM(0xF2352A),0,1.3,-L*.15,g)}
  const wm=TM(0x1D1A2F);[[-1,-1],[1,-1],[-1,1],[1,1]].forEach(([a,b])=>{const w=part(T,cy(T,big?.5:.36,big?.5:.36,.32,10),wm,a*W/2,big?.5:.36,b*L*.32,g);w.rotation.z=Math.PI/2});
  K.ink(g,.05);[-1,1].forEach(a=>{part(T,bx(T,.34,.2,.06),TM(0xFFE27A),a*W*.3,big?1.4:.8,L/2+.02,g).userData.noInk=1});return g}
function wrapA(a){while(a>Math.PI)a-=Math.PI*2;while(a<-Math.PI)a+=Math.PI*2;return a}
G.push({id:'hs_speed',name:'Blur',kind:'hero',levels:true,wide:true,tint:'#F2352A',blurb:'3D super speed. Break the sound barrier in city traffic, freeze time, and stop the bomber Gridlock.',fmt:b=>b+' pts',
art:'<rect width="120" height="72" fill="#FFD23F"/><g stroke="#fff" stroke-width="4" stroke-linecap="round"><path d="M6 18H44M14 34H38M4 50H46"/></g><path d="M74 6L50 40h15L55 66l34-40H74l12-20z" fill="#F2352A" stroke="#1D1A2F" stroke-width="3.5" stroke-linejoin="round"/>',
run(root,c){return with3D(root,c,()=>{
  const st3=Stage3D(root,c,{lock:true,dragLook:true,fov:70,far:420,fireLabel:'DASH',altLabel:'BLUR',jumpLabel:'JUMP'});
  const M=[{name:'Rush Hour',brief:['Morning in Brightside City. Traffic is terrible, the coffee is late, and the bomber <b>Gridlock</b> just hid time bombs all over town.','Ten bombs, all over town. Nobody else is fast enough to reach them all. Luckily, you’re the fastest person alive.'],goal:'Defuse all 10 bombs before any timer hits zero. Just run through a bomb to defuse it.'},
    {name:'Everything Falls Down',brief:['Gridlock rigged the old Brightside Tower. It’s coming apart, and people are stuck in the streets underneath.','Scoop them up one at a time and run them to the green safe zone. Red shadows show where debris is about to land.'],goal:'Rescue 12 people before the clock runs out.'},
    {name:'Gridlock',brief:['Gridlock is getting away in an armoured truck, dropping oil slicks and traffic cones behind him.','Catch up and tag the truck five times to jam its wheels. Click (or DASH) when you’re right next to it.'],goal:'Tag the getaway truck 5 times before time runs out.'}];
  const K=heroKit(st3,c,{id:'hs_speed',issues:3,camDist:6.2,camH:1.9,fogNear:120,fogFar:260,finale:'Gridlock is stuck!',start:mi=>start(mi)});
  const{T,scene,camera,input,TM,cam,H,F}=K;
  K.sky('#7FC8F8','#FFE9B8');K.lights(0xffffff,0x8a7fb0,.7);
  const city=K.streamCity({blk:26,st:16,chunk:3,radius:2});let RM=null;city.update(0,0,true);cam.boxes=city.boxes;const CELL=city.cell;K.touchBtn('DRIFT','drift');
  const hero=K.fig({suit:0xF2352A,trim:0xFFD23F,bolt:1,skin:0xc68642,hair:0x1D1A2F});scene.add(hero);
  const trA=K.ribbon(0xFFD23F,70,.5),trB=K.ribbon(0xF2352A,56,.32),trC=K.ribbon(0xffffff,40,.14);
  const ghosts=[];const gG=bx(T,.8,2.1,.45);function ghost(){const m=new T.Mesh(gG,new T.MeshBasicMaterial({color:pick([0xF2352A,0xFFD23F,0xFF9F43]),transparent:true,opacity:.45,depthWrite:false}));m.position.set(P.x,P.y+1.05,P.z);m.rotation.y=P.face;scene.add(m);ghosts.push({m,l:.28})}
  const arcM=new T.LineBasicMaterial({color:0xFFE27A}),arcs=[];for(let k=0;k<3;k++){const g=new T.BufferGeometry();g.setAttribute('position',new T.BufferAttribute(new Float32Array(8*3),3));const l=new T.Line(g,arcM);l.frustumCulled=false;l.visible=false;scene.add(l);arcs.push(l)}
  const cone=new T.Mesh(new T.ConeGeometry(2.2,5,24,1,true),new T.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:0,side:T.DoubleSide,depthWrite:false}));cone.rotation.x=-Math.PI/2;const coneG=new T.Group();coneG.add(cone);scene.add(coneG);let mach=false;
  const hpB=H.bar('HEALTH','#2BB673'),blB=H.bar('BLUR','#7FC8F8'),spB=H.bar('SPEED','#F2352A');const rad=K.radar(200);
  const diff=c.pick(.75,1,1.25);const MAX=130,SOUND=85;
  const P={mv:0,drift:0,x:0,y:0,z:0,vy:0,face:0,spd:0,hp:100,blur:1,dash:0,dashCd:0,stun:0,spin:0,inv:0,ph:0,carry:null,tagCd:0};
  let cars=[],bombs=[],civs=[],debris=[],slicks=[],cones=[],truck=null,zone=null,tower=null,score=0,timeLeft=0,defused=0,rescued=0,tags=0,mi=0,ws=1,wclk=0,spawnT=0,made=0,dropT=0,coneT=0;
  const objs=[];const add=o=>{scene.add(o);objs.push(o);return o};
  function clearAll(){objs.forEach(o=>scene.remove(o));objs.length=0;cars=[];bombs=[];civs=[];debris=[];slicks=[];cones=[];truck=null;zone=null;if(tower){tower.m.position.x=tower.cx;tower.m.position.z=tower.cz;city.unpin(tower);tower.noSmash=false;tower=null}}
  const CARC=[0x7FC8F8,0xFF9F43,0x6EE7B7,0xB9A7FF,0xFF8FB1,0xffffff,0x2d6fd6,0xFFD23F];
  function addCar(){const m=add(toonCar(K,pick(CARC)));const car={m,fly:null,nm:0,sp:(8+Math.random()*6)*diff};respawnCar(car,true);cars.push(car);return car}
  function respawnCar(car,any){const a=Math.random()<.5?0:1,s=Math.random()<.5?-1:1;car.a=a;car.dir=s;const along=a===0?P.z:P.x,across=a===0?P.x:P.z;car.line=(Math.round(across/CELL)+rand(11)-5)*CELL+s*3.3;const ahead=a===0?Math.cos(P.face):Math.sin(P.face);car.u=along+(any?(Math.random()-.5)*500:(Math.sign(ahead)||1)*(200+Math.random()*80)*(Math.random()<.7?1:-1));placeCar(car)}
  function placeCar(car){if(car.a===0){car.m.position.set(car.line,0,car.u);car.m.rotation.set(0,car.dir>0?0:Math.PI,0)}else{car.m.position.set(car.u,0,car.line);car.m.rotation.set(0,car.dir>0?Math.PI/2:-Math.PI/2,0)}}
  function person(col){const f=K.fig({suit:col,trim:pick([0x1D1A2F,0x2d4fb3,0x5A5470]),skin:pick([0xf1c7a0,0xc68642,0x8d5524,0xe0ac69]),hair:pick([0x1D1A2F,0x8a5a2b,0xFFD23F,0xF2352A])});f.scale.setScalar(.82);return f}
  function beam(col,h){const g=new T.Group();const b=part(T,cy(T,1.1,1.1,h||70,12,true),new T.MeshBasicMaterial({color:col,transparent:true,opacity:.28,depthWrite:false}),0,(h||70)/2,0,g);b.userData.noInk=1;return g}
  function hurt(d,why){if(P.inv>0||P.dash>0||F.state!=='play')return;P.hp-=d*c.pick(.6,1,1.3);P.inv=.8;cam.shake=.7;H.tint('rgba(242,53,42,.4)',1);beep(140,.2,'sawtooth',.08);if(P.hp<=0){P.hp=0;F.lose(M,'Out cold!','Even the fastest person alive needs a nap sometimes. '+(why||'')+' Try again?')}}
  function start(i){mi=i;if(!RM)RM=heroRoam(K,{id:'hs_speed',city,pos:()=>({x:P.x,y:P.y,z:P.z}),fly:false,chase:48});RM.reset(i<0);clearAll();Object.assign(P,{mv:Math.PI,x:0,y:0,z:0,vy:0,face:Math.PI,spd:0,hp:100,blur:1,dash:0,dashCd:0,stun:0,spin:0,inv:1,carry:null,tagCd:0});cam.yaw=0;score=0;defused=0;rescued=0;tags=0;made=0;spawnT=0;dropT=0;coneT=0;trA.clear();trB.clear();trC.clear();mach=false;city.update(0,0,true);
    for(let k=0;k<46;k++)addCar();
    if(i===0){timeLeft=0;newBomb();newBomb();newBomb()}
    if(i===1){timeLeft=c.pick(100,80,65);let best=null;city.boxes.forEach(b=>{if(!b.tree&&Math.hypot(b.cx-60,b.cz-60)<130&&(!best||b.h>best.h))best=b});tower=best;best.noSmash=true;city.pin(best);const zp=city.node(-8,-8);zone=add(beam(0x2BB673,40));zone.position.set(zp.x,0,zp.z);const r=part(T,new T.CylinderGeometry(7,7,.2,32),new T.MeshBasicMaterial({color:0x6EE7B7,transparent:true,opacity:.6}),0,.2,0,zone);r.userData.noInk=1;
      for(let k=0;k<12;k++){let p;for(let tries=0;tries<40;tries++){p=city.streetPt(tower.cx,tower.cz,16,80);const d=Math.hypot(p.x-tower.cx,p.z-tower.cz);if(d>14&&d<85)break}const m=add(person(pick(CARC)));m.position.set(p.x,.3,p.z);civs.push({m,x:p.x,z:p.z,st:0,t:Math.random()*6})}}
    if(i===2){timeLeft=c.pick(140,115,95);const m=add(toonCar(K,0x3a3552,true));truck={m,i:3,j:3,ni:4,nj:3,u:0,sp:c.pick(52,62,72),hp:5,slow:0};const p=city.node(3,3);m.position.set(p.x,0,p.z)}
    P.top=0;P.dist=0;P.smashN=0;if(i>=0)H.say(M[i].name,1800)}
  F.revive=()=>{P.hp=100;P.inv=2;P.stun=0}
  function newBomb(){if(made>=10)return;made++;let p;for(let k=0;k<60;k++){p=city.streetPt(P.x,P.z,160,460);if(!bombs.some(b=>Math.hypot(b.x-p.x,b.z-p.z)<120))break}const g=add(new T.Group());part(T,cy(T,.7,.7,1.1,12),TM(0xF2352A),0,.55,0,g);part(T,cy(T,.72,.72,.25,12),TM(0xFFD23F),0,.6,0,g);K.ink(g,.05);const lamp=part(T,sp(T,.25),new T.MeshBasicMaterial({color:0xffffff}),0,1.3,0,g);g.add(beam(0xF2352A,80));g.position.set(p.x,.3,p.z);
    const d=Math.hypot(p.x-P.x,p.z-P.z);bombs.push({x:p.x,z:p.z,m:g,lamp,t:(7+d/32)*c.pick(1.6,1.2,.95)})}
  function mode(){return F.state==='play'&&!F.paused()}
  let dashLatch=false,jumpLatch=false;
  st3.onFrame((rdt,now)=>{H.tick(rdt);const play=mode();const I=input,Kk=I.keys;
    const blurOn=play&&(Kk.shift||I.alt||Kk.q)&&P.blur>.02;ws+=((blurOn?.2:1)-ws)*Math.min(1,rdt*8);const dt=rdt*ws,wdt=dt;wclk+=dt;now=wclk*1000;K.fxTick(dt);
    H.tint(blurOn?'rgba(127,200,248,.22)':null,blurOn?1:0);if(!blurOn&&P.inv>.5)H.tint('rgba(242,53,42,.4)',P.inv-.3);
    // traffic always moves (menu too) for life
    cars.forEach(car=>{if(car.fly){const f=car.fly;f.vy-=30*wdt;car.m.position.y+=f.vy*wdt;car.m.position.x+=f.vx*wdt;car.m.position.z+=f.vz*wdt;car.m.rotation.x+=f.rx*wdt;car.m.rotation.z+=f.rz*wdt;if(car.m.position.y<0){car.m.position.y=0;f.vy*=-.3;f.vx*=.5;f.vz*=.5;f.rx*=.5;f.rz*=.5;f.l-=wdt*2}f.l-=wdt;if(f.l<=0){car.fly=null;car.m.rotation.set(0,0,0);respawnCar(car,false)}return}
      car.u+=car.dir*car.sp*wdt;placeCar(car);if(Math.abs(car.m.position.x-P.x)>300||Math.abs(car.m.position.z-P.z)>300)respawnCar(car,false);car.nm-=dt});
    if(!play){P.ph+=dt;K.pose(hero,'idle',P.ph);K.capeAnim(hero,0,now/1000);hero.position.set(P.x,P.y,P.z);hero.rotation.y=P.face;cam.yaw+=rdt*.15;cam.place(P,rdt,8,2.2,0);H.lines(0);return}
    // --- hero control ---
    cam.look();const mv=K.moveIn();P.inv-=dt;P.dashCd-=dt;P.tagCd-=dt;
    if(blurOn)P.blur=Math.max(0,P.blur-rdt*.18);else P.blur=Math.min(1,P.blur+rdt*(.02+P.spd/MAX*.09));
    const fire=I.down||I.fire||Kk.f||Kk.j;if(fire&&!dashLatch&&P.dashCd<=0&&P.stun<=0){dashLatch=true;P.dash=.45;P.dashCd=2;sweep(300,1400,.35,'sawtooth',.06);K.ring(new T.Vector3(P.x,.3,P.z),0xffffff,1,9,.4);cam.shake=.3}if(!fire)dashLatch=false;
    if(P.spin>0){P.spin-=dt;P.face+=dt*14;P.spd*=Math.pow(.2,dt)}
    else if(P.stun>0){P.stun-=dt;P.spd*=Math.pow(.02,dt)}
    else if(mv.m>0){const tgt=Math.atan2(mv.x,mv.z);const da=wrapA(tgt-P.face);const drifting=(I.right||Kk.e||I.drift)&&P.spd>18;const rate=drifting?8:11-6.5*Math.min(1,P.spd/MAX);P.face+=clamp(da,-rate*dt,rate*dt);if(Math.abs(da)>2.2&&P.spd>30){P.spd-=160*dt;if(Math.random()<.6)K.puff(new T.Vector3(P.x,.3,P.z),0xffffff,.6,.4)}else P.spd+=(P.spd<60?90:P.spd<100?32:16)*dt*mv.m;P.spd=Math.min(P.spd,MAX)}
    else P.spd=Math.max(0,P.spd-(P.spd>60?70:110)*dt);
    if(P.dash>0){P.dash-=dt;P.spd=Math.max(P.spd,MAX*1.55)}else if(P.spd>MAX)P.spd=Math.max(MAX,P.spd-120*dt);
    const drifting=(I.right||Kk.e||I.drift)&&P.spd>18&&P.stun<=0&&P.spin<=0;{const dm=wrapA(P.face-P.mv);P.mv+=clamp(dm,-(drifting?2.2:25)*dt,(drifting?2.2:25)*dt);if(drifting){P.spd*=Math.pow(.93,dt);const slip=Math.abs(wrapA(P.face-P.mv));P.drift+=dt*slip;if(Math.random()<dt*30)K.burst(new T.Vector3(P.x,.2,P.z),[0xffffff,0xFFE27A,0xd8d4e4],2,5,.35,8);if(slip>.3&&Math.random()<dt*2)K.puff(new T.Vector3(P.x,.2,P.z),0xd8d4e4,.6,.5)}else if(P.drift>.6){const pts=Math.round(P.drift*200);score+=pts;H.pow('DRIFT +'+pts,new T.Vector3(P.x,2.5,P.z),'#FFD23F');P.drift=0}else P.drift=0}
    let hb=null;const nsub=Math.max(1,Math.ceil(P.spd*dt/1.2));for(let q=0;q<nsub;q++){P.x+=Math.sin(P.mv)*P.spd*dt/nsub;P.z+=Math.cos(P.mv)*P.spd*dt/nsub;const h2=K.push(P,.5,city.boxes,P.y);if(h2){hb=h2;const hx=Math.sin(P.mv),hz=Math.cos(P.mv);const dot=Math.abs(hx*(P.nx||0)+hz*(P.nz||0));if(dot<.75&&P.spd>20){const tx=P.nx?0:hx,tz=P.nx?hz:0;const L=Math.hypot(tx,tz)||1;P.face=Math.atan2(tx/L,tz/L);P.mv=P.face;P.spd*=1-dot*.5;if(Math.random()<.5){K.burst(new T.Vector3(P.x,1,P.z),[0xFFE27A,0xffffff],4,8,.3,10)}if(Math.random()<.08)H.pow(pick(['SKRRT!','ZWIP!','WALL-RUN!']),new T.Vector3(P.x,2,P.z),'#fff');hb=null}}}
    let flr=0;for(const b of city.boxes){if(b.dead||b.tree)continue;if(P.x>b.x0&&P.x<b.x1&&P.z>b.z0&&P.z<b.z1&&b.h<=P.y+.8&&b.h>flr)flr=b.h}
    const jmp=Kk[' ']||I.jumpBtn;if(jmp&&!jumpLatch&&P.y<=flr+.001){P.vy=11.5;jumpLatch=true;beep(600,.08,'triangle',.05)}if(!jmp)jumpLatch=false;if(P.climbT>0)P.climbT-=dt;else P.vy-=30*dt;P.y=Math.max(flr,P.y+P.vy*dt);P.air=P.y>flr+.2;if(P.y<=flr){if(P.vy<0)P.vy=0;if(P.climbing&&P.climbT<=0){P.climbing=false}}
    if(hb&&P.dash<=0&&mv.m>0&&hb.h>P.y+.5&&P.stun<=0){const cs=Math.min(14+Math.min(P.spd,MAX)*.5,(hb.h+1.6-P.y)*5+4);P.vy=cs;P.climbT=.12;if(!P.climbing){P.climbing=true;H.pow('WALL-RUN!',new T.Vector3(P.x,P.y+2,P.z),'#fff');beep(700,.08,'triangle',.05)}P.spd=Math.max(P.spd*.985,22);if(Math.random()<.6)K.burst(new T.Vector3(P.x,P.y+.5,P.z),[0xFFE27A,0xffffff,0xd8d4e4],3,6,.3,8);hb=null}
    if(hb){if(P.dash>0){const r=K.smash(hb,new T.Vector3(P.x,1.2,P.z),P.spd*(P.dash>0?1.6:.8));score+=Math.round(P.spd);if(r==='collapse'){P.smashN=(P.smashN||0)+1;H.pow('SMASH!',new T.Vector3(P.x,2,P.z),'#FFD23F');P.spd*=.7;P.dash=0}else if(P.dash>0){H.pow('KRAK!',new T.Vector3(P.x,1.5,P.z));P.spd*=.5;P.dash=0}else{H.pow('WHAM!',new T.Vector3(P.x,1.5,P.z));hurt(6,'Buildings don’t move out of the way.');P.stun=.3;P.spd*=.2}}else P.spd*=.92}
    city.update(P.x,P.z);
    const fr=Math.min(1.4,P.spd/MAX);H.lines((fr-.25)*1.6);const fovT=70+fr*34;if(Math.abs(camera.fov-fovT)>.2){camera.fov+=(fovT-camera.fov)*Math.min(1,rdt*4);camera.updateProjectionMatrix()}if(P.spd>100)cam.shake=Math.max(cam.shake,.12+(P.spd-100)*.004);
    if(P.spd>SOUND&&!mach){mach=true;K.ring(new T.Vector3(P.x,1,P.z),0xffffff,1,40,.7,1);K.ring(new T.Vector3(P.x,.4,P.z),0xFFE27A,1,26,.5,.4);H.pow('SONIC BOOM!',new T.Vector3(P.x,3,P.z),'#fff');noise(.9,'lowpass',160,.5);cam.shake=1.2;cars.forEach(car=>{if(!car.fly&&car.m.position.distanceTo(new T.Vector3(P.x,0,P.z))<22){const d=Math.atan2(car.m.position.x-P.x,car.m.position.z-P.z);car.fly={vy:12,vx:Math.sin(d)*14,vz:Math.cos(d)*14,rx:4,rz:5,l:3};score+=60}});score+=200}else if(P.spd<SOUND-15)mach=false;
    coneG.position.set(P.x,P.y+1.1,P.z);coneG.rotation.y=P.face;cone.position.z=0;cone.material.opacity=P.spd>SOUND?.18+Math.random()*.08:0;cone.scale.set(1,1+fr*.4,1);
    if(P.spd>60&&Math.random()<dt*(P.spd/4))ghost();for(let i=ghosts.length-1;i>=0;i--){const g=ghosts[i];g.l-=dt;g.m.material.opacity=g.l*1.6;if(g.l<=0){scene.remove(g.m);g.m.material.dispose();ghosts.splice(i,1)}}
    arcs.forEach(l=>{l.visible=P.spd>75&&Math.random()<.7;if(l.visible){const a=l.geometry.attributes.position;let px=P.x+(Math.random()-.5)*1.5,py=P.y+.4+Math.random()*1.6,pz=P.z+(Math.random()-.5)*1.5;for(let i=0;i<8;i++){a.setXYZ(i,px,py,pz);px+=(Math.random()-.5)*.7-Math.sin(P.face)*.5;py+=(Math.random()-.5)*.6;pz+=(Math.random()-.5)*.7-Math.cos(P.face)*.5}a.needsUpdate=true}});
    if(P.spd>12&&!input.mdx&&mv.m>0){cam.yaw+=wrapA(P.face+Math.PI-cam.yaw)*Math.min(1,rdt*(.8+fr*3))}
    // hero visuals
    P.ph+=dt*(3+Math.min(P.spd,40)*.5+(P.spd>40?30:0));P.ph=P.ph%1000;K.pose(hero,P.air&&!P.climbing?'air':P.climbing?'sprint':P.spd<.5?'idle':P.spd<24?'run':'sprint',Math.min(P.ph,P.ph),Math.min(1,P.spd/10));hero.position.set(P.x,P.y,P.z);hero.rotation.y=P.face;hero.rotation.z=drifting?clamp(wrapA(P.face-P.mv),-.5,.5)*.6:0;K.capeAnim(hero,Math.min(1,fr*1.3),now/1000);
    const on=P.spd>16;trA.push(new T.Vector3(P.x,P.y+1.2,P.z),{x:0,y:1,z:0},on);trB.push(new T.Vector3(P.x,P.y+.55,P.z),{x:0,y:1,z:0},on);trC.push(new T.Vector3(P.x,P.y+1.7,P.z),{x:0,y:1,z:0},P.spd>70);
    if(on&&!P.air&&Math.random()<dt*(5+P.spd*.06))K.puff(new T.Vector3(P.x+(Math.random()-.5)*1.6,.1,P.z+(Math.random()-.5)*1.6),0xe8e1d0,.18,.35,new T.Vector3((Math.random()-.5)*2,.5,(Math.random()-.5)*2));
    // cars vs hero
    cars.forEach(car=>{if(car.fly)return;const cp=car.m.position;const dx=P.x-cp.x,dz=P.z-cp.z;const al=car.a===0?Math.abs(dz):Math.abs(dx),cr=car.a===0?Math.abs(dx):Math.abs(dz);
      const rr=P.spd>70?2.4:0;if(al<2.3+rr&&cr<1.4+rr&&P.y<1.3){if(P.dash>0||blurOn||P.spd>70){if(P.dash>0||P.spd>70){const side=Math.sign((cp.x-P.x)*Math.cos(P.face)-(cp.z-P.z)*Math.sin(P.face))||1;car.fly={vy:10+P.spd*.08,vx:Math.sin(P.face)*P.spd*.2+Math.cos(P.face)*side*12,vz:Math.cos(P.face)*P.spd*.2-Math.sin(P.face)*side*12,rx:6,rz:6,l:3};score+=100;H.pow(pick(['WHOOSH!','WHAM!','FWOOM!']),cp.clone().setY(1.5));P.spd*=.97;noise(.3,'lowpass',500,.25);cam.shake=.4}else{P.vy=9;P.y=Math.max(P.y,.1);H.pow('HOP!',cp.clone().setY(1.5),'#7FC8F8');score+=25}}else{hurt(12,'Traffic is dangerous, even for you.');car.fly={vy:6,vx:-Math.sin(P.face)*3,vz:-Math.cos(P.face)*3,rx:2,rz:3,l:2.5};P.spd*=.1;P.stun=.4;H.pow('CRUNCH!',cp.clone().setY(1.5))}}
      else if(al<6&&cr<5&&P.spd>40&&car.nm<=0){car.nm=3;score+=50;H.pow('ZIP!',cp.clone().setY(2),'#fff');beep(1200,.05,'square',.03)}});
    // ---- missions ----
    const dots=[];
    if(mi===0){bombs=bombs.filter(b=>{b.t-=wdt;const bl=b.t<6?(Math.sin(now/60)>0):(Math.sin(now/200)>0);b.lamp.material.color.setHex(bl?0xF2352A:0xffffff);b.m.rotation.y+=dt;
        if(Math.hypot(P.x-b.x,P.z-b.z)<2.6){defused++;score+=500+Math.ceil(b.t)*20;H.pow('DEFUSED!',new T.Vector3(b.x,2,b.z),'#6EE7B7');[880,1320].forEach((f,i)=>c.after(()=>beep(f,.12,'triangle',.07),i*90));scene.remove(b.m);P.blur=Math.min(1,P.blur+.25);c.after(()=>{if(F.state==='play'&&mi===0)newBomb()},600);return false}
        if(b.t<=0){K.burst(new T.Vector3(b.x,1,b.z),[0xF2352A,0xFFD23F,0xFF9F43,0x1D1A2F],50,22,.8,1.2);H.pow('KA-BOOM!',new T.Vector3(b.x,3,b.z));noise(1,'lowpass',300,.5);cam.shake=1;scene.remove(b.m);F.lose(M,'KA-BOOM!','One of Gridlock’s bombs went off. Nobody got hurt, but the donut shop is gone forever. Try again?');return false}
        dots.push({x:b.x,z:b.z,col:'#F2352A',r:6});return true});
      const nt=bombs.length?Math.min(...bombs.map(b=>b.t)):0;H.cap('Issue #1 · Rush Hour','Bombs defused '+defused+'/10'+(bombs.length?' · closest timer '+Math.ceil(nt)+'s':''));
      if(defused>=10)F.win(M,score+Math.round(P.hp)*5,[[defused,'defused'],[Math.round(P.hp),'health'],[score,'points'],[LVN[c.level],'mode']],'Ten bombs, zero booms. Gridlock is furious, and the donut shop is safe.')}
    if(mi===1){timeLeft-=wdt;const tp=tower.m.position;tp.x=tower.cx+(Math.random()-.5)*.25;tp.z=tower.cz+(Math.random()-.5)*.25;
      spawnT-=wdt;if(spawnT<=0){spawnT=.45/diff;const a=Math.random()*6.28,r=6+Math.random()*75;let x=tower.cx+Math.cos(a)*r,z=tower.cz+Math.sin(a)*r;if(Math.random()<.3){x=P.x+Math.sin(P.face)*P.spd*.9+(Math.random()-.5)*8;z=P.z+Math.cos(P.face)*P.spd*.9+(Math.random()-.5)*8}
        if(!K.inBox(x,1,z,city.boxes)){const sh=add(part(T,new T.CircleGeometry(1.8,20),new T.MeshBasicMaterial({color:0xF2352A,transparent:true,opacity:.5}),x,.35,z));sh.rotation.x=-Math.PI/2;const rock=add(part(T,bx(T,1.6,1.6,1.6),TM(pick([0xd8d4e4,0x8c86a3,0xB9A7FF])),x,70,z));K.ink(rock,.08);debris.push({sh,rock,x,z,y:70,t:0})}}
      debris=debris.filter(d=>{d.t+=wdt;d.y=70-70*Math.min(1,d.t/1.6)**2;d.rock.position.y=d.y;d.rock.rotation.x+=wdt*3;d.sh.material.opacity=.3+.4*(d.t/1.6);if(d.t>=1.6){K.burst(new T.Vector3(d.x,.8,d.z),[0xd8d4e4,0x8c86a3,0xFFE27A],14,10,.6);noise(.12,'lowpass',400,.15);if(Math.hypot(P.x-d.x,P.z-d.z)<2.4&&P.y<2)hurt(20,'Falling rocks hurt.');civs.forEach(cv=>{if(cv.st===0&&Math.hypot(cv.x-d.x,cv.z-d.z)<1.8){cv.x+=3;cv.z+=3}});scene.remove(d.sh);scene.remove(d.rock);return false}return true});
      civs.forEach(cv=>{cv.t+=dt;if(cv.st===0){cv.m.position.set(cv.x,.3,cv.z);K.pose(cv.m,'lift',cv.t);cv.m.userData.armL.rotation.z=Math.sin(cv.t*8)*.4-.3;cv.m.userData.armR.rotation.z=-Math.sin(cv.t*8)*.4+.3;cv.m.rotation.y=Math.atan2(P.x-cv.x,P.z-cv.z);dots.push({x:cv.x,z:cv.z,col:'#FFD23F'});
          if(!P.carry&&Math.hypot(P.x-cv.x,P.z-cv.z)<2.2&&P.y<2){cv.st=1;P.carry=cv;H.pow('GOTCHA!',cv.m.position.clone().setY(2),'#fff');beep(900,.08,'triangle',.06)}}
        else if(cv.st===1){cv.m.position.set(P.x-Math.sin(P.face)*.1,P.y+1.6,P.z-Math.cos(P.face)*.1);cv.m.rotation.set(0,P.face+Math.PI/2,Math.PI/2)}});
      const zx=zone.position.x,zz=zone.position.z;dots.push({x:zx,z:zz,col:'#2BB673',r:7});
      if(P.carry&&Math.hypot(P.x-zx,P.z-zz)<7.5){const cv=P.carry;cv.st=2;P.carry=null;rescued++;score+=400+Math.round(timeLeft)*3;H.pow('SAFE!',new T.Vector3(zx,3,zz),'#6EE7B7');cv.m.position.set(zx+(Math.random()-.5)*8,.3,zz+(Math.random()-.5)*8);cv.m.rotation.set(0,Math.random()*6,0);K.pose(cv.m,'lift',0);[660,990].forEach((f,i)=>c.after(()=>beep(f,.12,'triangle',.07),i*90))}
      H.cap('Issue #2 · Everything Falls Down','Rescued '+rescued+'/12 · '+Math.max(0,Math.ceil(timeLeft))+'s left'+(P.carry?' · run to the green zone!':''));
      if(rescued>=12)F.win(M,score+Math.round(timeLeft)*20,[[rescued,'rescued'],[Math.ceil(timeLeft)+'s','to spare'],[Math.round(P.hp),'health'],[LVN[c.level],'mode']],'Everyone’s out, and not a second too soon. Brightside Tower folds up like a lawn chair behind you.');
      else if(timeLeft<=0){K.burst(tower.m.position.clone().setY(20),[0xd8d4e4,0x8c86a3],60,30,1.2);F.lose(M,'The tower came down','Everyone got out on their own in the end, but it was way too close. Try again?')}}
    if(mi===2){timeLeft-=wdt;const tr=truck;const a=city.node(tr.i,tr.j),b=city.node(tr.ni,tr.nj);const seg=Math.hypot(b.x-a.x,b.z-a.z);tr.slow-=wdt;tr.u+=tr.sp*(tr.slow>0?.55:1)*wdt/seg;
      if(tr.u>=1){const pi=tr.i,pj=tr.j;tr.i=tr.ni;tr.j=tr.nj;tr.u=Math.min(tr.u-1,.5);let opts=[[1,0],[-1,0],[0,1],[0,-1]].map(([di,dj])=>[tr.i+di,tr.j+dj]).filter(([x,y])=>!(x===pi&&y===pj));
        const away=opts.filter(([x,y])=>{const q=city.node(x,y);return Math.hypot(q.x-P.x,q.z-P.z)>Math.hypot(city.node(tr.i,tr.j).x-P.x,city.node(tr.i,tr.j).z-P.z)});const nb=pick(away.length&&Math.random()<.6?away:opts);tr.ni=nb[0];tr.nj=nb[1]}
      const A=city.node(tr.i,tr.j),B=city.node(tr.ni,tr.nj);const tx=A.x+(B.x-A.x)*tr.u,tz=A.z+(B.z-A.z)*tr.u;tr.m.position.set(tx,0,tz);tr.m.rotation.y=Math.atan2(B.x-A.x,B.z-A.z);
      dropT-=wdt;if(dropT<=0){dropT=c.pick(2.2,1.6,1.2);const s=add(part(T,new T.CircleGeometry(2.2,18),new T.MeshBasicMaterial({color:0x1D1A2F,transparent:true,opacity:.85}),tx,.33,tz));s.rotation.x=-Math.PI/2;slicks.push({m:s,x:tx,z:tz,l:14})}
      coneT-=wdt;if(coneT<=0){coneT=c.pick(1.6,1.1,.8);const cn=add(new T.Group());part(T,new T.ConeGeometry(.45,1.1,10),TM(0xFF9F43),0,.55,0,cn);part(T,cy(T,.3,.35,.16,10),TM(0xffffff),0,.6,0,cn);K.ink(cn,.04);const off=(Math.random()-.5)*6;const rx=Math.cos(tr.m.rotation.y)*off,rz=-Math.sin(tr.m.rotation.y)*off;cn.position.set(tx+rx,0,tz+rz);cones.push({m:cn,x:tx+rx,z:tz+rz,l:16,fly:null})}
      slicks=slicks.filter(s=>{s.l-=wdt;if(s.l<2)s.m.material.opacity=s.l/2*.85;if(P.spin<=0&&P.y<.3&&P.dash<=0&&Math.hypot(P.x-s.x,P.z-s.z)<2.2){P.spin=.7;H.pow('SPLOOSH!',new T.Vector3(P.x,1.5,P.z),'#B9A7FF');sweep(700,200,.4,'sine',.06)}if(s.l<=0){scene.remove(s.m);return false}return true});
      cones=cones.filter(cn=>{cn.l-=wdt;if(cn.fly){cn.fly.vy-=30*wdt;cn.m.position.x+=cn.fly.vx*wdt;cn.m.position.z+=cn.fly.vz*wdt;cn.m.position.y=Math.max(0,cn.m.position.y+cn.fly.vy*wdt);cn.m.rotation.x+=wdt*10}else if(P.y<1&&Math.hypot(P.x-cn.x,P.z-cn.z)<1.2){cn.fly={vy:10,vx:Math.sin(P.face)*P.spd*.5,vz:Math.cos(P.face)*P.spd*.5};if(P.dash<=0&&!blurOn){hurt(7,'Cones hurt at 200 mph.');P.spd*=.5}H.pow('BONK!',new T.Vector3(cn.x,1.5,cn.z))}if(cn.l<=0){scene.remove(cn.m);return false}return true});
      const td=Math.hypot(P.x-tx,P.z-tz);if(td<6&&P.tagCd<=0&&(fire||P.dash>0)){P.tagCd=1;tags++;tr.slow=1.2;score+=800;H.pow(tags>=5?'JAMMED!':'TAG!',new T.Vector3(tx,3,tz));K.burst(new T.Vector3(tx,1,tz),[0xFFD23F,0xffffff,0x1D1A2F],20,10,.6);beep(1000,.1,'square',.06);cam.shake=.4;if(tags<5)tr.sp*=1.04}
      dots.push({x:tx,z:tz,col:'#1D1A2F',r:7});H.boss('Gridlock’s truck',(5-tags)/5);
      H.cap('Issue #3 · Gridlock','Tags '+tags+'/5 · '+Math.max(0,Math.ceil(timeLeft))+'s · '+(td<40?'close!':Math.round(td)+'m away'));
      if(tags>=5){H.boss(null);tr.sp=0;K.burst(new T.Vector3(tx,2,tz),[0xFFD23F,0xF2352A,0xffffff],60,20,1);F.win(M,score+Math.round(timeLeft)*25+Math.round(P.hp)*5,[[tags,'tags'],[Math.ceil(timeLeft)+'s','to spare'],[Math.round(P.hp),'health'],[LVN[c.level],'mode']],'All four wheels jammed and the doors glued shut with his own oil. Gridlock is going nowhere, which, honestly, is how he likes everyone else.')}
      else if(timeLeft<=0){H.boss(null);F.lose(M,'He got away!','Gridlock’s truck disappears onto the highway. He’ll be back. Try again?')}}
    if(mi<0){P.top=Math.max(P.top,P.spd);P.dist+=P.spd*dt;H.cap('Free roam · Brightside City','Top '+Math.round(P.top*9)+' MPH · '+(P.dist*9/3600).toFixed(1)+' miles · buildings wrecked '+P.smashN+' · P for menu')}
    // hud
    hpB(P.hp/100,'HEALTH '+Math.ceil(P.hp));blB(P.blur,blurOn?'BLUR  (time slowed)':'BLUR  [Shift]');spB(P.spd/MAX,(P.spd>SOUND?'MACH '+(P.spd/SOUND).toFixed(1)+' · ':'')+Math.round(P.spd*9)+' MPH'+(P.dashCd<=0?'  · DASH':''));H.score(score,'score');
    if(RM&&mi<0){RM.tick(dt,P.spd);RM.dots(dots)}rad(P.x,P.z,cam.yaw,dots,city.boxes);c.stat('Blur · '+F.tag(mi)+' · Score '+score);
    cam.place(P,rdt,5.6+fr*1.2,1.6-fr*.3,14)});
  F.intro(M,'Blur','A Detour original · 3D super-speed','<p>You’re <b>Blur</b>, the fastest person alive. Brightside City moves at a crawl compared to you, which is great, because the bomber <b>Gridlock</b> has plans for it.</p><p>Hold forward to build momentum all the way past the speed of sound. Dash (or crash at full speed) into buildings to smash chunks out of them, and keep going to bring them down. At full speed traffic just gets blown out of your way, and you skid along buildings instead of stopping. Head-on hits still hurt.</p>','WASD or arrows to run (hold to build speed), mouse to look (click the game to lock the mouse). Hold <b>right-click or E</b> to drift round corners. <b>Shift</b> slows time to slow motion for everything, you included, so you get more time to line up turns and dashes. <b>Click</b> or F to dash (smashes through traffic). <b>Space</b> jumps. Run straight into a building to <b>run up its wall</b> onto the roof. P pauses. On a phone: joystick on the left, drag on the right to look, and the DASH, BLUR, DRIFT and JUMP buttons. The city never ends, so run as far as you like.');
  return()=>st3.dispose()})}});
