/* ================= TACTICAL FPS ENGINE v2: Breach 5v5 (CS-style bomb defusal) + Last Drop (battle royale) ================= */
const TX_CSS=`.tx .hud{font:700 13px 'Trebuchet MS',system-ui,-apple-system,Segoe UI,sans-serif;color:#fff;text-shadow:0 1px 2px rgba(0,0,0,.9)}
.tx button{transform:none!important}
.tx-x{position:absolute;left:50%;top:50%;width:0;height:0;pointer-events:none}.tx-x i{position:absolute;background:#4cff5c;box-shadow:0 0 0 1px rgba(0,0,0,.6)}.tx-x b{position:absolute;left:-1px;top:-1px;width:2px;height:2px;background:#4cff5c}
.tx-hm{position:absolute;left:50%;top:50%;width:26px;height:26px;margin:-13px;pointer-events:none;opacity:0}.tx-hm:before,.tx-hm:after{content:'';position:absolute;left:12px;top:0;width:2px;height:26px;background:#fff;transform:rotate(45deg)}.tx-hm:after{transform:rotate(-45deg)}.tx-hm.hs:before,.tx-hm.hs:after{background:#ff3a2a}
.tx-bl{position:absolute;left:0;bottom:0;display:flex;align-items:flex-end;gap:2px;padding:0 0 10px 12px}
.tx-stat{display:flex;align-items:center;gap:6px;background:linear-gradient(90deg,rgba(0,0,0,.55),rgba(0,0,0,0));padding:4px 16px 4px 8px;font:900 28px 'Trebuchet MS',system-ui,sans-serif;min-width:90px}
.tx-stat svg{width:22px;height:22px;fill:#fff;opacity:.9}.tx-stat.low{color:#ff4a3a}
.tx-am{position:absolute;right:14px;bottom:10px;text-align:right;font:900 30px 'Trebuchet MS',system-ui,sans-serif;background:linear-gradient(270deg,rgba(0,0,0,.55),rgba(0,0,0,0));padding:4px 10px 4px 30px}.tx-am small{font:800 16px system-ui,sans-serif;opacity:.8;margin-left:4px}.tx-am em{display:block;font:800 11px system-ui,sans-serif;font-style:normal;opacity:.8;letter-spacing:.06em}
.tx-money{position:absolute;left:12px;top:192px;font:900 18px 'Trebuchet MS',system-ui,sans-serif;color:#8aff8a;background:rgba(0,0,0,.45);padding:3px 10px;border-radius:4px}
.tx-top{position:absolute;left:50%;top:6px;transform:translateX(-50%);display:flex;align-items:stretch;gap:0;font:900 16px 'Trebuchet MS',system-ui,sans-serif}
.tx-top .txs{padding:4px 12px;min-width:34px;text-align:center;line-height:1.35;height:auto}.tx-top .txT{background:rgba(190,140,60,.9)}.tx-top .txC{background:rgba(70,120,200,.9)}
.tx-top .txm{background:rgba(0,0,0,.65);padding:4px 14px;font-size:19px;min-width:64px;text-align:center;line-height:1.3}
.tx-alive{display:flex;gap:3px;align-items:center;padding:0 8px;background:rgba(0,0,0,.35)}.tx-alive i{width:16px;height:22px;border-radius:3px;background:currentColor;opacity:.95;position:relative}.tx-alive i.d{opacity:.18}.tx-alive i.me{box-shadow:0 0 0 2px #fff}
.tx-feed{position:absolute;right:10px;top:10px;display:flex;flex-direction:column;gap:3px;align-items:flex-end;font:800 13px 'Trebuchet MS',system-ui,sans-serif}
.tx-feed div{background:rgba(0,0,0,.55);padding:4px 10px;border-radius:3px;display:flex;align-items:center;gap:6px}.tx-feed .me{outline:2px solid #e8321e;background:rgba(80,0,0,.55)}
.tx-feed .fT{color:#ead18a}.tx-feed .fC{color:#8ab8ff}.tx-feed .w{opacity:.9;font-size:12px;color:#fff}
.tx .hud canvas.tx-radar{position:absolute;inset:auto;left:10px;top:10px;right:auto;bottom:auto;width:176px;height:176px;border-radius:6px;background:rgba(0,0,0,.5);border:1px solid rgba(255,255,255,.25);pointer-events:none}
@media (max-width:640px){.tx .hud canvas.tx-radar{width:110px;height:110px}.tx-money{top:126px;font-size:14px}.tx-stat,.tx-am{font-size:20px}}
.tx-center{position:absolute;left:0;right:0;top:24%;text-align:center;font:900 clamp(22px,4.4vw,40px) 'Trebuchet MS',system-ui,sans-serif;pointer-events:none;letter-spacing:.02em}
.tx-center small{display:block;font:700 15px system-ui,sans-serif;opacity:.92;margin-top:6px}
.tx-banner{position:absolute;left:0;right:0;top:18%;text-align:center;pointer-events:none;display:none}.tx-banner div{display:inline-block;padding:10px 60px;font:900 clamp(22px,4vw,36px) 'Trebuchet MS',system-ui,sans-serif;letter-spacing:.04em}.tx-banner .T{background:linear-gradient(90deg,transparent,rgba(170,120,40,.9),transparent)}.tx-banner .CT{background:linear-gradient(90deg,transparent,rgba(50,100,190,.9),transparent)}.tx-banner small{display:block;font:700 13px system-ui,sans-serif;opacity:.9}
.tx-bar{position:absolute;left:50%;top:62%;width:260px;height:12px;margin-left:-130px;border-radius:2px;background:rgba(0,0,0,.6);overflow:hidden;display:none;border:1px solid rgba(255,255,255,.3)}.tx-bar i{display:block;height:100%;background:#ffd23f;width:0}
.tx-hint{position:absolute;left:0;right:0;top:67%;text-align:center;font:800 14px system-ui,sans-serif;pointer-events:none}
.tx-buyhint{position:absolute;left:12px;bottom:70px;font:800 13px system-ui,sans-serif;background:rgba(0,0,0,.5);padding:4px 10px;border-radius:4px;pointer-events:auto;cursor:pointer;display:none}
.tx-flash{position:absolute;inset:0;background:#fff;pointer-events:none;opacity:0}
.tx-hurt{position:absolute;inset:0;pointer-events:none;opacity:0;background:radial-gradient(ellipse at center,transparent 50%,rgba(170,0,0,.6))}
.tx-storm{position:absolute;inset:0;pointer-events:none;opacity:0;background:rgba(40,70,180,.28);box-shadow:inset 0 0 120px rgba(40,70,200,.9)}
.tx-dir{position:absolute;left:50%;top:50%;width:0;height:0;pointer-events:none}.tx-dir i{position:absolute;left:-40px;top:-150px;width:80px;height:26px;border-radius:50% 50% 0 0;border-top:6px solid rgba(255,40,30,.85);transform-origin:40px 150px}
.tx-scope{position:absolute;inset:0;pointer-events:none;display:none;background:radial-gradient(circle at center,transparent 0,transparent 42vh,#000 42.3vh)}.tx-scope:before,.tx-scope:after{content:'';position:absolute;background:#000}.tx-scope:before{left:0;right:0;top:50%;height:1.5px}.tx-scope:after{top:0;bottom:0;left:50%;width:1.5px}
.tx-ov{position:absolute;inset:0;display:none;align-items:center;justify-content:center;padding:12px;background:rgba(6,8,12,.78);pointer-events:auto;overflow:auto}
.tx-ov.on{display:flex}.tx-ov.clear{background:rgba(6,8,12,.35)}
.tx-card{background:rgba(18,21,28,.97);border:1px solid rgba(255,255,255,.14);border-radius:10px;padding:16px 18px;max-width:820px;width:100%;max-height:100%;overflow:auto;color:#fff;font:600 13px system-ui,sans-serif}
.tx-card h2{margin:0 0 4px;font:900 clamp(24px,5vw,38px) 'Trebuchet MS',system-ui,sans-serif;letter-spacing:.02em}.tx-card h2 span{color:var(--ac)}
.tx-card h3{margin:14px 0 6px;font:900 11px system-ui,sans-serif;letter-spacing:.14em;opacity:.6}
.tx-card p{margin:4px 0 8px;opacity:.85;line-height:1.45}
.tx-btn{all:unset;cursor:pointer;display:inline-block;padding:10px 16px;border-radius:6px;background:rgba(255,255,255,.1);font:800 14px system-ui,sans-serif;margin:4px 4px 0 0;text-align:center}
.tx-btn.pri{background:var(--ac);color:#111}.tx-btn.on{outline:2px solid var(--ac)}
.tx-in{all:unset;background:rgba(255,255,255,.1);border-radius:6px;padding:9px 12px;font:700 14px system-ui,sans-serif;width:180px}
.tx-buyw{display:grid;grid-template-columns:repeat(5,1fr);gap:8px}.tx-buyc h4{margin:0 0 6px;font:900 12px system-ui,sans-serif;letter-spacing:.1em;opacity:.7}
.tx-buyc button{all:unset;cursor:pointer;display:block;background:rgba(255,255,255,.07);border-radius:5px;padding:7px 9px;margin-bottom:5px;font:800 13px system-ui,sans-serif;border-left:3px solid transparent}.tx-buyc button:hover{background:rgba(255,255,255,.15);border-left-color:var(--ac)}
.tx-buyc button small{display:block;font:700 11px system-ui,sans-serif;color:#8aff8a}.tx-buyc button.no{opacity:.35}.tx-buyc button.own{border-left-color:#8aff8a}
@media (max-width:700px){.tx-buyw{grid-template-columns:repeat(2,1fr)}}
.tx-sb{width:100%;border-collapse:collapse;font:700 13px system-ui,sans-serif}.tx-sb td,.tx-sb th{padding:5px 8px;text-align:left}.tx-sb th{opacity:.6;font-size:11px;letter-spacing:.08em}.tx-sb tr.me{background:rgba(255,255,255,.12)}.tx-sb .dead{opacity:.45}.tx-sb tr.T td:first-child{border-left:3px solid #d8a84a}.tx-sb tr.CT td:first-child{border-left:3px solid #4a8ae8}
.tx-rooms div{display:flex;align-items:center;gap:8px;background:rgba(255,255,255,.06);border-radius:6px;padding:8px 10px;margin-bottom:5px}.tx-rooms div b{flex:1}
.tx-inv{position:absolute;right:14px;bottom:62px;display:flex;flex-direction:column;gap:4px;align-items:flex-end}.tx-inv div{background:rgba(0,0,0,.45);border-right:3px solid rgba(255,255,255,.2);padding:3px 10px;font:800 12px system-ui,sans-serif;text-align:right;min-width:120px}.tx-inv div.on{border-right-color:var(--ac);background:rgba(0,0,0,.65)}
.tx-inv div.r1{color:#e8e8e8}.tx-inv div.r2{color:#6aff7a}.tx-inv div.r3{color:#5ab0ff}.tx-inv div.r4{color:#d88aff}.tx-inv div.r5{color:#ffc03a}
.tx-mapov{position:absolute;inset:0;display:none;align-items:center;justify-content:center;pointer-events:auto;background:rgba(0,0,0,.55)}.tx-mapov.on{display:flex}.tx-mapov canvas{width:min(86vh,86%);height:auto;aspect-ratio:1;border-radius:8px;border:2px solid rgba(255,255,255,.3)}
.tx .tbtn{background:rgba(10,14,20,.5)!important}
.tx-tbuy{position:absolute;right:12px;top:50%;pointer-events:auto;display:none}.tx.touch .tx-tbuy{display:block}.tx-tbuy button{all:unset;display:block;margin-bottom:8px;width:56px;height:40px;border-radius:8px;background:rgba(0,0,0,.5);border:1px solid rgba(255,255,255,.4);text-align:center;font:800 12px system-ui,sans-serif}
.tx .hud .tx-keys{position:absolute;left:12px;top:228px;display:grid;grid-template-columns:auto auto;column-gap:14px;row-gap:1px;background:rgba(0,0,0,.42);border-radius:6px;padding:6px 10px;font:700 10.5px/1.5 system-ui,sans-serif;color:#e8e8e8;pointer-events:none;width:max-content}.tx .hud .tx-keys.roy{top:196px}.tx .hud .tx-keys b{all:unset;display:inline-block;min-width:13px;padding:0 4px;margin-right:4px;border-radius:3px;background:rgba(255,255,255,.18);box-shadow:inset 0 -2px rgba(255,255,255,.25);font:800 9.5px/1.45 system-ui,sans-serif;text-align:center;color:#fff}.tx .hud .tx-keys div{white-space:nowrap}.tx .hud .tx-keys .k2{grid-column:1/-1;opacity:.62;font-size:9.5px;margin-top:2px}.tx .hud .tx-keys.min div:not(.k2){display:none}.tx.touch .tx-keys{display:none!important}@media (max-width:640px),(max-height:560px){.tx .hud .tx-keys{display:none}}
.tx-qb{display:flex;gap:6px;flex-wrap:wrap;margin:6px 0 10px}.tx-qb button{all:unset;cursor:pointer;background:rgba(255,190,60,.16);border:1px solid rgba(255,190,60,.55);border-radius:5px;padding:5px 10px;font:800 12px system-ui,sans-serif}.tx-qb button:hover{background:rgba(255,190,60,.35)}.tx-qb button.no{opacity:.4}.tx-qb button i{font-style:normal;opacity:.7;margin-right:5px}
.tx-sens{display:flex;align-items:center;gap:10px;font:700 13px system-ui,sans-serif}.tx-sens input{flex:1;max-width:260px}
`;
function tacticalGame(root,c,cfg){return with3D(root,c,()=>{
const ROY=cfg.mode==='royale',GAME=cfg.id;
const st3=Stage3D(root,c,{lock:true,fov:78,far:ROY?1600:420,fireLabel:'FIRE',altLabel:ROY?'USE':'SCOPE',jumpLabel:'JUMP'});
const{T,scene,camera,renderer,wrap,hud,input}=st3;const V3=T.Vector3;
wrap.classList.add('tx');wrap.style.setProperty('--ac',ROY?'#ffb02e':'#e8b03a');wrap.append(el('style',null,TX_CSS));
renderer.outputEncoding=T.sRGBEncoding;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=ROY?1:1.08;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;camera.near=.035;camera.updateProjectionMatrix();
const PI=Math.PI,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t,rnd=(a,b)=>a+Math.random()*(b-a),pick=a=>a[Math.random()*a.length|0],lin=h=>new T.Color(h).convertSRGBToLinear(),sstep=(a,b,x)=>{const t=clamp((x-a)/(b-a),0,1);return t*t*(3-2*t)};
function mulberry(a){return function(){a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
const hsh=(x,z)=>{const s=Math.sin(x*127.1+z*311.7)*43758.5453;return s-Math.floor(s)};const vn=(x,z)=>{const xi=Math.floor(x),zi=Math.floor(z),xf=x-xi,zf=z-zi,u=xf*xf*(3-2*xf),v=zf*zf*(3-2*zf);return lerp(lerp(hsh(xi,zi),hsh(xi+1,zi),u),lerp(hsh(xi,zi+1),hsh(xi+1,zi+1),u),v)};const fbm=(x,z,o)=>{let a=0,f=1,m=1,t=0;for(let i=0;i<(o||4);i++){a+=vn(x*f,z*f)*m;t+=m;f*=2.03;m*=.5}return a/t};
/* ---------------- textures ---------------- */
const ctex=(w,h,fn)=>{const cv=document.createElement('canvas');cv.width=w;cv.height=h;fn(cv.getContext('2d'),w,h);const t=new T.CanvasTexture(cv);t.encoding=T.sRGBEncoding;t.wrapS=t.wrapT=T.RepeatWrapping;t.anisotropy=8;return t};
const grain=(g,w,h,a,sat)=>{const id=g.getImageData(0,0,w,h);for(let i=0;i<id.data.length;i+=4){const n=(Math.random()-.5)*a;id.data[i]+=n;id.data[i+1]+=n*(sat||1);id.data[i+2]+=n*(sat||1)*.9}g.putImageData(id,0,0)};
const blot=(g,w,h,n,col,rmin,rmax)=>{for(let i=0;i<n;i++){const x=Math.random()*w,y=Math.random()*h,r=rnd(rmin,rmax),gr=g.createRadialGradient(x,y,0,x,y,r);gr.addColorStop(0,col);gr.addColorStop(1,'rgba(0,0,0,0)');g.fillStyle=gr;g.fillRect(x-r,y-r,r*2,r*2)}};
const TEX={
 sandwall:()=>ctex(512,512,(g,w,h)=>{g.fillStyle='#b8986a';g.fillRect(0,0,w,h);for(let y=0;y<h;y+=42){const off=(y/42)%2?-60:0;for(let x=off;x<w;x+=120){const l=rnd(58,70);g.fillStyle=`hsl(${rnd(32,38)},${rnd(30,40)}%,${l}%)`;g.fillRect(x+3,y+3,114,36);g.fillStyle=`hsla(30,30%,${l-12}%,.5)`;g.fillRect(x+3,y+36,114,3);g.fillStyle=`hsla(40,40%,${l+8}%,.35)`;g.fillRect(x+3,y+3,114,3)}}blot(g,w,h,30,'rgba(90,60,30,.12)',20,90);blot(g,w,h,20,'rgba(255,240,210,.1)',20,70);grain(g,w,h,22);const gr=g.createLinearGradient(0,h*.8,0,h);gr.addColorStop(0,'rgba(60,40,20,0)');gr.addColorStop(1,'rgba(60,40,20,.25)');g.fillStyle=gr;g.fillRect(0,0,w,h)}),
 plaster:()=>ctex(512,512,(g,w,h)=>{g.fillStyle='#d8c8a4';g.fillRect(0,0,w,h);blot(g,w,h,60,'rgba(160,120,70,.14)',20,110);blot(g,w,h,30,'rgba(255,250,235,.18)',20,80);for(let i=0;i<12;i++){g.strokeStyle='rgba(90,70,40,.25)';g.lineWidth=1;g.beginPath();let x=rnd(0,w),y=rnd(0,h);g.moveTo(x,y);for(let k=0;k<6;k++){x+=rnd(-20,20);y+=rnd(5,25);g.lineTo(x,y)}g.stroke()}grain(g,w,h,18)}),
 ground:()=>ctex(512,512,(g,w,h)=>{g.fillStyle='#c4a476';g.fillRect(0,0,w,h);blot(g,w,h,80,'rgba(140,100,60,.18)',10,70);blot(g,w,h,40,'rgba(240,220,180,.2)',10,50);for(let i=0;i<500;i++){g.fillStyle=`rgba(${rnd(80,140)|0},${rnd(60,100)|0},40,.35)`;g.fillRect(rnd(0,w),rnd(0,h),rnd(1,4),rnd(1,3))}grain(g,w,h,26)}),
 stone:()=>ctex(512,512,(g,w,h)=>{g.fillStyle='#6a5e50';g.fillRect(0,0,w,h);for(let y=0;y<h;y+=64)for(let x=0;x<w;x+=64){const l=rnd(48,62);g.fillStyle=`hsl(${rnd(28,36)},${rnd(14,22)}%,${l}%)`;g.fillRect(x+2,y+2,60,60);g.fillStyle='rgba(255,255,255,.07)';g.fillRect(x+2,y+2,60,4)}blot(g,w,h,30,'rgba(40,30,20,.15)',20,60);grain(g,w,h,20)}),
 cobble:()=>ctex(512,512,(g,w,h)=>{g.fillStyle='#5a5048';g.fillRect(0,0,w,h);for(let i=0;i<420;i++){const x=rnd(0,w),y=rnd(0,h),r=rnd(10,20);g.fillStyle=`hsl(${rnd(25,35)},${rnd(10,18)}%,${rnd(40,58)}%)`;g.beginPath();g.ellipse(x,y,r,r*rnd(.6,.9),rnd(0,3),0,7);g.fill()}grain(g,w,h,16)}),
 crate:()=>ctex(256,256,(g,w,h)=>{g.fillStyle='#7a5a32';g.fillRect(0,0,w,h);for(let y=0;y<h;y+=32){g.fillStyle=`hsl(30,${rnd(38,48)}%,${rnd(30,40)}%)`;g.fillRect(0,y+1,w,30);for(let k=0;k<6;k++){g.strokeStyle='rgba(40,25,10,.3)';g.beginPath();g.moveTo(rnd(0,w),y+rnd(4,28));g.lineTo(rnd(0,w),y+rnd(4,28));g.stroke()}}g.strokeStyle='#3a2810';g.lineWidth=18;g.strokeRect(9,9,w-18,h-18);g.lineWidth=14;g.beginPath();g.moveTo(14,14);g.lineTo(w-14,h-14);g.stroke();g.fillStyle='#2a2a2a';[[18,18],[w-18,18],[18,h-18],[w-18,h-18]].forEach(([x,y])=>{g.beginPath();g.arc(x,y,4,0,7);g.fill()});grain(g,w,h,20)}),
 metal:()=>ctex(256,256,(g,w,h)=>{g.fillStyle='#5a646c';g.fillRect(0,0,w,h);for(let x=0;x<w;x+=32){g.fillStyle='rgba(0,0,0,.22)';g.fillRect(x,0,4,h);g.fillStyle='rgba(255,255,255,.08)';g.fillRect(x+4,0,2,h)}blot(g,w,h,20,'rgba(120,70,30,.25)',10,40);grain(g,w,h,14)}),
 wood:()=>ctex(256,256,(g,w,h)=>{for(let x=0;x<w;x+=32){g.fillStyle=`hsl(26,${rnd(40,50)}%,${rnd(24,32)}%)`;g.fillRect(x,0,31,h);for(let k=0;k<10;k++){g.strokeStyle='rgba(20,10,0,.25)';g.beginPath();const xx=x+rnd(2,29);g.moveTo(xx,0);g.bezierCurveTo(xx+rnd(-3,3),h/3,xx+rnd(-3,3),h*2/3,xx,h);g.stroke()}}grain(g,w,h,16)}),
 grass:()=>ctex(512,512,(g,w,h)=>{g.fillStyle='#4e6a2e';g.fillRect(0,0,w,h);blot(g,w,h,60,'rgba(110,130,50,.35)',20,80);blot(g,w,h,40,'rgba(40,60,20,.35)',20,80);for(let i=0;i<6000;i++){g.fillStyle=`hsl(${rnd(70,100)},${rnd(30,50)}%,${rnd(22,45)}%)`;g.fillRect(rnd(0,w),rnd(0,h),1.2,rnd(2,6))}}),
 dirt:()=>ctex(512,512,(g,w,h)=>{g.fillStyle='#7a6246';g.fillRect(0,0,w,h);blot(g,w,h,60,'rgba(60,45,30,.3)',10,60);for(let i=0;i<900;i++){g.fillStyle=`rgba(${rnd(120,180)|0},${rnd(100,150)|0},90,.4)`;g.fillRect(rnd(0,w),rnd(0,h),2,2)}grain(g,w,h,24)}),
 road:()=>ctex(512,512,(g,w,h)=>{g.fillStyle='#3e3e42';g.fillRect(0,0,w,h);blot(g,w,h,40,'rgba(20,20,20,.3)',10,60);grain(g,w,h,26);g.fillStyle='#d8d0a0';for(let y=0;y<h;y+=128)g.fillRect(w/2-4,y,8,64);g.fillStyle='rgba(230,230,230,.8)';g.fillRect(14,0,6,h);g.fillRect(w-20,0,6,h)}),
 houseA:()=>ctex(512,512,(g,w,h)=>{g.fillStyle='#e6dccb';g.fillRect(0,0,w,h);blot(g,w,h,40,'rgba(150,130,100,.15)',20,90);grain(g,w,h,12);g.fillStyle='rgba(0,0,0,.08)';for(let y=0;y<h;y+=128)g.fillRect(0,y,w,3)}),
 houseB:()=>ctex(512,512,(g,w,h)=>{g.fillStyle='#8a4a36';g.fillRect(0,0,w,h);for(let y=0;y<h;y+=24)for(let x=((y/24)%2)*-24;x<w;x+=48){g.fillStyle=`hsl(${rnd(8,16)},${rnd(38,50)}%,${rnd(30,40)}%)`;g.fillRect(x+2,y+2,44,20)}grain(g,w,h,14)}),
 houseC:()=>ctex(512,512,(g,w,h)=>{for(let x=0;x<w;x+=40){g.fillStyle=`hsl(${rnd(195,210)},${rnd(18,28)}%,${rnd(50,60)}%)`;g.fillRect(x,0,38,h);g.fillStyle='rgba(0,0,0,.25)';g.fillRect(x+38,0,2,h)}grain(g,w,h,10)}),
 roof:()=>ctex(256,256,(g,w,h)=>{for(let y=0;y<h;y+=20)for(let x=((y/20)%2)*-16;x<w;x+=32){g.fillStyle=`hsl(${rnd(6,14)},${rnd(35,45)}%,${rnd(26,34)}%)`;g.fillRect(x+1,y+1,30,18);g.fillStyle='rgba(0,0,0,.25)';g.fillRect(x+1,y+16,30,3)}grain(g,w,h,12)}),
 concrete:()=>ctex(512,512,(g,w,h)=>{g.fillStyle='#8a8a86';g.fillRect(0,0,w,h);blot(g,w,h,50,'rgba(40,40,40,.15)',20,90);g.strokeStyle='rgba(0,0,0,.25)';g.lineWidth=3;for(let i=0;i<=w;i+=256){g.beginPath();g.moveTo(i,0);g.lineTo(i,h);g.moveTo(0,i);g.lineTo(w,i);g.stroke()}grain(g,w,h,18)}),
 floorwood:()=>ctex(512,512,(g,w,h)=>{for(let y=0;y<h;y+=32){g.fillStyle=`hsl(28,${rnd(35,45)}%,${rnd(32,42)}%)`;g.fillRect(0,y,w,31);g.fillStyle='rgba(0,0,0,.35)';g.fillRect(((y*37)%w),y,2,32);g.fillRect(((y*91)%w),y,2,32)}grain(g,w,h,12)})};
const MATS={},TXC={};const tx=k=>TXC[k]||(TXC[k]=TEX[k]());
function mat(k,o){if(MATS[k])return MATS[k];const m=new T.MeshStandardMaterial(Object.assign({map:tx(o&&o.tex||k),roughness:.88,metalness:0},o||{}));delete m.tex;m.userData.ts=(o&&o.ts)||3;MATS[k]=m;return m}
const PM=(col,r,mt)=>new T.MeshStandardMaterial({color:lin(col),roughness:r==null?.7:r,metalness:mt||0});
/* ---------------- world: boxes, terrain, raycast ---------------- */
let boxes=[],HASH=new Map(),stamp=0;const HS=8;const world=new T.Group();scene.add(world);
let TER=null;// royale terrain {N,S,h:Float32Array}
function terrH(x,z){if(!TER)return 0;const f=TER.N-1,gx=clamp(x/TER.S*f,0,f-.001),gz=clamp(z/TER.S*f,0,f-.001),ix=gx|0,iz=gz|0,fx=gx-ix,fz=gz-iz,N=TER.N,h=TER.h;return lerp(lerp(h[iz*N+ix],h[iz*N+ix+1],fx),lerp(h[(iz+1)*N+ix],h[(iz+1)*N+ix+1],fx),fz)}
function addBox(x0,y0,z0,x1,y1,z1,m,o){const b=Object.assign({x0:Math.min(x0,x1),y0,z0:Math.min(z0,z1),x1:Math.max(x0,x1),y1,z1:Math.max(z0,z1),m,st:0},o||{});boxes.push(b);return b}
function hashBoxes(){HASH.clear();for(const b of boxes){if(b.noHash)continue;for(let gx=Math.floor(b.x0/HS);gx<=Math.floor(b.x1/HS);gx++)for(let gz=Math.floor(b.z0/HS);gz<=Math.floor(b.z1/HS);gz++){const k=gx*4096+gz;let L=HASH.get(k);if(!L)HASH.set(k,L=[]);L.push(b)}}}
function nearBoxes(x0,z0,x1,z1,cb){stamp++;for(let gx=Math.floor(x0/HS);gx<=Math.floor(x1/HS);gx++)for(let gz=Math.floor(z0/HS);gz<=Math.floor(z1/HS);gz++){const L=HASH.get(gx*4096+gz);if(!L)continue;for(const b of L){if(b.st===stamp)continue;b.st=stamp;cb(b)}}}
function slab(b,ox,oy,oz,dx,dy,dz,out){let t0=0,t1=1e9,ax=-1;const A=[[ox,dx,b.x0,b.x1],[oy,dy,b.y0,b.y1],[oz,dz,b.z0,b.z1]];for(let i=0;i<3;i++){const[o,d,lo,hi]=A[i];if(Math.abs(d)<1e-9){if(o<lo||o>hi)return -1}else{let u=(lo-o)/d,v=(hi-o)/d;if(u>v){const s=u;u=v;v=s}if(u>t0){t0=u;ax=i}if(v<t1)t1=v;if(t0>t1)return -1}}if(out){out.ax=ax;out.t1=t1}return t0}
const _so={};
function ray(ox,oy,oz,dx,dy,dz,maxT,skip){let best=maxT,hit=null,bax=-1,bt1=0;stamp++;let gx=Math.floor(ox/HS),gz=Math.floor(oz/HS);const sx=dx>0?1:-1,sz=dz>0?1:-1,adx=Math.abs(dx)||1e-9,adz=Math.abs(dz)||1e-9;
  let tmx=(dx>0?(gx+1)*HS-ox:ox-gx*HS)/adx,tmz=(dz>0?(gz+1)*HS-oz:oz-gz*HS)/adz;const tdx=HS/adx,tdz=HS/adz;
  for(let it=0;it<800;it++){const L=HASH.get(gx*4096+gz);if(L)for(const b of L){if(b.st===stamp)continue;b.st=stamp;if(b.noRay||skip&&skip(b))continue;const t=slab(b,ox,oy,oz,dx,dy,dz,_so);if(t>=0&&t<best){best=t;hit=b;bax=_so.ax;bt1=_so.t1}}const tn=Math.min(tmx,tmz);if(best<=tn||tn>maxT)break;if(tmx<tmz){gx+=sx;tmx+=tdx}else{gz+=sz;tmz+=tdz}}
  if(TER){const lim=Math.min(best,maxT);let prev=0;for(let t=1.5;t<lim+1.5;t+=1.5){const tt=Math.min(t,lim),y=oy+dy*tt;if(y<terrH(ox+dx*tt,oz+dz*tt)){let a=prev,b2=tt;for(let k=0;k<6;k++){const m=(a+b2)/2;if(oy+dy*m<terrH(ox+dx*m,oz+dz*m))b2=m;else a=m}return{t:b2,b:{m:'terrain',terrain:1},ax:1,t1:b2}}prev=tt;if(tt>=lim)break}}
  return hit?{t:best,b:hit,ax:bax,t1:bt1}:null}
function groundAt(x,z,r,maxY){let g=terrH(x,z);if(TER){for(const[a,b2]of[[r,0],[-r,0],[0,r],[0,-r]]){const h=terrH(x+a,z+b2);if(h<=maxY+.05)g=Math.max(g,h*.35+g*.65)}}nearBoxes(x-r,z-r,x+r,z+r,b=>{if(b.y1<=maxY&&b.y1>g&&x+r>b.x0&&x-r<b.x1&&z+r>b.z0&&z-r<b.z1&&!b.noCol)g=b.y1});return g}
function losClear(a,b,smokeToo){const dx=b.x-a.x,dy=b.y-a.y,dz=b.z-a.z,d=Math.hypot(dx,dy,dz);if(d<.01)return true;const h=ray(a.x,a.y,a.z,dx/d,dy/d,dz/d,d,bb=>bb.glass||bb.foliage);if(h)return false;if(smokeToo)for(const s of smokes){if(s.t<1.2||s.t>s.life-1)continue;const t=clamp(((s.x-a.x)*dx+(s.y-a.y)*dy+(s.z-a.z)*dz)/(d*d),0,1);if(Math.hypot(a.x+dx*t-s.x,a.y+dy*t-s.y,a.z+dz*t-s.z)<s.r)return false}return true}
/* merged box meshes with world-space UVs + simple ambient occlusion via vertex colour darkening near ground */
function buildMeshes(){const groups={};for(const b of boxes){if(b.invis)continue;(groups[b.m]||(groups[b.m]=[])).push(b)}
  for(const k in groups){const MT=MATS[k];if(!MT)continue;const ts=MT.userData.ts||3;const P=[],N=[],U=[],C=[],I=[];
    for(const b of groups[k]){const{x0,y0,z0,x1,y1,z1}=b;const F=[[[x1,y0,z1],[0,0,z0-z1],[0,y1-y0,0],[1,0,0],'z'],[[x0,y0,z0],[0,0,z1-z0],[0,y1-y0,0],[-1,0,0],'z'],[[x0,y0,z1],[x1-x0,0,0],[0,y1-y0,0],[0,0,1],'x'],[[x1,y0,z0],[x0-x1,0,0],[0,y1-y0,0],[0,0,-1],'x'],[[x0,y1,z1],[x1-x0,0,0],[0,0,z0-z1],[0,1,0],'t'],[[x0,y0,z0],[x1-x0,0,0],[0,0,z1-z0],[0,-1,0],'t']];
      for(const[o,u,v,n,ax]of F){if(b.noTop&&n[1]===1)continue;if(b.noBottom!==false&&n[1]===-1&&y0<=.01)continue;const base=P.length/3;const vs=[o,[o[0]+u[0],o[1]+u[1],o[2]+u[2]],[o[0]+u[0]+v[0],o[1]+u[1]+v[1],o[2]+u[2]+v[2]],[o[0]+v[0],o[1]+v[1],o[2]+v[2]]];
        for(const p of vs){P.push(p[0],p[1],p[2]);N.push(n[0],n[1],n[2]);if(ax==='t')U.push(p[0]/ts,p[2]/ts);else U.push((ax==='z'?p[2]:p[0])/ts,p[1]/ts);const gy=p[1]-(b.base!=null?b.base:0);const ao=n[1]===0?(.62+.38*sstep(0,1.4,gy)):n[1]>0?1:.5;C.push(ao,ao,ao)}I.push(base,base+1,base+2,base,base+2,base+3)}}
    const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(P,3));g.setAttribute('normal',new T.Float32BufferAttribute(N,3));g.setAttribute('uv',new T.Float32BufferAttribute(U,2));g.setAttribute('color',new T.Float32BufferAttribute(C,3));g.setIndex(I);g.computeBoundingSphere();
    MT.vertexColors=true;MT.needsUpdate=true;const m=new T.Mesh(g,MT);m.castShadow=m.receiveShadow=true;world.add(m)}}
/* ---------------- navigation grid + A* ---------------- */
let MAPW=96,MAPD=80,NAV=null,NW=0,ND=0,NCS=1;
function buildNav(cs){NCS=cs;NW=Math.ceil(MAPW/cs);ND=Math.ceil(MAPD/cs);NAV=new Uint8Array(NW*ND);const pr=.42;for(const b of boxes){if(b.noCol||b.y1<.45||b.y0>1.7)continue;if(TER&&b.y1<terrH((b.x0+b.x1)/2,(b.z0+b.z1)/2)+.45)continue;const gx0=Math.max(0,Math.floor((b.x0-pr)/cs)),gx1=Math.min(NW-1,Math.floor((b.x1+pr)/cs)),gz0=Math.max(0,Math.floor((b.z0-pr)/cs)),gz1=Math.min(ND-1,Math.floor((b.z1+pr)/cs));for(let z=gz0;z<=gz1;z++)for(let x=gx0;x<=gx1;x++){const cx=(x+.5)*cs,cz=(z+.5)*cs;if(cx>b.x0-pr&&cx<b.x1+pr&&cz>b.z0-pr&&cz<b.z1+pr){if(b.y0>terrH(cx,cz)+1.7)continue;NAV[z*NW+x]=1}}}
  for(let x=0;x<NW;x++){NAV[x]=1;NAV[(ND-1)*NW+x]=1}for(let z=0;z<ND;z++){NAV[z*NW]=1;NAV[z*NW+NW-1]=1}}
function navFree(x,z){const gx=Math.floor(x/NCS),gz=Math.floor(z/NCS);if(gx<0||gz<0||gx>=NW||gz>=ND)return false;return!NAV[gz*NW+gx]}
function nearestFree(gx,gz){if(!NAV[gz*NW+gx])return[gx,gz];for(let r=1;r<10;r++)for(let dz=-r;dz<=r;dz++)for(let dx=-r;dx<=r;dx++){const x=gx+dx,z=gz+dz;if(x>0&&z>0&&x<NW&&z<ND&&!NAV[z*NW+x])return[x,z]}return[gx,gz]}
function astar(sx,sz,tx2,tz2,maxN){let[ax,az]=nearestFree(clamp(Math.floor(sx/NCS),1,NW-2),clamp(Math.floor(sz/NCS),1,ND-2));let[bx,bz]=nearestFree(clamp(Math.floor(tx2/NCS),1,NW-2),clamp(Math.floor(tz2/NCS),1,ND-2));const S=az*NW+ax,G=bz*NW+bx;if(S===G)return[[tx2,tz2]];
  const gS=new Float32Array(NW*ND).fill(1e9),from=new Int32Array(NW*ND).fill(-1),closed=new Uint8Array(NW*ND);const heap=[];const push=(n,f)=>{heap.push([f,n]);let i=heap.length-1;while(i>0){const p=(i-1)>>1;if(heap[p][0]<=heap[i][0])break;[heap[p],heap[i]]=[heap[i],heap[p]];i=p}};const pop=()=>{const top=heap[0],last=heap.pop();if(heap.length){heap[0]=last;let i=0;for(;;){const l=i*2+1,r2=l+1;let m=i;if(l<heap.length&&heap[l][0]<heap[m][0])m=l;if(r2<heap.length&&heap[r2][0]<heap[m][0])m=r2;if(m===i)break;[heap[m],heap[i]]=[heap[i],heap[m]];i=m}}return top};
  const h=n=>{const x=n%NW,z=(n/NW)|0;const dx=Math.abs(x-bx),dz=Math.abs(z-bz);return Math.max(dx,dz)+.414*Math.min(dx,dz)};gS[S]=0;push(S,h(S));let N=0,best=S,bestH=h(S);
  while(heap.length&&N<(maxN||20000)){const[,n]=pop();if(closed[n])continue;closed[n]=1;N++;if(n===G){best=n;break}const hn=h(n);if(hn<bestH){bestH=hn;best=n}const x=n%NW,z=(n/NW)|0;
    for(let dz=-1;dz<=1;dz++)for(let dx=-1;dx<=1;dx++){if(!dx&&!dz)continue;const nx=x+dx,nz=z+dz;if(nx<0||nz<0||nx>=NW||nz>=ND)continue;const m=nz*NW+nx;if(NAV[m]||closed[m])continue;if(dx&&dz&&(NAV[z*NW+nx]||NAV[nz*NW+x]))continue;const g2=gS[n]+(dx&&dz?1.414:1);if(g2<gS[m]){gS[m]=g2;from[m]=n;push(m,g2+h(m))}}}
  const path=[];let n=best;while(n!==-1&&n!==S){path.push([(n%NW+.5)*NCS,(((n/NW)|0)+.5)*NCS]);n=from[n]}path.reverse();if(best===G)path.push([tx2,tz2]);
  const out=[];let cx=sx,cz=sz;for(let i=0;i<path.length;i++){const nxt=path[i+1];if(nxt&&walkLine(cx,cz,nxt[0],nxt[1]))continue;out.push(path[i]);cx=path[i][0];cz=path[i][1]}return out}
function walkLine(ax,az,bx,bz){const d=Math.hypot(bx-ax,bz-az),n=Math.ceil(d/(NCS*.5));for(let i=1;i<=n;i++){const t=i/n;if(!navFree(ax+(bx-ax)*t,az+(bz-az)*t))return false}return true}
