/* ---------------- state ---------------- */
let players=[],me=null,state='menu',NETROLE='solo',diff=S.get(GAME+'_diff',1),nameMe=S.get('tx_name','')||('Player'+Math.floor(Math.random()*900+100)),teamPref=S.get(GAME+'_team','auto'),matchLen=S.get(GAME+'_len','short');
let round={n:0,phase:'freeze',t:0,score:{T:0,CT:0},loss:{T:1,CT:1},winner:null,buyT:0,plantedBy:null},bomb=null,grens=[],smokes=[],fires=[],feed=[],zone=null,plane=null,items=[],nextId=1,matchOver=false,WINS=9,HALF=8,mvp=null;
const fx=new T.Group();scene.add(fx);
/* sky + light */
const skyU={top:{value:new T.Color(ROY?0x4a7ac8:0x5a88c8)},hor:{value:new T.Color(ROY?0xc8dcec:0xecdcc0)},sun:{value:new V3(.45,.62,-.5).normalize()}};
{const sky=new T.Mesh(new T.SphereGeometry(ROY?1400:380,32,16),new T.ShaderMaterial({side:T.BackSide,depthWrite:false,fog:false,uniforms:skyU,vertexShader:'varying vec3 vD;void main(){vD=normalize(position);gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'uniform vec3 top,hor,sun;varying vec3 vD;float h(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float n(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(h(i),h(i+vec2(1,0)),f.x),mix(h(i+vec2(0,1)),h(i+vec2(1,1)),f.x),f.y);}void main(){float y=vD.y;vec3 c=mix(hor,top,pow(max(y,0.),.55));float s=max(dot(vD,sun),0.);c+=vec3(1.,.9,.7)*(pow(s,300.)*3.+pow(s,12.)*.18);if(y>0.){vec2 p=vD.xz/(y+.12)*2.;float cl=n(p)*.5+n(p*2.1)*.3+n(p*4.3)*.2;cl=smoothstep(.55,.8,cl)*smoothstep(0.,.25,y);c=mix(c,vec3(1.,.98,.95),cl*.8);}gl_FragColor=vec4(c,1.);}'}));sky.renderOrder=-1;scene.add(sky);st3.onFrame(()=>sky.position.copy(camera.position))}
const hemi=new T.HemisphereLight(ROY?0xcfe0ff:0xfff0dc,ROY?0x5a6a3a:0x9a7a5a,ROY?.62:.7);scene.add(hemi);const sun=new T.DirectionalLight(ROY?0xfff4e0:0xffe6c0,ROY?1.9:2.3);scene.add(sun,sun.target);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.bias=-.0004;sun.shadow.normalBias=.035;
Object.assign(sun.shadow.camera,{left:-45,right:45,top:45,bottom:-45,near:1,far:300});scene.fog=new T.Fog(ROY?0xc8d8e8:0xecdcc0,ROY?140:70,ROY?900:300);
/* ---------------- players ---------------- */
function mkPlayer(o){const p=Object.assign({id:nextId++,name:'Bot',team:'T',bot:true,peer:null,x:0,y:0,z:0,vx:0,vy:0,vz:0,yaw:0,pitch:0,hp:100,armor:0,helmet:false,kit:false,alive:true,money:800,inv:{},cur:'knife',prev:'knife',ammo:{},fireCd:0,rel:0,rcI:0,rcT:0,kickP:0,crouchT:0,onGround:true,kills:0,deaths:0,assists:0,dmgBy:{},inp:{},ai:null,flashT:0,swapT:0,scoped:0,heals:{b:0,m:0,e:0},healT:0,boost:0,chute:0,inPlane:false,spd:0,armorLv:0,helmetLv:0,ammoR:{light:0,heavy:0,shell:0,sniper:0},mvps:0,rdmg:0},o);p.mdl=mkChar(ROY?'R':p.team,p.id);scene.add(p.mdl);players.push(p);return p}
function giveW(p,id,full){const W=WPN[id];if(W.slot===4){p.inv.g=p.inv.g||[];if(p.inv.g.length<4&&(W.max?p.inv.g.filter(x=>x===id).length<W.max:!p.inv.g.includes(id)))p.inv.g.push(id);return}if(W.slot===5){p.inv[5]='bomb';return}p.inv[W.slot]=id;if(W.mag)p.ammo[id]={mag:W.mag,res:full===false?0:W.res}}
function slotW(p,s){return s===4?(p.inv.g&&p.inv.g[0]):p.inv[s]}
function equip(p,id){if(!id||p.cur===id)return;p.prev=p.cur;p.cur=id;p.swapT=(WPN[id]||{}).cls==='sniper'?.9:.55;p.rel=0;p.scoped=0;p.rcI=0;if(p===me)vmSet(true)}
function bestSlot(p){return p.inv[1]||p.inv[2]||'knife'}
function maxSpd(p){const W=WPN[p.cur]||WPN.knife;let s=(W.spd||250)*U2M;if(p.scoped)s=Math.min(s,(W.cls==='sniper'?100:150)*U2M);else if(ROY&&p.ads)s*=.72;return s}
function resetForRound(p,spawn){p.alive=true;p.hp=100;p.vx=p.vy=p.vz=0;p.x=spawn[0]+rnd(-.5,.5);p.z=spawn[1]+rnd(-.5,.5);p.y=groundAt(p.x,p.z,.3,10);p.yaw=p.team==='T'?0:PI;p.pitch=0;p.mdl.visible=true;p.mdl.rotation.set(0,0,0);p.flashT=0;p.fireCd=0;p.rel=0;p.rcI=0;p.plantT=0;p.defT=0;p.scoped=0;p.rdmg=0;p.dmgBy={};
  if(!p.inv[2])giveW(p,p.team==='T'?'glock':'usp');p.inv[3]='knife';for(const k in p.ammo){if(WPN[k]&&WPN[k].mag){p.ammo[k].mag=WPN[k].mag;p.ammo[k].res=WPN[k].res}}p.cur=bestSlot(p);p.swapT=0}
/* ---------------- movement (CS-like: fast accel, strong friction, counter-strafe) ---------------- */
function inBuyZone(p){if(ROY)return false;const z=BUYZ[p.team];return z&&p.x>z.x0&&p.x<z.x1&&p.z>z.z0&&p.z<z.z1}
function moveP(p,dt,inp){const frozen=!ROY&&round.phase==='freeze'&&round.n>0;const busy=p.plantT>0||p.defT>0||p.healT>0&&!p.boost;
  const ms=maxSpd(p)*(inp.walk?.52:1)*(p.crouchT>.5?.34:1)*(busy||frozen?0:1)*(p.healT>0?.5:1);
  const fw=(inp.f?1:0)-(inp.b?1:0),st=(inp.r?1:0)-(inp.l?1:0);let wx=-Math.sin(p.yaw)*fw+Math.cos(p.yaw)*st,wz=-Math.cos(p.yaw)*fw-Math.sin(p.yaw)*st;const wl=Math.hypot(wx,wz);if(wl>0){wx/=wl;wz/=wl}
  if(p.onGround){const sp=Math.hypot(p.vx,p.vz);if(sp>0){const drop=Math.max(sp,1.9)*5.2*dt;const ns=Math.max(0,sp-drop);p.vx*=ns/sp;p.vz*=ns/sp}if(wl>0){const cur=p.vx*wx+p.vz*wz,add=ms-cur;if(add>0){const acc=Math.min(add,5.5*ms*dt*1.6);p.vx+=wx*acc;p.vz+=wz*acc}}}
  else if(wl>0){const cur=p.vx*wx+p.vz*wz,add=Math.min(.76,ms)-cur;if(add>0){const acc=Math.min(add,12*dt);p.vx+=wx*acc;p.vz+=wz*acc}}
  p.crouchT=clamp(p.crouchT+(inp.c?1:-1)*dt*(inp.c?8:6),0,1);const H=1.8-p.crouchT*.52;
  if(inp.j&&p.onGround&&!p.jHeld&&!frozen){p.vy=6.3;p.onGround=false;if(p===me)footstep(p,1)}p.jHeld=inp.j;p.vy-=17*dt;
  const r=.36;let nx=p.x+p.vx*dt,nz=p.z+p.vz*dt;for(let pass=0;pass<2;pass++)nearBoxes(nx-r-1,nz-r-1,nx+r+1,nz+r+1,b=>{if(b.noCol||b.y1<=p.y+.4||b.y0>=p.y+H)return;const cx=clamp(nx,b.x0,b.x1),cz=clamp(nz,b.z0,b.z1),dx=nx-cx,dz=nz-cz,d=Math.hypot(dx,dz);if(d<r){if(d>1e-5){nx=cx+dx/d*r;nz=cz+dz/d*r}else{const e=[nx-b.x0,b.x1-nx,nz-b.z0,b.z1-nz],m=Math.min(...e);if(m===e[0])nx=b.x0-r;else if(m===e[1])nx=b.x1+r;else if(m===e[2])nz=b.z0-r;else nz=b.z1+r}}});
  if(TER){const hN=terrH(nx,nz),hC=terrH(p.x,p.z);if(hN-hC>.5*Math.hypot(nx-p.x,nz-p.z)+.25&&p.onGround){nx=p.x;nz=p.z}}
  p.x=clamp(nx,.5,MAPW-.5);p.z=clamp(nz,.5,MAPD-.5);let ny=p.y+p.vy*dt;const g=groundAt(p.x,p.z,r*.7,p.y+.42);
  if(ny<=g+.02&&p.vy<=0||p.onGround&&ny-g<.3&&p.vy<=0){if(p.vy<(ROY?-12.5:-10.5)&&p.alive)hurtP(p,Math.round((-p.vy-(ROY?12.5:10.5))*11),null,'fall');ny=g;p.vy=0;if(!p.onGround&&p===me)footstep(p,.8);p.onGround=true}else p.onGround=false;
  let ceil=false;nearBoxes(p.x-r,p.z-r,p.x+r,p.z+r,b=>{if(b.noCol)return;if(b.y0>p.y+.6&&b.y0<ny+H&&p.x+r>b.x0&&p.x-r<b.x1&&p.z+r>b.z0&&p.z-r<b.z1)ceil=true});if(ceil&&p.vy>0){p.vy=0;ny=p.y}
  p.y=ny;p.spd=Math.hypot(p.vx,p.vz);if(p.onGround&&p.spd>ms*.6+.3&&!inp.walk&&p.crouchT<.5){p.stepT=(p.stepT||0)-dt;if(p.stepT<=0){p.stepT=.36;footstep(p,1)}}}
/* ---------------- shooting ---------------- */
function eyeY(p){return p.y+1.64-p.crouchT*.52}
function inacc(p){const W=WPN[p.cur];if(!W||!W.st)return 0;const scoped=p.scoped&&W.sst;const base=scoped?W.sst:(p.crouchT>.5?W.cr:W.st);const ms=(W.spd||250)*U2M;const mvf=clamp((p.spd-ms*.34)/(ms*.66),0,1);let a=base+mvf*W.mv+(p.onGround?0:W.jp);if(W.cls==='sniper'&&!p.scoped)a=Math.max(a,W.st);if(ROY&&p.ads&&!scoped)a*=.5;a+=Math.min(p.rcI,14)*(W.cls==='rifle'?.0009:W.cls==='smg'?.0012:0);return a}
function partsOf(q){const e=eyeY(q),cr=q.crouchT;return[['head',q.x,e-.03,q.z,.13],['chest',q.x,q.y+1.3-cr*.45,q.z,.24],['stomach',q.x,q.y+1.02-cr*.4,q.z,.22],['legs',q.x,q.y+.62-cr*.28,q.z,.2],['legs',q.x,q.y+.28-cr*.15,q.z,.18]]}
function hitPlayers(p,ox,oy,oz,dx,dy,dz,t0,t1,skip){let best=null;for(const q of players){if(q===p||!q.alive||q.inPlane||skip&&skip.has(q))continue;if(Math.hypot(q.x-ox,q.z-oz)>t1+2)continue;for(const[part,cx,cy,cz,r]of partsOf(q)){const lx=cx-ox,ly=cy-oy,lz=cz-oz,t=lx*dx+ly*dy+lz*dz;if(t<t0||t>t1)continue;const d2=lx*lx+ly*ly+lz*lz-t*t;if(d2<r*r){const th=t-Math.sqrt(r*r-d2);if(!best||th<best.t)best={t:th,q,part}}}}return best}
function trace(p,ox,oy,oz,dx,dy,dz,W,pel){// returns end point; applies damage with wallbang
  let dmgMul=1,pp=W.cls==='sniper'?3:W.cls==='rifle'?2:W.cls==='shotgun'?0:1,t0=0,cx=ox,cy=oy,cz=oz,tot=0,hitSet=new Set();const maxR=W.maxR||220;
  for(let seg=0;seg<3;seg++){const wh=ray(cx,cy,cz,dx,dy,dz,maxR-tot);const lim=wh?wh.t:maxR-tot;const h=hitPlayers(p,cx,cy,cz,dx,dy,dz,0,lim,hitSet);
    if(h){const dist=tot+h.t;const rng=Math.pow(W.rng||.9,dist/(500*U2M));let dmg=W.dmg*rng*dmgMul*{head:4,chest:1,stomach:1.25,legs:.75}[h.part];if(W.pel&&dist>(W.maxR||25)*.5)dmg*=Math.max(.2,1-(dist-(W.maxR||25)*.5)/(W.maxR||25));
      const armored=h.part==='head'?h.q.helmet:h.part!=='legs'&&h.q.armor>0;if(armored){const absorb=ROY?[0,.3,.4,.55][h.part==='head'?h.q.helmetLv||1:h.q.armorLv||1]:(1-W.pen);h.q.armor=Math.max(0,h.q.armor-dmg*absorb*.5);dmg*=1-absorb}
      hurtP(h.q,Math.max(1,Math.round(dmg)),p,p.cur,h.part==='head',seg>0);evt({k:'blood',x:cx+dx*h.t,y:cy+dy*h.t,z:cz+dz*h.t,hs:h.part==='head'?1:0,by:p.id});hitSet.add(h.q);if(pel)return{x:cx+dx*h.t,y:cy+dy*h.t,z:cz+dz*h.t};dmgMul*=.7;continue}
    if(!wh)return{x:cx+dx*lim,y:cy+dy*lim,z:cz+dz*lim};const ix=cx+dx*wh.t,iy=cy+dy*wh.t,iz=cz+dz*wh.t;const n=wh.ax===0?[-Math.sign(dx),0,0]:wh.ax===1?[0,-Math.sign(dy),0]:[0,0,-Math.sign(dz)];if(seg===0||Math.random()<.5)evt({k:'imp',x:ix,y:iy,z:iz,nx:n[0],ny:n[1],nz:n[2],m:wh.b.m});
    const thick=(wh.t1||wh.t)-wh.t;if(pp>0&&!wh.b.terrain&&(wh.b.wood||thick<.4)&&thick<1.3){pp--;dmgMul*=wh.b.wood?.55:.35;tot+=wh.t1+.02;cx=ox+dx*tot;cy=oy+dy*tot;cz=oz+dz*tot;continue}return{x:ix,y:iy,z:iz}}return{x:cx,y:cy,z:cz}}
function fire(p,now){const id=p.cur,W=WPN[id];if(!W||p.swapT>0||!p.alive)return;
  if(W.cls==='melee'){if(p.fireCd>0)return;p.fireCd=.5;evt({k:'swing',p:p.id});const dx=-Math.sin(p.yaw)*Math.cos(p.pitch),dy=Math.sin(p.pitch),dz=-Math.cos(p.yaw)*Math.cos(p.pitch);const h=hitPlayers(p,p.x,eyeY(p),p.z,dx,dy,dz,0,1.9);if(h){const back=Math.cos(h.q.yaw-p.yaw)>.55;hurtP(h.q,back?(p.inp.alt?180:90):(p.inp.alt?65:40),p,'knife',false);evt({k:'blood',x:h.q.x,y:eyeY(h.q)-.4,z:h.q.z,by:p.id})}return}
  if(W.gren){if(p.fireCd>0)return;throwGren(p,id);return}if(W.cls==='bomb')return;
  const am=p.ammo[id];if(!am||p.fireCd>0||p.rel>0)return;if(am.mag<=0){if(am.res>0)reload(p);else{p.fireCd=.25;evt({k:'dry',p:p.id})}return}
  am.mag--;p.fireCd=60/W.rpm;if(now-p.rcT>60/W.rpm*1.8+.08&&p.rcI<1)p.rcI=0;p.rcT=now;
  const spr=inacc(p);let ry=0,rp=0;if(W.pat){const pt=PAT[W.pat],i=Math.min(Math.floor(p.rcI),pt.length-1),f=p.rcI-Math.floor(p.rcI),j=Math.min(i+1,pt.length-1);ry=lerp(pt[i][0],pt[j][0],f)*PI/180;rp=lerp(pt[i][1],pt[j][1],f)*PI/180;p.rcI+=1}else{rp=p.kickP;p.kickP+=(W.kick||1)*PI/180*.55;p.rcI+=1}
  const ox=p.x,oy=eyeY(p),oz=p.z;const pel=W.pel||1;let firstEnd=null;
  for(let k=0;k<pel;k++){const a=Math.random()*2*PI,rr=Math.sqrt(Math.random())*spr;const yaw=p.yaw-ry+Math.cos(a)*rr,pit=p.pitch+rp+Math.sin(a)*rr;const dx=-Math.sin(yaw)*Math.cos(pit),dy=Math.sin(pit),dz=-Math.cos(yaw)*Math.cos(pit);const end=trace(p,ox,oy,oz,dx,dy,dz,W,pel>1);if(k<3)evt({k:'tr',p:p.id,x:end.x,y:end.y,z:end.z});if(!firstEnd)firstEnd=end}
  evt({k:'shot',p:p.id,w:id});if(p.scoped&&W.cls==='sniper'){p.scoped=0;p.rescope=60/W.rpm}}
function reload(p){const W=WPN[p.cur],am=p.ammo[p.cur];if(!W||!am||p.rel>0||am.mag>=W.mag)return;if(ROY){if((p.ammoR[AMMOT(p.cur)]||0)<=0)return}else if(am.res<=0)return;p.rel=W.rel;p.scoped=0;evt({k:'rel',p:p.id})}
function finishReload(p){const W=WPN[p.cur],am=p.ammo[p.cur];if(!am)return;if(ROY){const t=AMMOT(p.cur),n=Math.min(W.mag-am.mag,p.ammoR[t]||0);am.mag+=n;p.ammoR[t]-=n}else{const n=Math.min(W.mag-am.mag,am.res);am.mag+=n;am.res-=n}}
function hurtP(q,dmg,by,w,hs,wb){if(!q.alive||dmg<=0)return;if(!ROY&&by&&by!==q&&by.team===q.team){if(by.bot)return;dmg=Math.round(dmg*.33);if(dmg<=0)return}const real=Math.min(q.hp,dmg);q.hp-=dmg;if(by&&by!==q){q.lastHitBy=by.id;q.dmgBy[by.id]=(q.dmgBy[by.id]||0)+real;by.rdmg=(by.rdmg||0)+real}evt({k:'hurt',p:q.id,d:dmg,from:by?by.id:0,hs:hs?1:0});if(q.bot&&by&&q.ai)q.ai.alert={x:by.x,z:by.z,t:3};if(q.hp<=0)kill(q,by,w,hs,wb)}
function kill(q,by,w,hs,wb){q.alive=false;q.hp=0;q.deaths++;q.plantT=q.defT=0;q.healT=0;
  if(by&&by!==q&&(ROY||by.team!==q.team)){by.kills++;if(!ROY)by.money=Math.min(16000,by.money+(w==='he'||w==='molotov'||w==='incgren'?300:(WPN[w]&&WPN[w].kill||300)))}for(const id in q.dmgBy){const a=pById(+id);if(a&&a!==by&&q.dmgBy[id]>=40&&(ROY||a.team!==q.team))a.assists++}
  evt({k:'kill',a:by?by.id:0,v:q.id,w:w||'',hs:hs?1:0,wb:wb?1:0},true);if(ROY)dropAll(q);else{if(q.inv[5]){q.inv[5]=null;dropBomb(q)}if(q.inv[1])dropGun(q,q.inv[1]);else if(q.inv[2]&&q.inv[2]!=='glock'&&q.inv[2]!=='usp')dropGun(q,q.inv[2]);q.inv={3:'knife'};q.ammo={};q.armor=0;q.helmet=false;q.kit=false;q.cur='knife'}}
/* ---------------- grenades ---------------- */
function throwGren(p,id){p.fireCd=1;const i=p.inv.g.indexOf(id);if(i>=0)p.inv.g.splice(i,1);const strong=!p.inp.alt;const sp=strong?16:8;const dx=-Math.sin(p.yaw)*Math.cos(p.pitch),dy=Math.sin(p.pitch)+.14,dz=-Math.cos(p.yaw)*Math.cos(p.pitch);const g=new T.Group();g.add(gunModel(id));fx.add(g);grens.push({id,x:p.x+dx*.5,y:eyeY(p)-.1,z:p.z+dz*.5,vx:dx*sp+p.vx,vy:dy*sp,vz:dz*sp+p.vz,t:0,fuse:id==='he'||id==='flash'?1.6:id==='smoke'?2.2:99,m:g,by:p.id,rest:0});evt({k:'throw',p:p.id});equip(p,(p.inv.g&&p.inv.g[0])||bestSlot(p))}
function stepGrens(dt){for(let i=grens.length-1;i>=0;i--){const g=grens[i];g.t+=dt;if(!g.rest){g.vy-=14*dt;const d=Math.hypot(g.vx,g.vy,g.vz)*dt||1e-6;const h=ray(g.x,g.y,g.z,g.vx*dt/d,g.vy*dt/d,g.vz*dt/d,d+.08);const fl=groundAt(g.x,g.z,.05,g.y+.1);
      if(h||g.y+g.vy*dt<fl+.05){const top=!h||h.ax===1;if((g.id==='molotov'||g.id==='incgren')&&top&&g.vy<0){fx.remove(g.m);grens.splice(i,1);detonate(g);continue}if(!h||h.ax===1){g.vy=-g.vy*.32;g.vx*=.62;g.vz*=.62;if(!h)g.y=fl+.05}else if(h.ax===0)g.vx=-g.vx*.45;else g.vz=-g.vz*.45;if(Math.hypot(g.vx,g.vy,g.vz)>1.5)evt({k:'bounce',x:g.x,y:g.y,z:g.z});if(Math.hypot(g.vx,g.vy,g.vz)<.6&&(!h||h.ax===1))g.rest=1}
      else{g.x+=g.vx*dt;g.y+=g.vy*dt;g.z+=g.vz*dt}g.m.rotation.x+=dt*9;g.m.rotation.z+=dt*5}
    g.m.position.set(g.x,g.y,g.z);if(g.t>=g.fuse||(g.id==='smoke'&&g.rest&&g.t>1.2)){fx.remove(g.m);grens.splice(i,1);detonate(g)}}}
function detonate(g){const by=pById(g.by);evt({k:'gren',id:g.id,x:g.x,y:g.y,z:g.z},true);
  if(g.id==='he'){for(const q of players){if(!q.alive)continue;const d=Math.hypot(q.x-g.x,q.y+1-g.y,q.z-g.z);if(d<8.5&&losClear({x:g.x,y:g.y+.3,z:g.z},{x:q.x,y:q.y+1,z:q.z})){let dmg=98*Math.pow(1-d/8.5,1.4);if(q.armor>0){dmg*=.5;q.armor=Math.max(0,q.armor-dmg*.5)}hurtP(q,Math.round(dmg),by,'he')}}}
  if(g.id==='flash'){for(const q of players){if(!q.alive)continue;const e={x:q.x,y:eyeY(q),z:q.z};const d=Math.hypot(e.x-g.x,e.y-g.y,e.z-g.z);if(d>35||!losClear({x:g.x,y:g.y+.15,z:g.z},e))continue;const fdx=-Math.sin(q.yaw)*Math.cos(q.pitch),fdy=Math.sin(q.pitch),fdz=-Math.cos(q.yaw)*Math.cos(q.pitch),dot=((g.x-e.x)*fdx+(g.y-e.y)*fdy+(g.z-e.z)*fdz)/(d||1);const t=(dot>.5?4.8:dot>0?2.6:dot>-.5?1.1:.5)*clamp(1.15-d/35,0,1);q.flashT=Math.max(q.flashT,t);q.flashMax=Math.max(q.flashT,q.flashMax||0)}}
  if(g.id==='smoke'){smokes.push({x:g.x,y:g.y+1.6,z:g.z,r:4.3,t:0,life:18});fires=fires.filter(f=>Math.hypot(f.x-g.x,f.z-g.z)>f.r+2)}
  if(g.id==='molotov'||g.id==='incgren'){if(smokes.some(s=>Math.hypot(s.x-g.x,s.z-g.z)<s.r)){evt({k:'fizz',x:g.x,z:g.z});return}fires.push({x:g.x,y:groundAt(g.x,g.z,.1,g.y+.3),z:g.z,r:3.2,t:0,life:7,by:g.by,tick:0})}}
function stepFires(dt){for(let i=fires.length-1;i>=0;i--){const f=fires[i];f.t+=dt;f.tick-=dt;if(smokes.some(s=>s.t>1&&Math.hypot(s.x-f.x,s.z-f.z)<s.r+f.r*.5))f.t=f.life;if(f.tick<=0){f.tick=.25;for(const q of players){if(!q.alive)continue;if(Math.hypot(q.x-f.x,q.z-f.z)<f.r&&Math.abs(q.y-f.y)<1.2)hurtP(q,7,pById(f.by),'molotov')}}if(f.t>=f.life){if(f.m)f.m.forEach(m=>fx.remove(m));fires.splice(i,1)}}}
/* ---------------- bomb ---------------- */
function dropBomb(p){bomb={st:'dropped',x:p.x,y:groundAt(p.x,p.z,.2,p.y+.5)+.05,z:p.z,t:0};evt({k:'bombdrop'},true)}
function inSite(x,z){for(const k in SITES){const s=SITES[k];if(x>s.x0&&x<s.x1&&z>s.z0&&z<s.z1)return k}return null}
function stepBombActions(p,dt,inp){if(!p.alive)return;
  const eP=p.team==='T'&&p.inv[5]&&inp.use&&inSite(p.x,p.z)&&round.phase==='live'&&p.onGround;if(eP&&p.cur!=='bomb')equip(p,'bomb');if(p.team==='T'&&p.cur==='bomb'&&(inp.fire||eP)&&p.onGround&&inSite(p.x,p.z)&&round.phase==='live'){if(!p.plantT)evt({k:'planting',p:p.id});p.plantT+=dt;if(p.plantT>=3.2){p.plantT=0;p.inv[5]=null;bomb={st:'planted',x:p.x-Math.sin(p.yaw)*.4,y:groundAt(p.x,p.z,.2,p.y+.5)+.05,z:p.z-Math.cos(p.yaw)*.4,t:0,site:inSite(p.x,p.z),beep:0};p.money=Math.min(16000,p.money+300);round.plantedBy=p.id;equip(p,bestSlot(p));evt({k:'plant',p:p.id},true)}}else p.plantT=0;
  if(p.team==='CT'&&bomb&&bomb.st==='planted'&&inp.use&&Math.hypot(p.x-bomb.x,p.z-bomb.z)<1.7&&p.onGround){if(!p.defT)evt({k:'defusing',p:p.id,kit:p.kit?1:0});p.defT+=dt;if(p.defT>=(p.kit?5:10)){bomb.st='defused';p.defT=0;p.money=Math.min(16000,p.money+300);evt({k:'defused',p:p.id},true);endRound('CT','The bomb has been defused',p)}}else p.defT=0;
  if(p.team==='T'&&bomb&&bomb.st==='dropped'&&Math.hypot(p.x-bomb.x,p.z-bomb.z)<1.2){p.inv[5]='bomb';bomb=null;evt({k:'bombpick',p:p.id},true)}
  if(inp.use&&!p.useHeld){let best=null,bd=1.8;for(const it of items){const d=Math.hypot(it.x-p.x,it.z-p.z);if(d<bd&&Math.abs(it.y-p.y)<2){bd=d;best=it}}if(best)pickUp(p,best)}p.useHeld=inp.use}
/* ---------------- items (breach drops, royale loot) ---------------- */
function mkItem(o){const it=Object.assign({id:nextId++,t:'gun',w:null,x:0,y:0,z:0},o);const g=new T.Group();
  if(it.t==='gun'){const gg=gunModel(it.w);gg.rotation.z=PI/2;gg.rotation.y=Math.random()*6;gg.position.y=.05;g.add(gg)}
  else if(it.t==='box'){const b=new T.Mesh(new T.BoxGeometry(.8,.5,.55),PM(0x3a4a2a,.7));b.position.y=.25;g.add(b);const lid=new T.Mesh(new T.BoxGeometry(.84,.08,.6),PM(0x2a3620,.7));lid.position.y=.52;g.add(lid)}
  else{const colr={ammo:0x8a7a3a,vest:[0,0x6a6a6a,0x3a5a8a,0x7a3aa8][it.lv||1],helm:[0,0x6a6a6a,0x3a5a8a,0x7a3aa8][it.lv||1],band:0xf0f0f0,med:0xe83a3a,drink:0x3ab0e8}[it.t]||0x888888;const b=new T.Mesh(it.t==='helm'?new T.SphereGeometry(.16,12,8,0,2*PI,0,PI/2):it.t==='drink'?new T.CylinderGeometry(.05,.05,.16,10):new T.BoxGeometry(it.t==='ammo'?.3:.36,it.t==='vest'?.42:.16,.26),PM(colr,.55));b.position.y=it.t==='vest'?.21:.08;g.add(b);if(it.t==='med'||it.t==='band'){const cr=new T.Mesh(new T.BoxGeometry(.2,.02,.06),new T.MeshBasicMaterial({color:it.t==='med'?0xffffff:0xe83a3a}));cr.position.y=.17;g.add(cr);const cr2=cr.clone();cr2.rotation.y=PI/2;g.add(cr2)}if(it.t==='ammo'){const lb=new T.Mesh(new T.BoxGeometry(.31,.06,.27),new T.MeshBasicMaterial({color:{light:0xe8c84a,heavy:0x4ae86a,shell:0xe84a4a,sniper:0x4a8ae8}[it.a]||0xffffff}));lb.position.y=.1;g.add(lb)}}
  const rar=it.t==='gun'?(ROYW[it.w]||0):it.t==='vest'||it.t==='helm'?(it.lv||1):it.t==='box'?4:0;const glow=new T.Mesh(new T.RingGeometry(.3,.44,24).rotateX(-PI/2),new T.MeshBasicMaterial({color:new T.Color(RARITY[rar][0]),transparent:true,opacity:.55,depthWrite:false}));glow.position.y=.02;g.add(glow);it.glow=glow;
  g.position.set(it.x,it.y,it.z);fx.add(g);it.m=g;items.push(it);itemsDirty=true;return it}
function takeItem(it){fx.remove(it.m);const i=items.indexOf(it);if(i>=0)items.splice(i,1);itemsDirty=true}
function dropGun(p,w){const am=p.ammo[w];mkItem({t:'gun',w,x:p.x+rnd(-.5,.5),y:groundAt(p.x,p.z,.2,p.y+.5)+.02,z:p.z+rnd(-.5,.5),mag:am?am.mag:0,res:am?am.res:0})}
function dropAll(p){const cont=[];for(const s of[1,2,3]){const w=p.inv[s];if(w&&w!=='knife')cont.push({t:'gun',w,mag:p.ammo[w]?p.ammo[w].mag:0})}for(const a in p.ammoR)if(p.ammoR[a]>0)cont.push({t:'ammo',a,n:p.ammoR[a]});if(p.armorLv)cont.push({t:'vest',lv:p.armorLv,ar:p.armor});if(p.helmetLv)cont.push({t:'helm',lv:p.helmetLv});['b','m','e'].forEach(k=>{for(let i=0;i<p.heals[k];i++)cont.push({t:{b:'band',m:'med',e:'drink'}[k]})});
  if(cont.length)mkItem({t:'box',x:p.x,y:groundAt(p.x,p.z,.3,p.y+.5),z:p.z,cont,who:p.name});p.inv={3:'knife'};p.ammo={};p.cur='knife'}
function applyLoot(p,it){if(it.t==='gun'){const W=WPN[it.w],s=W.slot;if(ROY&&s===1&&p.inv[1]&&!p.inv[4]&&p.inv[1]!==it.w){p.inv[4]=it.w}else if(ROY&&s===2&&p.inv[2]&&!p.inv[1]){p.inv[1]=it.w}else{if(p.inv[s]&&!ROY)dropGun(p,p.inv[s]);else if(p.inv[s]&&ROY){mkItem({t:'gun',w:p.inv[s],x:p.x+rnd(-.6,.6),y:p.y+.02,z:p.z+rnd(-.6,.6),mag:p.ammo[p.inv[s]]?p.ammo[p.inv[s]].mag:0})}p.inv[s]=it.w}
    p.ammo[it.w]={mag:it.mag!=null?it.mag:W.mag,res:it.res!=null?it.res:(ROY?0:W.res)};if(ROY&&it.mag==null)p.ammoR[AMMOT(it.w)]=(p.ammoR[AMMOT(it.w)]||0)+W.mag;if(!WPN[p.cur]||WPN[p.cur].cls==='melee'||p.cur===undefined)equip(p,it.w)}
  else if(it.t==='ammo'){const a=it.a||'light';p.ammoR[a]=(p.ammoR[a]||0)+(it.n||{light:60,heavy:60,shell:16,sniper:15}[a])}
  else if(it.t==='vest'){if((it.lv||1)>p.armorLv||p.armor<40){p.armorLv=it.lv||1;p.armor=it.ar!=null?it.ar:100}}else if(it.t==='helm'){if((it.lv||1)>p.helmetLv){p.helmetLv=it.lv||1;p.helmet=true}}else if(it.t==='band')p.heals.b++;else if(it.t==='med')p.heals.m++;else if(it.t==='drink')p.heals.e++}
function pickUp(p,it){if(it.t==='box'){it.cont.forEach(c2=>applyLoot(p,c2));evt({k:'pick',p:p.id,t:'box'});takeItem(it);return}applyLoot(p,it);evt({k:'pick',p:p.id,t:it.t,w:it.w});takeItem(it)}
let itemsDirty=true;
/* ---------------- round logic (breach) ---------------- */
function teamAlive(t){return players.filter(p=>p.team===t&&p.alive).length}
function startRound(){round.n++;const half=round.n===HALF+1;if(half){players.forEach(p=>{p.team=p.team==='T'?'CT':'T';scene.remove(p.mdl);p.mdl=mkChar(p.team,p.id);scene.add(p.mdl);p.money=800;p.inv={3:'knife'};p.ammo={};p.armor=0;p.helmet=false;p.kit=false;p.alive=false});const s=round.score.T;round.score.T=round.score.CT;round.score.CT=s;round.loss={T:1,CT:1};msgC('HALFTIME','Switching sides',3);say('Halftime. Switching sides')}
  round.phase='freeze';round.t=round.n===1||half?12:10;round.buyT=round.t+20;round.winner=null;round.plantedBy=null;bomb=null;smokes.forEach(s=>s.puffs&&s.puffs.forEach(m=>fx.remove(m)));smokes=[];fires.forEach(f=>f.m&&f.m.forEach(m=>fx.remove(m)));fires=[];grens.forEach(g=>fx.remove(g.m));grens=[];items.slice().forEach(takeItem);mvp=null;
  const tSp=SPAWN.T.slice(),ctSp=SPAWN.CT.slice();players.forEach(p=>{const sp=p.team==='T'?tSp.shift()||SPAWN.T[0]:ctSp.shift()||SPAWN.CT[0];if(!p.alive){p.inv={3:'knife'};p.ammo={};p.armor=0;p.helmet=false;p.kit=false}resetForRound(p,sp);p.inv[5]=null});
  const ts=players.filter(p=>p.team==='T');if(ts.length){const pool=ts.filter(p=>p.bot);const c2=pool.length&&Math.random()<.75?pick(pool):pick(ts);c2.inv[5]='bomb'}
  const plan=pick(['A','B','A','B','split','mid']);players.forEach(p=>{if(p.bot){botBuy(p);p.ai=newAI(p,plan)}});
  if(round.n===1)msgC('Round 1',me?(me.team==='T'?'Buy with B, then plant the C4 at A or B':'Buy with B, then defend sites A and B'):'',3);evt({k:'rstart',n:round.n},true)}
function endRound(w,why,hero){if(round.phase==='post')return;round.phase='post';round.t=6;round.winner=w;round.score[w]++;const l=w==='T'?'CT':'T';
  const reward=why.includes('defused')||why.includes('exploded')?3500:3250;players.forEach(p=>{if(p.team===w)p.money=Math.min(16000,p.money+reward);else{const lb=[1400,1900,2400,2900,3400][Math.min(4,round.loss[l]-1)];p.money=Math.min(16000,p.money+lb+(l==='T'&&round.plantedBy?800:0))}});round.loss[w]=Math.max(1,round.loss[w]-1);round.loss[l]=Math.min(5,round.loss[l]+1);
  mvp=hero||players.filter(p=>p.team===w).sort((a,b)=>(b.rdmg||0)-(a.rdmg||0))[0];if(mvp)mvp.mvps++;evt({k:'round',w,why,mvp:mvp?mvp.id:0},true);
  const maxR=HALF*2;if(round.score[w]>=WINS||round.n>=maxR&&round.score.T===round.score.CT){matchOver=true;setTimeout(()=>{if(state==='play'&&NETROLE!=='client')evt({k:'match',w:round.score.T===round.score.CT?'draw':w},true)},3000)}}
function stepRound(dt){round.t-=dt;round.buyT-=dt;if(round.phase==='freeze'&&round.t<=0){round.phase='live';round.t=115;msgC('','',.1);evt({k:'go'},true)}
  if(round.phase==='live'){if(!bomb||bomb.st!=='planted'){if(teamAlive('T')===0&&players.some(p=>p.team==='T'))endRound('CT','All terrorists eliminated');else if(teamAlive('CT')===0&&players.some(p=>p.team==='CT'))endRound('T','All counter-terrorists eliminated');else if(round.t<=0)endRound('CT','Time ran out')}
    else if(teamAlive('CT')===0)endRound('T','All counter-terrorists eliminated')}
  if(bomb&&bomb.st==='planted'){bomb.t+=dt;const left=40-bomb.t;bomb.beep-=dt;if(bomb.beep<=0){bomb.beep=left>20?1:left>10?.6:left>5?.35:left>2?.18:.1;evt({k:'beep',x:bomb.x,z:bomb.z})}
    if(bomb.t>=40){bomb.st='boom';evt({k:'boom',x:bomb.x,y:bomb.y,z:bomb.z},true);for(const p of players){if(!p.alive)continue;const d=Math.hypot(p.x-bomb.x,p.z-bomb.z);if(d<20)hurtP(p,Math.round(d<6?500:180*Math.pow(1-d/20,1.5)*(p.armor>0?.6:1)),null,'bomb')}if(round.phase!=='post')endRound('T','The bomb has exploded',pById(round.plantedBy))}}
  if(round.phase==='post'&&round.t<=0&&!matchOver)startRound()}
/* ---------------- buying ---------------- */
function canBuy(p){return !ROY&&p.alive&&round.buyT>0&&round.phase!=='post'&&inBuyZone(p)}
function buy(p,id){if(!canBuy(p))return false;const W=WPN[id],G=GEAR[id];const item=W||G;if(!item)return false;let price=item.price;if(id==='vesthelm'&&p.armor>=100)price=350;if(!price||p.money<price)return false;if(item.side&&item.side!==p.team)return false;
  if(G){if(id==='vest'){if(p.armor>=100)return false;p.armor=100}else if(id==='vesthelm'){if(p.armor>=100&&p.helmet)return false;p.armor=100;p.helmet=true}else if(id==='kit'){if(p.kit)return false;p.kit=true}}
  else if(W.slot===4){p.inv.g=p.inv.g||[];const cnt=p.inv.g.filter(x=>x===id).length;if(p.inv.g.length>=4||cnt>=(W.max||1))return false;p.inv.g.push(id)}
  else{if(p.inv[W.slot]===id)return false;const def=p.team==='T'?'glock':'usp';if(p.inv[W.slot]&&p.inv[W.slot]!==def)dropGun(p,p.inv[W.slot]);giveW(p,id);equip(p,id)}
  p.money-=price;return true}
function botBuy(p){const m=p.money,t=p.team,eco=m<2000&&round.n!==1&&round.n!==HALF+1;if(eco){if(m>=500&&Math.random()<.4)buy(p,'p250');return}
  if(round.n===1||round.n===HALF+1){if(Math.random()<.5)buy(p,'vest');else if(Math.random()<.5)buy(p,t==='T'?'tec9':'p250');else buy(p,'flash');return}
  if(m>=4750+1000&&Math.random()<.18)buy(p,'awp');else if(m>=3700)buy(p,t==='T'?'ak':(Math.random()<.5?'m4a4':'m4a1s'));else if(m>=2900)buy(p,t==='T'?'galil':'famas');else if(m>=1800)buy(p,t==='T'?'mac10':'mp9');
  buy(p,'vesthelm');buy(p,'vest');if(t==='CT')buy(p,'kit');for(const g2 of[pick(['smoke','flash']),'flash','he',t==='T'?'molotov':'incgren'])if(p.money>=600&&Math.random()<.55)buy(p,g2)}
/* ---------------- royale logic ---------------- */
const ZPH=[[60,40,150],[45,35,90],[40,25,55],[30,20,30],[25,15,15],[20,15,5],[15,10,0]];
function royaleStart(){zone={cx:200,cz:200,r:300,phase:'wait',i:0,t:ZPH[0][0],nx:null,nz:null,nr:null,dmg:1};const R2=mulberry(seed+7);
  items.slice().forEach(takeItem);const guns=Object.keys(ROYW);const pickG=tier=>{const w=guns.map(g=>{const r=ROYW[g];return tier>=3?(r>=2?3:.4):tier>=2?(r>=1&&r<=3?2:.5):(r<=1?3:r===2?1:r===3?.35:.08)});let t=R2()*w.reduce((a,b)=>a+b,0);for(let i=0;i<guns.length;i++){t-=w[i];if(t<=0)return guns[i]}return'ump'};
  LOOT.forEach(l=>{const tier=l.tier||1;const r2=R2();const P2={x:l.x,y:l.y,z:l.z};if(r2<.36)mkItem(Object.assign({t:'gun',w:pickG(tier)},P2));else if(r2<.6)mkItem(Object.assign({t:'ammo',a:pick(['light','light','heavy','heavy','shell','sniper'])},P2));else if(r2<.69)mkItem(Object.assign({t:'vest',lv:tier>=3?2+Math.floor(R2()*2):1+Math.floor(R2()*R2()*3)},P2));else if(r2<.76)mkItem(Object.assign({t:'helm',lv:tier>=3?2+Math.floor(R2()*2):1+Math.floor(R2()*R2()*3)},P2));else if(r2<.88)mkItem(Object.assign({t:'band'},P2));else if(r2<.95)mkItem(Object.assign({t:'med'},P2));else mkItem(Object.assign({t:'drink'},P2))});
  const a=R2()*PI*2;plane={x0:200+Math.cos(a)*260,z0:200+Math.sin(a)*260,dx:-Math.cos(a),dz:-Math.sin(a),t:0,len:520,sp:70,y:230};buildPlane();
  players.forEach(p=>{p.alive=true;p.hp=100;p.armor=0;p.armorLv=0;p.helmet=false;p.helmetLv=0;p.inv={3:'knife'};p.ammo={};p.ammoR={light:0,heavy:0,shell:0,sniper:0};p.cur='knife';p.heals={b:0,m:0,e:0};p.inPlane=true;p.chute=0;p.kills=0;p.mdl.visible=false;p.mdl.rotation.set(0,0,0);p.place=0;p.dmgDone=0;if(p.bot)p.ai=newAI(p)});
  msgC('LAST DROP','Open the map (M) to see the flight path · SPACE to jump',4)}
function buildPlane(){if(plane.m)scene.remove(plane.m);const pm=new T.Group();const bM=PM(0x7a8088,.45,.4),dM=PM(0x4a5058,.5,.3);const bd=new T.Mesh(new T.CylinderGeometry(2.4,2.1,28,16),bM);bd.rotation.x=PI/2;pm.add(bd);const nose=new T.Mesh(new T.SphereGeometry(2.4,16,10,0,2*PI,0,PI/2),bM);nose.rotation.x=-PI/2;nose.position.z=-14;pm.add(nose);const wg=new T.Mesh(new T.BoxGeometry(38,.45,5),bM);wg.position.set(0,1,-2);pm.add(wg);const tl=new T.Mesh(new T.BoxGeometry(.5,6,4),bM);tl.position.set(0,3.5,12);pm.add(tl);const ts=new T.Mesh(new T.BoxGeometry(12,.35,3),bM);ts.position.set(0,1.2,12.5);pm.add(ts);
  [-9,-5,5,9].forEach(x=>{const en=new T.Mesh(new T.CylinderGeometry(.8,.8,3,12),dM);en.rotation.x=PI/2;en.position.set(x,.3,-3.5);pm.add(en);const pr=new T.Mesh(new T.CylinderGeometry(1.6,1.6,.05,20),new T.MeshBasicMaterial({color:0x222222,transparent:true,opacity:.25}));pr.rotation.x=PI/2;pr.position.set(x,.3,-5.1);pm.add(pr)});const ramp=new T.Mesh(new T.BoxGeometry(3.4,.2,4),dM);ramp.position.set(0,-1.7,14.8);ramp.rotation.x=-.4;pm.add(ramp);pm.traverse(o=>{if(o.isMesh)o.castShadow=true});plane.m=pm;scene.add(pm)}
function planePos(){const d=Math.min(plane.len,plane.t*plane.sp);return{x:plane.x0+plane.dx*d,z:plane.z0+plane.dz*d}}
function stepRoyale(dt){if(!plane)return;plane.t+=dt;const pp=planePos();plane.m.position.set(pp.x,plane.y,pp.z);plane.m.rotation.y=Math.atan2(-plane.dx,-plane.dz);plane.m.visible=plane.t*plane.sp<plane.len+300;if(plane.t*plane.sp>=plane.len)players.forEach(p=>{if(p.inPlane)jumpOut(p)});
  const Z=zone;Z.t-=dt;if(Z.phase==='wait'){if(Z.nr==null){const ph=ZPH[Z.i];const maxOff=Math.max(0,Math.min(Z.r,250)-ph[2]);const a=rnd(0,2*PI),o=Math.random()*maxOff*.8;Z.nx=clamp(Z.cx+Math.cos(a)*o,30,370);Z.nz=clamp(Z.cz+Math.sin(a)*o,30,370);Z.nr=ph[2];Z.or=Z.r;Z.ocx=Z.cx;Z.ocz=Z.cz}if(Z.t<=0){Z.phase='shrink';Z.t=ZPH[Z.i][1];Z.T=Z.t;msgC('The zone is closing','',2.5)}}
  else if(Z.phase==='shrink'){const k=1-Math.max(0,Z.t)/Z.T;Z.r=lerp(Z.or,Z.nr,k);Z.cx=lerp(Z.ocx,Z.nx,k);Z.cz=lerp(Z.ocz,Z.nz,k);if(Z.t<=0){Z.i++;Z.dmg=[1,2,3,5,8,10,15,20][Z.i]||20;if(Z.i<ZPH.length){Z.phase='wait';Z.t=ZPH[Z.i][0];Z.nr=null}else Z.phase='final'}}
  Z.tick=(Z.tick||0)-dt;if(Z.tick<=0&&!matchOver){Z.tick=1;const al=players.filter(p=>p.alive&&!p.inPlane);const out=al.filter(p=>Math.hypot(p.x-Z.cx,p.z-Z.cz)>Z.r);let spare=null;if(al.length>1&&out.length===al.length&&al.every(p=>p.hp<=Z.dmg))spare=al.slice().sort((a,b)=>b.hp-a.hp||b.kills-a.kills)[0];for(const p of out)if(p!==spare)hurtP(p,Z.dmg,null,'zone')}
  for(const p of players)if(!p.alive&&!p.place)p.place=players.filter(q=>q.alive).length+1;
  const alive=players.filter(p=>p.alive);if(alive.length<=1&&players.length>1&&!matchOver){matchOver=true;const w=alive[0];if(w)w.place=1;evt({k:'rwin',p:w?w.id:0},true)}}
function jumpOut(p){if(!p.inPlane)return;const pp=planePos();p.inPlane=false;p.x=pp.x+rnd(-3,3);p.z=pp.z+rnd(-3,3);p.y=plane.y-4;p.vy=0;p.vx=plane.dx*18;p.vz=plane.dz*18;p.chute=0;p.air=true;p.mdl.visible=true;p.onGround=false;evt({k:'jump',p:p.id});if(p===me)msgC('Skydiving','WASD to steer · look down to dive faster · chute opens by itself',3)}
function stepAir(p,dt,inp){const fw=(inp.f?1:0)-(inp.b?1:0),st=(inp.r?1:0)-(inp.l?1:0);const dive=!p.chute&&p.pitch<-.6&&inp.f;const hs=p.chute?9:dive?30:20;const wx=-Math.sin(p.yaw)*fw+Math.cos(p.yaw)*st,wz=-Math.cos(p.yaw)*fw-Math.sin(p.yaw)*st;p.vx+=(wx*hs-p.vx)*Math.min(1,dt*1.3);p.vz+=(wz*hs-p.vz)*Math.min(1,dt*1.3);
  const g=groundAt(p.x,p.z,.3,p.y);if(!p.chute&&(p.y-g<75||inp.j&&p.y-g<170&&p.air>1)){p.chute=1;evt({k:'chute',p:p.id})}p.air=(p.air===true?1:p.air||1)+dt;const tvy=p.chute?-5.5:dive?-62:-42;p.vy+=(tvy-p.vy)*Math.min(1,dt*(p.chute?2.2:.9));
  p.x=clamp(p.x+p.vx*dt,2,MAPW-2);p.z=clamp(p.z+p.vz*dt,2,MAPD-2);p.y+=p.vy*dt;if(p.y<=g){p.y=g;p.vy=0;p.chute=0;p.onGround=true;p.air=false;evt({k:'land',p:p.id})}}
function useHeal(p){if(p.healT>0)return;if(p.heals.m>0&&p.hp<80){p.heals.m--;p.healT=6;p.healAmt=100;p.healKind='m'}else if(p.heals.b>0&&p.hp<75){p.heals.b--;p.healT=3;p.healAmt=Math.min(75,p.hp+15);p.healKind='b'}else if(p.heals.e>0&&p.boost<60){p.heals.e--;p.healT=3;p.healKind='e'}else return;evt({k:'heal',p:p.id})}
