/* ---------------- audio (positional) ---------------- */
let nBuf=null;function nbuf(a){if(!nBuf){const n=Math.floor(a.sampleRate*1.2);nBuf=a.createBuffer(1,n,a.sampleRate);const d=nBuf.getChannelData(0);for(let i=0;i<n;i++)d[i]=Math.random()*2-1}return nBuf}
function lsnPan(x,z){if(!camera)return[0,1];const dx=x-camera.position.x,dz=z-camera.position.z,d=Math.hypot(dx,dz);if(d<.5)return[0,d];const yaw=me?me.yaw:0;const rx=Math.cos(yaw),rz=-Math.sin(yaw);return[clamp((dx*rx+dz*rz)/d,-1,1)*.8,d]}
function play(x,z,o){if(muted)return;try{const a=ac(),t=a.currentTime;const[pan,d]=x==null?[0,0]:lsnPan(x,z);const range=o.range||60;let vol=o.vol*(x==null?1:Math.pow(clamp(1-d/range,0,1),1.6));if(o.occl&&x!=null&&d>3&&!losClear({x:camera.position.x,y:camera.position.y,z:camera.position.z},{x,y:(o.y||1.2),z}))vol*=.45;if(vol<.003)return;
  const P=a.createStereoPanner?a.createStereoPanner():null;const G2=a.createGain();G2.gain.value=vol;if(P){P.pan.value=pan;G2.connect(P);P.connect(a.destination)}else G2.connect(a.destination);
  if(o.noise){const s=a.createBufferSource();s.buffer=nbuf(a);s.playbackRate.value=o.rate||1;const f=a.createBiquadFilter();f.type=o.ft||'lowpass';f.frequency.value=(o.f||2000)*(x==null?1:clamp(1.3-d/range,.35,1.2));if(o.q)f.Q.value=o.q;const e=a.createGain();e.gain.setValueAtTime(1,t);e.gain.exponentialRampToValueAtTime(.001,t+o.dur);s.connect(f);f.connect(e);e.connect(G2);s.start(t,Math.random()*.8,o.dur+.05)}
  if(o.tone){const os=a.createOscillator();os.type=o.wave||'sine';os.frequency.setValueAtTime(o.tone,t);if(o.tone2)os.frequency.exponentialRampToValueAtTime(o.tone2,t+o.tdur);const e=a.createGain();e.gain.setValueAtTime(o.tvol||.6,t);e.gain.exponentialRampToValueAtTime(.001,t+o.tdur);os.connect(e);e.connect(G2);os.start(t);os.stop(t+o.tdur+.02)}}catch(e){}}
const GSND={pistol:{f:3200,dur:.16,tone:170,tdur:.08,vol:.42},sup:{f:1500,dur:.08,tone:300,tdur:.04,vol:.22,range:30},deagle:{f:2200,dur:.32,tone:90,tdur:.16,vol:.6},smg:{f:3000,dur:.11,tone:160,tdur:.06,vol:.36},shotgun:{f:1600,dur:.34,tone:80,tdur:.2,vol:.62},rifle:{f:2600,dur:.17,tone:120,tdur:.1,vol:.5},ak:{f:2300,dur:.2,tone:95,tdur:.12,vol:.55},m4:{f:3000,dur:.15,tone:130,tdur:.08,vol:.48},sniper:{f:2000,dur:.35,tone:80,tdur:.2,vol:.6,range:160},awp:{f:1500,dur:.55,tone:60,tdur:.35,vol:.75,range:200}};
function gunSound(p,w){const S2=GSND[(WPN[w]||{}).snd]||GSND.rifle;const loc=p===me;play(loc?null:p.x,loc?null:p.z,{noise:1,f:S2.f,dur:S2.dur,tone:S2.tone,tone2:S2.tone*.5,tdur:S2.tdur,wave:'square',tvol:.35,vol:S2.vol*(loc?.9:1),range:S2.range||110})}
function footstep(p,v){if(p===me&&!p.alive)return;const loc=p===me;play(loc?null:p.x,loc?null:p.z,{noise:1,f:loc?700:900,dur:.07,vol:(loc?.06:.22)*v,range:26,occl:1,y:p.y+.2})}
function say(t){if(muted)return;try{const u=new SpeechSynthesisUtterance(t);u.rate=1.05;u.pitch=.85;u.volume=.75;speechSynthesis.cancel();speechSynthesis.speak(u)}catch(e){}}
/* ---------------- effects ---------------- */
const TR_N=240,trGeo=new T.BufferGeometry();trGeo.setAttribute('position',new T.Float32BufferAttribute(new Float32Array(TR_N*6),3));const trLines=new T.LineSegments(trGeo,new T.LineBasicMaterial({color:0xffe8a0,transparent:true,opacity:.75}));trLines.frustumCulled=false;scene.add(trLines);const tracers=[];
const spr=(fn)=>{const cv=document.createElement('canvas');cv.width=cv.height=64;fn(cv.getContext('2d'));const t=new T.CanvasTexture(cv);return t};
const puffTex=spr(g=>{const gr=g.createRadialGradient(32,32,0,32,32,32);gr.addColorStop(0,'rgba(255,255,255,1)');gr.addColorStop(.5,'rgba(255,255,255,.45)');gr.addColorStop(1,'rgba(255,255,255,0)');g.fillStyle=gr;g.fillRect(0,0,64,64)});
const flashTex=spr(g=>{g.translate(32,32);for(let i=0;i<6;i++){g.rotate(PI/3);const gr=g.createLinearGradient(0,0,30,0);gr.addColorStop(0,'rgba(255,240,200,1)');gr.addColorStop(1,'rgba(255,160,40,0)');g.fillStyle=gr;g.beginPath();g.moveTo(0,-4);g.lineTo(30,0);g.lineTo(0,4);g.fill()}const gr=g.createRadialGradient(0,0,0,0,0,14);gr.addColorStop(0,'rgba(255,255,230,1)');gr.addColorStop(1,'rgba(255,200,80,0)');g.fillStyle=gr;g.fillRect(-16,-16,32,32)});
const holeTex=spr(g=>{const gr=g.createRadialGradient(32,32,0,32,32,30);gr.addColorStop(0,'rgba(10,8,6,1)');gr.addColorStop(.35,'rgba(30,24,18,.9)');gr.addColorStop(.6,'rgba(60,50,40,.35)');gr.addColorStop(1,'rgba(0,0,0,0)');g.fillStyle=gr;g.fillRect(0,0,64,64)});
let puffs=[];function puff(x,y,z,col,s,life,v,op,add){const m=new T.Sprite(new T.SpriteMaterial({map:puffTex,color:col,transparent:true,depthWrite:false,opacity:op||.7,blending:add?T.AdditiveBlending:T.NormalBlending}));m.position.set(x,y,z);m.scale.setScalar(s);fx.add(m);puffs.push({m,life,max:life,v:v||new V3(),op:op||.7,gr:.8});return m}
const decals=[];const decalGeo=new T.PlaneGeometry(.1,.1),decalMat=new T.MeshBasicMaterial({map:holeTex,transparent:true,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-4});
function decal(x,y,z,nx,ny,nz){const m=new T.Mesh(decalGeo,decalMat);m.position.set(x+nx*.01,y+ny*.01,z+nz*.01);m.lookAt(x+nx,y+ny,z+nz);m.rotation.z=Math.random()*6;m.scale.setScalar(rnd(.8,1.3));fx.add(m);decals.push(m);if(decals.length>160)fx.remove(decals.shift())}
let sparks=[];const sparkGeo=new T.BufferGeometry();sparkGeo.setAttribute('position',new T.Float32BufferAttribute(new Float32Array(300*6),3));const sparkL=new T.LineSegments(sparkGeo,new T.LineBasicMaterial({color:0xffd070,transparent:true,opacity:.9}));sparkL.frustumCulled=false;scene.add(sparkL);
function pById(id){return players.find(p=>p.id===id)}
/* ---------------- events (host -> clients) ---------------- */
let evQ=[],evRel=[];function evt(e,rel){evQ.push(e);if(rel)evRel.push(e);applyEvt(e,true)}
function applyEvt(e,local){const p=e.p?pById(e.p):null;
  if(e.k==='shot'&&p){gunSound(p,e.w);if(p===me){vmKick(e.w)}else{flashAt(p);for(const q of players)if(q.bot&&q.alive&&q.ai&&(ROY||q.team!==p.team)&&Math.hypot(q.x-p.x,q.z-p.z)<(WPN[e.w]&&WPN[e.w].snd==='sup'?12:40))q.ai.alert={x:p.x,z:p.z,t:2.5}}}
  if(e.k==='tr'&&p){const from=p===me?muzzleWorld():new V3(p.x-Math.sin(p.yaw)*.6,eyeY(p)-.18,p.z-Math.cos(p.yaw)*.6);tracers.push({a:from,b:new V3(e.x,e.y,e.z),t:0})}
  if(e.k==='imp'){if(e.m!=='terrain'){decal(e.x,e.y,e.z,e.nx,e.ny,e.nz)}const metal=e.m==='metal';puff(e.x,e.y,e.z,metal?0xaaaaaa:e.m==='terrain'||e.m==='ground'?0xa08a68:e.m==='crate'||e.m==='wood'?0x8a6a44:0xc8b08a,.3,.55,new V3(e.nx*.8,.5+e.ny*.5,e.nz*.8),.85);if(metal||Math.random()<.35)for(let i=0;i<(metal?5:2);i++)sparks.push({x:e.x,y:e.y,z:e.z,vx:e.nx*rnd(1,3)+rnd(-2,2),vy:rnd(0,3),vz:e.nz*rnd(1,3)+rnd(-2,2),l:rnd(.1,.3)});if(Math.random()<.35)play(e.x,e.z,{noise:1,ft:'bandpass',f:metal?4200:1800,q:3,dur:.05,vol:.1,range:25})}
  if(e.k==='blood'){for(let i=0;i<3;i++)puff(e.x+rnd(-.08,.08),e.y+rnd(-.08,.08),e.z+rnd(-.08,.08),0x8a0808,rnd(.2,.38),rnd(.3,.5),new V3(rnd(-.4,.4),rnd(-.2,.5),rnd(-.4,.4)),.9);const by=pById(e.by);if(by===me){hitmark=.22;hitHS=!!e.hs;play(null,null,{tone:e.hs?1600:1100,tdur:.05,wave:'square',tvol:.4,vol:.18})}}
  if(e.k==='hurt'&&me&&e.p===me.id){hurtFx=Math.min(1,hurtFx+e.d/55);if(e.from){const a=pById(e.from);if(a)dmgDirs.push({x:a.x,z:a.z,t:1.4})}if(e.hs)play(null,null,{tone:900,tone2:300,tdur:.2,wave:'triangle',tvol:.5,vol:.25});shakeV=Math.min(.6,shakeV+e.d/80)}
  if(e.k==='kill'){const a=pById(e.a),v=pById(e.v);feed.unshift({a:a?a.name:'',at:a?a.team:'',v:v?v.name:'',vt:v?v.team:'',w:WPN[e.w]?WPN[e.w].n:({fall:'fall',zone:'zone',bomb:'C4',he:'HE',molotov:'fire'})[e.w]||e.w,hs:e.hs,wb:e.wb,me:(a&&a===me)||(v&&v===me),t:7});if(feed.length>6)feed.pop();if(v){v.alive=false}if(a===me&&v!==me){play(null,null,{tone:e.hs?1400:900,tone2:e.hs?1800:1100,tdur:.12,wave:'triangle',tvol:.5,vol:.2});killCount++}if(v===me){deathT=0;killer=a}}
  if(e.k==='rel'&&p){if(p===me){vmRel=0}play(p===me?null:p.x,p===me?null:p.z,{noise:1,ft:'bandpass',f:2400,q:4,dur:.05,vol:.2,range:15});setTimeout(()=>play(p===me?null:p.x,p===me?null:p.z,{noise:1,ft:'bandpass',f:1500,q:4,dur:.06,vol:.22,range:15}),((WPN[p.cur]||{}).rel||2)*550)}
  if(e.k==='gren'){if(e.id==='he'){for(let i=0;i<14;i++)puff(e.x+rnd(-1,1),e.y+rnd(0,1.5),e.z+rnd(-1,1),i<6?0xffc060:0x3a3a3a,rnd(1.5,3.5),rnd(.5,1.5),new V3(rnd(-2,2),rnd(1,3),rnd(-2,2)),.9,i<6);play(e.x,e.z,{noise:1,f:600,dur:.9,tone:70,tone2:30,tdur:.6,tvol:.8,vol:.9,range:120});if(Math.hypot(e.x-camera.position.x,e.z-camera.position.z)<15)shakeV=.8}
    if(e.id==='flash'){puff(e.x,e.y,e.z,0xffffff,5,.25,null,1,true);play(e.x,e.z,{noise:1,ft:'highpass',f:2500,dur:.35,vol:.7,range:80});if(me&&me.flashT>1)play(null,null,{tone:3200,tdur:Math.min(3,me.flashT),tvol:.25,vol:.15})}
    if(e.id==='smoke'){if(NETROLE==='client')smokes.push({x:e.x,y:e.y+1.6,z:e.z,r:4.3,t:0,life:18});play(e.x,e.z,{noise:1,ft:'highpass',f:1200,dur:1.8,vol:.25,range:40})}
    if(e.id==='molotov'||e.id==='incgren'){if(NETROLE==='client')fires.push({x:e.x,y:e.y,z:e.z,r:3.2,t:0,life:7});play(e.x,e.z,{noise:1,f:900,dur:.6,vol:.5,range:50})}}
  if(e.k==='fizz')play(e.x,e.z,{noise:1,ft:'highpass',f:3000,dur:.6,vol:.3,range:30});
  if(e.k==='plant'){msgC('The bomb has been planted','',3);say('Bomb has been planted')}
  if(e.k==='planting'&&p)play(p===me?null:p.x,p===me?null:p.z,{tone:1400,tdur:.06,wave:'square',tvol:.4,vol:.18,range:20});
  if(e.k==='defusing'&&p)play(p===me?null:p.x,p===me?null:p.z,{noise:1,ft:'bandpass',f:2000,q:5,dur:.2,vol:.25,range:25});
  if(e.k==='defused'){msgC('The bomb has been defused','',3);say('Bomb has been defused')}
  if(e.k==='beep')play(e.x,e.z,{tone:2700,tdur:.07,wave:'square',tvol:.4,vol:.3,range:60});
  if(e.k==='boom'){for(let i=0;i<50;i++)puff(e.x+rnd(-5,5),e.y+rnd(0,8),e.z+rnd(-5,5),i<20?0xffb040:0x2a2a2a,rnd(4,10),rnd(1,3.5),new V3(rnd(-5,5),rnd(3,9),rnd(-5,5)),.95,i<20);play(e.x,e.z,{noise:1,f:300,dur:2.2,tone:50,tone2:20,tdur:1.5,tvol:.9,vol:1,range:300});shakeV=1.2}
  if(e.k==='round'){const L=e.w==='T'?'Terrorists win':'Counter-Terrorists win';banner(e.w,L,e.why,e.mvp);say(L)}
  if(e.k==='go'){say('Go go go')}
  if(e.k==='swing'&&p===me)vmSwing=.4;if(e.k==='swing'&&p)play(p===me?null:p.x,p===me?null:p.z,{noise:1,ft:'bandpass',f:2400,dur:.12,vol:.15,range:15});
  if(e.k==='bounce')play(e.x,e.z,{tone:rnd(1800,2600),tdur:.04,wave:'triangle',tvol:.4,vol:.15,range:30});if(e.k==='throw'&&p===me)vmSwing=.35;if(e.k==='dry'&&p===me)play(null,null,{tone:300,tdur:.04,wave:'square',tvol:.3,vol:.12});
  if(e.k==='pick'&&p===me)play(null,null,{tone:700,tone2:1000,tdur:.08,wave:'triangle',tvol:.4,vol:.12});
  if(e.k==='chute'&&p)play(p===me?null:p.x,p===me?null:p.z,{noise:1,ft:'lowpass',f:500,dur:.5,vol:.3,range:60});
  if(e.k==='heal'&&p===me)play(null,null,{noise:1,ft:'bandpass',f:1200,dur:.3,vol:.1});
  if(e.k==='match'&&NETROLE==='client')matchOver=true;if(e.k==='rwin'){matchOver=true;const w=pById(e.p);msgC(w?(w===me?'WINNER WINNER!':w.name+' wins'):'No survivors','',5)}}
function flashAt(p){const m=new T.Sprite(new T.SpriteMaterial({map:flashTex,transparent:true,depthWrite:false,blending:T.AdditiveBlending}));m.position.set(p.x-Math.sin(p.yaw)*.75,eyeY(p)-.22,p.z-Math.cos(p.yaw)*.75);m.scale.setScalar(.5);fx.add(m);puffs.push({m,life:.05,max:.05,v:new V3(),op:1,gr:0})}
/* ---------------- view model ---------------- */
const VM=new T.Group();camera.add(VM);scene.add(camera);const vmHold=new T.Group();VM.add(vmHold);let vmGun=null,vmId=null,vmKickT=0,vmRel=-1,vmSwing=0,vmInsp=0,hitmark=0,hitHS=false,hurtFx=0,dmgDirs=[],shakeV=0,swayX=0,swayY=0,killCount=0,deathT=0,killer=null;
const vmLight=new T.PointLight(0xffc070,0,7);VM.add(vmLight);const vmFlash=new T.Mesh(new T.PlaneGeometry(.22,.22),new T.MeshBasicMaterial({map:flashTex,transparent:true,depthWrite:false,blending:T.AdditiveBlending,opacity:0}));vmHold.add(vmFlash);
let armR=null,armL=null;const shells=[];
function mkArm(sleeveCol){const g=new T.Group();const sl=new T.Mesh(new T.CylinderGeometry(.042,.05,.34,10),new T.MeshStandardMaterial({color:lin(sleeveCol),roughness:.85}));sl.rotation.x=PI/2;sl.position.z=.2;g.add(sl);const cuff=new T.Mesh(new T.CylinderGeometry(.043,.043,.04,10),new T.MeshStandardMaterial({color:lin(0x1a1a1a),roughness:.7}));cuff.rotation.x=PI/2;cuff.position.z=.04;g.add(cuff);const hand=new T.Mesh(new T.BoxGeometry(.07,.085,.1),new T.MeshStandardMaterial({color:lin(0x202226),roughness:.75}));hand.position.z=-.02;g.add(hand);const th=new T.Mesh(new T.BoxGeometry(.025,.025,.06),new T.MeshStandardMaterial({color:lin(0x202226),roughness:.75}));th.position.set(-.035,.02,-.05);g.add(th);return g}
function vmSet(force){if(!me)return;const id=me.cur||'knife';if(vmId===id&&vmGun&&!force)return;if(vmGun)vmHold.remove(vmGun);vmGun=gunModel(id,true);vmHold.add(vmGun);vmId=id;if(armR){VM.remove(armR);VM.remove(armL)}const sc=ROY?0x4a5a3a:me.team==='T'?0x7a6a4a:0x2e3a4a;armR=mkArm(sc);armL=mkArm(sc);VM.add(armR,armL);vmFlash.position.set(0,.03,vmGun.userData.mz-.08)}
function vmKick(w){vmKickT=1;vmFlash.material.opacity=1;vmFlash.rotation.z=Math.random()*6;vmLight.intensity=4;setTimeout(()=>{vmFlash.material.opacity=0;vmLight.intensity=0},40);const W=WPN[w]||{};if(vmGun&&vmGun.userData.slide)vmGun.userData.slide.position.z=W.cls==='pistol'?.035:0;if(W.cls!=='shotgun'&&W.cls!=='melee'&&vmGun){const s=new T.Mesh(new T.CylinderGeometry(.006,.006,.022,6),gm('brass',0xc8a040,.3,.9));const ej=vmGun.userData.ej;s.position.set(ej[0],ej[1],ej[2]);vmHold.add(s);shells.push({m:s,v:new V3(rnd(.8,1.4),rnd(.6,1.1),rnd(-.1,.2)),r:new V3(rnd(-20,20),rnd(-20,20),0),t:.6})}}
function muzzleWorld(){camera.updateMatrixWorld(true);return new V3(.16,-.13,(vmGun?vmGun.userData.mz:-.3)-.35).applyMatrix4(camera.matrixWorld)}
function stepVM(dt,mdx,mdy){if(!me)return;vmSet();const t=performance.now()/1000;const sp=me.spd||0,W=WPN[me.cur]||{};const mv=Math.min(1,sp/5)*(me.onGround?1:.3);
  swayX=lerp(swayX,clamp(-mdx*.0008,-.04,.04),Math.min(1,dt*10));swayY=lerp(swayY,clamp(mdy*.0008,-.04,.04),Math.min(1,dt*10));vmKickT=Math.max(0,vmKickT-dt*(W.cls==='sniper'?4:10));vmSwing=Math.max(0,vmSwing-dt);vmInsp=Math.max(0,vmInsp-dt);
  const bq=1-(me.adsK||0)*.8,bx=Math.sin(t*8.5)*.012*mv*bq,by=bq*Math.abs(Math.cos(t*8.5))*.01*mv+Math.sin(t*1.6)*.002;const draw=me.swapT>0?me.swapT/.55:0;
  let rl=0,rlPh=-1;if(me.rel>0&&W.rel){rlPh=1-me.rel/W.rel;rl=Math.sin(Math.min(1,rlPh)*PI)}
  VM.visible=me.alive&&!(me.scoped&&W.cls!=='rifle')&&!me.inPlane&&!me.air;const scopedRifle=me.scoped&&W.cls==='rifle';
  const adsV=ROY&&me.ads&&!me.scoped&&W.cls!=='melee'&&!W.gren;me.adsK=lerp(me.adsK||0,adsV?1:0,Math.min(1,dt*14));const base0=W.cls==='pistol'?[.15,-.17,-.34]:W.cls==='melee'?[.2,-.2,-.3]:W.cls==='gren'||W.cls==='bomb'?[.18,-.2,-.32]:[.15,-.18,-.3];const AK=me.adsK,adsP=W.cls==='pistol'?[0,-.1,-.44]:[0,-.108,-.46];const base=[lerp(base0[0],adsP[0],AK),lerp(base0[1],adsP[1],AK),lerp(base0[2],adsP[2],AK)];
  vmHold.position.set(base[0]+bx+swayX-(scopedRifle?.15:0),base[1]-by+swayY-draw*.3-rl*.07+(scopedRifle?.07:0),base[2]+vmKickT*(W.cls==='sniper'?.09:.045)+(me.crouchT*.01));
  const insp=vmInsp>0?Math.sin(Math.min(1,(2.4-vmInsp)/2.4)*PI):0;vmHold.rotation.set(vmKickT*(W.cls==='pistol'?.18:.07)+draw*-.8+rl*.35+insp*.3,swayX*2+insp*.9,-draw*.4-rl*.5-insp*.4);
  if(vmSwing>0&&W.cls==='melee'){const k=Math.sin(vmSwing/.4*PI);vmHold.rotation.set(-.3-k*.4,k*1.4,k*.8);vmHold.position.x-=k*.12}
  if(vmGun&&vmGun.userData.slide)vmGun.userData.slide.position.z*=Math.exp(-dt*25);
  if(vmGun&&vmGun.userData.mag){const mg=vmGun.userData.mag;if(rlPh>=0){const k=rlPh<.3?rlPh/.3:rlPh<.55?1:rlPh<.75?1-(rlPh-.55)/.2:0;mg.position.y=-k*.25;mg.visible=!(rlPh>.28&&rlPh<.5)}else{mg.position.y=0;mg.visible=true}}
  // arms follow gun
  vmHold.updateMatrix();const two=W.cls!=='melee'&&W.cls!=='gren'&&W.cls!=='bomb';const gp=(x,y,z)=>new V3(x,y,z).applyMatrix4(vmHold.matrix);
  const rh=gp(0,-.05,W.cls==='pistol'?.04:.06),lh=W.cls==='pistol'?gp(-.02,-.06,.03):W.cls==='melee'||!two?null:gp(0,-.03,W.cls==='sniper'?-.3:W.cls==='smg'?-.18:-.24);
  armR.position.copy(rh);armR.rotation.set(vmHold.rotation.x+.75,vmHold.rotation.y+.3,vmHold.rotation.z);if(lh){armL.visible=true;armL.position.copy(lh);armL.rotation.set(vmHold.rotation.x+.85,vmHold.rotation.y-.55,vmHold.rotation.z+.2)}else{armL.visible=rl>0;if(rl>0){armL.position.set(.02,-.25+rl*.08,-.3);armL.rotation.set(.8,-.4,0)}}
  if(W.cls==='bomb'&&me.plantT>0){vmHold.position.y-=.05;vmHold.rotation.x=-.6;armL.visible=true;armL.position.set(.12+Math.sin(t*20)*.01,-.2,-.34);armL.rotation.set(.6,-.2,0)}
  for(let i=shells.length-1;i>=0;i--){const s=shells[i];s.t-=dt;s.v.y-=4*dt;s.m.position.addScaledVector(s.v,dt*.35);s.m.rotation.x+=s.r.x*dt;s.m.rotation.y+=s.r.y*dt;if(s.t<=0){vmHold.remove(s.m);shells.splice(i,1)}}}
/* ---------------- HUD ---------------- */
const ICON={hp:'<svg viewBox="0 0 24 24"><path d="M9 2h6v7h7v6h-7v7H9v-7H2V9h7z"/></svg>',ar:'<svg viewBox="0 0 24 24"><path d="M12 2l9 4v6c0 5-4 9-9 10-5-1-9-5-9-10V6z"/></svg>'};
const H=(()=>{const x=el('div',{class:'tx-x'});for(let i=0;i<4;i++)x.append(el('i'));x.append(el('b'));const hm=el('div',{class:'tx-hm'}),bl=el('div',{class:'tx-bl'}),hpE=el('div',{class:'tx-stat'}),arE=el('div',{class:'tx-stat'});bl.append(hpE,arE);
  const am=el('div',{class:'tx-am'}),money=el('div',{class:'tx-money'}),top=el('div',{class:'tx-top'}),feedE=el('div',{class:'tx-feed'}),rad=el('canvas',{class:'tx-radar',width:352,height:352}),cen=el('div',{class:'tx-center'}),ban=el('div',{class:'tx-banner'}),bar=el('div',{class:'tx-bar'},el('i')),hint=el('div',{class:'tx-hint'}),fl=el('div',{class:'tx-flash'}),hu=el('div',{class:'tx-hurt'}),storm=el('div',{class:'tx-storm'}),dir=el('div',{class:'tx-dir'}),sc=el('div',{class:'tx-scope'}),ov=el('div',{class:'tx-ov'}),inv=el('div',{class:'tx-inv'}),bh=el('div',{class:'tx-buyhint'},'🛒 Buy menu [B]'),mapov=el('div',{class:'tx-mapov'},el('canvas',{width:800,height:800})),tb=el('div',{class:'tx-tbuy'});
  const tbuy=el('button',{type:'button'},'BUY'),tmap=el('button',{type:'button'},ROY?'MAP':'SCORE'),trel=el('button',{type:'button'},'RELOAD'),tsw=el('button',{type:'button'},'SWAP'),tcr=el('button',{type:'button'},'CROUCH');const tads=el('button',{type:'button'},'AIM');tb.append(ROY?tmap:tbuy,trel,tsw,tcr);if(ROY)tb.append(tads);
  const keys=el('div',{class:'tx-keys'+(ROY?' roy':'')});hud.append(storm,fl,hu,sc,dir,x,hm,bl,am,money,top,feedE,rad,cen,ban,bar,hint,inv,bh,keys,tb,mapov,ov);[ov,bh,tb,mapov].forEach(e=>{e.addEventListener('mousedown',ev=>ev.stopPropagation());e.addEventListener('pointerdown',ev=>ev.stopPropagation())});
  return{tads,keys,x,hm,hpE,arE,am,money,top,feedE,rad,cen,ban,bar,hint,fl,hu,storm,dir,sc,ov,inv,bh,mapov,tbuy,tmap,trel,tsw,tcr,rg:rad.getContext('2d')}})();
H.bh.onclick=e=>{e.stopPropagation();toggleBuy()};H.tbuy.addEventListener('pointerdown',e=>{e.preventDefault();toggleBuy()});H.tmap.addEventListener('pointerdown',e=>{e.preventDefault();if(ROY)toggleMap();else showBoard(!boardOpen)});H.trel.addEventListener('pointerdown',e=>{e.preventDefault();doReload()});H.tsw.addEventListener('pointerdown',e=>{e.preventDefault();cycleWeapon()});H.tcr.addEventListener('pointerdown',e=>{e.preventDefault();touchCrouch=!touchCrouch;H.tcr.style.background=touchCrouch?'rgba(255,190,60,.5)':''});let touchCrouch=false,touchAds=false;H.tads.addEventListener('pointerdown',e=>{e.preventDefault();touchAds=!touchAds;H.tads.style.background=touchAds?'rgba(255,190,60,.5)':''});
const KEYL=ROY?[['WASD','move'],['Shift','walk'],['C','crouch'],['Space','jump · leave plane'],['LMB','shoot'],['R','reload'],['E','pick up · crate'],['Q','aim down sights (hold)'],['RMB','aim (hold)'],['X','heal'],['1-4','weapons'],['M','map'],['Tab','scoreboard']]:[['WASD','move'],['Shift','walk (silent)'],['C','crouch'],['Space','jump'],['LMB','shoot'],['R','reload'],['B','buy menu'],['1 2 3','gun pistol knife'],['Q / RMB','scope'],['L','last weapon'],['Z X V T','grenades'],['4','next grenade'],['E','plant · defuse · take'],['G','drop'],['F','inspect'],['Tab','scoreboard']];
let keysMin=!!S.get('tx_keysmin',0);function renderKeys(){H.keys.innerHTML='';KEYL.forEach(([k,d])=>{const r=el('div');k.split(' ').forEach(x=>r.append(el('b',null,x)));r.append(document.createTextNode(' '+d));H.keys.append(r)});H.keys.append(el('div',{class:'k2'},(keysMin?'Controls hidden · ':'')+'H '+(keysMin?'show':'hide')+' controls · - / = sensitivity'));H.keys.classList.toggle('min',keysMin)}renderKeys();
let sensMul=+S.get('tx_sens',1)||1;function setSens(v){sensMul=clamp(Math.round(v*20)/20,.2,4);S.set('tx_sens',sensMul);msgC('','Mouse sensitivity '+sensMul.toFixed(2)+'x',1.2)}
let cenT=0;function msgC(t,sub,d){H.cen.innerHTML='';if(t)H.cen.append(document.createTextNode(t));if(sub)H.cen.append(el('small',null,sub));cenT=d||3}
let banT=0;function banner(side,t,why,mvpId){H.cen.textContent="";cenT=0;H.ban.innerHTML='';const d=el('div',{class:side},t);if(why)d.append(el('small',null,why));const m=pById(mvpId);if(m)d.append(el('small',null,'★ MVP: '+m.name));H.ban.append(d);H.ban.style.display='block';banT=4.5}
function mkRadarImg(){const cv=document.createElement('canvas'),S2=ROY?800:420;cv.width=cv.height=S2;const g=cv.getContext('2d'),k=S2/Math.max(MAPW,MAPD);
  if(ROY){const id=g.createImageData(S2,S2);for(let y=0;y<S2;y++)for(let x=0;x<S2;x++){const wx=x/k,wz=y/k,h=terrH(wx,wz),n=fbm(wx*.03,wz*.03,2);const i=(y*S2+x)*4;let r=70+n*30,gg=100+n*30,b=50;if(h<1.1){r=60;gg=110;b=150}else if(h>26){r=130;gg=125;b=110}else{r+=h*1.2;gg+=h*.6}const sl=Math.abs(terrH(wx+2,wz)-h);r-=sl*8;gg-=sl*8;b-=sl*8;id.data[i]=r;id.data[i+1]=gg;id.data[i+2]=b;id.data[i+3]=255}g.putImageData(id,0,0)}
  if(!ROY){const blk=b=>!b.noCol&&!b.foliage&&!b.invis&&b.y0<1.75&&b.y1>.45;g.fillStyle='#b9a47c';g.fillRect(0,0,MAPW*k,MAPD*k);for(const s of Object.values(SITES)){g.fillStyle='rgba(215,70,50,.35)';g.fillRect(s.x0*k,s.z0*k,(s.x1-s.x0)*k,(s.z1-s.z0)*k)}for(const [t2,z] of Object.entries(BUYZ)){g.fillStyle=t2==='T'?'rgba(240,190,70,.28)':'rgba(90,150,255,.28)';g.fillRect(z.x0*k,z.z0*k,(z.x1-z.x0)*k,(z.z1-z.z0)*k)}
    for(const b of boxes){if(!blk(b)||b.y1>=1.35)continue;g.fillStyle='#7d6a4c';g.fillRect(b.x0*k,b.z0*k,Math.max(1,(b.x1-b.x0)*k),Math.max(1,(b.z1-b.z0)*k))}
    g.fillStyle='#2e2820';for(const b of boxes){if(!blk(b)||b.y1<1.35)continue;g.fillRect(b.x0*k-1,b.z0*k-1,Math.max(1,(b.x1-b.x0)*k)+2,Math.max(1,(b.z1-b.z0)*k)+2)}g.fillStyle='#4a4034';for(const b of boxes){if(!blk(b)||b.y1<1.35)continue;g.fillRect(b.x0*k,b.z0*k,Math.max(1,(b.x1-b.x0)*k),Math.max(1,(b.z1-b.z0)*k))}}
  else for(const b of boxes){if(b.noCol||b.foliage||b.invis||b.y1-(b.base||0)<.5)continue;g.fillStyle=b.y1-(b.base||0)>3?'rgba(210,205,195,.95)':'rgba(150,130,100,.85)';g.fillRect(b.x0*k,b.z0*k,Math.max(1,(b.x1-b.x0)*k),Math.max(1,(b.z1-b.z0)*k))}
  if(!ROY){g.fillStyle='#fff';g.font='bold 30px sans-serif';g.strokeStyle='rgba(0,0,0,.6)';g.lineWidth=4;g.strokeText('A',SITES.A.cx*k-9,SITES.A.cz*k+11);g.fillText('A',SITES.A.cx*k-9,SITES.A.cz*k+11);g.strokeText('B',SITES.B.cx*k-9,SITES.B.cz*k+11);g.fillText('B',SITES.B.cx*k-9,SITES.B.cz*k+11)}else{g.font='bold 16px sans-serif';g.fillStyle='#fff';g.strokeStyle='rgba(0,0,0,.7)';g.lineWidth=3;PLACES.forEach(p=>{g.strokeText(p.n,p.x*k-30,p.z*k);g.fillText(p.n,p.x*k-30,p.z*k)})}radarImg={cv,k}}
function drawRadar(){const g=H.rg,W2=352;g.clearRect(0,0,W2,W2);if(!radarImg||!me)return;const cp=spec||me;g.save();g.beginPath();g.rect(0,0,W2,W2);g.clip();g.translate(W2/2,W2/2);g.rotate(cp.yaw);const zoom=ROY?1.6:1.35,k=radarImg.k*zoom;g.scale(zoom,zoom);g.translate(-cp.x*radarImg.k,-cp.z*radarImg.k);g.drawImage(radarImg.cv,0,0);g.restore();
  const tp=(x,z)=>{const dx=(x-cp.x)*k,dz=(z-cp.z)*k,c2=Math.cos(cp.yaw),s=Math.sin(cp.yaw);return[W2/2+dx*c2-dz*s,W2/2+dx*s+dz*c2]};
  if(ROY&&zone){g.save();g.strokeStyle='rgba(80,140,255,.95)';g.lineWidth=4;const[cx,cy]=tp(zone.cx,zone.cz);g.beginPath();g.arc(cx,cy,zone.r*k,0,7);g.stroke();if(zone.nr!=null){g.strokeStyle='rgba(255,255,255,.85)';g.setLineDash([8,6]);const[nx,ny]=tp(zone.nx,zone.nz);g.beginPath();g.arc(nx,ny,zone.nr*k,0,7);g.stroke()}g.restore()}
  for(const p of players){if(p===cp||!p.alive||p.inPlane)continue;const vis=ROY?p.seenT>0&&p.seenBy===me:(p.team===me.team||p.seenT>0);if(!vis)continue;const[x,y]=tp(p.x,p.z);if(x<0||y<0||x>W2||y>W2)continue;g.fillStyle=ROY?'#ff4a3a':p.team===me.team?(p.team==='T'?'#f0c050':'#6aa8ff'):'#ff3a2a';g.beginPath();g.arc(x,y,8,0,7);g.fill();g.strokeStyle='#000';g.lineWidth=2;g.stroke()}
  if(bomb&&!ROY&&(me.team==='T'||bomb.st==='planted')){const[x,y]=tp(bomb.x,bomb.z);g.fillStyle=bomb.st==='planted'?'#ff3a2a':'#ffd23f';g.fillRect(x-7,y-7,14,14)}
  g.fillStyle='#fff';g.beginPath();g.moveTo(W2/2,W2/2-12);g.lineTo(W2/2+8,W2/2+9);g.lineTo(W2/2-8,W2/2+9);g.fill()}
function drawMap(){const cv=H.mapov.firstChild,g=cv.getContext('2d'),S2=800;g.drawImage(radarImg.cv,0,0,S2,S2);const k=S2/MAPW;if(zone){g.strokeStyle='rgba(80,140,255,.95)';g.lineWidth=4;g.beginPath();g.arc(zone.cx*k,zone.cz*k,zone.r*k,0,7);g.stroke();if(zone.nr!=null){g.strokeStyle='#fff';g.setLineDash([10,8]);g.beginPath();g.arc(zone.nx*k,zone.nz*k,zone.nr*k,0,7);g.stroke();g.setLineDash([])}}
  if(plane&&plane.t*plane.sp<plane.len){g.strokeStyle='rgba(255,255,255,.7)';g.lineWidth=3;g.setLineDash([12,8]);g.beginPath();g.moveTo(plane.x0*k,plane.z0*k);g.lineTo((plane.x0+plane.dx*plane.len)*k,(plane.z0+plane.dz*plane.len)*k);g.stroke();g.setLineDash([]);const pp=planePos();g.fillStyle='#fff';g.beginPath();g.arc(pp.x*k,pp.z*k,7,0,7);g.fill()}
  if(me){g.save();g.translate(me.x*k,me.z*k);g.rotate(-me.yaw);g.fillStyle='#ffd23f';g.beginPath();g.moveTo(0,-12);g.lineTo(8,9);g.lineTo(-8,9);g.fill();g.restore()}}
function toggleMap(){H.mapov.classList.toggle('on');if(H.mapov.classList.contains('on'))drawMap()}
let spec=null;
function updHUD(dt){if(!me)return;const W=WPN[me.cur]||{};const am=me.ammo[me.cur];const view=spec&&!me.alive?spec:me;
  H.hpE.innerHTML=ICON.hp+Math.max(0,Math.round(view.hp));H.hpE.className='tx-stat'+(view.hp<=25?' low':'');H.arE.innerHTML=ICON.ar+Math.round(view.armor)+(ROY?(view.armorLv?' L'+view.armorLv:''):(view.helmet?'<small style="font-size:12px"> +H</small>':''));
  H.am.innerHTML='';const W2=WPN[view.cur]||{};const am2=view.ammo&&view.ammo[view.cur];H.am.append(el('em',null,W2.n||''));if(am2){H.am.append(document.createTextNode(am2.mag));H.am.append(el('small',null,'/ '+(ROY?(view.ammoR[AMMOT(view.cur)]||0):am2.res)))}else if(W2.gren)H.am.append(document.createTextNode((view.inv.g||[]).length));
  H.money.textContent=ROY?'':'$'+me.money;H.money.style.display=ROY?'none':'';H.bh.style.display=canBuy(me)&&!buyOpen?'block':'none';
  const mvf=clamp((me.spd-(W.spd||250)*U2M*.34)/((W.spd||250)*U2M*.66),0,1);const gap=4+(W.st?mvf*14+(me.onGround?0:14)+Math.min(me.rcI,8)*.8:0);const ch=H.x.children;[[0,-gap-8,2,8],[0,gap,2,8],[-gap-8,0,8,2],[gap,0,8,2]].forEach(([x2,y2,w,h],i)=>{Object.assign(ch[i].style,{left:(x2-(w===2?1:0))+'px',top:(y2-(h===2?1:0))+'px',width:w+'px',height:h+'px'})});H.x.style.display=(ROY&&me.ads)||(me.scoped&&W.cls==='sniper')||!me.alive&&!spec||W.cls==='sniper'&&!me.scoped?'none':'';
  H.sc.style.display=me.scoped&&W.cls==='sniper'?'block':'none';if(hitmark>0){hitmark-=dt;H.hm.style.opacity=Math.min(1,hitmark*6);H.hm.className='tx-hm'+(hitHS?' hs':'')}else H.hm.style.opacity=0;
  H.top.innerHTML='';if(ROY){const alive=players.filter(p=>p.alive).length;H.top.append(el('span',{class:'txs txT'},alive+' ALIVE'),el('span',{class:'txm'},zone?(zone.phase==='wait'?'Zone '+Math.ceil(zone.t)+'s':zone.phase==='shrink'?'CLOSING':'FINAL'):''),el('span',{class:'txs txC'},'☠ '+me.kills))}
  else{const al=t2=>{const d=el('span',{class:'tx-alive',style:'color:'+(t2==='T'?'#e8b84a':'#5a9aff')});players.filter(p=>p.team===t2).forEach(p=>d.append(el('i',{class:(p.alive?'':'d')+(p===me?' me':'')})));return d};const tl=round.phase==='post'?'':bomb&&bomb.st==='planted'?'💣':Math.floor(Math.max(0,round.t)/60)+':'+String(Math.ceil(Math.max(0,round.t))%60).padStart(2,'0');
    H.top.append(al('T'),el('span',{class:'txs txT'},String(round.score.T)),el('span',{class:'txm',style:bomb&&bomb.st==='planted'?'color:#ff5a3a':round.phase==='freeze'?'color:#aaa':''},round.phase==='freeze'?'0:'+String(Math.ceil(round.t)).padStart(2,'0'):tl),el('span',{class:'txs txC'},String(round.score.CT)),al('CT'))}
  H.feedE.innerHTML='';feed.forEach(f=>{f.t-=dt;H.feedE.append(el('div',{class:f.me?'me':''},el('span',{class:ROY?'':f.at==='T'?'fT':'fC'},f.a),el('span',{class:'w'},f.w+(f.wb?' ⊘':'')+(f.hs?' ◉':'')),el('span',{class:ROY?'':f.vt==='T'?'fT':'fC'},f.v)))});feed=feed.filter(f=>f.t>0);
  if(cenT>0){cenT-=dt;if(cenT<=0)H.cen.textContent=''}if(banT>0){banT-=dt;if(banT<=0)H.ban.style.display='none'}
  const fa=me.alive?clamp(me.flashT/1.2,0,1):0;H.fl.style.opacity=fa;hurtFx=Math.max(0,hurtFx-dt*1.1);H.hu.style.opacity=hurtFx;
  H.dir.innerHTML='';dmgDirs=dmgDirs.filter(d=>(d.t-=dt)>0);dmgDirs.forEach(d=>{const a=Math.atan2(d.x-me.x,d.z-me.z)+me.yaw+PI;const i=el('i');i.style.transform='rotate('+(-a*180/PI)+'deg)';i.style.opacity=Math.min(1,d.t);H.dir.append(i)});
  H.storm.style.opacity=ROY&&zone&&me.alive&&Math.hypot(me.x-zone.cx,me.z-zone.cz)>zone.r?1:0;
  if(ROY){H.inv.innerHTML='';[[1,me.inv[1]],[2,me.inv[4]],[3,me.inv[2]],[4,'knife']].forEach(([s,w])=>{const r=w&&w!=='knife'?ROYW[w]+1:1;const a2=w&&me.ammo[w];H.inv.append(el('div',{class:(me.cur===w&&w?'on ':'')+'r'+r},s+'  '+(w?WPN[w].n:'—')+(a2?'  '+a2.mag+'/'+(me.ammoR[AMMOT(w)]||0):'')))});H.inv.append(el('div',null,'X heal · 🩹'+me.heals.b+' ✚'+me.heals.m+' ⚡'+me.heals.e+(me.boost>0?' · boost '+Math.round(me.boost):'')));H.inv.append(el('div',null,'⛑ L'+(me.helmetLv||0)+'  🦺 L'+(me.armorLv||0)))}
  if(H.mapov.classList.contains('on')&&Math.random()<.2)drawMap();drawRadar()}
/* ---------------- networking (WebRTC P2P, signaling via /api/mp) ---------------- */
const API='/api/mp';const peerId=(Math.random().toString(36).slice(2)+Math.random().toString(36).slice(2)).replace(/[^a-z0-9]/g,'').slice(0,16);let roomId=null,conns=new Map(),hostConn=null,pollT=null,beatT=null;
const ICE={iceServers:[{urls:['stun:stun.l.google.com:19302','stun:stun1.l.google.com:19302']},{urls:'stun:stun.cloudflare.com:3478'}]};
async function api(method,body,q){const r=await fetch(API+(q||''),method==='GET'?{cache:'no-store'}:{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error('server '+r.status);return r.json()}
function waitIce(pc,ms){return new Promise(res=>{if(pc.iceGatheringState==='complete')return res();const t=setTimeout(res,ms||2500);pc.addEventListener('icegatheringstatechange',()=>{if(pc.iceGatheringState==='complete'){clearTimeout(t);res()}})})}
async function hostRoom(){const r=await api('POST',{op:'host',game:GAME,peer:peerId,name:nameMe+"'s "+(ROY?'drop':'match'),max:ROY?16:10,mode:ROY?'royale':'breach'});roomId=r.id;NETROLE='host';pollT=setInterval(pollHost,1200);beatT=setInterval(()=>api('POST',{op:'beat',game:GAME,room:roomId,peer:peerId,n:1+conns.size,open:true}).catch(()=>{}),8000);return roomId}
async function pollHost(){try{const r=await api('GET',null,'?room='+roomId+'&peer='+peerId);for(const{from,msg}of r.msgs){if(!msg)continue;if(msg.type==='join')await acceptPeer(from,msg.name);else if(msg.type==='answer'){const c2=conns.get(from);if(c2&&c2.pc.signalingState!=='stable')await c2.pc.setRemoteDescription(msg.sdp)}}}catch(e){}}
async function acceptPeer(from,name){if(conns.has(from)||conns.size>=(ROY?15:9))return;const pc=new RTCPeerConnection(ICE);const u=pc.createDataChannel('u',{ordered:false,maxRetransmits:0}),rl=pc.createDataChannel('r');const c2={pc,u,rl,name:String(name||'Player').slice(0,16),peer:from,ready:false,player:null,last:performance.now()};conns.set(from,c2);
  rl.onopen=()=>{c2.ready=true;onPeerReady(c2)};rl.onmessage=e=>onHostMsg(c2,JSON.parse(e.data));u.onmessage=e=>onHostMsg(c2,JSON.parse(e.data));pc.onconnectionstatechange=()=>{if(['failed','closed','disconnected'].includes(pc.connectionState))dropPeer(c2)};
  const off=await pc.createOffer();await pc.setLocalDescription(off);await waitIce(pc);await api('POST',{op:'send',room:roomId,from:peerId,to:from,msg:{type:'offer',sdp:pc.localDescription}})}
function dropPeer(c2){if(!conns.has(c2.peer))return;conns.delete(c2.peer);if(c2.player){const p=c2.player;p.peer=null;p.bot=true;p.name=p.name+' (bot)';p.ai=newAI(p,'A')}feedMsg(c2.name+' left')}
function feedMsg(t){feed.unshift({a:'',v:t,w:'',t:5});if(feed.length>6)feed.pop()}
function onPeerReady(c2){if(state!=='play'){return}let slot=null;if(!ROY){const tc={T:players.filter(p=>p.team==='T'&&!p.bot).length,CT:players.filter(p=>p.team==='CT'&&!p.bot).length};const team=tc.T<=tc.CT?'T':'CT';slot=players.find(p=>p.bot&&p.team===team)||players.find(p=>p.bot)}else slot=players.find(p=>p.bot&&(p.inPlane||!p.alive))||players.find(p=>p.bot);
  if(!slot)slot=mkPlayer({team:'CT',bot:false});slot.bot=false;slot.peer=c2.peer;slot.name=c2.name;slot.ai=null;c2.player=slot;feedMsg(c2.name+' joined');c2.rl.send(JSON.stringify({t:'welcome',id:slot.id,mode:cfg.mode,seed,len:matchLen,full:fullState()}));c2.needItems=true}
function onHostMsg(c2,m){c2.last=performance.now();const p=c2.player;if(!p)return;if(m.t==='i'){p.inp=m.i;if(m.i.yaw!=null){p.yaw=m.i.yaw;p.pitch=m.i.pitch}}if(m.t==='buy')buy(p,m.id);if(m.t==='slot'){const w=m.w;if(w&&(w==='knife'||Object.values(p.inv).includes(w)||(p.inv.g||[]).includes(w)||w==='bomb'&&p.inv[5]))equip(p,w)}if(m.t==='rel')reload(p);if(m.t==='heal')useHeal(p);if(m.t==='scope')toggleScope(p);if(m.t==='jump')jumpOut(p);if(m.t==='drop')dropCur(p)}
function fullState(){return{players:players.map(p=>({id:p.id,name:p.name,team:p.team})),plane:plane?{x0:plane.x0,z0:plane.z0,dx:plane.dx,dz:plane.dz,t:plane.t,len:plane.len,sp:plane.sp,y:plane.y}:null,score:round.score}}
function itemList(){return items.map(it=>({id:it.id,t:it.t,w:it.w,lv:it.lv,a:it.a,x:+it.x.toFixed(2),y:+it.y.toFixed(2),z:+it.z.toFixed(2),cont:it.cont}))}
function snapshot(forP){const ps=players.map(p=>[p.id,+p.x.toFixed(2),+p.y.toFixed(2),+p.z.toFixed(2),+p.yaw.toFixed(3),+p.pitch.toFixed(3),Math.round(p.hp),p.alive?1:0,p.cur,+p.crouchT.toFixed(2),p.inPlane?1:0,p.team,p.chute||0,+(p.vx.toFixed(1)),+(p.vz.toFixed(1)),p.onGround?1:0,p.helmet?1:0,Math.round(p.armor),p.kills,p.deaths,p.money,p.plantT>0||p.defT>0?1:0,p.air?1:0]);
  const s={t:'s',ps,r:ROY?null:{n:round.n,ph:round.phase,t:+round.t.toFixed(1),sc:round.score,bt:+round.buyT.toFixed(1)},b:bomb?{st:bomb.st,x:bomb.x,y:bomb.y,z:bomb.z,t:bomb.t,site:bomb.site}:null,z:zone?{cx:zone.cx,cz:zone.cz,r:zone.r,nx:zone.nx,nz:zone.nz,nr:zone.nr,ph:zone.phase,t:zone.t}:null,pl:plane?plane.t:null,ev:evQ.filter(e=>!e.__r)};
  if(forP)s.me={hp:forP.hp,armor:forP.armor,helmet:forP.helmet,money:forP.money,inv:forP.inv,ammo:forP.ammo,cur:forP.cur,kit:forP.kit,heals:forP.heals,flashT:forP.flashT,plantT:forP.plantT,defT:forP.defT,scoped:forP.scoped,kills:forP.kills,rcI:forP.rcI,ammoR:forP.ammoR,armorLv:forP.armorLv,helmetLv:forP.helmetLv,boost:forP.boost,healT:forP.healT,rel:forP.rel};return s}
let snapT=0;function netHostTick(dt){snapT-=dt;if(snapT>0)return;snapT=1/20;const rel=evRel;evRel=[];for(const c2 of conns.values()){if(!c2.ready||!c2.player)continue;try{if(itemsDirty||c2.needItems){c2.rl.send(JSON.stringify({t:'items',items:itemList()}));c2.needItems=false}if(rel.length)c2.rl.send(JSON.stringify({t:'ev',ev:rel}));const str=JSON.stringify(snapshot(c2.player));(str.length<15000?c2.u:c2.rl).send(str);if(performance.now()-c2.last>15000)dropPeer(c2)}catch(e){}}itemsDirty=false;evQ=[]}
async function joinRoom(code){const f=await api('POST',{op:'find',game:GAME,room:code});roomId=code;NETROLE='client';const hostPeer=f.host;await api('POST',{op:'send',room:roomId,from:peerId,to:hostPeer,msg:{type:'join',name:nameMe}});
  return new Promise((res,rej)=>{let done=false;const to=setTimeout(()=>{if(!done){done=true;clearInterval(pollT);rej(new Error('Could not connect to the host. Your network may block peer-to-peer connections, or the host has not started the match yet.'))}},25000);
    pollT=setInterval(async()=>{try{const r=await api('GET',null,'?room='+roomId+'&peer='+peerId);for(const{from,msg}of r.msgs){if(msg&&msg.type==='offer'&&!hostConn){const pc=new RTCPeerConnection(ICE);hostConn={pc,u:null,rl:null};pc.ondatachannel=e=>{const ch=e.channel;if(ch.label==='u')hostConn.u=ch;else hostConn.rl=ch;ch.onmessage=ev=>onClientMsg(JSON.parse(ev.data));if(ch.label==='r')ch.onopen=()=>{if(!done){done=true;clearTimeout(to);clearInterval(pollT);res()}}};pc.onconnectionstatechange=()=>{if(['failed','closed'].includes(pc.connectionState)&&state==='play'){msgC('Disconnected from host','',5);setTimeout(()=>menu(),3000)}};
        await pc.setRemoteDescription(msg.sdp);const ans=await pc.createAnswer();await pc.setLocalDescription(ans);await waitIce(pc);await api('POST',{op:'send',room:roomId,from:peerId,to:hostPeer,msg:{type:'answer',sdp:pc.localDescription}})}}}catch(e){}},1000)})}
function onClientMsg(m){if(m.t==='welcome')startClient(m);else if(m.t==='s')applySnap(m);else if(m.t==='ev')m.ev.forEach(e=>{e.__r=1;applyEvt(e)});else if(m.t==='items')syncItems(m.items)}
function syncItems(list){const ids=new Set(list.map(i=>i.id));items.slice().forEach(it=>{if(!ids.has(it.id))takeItem(it)});list.forEach(i=>{if(!items.some(it=>it.id===i.id)){const it=mkItem(Object.assign({},i));it.id=i.id}})}
function ensureP(id,team){let p=pById(id);if(!p){p=mkPlayer({id,team,name:'Player',bot:false})}return p}
function applySnap(s){for(const a of s.ps){const[id,x,y,z,yaw,pitch,hp,alive,cur,cr,inPlane,team,chute,vx,vz,og,helm,armor,kills,deaths,money,busy,air]=a;const p=ensureP(id,team);if(p.team!==team&&!ROY){p.team=team;scene.remove(p.mdl);p.mdl=mkChar(team,p.id);scene.add(p.mdl);if(p===me)vmSet(true)}p.hp=hp;p.alive=!!alive;p.inPlane=!!inPlane;p.chute=chute;p.cur=cur;p.helmet=!!helm;p.armor=armor;p.kills=kills;p.deaths=deaths;p.money=money;p.air=!!air;
    if(p===me){const d=Math.hypot(p.x-x,p.z-z)+Math.abs(p.y-y);if(d>1.3||!p.alive||p.inPlane||p.air){p.x=x;p.y=y;p.z=z}else{p.x+=(x-p.x)*.12;p.z+=(z-p.z)*.12;p.y+=(y-p.y)*.25}}else{p.tx=x;p.ty=y;p.tz=z;p.tyaw=yaw;p.tpitch=pitch;p.crouchT=cr;p.vx=vx;p.vz=vz;p.onGround=!!og;if(busy)p.plantT=.1;else p.plantT=0}}
  if(s.r){round.n=s.r.n;round.phase=s.r.ph;round.t=s.r.t;round.score=s.r.sc;round.buyT=s.r.bt}bomb=s.b;if(s.z)zone=Object.assign(zone||{},{cx:s.z.cx,cz:s.z.cz,r:s.z.r,nx:s.z.nx,nz:s.z.nz,nr:s.z.nr,phase:s.z.ph,t:s.z.t});if(plane&&s.pl!=null)plane.t=s.pl;
  if(s.me&&me){const o=s.me;Object.assign(me,{hp:o.hp,armor:o.armor,helmet:o.helmet,money:o.money,inv:o.inv,ammo:o.ammo,kit:o.kit,heals:o.heals,plantT:o.plantT,defT:o.defT,scoped:o.scoped,kills:o.kills,ammoR:o.ammoR,armorLv:o.armorLv,helmetLv:o.helmetLv,boost:o.boost,healT:o.healT,rel:o.rel});me.flashT=Math.max(me.flashT,o.flashT);if(me.cur!==o.cur){me.cur=o.cur;vmSet()}}
  (s.ev||[]).forEach(e=>{if(['kill','round','plant','defused','boom','gren','rstart','match','rwin','go'].includes(e.k))return;applyEvt(e)})}
function startClient(m){seed=m.seed;matchLen=m.len||matchLen;cleanupWorld();if(ROY)royaleMap(seed);else breachMap();mkRadarImg();players=[];m.full.players.forEach(pp=>{const p=mkPlayer({id:pp.id,team:pp.team,name:pp.name,bot:false});p.alive=true});me=pById(m.id);me.local=true;if(m.full.score)round.score=m.full.score;
  if(ROY&&m.full.plane){plane=Object.assign({},m.full.plane);buildPlane();zone={cx:200,cz:200,r:300,phase:'wait',t:60}}
  state='play';H.ov.classList.remove('on');vmSet(true);try{renderer.domElement.requestPointerLock()}catch(e){}msgC('Connected',ROY?'SPACE to jump from the plane':'You are '+(me.team==='T'?'a Terrorist':'a Counter-Terrorist'),3)}
function cleanupWorld(){world.clear();lightsG.clear();world.add(lightsG);boxes=[];HASH.clear();TER=null;players.forEach(p=>scene.remove(p.mdl));players=[];items.forEach(it=>fx.remove(it.m));items=[];grens.forEach(g=>fx.remove(g.m));grens=[];smokes.forEach(s=>s.puffs&&s.puffs.forEach(m=>fx.remove(m)));smokes=[];fires.forEach(f=>f.m&&f.m.forEach(m=>fx.remove(m)));fires=[];puffs.forEach(q=>fx.remove(q.m));puffs=[];decals.forEach(d=>fx.remove(d));decals.length=0;if(zoneM)zoneM.visible=false;if(plane&&plane.m)scene.remove(plane.m);plane=null;zone=null;bomb=null;feed=[];matchOver=false;overShown=false;round={n:0,phase:'freeze',t:0,score:{T:0,CT:0},loss:{T:1,CT:1},buyT:0};WINS=matchLen==='long'?13:9;HALF=matchLen==='long'?12:8}
function sendInput(inp){if(!hostConn||!hostConn.u||hostConn.u.readyState!=='open')return;hostConn.u.send(JSON.stringify({t:'i',i:Object.assign({},inp,{yaw:+me.yaw.toFixed(4),pitch:+me.pitch.toFixed(4)})}))}
function sendRel(m){if(hostConn&&hostConn.rl&&hostConn.rl.readyState==='open')hostConn.rl.send(JSON.stringify(m))}
function leaveNet(){clearInterval(pollT);clearInterval(beatT);if(NETROLE==='host'&&roomId)api('POST',{op:'close',game:GAME,room:roomId,peer:peerId}).catch(()=>{});conns.forEach(c2=>{try{c2.pc.close()}catch(e){}});conns.clear();if(hostConn)try{hostConn.pc.close()}catch(e){}hostConn=null;roomId=null;NETROLE='solo'}
/* ---------------- local input ---------------- */
function toggleScope(p){const W=WPN[p.cur];if(!W||!W.scope||p.rel>0)return;p.scoped=(p.scoped+1)%(W.scope2?3:2);if(p===me)play(null,null,{tone:1200,tdur:.02,wave:'square',tvol:.3,vol:.1})}
function dropCur(p){const w=p.cur;if(!w||w==='knife')return;if(w==='bomb'){p.inv[5]=null;dropBomb(p)}else if(WPN[w].slot<=2||WPN[w].slot===1){const s=Object.keys(p.inv).find(k=>p.inv[k]===w);if(s){delete p.inv[s];const it=mkItem({t:'gun',w,x:p.x-Math.sin(p.yaw)*1.2,y:p.y+.02,z:p.z-Math.cos(p.yaw)*1.2,mag:p.ammo[w]?p.ammo[w].mag:0,res:p.ammo[w]?p.ammo[w].res:0});delete p.ammo[w]}}else return;p.cur=bestSlot(p);if(p===me)vmSet()}
function selW(w){if(!w)return;if(NETROLE==='client'){sendRel({t:'slot',w});me.cur=w;vmSet()}else equip(me,w)}
function doReload(){NETROLE==='client'?sendRel({t:'rel'}):reload(me)}
function cycleWeapon(dir){dir=dir||1;const list=ROY?[me.inv[1],me.inv[4],me.inv[2],'knife']:[me.inv[1],me.inv[2],'knife',...(me.inv.g||[]),me.inv[5]?'bomb':null];const l=list.filter(Boolean);const i=l.indexOf(me.cur);selW(l[((i<0?0:i+dir)%l.length+l.length)%l.length])}
const K=input.keys;
function localInput(){const k=K;return{f:!!(k.w||k.arrowup)||input.joy.y<-.3,b:!!(k.s||k.arrowdown)||input.joy.y>.3,l:!!(k.a||k.arrowleft)||input.joy.x<-.3,r:!!(k.d||k.arrowright)||input.joy.x>.3,j:!!k[' ']||!!input.jumpBtn,c:!!(k.control||k.c)||touchCrouch,walk:!!k.shift,fire:(input.down||input.fire)&&!buyOpen,alt:!!input.right,use:!!k.e||(ROY&&!!input.alt&&input.touch),ads:ROY&&(!!k.q||!!input.right||touchAds)}}
c.on(document,'keydown',e=>{if(state!=='play'||!me)return;const k=e.key.toLowerCase();if(k==='tab'){e.preventDefault();showBoard(true);return}if(k==='h'){keysMin=!keysMin;S.set('tx_keysmin',keysMin?1:0);renderKeys();return}if(k==='-'||k==='_'){setSens(sensMul-.1);return}if(k==='='||k==='+'){setSens(sensMul+.1);return}if(buyOpen&&/^[1-4]$/.test(k)){quickBuy(+k);return}if(k==='b'&&!ROY){toggleBuy();return}if(k==='escape'&&buyOpen){toggleBuy();return}if(k==='m'&&ROY){toggleMap();return}if(buyOpen)return;
  if(ROY){const map={1:me.inv[1],2:me.inv[4],3:me.inv[2],4:'knife'};if(map[k]!==undefined)selW(map[k])}else{if(k==='1')selW(me.inv[1]);if(k==='2')selW(me.inv[2]);if(k==='3')selW('knife');if(k==='4'&&me.inv.g&&me.inv.g.length){const g=me.inv.g;const i=g.indexOf(me.cur);selW(g[(i+1)%g.length])}if(k==='5'&&me.inv[5])selW('bomb');const gk={z:['flash'],x:['smoke'],v:['he'],t:['molotov','incgren']}[k];if(gk){const g=(me.inv.g||[]).find(w=>gk.includes(w));if(g)selW(g);else msgC('','No '+({z:'flashbang',x:'smoke',v:'HE grenade',t:'molotov'})[k]+' — buy one with B',1.4)}}
  if(ROY&&(k==='x'||k==='5')){NETROLE==='client'?sendRel({t:'heal'}):useHeal(me)}if(k==='q'&&!ROY&&!e.repeat&&state==='play'&&me){NETROLE==='client'?sendRel({t:'scope'}):toggleScope(me)}if(k==='l'&&!ROY){{const w=me.prev&&(me.prev==='knife'||Object.values(me.inv).includes(me.prev)||(me.inv.g||[]).includes(me.prev))?me.prev:bestSlot(me);selW(w)}}
  if(k==='r')doReload();if(k==='f'&&!vmInsp)vmInsp=2.4;if(k==='g'){NETROLE==='client'?sendRel({t:'drop'}):dropCur(me)}
  if((k===' '||k==='e')&&ROY&&me.inPlane){NETROLE==='client'?sendRel({t:'jump'}):jumpOut(me)}});
c.on(document,'keyup',e=>{if(e.key==='Tab')showBoard(false)});
c.on(renderer.domElement,'mousedown',e=>{if(e.button===2&&state==='play'&&me&&!ROY){NETROLE==='client'?sendRel({t:'scope'}):toggleScope(me)}});
let wheelT=0;c.on(renderer.domElement,'wheel',e=>{const n=performance.now();if(state==='play'&&me&&!buyOpen&&n-wheelT>120){wheelT=n;cycleWeapon(e.deltaY>0?1:-1)}},{passive:true});
let buyOpen=false,boardOpen=false;
function toggleBuy(){if(!me||ROY)return;buyOpen=!buyOpen;if(buyOpen){if(document.pointerLockElement)document.exitPointerLock();renderBuy()}else{H.ov.classList.remove('on');H.ov.classList.remove('clear');try{if(!input.touch)renderer.domElement.requestPointerLock()}catch(e){}}}
let buyLog={n:-1,cur:[],prev:[]};function doBuy(id){if(buyLog.n!==round.n){if(buyLog.cur.length)buyLog.prev=buyLog.cur;buyLog.cur=[];buyLog.n=round.n}let ok;if(NETROLE==='client'){sendRel({t:'buy',id});ok=true}else ok=buy(me,id);if(ok){buyLog.cur.push(id);play(null,null,{tone:900,tone2:1200,tdur:.06,wave:'triangle',tvol:.4,vol:.12})}return ok}
const QB=[['Rifle + armor',()=>{const r=me.team==='T'?['ak','galil']:['m4a1s','m4a4','famas'];const hasP=me.inv[1];const out=[];if(me.armor<100||!me.helmet)out.push(me.money>=(hasP?1000:3700)?'vesthelm':'vest');if(!hasP)out.push(...r);return out}],['Utility',()=>['flash','smoke',me.team==='T'?'molotov':'incgren','flash','he']],['Rebuy last',()=>buyLog.prev.slice()],['AWP',()=>['awp']]];
function quickBuy(i){if(!canBuy(me))return;const list=QB[i-1][1]();let bought=0;const rifles=['ak','galil','m4a1s','m4a4','famas'];let gotR=false;for(const id of list){if(rifles.includes(id)){if(gotR)continue;const it=WPN[id];if(it.side&&it.side!==me.team)continue;if(me.money<it.price)continue;if(doBuy(id)){gotR=true;bought++}}else if(doBuy(id))bought++}if(!bought)msgC('','Nothing bought — not enough money or already owned',1.4);setTimeout(renderBuy,NETROLE==='client'?250:0)}
function renderBuy(){H.ov.classList.add('on');H.ov.classList.add('clear');H.ov.innerHTML='';const card=el('div',{class:'tx-card'});H.ov.append(card);const ok=canBuy(me);card.append(el('h2',null,'BUY MENU ',el('span',null,'$'+me.money)),el('p',null,ok?'Click an item to buy it. Press B or Esc to close.':me.alive?(inBuyZone(me)?'Buy time has expired.':'You are not in a buy zone. Go back to your spawn.'):'You are dead.'));
  if(!buyOpen)return;const qb=el('div',{class:'tx-qb'});QB.forEach(([n],i)=>{const b=el('button',{type:'button',class:ok?'':'no'},el('i',null,String(i+1)),n);b.onclick=e=>{e.stopPropagation();quickBuy(i+1)};qb.append(b)});card.append(el('h4',{style:'margin:4px 0 0;font:800 11px system-ui;opacity:.7;letter-spacing:.08em'},'QUICK BUY (keys 1-4)'),qb);const wrapC=el('div',{class:'tx-buyw'});BUYCATS.forEach(([cat,list])=>{const col=el('div',{class:'tx-buyc'},el('h4',null,cat));list.forEach(id=>{const it=WPN[id]||GEAR[id];if(it.side&&it.side!==me.team)return;let price=it.price;if(id==='vesthelm'&&me.armor>=100)price=350;const own=me.inv[1]===id||me.inv[2]===id||(me.inv.g||[]).includes(id)||id==='vest'&&me.armor>=100||id==='vesthelm'&&me.helmet||id==='kit'&&me.kit;const can=ok&&me.money>=price;const b=el('button',{type:'button',class:(can?'':'no')+(own?' own':'')},it.n,el('small',null,'$'+price));b.onclick=e=>{e.stopPropagation();doBuy(id);setTimeout(renderBuy,NETROLE==='client'?250:0)};col.append(b)});wrapC.append(col)});card.append(wrapC);
  const cl=el('button',{type:'button',class:'tx-btn pri'},'Close (B)');cl.onclick=e=>{e.stopPropagation();toggleBuy()};card.append(el('div',null,cl))}
function showBoard(on){boardOpen=on;if(!on){if(!buyOpen){H.ov.classList.remove('on');H.ov.classList.remove('clear')}return}H.ov.classList.add('on');H.ov.classList.add('clear');H.ov.innerHTML='';const card=el('div',{class:'tx-card'});H.ov.append(card);const tb=el('table',{class:'tx-sb'});
  tb.append(el('tr',null,el('th',null,'PLAYER'),el('th',null,ROY?'':'MONEY'),el('th',null,'K'),el('th',null,'A'),el('th',null,'D'),el('th',null,ROY?'':'MVP'),el('th',null,ROY?'PLACE':'')));
  const sorted=ROY?players.slice().sort((a,b)=>b.kills-a.kills):['CT','T'].flatMap(t=>players.filter(p=>p.team===t).sort((a,b)=>b.kills-a.kills));sorted.forEach(p=>tb.append(el('tr',{class:(p===me?'me ':'')+(p.alive?'':'dead ')+(ROY?'':p.team)},el('td',null,p.name+(p.bot?' 🤖':' 🌐')),el('td',null,ROY?'':(p.team===me.team?'$'+p.money:'')),el('td',null,String(p.kills)),el('td',null,String(p.assists||0)),el('td',null,String(p.deaths)),el('td',null,ROY?'':(p.mvps?'★'+p.mvps:'')),el('td',null,ROY&&p.place?'#'+p.place:''))));
  card.append(el('h2',null,ROY?'LAST ':'BREACH ',el('span',null,ROY?'DROP':'CT '+round.score.CT+' : '+round.score.T+' T')),tb,el('p',null,(roomId?'Room code '+roomId.toUpperCase()+' · '+(NETROLE==='host'?'you are hosting':'online'):'Offline match vs bots')+(ROY?'':' · first to '+WINS+' · round '+round.n)))}
/* ---------------- menus ---------------- */
const BOTN=['Rook','Vex','Moss','Tango','Brick','Juno','Kilo','Nash','Pike','Quill','Rune','Sage','Tusk','Wren','Yara','Zeke','Ash','Blitz','Cobra','Dune','Echo','Flint','Gale','Hex','Ivo','Jett','Knox','Lux','Mako','Nyx'];
function menu(){state='menu';leaveNet();if(document.pointerLockElement)document.exitPointerLock();H.ov.classList.add('on');H.ov.classList.remove('clear');H.ov.innerHTML='';const card=el('div',{class:'tx-card'});H.ov.append(card);
  card.append(el('h2',null,ROY?'LAST ':'BREACH ',el('span',null,ROY?'DROP':'5v5')),el('p',null,ROY?'Battle royale on a 400 m island with hills, towns, a military fort and a quarry. Drop from the plane, loot weapons by rarity, armour, helmets and meds, and outlast the storm. 30 players: online friends plus bots.':'Competitive bomb defusal with real CS mechanics: the full weapon lineup with CS2 stats and spray patterns, counter-strafing, headshots, wallbangs, the economy and loss bonus, buy zones, grenades, the C4 and a halftime side swap. Play online with friends (bots fill the empty slots) or offline.'));
  const nm=el('input',{class:'tx-in',value:nameMe,maxlength:'16'});nm.addEventListener('input',()=>{nameMe=nm.value.replace(/[^A-Za-z0-9 _.\-]/g,'').slice(0,16)||'Player';S.set('tx_name',nameMe)});nm.addEventListener('keydown',e=>e.stopPropagation());card.append(el('h3',null,'YOUR NAME'),nm);
  const opt=(title,list,cur,set)=>{card.append(el('h3',null,title));list.forEach(([v,n])=>{const b=el('button',{type:'button',class:'tx-btn'+(cur===v?' on':'')},n);b.onclick=e=>{e.stopPropagation();set(v);menu()};card.append(b)})};
  {const sv=el('span',null,sensMul.toFixed(2)+'x');const sl=el('input',{type:'range',min:'0.2',max:'4',step:'0.05',value:String(sensMul)});sl.addEventListener('input',()=>{sensMul=+sl.value;S.set('tx_sens',sensMul);sv.textContent=sensMul.toFixed(2)+'x'});['mousedown','pointerdown','keydown'].forEach(ev=>sl.addEventListener(ev,e=>e.stopPropagation()));card.append(el('h3',null,'MOUSE SENSITIVITY'),el('div',{class:'tx-sens'},sl,sv))}
  opt('BOT SKILL',[[0,'Easy'],[1,'Normal'],[2,'Hard']],diff,v=>{diff=v;S.set(GAME+'_diff',v)});
  if(!ROY){opt('SIDE',[['auto','Auto'],['T','Terrorists'],['CT','Counter-Terrorists']],teamPref,v=>{teamPref=v;S.set(GAME+'_team',v)});opt('MATCH',[['short','Short (first to 9)'],['long','Competitive (first to 13)']],matchLen,v=>{matchLen=v;S.set(GAME+'_len',v)})}
  card.append(el('h3',null,'PLAY'));const b1=el('button',{type:'button',class:'tx-btn pri'},'Play vs bots');b1.onclick=e=>{e.stopPropagation();startLocal('solo')};const b2=el('button',{type:'button',class:'tx-btn'},'🌐 Host online match');b2.onclick=e=>{e.stopPropagation();hostMenu()};const b3=el('button',{type:'button',class:'tx-btn'},'🌐 Join online match');b3.onclick=e=>{e.stopPropagation();joinMenu()};card.append(b1,b2,b3);
  card.append(el('p',{style:'font-size:12px;opacity:.7;margin-top:12px;line-height:1.6'},ROY?'The full controls list stays on screen during the match (press H to hide it). Hold Q or right mouse to aim down sights for a tighter spread; X heals.':'The full controls list stays on screen during the match (press H to hide it). Tip: stop moving before you shoot. Guns are only accurate when you stand still or walk, just like CS.'))}
function hostMenu(){H.ov.innerHTML='';const card=el('div',{class:'tx-card'});H.ov.append(card);card.append(el('h2',null,'HOST ',el('span',null,'ONLINE')),el('p',null,'Creating a room…'));
  hostRoom().then(id=>{card.innerHTML='';card.append(el('h2',null,'ROOM ',el('span',null,id.toUpperCase())),el('p',null,'Friends join from “Join online match” (the room is listed there) or by typing this code. Press Start whenever you like: bots fill empty slots and friends can join mid-match to take over a bot.'));const lst=el('div',{class:'tx-rooms'});card.append(lst);const upd=()=>{lst.innerHTML='';lst.append(el('div',null,el('b',null,nameMe+' (you, host)')));conns.forEach(c2=>lst.append(el('div',null,el('b',null,c2.name),c2.ready?'connected':'connecting…')))};upd();const iv=setInterval(()=>{if(state!=='menu'){clearInterval(iv);return}upd()},800);
    const go=el('button',{type:'button',class:'tx-btn pri'},'Start match');go.onclick=e=>{e.stopPropagation();clearInterval(iv);startLocal('host')};const bk=el('button',{type:'button',class:'tx-btn'},'Cancel');bk.onclick=e=>{e.stopPropagation();clearInterval(iv);menu()};card.append(go,bk)}).catch(err=>{card.innerHTML='';card.append(el('h2',null,'OFFLINE'),el('p',null,'Online play needs the Detourr server, which isn’t reachable right now ('+err.message+'). You can still play against bots.'));const b=el('button',{type:'button',class:'tx-btn pri'},'Back');b.onclick=e=>{e.stopPropagation();menu()};card.append(b)})}
function joinMenu(){H.ov.innerHTML='';const card=el('div',{class:'tx-card'});H.ov.append(card);card.append(el('h2',null,'JOIN ',el('span',null,'ONLINE')));const lst=el('div',{class:'tx-rooms'},el('p',null,'Looking for rooms…'));const code=el('input',{class:'tx-in',placeholder:'Room code',maxlength:'5'});code.addEventListener('keydown',e=>e.stopPropagation());const jb=el('button',{type:'button',class:'tx-btn pri'},'Join code');const st=el('p');
  const doJoin=id=>{st.textContent='Connecting to '+id.toUpperCase()+'… (peer-to-peer)';joinRoom(id.toLowerCase()).catch(err=>{st.textContent=err.message;leaveNet()})};jb.onclick=e=>{e.stopPropagation();if(code.value.trim())doJoin(code.value.trim())};
  const refresh=()=>api('GET',null,'?list='+GAME).then(r=>{lst.innerHTML='';if(!r.rooms.length)lst.append(el('p',null,'No open rooms right now. Host one and share the code!'));r.rooms.forEach(rm=>{const b=el('button',{type:'button',class:'tx-btn pri'},'Join');b.onclick=e=>{e.stopPropagation();doJoin(rm.id)};lst.append(el('div',null,el('b',null,rm.name),rm.n+'/'+rm.max+' humans',b))})}).catch(err=>{lst.innerHTML='';lst.append(el('p',null,'Can’t reach the Detourr server: '+err.message))});
  const rb=el('button',{type:'button',class:'tx-btn'},'Refresh');rb.onclick=e=>{e.stopPropagation();refresh()};const bk=el('button',{type:'button',class:'tx-btn'},'Back');bk.onclick=e=>{e.stopPropagation();menu()};card.append(lst,el('div',null,code,' ',jb,' ',rb,' ',bk),st);refresh()}
function startLocal(role){const keep=role==='host'?conns:null;if(role==='solo')leaveNet();NETROLE=role;cleanupWorld();seed=Math.floor(Math.random()*1e9);if(ROY)royaleMap(seed);else breachMap();mkRadarImg();nextId=1;
  if(ROY){me=mkPlayer({name:nameMe,bot:false,team:'R'});me.local=true;for(let i=0;i<29;i++)mkPlayer({name:BOTN[i%BOTN.length],bot:true,team:'R'});royaleStart()}
  else{const myTeam=teamPref==='auto'?pick(['T','CT']):teamPref;me=mkPlayer({name:nameMe,bot:false,team:myTeam});me.local=true;let bi=0;for(const t of['T','CT'])for(let i=players.filter(p=>p.team===t).length;i<5;i++)mkPlayer({name:BOTN[bi++],bot:true,team:t});players.forEach(p=>{p.money=800;p.inv={3:'knife'};p.ammo={};p.alive=false});startRound()}
  state='play';conns.forEach(c2=>{if(c2.ready)onPeerReady(c2)});H.ov.classList.remove('on');vmSet(true);try{if(!input.touch)renderer.domElement.requestPointerLock()}catch(e){}}
/* ---------------- main loop ---------------- */
let sendT=0,overShown=false,zoneM=null,bombM=null;
function zoneWall(){if(!zone)return;if(!zoneM){zoneM=new T.Mesh(new T.CylinderGeometry(1,1,300,128,1,true),new T.ShaderMaterial({transparent:true,depthWrite:false,side:T.DoubleSide,uniforms:{t:{value:0}},vertexShader:'varying vec2 vU;varying vec3 vW;void main(){vU=uv;vec4 w=modelMatrix*vec4(position,1.);vW=w.xyz;gl_Position=projectionMatrix*viewMatrix*w;}',fragmentShader:'uniform float t;varying vec2 vU;varying vec3 vW;void main(){float s=sin(vU.x*600.+t*2.)*.5+.5;float h=sin(vW.y*.4-t*1.5)*.5+.5;float a=.18+.14*s*h;gl_FragColor=vec4(.25,.45,1.,a);}'}));scene.add(zoneM)}zoneM.position.set(zone.cx,100,zone.cz);zoneM.scale.set(zone.r,1,zone.r);zoneM.visible=true;zoneM.material.uniforms.t.value=performance.now()/1000}
function simPlayer(p,inp,dt,now){p.fireCd=Math.max(0,p.fireCd-dt);p.swapT=Math.max(0,p.swapT-dt);p.flashT=Math.max(0,p.flashT-dt);if(now-p.rcT>.1){const W=WPN[p.cur]||{};p.rcI=Math.max(0,p.rcI-dt*(W.pat?30/.45:6));}p.kickP*=Math.exp(-dt*8);if(p.rescope>0){p.rescope-=dt}
  if(p.rel>0){p.rel-=dt;if(p.rel<=0){p.rel=0;finishReload(p)}}else if(p.fireCd<=0&&p.swapT<=0&&p.ammo[p.cur]&&p.ammo[p.cur].mag<=0)reload(p);if(p.healT>0){p.healT-=dt;if(p.healT<=0){if(p.healKind==='m')p.hp=100;else if(p.healKind==='b')p.hp=Math.max(p.hp,p.healAmt);else p.boost=Math.min(100,(p.boost||0)+50)}}if(p.boost>0){p.boost-=dt*2.5;p.hp=Math.min(100,p.hp+dt*1.2)}
  if(ROY&&!p.bot){const W=WPN[p.cur]||{};p.ads=!!inp.ads&&!(p.rel>0)&&!p.inPlane&&!p.air&&W.cls!=='melee'&&!W.gren;if(W.scope)p.scoped=p.ads?1:0}
  if(ROY&&p.inPlane){const pp=planePos();p.x=pp.x;p.z=pp.z;p.y=plane.y;if(inp.j&&p!==me)jumpOut(p);return}
  if(ROY&&p.air){stepAir(p,dt,inp);return}
  moveP(p,dt,inp);if(inp.fire&&(ROY||round.phase!=='freeze')){const W=WPN[p.cur];if(W&&(W.auto||W.cls==='melee'||!p.fireHeld||W.gren||W.cls==='bomb'))fire(p,now)}p.fireHeld=inp.fire;
  if(!ROY)stepBombActions(p,dt,inp);else{if(inp.use&&!p.useHeld){let best=null,bd=1.9;for(const it of items){const d=Math.hypot(it.x-p.x,it.z-p.z);if(d<bd&&Math.abs(it.y-p.y)<1.6){bd=d;best=it}}if(best)pickUp(p,best)}p.useHeld=inp.use}if(p.y<-8){p.y=groundAt(p.x,p.z,.3,200)}}
function endScreen(){state='over';if(document.pointerLockElement)document.exitPointerLock();H.ov.classList.add('on');H.ov.classList.remove('clear');H.ov.innerHTML='';const card=el('div',{class:'tx-card'});H.ov.append(card);
  if(ROY){const place=me.place||players.filter(p=>p.alive).length||1;const win=place===1&&me.alive;card.append(el('h2',null,win?'WINNER ':'#'+place+' ',el('span',null,win?'WINNER!':'OF '+players.length)),el('p',null,(win?'Last one standing. ':'')+me.kills+' kills.'));if(win){const n=(S.get(GAME+'_wins',0)||0)+1;S.set(GAME+'_wins',n);c.best(n)}}
  else{const w=round.score.T>round.score.CT?'T':round.score.CT>round.score.T?'CT':'draw';const win=w===me.team;card.append(el('h2',null,w==='draw'?'DRAW ':win?'VICTORY ':'DEFEAT ',el('span',null,round.score.CT+' : '+round.score.T)),el('p',null,(w==='draw'?'The match ends in a draw.':(w==='T'?'Terrorists':'Counter-Terrorists')+' win the match.')+' You: '+me.kills+' K / '+(me.assists||0)+' A / '+me.deaths+' D · '+(me.mvps||0)+' MVP'));if(win){const n=(S.get(GAME+'_wins',0)||0)+1;S.set(GAME+'_wins',n);c.best(n)}}
  const a=el('button',{type:'button',class:'tx-btn pri'},'Play again');a.onclick=e=>{e.stopPropagation();startLocal(NETROLE==='host'?'host':'solo')};const m=el('button',{type:'button',class:'tx-btn'},'Menu');m.onclick=e=>{e.stopPropagation();menu()};card.append(a,m)}
st3.onFrame((dt0,nowMs)=>{const dt=Math.min(dt0,.05),now=nowMs/1000;
  if(state!=='play'||!me){if(!me){camera.position.set(ROY?200:48,ROY?90:32,ROY?260:74);camera.lookAt(ROY?200:48,0,ROY?200:40)}input.mdx=input.mdy=0;return}
  const sens=.0021*sensMul*(me.scoped?(me.scoped===2?.22:.42):ROY&&me.ads?.72:1);const mdx=input.mdx,mdy=input.mdy;if(!buyOpen&&me.alive){me.yaw-=mdx*sens;me.pitch=clamp(me.pitch-mdy*sens,-1.52,1.52)}input.mdx=input.mdy=0;
  const inp=me.alive&&!buyOpen?localInput():{};if(inp.alt&&!me.altHeld&&(WPN[me.cur]||{}).cls==='melee'){inp.fire=1}me.altHeld=inp.alt;
  if(NETROLE!=='client'){for(const p of players){if(!p.alive)continue;const pi=p===me?inp:p.bot?botThink(p,dt,now):(p.inp||{});p.inp=pi;simPlayer(p,pi,dt,now)}
    if(ROY)stepRoyale(dt);else stepRound(dt);stepGrens(dt);stepFires(dt);if(NETROLE==='host')netHostTick(dt);else{evQ=[];evRel=[]}for(const p of players)p.seenT=Math.max(0,(p.seenT||0)-dt)}
  else{if(me.alive){if(ROY&&me.inPlane){const pp=planePos();me.x=pp.x;me.z=pp.z;me.y=plane.y}else if(ROY&&me.air)stepAir(me,dt,inp);else moveP(me,dt,inp);me.fireCd=Math.max(0,me.fireCd-dt);if(inp.fire&&me.fireCd<=0&&round.phase!=='freeze'){const W=WPN[me.cur];if(W&&W.rpm&&me.ammo[me.cur]&&me.ammo[me.cur].mag>0&&!me.rel&&(W.auto||!me.fireHeld)){me.fireCd=60/W.rpm}}me.fireHeld=inp.fire}
    if(ROY){const W=WPN[me.cur]||{};me.ads=!!inp.ads&&!(me.rel>0)&&!me.inPlane&&!me.air&&W.cls!=='melee'&&!W.gren}sendT-=dt;if(sendT<=0){sendT=1/30;sendInput(inp)}for(const p of players){if(p===me||p.tx==null)continue;const k=Math.min(1,dt*12);p.x+=(p.tx-p.x)*k;p.y+=(p.ty-p.y)*k;p.z+=(p.tz-p.z)*k;let dy=p.tyaw-p.yaw;dy=Math.atan2(Math.sin(dy),Math.cos(dy));p.yaw+=dy*k;p.pitch+=(p.tpitch-p.pitch)*k;p.spd=Math.hypot(p.vx,p.vz);if(p.spd>3&&p.onGround){p.stepT=(p.stepT||0)-dt;if(p.stepT<=0){p.stepT=.36;footstep(p,1)}}}
    if(ROY&&plane){plane.t+=dt;const pp=planePos();plane.m.position.set(pp.x,plane.y,pp.z);plane.m.rotation.y=Math.atan2(-plane.dx,-plane.dz);plane.m.visible=plane.t*plane.sp<plane.len+300}me.flashT=Math.max(0,me.flashT-dt)}
  // visuals: players
  for(const p of players){const show=!(p===me&&!(ROY&&(me.air||me.chute)))&&!p.inPlane;p.mdl.visible=show&&(p.alive||(p.deadT=(p.deadT||0)+(p.alive?0:dt))<25);if(p.alive)p.deadT=0;if(!p.mdl.visible)continue;p.mdl.position.set(p.x,p.y,p.z);p.mdl.rotation.y=p.yaw;setCharGun(p);poseChar(p,dt);
    if(p.chute&&!p.mdl.userData.chute){const ch=new T.Group();const cm=new T.Mesh(new T.SphereGeometry(2.8,16,8,0,2*PI,0,PI/2.6),new T.MeshStandardMaterial({color:lin(pick([0xe8321e,0x2a6ae8,0xf2c21a,0x3ab04a,0xe86a2a])),side:T.DoubleSide,roughness:.7}));cm.position.y=4.6;ch.add(cm);for(let i=0;i<6;i++){const a=i/6*PI*2;const ln=new T.Mesh(new T.CylinderGeometry(.01,.01,3.6,3),new T.MeshBasicMaterial({color:0x333333}));ln.position.set(Math.cos(a)*1.3,3,Math.sin(a)*1.3);ln.rotation.z=-Math.cos(a)*.45;ln.rotation.x=Math.sin(a)*.45;ch.add(ln)}p.mdl.add(ch);p.mdl.userData.chute=ch}if(p.mdl.userData.chute)p.mdl.userData.chute.visible=!!p.chute}
  // smokes, fires, puffs, sparks, tracers
  for(let i=smokes.length-1;i>=0;i--){const s=smokes[i];s.t+=dt;if(!s.puffs){s.puffs=[];for(let k=0;k<34;k++){const m=new T.Sprite(new T.SpriteMaterial({map:puffTex,color:new T.Color().setHSL(0,0,rnd(.72,.86)),transparent:true,depthWrite:false,opacity:0}));const a=rnd(0,2*PI),r=Math.sqrt(Math.random())*3.2;m.position.set(s.x+Math.cos(a)*r,s.y+rnd(-1.5,1.6),s.z+Math.sin(a)*r);m.scale.setScalar(rnd(3.5,5.5));m.userData.r=rnd(-.2,.2);fx.add(m);s.puffs.push(m)}}const o=s.t<1.2?s.t/1.2:s.t>s.life-2?Math.max(0,(s.life-s.t)/2):1;s.puffs.forEach(m=>{m.material.opacity=.95*o;m.material.rotation+=m.userData.r*dt});if(s.t>s.life){s.puffs.forEach(m=>fx.remove(m));smokes.splice(i,1)}}
  for(const f of fires){if(!f.m){f.m=[];for(let k=0;k<16;k++){const m=new T.Sprite(new T.SpriteMaterial({map:puffTex,color:k<10?0xff7a1a:0xffc040,transparent:true,depthWrite:false,blending:T.AdditiveBlending,opacity:.8}));const a=rnd(0,2*PI),r=Math.sqrt(Math.random())*f.r*.9;m.position.set(f.x+Math.cos(a)*r,(f.y||0)+.35,f.z+Math.sin(a)*r);m.scale.setScalar(rnd(.8,1.5));fx.add(m);f.m.push(m)}const l=new T.PointLight(0xff7a2a,2,10,2);l.position.set(f.x,(f.y||0)+1,f.z);fx.add(l);f.m.push(l)}f.m.forEach((m,k)=>{if(m.isSprite){m.scale.y=rnd(1,1.9);m.material.opacity=clamp(1-f.t/f.life,0,1)*.85}});if(!NETROLE==='client')continue;if(NETROLE==='client'){f.t+=dt}}
  if(NETROLE==='client')for(let i=fires.length-1;i>=0;i--)if(fires[i].t>fires[i].life){fires[i].m.forEach(m=>fx.remove(m));fires.splice(i,1)}
  for(let i=puffs.length-1;i>=0;i--){const q=puffs[i];q.life-=dt;if(q.life<=0){fx.remove(q.m);q.m.material.dispose();puffs.splice(i,1);continue}q.m.position.addScaledVector(q.v,dt);q.m.scale.multiplyScalar(1+dt*q.gr);q.m.material.opacity=q.op*Math.min(1,q.life/q.max*1.5)}
  {const pos=sparkGeo.attributes.position;let n=0;for(let i=sparks.length-1;i>=0;i--){const s=sparks[i];s.l-=dt;if(s.l<=0){sparks.splice(i,1);continue}s.vy-=9*dt;s.x+=s.vx*dt;s.y+=s.vy*dt;s.z+=s.vz*dt;if(n<300){pos.setXYZ(n*2,s.x,s.y,s.z);pos.setXYZ(n*2+1,s.x-s.vx*.03,s.y-s.vy*.03,s.z-s.vz*.03);n++}}for(let i=n;i<300;i++){pos.setXYZ(i*2,0,-99,0);pos.setXYZ(i*2+1,0,-99,0)}pos.needsUpdate=true}
  {const pos=trGeo.attributes.position;let n=0;for(let i=tracers.length-1;i>=0;i--){const t2=tracers[i];t2.t+=dt;const d=t2.b.clone().sub(t2.a),len=d.length();const sp=len/Math.max(.02,len/650);const head=Math.min(len,t2.t*650);if(head>=len&&t2.t*650>len+4){tracers.splice(i,1);continue}if(n>=TR_N)continue;d.normalize();const s=t2.a.clone().addScaledVector(d,Math.max(0,head-3.5)),e2=t2.a.clone().addScaledVector(d,head);pos.setXYZ(n*2,s.x,s.y,s.z);pos.setXYZ(n*2+1,e2.x,e2.y,e2.z);n++}for(let i=n;i<TR_N;i++){pos.setXYZ(i*2,0,-99,0);pos.setXYZ(i*2+1,0,-99,0)}pos.needsUpdate=true}
  if(bomb&&!ROY){if(!bombM){bombM=gunModel('bomb');bombM.scale.setScalar(1.3);scene.add(bombM)}bombM.visible=bomb.st!=='boom';bombM.position.set(bomb.x,bomb.y+.06,bomb.z);if(bomb.st==='planted'&&bombM.userData.scr){const on=Math.sin(now*12*(1+bomb.t/10))>0;bombM.userData.scr.material.color.set(on?0xff2010:0x220000)}}else if(bombM)bombM.visible=false;
  // camera
  shakeV=Math.max(0,shakeV-dt*1.5);spec=null;if(!me.alive){deathT+=dt;if(deathT>2.5)spec=players.find(p=>p.alive&&(ROY?p===killer:p.team===me.team))||players.find(p=>p.alive&&(ROY||p.team===me.team))||(ROY?players.find(p=>p.alive):null)}
  const W=WPN[me.cur]||{};const pat=W.pat?PAT[W.pat]:null;let vp=0,vy=0;if(pat&&me.rcI>0){const i=Math.min(Math.floor(me.rcI),pat.length-1);vy=pat[i][0]*PI/180*.5;vp=pat[i][1]*PI/180*.5}else vp=me.kickP*.6;
  if(spec){const ey=eyeY(spec);camera.position.set(spec.x+Math.sin(spec.yaw)*2.8,ey+.7,spec.z+Math.cos(spec.yaw)*2.8);camera.rotation.set(-.18,spec.yaw,0,'YXZ');H.hint.textContent='Spectating '+spec.name}
  else if(!me.alive){camera.position.set(me.x,me.y+.4+Math.max(0,1.2-deathT),me.z);camera.rotation.set(me.pitch*.5-deathT*.3,me.yaw,Math.min(.6,deathT*.8),'YXZ')}
  else if(ROY&&me.inPlane){const pp=planePos();camera.position.set(pp.x-plane.dx*34-Math.sin(me.yaw)*8,plane.y+14,pp.z-plane.dz*34-Math.cos(me.yaw)*8);camera.lookAt(pp.x,plane.y,pp.z)}
  else if(ROY&&(me.air||me.chute)&&!me.onGround){camera.position.set(me.x+Math.sin(me.yaw)*5,me.y+2.8,me.z+Math.cos(me.yaw)*5);camera.rotation.set(me.pitch*.6-.3,me.yaw,0,'YXZ')}
  else{const sh=shakeV*shakeV*.04;camera.position.set(me.x+rnd(-sh,sh),eyeY(me)+rnd(-sh,sh),me.z);camera.rotation.set(me.pitch+vp,me.yaw-vy,0,'YXZ')}
  const fovT=me.scoped&&W.scope?78/(me.scoped===2&&W.scope2?W.scope2:W.cls==='rifle'?W.scope:W.scope*1.9):ROY&&me.ads?78/1.4:78;if(Math.abs(camera.fov-fovT)>.1){camera.fov+=(fovT-camera.fov)*Math.min(1,dt*20);camera.updateProjectionMatrix()}
  sun.position.set(camera.position.x+30,ROY?120:90,camera.position.z+25);sun.target.position.set(camera.position.x,0,camera.position.z);
  if(ROY)zoneWall();else if(zoneM)zoneM.visible=false;
  stepVM(dt,mdx,mdy);updHUD(dt);
  let bar=0,hint='';if(me.alive&&!ROY){if(me.plantT>0){bar=me.plantT/3.2;hint='Planting the bomb…'}else if(me.defT>0){bar=me.defT/(me.kit?5:10);hint='Defusing the bomb…'+(me.kit?'':' (no kit)')}else if(me.cur==='bomb'&&inSite(me.x,me.z))hint='Hold E (or fire) to plant the bomb';else if(me.inv[5]&&inSite(me.x,me.z))hint='Hold E to plant the bomb';else if(me.cur==='bomb')hint='Take the C4 to bombsite A or B';else if(me.team==='CT'&&bomb&&bomb.st==='planted'&&Math.hypot(me.x-bomb.x,me.z-bomb.z)<1.7)hint='Hold E to defuse';else if(round.phase==='freeze')hint='Freeze time · press B to buy';else{let best=null,bd=1.8;for(const it of items){const d=Math.hypot(it.x-me.x,it.z-me.z);if(d<bd){bd=d;best=it}}if(best)hint='E: pick up '+WPN[best.w].n}}
  if(me.alive&&ROY){if(me.inPlane)hint='Press SPACE to jump · M for the map';else if(me.healT>0){bar=1-me.healT/(me.healKind==='m'?6:3);hint='Using '+({m:'medkit',b:'bandage',e:'energy drink'})[me.healKind]+'…'}else{let best=null,bd=1.9;for(const it of items){const d=Math.hypot(it.x-me.x,it.z-me.z);if(d<bd&&Math.abs(it.y-me.y)<1.6){bd=d;best=it}}if(best){const nm=best.t==='gun'?WPN[best.w].n:best.t==='box'?(best.who||'')+' loot crate ('+best.cont.length+' items)':{ammo:(best.a||'')+' ammo',vest:'Armour vest L'+(best.lv||1),helm:'Helmet L'+(best.lv||1),band:'Bandage',med:'Medkit',drink:'Energy drink'}[best.t];hint='E: pick up '+nm}if(zone&&Math.hypot(me.x-zone.cx,me.z-zone.cz)>zone.r)hint='⚠ You are in the storm! Get to the safe zone. '+hint}}
  if(!me.alive&&!spec)hint=ROY?'You were eliminated'+(killer?' by '+killer.name:''):'You died'+(killer?' · killed by '+killer.name:'')+'. Wait for the next round';if(buyOpen)hint='';if(!spec)H.hint.textContent=hint;H.bar.style.display=bar>0?'block':'none';H.bar.firstChild.style.width=(bar*100)+'%';
  if(matchOver&&!overShown){overShown=true;setTimeout(()=>{if(state==='play')endScreen()},ROY?4000:5000)}});
menu();
if(window.__GS_TEST)window.__TX={get me(){return me},get feed(){return feed},get players(){return players},get state(){return state},startLocal,get round(){return round},get items(){return items},get zone(){return zone},get bomb(){return bomb},get SITES(){return SITES},get radarImg(){return radarImg},buy,astar,get boxes(){return boxes},api,joinRoom,hostRoom,get conns(){return conns},get NETROLE(){return NETROLE},set diff(v){diff=v},jumpOut,peerId,toggleBuy,canBuy,terrH,
  fast(sec){const dt=.05;let now=performance.now()/1000;for(let t=0;t<sec;t+=dt){now+=dt;for(const p of players){if(!p.alive)continue;const pi=p===me?{}:p.bot?botThink(p,dt,now):(p.inp||{});p.inp=pi;simPlayer(p,pi,dt,now)}if(ROY)stepRoyale(dt);else stepRound(dt);stepGrens(dt);stepFires(dt);evQ=[];evRel=[];for(const p of players)p.seenT=Math.max(0,(p.seenT||0)-dt)}return players.map(p=>[p.name,p.team,p.alive?1:0,p.hp|0,p.inv[1]||p.inv[2]||'-',p.kills]).map(a=>a.join(':')).join(' ')}};
return()=>{leaveNet();try{speechSynthesis.cancel()}catch(e){}st3.dispose()}})}
G.push({id:'breach',name:'Breach 5v5',kind:'game',wide:true,big:true,tint:'#e8b03a',blurb:'A Counter-Strike-style competitive shooter: AK-47, M4A4, AWP and the full CS2 lineup with real stats and spray patterns, counter-strafing, headshots, wallbangs, the money economy, buy zones, flashbangs, smokes, molotovs, the C4 and a halftime side swap. Online with friends (peer-to-peer) or against bots.',fmt:b=>b+' match wins',
art:'<rect width="120" height="72" fill="#e8d0a8"/><rect y="48" width="120" height="24" fill="#b89a70"/><rect x="0" y="10" width="34" height="40" fill="#c9a878"/><rect x="86" y="14" width="34" height="36" fill="#c9a878"/><rect x="40" y="36" width="12" height="12" fill="#8a6a3a" stroke="#4a3418"/><text x="70" y="44" font-family="Arial Black" font-size="16" fill="#c8322a" opacity=".8">A</text><path d="M70 72l14-30h8l-4 30z" fill="#26282c"/><path d="M84 42l18-6 2 4-18 6z" fill="#26282c"/><path d="M58 28h8M62 24v8" stroke="#4cff5c" stroke-width="1.5"/>',
run(root,c){return tacticalGame(root,c,{mode:'breach',id:'breach'})}});
G.push({id:'royale',name:'Last Drop',kind:'game',wide:true,big:true,tint:'#ffb02e',blurb:'Battle royale on a hilly 400 m island: skydive from the plane, loot two-storey houses, a military fort and a quarry for weapons by rarity, armour, helmets and meds, and outlast the closing storm. 30 players: online friends plus bots.',fmt:b=>b+' wins',
art:'<rect width="120" height="72" fill="#9ac8f0"/><path d="M0 50q30-14 60-4t60-6v32H0z" fill="#5a7a3a"/><rect x="14" y="36" width="20" height="14" fill="#e6dccb"/><path d="M12 36l12-8 12 8z" fill="#7a3a2a"/><rect x="80" y="32" width="24" height="18" fill="#8a4a36"/><circle cx="60" cy="58" r="30" fill="none" stroke="#50a0ff" stroke-width="2" stroke-dasharray="4 3"/><path d="M50 10q10-8 20 0z" fill="#e8321e"/><path d="M50 10l10 12M70 10l-10 12" stroke="#333" stroke-width=".6"/><rect x="58" y="22" width="4" height="6" fill="#3a4428"/>',
run(root,c){return tacticalGame(root,c,{mode:'royale',id:'royale'})}});
