  /* ---------- villain mode (Overlord runs on this engine) ---------- */
  const VIL=[
    {id:'overlord',name:'Overlord',col:'#B3122E',tag:'Evil alien powerhouse',pw:'Laser eyes that slice and ignite · R: thunder clap · Q: sky slam',fly:1.7,eye:0xFF2A2A,fire:'LASER',pow:'CLAP',pcd:5,beam:[0xFFF3C4,0xFF2A2A],fig:{suit:0x1D1A2F,trim:0xB3122E,mask:0x111111,cape:0x8B0000,emblemSides:3,hair:0x111111,bulk:1.1}},
    {id:'ruin',name:'Ruin',col:'#2BB673',tag:'Giant green rage brute',pw:'Smash punches · hold Space to leap, run up walls · R: throw cars · Q: ground pound · Shift: RAGE',mode:'ground',scale:1.9,cam:1.7,eye:0xB6FF4A,fire:'SMASH',pow:'THROW',pcd:1.1,fig:{suit:0x4CAF50,skin:0x4CAF50,trim:0x6a2c91,mask:0x4CAF50,hair:0x14301a,bulk:1.7,emblemSides:4}},
    {id:'havoc',name:'Havoc',col:'#5A5470',tag:'Mercenary with far too many guns',pw:'Minigun, rockets, grenades, railgun, C4, hand lasers · Q: airstrike · X: orbital strike',fly:1,eye:0xFFD23F,fire:'SHOOT',pow:'DET',pcd:1,fig:{suit:0x2b2b33,trim:0xF2352A,mask:0x111111,helm:0x3a3a44,emblemSides:3,bulk:1.25,cape:0x7a1020}},
    {id:'tempest',name:'Tempest',col:'#7FC8F8',tag:'Storm witch',pw:'Chain lightning · R: tornadoes that tear buildings apart and follow your aim · Q: sky slam',fly:1.5,eye:0x9FE8FF,fire:'ZAP',pow:'TWISTER',pcd:5,beam:[0xffffff,0x9FE8FF],fig:{suit:0x3b2a6b,trim:0x7FC8F8,mask:0x3b2a6b,cape:0x241a47,hair:0xeef0ff,bulk:1}},
    {id:'pyra',name:'Pyra',col:'#FF7A2A',tag:'Queen of fire',pw:'Flamethrower that melts walls and spreads fire · R: meteor strike · Q: sky slam',fly:1.5,eye:0xFFB02A,fire:'FLAME',pow:'METEOR',pcd:3.5,beam:[0xFFF3C4,0xFF7A2A],fig:{suit:0x3a0a0a,trim:0xFF7A2A,mask:0x3a0a0a,cape:0xFF3B1F,hair:0xFF5A1F,bulk:1}}];
  let vi=clamp(S.get('hs_villain_pick',0)|0,0,VIL.length-1),VL=VM?VIL[vi]:VIL[2],vcd=0,vpcd=0,rageT=0,rageCd=0,punchT=0,punchSide=0,zapT=0,zapN=0,flameT=0,leapCh=0,leapL=false,detL2=false,fires=[],twisters=[];
  const eyeMat=new T.MeshBasicMaterial({color:0xFF2A2A});
  const isGround=()=>VM&&VL.mode==='ground',vsc=()=>VM?(VL.scale||1):1;
  function setVillain(i){vi=i;VL=VIL[i];S.set('hs_villain_pick',i);HR.remove(hero);hero=K.fig(VL.fig);hero.scale.setScalar(1.15*(VL.scale||1));HR.add(hero);U=hero.userData;
    [-.1,.1].forEach(x0=>{const e=part(T,bx(T,.11,.07,.03),eyeMat,x0,.3,.245,U.neck);e.userData.noInk=1});eyeMat.color.setHex(VL.eye);
    U.armR.add(WG);WG.visible=VL.id==='havoc';handGlow.forEach((g,k)=>(k?U.armL:U.armR).add(g));
    if(VL.id==='havoc'){part(T,bx(T,.48,.08,.05),new T.MeshBasicMaterial({color:0xF2352A}),0,.31,.25,U.neck).userData.noInk=1;[-.42,.42].forEach(x0=>part(T,bx(T,.3,.22,.46),TM(0x3a3a44),x0*1.25,.72,0,U.torso))}
    if(VL.id==='tempest'){const o=part(T,sp(T,.2),glowM(0x9FE8FF),0,-.8,0,U.armR);o.userData.noInk=1}
    if(VL.id==='pyra'){for(let k=0;k<5;k++){const f=part(T,new T.ConeGeometry(.09,.32,6),glowM(k%2?0xFFD23F:0xFF7A2A),-.18+k*.09,.66,0,U.neck);f.userData.noInk=1}const o=part(T,sp(T,.2),glowM(0xFF7A2A),0,-.8,0,U.armR);o.userData.noInk=1}
    if(VL.id==='ruin')part(T,bx(T,.66*1.7,.3,.4*1.7),TM(0x6a2c91),0,-.12,0,U.hips);
    hero.traverse(o=>{if(o.isMesh)o.castShadow=hiQ});
    wbar.style.display=VL.id==='havoc'?'flex':'none';tbD.textContent=VL.id==='havoc'?'DET':VL.pow;tbS.textContent=VL.id==='havoc'?'STRIKE':VL.mode==='ground'?'POUND':'SLAM';
    const bc=VL.beam||[0xFFF4D6,0xFF3A22];beams.forEach(b=>{b.c.material.color.setHex(bc[0]);b.o.material.color.setHex(bc[1])});
    root.querySelectorAll('.tctl .tbtn').forEach(b=>{if(b.classList.contains('fire'))b.textContent=VL.fire;else if(b.classList.contains('jump'))b.textContent=VL.mode==='ground'?'LEAP':'UP';else if(b.classList.contains('alt'))b.textContent=VL.mode==='ground'?'RAGE':'BOOST'});
    setW(VL.id==='havoc'?0:0)}
  function villainTick(dt,fire,I){const rm=rageT>0?1.6:1;vcd-=dt;vpcd-=dt;punchT-=dt;rageT-=dt;rageCd-=dt;
    const o=camera.position.clone(),d=new T.Vector3();camera.getWorldDirection(d);
    if(fire){P.fireT=1;if(VL.id==='overlord')laser(dt,'eyes');else if(VL.id==='tempest'){zapT-=dt;if(zapT<=0){zapT=.11;zap(o,d)}}else if(VL.id==='pyra')flame(dt,o,d);else if(VL.id==='ruin'&&vcd<=0){vcd=rageT>0?.26:.36;punch(d,rm)}}else{lzAcc=0;lzBlast=0}
    const pk=!!(tap.r||(I.det&&!detL2));detL2=!!I.det;if(pk){if(vpcd>0)H.say(VL.pow+' ready in '+vpcd.toFixed(1)+'s',700);else power(o,d,rm)}
    if(VL.id==='ruin'&&(input.keys.shift||I.alt)&&rageT<=0&&rageCd<=0){rageT=8;rageCd=22;H.pow('RAAAGE!',P.p.clone().setY(P.p.y+8),'#2BB673');noise(.8,'lowpass',160,.5);cam.shake=1}
    if(VL.id==='pyra'||VL.id==='tempest')handGlow.forEach(g=>{g.visible=false})}
  function bolt(a,b){const seg=6,L=a.distanceTo(b);let p0=a.clone();for(let i=1;i<=seg;i++){const p1=a.clone().lerp(b,i/seg);if(i<seg)p1.add(new T.Vector3(Math.random()-.5,Math.random()-.5,Math.random()-.5).multiplyScalar(L*.07));tracer(p0,p1,0x9FE8FF,2.6,.13);tracer(p0,p1,0xffffff,.9,.11);p0=p1}}
  function zap(o,d){const h=aim(o,d,240);const hand=U.armR.localToWorld(new T.Vector3(0,-.8,0));bolt(hand,h.pt);flash(h.pt,2.2);
    if(h.B){if(dmgBlock(h.B,h.k,3,d.x*10,4,d.z*10))hitMark();for(let q=0;q<2;q++){const gx=Math.floor(h.pt.x/BS+(Math.random()-.5)*2.2),gy=Math.floor(h.pt.y/BS+(Math.random()-.5)*2.2),gz=Math.floor(h.pt.z/BS+(Math.random()-.5)*2.2);const B=bAtG(gx,gz);if(B&&gy>=0&&gy<B.fh)dmgBlock(B,vI(B,gx-B.gx0,gy,gz-B.gz0),2,d.x*8,3,d.z*8)}K.burst(h.pt.clone(),[0x9FE8FF,0xffffff],5,9,.3)}
    else if(h.ent){hitEnt(h.ent,h.pt,28,d);hitMark()}
    if(crowd)crowd.blast(h.pt,2.4,.7);let from=h.pt.clone(),n=0;const used=new Set([h.ent]);while(n<3){let best=null,bd=30;enemies.forEach(e=>{if(e.dead||used.has(e))return;const dd=e.p.distanceTo(from);if(dd<bd){bd=dd;best=e}});if(!best)break;used.add(best);bolt(from,best.p);hurtEnemy(best,24,from);from=best.p.clone();n++}
    zapN++;if(zapN%5===0)explode(h.pt.clone(),3.2,.8,true,true);if(zapN%2)noise(.09,'highpass',2600,.09)}
  function flame(dt,o,d){flameT-=dt;const hand=U.armR.localToWorld(new T.Vector3(0,-.8,0));for(let k=0;k<2;k++){const v=d.clone().multiplyScalar(26+Math.random()*12).add(new T.Vector3((Math.random()-.5)*6,(Math.random()-.5)*6,(Math.random()-.5)*6));K.puff(hand.clone(),Math.random()<.5?0xFF7A2A:0xFFD23F,.7+Math.random()*.6,.5,v)}
    if(flameT>0)return;flameT=1/15;for(let r=0;r<3;r++){const dd=d.clone().add(new T.Vector3((Math.random()-.5)*.22,(Math.random()-.5)*.22,(Math.random()-.5)*.22)).normalize();const h=aim(o,dd,34);
      if(h.B){dmgBlock(h.B,h.k,1,dd.x*4,2,dd.z*4);if(Math.random()<.07)ignite(h.pt.clone())}else if(h.ent)hitEnt(h.ent,h.pt,6,dd);if(h.t&&crowd)crowd.blast(h.pt,2.6,.5)}
    enemies.forEach(e=>{if(e.dead)return;const to=e.p.clone().sub(o);const L=to.length();if(L<38&&to.normalize().dot(d)>.93)hurtEnemy(e,6,o)});if(Math.random()<.3)noise(.12,'lowpass',500,.07)}
  function punch(d,rm){punchT=.22;punchSide^=1;const s=vsc();const fw=new T.Vector3(d.x,0,d.z).normalize();const pt=P.p.clone().addScaledVector(fw,2.6*s).setY(P.p.y+1.3*s+d.y*3);explode(pt,4.3*rm,1.5*rm,true,true);cam.shake=Math.max(cam.shake,.35);if(Math.random()<.35)H.pow(pick(['SMASH!','POW!','WHAM!','KRAK!']),pt.clone().setY(pt.y+2),'#2BB673')}
  function quakeLine(){const fw=new T.Vector3(-Math.sin(cam.yaw),0,-Math.cos(cam.yaw));const c0=P.p.clone();H.pow('EARTHQUAKE!',c0.clone().setY(8),'#FFD23F');for(let s2=-1;s2<=1;s2+=2)for(let k=1;k<=7;k++){const q=c0.clone().addScaledVector(fw,s2*k*7).setY(.8);strikes.push({t:k*.08,fn:()=>{explode(q,5.5,1.2,true,true);K.burst(q.clone(),[0x8c86a3,0x5A5470,0xd8d4e4],8,10,1)}})}}
  function power(o,d,rm){vpcd=VL.pcd;const h=aim(o,d,420);
    if(VL.id==='overlord'){const c0=P.p.clone();explode(c0.clone().setY(Math.max(1,c0.y)),10,1.5,true,true);for(let k=0;k<10;k++){const a=k/10*6.283;const q=c0.clone().add(new T.Vector3(Math.cos(a)*14,0,Math.sin(a)*14)).setY(Math.max(1,c0.y));strikes.push({t:.12,fn:()=>explode(q,6.5,1.1,true,true)})}K.ring(c0.clone(),0xffffff,2,70,.8);if(crowd)crowd.blast(c0,34,1.4);H.pow('THUNDER CLAP!',c0.clone().setY(c0.y+6),'#FFD23F');noise(1.3,'lowpass',120,.6);cam.shake=1.5}
    else if(VL.id==='tempest'){if(twisters.length>=3){const t0=twisters.shift();scene.remove(t0.g)}twisters.push(mkTwister(h.pt.clone().setY(0)));H.say('🌪️ Tornado! It follows your aim.',1300);noise(1.5,'bandpass',300,.2)}
    else if(VL.id==='pyra'){const tp=h.pt.clone();const m=new T.Mesh(new T.SphereGeometry(2.4,12,10),glowM(0xFF7A2A));const st=tp.clone().add(new T.Vector3(50,170,35));m.position.copy(st);scene.add(m);projs.push({k:'meteor',m,v:tp.clone().sub(st).normalize().multiplyScalar(120),l:4});H.say('☄️ Meteor incoming!',900);sweep(1500,200,1.2,'sawtooth',.05)}
    else if(VL.id==='ruin'){const m=toonCar(K,pick(CARC),Math.random()<.2);m.scale.setScalar(1.2);scene.add(m);const s=vsc();const hand=P.p.clone().setY(P.p.y+3*s);m.position.copy(hand);const v=h.pt.clone().sub(hand);const L=v.length();v.normalize().multiplyScalar(62);v.y+=Math.min(14,L*.09);projs.push({k:'car',m,v,l:5});beep(200,.15,'sawtooth',.05)}}
  const twG=new T.ConeGeometry(1,1,14,1,true);
  function mkTwister(pt){const g=new T.Group();for(let k=0;k<8;k++){const m=new T.Mesh(twG,new T.MeshBasicMaterial({color:k%2?0xc8d2e6:0x8c96ab,transparent:true,opacity:.42,side:T.DoubleSide,depthWrite:false}));const r=2+k*1.7;m.scale.set(r,6,r);m.position.y=3+k*5.3;m.rotation.x=Math.PI;g.add(m)}g.position.copy(pt);scene.add(g);return{g,t:12,acc:0}}
  function tickTwisters(dt){if(!twisters.length)return;const o=camera.position.clone(),d=new T.Vector3();camera.getWorldDirection(d);const aimPt=aim(o,d,420).pt;
    twisters=twisters.filter(tw=>{tw.t-=dt;const p=tw.g.position;const to=aimPt.clone().setY(0).sub(p);const L=to.length();if(L>1)p.addScaledVector(to,Math.min(1,15*dt/L));tw.g.children.forEach((m,k)=>{m.rotation.y+=dt*(5+k)});tw.g.rotation.z=Math.sin(tw.t*2)*.08;
      tw.acc+=dt;while(tw.acc>.08){tw.acc-=.08;for(let q=0;q<11;q++){const a=Math.random()*6.283,r=Math.random()*6.5,y=Math.random()*46;const x=p.x+Math.cos(a)*r,z=p.z+Math.sin(a)*r;const gx=Math.floor(x/BS),gy=Math.floor(y/BS),gz=Math.floor(z/BS);const B=bAtG(gx,gz);if(B&&gy>=0&&gy<B.fh){const k=vI(B,gx-B.gx0,gy,gz-B.gz0);if(B.hp[k])killBlock(B,k,-Math.sin(a)*18+Math.cos(a)*4,14+Math.random()*12,Math.cos(a)*18+Math.sin(a)*4)}}
        if(crowd)crowd.blast(p.clone().setY(1),7.5,1);enemies.forEach(e=>{if(!e.dead&&Math.hypot(e.p.x-p.x,e.p.z-p.z)<10&&e.p.y<55)hurtEnemy(e,18,p)});cars.forEach(q=>{if(q.alive&&q.m.position.distanceTo(p)<8)hurtCar(q,30,p)});people.forEach(q=>{if(q.st!=='gone'&&q.st!=='fly'&&q.g.position.distanceTo(p)<9)flingP(q,p,22)})}
      if(Math.random()<dt*6)K.puff(p.clone().setY(Math.random()*6),0x8c86a3,2.5,1.2,new T.Vector3(0,6,0));if(tw.t<=0){scene.remove(tw.g);return false}return true})}
  const fireCone=new T.ConeGeometry(1,2.6,7);fireCone.translate(0,1.3,0);
  function ignite(pt){if(fires.length>=45)return;const m=new T.Mesh(fireCone,glowM(Math.random()<.5?0xFF7A2A:0xFFB02A));m.position.copy(pt);scene.add(m);fires.push({m,p:pt.clone(),t:7+Math.random()*4,acc:Math.random()*.4})}
  function tickFires(dt){if(!fires.length)return;fires=fires.filter(f=>{f.t-=dt;const s=Math.min(1,f.t/2)*(1+Math.random()*.3);f.m.scale.set(s*1.5,s*(1.2+Math.random()*.7),s*1.5);f.acc+=dt;
      if(f.acc>.45){f.acc=0;for(let q=0;q<3;q++){const x=f.p.x+(Math.random()-.5)*5,y=f.p.y+(Math.random()-.3)*4,z=f.p.z+(Math.random()-.5)*5;const gx=Math.floor(x/BS),gy=Math.floor(y/BS),gz=Math.floor(z/BS);const B=bAtG(gx,gz);if(B&&gy>=0&&gy<B.fh){const k=vI(B,gx-B.gx0,gy,gz-B.gz0);if(B.hp[k]){dmgBlock(B,k,1,0,2,0);if(Math.random()<.12)ignite(new T.Vector3(x,(gy+1)*BS,z))}}}
        if(Math.random()<.5)K.puff(f.p.clone().setY(f.p.y+3),0x3a3552,2,2.2,new T.Vector3(0,4,0));if(crowd)crowd.scare(f.p,22)}
      if(f.t<=0){scene.remove(f.m);return false}return true})}
  function ruinMove(dt,mv,upK){const sp=rageT>0?24:17;const k=P.ground?10:1.5;P.v.x+=(mv.x*sp-P.v.x)*Math.min(1,dt*k);P.v.z+=(mv.z*sp-P.v.z)*Math.min(1,dt*k);if(P.slam<=0)P.v.y-=40*dt;
    if(P.ground){if(upK){leapCh=Math.min(1,leapCh+dt*1.1);P.v.x*=.9;P.v.z*=.9}else if(leapL&&leapCh>0){const fw=cam.dir3();P.v.y=18+leapCh*38;P.v.x+=fw.x*leapCh*50;P.v.z+=fw.z*leapCh*50;P.ground=false;if(leapCh>.6)H.pow('HRAAH!',P.p.clone().setY(P.p.y+7),'#2BB673');beep(220+leapCh*200,.18,'triangle',.06);K.burst(P.p.clone(),[0x8c86a3,0xd8d4e4],12,10,.8);leapCh=0}}leapL=upK;
    if(mv.m>.3){const ax=P.p.x+mv.x*1.2,az=P.p.z+mv.z*1.2;if(blockedAt(ax,P.p.y,az)&&!blockedAt(P.p.x,P.p.y+2.5,P.p.z)){P.v.y=Math.max(P.v.y,11);P.ground=false;if(Math.random()<dt*8)K.burst(P.p.clone().setY(P.p.y+1),[0x8c86a3,0xd8d4e4],2,5,.6)}}}
  /* ---------- villain missions ---------- */
  let vmi=-1,timeLeft=0,target=0,vehT=0,pplT=0,airN=0,heroN=0,heroSp=0,boss=null,airT=0;const LVN=['Easy','Normal','Hard'];const money=n=>'$'+(n/100).toFixed(1)+'M';const missionPtr=K.pointer();
  function mkPlane(){const g=new T.Group();const W0=TM(0xf2f2f6),R0=TM(pick([0xF2352A,0x2d6fd6,0x2BB673]));part(T,cy(T,1.6,1.3,16,10),W0,0,0,0,g).rotation.x=Math.PI/2;part(T,bx(T,22,.35,3.4),W0,0,-.2,.5,g);part(T,bx(T,7,.3,2),W0,0,.4,-7,g);part(T,bx(T,.3,3.4,2.4),R0,0,2,-7,g);[-5,5].forEach(x0=>part(T,cy(T,.6,.6,2.4,8),TM(0x8c86a3),x0,-.9,1,g).rotation.x=Math.PI/2);K.ink(g,.05);scene.add(g);const a=Math.random()*6.283;const dir=new T.Vector3(Math.cos(a),0,Math.sin(a));g.position.set(-dir.x*300,70+Math.random()*40,-dir.z*300);g.lookAt(g.position.clone().add(dir));const e={kind:'plane',m:g,p:g.position,r:8,hp:160,v:dir.multiplyScalar(36)};addMarker(e,'✈️');return e}
  function mkBlimp(){const g=new T.Group();const b=part(T,sp(T,1),TM(0xd8d4e4),0,0,0,g);b.scale.set(5,5,15);part(T,bx(T,2.4,1.6,4.4),TM(0xFFD23F),0,-5.4,1,g);[[0,4,-12],[0,-4,-12]].forEach(([x0,y0,z0])=>part(T,bx(T,.4,3,3),TM(0xF2352A),x0,y0,z0,g));part(T,bx(T,6,.4,3),TM(0xF2352A),0,0,-12,g);K.ink(g,.05);scene.add(g);const a=Math.random()*6.283;const dir=new T.Vector3(Math.cos(a),0,Math.sin(a));g.position.set(-dir.x*220,85,-dir.z*220);g.lookAt(g.position.clone().add(dir));const e={kind:'blimp',m:g,p:g.position,r:13,hp:420,v:dir.multiplyScalar(9)};addMarker(e,'🎈');e.mkH=10;return e}
  function mkNews(){const e=mkHeli(0xFFD23F);e.kind='news';e.hp=140;e.ctr=new T.Vector3((Math.random()-.5)*200,0,(Math.random()-.5)*200);e.mk.material.map=markerTex('📺','#FFD23F');return e}
  function mkHeroJet(){const g=new T.Group();const Bl=TM(0x2d6fd6),Gd=TM(0xFFD23F);part(T,bx(T,1.4,.9,5.4),Bl,0,0,0,g);part(T,bx(T,8,.18,2),Bl,0,0,-.4,g);part(T,bx(T,.18,1.4,1.2),Gd,0,.8,-2.2,g);part(T,sp(T,.5),TM(0x9fd6ff),0,.5,1.4,g).scale.set(1,.7,1.6);const fl=part(T,sp(T,.45),glowM(0x7FC8F8),0,0,-2.9,g);fl.userData.noInk=1;K.ink(g,.05);scene.add(g);const a=Math.random()*6.283;g.position.set(P.p.x+Math.cos(a)*230,Math.max(40,P.p.y+20),P.p.z+Math.sin(a)*230);const e={kind:'herojet',m:g,p:g.position,r:3.8,hp:c.pick(70,90,110),v:new T.Vector3(),ang:a,cd:2+Math.random()*2,dive:0};addMarker(e,'🦸');return e}
  function mkBoss(){const g=new T.Group();const f=K.fig({suit:0x2d6fd6,trim:0xF2352A,mask:0x2d6fd6,cape:0xF2352A,hair:0x6b4a33,emblemSides:5,bulk:1.3});f.scale.setScalar(1.5);g.add(f);scene.add(g);g.position.set(P.p.x+60,Math.max(30,P.p.y+15),P.p.z+60);const e={kind:'boss',m:g,f,p:g.position,r:2.6,hp:c.pick(900,1300,1700),max:c.pick(900,1300,1700),v:new T.Vector3(),st:'circle',t:4,ang:0,dizzy:0,cd:3};addMarker(e,'🦸');return e}
  function tickVillainEnemy(e,dt,now,d){const p=e.p;
    if(e.kind==='plane'||e.kind==='blimp'){p.addScaledVector(e.v,dt);if(e.kind==='blimp')e.m.rotation.z=Math.sin(now/900)*.04;if(Math.hypot(p.x,p.z)>360)return false}
    else if(e.kind==='news'){e.ang+=dt*.25;const goal=new T.Vector3(e.ctr.x+Math.cos(e.ang)*70,55,e.ctr.z+Math.sin(e.ang)*70);const dv=goal.sub(p);const L=dv.length();e.v.lerp(dv.multiplyScalar(L>1?Math.min(30,L)/L:0),Math.min(1,dt));p.addScaledVector(e.v,dt);e.m.rotation.y=Math.atan2(e.v.x,e.v.z);e.rot.rotation.y+=dt*28;if(solidW(p.x,p.y,p.z))hurtEnemy(e,999,p)}
    else if(e.kind==='herojet'){e.cd-=dt;let goal;if(e.dive>0){e.dive-=dt;goal=P.p.clone().add(new T.Vector3(0,1,0))}else{e.ang+=dt*.5;goal=new T.Vector3(P.p.x+Math.cos(e.ang)*70,Math.max(30,P.p.y+15),P.p.z+Math.sin(e.ang)*70);if(e.cd<=0){e.dive=2.2;e.cd=c.pick(5,4,3)}}
      const dv=goal.sub(p);const L=dv.length();e.v.lerp(dv.multiplyScalar(Math.min(e.dive>0?85:55,L)/Math.max(1,L)),Math.min(1,dt*1.5));p.addScaledVector(e.v,dt);e.m.lookAt(p.clone().add(e.v));if(e.dive>0&&Math.random()<dt*6&&d<120)eShoot(p.clone(),'bullet');if(d<4&&e.dive>0){hurt(12,'Hero Corps ram!');e.dive=0}if(solidW(p.x,p.y,p.z))hurtEnemy(e,999,p)}
    else if(e.kind==='boss'){const B=e;B.t-=dt;B.dizzy-=dt;B.cd-=dt;K.pose(B.f,B.st==='charge'?'fly':'hover',now/300);K.capeAnim(B.f,.7,now/1000,8);
      if(B.dizzy>0){B.v.multiplyScalar(Math.pow(.2,dt));B.m.rotation.y+=dt*8;if(Math.random()<dt*6)K.burst(p.clone().add(new T.Vector3(0,4,0)),[0xFFD23F],3,3,.4)}
      else if(B.st==='circle'){B.ang+=dt*.6;const goal=new T.Vector3(P.p.x+Math.cos(B.ang)*28,Math.max(6,P.p.y+4),P.p.z+Math.sin(B.ang)*28);const dv=goal.sub(p);const L=dv.length();B.v.lerp(dv.multiplyScalar(Math.min(60,L*2)/Math.max(1,L)),Math.min(1,dt*2.5));B.m.lookAt(P.p);if(B.cd<=0&&d<90){B.cd=c.pick(1.4,1,.7);eShoot(p.clone().add(new T.Vector3(0,3,0)),'rocket')}if(B.t<=0){B.st='charge';B.t=1.4;B.cv=P.p.clone().add(new T.Vector3(0,1,0)).sub(p).normalize().multiplyScalar(c.pick(70,85,100));H.say('⚠️ Captain Valor is charging! Dodge!',900)}}
      else{B.v.copy(B.cv);B.m.lookAt(p.clone().add(B.cv));if(d<4.5){hurt(28,'POW! Captain Valor lands a punch!');P.v.addScaledVector(B.cv,.6);B.st='circle';B.t=5+Math.random()*2}
        if(solidW(p.x,p.y+2,p.z)){explode(p.clone(),7,1.3,true,true);B.dizzy=3.5;B.st='circle';B.t=6;H.pow('DIZZY! Hit him now!',p.clone().setY(p.y+6),'#FFD23F')}if(B.t<=0){B.st='circle';B.t=5+Math.random()*2}}
      p.addScaledVector(B.v,dt);if(p.y<3)p.y=3;if(B.dizzy<=0&&d<5&&Math.hypot(P.v.x,P.v.y,P.v.z)>45){hurtEnemy(B,60,P.p);P.v.multiplyScalar(-.4);H.pow('KA-POW!',p.clone().setY(p.y+4),'#FFD23F');cam.shake=1}}
    return true}
  function missionTick(dt){if(!VM)return;const LV=LVN[c.level]||'Normal';let tg=null,tl='';
    if(vmi<0){H.cap('Free roam · '+VL.name+' in the city','Damage '+money(score)+' · '+stats.towers+' towers · '+stats.cars+' vehicles · '+stats.people+' people flung · P for menu');missionPtr(null);return}
    if(vmi===0){timeLeft-=dt;H.cap('Issue #1 · Grand Entrance','Damage '+money(score)+' / '+money(target)+' · '+Math.max(0,Math.ceil(timeLeft))+'s left');
      if(score>=target)F.win(M,Math.round(score)+Math.round(timeLeft)*2,[[money(score),'damage'],[stats.towers,'toppled'],[stats.cars,'vehicles'],[LV,'mode']],'The city now knows your name. It’s on every news channel, usually followed by the word “RUN”.');else if(timeLeft<=0)F.lose(M,'Not scary enough','The news called it “a mild inconvenience”. How insulting. Try again?')}
    if(vmi===1){timeLeft-=dt;H.cap('Issue #2 · Rush Hour','Vehicles '+Math.min(stats.cars,vehT)+'/'+vehT+' · people flung '+Math.min(stats.people,pplT)+'/'+pplT+' · '+Math.max(0,Math.ceil(timeLeft))+'s left');
      if(stats.cars>=vehT&&stats.people>=pplT)F.win(M,Math.round(score)+Math.round(timeLeft)*3,[[stats.cars,'vehicles'],[stats.people,'people flung'],[stats.towers,'toppled'],[LV,'mode']],'Traffic reports now just say “Don’t.” Everyone is working from home until further notice.');else if(timeLeft<=0)F.lose(M,'Traffic survived','Somehow, everyone still got home on time. Try again?')}
    if(vmi===2){const need=c.pick(5,7,9);airT-=dt;const alive=enemies.filter(e=>!e.dead&&(e.kind==='plane'||e.kind==='blimp'||e.kind==='news')).length;if(airT<=0&&alive<4){airT=4;const r=Math.random();enemies.push(r<.45?mkPlane():r<.75?mkNews():mkBlimp())}
      let bd=1e9;enemies.forEach(e=>{if(e.dead||!(e.kind==='plane'||e.kind==='blimp'||e.kind==='news'))return;const d=e.p.distanceTo(P.p);if(d<bd){bd=d;tg=e.p.clone();tl=({plane:'✈️ PLANE',blimp:'🎈 BLIMP',news:'📺 CHOPPER'})[e.kind]+' '+Math.round(d)+'m'}});
      H.cap('Issue #3 · Air Traffic','Aircraft down '+airN+'/'+need+' · damage '+money(score));if(airN>=need)F.win(M,Math.round(score)+Math.round(P.hp)*3,[[airN,'aircraft'],[money(score),'damage'],[Math.round(P.hp),'health'],[LV,'mode']],'Every airline has quietly rerouted around the city. The blimp company has filed a strongly worded letter.')}
    if(vmi===3){const total=12;airT-=dt;const alive=enemies.filter(e=>!e.dead&&e.kind==='herojet').length;if(airT<=0&&alive<c.pick(3,4,5)&&heroSp<total){airT=c.pick(3,2.4,1.8);heroSp++;enemies.push(mkHeroJet())}
      let bd=1e9;enemies.forEach(e=>{if(e.dead||e.kind!=='herojet')return;const d=e.p.distanceTo(P.p);if(d<bd){bd=d;tg=e.p.clone();tl='🦸 JET '+Math.round(d)+'m'}});
      H.cap('Issue #4 · Hero Corps','Jets downed '+heroN+'/'+total+' · damage '+money(score));if(heroN>=total)F.win(M,Math.round(score)+Math.round(P.hp)*3,[[heroN,'jets'],[money(score),'damage'],[Math.round(P.hp),'health'],[LV,'mode']],'The Hero Corps retreats to repaint their jets. Nobody else is brave enough to get in your way. Almost nobody.')}
    if(vmi===4&&boss){tg=boss.p.clone();tl='🦸 CAPTAIN VALOR '+Math.round(boss.p.distanceTo(P.p))+'m';H.cap('Issue #5 · Captain Valor','Valor '+Math.max(0,Math.ceil(boss.hp/boss.max*100))+'% '+'█'.repeat(Math.max(0,Math.ceil(boss.hp/boss.max*10)))+(boss.dizzy>0?' · DIZZY: hit him!':''));
      if(boss.dead)F.win(M,Math.round(score)+Math.round(P.hp)*5,[['KO','Valor'],[money(score),'damage'],[Math.round(P.hp),'health'],[LV,'mode']],'Captain Valor limps home to rethink his career. Metro City is yours. Every channel, every billboard, every blimp.')}
    missionPtr(tg?tg.add(new T.Vector3(0,3,0)):null,tl)}
