G.push({id:'hs_villain',name:'Overlord',kind:'hero',levels:true,wide:true,tint:'#B3122E',blurb:'3D villain rampage. Pick one of five villains (laser eyes, a giant green brute, a mercenary, a storm witch or a fire queen) and wreck the city: towers, fire, crowds, cars, planes, choppers and blimps.',fmt:b=>'$'+(b/10).toFixed(1)+'M',
art:'<rect width="120" height="72" fill="#3a1030"/><rect y="46" width="120" height="26" fill="#FF9F43" opacity=".35"/><path d="M4 72V36h14v36M22 72V22h16v50M84 72V30h14v42M100 72V44h14v28" fill="#5A5470" stroke="#1D1A2F" stroke-width="2.5"/><path d="M38 40L22 47" stroke="#FFD23F" stroke-width="6" stroke-linecap="round"/><path d="M38 40L22 47" stroke="#F2352A" stroke-width="3" stroke-linecap="round"/><path d="M60 32l-22 24 30-10z" fill="#8B0000" stroke="#1D1A2F" stroke-width="2.5" stroke-linejoin="round"/><rect x="54" y="30" width="18" height="22" rx="3" fill="#1D1A2F"/><circle cx="63" cy="24" r="8" fill="#f1c7a0" stroke="#1D1A2F" stroke-width="2.5"/><path d="M58 23h4M64 23h4" stroke="#F2352A" stroke-width="3"/><path d="M60 38l3 5 3-5z" fill="#F2352A"/>',
run(root,c){return with3D(root,c,()=>{
  const st3=Stage3D(root,c,{lock:true,dragLook:true,fov:70,far:560,fireLabel:'LASER',altLabel:'BOOST',jumpLabel:'UP'});
  const M=[{name:'Grand Entrance',brief:['Metro City has never heard of you. Time to fix that.','Hold <b>click</b> for your main attack and press <b>R</b> for your power. Towers crack, catch fire and crumble. Cars fly. Crowds run.'],goal:'Cause the target amount of damage before the clock runs out.'},
    {name:'Rush Hour',brief:['Five o’clock. Everyone in Metro City is trying to get home.','Send the crowds running and wreck the traffic. Nobody gets hurt in this comic. They just get very, very annoyed.'],goal:'Wreck enough vehicles and send enough people running before time runs out.'},
    {name:'Air Traffic',brief:['Cargo planes, news choppers and a blimp keep flying over <i>your</i> city without asking.','Knock them out of the sky. The crews always bail out with parachutes, so only the paperwork suffers. Police choppers shoot back.'],goal:'Bring down the target number of aircraft.'},
    {name:'Hero Corps',brief:['The city sent the Hero Corps after you: a squadron of shiny blue jets with a strong sense of justice.','They fire stun blasts, so keep moving. Blast them out of the sky or ram them.'],goal:'Take down 12 Hero Corps jets.'},
    {name:'Captain Valor',brief:['Metro City’s greatest hero has come to stop you. He is fast, he is strong, and he has great hair.','Keep hitting him while he circles, and dodge when he charges. If he crashes into a building he gets dizzy, so hit him hard.'],goal:'Defeat Captain Valor.'}];
  const K=heroKit(st3,c,{id:'hs_villain',issues:5,camDist:7,camH:1.4,fogNear:140,fogFar:320,finale:'The city is yours!',start:mi=>start(mi)});
  const{T,scene,camera,input,TM,cam,H,F}=K;cam.pmin=-1.35;cam.pmax=1.3;
  K.sky('#3a1030','#FF9F43');K.lights(0xffe0d0,0x6a3050,.75);
  const city=K.streamCity({blk:28,st:18,hmul:1.5,chunk:3,radius:2,seed:13});city.update(0,0,true);cam.boxes=city.boxes;
  const turnB=K.touchBtn('TURN','drift'),slamB=K.touchBtn('SLAM','slam','left:auto;right:240px;bottom:120px'),powB=K.touchBtn('POWER','power','left:auto;right:240px;bottom:196px');
  const VIL=[
    {id:'overlord',name:'Overlord',col:'#B3122E',tag:'Evil alien powerhouse',pw:'Laser eyes set towers ablaze · R: thunder clap · Q: sky slam',mode:'fly',spd:[85,150],heat:.16,eye:0xFF2A2A,fire:'LASER',pow:'CLAP',beam:[0xFFF3C4,0xFF2A2A],fig:{suit:0x1D1A2F,trim:0xB3122E,mask:0x111111,cape:0x8B0000,emblemSides:3,hair:0x111111,bulk:1.1}},
    {id:'ruin',name:'Ruin',col:'#2BB673',tag:'Giant green rage brute',pw:'Smash punches · hold Space to leap, climb walls · R: grab & throw cars · Q: earthquake pound · Shift: RAGE',mode:'ground',scale:1.9,eye:0xB6FF4A,fire:'SMASH',pow:'THROW',fig:{suit:0x4CAF50,skin:0x4CAF50,trim:0x6a2c91,mask:0x4CAF50,hair:0x14301a,bulk:1.7,emblemSides:4}},
    {id:'havoc',name:'Havoc',col:'#5A5470',tag:'Mercenary with far too many guns',pw:'Minigun · R: rockets that start fires · Q: airstrike · jetpack flight',mode:'fly',spd:[58,100],heat:.1,eye:0xFFD23F,fire:'SHOOT',pow:'ROCKET',beam:[0xFFF3C4,0xFFB02A],fig:{suit:0x2b2b33,trim:0xe8e8e8,mask:0x111111,helm:0x3a3a44,emblemSides:3,bulk:1.2}},
    {id:'tempest',name:'Tempest',col:'#7FC8F8',tag:'Storm witch',pw:'Chain lightning · R: summon tornadoes that follow your aim · Q: sky slam',mode:'fly',spd:[80,140],heat:.13,eye:0x9FE8FF,fire:'ZAP',pow:'TWISTER',fig:{suit:0x3b2a6b,trim:0x7FC8F8,mask:0x3b2a6b,cape:0x241a47,hair:0xeef0ff,bulk:1}},
    {id:'pyra',name:'Pyra',col:'#FF7A2A',tag:'Queen of fire',pw:'Flamethrower spreads fire · R: meteor strike · Q: sky slam',mode:'fly',spd:[80,145],heat:.12,eye:0xFFB02A,fire:'FLAME',pow:'METEOR',fig:{suit:0x3a0a0a,trim:0xFF7A2A,mask:0x3a0a0a,cape:0xFF3B1F,hair:0xFF5A1F,bulk:1}}];
  let vi=clamp(S.get('hs_villain_pick',0)|0,0,VIL.length-1),VL=VIL[vi],hero=null,sc=1,jetFl=[];
  const HR=new T.Group();HR.rotation.order='YXZ';scene.add(HR);const eyeMat=new T.MeshBasicMaterial({color:0xFF2A2A});
  const add3=(c0,op)=>new T.MeshBasicMaterial({color:c0,transparent:true,opacity:op==null?.85:op,depthWrite:false,blending:T.AdditiveBlending});
  // laser / tracer beam
  const beam=new T.Group();const beamCore=new T.Mesh(new T.CylinderGeometry(.12,.12,1,8,1,true),new T.MeshBasicMaterial({color:0xFFF3C4}));const beamGlow=new T.Mesh(new T.CylinderGeometry(.5,.5,1,10,1,true),add3(0xFF2A2A,.6));beam.add(beamCore,beamGlow);beam.visible=false;scene.add(beam);
  const hitGlow=new T.Mesh(new T.SphereGeometry(1,12,8),add3(0xFF7A2A,.6));hitGlow.visible=false;scene.add(hitGlow);
  function setVillain(i){vi=i;VL=VIL[i];if(hero)HR.remove(hero);hero=K.fig(VL.fig);sc=VL.scale||1;hero.scale.setScalar(sc);hero.position.y=VL.mode==='ground'?0:-1;HR.add(hero);eyeMat.color.setHex(VL.eye);const u=hero.userData;
    [-.1,.1].forEach(x=>{const e=part(T,bx(T,.11,.07,.03),eyeMat,x,.3,.245,u.neck);e.userData.noInk=1});jetFl=[];
    if(VL.id==='havoc'){const gm=TM(0x3a3a44);const gun=part(T,cy(T,.16,.16,1.3,8),gm,0,-.75,.45,u.armR);gun.rotation.x=Math.PI/2;part(T,bx(T,.52,.62,.3),TM(0x5A5470),0,.42,-.34,u.torso);[-.16,.16].forEach(x=>{part(T,cy(T,.09,.12,.3,8),gm,x,.02,-.38,u.torso);const fl=part(T,new T.ConeGeometry(.12,.7,8),add3(0xFFB02A),x,-.4,-.38,u.torso);fl.rotation.x=Math.PI;fl.userData.noInk=1;jetFl.push(fl)})}
    if(VL.id==='tempest'){const o=part(T,sp(T,.2),add3(0x9FE8FF,.9),0,-.8,0,u.armR);o.userData.noInk=1}
    if(VL.id==='pyra'){for(let k=0;k<5;k++){const f=part(T,new T.ConeGeometry(.09,.32,6),add3(k%2?0xFFD23F:0xFF7A2A,.95),-.18+k*.09,.66,0,u.neck);f.userData.noInk=1;jetFl.push(f)}}
    if(VL.id==='ruin')part(T,bx(T,.66*1.7,.3,.4*1.7),TM(0x6a2c91),0,-.12,0,u.hips);
    if(VL.beam){beamCore.material.color.setHex(VL.beam[0]);beamGlow.material.color.setHex(VL.beam[1])}
    root.querySelectorAll('.tctl .tbtn').forEach(b=>{if(b.classList.contains('fire'))b.textContent=VL.fire;else if(b.classList.contains('alt'))b.textContent=VL.mode==='ground'?'RAGE':'BOOST';else if(b.classList.contains('jump'))b.textContent=VL.mode==='ground'?'LEAP':'UP'});
    powB.textContent=VL.pow;slamB.textContent=VL.id==='havoc'?'STRIKE':VL.mode==='ground'?'POUND':'SLAM';turnB.style.display=VL.mode==='ground'?'none':''}
  setVillain(vi);
  const cross=el('div',{style:'position:absolute;left:50%;top:50%;width:22px;height:22px;margin:-11px 0 0 -11px;border:3px solid #FF2A2A;border-radius:50%;box-shadow:0 0 0 2px #1D1A2F;pointer-events:none'});K.hud.append(cross);
  const hpB=H.bar('HEALTH','#2BB673'),htB=H.bar('HEAT','#FF2A2A'),pwB=H.bar('POWER','#B9A7FF'),spB=H.bar('SPEED','#FF9F43');const rad=K.radar(160);const ptr=K.pointer();
  const diff=c.pick(.75,1,1.2);
  const P={prev:new T.Vector3(),p:new T.Vector3(),v:new T.Vector3(),spd:0,hp:100,heat:1,hot:0,inv:0,bank:0,t:0,slam:0,boost:1,cd:0,qcd:0,pcd:0,punchT:0,pa:0,ch:0,jl:false,ground:false,rage:0,rageT:0,held:null,fireT:0,mg:0};
  let mi=0,score=0,objs=[],cars=[],jets=[],shots=[],scorch=[],boss=null,timeLeft=0,target=0,downed=0,collapsed=0,carsN=0,spawnT=0,lzT=0,slamL=false,powL=false,rageL=false;
  let crowd=null,people=[],air=[],paras=[],burning=[],tornados=[],proj=[],timers=[],pplN=0,scared=0,airN=0,fireN=0,airT=0,vehT=0,pplT=0,lastScore=0;
  const add=o=>{scene.add(o);objs.push(o);return o};
  const money=v=>'$'+(v/10).toFixed(1)+'M';
  const V=new T.Vector3(),UP=new T.Vector3(0,1,0);
  function rayBox(o,d,b){let t0=0,t1=1e9;const lo=[b.x0,0,b.z0],hi=[b.x1,b.h,b.z1],oo=[o.x,o.y,o.z],dd=[d.x,d.y,d.z];for(let i=0;i<3;i++){if(Math.abs(dd[i])<1e-6){if(oo[i]<lo[i]||oo[i]>hi[i])return null;continue}let a=(lo[i]-oo[i])/dd[i],b2=(hi[i]-oo[i])/dd[i];if(a>b2){const q=a;a=b2;b2=q}t0=Math.max(t0,a);t1=Math.min(t1,b2);if(t0>t1)return null}return t0}
  function raySph(o,d,p,r){const ox=p.x-o.x,oy=p.y-o.y,oz=p.z-o.z;const t=ox*d.x+oy*d.y+oz*d.z;if(t<0)return null;const d2=ox*ox+oy*oy+oz*oz-t*t;return d2<r*r?t-Math.sqrt(r*r-d2):null}
  function cast(o,d,max){let best=max,hit=null,kind='air';for(const b of city.boxes){if(b.tree||b.dead)continue;const t=rayBox(o,d,b);if(t!=null&&t<best){best=t;hit=b;kind='bld'}}
    if(d.y<-1e-4){const t=-o.y/d.y;if(t>0&&t<best){best=t;hit=null;kind='gnd'}}
    const tg=q=>{const t=raySph(o,d,q.cp||q.p,q.aim||q.r);if(t!=null&&t<best){best=t;hit=q;kind='tg'}};cars.forEach(q=>{if(!q.dead&&!q.held&&!q.thrown)tg(q)});people.forEach(q=>{if(q.st!=='gone')tg(q)});jets.forEach(tg);air.forEach(a=>{if(!a.fall)tg(a)});if(boss&&!boss.dead)tg(boss);
    return{t:best,pt:o.clone().addScaledVector(d,best),hit,kind}}
  const closest=(b,pt)=>new T.Vector3(clamp(pt.x,b.x0,b.x1),clamp(pt.y,.5,b.h-.5),clamp(pt.z,b.z0,b.z1));
  const nearB=(pt,r)=>city.boxes.filter(b=>!b.tree&&!b.dead&&closest(b,pt).distanceTo(pt)<r);
  // ---- traffic ----
  function onStreetX(x){const k=Math.round(x/city.cell)*city.cell;return Math.abs(x-k)<city.st/2-1}
  function placeCar(q,near){for(let k=0;k<20;k++){const p=city.streetPt(P.p.x,P.p.z,near?40:150,near?220:260);if(!p)continue;const alongZ=onStreetX(p.x);q.ax=alongZ?'z':'x';const lane=(Math.random()<.5?-1:1)*3;if(alongZ)p.x=Math.round(p.x/city.cell)*city.cell+lane;else p.z=Math.round(p.z/city.cell)*city.cell+lane;q.p.set(p.x,0,p.z);q.dir=Math.sign(lane);q.m.rotation.set(0,alongZ?(q.dir>0?0:Math.PI):(q.dir>0?Math.PI/2:-Math.PI/2),0);q.dead=false;q.fly=null;q.hits=0;q.m.visible=true;return}}
  function makeCar(k){const big=k%5===0,tanker=k%10===0;const m=toonCar(K,tanker?0xdedede:pick([0x7FC8F8,0xFF8FB1,0x6EE7B7,0xFFD23F,0xB9A7FF,0xffffff,0xFF9F43]),big);if(tanker){const tk=part(T,cy(T,1.05,1.05,3.3,12),TM(0xe8e8ee),0,2.05,-.75,m);tk.rotation.x=Math.PI/2;part(T,cy(T,1.08,1.08,.4,12),TM(0xF2352A),0,2.05,-.75,m).rotation.x=Math.PI/2;K.ink(tk,.05)}scene.add(m);const q={m,p:m.position,r:2.6,sp:10+Math.random()*8,kind:'car',tanker};placeCar(q,true);return q}
  function blowCar(q,from,swirl){if(q.dead||q.held)return;q.dead=true;carsN++;score+=3;const a=Math.atan2(q.p.x-from.x,q.p.z-from.z);q.fly={vy:14+Math.random()*8,vx:Math.sin(a)*10,vz:Math.cos(a)*10,rx:(Math.random()-.5)*8,rz:(Math.random()-.5)*8,l:3};if(swirl){q.fly.vy=26+Math.random()*12;q.fly.vx=Math.cos(a)*16;q.fly.vz=-Math.sin(a)*16}
    K.burst(q.p.clone().setY(1.5),[0xFF9F43,0xF2352A,0xFFD23F,0x1D1A2F],26,14,.8);K.puff(q.p.clone().setY(2),0x3a3552,2.4,1.4);H.pow(pick(['KA-BLAM!','BOOM!','KRUNCH!']),q.p.clone().setY(3));noise(.4,'lowpass',400,.3);
    if(q.tanker){const pt=q.p.clone().setY(1.5);timers.push({t:.18,fn:()=>{H.pow('FUEL TRUCK!',pt.clone().setY(7),'#FFD23F');boom(pt,13,95,true)}})}}
  // ---- people ----
  const pG={leg:bx(T,.62,.85,.36),body:bx(T,.72,.85,.42),head:bx(T,.46,.46,.46),arm:bx(T,.2,.75,.2),hair:bx(T,.5,.14,.5)};pG.arm.translate(0,-.33,0);
  const shirtM=[0xF2352A,0x7FC8F8,0xFFD23F,0x6EE7B7,0xFF8FB1,0xB9A7FF,0xffffff,0xFF9F43].map(v=>TM(v)),pantsM=[0x2d3a5a,0x3a3552,0x5a3a2a,0x1D1A2F].map(v=>TM(v)),skinM=[0xf1c7a0,0xc68a5a,0x8d5a3a,0xffd9b8].map(v=>TM(v)),hairM=[0x1D1A2F,0x6b3f14,0xe8c170,0xa33a1a,0xcccccc].map(v=>TM(v));
  function makePerson(){const g=new T.Group();part(T,pG.leg,pick(pantsM),0,.43,0,g);const sh=pick(shirtM);part(T,pG.body,sh,0,1.28,0,g);part(T,pG.head,pick(skinM),0,1.95,0,g);part(T,pG.hair,pick(hairM),0,2.2,0,g);const aL=part(T,pG.arm,sh,-.47,1.66,0,g),aR=part(T,pG.arm,sh,.47,1.66,0,g);g.scale.setScalar(1.3);scene.add(g);
    const q={g,p:g.position,cp:new T.Vector3(),kind:'person',r:1.2,aim:2,st:'walk',v:new T.Vector3(),aL,aR,sp:1.5,dir:1,ax:'z',t:Math.random()*6,gy:0,spin:0,dn:0};placePerson(q,true);return q}
  function placePerson(q,near){const off=(city.cell-city.blk)/2;for(let k=0;k<12;k++){const p=city.streetPt(P.p.x,P.p.z,near?15:110,near?150:190);if(!p)continue;const alongZ=onStreetX(p.x);const s=Math.random()<.5?-1:1;let x=p.x,z=p.z;if(alongZ)x=Math.round(x/city.cell)*city.cell+s*off;else z=Math.round(z/city.cell)*city.cell+s*off;if(K.inBox(x,.5,z,city.boxes,.4))continue;
      q.p.set(x,0,z);q.gy=0;q.ax=alongZ?'z':'x';q.dir=Math.random()<.5?-1:1;q.st='walk';q.sc=false;q.fl=false;q.g.rotation.set(0,0,0);q.g.visible=true;q.sp=1.3+Math.random()*.9;return}q.g.visible=false;q.st='gone'}
  function scareP(q){if(q.st==='walk')q.st='flee';if(!q.sc&&q.st!=='gone'){q.sc=true;scared++}}
  function fling(q,from,pw,swirl){if(q.st==='gone')return;const d=q.p.clone().sub(from);d.y=0;if(d.lengthSq()<.01)d.set(Math.random()-.5,0,Math.random()-.5);d.normalize();const s=clamp(pw,6,40);if(swirl)q.v.set(-d.z*s,14+s*.5,d.x*s);else q.v.set(d.x*s,9+s*.55,d.z*s);if(q.st!=='fly'){q.p.y+=.3}q.st='fly';q.spin=(Math.random()-.5)*14;scareP(q);q.st='fly';
    if(!q.fl){q.fl=true;pplN++;score+=1}if(Math.random()<.3){H.pow(pick(['AAAH!','EEK!','WAAAH!','HEEELP!','MY HAT!','NOT AGAIN!']),q.p.clone().add(new T.Vector3(0,4,0)),'#fff');beep(700+Math.random()*500,.14,'triangle',.025)}}
  function updPeople(dt){for(const q of people){const g=q.g;q.t+=dt;q.cp.copy(q.p);q.cp.y+=1.4;
      if(q.st==='gone'){if(Math.random()<dt)placePerson(q,false);continue}
      if(q.st==='fly'){q.v.y-=30*dt;q.p.addScaledVector(q.v,dt);g.rotation.x+=q.spin*dt;g.rotation.z+=q.spin*.7*dt;let floor=0;const b=K.inBox(q.p.x,q.p.y+.5,q.p.z,city.boxes,.3);if(b){if(q.p.y>b.h-1.2&&q.v.y<0)floor=b.h;else{K.push(q.p,.3,[b]);q.v.x*=-.4;q.v.z*=-.4}}
        if(q.p.y<=floor){q.p.y=floor;if(q.v.y<-12){q.v.y*=-.3;q.v.x*=.5;q.v.z*=.5}else{q.st='down';q.gy=floor;q.dn=1+Math.random()*1.2;g.rotation.set(-Math.PI/2,g.rotation.y,0);q.p.y=floor+.3;q.v.set(0,0,0)}}
        if(Math.abs(q.p.x-P.p.x)>320||Math.abs(q.p.z-P.p.z)>320)placePerson(q,false);continue}
      if(q.st==='down'){q.dn-=dt;if(q.dn<=0){q.st='flee';g.rotation.set(0,0,0);q.p.y=q.gy}continue}
      const dx=q.p.x-P.p.x,dz=q.p.z-P.p.z,d2=dx*dx+dz*dz;if(d2>270*270){placePerson(q,false);continue}
      if(q.st==='walk'&&d2<34*34&&P.p.y-q.p.y<45)scareP(q);
      const fl=q.st==='flee';if(fl)q.dir=q.ax==='z'?(Math.sign(dz)||1):(Math.sign(dx)||1);const s=fl?7.5:q.sp;const ox=q.p.x,oz=q.p.z;if(q.ax==='z')q.p.z+=q.dir*s*dt;else q.p.x+=q.dir*s*dt;
      if(K.inBox(q.p.x,q.gy+.5,q.p.z,city.boxes,.3)){q.p.x=ox;q.p.z=oz;q.ax=q.ax==='z'?'x':'z'}
      if(q.gy>0&&!K.inBox(q.p.x,q.gy-.3,q.p.z,city.boxes,0)){q.st='fly';q.v.set(0,0,0);q.spin=1.5;q.gy=0;continue}
      g.rotation.y=q.ax==='z'?(q.dir>0?0:Math.PI):(q.dir>0?Math.PI/2:-Math.PI/2);const ph=q.t*s*2.2;q.p.y=q.gy+Math.abs(Math.sin(ph))*(fl?.25:.08);
      if(fl){q.aL.rotation.x=-2.7+Math.sin(q.t*18)*.35;q.aR.rotation.x=-2.7+Math.cos(q.t*18)*.35;if(Math.random()<dt*.2&&d2<50*50)beep(800+Math.random()*500,.12,'triangle',.018)}else{q.aL.rotation.x=Math.sin(ph)*.6;q.aR.rotation.x=-Math.sin(ph)*.6}}}
  // ---- aircraft ----
  function makeAir(type){const g=add(new T.Group());g.rotation.order='YXZ';let a;
    if(type==='plane'){const W=TM(0xf4f4f8),S2=TM(pick([0xF2352A,0x2d6fd6,0x2BB673,0xFF9F43,0xB9A7FF]));part(T,cy(T,1.6,1.6,17,12),W,0,0,0,g).rotation.x=Math.PI/2;part(T,sp(T,1.6),W,0,0,8.5,g);const tl=part(T,new T.ConeGeometry(1.6,4,12),W,0,.3,-10.4,g);tl.rotation.x=-Math.PI/2;part(T,bx(T,23,.35,3.2),W,0,-.4,.5,g);part(T,bx(T,.3,3.4,2.6),S2,0,2.2,-10,g);part(T,bx(T,7,.25,2),W,0,.4,-10.4,g);[-1,1].forEach(s=>{part(T,bx(T,.2,.55,15),S2,s*1.58,0,0,g);part(T,cy(T,.7,.7,2.6,10),S2,s*5.5,-1.1,1.3,g).rotation.x=Math.PI/2});part(T,bx(T,2.4,.6,1.2),TM(0x1D1A2F),0,.9,8.2,g);
      const h=Math.random()*6.283,off=(Math.random()-.5)*160;const dir=new T.Vector3(Math.sin(h),0,Math.cos(h)),pp=new T.Vector3(-dir.z,0,dir.x);g.position.set(P.p.x,138+Math.random()*30,P.p.z).addScaledVector(dir,-380).addScaledVector(pp,off);a={v:dir.multiplyScalar(48),hp:1,aim:9,r:9,pts:40,br:18,bp:150}}
    else if(type==='heli'){const cop=mi===2&&Math.random()<.6;const B=TM(cop?0x2d3a5a:pick([0xFFD23F,0xF2352A,0xffffff])),D=TM(0x1D1A2F);const bd=part(T,sp(T,1),B,0,0,0,g);bd.scale.set(1.8,1.6,2.6);part(T,bx(T,.45,.45,5.5),B,0,.3,-4.2,g);part(T,bx(T,.15,1.6,.8),B,0,.9,-6.8,g);const gl=part(T,sp(T,1),TM(0x9fd6ff),0,.3,1.4,g);gl.scale.set(1.2,1,1.2);[-1,1].forEach(s=>part(T,bx(T,.15,.15,3.6),D,s*1.1,-1.8,0,g));part(T,cy(T,.12,.12,.8,6),D,0,1.9,0,g);const rot=part(T,bx(T,11,.1,.55),D,0,2.3,0,g);part(T,bx(T,.55,.1,11),D,0,0,0,rot);
      a={rot,cop,hp:c.pick(.6,.8,1),aim:6,r:6,pts:20,br:11,bp:100,ang:Math.random()*6.283,cd:3+Math.random()*2,v:new T.Vector3()};const r0=150;g.position.set(P.p.x+Math.cos(a.ang)*r0,55,P.p.z+Math.sin(a.ang)*r0)}
    else{const bl=part(T,sp(T,1),TM(0xcfd3e0),0,0,0,g);bl.scale.set(7,7,22);part(T,bx(T,.3,6,5),TM(0xF2352A),0,5,-18,g);part(T,bx(T,12,.3,5),TM(0xF2352A),0,0,-18,g);part(T,bx(T,2.4,1.6,5),TM(0x5A5470),0,-7.6,2,g);const bn=part(T,cy(T,7.08,7.08,4,20,1,true),TM(0xFF9F43),0,0,2,g);bn.rotation.x=Math.PI/2;
      const h=Math.random()*6.283;const dir=new T.Vector3(Math.sin(h),0,Math.cos(h));g.position.set(P.p.x,112,P.p.z).addScaledVector(dir,-300);a={v:dir.multiplyScalar(10),hp:c.pick(1.8,2.4,3),aim:10,r:12,pts:60,br:20,bp:150}}
    K.ink(g,.06);Object.assign(a,{type,g,p:g.position,kind:'air',fall:false,flash:0});if(a.v.lengthSq())g.rotation.y=Math.atan2(a.v.x,a.v.z);air.push(a);return a}
  function hitAir(a,d){if(a.fall)return;a.hp-=d;a.flash=.15;if(a.hp<=0)downAir(a)}
  function downAir(a){a.fall=true;airN++;score+=a.pts;H.pow(pick(['KA-BLOOEY!','KRAKOOM!','SPLOOSH!']),a.p.clone().add(new T.Vector3(0,5,0)),'#FFD23F');K.burst(a.p.clone(),[0xFF9F43,0xF2352A,0xFFD23F,0x1D1A2F],40,18,1.1);noise(.8,'lowpass',300,.4);
    for(let k=0;k<(a.type==='heli'?1:2);k++)makePara(a.p.clone().add(new T.Vector3((Math.random()-.5)*6,-2,(Math.random()-.5)*6)));if(a.type==='heli')a.v.set(0,0,0)}
  const paraG=new T.SphereGeometry(2.2,12,6,0,Math.PI*2,0,Math.PI/2);
  function makePara(p){const g=add(new T.Group());part(T,paraG,TM(pick([0xFF9F43,0xFFD23F,0xF2352A,0xffffff])),0,5,0,g);part(T,bx(T,.7,1.1,.4),TM(0x2d6fd6),0,1,0,g);part(T,bx(T,.45,.45,.45),TM(0xf1c7a0),0,1.8,0,g);g.position.copy(p);K.ink(g,.05);paras.push({g,p:g.position,t:Math.random()*6})}
  function updAir(dt,play){if(play){airT-=dt;if(airT<=0){airT=mi===2?2.5:7;const cnt=t=>air.filter(a=>a.type===t&&!a.fall).length;if(cnt('plane')<(mi===2||mi<0?3:mi===4?0:2))makeAir('plane');else if(cnt('heli')<(mi===2?3:mi<0?2:mi===4?0:1))makeAir('heli');else if(mi!==3&&mi!==4&&cnt('blimp')<1)makeAir('blimp')}}
    air=air.filter(a=>{const g=a.g;a.flash-=dt;
      if(!a.fall){if(a.type==='heli'){a.ang+=dt*.22;const goal=new T.Vector3(P.p.x+Math.cos(a.ang)*62,Math.max(38,P.p.y+18),P.p.z+Math.sin(a.ang)*62);const dv=goal.sub(a.p);const L=dv.length();a.v.lerp(dv.multiplyScalar(L>1?Math.min(90,L*.8)/L:0),Math.min(1,dt*1.5));a.p.addScaledVector(a.v,dt);g.rotation.y=Math.atan2(P.p.x-a.p.x,P.p.z-a.p.z);g.rotation.x=clamp(a.v.length()*.004,0,.3);a.rot.rotation.y+=dt*25;
          if(a.cop&&play){a.cd-=dt;if(a.cd<=0&&a.p.distanceTo(P.p)<120){a.cd=c.pick(4,3,2.3)+Math.random();shoot(a.p.clone(),0x7FC8F8,50*diff,6)}}}
        else{a.p.addScaledVector(a.v,dt);const dx=a.p.x-P.p.x,dz=a.p.z-P.p.z;if(dx*dx+dz*dz>470*470&&dx*a.v.x+dz*a.v.z>0){scene.remove(g);return false}}
        g.visible=!(a.flash>0&&Math.sin(P.t*60)>0);return true}
      g.visible=true;if(a.type==='plane'){a.v.x*=Math.pow(.35,dt);a.v.z*=Math.pow(.35,dt);a.v.y=Math.max(a.v.y-16*dt,-60);g.rotation.x=Math.min(1.1,g.rotation.x+dt*.6);g.rotation.z+=dt*1.8}else if(a.type==='heli'){a.v.y=Math.max(a.v.y-18*dt,-40);g.rotation.y+=dt*9;a.rot.rotation.y+=dt*10}else{a.v.set(a.v.x*.99,-8,a.v.z*.99);g.rotation.x=Math.min(.5,g.rotation.x+dt*.12)}
      a.p.addScaledVector(a.v,dt);if(Math.random()<dt*14)K.puff(a.p.clone(),0x3a3552,2+a.r*.2,1.6);if(Math.random()<dt*10)K.burst(a.p.clone(),[0xFF9F43,0xFFD23F],4,6,.6);
      const b=K.inBox(a.p.x,a.p.y-1,a.p.z,city.boxes,1);if(a.p.y<=1.5||b){const pt=a.p.clone();pt.y=Math.max(1,pt.y);scene.remove(g);boom(pt,a.br,a.bp,true);return false}return true});
    paras=paras.filter(q=>{q.t+=dt;q.p.y-=4*dt;q.p.x+=Math.sin(q.t)*2*dt;q.g.rotation.z=Math.sin(q.t*1.3)*.15;const b=K.inBox(q.p.x,q.p.y,q.p.z,city.boxes,0);if(q.p.y<=0||b){K.puff(q.p.clone(),0xd8d4e4,1.5,.8);scene.remove(q.g);return false}return true})}
  // ---- fire (new destruction type: buildings burn, spread and collapse) ----
  const flameG=new T.ConeGeometry(1,2.6,6);flameG.translate(0,1.3,0);const flameM=[0xFFE27A,0xFF8A1F,0xE8321E].map((c0,k)=>new T.MeshBasicMaterial({color:c0,transparent:true,opacity:[.95,.9,.8][k],depthWrite:false}));
  function facePt(b){const s=Math.random()*4|0,y=Math.random()*b.h*.9;return s===0?new T.Vector3(b.x0,y,b.z0+Math.random()*(b.z1-b.z0)):s===1?new T.Vector3(b.x1,y,b.z0+Math.random()*(b.z1-b.z0)):s===2?new T.Vector3(b.x0+Math.random()*(b.x1-b.x0),y,b.z0):new T.Vector3(b.x0+Math.random()*(b.x1-b.x0),y,b.z1)}
  function addFlame(b,pt){const m=new T.Mesh(flameG,flameM[b.fire.fl.length%3]);m.position.copy(pt);const s=Math.min(4.5,1.4+Math.max(b.w,b.d)*.09)*(.7+Math.random()*.5);m.scale.setScalar(s);m.userData.s=s;scene.add(m);b.fire.fl.push(m)}
  function ignite(b,pt){if(!b||b.dead||b.tree||b.fire)return false;if(burning.length>=14)douse(burning.shift());if(b.hp==null)b.hp=Math.max(40,b.w*b.d*b.h/260);b.fire={t:0,sp:0,grow:0,fl:[],rate:b.hp/c.pick(30,24,20)};addFlame(b,pt||facePt(b));for(let k=0;k<3;k++)addFlame(b,k===0?new T.Vector3(b.x0+Math.random()*(b.x1-b.x0),b.h+.5,b.z0+Math.random()*(b.z1-b.z0)):facePt(b));burning.push(b);fireN++;score+=2;return true}
  function douse(b){if(!b.fire)return;b.fire.fl.forEach(m=>scene.remove(m));b.fire=null}
  function tickFire(dt){burning=burning.filter(b=>{const f=b.fire;if(!f)return false;if(b.dead||city.boxes.indexOf(b)<0){douse(b);return false}f.t+=dt;f.sp+=dt;f.grow+=dt;
      f.fl.forEach(m=>{const s=m.userData.s;m.scale.set(s*(.85+Math.random()*.3),s*(.75+Math.random()*.6),s*(.85+Math.random()*.3))});if(Math.random()<dt*3)K.puff(new T.Vector3(b.x0+Math.random()*(b.x1-b.x0),b.h+2,b.z0+Math.random()*(b.z1-b.z0)),0x3a3552,3+Math.random()*2,2.4,new T.Vector3(0,5,0));
      if(f.grow>2.5&&f.fl.length<9){f.grow=0;addFlame(b,facePt(b))}score+=dt*.8;b.hp-=f.rate*dt;
      if(f.sp>3){f.sp=0;if(Math.random()<.45){const nb=nearB(new T.Vector3(b.cx,b.h*.5,b.cz),Math.max(b.w,b.d)*.5+9).filter(o=>o!==b&&!o.fire);if(nb.length)ignite(pick(nb))}}
      if(b.hp<=0){douse(b);wreck(b,facePt(b),1);return false}return true})}
  // ---- fx pools: flames, lightning ----
  const flP=[],flG=new T.IcosahedronGeometry(1,0),sprM=[add3(0xFFE27A,.55),add3(0xFF8A1F,.45),add3(0xE8321E,.3)];
  function spray(from,dir,len){for(let k=0;k<2;k++){let q=flP.find(z=>z.l<=0);if(!q){if(flP.length>=90)return;q={m:new T.Mesh(flG,sprM[0]),v:new T.Vector3(),l:0,l0:.45};scene.add(q.m);flP.push(q)}q.m.visible=true;q.m.position.copy(from).addScaledVector(dir,2.5+Math.random()*1.5);q.l=q.l0=.35+Math.random()*.15;q.v.copy(dir).multiplyScalar(len/q.l0*(.85+Math.random()*.3)).add(new T.Vector3((Math.random()-.5)*7,(Math.random()-.5)*7+2,(Math.random()-.5)*7))}}
  const boltG=new T.CylinderGeometry(.2,.2,1,5,1,true);boltG.translate(0,.5,0);const boltM=add3(0xDFF6FF,.95),bolts=[];
  function seg(a,b){let q=bolts.find(z=>z.l<=0);if(!q){q={m:new T.Mesh(boltG,boltM),l:0};scene.add(q.m);bolts.push(q)}const d=b.clone().sub(a);q.m.visible=true;q.m.position.copy(a);q.m.quaternion.setFromUnitVectors(UP,d.clone().normalize());const w=.7+Math.random()*.8;q.m.scale.set(w,d.length(),w);q.l=.13}
  function bolt(a,b){const n=9,L=a.distanceTo(b);let pv=a.clone();for(let i=1;i<=n;i++){const pt=a.clone().lerp(b,i/n);if(i<n)pt.add(new T.Vector3(Math.random()-.5,Math.random()-.5,Math.random()-.5).multiplyScalar(Math.min(8,L*.08)));seg(pv,pt);pv=pt}}
  function tickFx(dt){for(const q of flP){if(q.l<=0)continue;q.l-=dt;if(q.l<=0){q.m.visible=false;continue}const a=1-q.l/q.l0;q.m.position.addScaledVector(q.v,dt);q.m.scale.setScalar(.2+a*a*2.6);q.m.material=sprM[a<.3?0:a<.7?1:2]}
    for(const q of bolts){if(q.l<=0)continue;q.l-=dt;if(q.l<=0)q.m.visible=false}
    timers=timers.filter(t=>{t.t-=dt;if(t.t<=0){t.fn();return false}return true})}
  // ---- tornadoes ----
  const tornM=new T.MeshBasicMaterial({color:0x8c8fa8,transparent:true,opacity:.5,depthWrite:false,side:T.DoubleSide});const tornG=[];for(let k=0;k<8;k++)tornG.push(new T.CylinderGeometry(2.4+(k+1)*1.7,2.4+k*1.7,9,14,1,true));
  let tAim=new T.Vector3();
  function makeTornado(pt){if(tornados.length>=2){const o=tornados.shift();scene.remove(o.g)}const g=new T.Group();const parts=tornG.map((geo,k)=>{const m=new T.Mesh(geo,tornM);m.position.y=k*9+4.5;g.add(m);return m});g.position.set(pt.x,0,pt.z);scene.add(g);tornados.push({g,parts,p:g.position,l:16,t:0,tk:0});H.pow('TWISTER!',pt.clone().setY(12),'#9FE8FF');noise(1.5,'bandpass',300,.4)}
  function tickTornado(dt){tornados=tornados.filter(o=>{o.l-=dt;o.t+=dt;o.tk-=dt;o.parts.forEach((m,k)=>{m.rotation.y+=dt*(5+k*.5);m.position.x=Math.sin(o.t*2+k*.7)*k*.5;m.position.z=Math.cos(o.t*1.7+k*.7)*k*.5});o.g.scale.setScalar(clamp(Math.min(o.t*2,o.l),0,1));
      const to=tAim.clone().sub(o.p);to.y=0;const L=to.length();if(L>3)o.p.addScaledVector(to,Math.min(L,18*dt)/L);o.p.x+=Math.sin(o.t*1.3)*dt*4;
      const R=16;if(crowd&&Math.random()<.2)crowd.blast(o.p,R,1);cars.forEach(q=>{if(!q.dead&&!q.held&&!q.thrown&&Math.hypot(q.p.x-o.p.x,q.p.z-o.p.z)<R)blowCar(q,o.p,true)});people.forEach(q=>{if((q.st==='walk'||q.st==='flee'||q.st==='down')&&Math.hypot(q.p.x-o.p.x,q.p.z-o.p.z)<R+2)fling(q,o.p,22,true)});
      if(Math.random()<dt*12)K.burst(o.p.clone().add(new T.Vector3((Math.random()-.5)*10,Math.random()*50,(Math.random()-.5)*10)),[0x8c86a3,0x5A5470,0xd8d4e4],3,10,.8);
      if(o.tk<=0){o.tk=.35;nearB(o.p.clone().setY(8),10).forEach(b=>{const cp=closest(b,new T.Vector3(o.p.x,5+Math.random()*Math.min(60,b.h),o.p.z));wreck(b,cp,c.pick(42,36,32))});jets.forEach(j=>{if(!j.dead&&Math.hypot(j.p.x-o.p.x,j.p.z-o.p.z)<22&&j.p.y<75)j.hp-=.35});air.forEach(a=>{if(Math.hypot(a.p.x-o.p.x,a.p.z-o.p.z)<24&&a.p.y<80)hitAir(a,.3)});if(boss&&Math.hypot(boss.p.x-o.p.x,boss.p.z-o.p.z)<20&&boss.p.y<75){boss.hp-=1.6;boss.flash=.2}if(Math.random()<.3)noise(.5,'bandpass',250,.12)}
      if(o.l<=0){scene.remove(o.g);return false}return true})}
  // ---- projectiles (rockets, thrown cars, boulders, meteors) ----
  function homing(pos,dir){let best=null,bd=.93;const tt=[...jets.filter(j=>!j.dead),...air.filter(a=>!a.fall)];if(boss&&!boss.dead)tt.push(boss);tt.forEach(t=>{const d=t.p.clone().sub(pos);const L=d.length();if(L>260)return;const dt2=d.normalize().dot(dir);if(dt2>bd){bd=dt2;best=t}});return best}
  function tickProj(dt){proj=proj.filter(q=>{q.l-=dt;const m=q.m;if(q.home&&!(q.home.dead||q.home.fall)){const want=q.home.p.clone().sub(m.position).normalize().multiplyScalar(q.v.length());q.v.lerp(want,Math.min(1,dt*3))}q.v.y-=q.grav*dt;m.position.addScaledVector(q.v,dt);
      if(q.kind==='car'||q.kind==='rock'){m.rotation.x+=dt*5;m.rotation.z+=dt*3}else m.quaternion.setFromUnitVectors(new T.Vector3(0,0,1),q.v.clone().normalize());
      if(q.kind==='rocket'&&Math.random()<dt*40)K.puff(m.position.clone(),0xd8d4e4,.9,.8);if(q.kind==='meteor'&&Math.random()<dt*40){K.puff(m.position.clone(),0x3a3552,3,1.4);K.burst(m.position.clone(),[0xFF9F43,0xFFD23F],3,6,1)}
      let hit=m.position.y<=(q.floor||.3)||q.l<=0||!!K.inBox(m.position.x,m.position.y,m.position.z,city.boxes,.3);
      if(!hit){const t2=[...jets.filter(j=>!j.dead),...air.filter(a=>!a.fall),...cars.filter(c2=>!c2.dead&&!c2.held&&!c2.thrown&&c2!==q.car)];if(boss&&!boss.dead)t2.push(boss);for(const t of t2)if(t.p.distanceTo(m.position)<(t.aim||t.r||3)*.7+1.5){hit=true;break}}
      if(!hit)return true;const pt=m.position.clone();pt.y=Math.max(.5,pt.y);
      if(q.car){q.car.thrown=false;q.car.dead=false;blowCar(q.car,pt)}else scene.remove(m);if(q.mark)scene.remove(q.mark);
      boom(pt,q.r,q.pw,q.ign);if(q.kind==='meteor'){for(let k=0;k<3;k++)scorchAt(pt.clone().add(new T.Vector3((Math.random()-.5)*10,0,(Math.random()-.5)*10)),3);K.ring(pt.clone().setY(.5),0xFF7A2A,3,60,1.2);cam.shake=Math.max(cam.shake,1.8)}return false})}
  // ---- jets ----
  function makeJet(){const g=add(new T.Group());part(T,bx(T,1.4,.9,4.2),TM(0x2d6fd6),0,0,0,g);part(T,bx(T,6,.18,1.6),TM(0xffffff),0,0,-.3,g);part(T,bx(T,.2,1.4,1.2),TM(0xFFD23F),0,.8,-1.6,g);part(T,bx(T,.9,.5,1.2),TM(0x9fd6ff),0,.55,.9,g);const fl=part(T,sp(T,.45),new T.MeshBasicMaterial({color:0x7FC8F8}),0,0,-2.3,g);K.ink(g,.05);
    const a=Math.random()*6.28,r=90+Math.random()*50;g.position.set(P.p.x+Math.cos(a)*r,40+Math.random()*50,P.p.z+Math.sin(a)*r);const j={g,p:g.position,r:3.2,aim:c.pick(8,6.5,5),hp:c.pick(.5,.7,.9),v:new T.Vector3(),cd:2+Math.random()*2,off:Math.random()*6.28,fl,kind:'jet'};jets.push(j);return j}
  function killJet(j,how){j.dead=true;downed++;score+=15;K.burst(j.p.clone(),[0x2d6fd6,0xFFD23F,0xffffff,0xFF9F43],40,20,1);K.ring(j.p.clone(),0xFFD23F,1,14,.5);H.pow(how||'KA-POW!',j.p.clone().add(new T.Vector3(0,3,0)),'#FFD23F');noise(.6,'lowpass',500,.35);scene.remove(j.g)}
  function shoot(from,col,spd,dmg){const m=add(part(T,sp(T,.55),new T.MeshBasicMaterial({color:col}),from.x,from.y,from.z));const lead=P.v.clone().multiplyScalar(.5);const d=P.p.clone().add(lead).add(new T.Vector3(0,VL.mode==='ground'?2*sc:0,0)).sub(from).normalize();shots.push({m,v:d.multiplyScalar(spd),l:5,dmg})}
  // ---- boss ----
  function makeBoss(){const f=K.fig({suit:0x2d6fd6,trim:0xFFD23F,mask:0x2d6fd6,cape:0xFFD23F,emblemSides:5,hair:0x6b3f14,bulk:1.1});f.scale.setScalar(1.6);const g=add(new T.Group());g.add(f);f.position.y=-1.6;g.position.set(P.p.x,90,P.p.z-160);return{g,f,p:g.position,r:3.4,aim:c.pick(7,6,5),hp:100,st:'circle',t:4,a:0,v:new T.Vector3(),cd:2,flash:0,kind:'boss'}}
  function hurt(d,why){if(P.inv>0||F.state!=='play')return;P.hp-=d*c.pick(.55,.85,1.15)*(P.rageT>0?.5:1);P.inv=.6;cam.shake=.8;H.tint('rgba(127,200,248,.45)',1);beep(160,.2,'sawtooth',.08);if(why)H.say(why,1100);if(P.hp<=0){P.hp=0;F.lose(M,'Defeated!','The heroes haul you off to Metro Max, a prison with surprisingly nice pillows. Try again?')}}
  F.revive=()=>{P.hp=100;P.inv=2};
  function releaseHeld(){if(!P.held)return;if(P.held.car){P.held.car.held=false;placeCar(P.held.car,false)}else scene.remove(P.held.m);P.held=null}
  function clearAll(){releaseHeld();objs.forEach(o=>scene.remove(o));objs=[];jets=[];shots=[];air=[];paras=[];boss=null;scorch.forEach(s=>scene.remove(s));scorch=[];H.boss(null);burning.slice().forEach(douse);burning=[];tornados.forEach(o=>scene.remove(o.g));tornados=[];proj.forEach(q=>{if(q.car){q.car.thrown=false;placeCar(q.car,false)}else scene.remove(q.m);if(q.mark)scene.remove(q.mark)});proj=[];timers=[]}
  function start(i){mi=i;clearAll();const gr=VL.mode==='ground';P.p.set(0,gr?0:50,40);P.v.set(0,0,gr?0:-10);P.spd=gr?0:10;P.hp=100;P.heat=1;P.hot=0;P.inv=1.5;P.boost=1;P.slam=0;P.cd=0;P.qcd=0;P.rage=0;P.rageT=0;P.ch=0;P.ground=gr;cam.yaw=0;cam.pitch=gr?-.05:-.15;
    score=0;lastScore=0;downed=0;collapsed=0;carsN=0;pplN=0;scared=0;airN=0;fireN=0;spawnT=2;airT=1;city.update(0,0,true);
    if(!cars.length)for(let k=0;k<40;k++)cars.push(makeCar(k));else cars.forEach(q=>{q.held=false;q.thrown=false;placeCar(q,true)});
    if(!people.length)for(let k=0;k<56;k++)people.push(makePerson());else people.forEach(q=>placePerson(q,true));
    if(!crowd)crowd=K.crowd({people:1120,cars:800,snap:v=>Math.round(v/city.cell)*city.cell,walkOff:(city.cell-city.blk)/2,lane:3,radius:270,center:()=>P.p,slowBlocked:(x,z)=>K.inBox(x,.5,z,city.boxes,.4),onPerson:()=>{pplN++;score+=1},onCar:()=>{carsN++;score+=3}});crowd.reset();
    timeLeft=i===0?c.pick(170,150,130):i===1?c.pick(180,160,140):0;target=c.pick(120,200,280);vehT=c.pick(15,22,28);pplT=c.pick(20,30,40);
    if(i===2)for(let k=0;k<3;k++)makeAir(k===2?'heli':'plane');
    if(i===4){boss=makeBoss();H.say('Captain Valor has arrived!',1800)}else if(i>=0)H.say(M[i].name,1800);else H.say(VL.name+' is loose in Metro City',1800)}
  function onCollapse(b){collapsed++;score+=Math.max(8,Math.round(b.w*b.d*b.h/1500));K.ring(new T.Vector3(b.cx,.5,b.cz),0xFF9F43,4,40,1);douse(b)}
  function wreck(b,pt,pw){const r=K.smash(b,pt,pw,{onCollapse});if(r){score+=1}return r}
  function scorchAt(pt,s){const m=new T.Mesh(new T.CircleGeometry((.9+Math.random()*.8)*(s||1),9),new T.MeshBasicMaterial({color:0x1D1A2F,transparent:true,opacity:.7,depthWrite:false}));m.rotation.x=-Math.PI/2;m.position.set(pt.x,.06+Math.random()*.02,pt.z);scene.add(m);scorch.push(m);if(scorch.length>90)scene.remove(scorch.shift())}
  function boom(pt,r,pw,ign){K.burst(pt.clone(),[0xFF9F43,0xF2352A,0xFFD23F,0x1D1A2F],Math.min(60,20+r*2),r*1.3,1+r*.05);K.ring(pt.clone().setY(Math.max(.4,pt.y)),0xFF9F43,1,r*2,.7);K.puff(pt.clone(),0x3a3552,r*.4,1.6);H.pow(pick(['KA-BOOM!','BLAM!','KRA-KOOM!','WHOOMP!']),pt.clone().add(new T.Vector3(0,3,0)),'#FF9F43');noise(.9,'lowpass',200+Math.random()*100,.45);cam.shake=Math.max(cam.shake,clamp(1.5-pt.distanceTo(P.p)/80,0,1.5));if(pt.y<2)scorchAt(pt,r*.3);
    nearB(pt,r).forEach(b=>{const cp=closest(b,pt);wreck(b,cp,pw*(1-.6*cp.distanceTo(pt)/r));if(ign&&Math.random()<.6)ignite(b,cp)});
    if(crowd)crowd.blast(pt,r,1.2);cars.forEach(q=>{if(!q.dead&&!q.fly&&!q.held&&!q.thrown&&q.p.distanceTo(pt)<r*1.4)blowCar(q,pt)});people.forEach(q=>{const d=q.p.distanceTo(pt);if(d<r*1.6)fling(q,pt,pw*.25*(1-d/(r*1.6))+10);else if(d<r*4)scareP(q)});
    jets.forEach(j=>{if(!j.dead&&j.p.distanceTo(pt)<r+3)j.hp-=pw/60});air.forEach(a=>{if(!a.fall&&a.p.distanceTo(pt)<r+a.aim)hitAir(a,pw/60)});if(boss&&boss.p.distanceTo(pt)<r+3){boss.hp-=pw/16;boss.flash=.3}}
  function slamWave(big){const pt=P.p.clone().setY(.3);const R=big?1.25:1;K.ring(pt,0xFF9F43,2,46*R,.9,1);K.ring(pt,0xffffff,1,30*R,.6,.5);K.burst(pt,[0xd8d4e4,0x8c86a3,0xFF9F43],50,24,1.2);H.pow('KA-THOOOM!',pt.clone().setY(5),'#FF9F43');noise(1.4,'lowpass',120,.55);cam.shake=1.6;score+=4;
    nearB(new T.Vector3(P.p.x,3,P.p.z),22*R).forEach(b=>wreck(b,closest(b,new T.Vector3(P.p.x,3,P.p.z)),120*R));
    if(crowd)crowd.blast(pt,30*R,1.4);cars.forEach(q=>{if(!q.dead&&!q.held&&q.p.distanceTo(pt)<34*R)blowCar(q,pt)});people.forEach(q=>{const d=q.p.distanceTo(pt);if(d<40*R)fling(q,pt,30-d*.5);else if(d<90)scareP(q)});jets.forEach(j=>{if(!j.dead&&j.p.distanceTo(P.p)<30)j.hp=0});if(boss&&boss.p.distanceTo(P.p)<22){boss.hp-=10;boss.flash=.3}}
  // earthquake crack line (Ruin's pound)
  const crackM=new T.MeshBasicMaterial({color:0x1D1A2F,transparent:true,opacity:.85,depthWrite:false});
  function quake(pt,fw){H.pow('EARTHQUAKE!',pt.clone().setY(8),'#FFD23F');for(let s=-1;s<=1;s+=2)for(let k=1;k<=7;k++){const q=pt.clone().addScaledVector(fw,s*k*7);timers.push({t:k*.08,fn:()=>{const m=new T.Mesh(new T.PlaneGeometry(2.2+Math.random(),8),crackM);m.rotation.set(-Math.PI/2,0,Math.atan2(fw.x,fw.z)+(Math.random()-.5)*.6);m.position.set(q.x,.07,q.z);scene.add(m);scorch.push(m);if(scorch.length>90)scene.remove(scorch.shift());
      K.burst(q.clone().setY(.5),[0x8c86a3,0x5A5470,0xd8d4e4],10,12,1);noise(.3,'lowpass',90,.3);nearB(q.clone().setY(2),7).forEach(b=>wreck(b,closest(b,q.clone().setY(2)),85));if(crowd)crowd.blast(q,6,1);cars.forEach(c2=>{if(!c2.dead&&!c2.held&&c2.p.distanceTo(q)<7)blowCar(c2,q)});people.forEach(p2=>{if(p2.p.distanceTo(q)<9)fling(p2,q,18)})}})}cam.shake=2}
  function hitT(q,pt,p){if(q.kind==='car'){if(p>=.6)blowCar(q,pt);else{q.hits=(q.hits||0)+p;if(q.hits>=1)blowCar(q,pt)}}else if(q.kind==='person')fling(q,pt,8+p*6);else if(q.kind==='jet'){q.hp-=.3*p;if(q.hp<=0&&!q.dead)killJet(q,pick(['ZZZAP!','KA-POW!']))}else if(q.kind==='air')hitAir(q,.26*p);else if(q.kind==='boss'){q.hp-=c.pick(4.4,3.6,2.9)*p;q.flash=.12;score+=1}}
  // ---- villain pick ----
  let chosen=false;const oBrief=F.brief,oRoam=F.roamMenu,oIntro=F.intro;
  F.intro=(...a)=>{chosen=false;return oIntro(...a)};F.brief=M2=>chosen?oBrief(M2):pickV(()=>oBrief(M2));F.roamMenu=()=>pickV(()=>oRoam());
  function pickV(next){F.state='menu';const html='<small class="kick">Choose your villain</small><h2>Who are you today?</h2><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:8px;margin:10px 0">'+VIL.map((v,i)=>'<button type="button" data-v="'+i+'" style="text-align:left;cursor:pointer;font:inherit;color:#1D1A2F;background:'+(i===vi?'#fff3c4':'#fff')+';border:3px solid #1D1A2F;border-left:12px solid '+v.col+';border-radius:6px;padding:8px 10px;line-height:1.3"><b style="font-size:1.1em">'+v.name+'</b><br><small><i>'+v.tag+'</i></small><br><small>'+v.pw+'</small></button>').join('')+'</div>';
    const o=F.ov(html,[['Back',()=>F.intro(...F._intro)]]);o.querySelectorAll('[data-v]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();const i=+b.dataset.v;S.set('hs_villain_pick',i);if(i!==vi||!hero)setVillain(i);chosen=true;o.remove();K.wrap.classList.remove('paused');try{unlockAudio()}catch(er){}next()}))}
  let lzL=false;/*DBGV*/
  st3.onFrame((dt,now)=>{K.fxTick(dt);H.tick(dt);const play=F.state==='play'&&!F.paused();const I=input,Kk=I.keys;P.t+=dt;const gr=VL.mode==='ground';
    // traffic
    if(crowd)crowd.update(dt);
    cars.forEach(q=>{if(q.held||q.thrown)return;if(q.fly){const f=q.fly;f.vy-=30*dt;q.p.x+=f.vx*dt;q.p.y+=f.vy*dt;q.p.z+=f.vz*dt;q.m.rotation.x+=f.rx*dt;q.m.rotation.z+=f.rz*dt;if(q.p.y<0){q.p.y=0;f.vy*=-.3;f.vx*=.5;f.vz*=.5;f.rx*=.4;f.rz*=.4}f.l-=dt;if(Math.random()<dt*6)K.puff(q.p.clone().setY(1.5),0x3a3552,1.2,1);if(f.l<=0){q.fly=null;placeCar(q,false)}return}
      if(q.dead){placeCar(q,false);return}if(q.ax==='z')q.p.z+=q.dir*q.sp*dt;else q.p.x+=q.dir*q.sp*dt;if(Math.abs(q.p.x-P.p.x)>300||Math.abs(q.p.z-P.p.z)>300||K.inBox(q.p.x,.5,q.p.z,city.boxes,1))placeCar(q,false)});
    updPeople(dt);updAir(dt,play);tickFire(dt);tickFx(dt);tickTornado(dt);tickProj(dt);jetFl.forEach(f=>f.scale.set(1,.7+Math.random()*.6,1));
    if(!play){beam.visible=false;hitGlow.visible=false;ptr(null);cross.style.display='none';cam.yaw+=dt*.1;if(gr){K.pose(hero,'run',0,0);HR.position.copy(P.p)}else{K.pose(hero,'hover',P.t*2);HR.position.copy(P.p)}K.capeAnim(hero,.2,now/1000,5);HR.rotation.set(gr?0:.1,cam.yaw+Math.PI,0);cam.place(P.p.clone().add(new T.Vector3(0,gr?3*sc/1.9:0,0)),dt,gr?11:9,1.6,0);H.lines(0);return}
    cross.style.display='';cam.look(1.1);P.inv-=dt;P.cd-=dt;P.qcd-=dt;P.pcd-=dt;P.punchT-=dt;
    const dir=cam.dir3();const f=(Kk.w||Kk.arrowup?1:0)-(Kk.s||Kk.arrowdown?1:0)-(I.joy.y<-.2?-1:I.joy.y>.2?1:0);const strafe=(Kk.d||Kk.arrowright?1:0)-(Kk.a||Kk.arrowleft?1:0)+(Math.abs(I.joy.x)>.2?I.joy.x:0);
    const fw=new T.Vector3(dir.x,0,dir.z);if(fw.lengthSq()<1e-4)fw.set(-Math.sin(cam.yaw),0,-Math.cos(cam.yaw));fw.normalize();const rt=new T.Vector3(-fw.z,0,fw.x);
    const slamK=Kk.q||Kk.g||I.slam,slamE=slamK&&!slamL;slamL=slamK;const powK=Kk.r||I.power,powE=powK&&!powL;powL=powK;const rageK=Kk.shift||I.alt,rageE=rageK&&!rageL;rageL=rageK;
    const rm=P.rageT>0?1.35:1;
    if(!gr){ // ---- flight (hover in place when idle) ----
      const[cr,bs]=VL.spd;const boosting=(Kk.shift||I.alt)&&P.boost>.02&&f>=0;const cruise=boosting?bs:f>0?cr:0;
      P.spd+=(cruise-P.spd)*Math.min(1,dt*(f<0?2.2:boosting?1.6:f>0?.9:1.4));if(f>0||boosting)P.spd+=-dir.y*30*dt*(P.spd>6?1:0);P.spd=clamp(P.spd,0,bs+40);
      if(boosting)P.boost=Math.max(0,P.boost-dt*.25);else P.boost=Math.min(1,P.boost+dt*.08);
      const want=dir.clone().multiplyScalar(P.spd);want.addScaledVector(rt,strafe*12);const up=(Kk[' ']||I.jumpBtn?1:0)-(Kk.c||Kk.control?1:0);want.y+=up*14;
      const tight=I.right||Kk.e||I.drift;if(tight)want.multiplyScalar(.7);
      if(VL.id!=='havoc'&&slamE&&P.slam<=0&&P.p.y>4){P.slam=1;beep(300,.2,'sawtooth',.06);H.say('SLAM!',500)}
      if(P.slam>0){P.v.set(P.v.x*.9,-130,P.v.z*.9);P.spd=0}else P.v.lerp(want,Math.min(1,dt*(tight?11:4)));
      P.prev.copy(P.p);P.p.addScaledVector(P.v,dt);
      const b=K.inBox(P.p.x,P.p.y-.2,P.p.z,city.boxes,.7);if(b){if(P.p.y>b.h-1.6&&P.v.y<=2){P.p.y=b.h+.2;if(P.slam>0){P.slam=0;P.v.set(0,0,0);wreck(b,P.p.clone().setY(b.h-1),200);slamWave()}else if(P.v.y<0)P.v.y=0}else{const sp0=P.v.length();const q={x:P.p.x,z:P.p.z};K.push(q,.8,[b]);P.p.x=q.x;P.p.z=q.z;if(sp0>40){const r=wreck(b,P.p.clone().add(new T.Vector3(0,1,0)),sp0*1.3);H.pow(r==='collapse'?'KRA-KOOOM!':pick(['CRUNCH!','KRAK!','WHAM!']),P.p.clone(),'#FF9F43');P.v.multiplyScalar(r==='collapse'?.8:.4);P.spd*=r==='collapse'?.8:.45;cam.shake=Math.max(cam.shake,.9)}else{if(q.nx)P.v.x=0;else P.v.z=0}}}
      if(P.p.y<.2){if(P.slam>0||P.v.y<-40){P.slam=0;slamWave()}P.p.y=.2;if(P.v.y<0)P.v.y=0}
      if(P.p.y>230)P.p.y=230}
    else{ // ---- Ruin: run, leap, climb, pound ----
      if(rageE&&P.rage>=1&&P.rageT<=0){P.rageT=12;P.rage=1;H.pow('RAAAAGH!',P.p.clone().setY(6*sc),'#2BB673');K.ring(P.p.clone().setY(.4),0x2BB673,2,40,.9);noise(1.2,'lowpass',90,.5);cam.shake=1.4;H.tint('rgba(43,182,115,.35)',1.2)}
      if(P.rageT>0){P.rageT-=dt;P.rage=Math.max(0,P.rageT/12)}
      const spd=(Kk.shift&&P.rageT<=0&&P.rage<1?34:25)*rm;const want=fw.clone().multiplyScalar(f*spd).addScaledVector(rt,strafe*spd*.8);if(want.length()>spd)want.setLength(spd);
      const kk=P.ground?10:1.2;P.v.x+=(want.x-P.v.x)*Math.min(1,dt*kk);P.v.z+=(want.z-P.v.z)*Math.min(1,dt*kk);
      const jk=!!(Kk[' ']||I.jumpBtn);if(jk&&P.ground)P.ch=Math.min(1,P.ch+dt*1.3);
      if(!jk&&P.jl&&P.ground){const ch=P.ch;P.v.y=20+ch*44*Math.sqrt(rm);P.v.x+=fw.x*ch*48*rm;P.v.z+=fw.z*ch*48*rm;P.ground=false;P.ch=0;beep(220+ch*200,.18,'triangle',.06);if(ch>.6)H.pow('HRAAH!',P.p.clone().setY(5*sc),'#2BB673');K.burst(P.p.clone().setY(.3),[0xd8d4e4,0x8c86a3],12,10,1);if(P.p.y<.5)scorchAt(P.p,1.5)}P.jl=jk;
      if(slamE&&!P.ground&&P.p.y>3&&P.slam<=0){P.slam=1;P.v.set(P.v.x*.3,-95,P.v.z*.3);H.say('POUND!',500);beep(300,.2,'sawtooth',.06)}
      if(P.slam<=0)P.v.y-=48*dt;P.prev.copy(P.p);P.p.addScaledVector(P.v,dt);P.ground=false;
      const land=h=>{const vy=P.v.y;P.p.y=h;P.v.y=0;P.ground=true;if(P.slam>0){P.slam=0;slamWave(true);quake(P.p.clone().setY(0),fw.clone())}else if(vy<-38){K.ring(P.p.clone().setY(h+.3),0xd8d4e4,2,20,.6);cam.shake=Math.max(cam.shake,.8);noise(.5,'lowpass',120,.35);people.forEach(q=>{if(q.p.distanceTo(P.p)<14)fling(q,P.p,14)});cars.forEach(q=>{if(!q.dead&&!q.held&&q.p.distanceTo(P.p)<10)blowCar(q,P.p)})}};
      const pad=.9*sc*(P.rageT>0?1.3:1);const b=K.inBox(P.p.x,P.p.y+.1,P.p.z,city.boxes,pad);
      if(b){if(P.prev.y>=b.h-.6&&P.v.y<=0)land(b.h);else{const hs=Math.hypot(P.v.x,P.v.z);const q={x:P.p.x,z:P.p.z};K.push(q,pad,[b]);P.p.x=q.x;P.p.z=q.z;
        if(hs>32&&!b.tree){const r=wreck(b,P.p.clone().setY(P.p.y+2),hs*2.2*rm);H.pow(r==='collapse'?'KRA-KOOOM!':pick(['CRUNCH!','WHAM!']),P.p.clone().setY(P.p.y+3),'#2BB673');cam.shake=Math.max(cam.shake,1)}
        if(q.nx)P.v.x*=-.1;else P.v.z*=-.1;if(f>0&&!b.tree){P.v.y=Math.max(P.v.y,17*rm);if(Math.random()<dt*8)K.burst(P.p.clone().setY(P.p.y+1),[0x8c86a3,0xd8d4e4],2,5,.6)}}}
      if(P.p.y<=0&&!P.ground)land(0);if(P.p.y>260)P.p.y=260}
    city.update(P.p.x,P.p.z);
    const vs=P.v.length();
    // ram / trample
    const rr=gr?3.2*sc*rm*.6:3.2;if(crowd){if(vs>6)crowd.blast(P.p,rr,.8);crowd.scare(P.p,30)}cars.forEach(q=>{if(!q.dead&&!q.fly&&!q.held&&!q.thrown&&q.p.distanceTo(P.p)<rr&&(gr?vs>6:true))blowCar(q,P.p)});people.forEach(q=>{if((q.st==='walk'||q.st==='flee')&&q.p.distanceTo(P.p)<rr+.5&&vs>6)fling(q,P.p,10+vs*.3)});
    if(!gr)air.forEach(a=>{if(!a.fall&&vs>30&&a.p.distanceTo(P.p)<a.aim*.8){hitAir(a,5);cam.shake=1}});
    // pose
    const tight=I.right||Kk.e||I.drift;
    if(!gr){const a=clamp((vs-5)/12,0,1);const climb=vs>1?Math.asin(clamp(P.v.y/vs,-1,1)):0;const yaw=vs>2&&P.slam<=0?Math.atan2(P.v.x,P.v.z):cam.yaw+Math.PI;
      const turn=wrapA(yaw-(HR.userData.py||yaw))/Math.max(dt,.001);HR.userData.py=yaw;P.bank+=(clamp(-turn*.25,-.9,.9)-P.bank)*Math.min(1,dt*4);
      HR.position.copy(P.p).add(new T.Vector3(0,1,0));HR.rotation.set(P.slam>0?Math.PI:a*(Math.PI/2-climb)+(1-a)*.08,yaw,P.bank*a);K.pose(hero,a>.5?'fly':'hover',P.t*3);K.capeAnim(hero,.2+a*.9,now/1000,6+a*8);
      if(vs>110&&!P.mach){P.mach=1;K.ring(P.p.clone(),0xffffff,1,50,.8);H.pow('SONIC BOOM!',P.p.clone().add(new T.Vector3(0,3,0)),'#fff');noise(1,'lowpass',150,.5);cam.shake=1.2;if(crowd)crowd.blast(P.p,26,1.2);cars.forEach(q=>{if(!q.dead&&!q.held&&q.p.distanceTo(P.p)<30)blowCar(q,P.p)});people.forEach(q=>{if(q.p.distanceTo(P.p)<40)fling(q,P.p,16)})}else if(vs<90)P.mach=0}
    else{const hs=Math.hypot(P.v.x,P.v.z);const yaw=(P.punchT>0||P.held||hs<2)?Math.atan2(dir.x,dir.z):Math.atan2(P.v.x,P.v.z);HR.rotation.set(0,yaw,0);HR.position.copy(P.p);hero.scale.setScalar(sc*(1+(P.rageT>0?.3:0)));hero.position.y=-P.ch*.35*sc;
      if(P.held)K.pose(hero,'lift',P.t*3);else if(!P.ground)K.pose(hero,'air',P.t*3);else K.pose(hero,'run',P.t*hs*.28,clamp(hs/22,0,1));const u=hero.userData;if(P.punchT>0){const arm=P.pa?u.armR:u.armL;arm.rotation.set(-Math.PI/2,0,0)}
      if(P.held){const hp=P.p.clone().add(new T.Vector3(0,sc*(P.rageT>0?1.3:1)*2.4+1.4,0));P.held.m.position.copy(hp);P.held.m.rotation.set(0,yaw,0)}}
    H.lines((vs-60)/70);const fv=70+clamp(vs-30,0,120)*.25;if(Math.abs(camera.fov-fv)>.2){camera.fov+=(fv-camera.fov)*Math.min(1,dt*3);camera.updateProjectionMatrix()}
    // ---- attacks ----
    camera.getWorldDirection(V);const aim=cast(camera.position.clone(),V.clone(),420);tAim.copy(aim.kind==='air'||aim.kind==='tg'&&aim.hit.kind!=='car'&&aim.hit.kind!=='person'?camera.position.clone().addScaledVector(V,80):aim.pt);tAim.y=0;
    const fireK=!!(I.down||I.fire||Kk.f||Kk.j);const heatW=VL.heat&&fireK&&P.hot<=0&&P.heat>0;
    if(VL.heat){if(heatW){P.heat=Math.max(0,P.heat-dt*VL.heat);if(P.heat<=0){P.hot=1.6;H.say('Overheated! Cooling down…',1100);beep(200,.3,'square',.05)}}else{P.heat=Math.min(1,P.heat+dt*(P.hot>0?.35:.28));P.hot-=dt}}
    const eye=new T.Vector3();hero.userData.neck.getWorldPosition(eye);eye.y+=.3;const hand=new T.Vector3();hero.userData.armR.getWorldPosition(hand);hand.addScaledVector(V,1.2);hand.y-=.4;
    beam.visible=false;hitGlow.visible=false;lzT-=dt;
    const hitAt=(h,bw,ig)=>{if(h.kind==='bld'){wreck(h.hit,h.pt,bw);if(ig&&Math.random()<ig)ignite(h.hit,h.pt)}else if(h.kind==='gnd'){scorchAt(h.pt);if(crowd)crowd.blast(h.pt,4,.8);cars.forEach(q=>{if(!q.dead&&!q.held&&q.p.distanceTo(h.pt)<4)blowCar(q,h.pt)});people.forEach(q=>{const d=q.p.distanceTo(h.pt);if(d<5)fling(q,h.pt,14);else if(d<25)scareP(q)})}};
    const showBeam=(from,h,w)=>{const seg2=h.pt.clone().sub(from);const L=seg2.length();beam.visible=true;beam.position.copy(from).addScaledVector(seg2,.5);beam.quaternion.setFromUnitVectors(UP,seg2.normalize());beam.scale.set(w*(1+Math.random()*.3),L,w*(1+Math.random()*.3));hitGlow.visible=h.kind!=='air';hitGlow.position.copy(h.pt);hitGlow.scale.setScalar(w*(1.2+Math.random()*.8))};
    if(VL.id==='overlord'){if(heatW){showBeam(eye,aim,1);if(Math.random()<dt*40&&aim.kind!=='air')K.burst(aim.pt.clone(),[0xFFD23F,0xFF7A2A,0xffffff],3,8,.35);if(Math.random()<dt*14)beep(900+Math.random()*300,.03,'sawtooth',.018);
        if(lzT<=0){lzT=.18;if(aim.kind==='tg')hitT(aim.hit,aim.pt,1);else hitAt(aim,c.pick(55,45,40),.12)}}
      if(powE&&P.cd<=0){P.cd=4;H.pow('THUNDER CLAP!',P.p.clone().addScaledVector(V,6).add(new T.Vector3(0,3,0)),'#fff');noise(1.3,'lowpass',160,.55);cam.shake=1.5;for(let k=1;k<=5;k++)K.ring(P.p.clone().addScaledVector(V,k*8),0xffffff,1,6+k*4,.5,null);K.burst(P.p.clone().addScaledVector(V,6),[0xffffff,0xd8d4e4],40,40,1);
        const cone=(p,r)=>{const d=p.clone().sub(P.p);const L=d.length();return L<r&&d.normalize().dot(V)>.7};
        nearB(P.p,55).forEach(b=>{const cp=closest(b,P.p.clone().addScaledVector(V,20));if(cone(cp,60))wreck(b,cp,110*(1-cp.distanceTo(P.p)/80))});if(crowd)crowd.blast(P.p.clone().addScaledVector(V,28),26,1.3);cars.forEach(q=>{if(!q.dead&&!q.held&&cone(q.p,60))blowCar(q,P.p)});people.forEach(q=>{if(cone(q.p,70))fling(q,P.p,34)});jets.forEach(j=>{if(!j.dead&&cone(j.p,60))j.hp=0});air.forEach(a=>{if(!a.fall&&cone(a.p,70))hitAir(a,3)});if(boss&&cone(boss.p,50)){boss.hp-=9;boss.flash=.3}}}
    else if(VL.id==='havoc'){if(heatW){showBeam(hand,aim,.22);if(lzT<=0){lzT=.07;beep(140+Math.random()*60,.03,'square',.03);if(Math.random()<.5&&aim.kind!=='air')K.burst(aim.pt.clone(),[0xFFD23F,0xffffff],3,10,.25);
          if(aim.kind==='tg')hitT(aim.hit,aim.pt,.32);else if(aim.kind==='bld'){P.mg+=1;if(P.mg>=4){P.mg=0;wreck(aim.hit,aim.pt,c.pick(34,28,24))}}else if(aim.kind==='gnd'){if(Math.random()<.3)scorchAt(aim.pt,.5);people.forEach(q=>{const d=q.p.distanceTo(aim.pt);if(d<3)fling(q,aim.pt,10);else if(d<30)scareP(q)});cars.forEach(q=>{if(!q.dead&&!q.held&&q.p.distanceTo(aim.pt)<3.5)hitT(q,aim.pt,.32)})}}}
      if(powE&&P.cd<=0){P.cd=1.1;const m=add(new T.Group());part(T,cy(T,.25,.25,1.6,8),TM(0x5A5470),0,0,0,m).rotation.x=Math.PI/2;part(T,sp(T,.45),add3(0xFFB02A,.9),0,0,-.9,m);m.position.copy(hand);proj.push({m,v:V.clone().multiplyScalar(150),l:3,kind:'rocket',r:11,pw:115,ign:true,grav:0,home:homing(hand,V)});beep(200,.25,'sawtooth',.06);noise(.3,'highpass',800,.2)}
      if(slamE&&P.qcd<=0){P.qcd=c.pick(10,12,14);const tp=aim.kind==='air'?camera.position.clone().addScaledVector(V,120).setY(0):aim.pt.clone();H.say('Airstrike incoming!',1200);sweep(1400,300,1.2,'sawtooth',.05);for(let k=0;k<8;k++){const q=tp.clone().addScaledVector(fw,(k-3.5)*9);q.y=Math.max(1,q.y);timers.push({t:.9+k*.13,fn:()=>boom(q,10,100,true)})}}}
    else if(VL.id==='tempest'){if(heatW&&lzT<=0){lzT=.22;bolt(hand,aim.pt);noise(.25,'highpass',1500,.25);if(aim.kind==='tg')hitT(aim.hit,aim.pt,1.2);else hitAt(aim,c.pick(40,34,30),.1);hitGlow.visible=true;hitGlow.position.copy(aim.pt);
        const pool=[...cars.filter(q=>!q.dead&&!q.held&&!q.thrown),...people.filter(q=>q.st!=='gone'&&q.st!=='fly'),...jets.filter(j=>!j.dead),...air.filter(a=>!a.fall)];let from=aim.pt,n=0;const used=new Set([aim.hit]);while(n<3){let bq=null,bd=24;pool.forEach(q=>{if(used.has(q))return;const d=(q.cp||q.p).distanceTo(from);if(d<bd){bd=d;bq=q}});if(!bq)break;used.add(bq);const to=(q=>q.cp||q.p)(bq).clone();bolt(from,to);hitT(bq,to,.8);from=to;n++}}
      if(heatW)hitGlow.visible=true;
      if(powE&&P.cd<=0){P.cd=c.pick(6,7,8);const pt=aim.kind==='gnd'||aim.kind==='bld'?aim.pt.clone().setY(0):camera.position.clone().addScaledVector(V,60).setY(0);makeTornado(pt)}}
    else if(VL.id==='pyra'){if(heatW){const L=Math.min(60,aim.t);spray(hand,V,L);if(Math.random()<dt*10)noise(.2,'bandpass',500,.12);if(lzT<=0&&aim.t<60){lzT=.18;if(aim.kind==='tg')hitT(aim.hit,aim.pt,.8);else{hitAt(aim,c.pick(16,13,11),1);if(aim.kind==='gnd')scorchAt(aim.pt,1.4)}}}
      if(powE&&P.cd<=0){P.cd=c.pick(4,5,6);const tp=aim.kind==='air'||aim.kind==='tg'?camera.position.clone().addScaledVector(V,90):aim.pt.clone();if(aim.kind==='bld'){const b=aim.hit;tp.set(clamp(tp.x,b.x0+2,b.x1-2),b.h,clamp(tp.z,b.z0+2,b.z1-2))}else if(aim.kind!=='gnd')tp.y=0;tp.y=Math.max(0,tp.y);const st2=tp.clone().add(new T.Vector3(-fw.x*40,150,-fw.z*40));const m=add(new T.Group());const rk=part(T,new T.IcosahedronGeometry(3,0),TM(0x3a1d14),0,0,0,m);rk.userData.noInk=1;part(T,new T.SphereGeometry(4.6,12,8),add3(0xFF7A2A,.6),0,0,0,m);m.position.copy(st2);
        const mk=add(new T.Mesh(new T.RingGeometry(6,8,32),new T.MeshBasicMaterial({color:0xF2352A,transparent:true,opacity:.7,side:T.DoubleSide,depthWrite:false})));mk.rotation.x=-Math.PI/2;mk.position.copy(tp).setY(tp.y+.3);
        proj.push({m,v:tp.clone().sub(st2).normalize().multiplyScalar(120),l:4,kind:'meteor',r:18,pw:200,ign:true,grav:0,mark:mk,floor:tp.y+.3});H.say('Meteor incoming!',900);sweep(900,120,1.2,'sawtooth',.05)}}
    else if(VL.id==='ruin'){if(fireK&&P.pcd<=0&&!P.held){P.pcd=P.rageT>0?.22:.34;P.pa=1-P.pa;P.punchT=.16;const pw=P.rageT>0?2:1;const pp=P.p.clone().add(new T.Vector3(0,2.2*sc,0)).addScaledVector(V,3.4*sc*rm);let hitAny=false;
        nearB(pp,4.5*rm).forEach(b=>{const cp=closest(b,pp);wreck(b,cp,c.pick(110,95,85)*pw);hitAny=true});const R=6.5*rm;if(crowd){const bl=crowd.blast(pp,R,1);if(bl.p||bl.c)hitAny=true}cars.forEach(q=>{if(!q.dead&&!q.held&&!q.thrown&&q.p.distanceTo(pp)<R+1){blowCar(q,P.p);hitAny=true}});people.forEach(q=>{if(q.st!=='gone'&&q.p.distanceTo(pp)<R+2){fling(q,P.p,26);hitAny=true}});
        jets.forEach(j=>{if(!j.dead&&j.p.distanceTo(pp)<R+3){j.hp-=1;hitAny=true}});air.forEach(a=>{if(!a.fall&&a.p.distanceTo(pp)<R+a.aim){hitAir(a,2);hitAny=true}});if(boss&&boss.p.distanceTo(pp)<R+4){boss.hp-=c.pick(7,6,5)*pw;boss.flash=.3;hitAny=true;boss.v.addScaledVector(V,40)}
        if(hitAny){H.pow(pick(['SMASH!','POW!','WHAM!','KRAKK!']),pp.clone(),'#2BB673');noise(.4,'lowpass',180,.4);cam.shake=Math.max(cam.shake,.6)}else noise(.12,'bandpass',600,.12)}
      if(powE){if(P.held){const h=P.held;P.held=null;const v=V.clone().multiplyScalar(100*rm);v.y+=8;const pr={m:h.m,v,l:4,kind:h.car?'car':'rock',r:h.car?9:7,pw:h.car?95:75,ign:!!h.car,grav:14,home:homing(h.m.position,V)};if(h.car){pr.car=h.car;h.car.held=false;h.car.thrown=true}proj.push(pr);beep(180,.2,'sawtooth',.06);H.pow('HEAVE!',h.m.position.clone(),'#2BB673')}
        else{let bq=null,bd=15*rm;cars.forEach(q=>{if(q.dead||q.fly||q.held||q.thrown)return;const d=q.p.distanceTo(P.p);if(d<bd){bd=d;bq=q}});if(bq){bq.held=true;P.held={car:bq,m:bq.m};H.say('Got one! Press R to throw',900)}else{const m=add(new T.Mesh(new T.DodecahedronGeometry(2.2,0),TM(0x8c86a3)));K.ink(m,.1);P.held={m};K.burst(P.p.clone().setY(.4),[0x8c86a3,0x5A5470],14,10,1);scorchAt(P.p,2);H.say('Ripped up the road! R to throw',900)}beep(120,.2,'square',.05)}}
      if(P.rageT<=0){P.rage=Math.min(1,P.rage+Math.max(0,score-lastScore)*.006);if(P.rage>=1&&!P.rageRdy){P.rageRdy=1;H.say('RAGE is full! Press Shift',1500)}}if(P.rage<1)P.rageRdy=0}
    lastScore=score;
    // jets & shots
    const dots=[];
    jets=jets.filter(j=>{if(j.dead)return false;const to=P.p.clone().sub(j.p);const d=to.length();const orbit=new T.Vector3(Math.cos(P.t*.6+j.off)*50,20+Math.sin(P.t+j.off)*8,Math.sin(P.t*.6+j.off)*50);const goal=P.p.clone().add(orbit);const dv=goal.sub(j.p).normalize().multiplyScalar(d>90?Math.max(90,vs*1.05):40);j.v.lerp(dv,Math.min(1,dt*1.6));j.p.addScaledVector(j.v,dt);j.g.lookAt(j.p.clone().add(j.v));j.fl.scale.setScalar(.8+Math.random()*.5);
      j.cd-=dt;if(j.cd<=0&&d<130){j.cd=c.pick(3.2,2.4,1.8)+Math.random();shoot(j.p.clone(),0x7FC8F8,55*diff,8)}
      if(d<4.5&&vs>30){killJet(j,'KRUNCH!');return false}if(j.hp<=0){killJet(j);return false}dots.push({x:j.p.x,z:j.p.z,col:'#2d6fd6',r:5});return true});
    const hc=P.p.clone().setY(P.p.y+(gr?2*sc:1)),hr2=gr?2.2*sc:2;shots=shots.filter(s=>{s.l-=dt;s.m.position.addScaledVector(s.v,dt);if(s.m.position.distanceTo(hc)<hr2){hurt(s.dmg,'');K.burst(s.m.position.clone(),[0x7FC8F8,0xffffff],12,8,.5);scene.remove(s.m);return false}if(s.l<=0||s.m.position.y<0){scene.remove(s.m);return false}return true});
    air.forEach(a=>{if(!a.fall)dots.push({x:a.p.x,z:a.p.z,col:a.type==='heli'?(a.cop?'#2d3a5a':'#FFD23F'):'#ffffff',r:a.type==='blimp'?8:5})});
    // missions
    let tg=null,tl='';
    if(mi<0){H.cap('Free roam · '+VL.name+' in Metro City','Damage '+money(score)+' · towers '+collapsed+' · cars '+carsN+' · people sent flying '+pplN+' · aircraft '+airN+' · P for menu')}
    if(mi===0){timeLeft-=dt;H.cap('Issue #1 · Grand Entrance','Damage '+money(score)+' / '+money(target)+' · '+Math.max(0,Math.ceil(timeLeft))+'s left');
      if(score>=target)F.win(M,score+Math.round(timeLeft)*2,[[money(score),'damage'],[collapsed,'toppled'],[carsN,'cars'],[LVN[c.level],'mode']],'Metro City now knows your name. It’s on every news channel, usually followed by the word “RUN”.');
      else if(timeLeft<=0)F.lose(M,'Not scary enough','The news called it “a mild inconvenience”. How insulting. Try again?')}
    if(mi===1){timeLeft-=dt;H.cap('Issue #2 · Rush Hour','Vehicles '+Math.min(carsN,vehT)+'/'+vehT+' · people running '+Math.min(scared,pplT)+'/'+pplT+' · '+Math.max(0,Math.ceil(timeLeft))+'s left');
      if(carsN>=vehT&&scared>=pplT)F.win(M,score+Math.round(timeLeft)*3,[[carsN,'vehicles'],[scared,'people ran'],[pplN,'sent flying'],[LVN[c.level],'mode']],'Traffic reports now just say “Don’t.” Everyone is working from home until further notice.');
      else if(timeLeft<=0)F.lose(M,'Traffic survived','Somehow, everyone still got home on time. Try again?')}
    if(mi===2){const need=c.pick(5,7,9);let ba=null,bd=1e9;air.forEach(a=>{if(a.fall)return;const d=a.p.distanceTo(P.p);if(d<bd){bd=d;ba=a}});if(ba){tg=ba.p.clone();tl=ba.type.toUpperCase()+' '+Math.round(bd)+'m'}
      H.cap('Issue #3 · Air Traffic','Aircraft down '+airN+'/'+need+' · damage '+money(score));if(airN>=need)F.win(M,score+Math.round(P.hp)*3,[[airN,'aircraft'],[money(score),'damage'],[Math.round(P.hp),'health'],[LVN[c.level],'mode']],'Every airline has quietly rerouted around Metro City. The blimp company has filed a strongly worded letter.')}
    if(mi===3){spawnT-=dt;const total=12;if(spawnT<=0&&jets.length<c.pick(3,4,5)&&downed+jets.length<total){spawnT=c.pick(3,2.4,1.8);makeJet()}
      let bj=null,bd=1e9;jets.forEach(j=>{const d=j.p.distanceTo(P.p);if(d<bd){bd=d;bj=j}});if(bj){tg=bj.p.clone();tl='JET '+Math.round(bd)+'m'}
      H.cap('Issue #4 · Hero Corps','Jets downed '+downed+'/'+total+' · damage '+money(score));if(downed>=total)F.win(M,score+Math.round(P.hp)*3,[[downed,'jets'],[money(score),'damage'],[Math.round(P.hp),'health'],[LVN[c.level],'mode']],'The Hero Corps retreats to repaint their jets. Nobody else is brave enough to get in your way. Almost nobody.')}
    if(mi===4&&boss){const B=boss;B.flash-=dt;B.t-=dt;const to=P.p.clone().sub(B.p);const d=to.length();const bh=gr?6:12;
      if(B.st==='circle'){B.a+=dt*.7*diff;const goal=P.p.clone().add(new T.Vector3(Math.cos(B.a)*45,bh+Math.sin(B.a*2)*(gr?3:8),Math.sin(B.a)*45));{const gv=goal.sub(B.p).multiplyScalar(1.4);if(gv.length()>170)gv.setLength(170);B.v.lerp(gv,Math.min(1,dt*2))};B.cd-=dt;if(B.cd<=0){B.cd=c.pick(2.6,2,1.5);shoot(B.p.clone(),0xFFD23F,65*diff,10)}if(B.t<=0){B.st='wind';B.t=.9;H.say('Valor is charging!',800);beep(500,.4,'sawtooth',.05)}}
      else if(B.st==='wind'){B.v.multiplyScalar(Math.pow(.05,dt));if(B.t<=0){B.st='charge';B.t=1.6;B.cv=to.add(new T.Vector3(0,gr?2*sc:0,0)).normalize().multiplyScalar(110*diff)}}
      else if(B.st==='charge'){B.v.copy(B.cv);if(d<4+(gr?2*sc:0)){hurt(20,'POW! Captain Valor lands a punch!');P.v.addScaledVector(B.cv,.6);B.st='circle';B.t=5+Math.random()*2}if(B.t<=0){B.st='circle';B.t=5+Math.random()*2}const bb=K.inBox(B.p.x,B.p.y,B.p.z,city.boxes,1);if(bb){wreck(bb,B.p.clone(),120);B.st='dizzy';B.t=2.5;B.v.set(0,0,0);H.say('He crashed! Hit him now!',1100)}}
      else if(B.st==='dizzy'){B.v.multiplyScalar(Math.pow(.1,dt));if(B.t<=0){B.st='circle';B.t=5}}
      B.p.addScaledVector(B.v,dt);if(B.p.y<3)B.p.y=3;B.g.lookAt(B.st==='charge'?B.p.clone().add(B.v):P.p);K.pose(B.f,B.st==='charge'?'fly':'hover',P.t*3);K.capeAnim(B.f,.6,now/1000,8);B.f.rotation.x=B.st==='charge'?Math.PI/2:0;B.f.visible=!(B.flash>0&&Math.sin(now/30)>0);
      if(d<5&&vs>60&&P.inv<=0&&B.st!=='charge'){B.hp-=c.pick(14,11,9);B.flash=.4;P.v.multiplyScalar(-.4);P.inv=.5;H.pow('KA-POW!',B.p.clone().add(new T.Vector3(0,3,0)),'#FFD23F');cam.shake=1;noise(.5,'lowpass',400,.3)}
      H.boss('CAPTAIN VALOR',Math.max(0,B.hp)/100);dots.push({x:B.p.x,z:B.p.z,col:'#FFD23F',r:9});tg=B.p.clone().add(new T.Vector3(0,3,0));tl='VALOR '+Math.round(d)+'m';
      H.cap('Issue #5 · Captain Valor',B.st==='dizzy'?'He’s dizzy! Hit him!':gr?'Throw cars at him (R) · punch him when he gets close':'Keep hitting him · dodge his charge');
      if(B.hp<=0){B.dead=true;H.boss(null);K.burst(B.p.clone(),[0x2d6fd6,0xFFD23F,0xffffff],80,24,1.4);H.pow('DEFEATED!',B.p.clone().add(new T.Vector3(0,4,0)),'#FFD23F');B.g.visible=false;boss=null;F.win(M,score+Math.round(P.hp)*8,[[money(score),'damage'],[collapsed,'toppled'],[Math.round(P.hp),'health'],[LVN[c.level],'mode']],'Captain Valor limps away to “regroup”. Metro City has a new ruler, and it’s you. Try not to let it go to your head.')}}
    ptr(tg,tl);
    if(P.slam<=0)P.hp=Math.min(100,P.hp+dt*1.5);
    hpB(P.hp/100,'HEALTH '+Math.ceil(P.hp));
    if(gr)htB(P.rageT>0?P.rageT/12:P.rage,P.rageT>0?'RAGE! '+Math.ceil(P.rageT)+'s':P.rage>=1?'RAGE READY [Shift]':'RAGE');else htB(P.heat,P.hot>0?'OVERHEATED':VL.fire+'  [hold click]');
    const cdMax=VL.id==='overlord'?4:VL.id==='havoc'?1.1:VL.id==='tempest'?c.pick(6,7,8):VL.id==='pyra'?c.pick(4,5,6):1;pwB(gr?1:1-Math.max(0,P.cd)/cdMax,gr?(P.held?'THROW [R]':'GRAB A CAR [R]'):P.cd>0?VL.pow+' '+Math.ceil(P.cd)+'s':VL.pow+' READY [R]');
    spB(gr?Math.hypot(P.v.x,P.v.z)/40:vs/160,gr?(P.ground?(P.ch>0?'LEAP '+Math.round(P.ch*100)+'%':'Hold SPACE to leap · Q in the air to pound'):'ALT '+Math.round(P.p.y)+'m · [Q] pound'):Math.round(vs*7)+' MPH · ALT '+Math.round(P.p.y)+'m · '+(VL.id==='havoc'?(P.qcd>0?'airstrike '+Math.ceil(P.qcd)+'s':'[Q] airstrike'):'[Q] slam'));
    H.score(Math.floor(score),'havoc');rad(P.p.x,P.p.z,cam.yaw,dots,city.boxes);c.stat(VL.name+' · '+F.tag(mi)+' · '+money(score));
    if(gr)cam.place(P.p.clone().add(new T.Vector3(0,3.4*sc/1.9*(P.rageT>0?1.2:1),0)).addScaledVector(rt,2.6),dt,12.5+(P.rageT>0?2.5:0),1.5,10);else cam.place(P.p.clone().addScaledVector(rt,1.9),dt,7+clamp(vs,0,150)*.02,1.5,10)});
  F.intro(M,'Overlord','A Detour original · 3D villain rampage','<p>Pick your villain and bring Metro City to its knees.</p><p><b>Overlord</b> burns towers with laser eyes. <b>Ruin</b> is a giant green brute who leaps whole blocks and throws cars. <b>Havoc</b> brings a minigun, rockets and airstrikes. <b>Tempest</b> throws chain lightning and tornadoes. <b>Pyra</b> sets the skyline on fire and calls down meteors.</p><p>Buildings crack, burn, spread fire and collapse. Crowds run, cars fly, and cargo planes, news choppers and blimps fall out of the sky (their crews always parachute out).</p>','Move with WASD and look with the mouse (click the game to lock the mouse). <b>Hold click</b> or F for your main attack, <b>R</b> for your power and <b>Q</b> for your special. Flyers: Shift boosts, Space rises, C drops, and E or right-click makes tight turns. Ruin: hold <b>Space</b> to charge a leap, push into walls to climb, and press Shift when RAGE is full. P pauses. On a phone: joystick, drag to look, and the on-screen buttons.');
  return()=>st3.dispose()})}});
