const {chromium}=require('/opt/node22/lib/node_modules/playwright');const fs=require('fs');const OUT=__dirname+'/../ads/shots/';
(async()=>{const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome',args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=async()=>{const p=await b.newPage({viewport:{width:1280,height:900}});await p.route('**/three.min.js',r=>r.fulfill({body:fs.readFileSync(__dirname+'/node_modules/three/build/three.min.js'),contentType:'application/javascript'}));await p.route('**/matter.min.js',r=>r.fulfill({body:fs.readFileSync(__dirname+'/node_modules/matter-js/build/matter.min.js'),contentType:'application/javascript'}));await p.route(/fonts\./,r=>r.abort());p.on('pageerror',e=>console.log('ERR',e.message));return p};
const shot=async(p,sel,name)=>{await p.addStyleTag({content:'.cx-say,.cx-arrow{display:none!important}'});const e=await p.$(sel);await e.screenshot({path:OUT+name+'.jpg',type:'jpeg',quality:88})};
// Overlord villains
const vil=async(v,name,act)=>{const p=await page();await p.goto('file://'+process.argv[2]+'?g=hs_villain#hs_villain');await p.waitForTimeout(2500);const all=await p.$$('.ov3 .btn');await all[all.length-1].click();await p.waitForTimeout(300);await (await p.$('.ov3 [data-v="'+v+'"]')).click();await p.waitForTimeout(400);let pr=await p.$('.ov3 .btn.primary');if(pr){await pr.click();await p.waitForTimeout(300)}
  await p.evaluate(()=>{const s=document.querySelector('.cx-say,.cx-bubble');});await p.waitForTimeout(2500);await act(p);await shot(p,'.g3',name);await p.close()};
const aimB=p=>p.evaluate(()=>{const X=window.__HX;let best=null,bd=1e9;X.blds.forEach(B=>{const cx=(B.gx0+B.fx/2)*4,cz=(B.gz0+B.fz/2)*4;const d=Math.hypot(cx-X.P.p.x,cz-X.P.p.z);if(d<bd&&d>30&&B.fh>8){bd=d;best=B}});if(best)X.aimAt((best.gx0+best.fx/2)*4,10,(best.gz0+best.fz/2)*4)});
await vil(0,'overlord',async p=>{await aimB(p);await p.keyboard.down('f');for(let i=0;i<8;i++){await aimB(p);await p.waitForTimeout(300)}});
await vil(4,'pyra',async p=>{await aimB(p);await p.keyboard.press('r');await p.waitForTimeout(1600);await p.keyboard.down('f');for(let i=0;i<4;i++){await aimB(p);await p.waitForTimeout(300)}});
await vil(3,'tempest',async p=>{await aimB(p);await p.keyboard.press('r');for(let i=0;i<10;i++){await aimB(p);await p.waitForTimeout(300)}});
// Havoc aerial crowd
{const p=await page();await p.goto('file://'+process.argv[2]+'?g=hs_havoc#hs_havoc');await p.waitForTimeout(2500);await (await p.$('.ov3 .btn.primary')).click();await p.waitForTimeout(2500);await p.keyboard.press('Space');for(let i=0;i<6;i++){await p.evaluate(()=>{const X=window.__HX;X.P.p.y=35;X.P.v.set(0,0,0);X.aimAt(X.P.p.x+30,0,X.P.p.z-30)});await p.waitForTimeout(200)}await p.keyboard.press('2');await p.keyboard.down('f');await p.waitForTimeout(900);await p.keyboard.up('f');await p.waitForTimeout(700);await shot(p,'.g3','havoc');await p.close()}
// Bonk
{const p=await page();await p.goto('file://'+process.argv[2]+'?g=ph_buddy#ph_buddy');await p.waitForTimeout(1500);const cv=await p.$('canvas');const bb=await cv.boundingBox();await p.waitForTimeout(1500);await p.mouse.click(bb.x+bb.width*.5,bb.y+bb.height*.5);await p.waitForTimeout(120);await shot(p,'canvas','bonk');await p.close()}
// Pizza
{const p=await page();await p.goto('file://'+process.argv[2]+'?g=cook_pizza#cook_pizza');await p.waitForTimeout(800);const cv=await p.$('canvas.board');const at=async(X,Y)=>{const bb=await cv.boundingBox();await p.mouse.click(bb.x+X/960*bb.width,bb.y+Y/620*bb.height);await p.waitForTimeout(150)};
 const path=async(pts)=>{const bb=await cv.boundingBox();const f=(X,Y)=>[bb.x+X/960*bb.width,bb.y+Y/620*bb.height];await p.mouse.move(...f(...pts[0]));await p.mouse.down();for(const q of pts.slice(1))await p.mouse.move(...f(...q),{steps:8});await p.mouse.up()};
 const sweep=async()=>{const pts=[];for(let y=232,k=0;y<=515;y+=28,k++){const hw=Math.sqrt(Math.max(0,160*160*.8-(y-372)**2));pts.push([385+(k%2?hw:-hw),y],[385+(k%2?-hw:hw),y])}await path(pts)};
 await at(480,378);await p.waitForTimeout(2600);await at(165,548);await sweep();await at(655,515);await sweep();await at(655,515);for(let i=0;i<10;i++)await at(300+(i%4)*55,270+Math.floor(i/4)*80);await shot(p,'canvas.board','pizza');await p.close()}
// Tractor
{const p=await page();await p.goto('file://'+process.argv[2]+'?g=sim_tractor#sim_tractor');await p.waitForTimeout(2500);await (await p.$('.ov3 .btn.primary')).click();await p.waitForTimeout(500);
 for(const [z,t] of [[-70,'1'],[-64,'1'],[-58,'2'],[-52,'2']]){await p.keyboard.press(t);await p.evaluate(z=>{const P=window.__TF.P;P.x=-78;P.z=z;P.yaw=Math.PI/2;P.v=9},z);await p.keyboard.down('w');await p.waitForTimeout(5500);await p.keyboard.up('w')}
 await p.evaluate(()=>window.__TF.setT(80));await p.waitForTimeout(3500);await p.evaluate(()=>window.__TF.setT(1));await p.keyboard.press('3');await p.evaluate(()=>{const P=window.__TF.P;P.x=-78;P.z=-52;P.yaw=Math.PI/2;P.v=6});await p.keyboard.down('w');await p.waitForTimeout(3000);await p.keyboard.up('w');await shot(p,'.g3','tractor');await p.close()}
// Home grid
{const p=await b.newPage({viewport:{width:1100,height:1400}});await p.route(/fonts\./,r=>r.abort());await p.goto('file:///home/user/webs/index.html');await p.waitForTimeout(800);await p.screenshot({path:OUT+'home.jpg',type:'jpeg',quality:88,fullPage:false});const g=await p.$('#grid');await g.scrollIntoViewIfNeeded();await p.screenshot({path:OUT+'grid.jpg',type:'jpeg',quality:88});await p.close()}
await b.close()})();
