const {chromium}=require('/opt/node22/lib/node_modules/playwright');const fs=require('fs');
(async()=>{const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome',args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const p=await b.newPage({viewport:{width:900,height:620}});const errs=[];p.on('pageerror',e=>errs.push(e.message+' '+(e.stack||'').split('\n')[1]));
await p.route('**/three.min.js',r=>r.fulfill({body:fs.readFileSync(__dirname+'/node_modules/three/build/three.min.js'),contentType:'application/javascript'}));await p.route(/fonts\.|google/,r=>r.abort());
await p.goto('file://'+process.argv[2]+'?g=hs_kaiju#hs_kaiju');await p.waitForTimeout(2500);
await (await p.$('.ov3 .btn.primary')).click();await p.waitForTimeout(500);await (await p.$('.ov3 .btn.primary')).click();await p.waitForTimeout(1500);await p.keyboard.press('g');
const st=()=>p.evaluate(()=>{const X=window.__HX;return {p:[X.P.p.x|0,X.P.p.y|0,X.P.p.z|0],v:Math.round(Math.hypot(X.P.v.x,X.P.v.z)),sw:X.KZ.sw.toFixed(2),t:X.KZ.t.toFixed(1),boats:X.enemies.filter(e=>e.kind==='boat'&&!e.dead).length,blocks:X.stats.blocks}});
console.log(JSON.stringify(await st()));await p.screenshot({path:__dirname+'/s/ks0.png'});
await p.keyboard.down('w');for(let i=0;i<6;i++){await p.waitForTimeout(1500);console.log(JSON.stringify(await st()))}await p.screenshot({path:__dirname+'/s/ks1.png'});
await p.keyboard.down('Shift');for(let i=0;i<6;i++){await p.waitForTimeout(1500);console.log(JSON.stringify(await st()))}await p.screenshot({path:__dirname+'/s/ks2.png'});
console.log('errors',errs.join('\n')||'none');await b.close()})();
