const {chromium}=require('/opt/node22/lib/node_modules/playwright');const fs=require('fs');
(async()=>{const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome',args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const pg=async()=>{const p=await b.newPage({viewport:{width:1000,height:640}});p.on('pageerror',e=>console.log('ERR',e.message));await p.route('**/three.min.js',r=>r.fulfill({body:fs.readFileSync(__dirname+'/node_modules/three/build/three.min.js'),contentType:'application/javascript'}));await p.route(/fonts\./,r=>r.abort());return p};
{const p=await pg();await p.goto('file://'+process.argv[2]+'?g=hs_havoc#hs_havoc');await p.waitForTimeout(2500);await (await p.$('.ov3 .btn.primary')).click();await p.waitForTimeout(1500);
 const info=await p.evaluate(()=>{const X=window.__HX;let best=null;X.blds.forEach(B=>{if(B.fh>=8&&B.fx>=4&&(!best||B.fx*B.fz>best.fx*best.fz))best=B});const cx=(best.gx0+best.fx/2)*4,cz=(best.gz0+best.fz/2)*4;X.P.p.set(best.gx0*4-11,12,cz);X.P.v.set(0,0,0);X.P.ground=false;X.best=best;X.aimAt(cx+100,12,cz);return{x0:(best.gx0)*4,x1:(best.gx0+best.fx)*4,cz,px:X.P.p.x,alive:best.alive}});
 console.log('building x',info.x0,'..',info.x1,'player x',info.px);
 await p.keyboard.down('Shift');await p.keyboard.down('w');for(let i=0;i<40;i++){await p.evaluate(z=>{const X=window.__HX;X.P.p.y=12;X.aimAt(X.P.p.x+100,12,z)},info.cz);const q=await p.evaluate(()=>{const X=window.__HX;return [X.P.p.x.toFixed(1),X.P.p.y.toFixed(1),X.P.v.length().toFixed(1),X.stats.blocks]});console.log('t',i,q.join(' '));await p.waitForTimeout(250)}await p.keyboard.up('w');await p.keyboard.up('Shift');
 const r=await p.evaluate(()=>{const X=window.__HX;return{x:X.P.p.x|0,alive:X.best.alive,blocks:X.stats.blocks}});console.log('after: player x',r.x,'building alive blocks',info.alive,'->',r.alive,'total destroyed',r.blocks,'passed through:',r.x>info.x1);await p.screenshot({path:__dirname+'/s/ram.png'});await p.close()}
{const p=await pg();await p.goto('file://'+process.argv[2]+'?g=hs_speed#hs_speed');await p.waitForTimeout(2500);const all=await p.$$('.ov3 .btn');await all[all.length-1].click();await p.waitForTimeout(500);const pr=await p.$('.ov3 .btn.primary');if(pr){await pr.click();await p.waitForTimeout(500)}await p.waitForTimeout(1000);
 await p.evaluate(()=>{const P=window.__RP();const bs=window.__RB();let best=null,bd=1e9;bs.forEach(b=>{if(b.tree||b.h<15)return;const cx=(b.x0+b.x1)/2,cz=(b.z0+b.z1)/2;const d=Math.hypot(cx-P.x,cz-P.z);if(d<bd&&d>25){bd=d;best=b}});const cx=(best.x0+best.x1)/2,cz=(best.z0+best.z1)/2;window.__tb=best;P.face=P.mv=Math.atan2(cx-P.x,cz-P.z);const K=window.__hsK;});let maxY=0,roof=0;await p.keyboard.down('w');for(let i=0;i<40;i++){await p.waitForTimeout(200);const P=await p.evaluate(()=>{const P=window.__RP();const b=window.__tb;P.face=P.mv=Math.atan2((b.x0+b.x1)/2-P.x,(b.z0+b.z1)/2-P.z);return[P.y,P.air,P.climbing,P.spd]});maxY=Math.max(maxY,P[0]);if(P[0]>await p.evaluate(()=>window.__tb.h)-1){await p.keyboard.up('w');for(let k=0;k<6;k++){await p.waitForTimeout(1000);console.log('after release',k,await p.evaluate(()=>{const P=window.__RP();return P.y.toFixed(1)+' vy '+P.vy.toFixed(1)+' air '+P.air}))}const L=await p.evaluate(()=>{const P=window.__RP();return[P.y.toFixed(1),P.air,P.spd|0]});console.log('released on top: y',L[0],'air',L[1],'spd',L[2],'ov',await p.evaluate(()=>{const o=document.querySelector('.ov3');return o?o.textContent.slice(0,80):'none'}),'boxes',await p.evaluate(()=>{const P=window.__RP();return JSON.stringify(window.__RB().filter(b=>P.x>b.x0-1&&P.x<b.x1+1&&P.z>b.z0-1&&P.z<b.z1+1).map(b=>[b.h.toFixed(1),!!b.dead,!!b.tree,(P.x-b.x0).toFixed(1),(b.x1-P.x).toFixed(1),(P.z-b.z0).toFixed(1),(b.z1-P.z).toFixed(1)]))+' vy '+P.vy.toFixed(2)+' climbT '+P.climbT}));await p.screenshot({path:__dirname+'/s/blur_top.png'});break}if(P[0]>5&&!P[1])roof++;if(i%8===0)console.log('blur y',P[0].toFixed(1),'air',P[1],'climb',P[2],'spd',P[3]|0)}await p.keyboard.up('w');
 console.log('target h',await p.evaluate(()=>window.__tb.h|0));console.log('blur max height',maxY.toFixed(1),'frames standing on roof',roof);await p.screenshot({path:__dirname+'/s/blur_climb.png'});await p.close()}
await b.close()})();
