const {chromium}=require('/opt/node22/lib/node_modules/playwright');const fs=require('fs');
(async()=>{const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome',args:['--use-gl=swiftshader','--enable-webgl','--ignore-gpu-blocklist']});
const p=await b.newPage({viewport:{width:900,height:600}});const errs=[];p.on('pageerror',e=>errs.push(e.message));
await p.route(/fonts\.|google/,r=>r.abort());await p.route(/cdnjs.*three/,r=>r.fulfill({body:fs.readFileSync(__dirname+'/node_modules/three/build/three.min.js'),contentType:'application/javascript'}));
await p.route('https://detour.test/**',r=>r.fulfill({body:fs.readFileSync(__dirname+'/../srv/test.html'),contentType:'text/html'}));
await p.goto('https://detour.test/#contract');await p.waitForFunction(()=>window.__SC,null,{timeout:60000});await p.waitForTimeout(1000);
const r=await p.evaluate(()=>{const N=__SC,K=N.K,log=[];K.menuOff();N.startLevel(0);const NAV=K.NAV;log.push('nav '+NAV.w+'x'+NAV.h+' cs '+NAV.cs);
 const a=N.tw(24,19),b2=N.tw(29,9);const pth=K.astar(a.x,a.z,b2.x,b2.z,40000);log.push('path '+(pth?pth.length:'null'));const T2=(a1,b1)=>{const a=N.tw(...a1),b=N.tw(...b1);const q=K.astar(a.x,a.z,b.x,b.z,40000);return a1+'->'+b1+': '+(q?q.length:'null')};log.push(T2([20,10],[29,9]));{const b=N.tw(29,9);const q=K.astar(1,0,b.x,b.z,400000);const q4=K.astar(-17,11,-9,-5,40000),q5=K.astar(-9,-5,b.x,b.z,40000),q6=K.astar(-17,11,1,-15,40000);log.push('bar->hallmid '+(q4&&q4.length)+' hallmid->lounge '+(q5&&q5.length)+' bar->hallE '+(q6&&q6.length));log.push('from 1,0: '+(q?q.length:'null'));const q2=K.astar(-17,11,b.x,b.z,40000);log.push('from bar: '+(q2?q2.length:'null'));const q3=K.astar(-17,11,-9,-17,40000);log.push('bar->hall: '+(q3?q3.map(v=>v.x.toFixed(0)+','+v.z.toFixed(0)).join(' '):'null'))}log.push(T2([20,20],[20,10]));log.push(T2([20,10],[25,9]));log.push(T2([25,9],[27,8]));log.push(T2([20,2],[20,10]));const bl=[];for(let j=5;j<12;j++){let s2='';for(let i=22;i<32;i++){const c=N.tw(i,j);const ix=Math.floor((c.x-NAV.x0)/NAV.cs),iz=Math.floor((c.z-NAV.z0)/NAV.cs);s2+=NAV.g[iz*NAV.w+ix]?'#':'.'}bl.push(s2)}log.push(bl.join('\n'));
 // print nav around door (26,8) and (19,17)
 const row=(tx,ty)=>{const c=N.tw(tx,ty);let s='';for(let dz=-2;dz<2;dz+=.5){for(let dx=-3;dx<3;dx+=.5){const ix=Math.floor((c.x+dx-NAV.x0)/NAV.cs),iz=Math.floor((c.z+dz-NAV.z0)/NAV.cs);s+=NAV.g[iz*NAV.w+ix]?'#':'.'}s+='\n'}return s};log.push('door 26,8:\n'+row(26,8));log.push('door 19,17:\n'+row(19,17));return log});
console.log(r.join('\n'));console.log(errs.join('\n')||'no errors');await b.close()})();
