const {chromium}=require('/opt/node22/lib/node_modules/playwright');const fs=require('fs');
(async()=>{const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome',args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const p=await b.newPage({viewport:{width:1100,height:700}});const errs=[];p.on('pageerror',e=>errs.push(e.message+' '+(e.stack||'').split('\n')[1]));
await p.route('**/three.min.js',r=>r.fulfill({body:fs.readFileSync(__dirname+'/node_modules/three/build/three.min.js'),contentType:'application/javascript'}));await p.route(/fonts\./,r=>r.abort());
const mis=process.argv[3]||'0';await p.addInitScript(m=>localStorage.setItem('unb_hs_villain_lv',m),mis);
await p.goto('file://'+process.argv[2]+'?g=hs_villain#hs_villain');await p.waitForTimeout(2000);
const cl=async()=>{const bt=await p.$('.ov3 .btn.primary');if(bt){await bt.click();await p.waitForTimeout(300)}};await cl();await cl();
await p.mouse.move(550,350);await p.mouse.down();await p.mouse.move(420,350,{steps:10});await p.mouse.up();
await p.keyboard.down('f');for(let i=0;i<30;i++){await p.waitForTimeout(250);if(i==10)await p.screenshot({path:'s/vl_laser.png'})}await p.keyboard.up('f');
await p.keyboard.press('q');await p.waitForTimeout(1500);await p.screenshot({path:'s/vl_slam.png'});
await p.keyboard.down('w');await p.keyboard.down('Shift');await p.keyboard.down('f');await p.waitForTimeout(8000);await p.screenshot({path:'s/vl_end.png'});
console.log(await p.evaluate(()=>document.querySelector('.cx-cap').textContent),errs.join('\n')||'no errors');await b.close()})();
