/* lib/escape.js: code shared by several games (from src/heroes/escape.js) */
const ESC_FMT=b=>Math.floor(b/60)+':'+String(Math.floor(b%60)).padStart(2,'0');
function escCss(){if(document.getElementById('esc-css'))return;const s=document.createElement('style');s.id='esc-css';s.textContent=`
.esc{width:min(100%,980px);margin:0 auto;display:grid;gap:10px;user-select:none;-webkit-user-select:none}
.esc-top{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap}
.esc-top b{font-size:18px}.esc-top .esc-wall{font-weight:800;opacity:.75}
.esc-view{position:relative;aspect-ratio:16/9;border:4px solid #1D1A2F;border-radius:14px;overflow:hidden;background:#1D1A2F;box-shadow:6px 6px 0 #1D1A2F}
.esc-view>svg{position:absolute;inset:0;width:100%;height:100%;display:block}
.esc-spot{position:absolute;background:transparent;border:3px dashed transparent;border-radius:10px;cursor:pointer;padding:0}
.esc-spot:hover,.esc-spot:focus-visible{border-color:rgba(255,210,63,.95);background:rgba(255,210,63,.12);outline:none}
.esc-view.using .esc-spot{border-color:rgba(255,255,255,.35)}
.esc-nav{position:absolute;bottom:8px;transform:none!important;width:54px;height:44px;border:3px solid #1D1A2F;border-radius:12px;background:rgba(255,253,246,.92);font:900 24px Figtree,sans-serif;cursor:pointer;z-index:3;color:#1D1A2F}
.esc-nav.l{left:8px}.esc-nav.r{right:8px}
.esc-zoom{position:absolute;inset:0;z-index:5;background:rgba(29,26,47,.78);display:grid;place-items:center;padding:12px}
.esc-card{background:#FFFDF6;border:4px solid #1D1A2F;border-radius:14px;box-shadow:6px 6px 0 #1D1A2F;padding:14px 16px;max-width:min(94%,620px);max-height:94%;overflow:auto;text-align:center;color:#1D1A2F}
.esc-card h4{margin:0 0 8px;font-size:18px}
.esc-card p{margin:6px 0}
.esc-card .btn{margin-top:10px}
.esc-msg{min-height:26px;font-weight:800;background:#FFFDF6;color:#1D1A2F;border:3px solid #1D1A2F;border-radius:10px;padding:6px 10px}
.esc-inv{display:flex;gap:8px;flex-wrap:wrap;align-items:center}
.esc-inv>span{font-weight:900;font-size:13px;letter-spacing:.08em;text-transform:uppercase}
.esc-slot{width:56px;height:56px;border:3px solid #1D1A2F;border-radius:12px;background:#FFFDF6;font-size:28px;cursor:pointer;display:grid;place-items:center;padding:0;position:relative}
.esc-slot.on{background:#FFD23F;transform:translateY(-4px);box-shadow:0 4px 0 #1D1A2F}
.esc-slot.empty{opacity:.35;cursor:default}
.esc-dials{display:flex;gap:10px;justify-content:center;margin:10px 0}
.esc-dial{display:flex;flex-direction:column;align-items:center;gap:4px}
.esc-dial button{width:52px;height:34px;border:3px solid #1D1A2F;border-radius:8px;background:#fff;font:900 16px Figtree,sans-serif;cursor:pointer;color:#1D1A2F}
.esc-dial div{width:52px;height:56px;border:3px solid #1D1A2F;border-radius:10px;background:#1D1A2F;color:#FFD23F;font:900 30px Figtree,sans-serif;display:grid;place-items:center}
.esc-shake{animation:escshake .35s}
@keyframes escshake{20%,60%{transform:translateX(-8px)}40%,80%{transform:translateX(8px)}}
.esc-seq{display:flex;gap:8px;justify-content:center;margin:8px 0}
.esc-seq i{width:34px;height:34px;border:3px solid #1D1A2F;border-radius:50%;background:#e8e4da}
.esc-pal{display:grid;grid-template-columns:repeat(3,56px);gap:8px;justify-content:center}
.esc-pal button{height:56px;border:3px solid #1D1A2F;border-radius:12px;cursor:pointer}
.esc-books{display:flex;gap:6px;justify-content:center;align-items:flex-end;height:170px;margin:10px 0}
.esc-books button{width:48px;border:3px solid #1D1A2F;border-radius:6px 6px 2px 2px;cursor:pointer;padding:0}
.esc-books button.on{transform:translateY(-14px);box-shadow:0 6px 0 #FFD23F}
.esc-win{position:absolute;inset:0;z-index:8;background:rgba(29,26,47,.8);display:grid;place-items:center}
.esc-win .esc-card{animation:escpop .45s cubic-bezier(.3,1.7,.5,1)}
@keyframes escpop{from{transform:scale(.7);opacity:0}}
@media (max-width:600px){.esc-slot{width:46px;height:46px;font-size:23px}.esc-nav{width:42px;height:36px;font-size:18px}.esc-dial button,.esc-dial div{width:42px}}`;document.head.append(s)}
const eR=(x,y,w,h,f,ex)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="${f}" stroke="#1D1A2F" stroke-width="4" ${ex||''}/>`;
const eT=(x,y,s,t,f,ex)=>`<text x="${x}" y="${y}" font-size="${s}" fill="${f||'#1D1A2F'}" font-family="Figtree,Arial,sans-serif" font-weight="900" text-anchor="middle" ${ex||''}>${t}</text>`;
const eRoom=(wall,floor,pat)=>`<rect width="800" height="450" fill="${wall}"/>${pat||''}<rect y="360" width="800" height="90" fill="${floor}"/><path d="M0 360H800" stroke="#1D1A2F" stroke-width="5"/>`;
function escapeRoom(root,c,R){escCss();
  const wrap=el('div',{class:'esc'}),top=el('div',{class:'esc-top'}),view=el('div',{class:'esc-view'}),msg=el('div',{class:'esc-msg'}),inv=el('div',{class:'esc-inv'});
  const wallLbl=el('span',{class:'esc-wall'}),hintB=el('button',{class:'btn',type:'button'},'💡 Hint');top.append(el('b',null,'🔐 '+R.title),wallLbl,hintB);wrap.append(top,view,msg,inv);root.append(wrap);
  let st,items,sel,wall,zoomFn,time,hints,won,look;
  const say=t=>{msg.textContent=t};
  const api={get st(){return st},has:id=>items.includes(id),add(id,t){if(!items.includes(id))items.push(id);beep(740,.08,'triangle');setTimeout(()=>beep(990,.1,'triangle'),70);say(t||('You got: '+R.items[id].name+'.'));drawInv()},remove(id){items=items.filter(x=>x!==id);if(sel===id)sel=null;drawInv()},say,
    go(w){wall=w;render()},refresh(){render()},zoom(fn){zoomFn=fn;render()},close(){zoomFn=null;render()},
    win(){if(won)return;won=true;const total=Math.round(time+hints*30);const best=c.best(total,true);[523,659,784,1046,1318].forEach((f,i)=>setTimeout(()=>beep(f,.2,'triangle'),i*110));
      const box=el('div',{class:'esc-win'}),card=el('div',{class:'esc-card'});card.innerHTML='<h4>🎉 You escaped!</h4><p>'+R.outro+'</p><p><b>Time: '+ESC_FMT(total)+'</b>'+(hints?' (includes '+hints+' hint'+(hints>1?'s':'')+' × 30s)':'')+'</p><p>Best: '+ESC_FMT(best)+'</p>';
      const again=el('button',{class:'btn primary',type:'button'},'Play again');again.addEventListener('click',()=>{box.remove();start()});card.append(again);
      const next=ESC_ROOMS.filter(r=>r.id!==R.id);next.forEach(r=>{const g=G.find(x=>x.id===r.id);if(!g)return;const b=el('button',{class:'btn',type:'button',style:'margin-left:8px'},'Next: '+r.title+' →');b.addEventListener('click',()=>openGame(g));card.append(b)});box.append(card);view.append(box)},
    sfx:{ok(){beep(520,.08,'square');setTimeout(()=>beep(780,.12,'square'),80)},no(){beep(140,.18,'sawtooth')},click(){beep(420,.03,'square')}},
    /* a lock made of spinning dials: symbols, count, answer (array), onOpen */
    dials(box,key,syms,n,answer,onOpen,label){const cur=st.locks[key]||(st.locks[key]=Array(n).fill(0));const row=el('div',{class:'esc-dials'});
      for(let i=0;i<n;i++){const d=el('div',{class:'esc-dial'}),up=el('button',{type:'button','aria-label':'Up'},'▲'),v=el('div',null,syms[cur[i]]),dn=el('button',{type:'button','aria-label':'Down'},'▼');const set=k=>{cur[i]=(cur[i]+k+syms.length)%syms.length;v.textContent=syms[cur[i]];api.sfx.click()};up.addEventListener('click',()=>set(1));dn.addEventListener('click',()=>set(-1));d.append(up,v,dn);row.append(d)}
      const go=el('button',{class:'btn primary',type:'button'},label||'Open');go.addEventListener('click',()=>{if(cur.every((k,i)=>syms[k]===answer[i])){api.sfx.ok();onOpen()}else{api.sfx.no();row.classList.remove('esc-shake');void row.offsetWidth;row.classList.add('esc-shake');say('Nothing. That’s not it.')}});box.append(row,go)},
    /* a colour sequence panel */
    seq(box,cols,n,answer,onOpen){const got=[];const slots=el('div',{class:'esc-seq'});const draw=()=>{slots.innerHTML='';for(let i=0;i<n;i++){const s=el('i');if(got[i])s.style.background=cols.find(x=>x[0]===got[i])[1];slots.append(s)}};draw();const pal=el('div',{class:'esc-pal'});
      cols.forEach(([id,hex])=>{const b=el('button',{type:'button','aria-label':id,style:'background:'+hex});b.addEventListener('click',()=>{got.push(id);api.sfx.click();draw();if(got.length===n){if(got.every((x,i)=>x===answer[i]))setTimeout(onOpen,250);else{api.sfx.no();say('BZZT. Wrong sequence.');slots.classList.remove('esc-shake');void slots.offsetWidth;slots.classList.add('esc-shake');setTimeout(()=>{got.length=0;draw()},450)}}});pal.append(b)});box.append(slots,pal)}};
  function drawInv(){inv.innerHTML='';inv.append(el('span',null,'Items'));for(let i=0;i<Math.max(6,items.length);i++){const id=items[i];if(!id){inv.append(el('button',{class:'esc-slot empty',type:'button','aria-label':'Empty slot',disabled:''}));continue}const it=R.items[id];
      const b=el('button',{class:'esc-slot'+(sel===id?' on':''),type:'button',title:it.name,'aria-label':it.name,style:it.bg?'background:'+it.bg:''},it.icon);
      b.addEventListener('click',()=>{if(won)return;if(sel===id){sel=null;if(it.read){zoomFn=box=>{box.append(el('h4',null,it.icon+' '+it.name),el('div',{html:it.read}))};render()}else say(it.name+': '+it.desc);drawInv();return}
        if(sel){const a=sel;sel=null;if(!(R.combine&&R.combine(a,id,api)))say('Those two don’t go together.');drawInv();return}
        sel=id;say('Using: '+it.name+'. Click where to use it, click another item to combine, or click it again to look at it.');drawInv();view.classList.add('using')});inv.append(b)}if(!sel)view.classList.remove('using')}
  function render(){view.innerHTML='';const w=R.walls[wall](api);wallLbl.textContent=w.name+' · '+(wall+1)+'/'+R.walls.length;view.innerHTML='<svg viewBox="0 0 800 450" aria-hidden="true">'+w.svg+'</svg>';
    w.spots.forEach(s=>{const b=el('button',{class:'esc-spot',type:'button','aria-label':s.name,title:s.name,style:`left:${s.x/8}%;top:${s.y/4.5}%;width:${s.w/8}%;height:${s.h/4.5}%`});
      b.addEventListener('click',()=>{if(won)return;if(sel){const it=sel;sel=null;const ok=s.use&&s.use(it);if(!ok)say('The '+R.items[it].name.toLowerCase()+' doesn’t do anything there.');drawInv();render();return}if(s.fn)s.fn();else if(s.say)say(s.say)});view.append(b)});
    const l=el('button',{class:'esc-nav l',type:'button','aria-label':'Turn left'},'◀'),r=el('button',{class:'esc-nav r',type:'button','aria-label':'Turn right'},'▶');l.addEventListener('click',()=>{zoomFn=null;wall=(wall+R.walls.length-1)%R.walls.length;render()});r.addEventListener('click',()=>{zoomFn=null;wall=(wall+1)%R.walls.length;render()});view.append(l,r);
    if(zoomFn){const z=el('div',{class:'esc-zoom'}),card=el('div',{class:'esc-card'});z.append(card);zoomFn(card);const bk=el('button',{class:'btn',type:'button'},'← Back');bk.addEventListener('click',()=>{zoomFn=null;render()});card.append(el('div',null,bk));z.addEventListener('click',e=>{if(e.target===z){zoomFn=null;render()}});view.append(z)}}
  hintB.addEventListener('click',()=>{if(won)return;hints++;say('💡 '+R.hint(st,api)+' (+30s)');beep(600,.1,'triangle')});
  c.on(document,'keydown',e=>{if(won)return;if(e.key==='ArrowLeft'){zoomFn=null;wall=(wall+R.walls.length-1)%R.walls.length;render()}else if(e.key==='ArrowRight'){zoomFn=null;wall=(wall+1)%R.walls.length;render()}else if(e.key==='Escape'&&zoomFn){zoomFn=null;render()}});
  function start(){st=Object.assign({locks:{}},R.init());items=[];sel=null;wall=0;zoomFn=null;time=0;hints=0;won=false;drawInv();render();say(R.intro)}
  c.loop(dt=>{if(!won){time+=dt/1000;c.stat('⏱ '+ESC_FMT(time)+(hints?' · '+hints+' hint'+(hints>1?'s':''):''))}});start()}
const ESC_CLASS={id:'esc_class',title:'Detention',
  intro:'The bell rang, everyone left, and the janitor locked the door with you still inside. The door has a 4-digit keypad. Look around: click things, use ◀ ▶ to turn.',
  outro:'You slip out of the classroom and down the empty hallway. Nobody will ever know. Except the janitor. He knows.',
  items:{note:{icon:'📝',name:'Crumpled note',desc:'',read:'<p style="font:700 18px/1.5 \'Comic Sans MS\',cursive;background:#fffbe0;border:2px dashed #c9b25a;padding:10px">My locker combo is the number of sides on the shapes on the chalkboard, left to right.<br>- Sam (locker 2)</p>'},
    flash:{icon:'🔦',name:'UV flashlight',desc:'A purple UV flashlight. It has no batteries.'},bat:{icon:'🔋',name:'Batteries',desc:'Two AA batteries.'},uv:{icon:'🔦',name:'Working UV light',bg:'#d9c2ff',desc:'It glows purple. UV light shows hidden ink.'},key:{icon:'🗝️',name:'Small brass key',desc:'A tiny key. It looks like it fits a desk drawer.'}},
  init:()=>({books:['blue','red','purple','yellow','green','orange'],comp:false,keyTaken:false,drawer:false,batTaken:false,note:false,locker:false,flashTaken:false,uvSeen:false,pick:-1}),
  combine(a,b,api){if((a==='flash'&&b==='bat')||(a==='bat'&&b==='flash')){api.remove('flash');api.remove('bat');api.add('uv','You pop the batteries into the flashlight. It glows purple!');return true}return false},
  hint(st,api){if(!st.note)return'Classrooms are messy. Check the trash can.';if(!st.locker)return'Read the crumpled note (click it twice in your items), then count the sides of each shape on the chalkboard.';if(!st.flashTaken)return'Take what’s inside Sam’s locker.';if(!st.comp)return'The poster says ROY G BIV. Put the books on the shelf in rainbow order.';if(!st.keyTaken)return'Something opened on the bookshelf. Take it.';if(!st.drawer)return'Use the small key on the teacher’s desk drawer.';if(!st.batTaken)return'Take the batteries from the drawer.';if(!api.has('uv'))return'Combine the flashlight with the batteries: click one item, then the other.';if(!st.uvSeen)return'UV light shows hidden writing. Use it on the chalkboard.';return'Look at the clock and type the time into the door keypad.'},
  walls:[
    api=>{const st=api.st;const hA=(10+25/60)*30*Math.PI/180,mA=150*Math.PI/180;return{name:'Front of the class',svg:eRoom('#cfe3d4','#b98b5e')+
      `<circle cx="400" cy="72" r="40" fill="#fff" stroke="#1D1A2F" stroke-width="5"/>${[...Array(12)].map((_,i)=>`<circle cx="${400+Math.sin(i*Math.PI/6)*31}" cy="${72-Math.cos(i*Math.PI/6)*31}" r="2.5" fill="#1D1A2F"/>`).join('')}<path d="M400 72L${400+Math.sin(hA)*18} ${72-Math.cos(hA)*18}" stroke="#1D1A2F" stroke-width="6" stroke-linecap="round"/><path d="M400 72L${400+Math.sin(mA)*28} ${72-Math.cos(mA)*28}" stroke="#1D1A2F" stroke-width="4" stroke-linecap="round"/>`+
      eR(60,110,130,170,'#fffdf6')+eT(125,140,18,'CLASS RULES')+eT(125,172,13,'1. No phones')+eT(125,194,13,'2. No running')+eT(125,216,13,'3. No escaping')+eT(125,250,22,'🙂')+
      eR(250,240,300,26,'#8a5a2b')+eR(262,266,40,94,'#7a4a22')+eR(498,266,40,94,'#7a4a22')+eR(310,266,180,70,'#a86f38')+
      (st.drawer?eR(318,300,164,54,'#c48a4c')+(st.batTaken?'':eT(400,338,30,'🔋')):`<circle cx="400" cy="300" r="6" fill="#1D1A2F"/><rect x="398" y="300" width="4" height="12" fill="#1D1A2F"/>`)+
      `<circle cx="300" cy="226" r="14" fill="#F2352A" stroke="#1D1A2F" stroke-width="4"/><path d="M300 212l4-8" stroke="#1D1A2F" stroke-width="4"/>`+eR(420,212,90,28,'#fffdf6')+
      eR(610,100,150,260,'#7a4a2a')+eR(650,125,70,70,'#bfe3ff')+`<circle cx="740" cy="240" r="8" fill="#FFD23F" stroke="#1D1A2F" stroke-width="3"/>`+eR(574,200,28,48,'#9aa3b5')+`${[0,1,2].map(r=>[0,1].map(q=>`<rect x="${579+q*10}" y="${206+r*13}" width="7" height="9" fill="#1D1A2F"/>`).join('')).join('')}`,
      spots:[{name:'Clock',x:358,y:30,w:84,h:84,say:'The clock has stopped. It says 10:25.'},{name:'Class rules',x:60,y:110,w:130,h:170,say:'Rule 3: No escaping. Rude.'},{name:'Apple',x:282,y:204,w:40,h:40,say:'An apple for the teacher. It’s plastic.'},
        {name:'Teacher’s drawer',x:310,y:266,w:180,h:90,fn(){if(!st.drawer)api.say('The drawer is locked. There’s a tiny keyhole.');else if(!st.batTaken){st.batTaken=true;api.add('bat','You take two AA batteries from the drawer.');api.refresh()}else api.say('Just red pens and a stapler.')},use(it){if(it==='key'&&!st.drawer){st.drawer=true;api.remove('key');api.sfx.ok();api.say('The key turns. The drawer slides open: there are batteries inside!');return true}}},
        {name:'Door',x:610,y:100,w:150,h:260,say:'Locked tight. The keypad next to it wants a 4-digit code.'},
        {name:'Door keypad',x:566,y:192,w:44,h:64,fn(){api.zoom(box=>{box.append(el('h4',null,'🔢 Door keypad'),el('p',null,'Enter the 4-digit code.'));api.dials(box,'door','0123456789'.split(''),4,['1','0','2','5'],()=>api.win(),'Enter')})}}]}},
    api=>{const st=api.st;const COL={red:'#F2352A',orange:'#FF9F43',yellow:'#FFD23F',green:'#2BB673',blue:'#2d6fd6',purple:'#8b5cf6'};return{name:'Bookshelf',svg:eRoom('#cfe3d4','#b98b5e')+
      eR(60,60,200,180,'#bfe3ff')+`<path d="M160 60V240M60 150H260" stroke="#1D1A2F" stroke-width="5"/>${[0,1,2,3,4,5,6,7].map(i=>`<path d="M64 ${72+i*21}H256" stroke="#fffdf6" stroke-width="7" opacity=".85"/>`).join('')}`+
      eR(300,70,100,150,'#fffdf6')+['#F2352A','#FF9F43','#FFD23F','#2BB673','#2d6fd6','#8b5cf6'].map((c2,i)=>`<rect x="310" y="${82+i*16}" width="80" height="14" fill="${c2}"/>`).join('')+eT(350,202,16,'ROY G BIV')+
      eR(440,110,300,250,'#8a5a2b')+eR(452,122,276,110,'#6b4220')+st.books.map((b,i)=>eR(468+i*42,138+(i%2)*8,34,94-(i%2)*8,COL[b])).join('')+eR(452,244,276,104,'#6b4220')+
      (st.comp?eR(600,260,110,74,'#3a2413')+(st.keyTaken?'':eT(655,310,34,'🗝️')):eR(600,260,110,74,'#a86f38')+`<circle cx="690" cy="297" r="5" fill="#1D1A2F"/>`)+eR(470,270,100,60,'#e9e0c8')+eT(520,306,14,'OLD MAPS'),
      spots:[{name:'Window',x:60,y:60,w:200,h:180,say:'Locked. And you’re on the third floor anyway.'},{name:'Rainbow poster',x:300,y:70,w:100,h:150,fn(){api.zoom(box=>{box.append(el('h4',null,'🌈 Remember the rainbow!'),el('div',{html:'<p style="font-size:26px;font-weight:900;letter-spacing:.08em"><span style="color:#F2352A">R</span>ed · <span style="color:#FF9F43">O</span>range · <span style="color:#c9a100">Y</span>ellow · <span style="color:#2BB673">G</span>reen · <span style="color:#2d6fd6">B</span>lue · <span style="color:#6b3fd1">I</span>ndigo · <span style="color:#8b5cf6">V</span>iolet</p>'}))})}},
        {name:'Books',x:452,y:122,w:276,h:110,fn(){if(st.comp){api.say('The books are in rainbow order now.');return}const draw=box=>{box.append(el('h4',null,'📚 The bookshelf'),el('p',null,'Click two books to swap them.'));const row=el('div',{class:'esc-books'});st.books.forEach((b,i)=>{const bt=el('button',{type:'button','aria-label':b+' book',class:st.pick===i?'on':'',style:'background:'+COL[b]+';height:'+(120+(i%3)*14)+'px'});bt.addEventListener('click',()=>{if(st.pick<0){st.pick=i;api.sfx.click()}else{const j=st.pick;st.pick=-1;[st.books[i],st.books[j]]=[st.books[j],st.books[i]];api.sfx.click();if(st.books.join()==='red,orange,yellow,green,blue,purple'){st.comp=true;api.sfx.ok();api.close();api.say('Click! A little panel at the bottom of the shelf swings open.');return}}api.zoom(draw)});row.append(bt)});box.append(row)};api.zoom(draw)}},
        {name:'Panel',x:600,y:260,w:110,h:74,fn(){if(!st.comp)api.say('A little wooden panel with no handle. Something must open it.');else if(!st.keyTaken){st.keyTaken=true;api.add('key','You take a small brass key from the hidden panel.');api.refresh()}else api.say('Empty now.')}},{name:'Old maps',x:470,y:270,w:100,h:60,say:'Old maps of places you’d rather be. Anywhere but here.'}]}},
    api=>{const st=api.st;return{name:'Chalkboard and lockers',svg:eRoom('#cfe3d4','#b98b5e')+
      eR(40,50,430,240,'#8a5a2b')+`<rect x="54" y="64" width="402" height="212" fill="#2f5b45"/>`+eT(255,100,22,'Pop quiz: how many sides?','#f4f1e6')+
      `<path d="M120 220L160 150L200 220Z" fill="none" stroke="#f4f1e6" stroke-width="5"/><rect x="225" y="155" width="62" height="62" fill="none" stroke="#f4f1e6" stroke-width="5"/><path d="M345 150l30 0 17 30 -17 30 -30 0 -17 -30z" fill="none" stroke="#f4f1e6" stroke-width="5"/>`+
      (st.uvSeen?`<g filter="url(#uvg)">${eT(255,258,19,'EXIT CODE = THE TIME ON THE CLOCK','#e6b8ff')}</g><defs><filter id="uvg"><feGaussianBlur stdDeviation="2" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>`:'')+
      [0,1,2].map(i=>{const x=510+i*90,open=i===1&&st.locker;return eR(x,70,80,290,'#7c93b5')+(open?eR(x+6,76,68,278,'#2a3350')+(st.flashTaken?'':eT(x+40,240,34,'🔦')):`${[0,1,2,3].map(k=>`<path d="M${x+18} ${92+k*10}H${x+62}" stroke="#1D1A2F" stroke-width="3"/>`).join('')}`+eT(x+40,160,26,String(i+1),'#fffdf6')+(i===1?`<rect x="${x+30}" y="200" width="22" height="26" rx="4" fill="#FFD23F" stroke="#1D1A2F" stroke-width="3"/><path d="M${x+34} 200v-8a7 7 0 0 1 14 0v8" fill="none" stroke="#1D1A2F" stroke-width="3"/>`:''))}).join(''),
      spots:[{name:'Chalkboard',x:40,y:50,w:430,h:240,fn(){api.say(st.uvSeen?'Glowing UV writing: EXIT CODE = THE TIME ON THE CLOCK.':'A triangle, a square and a hexagon. “Pop quiz: how many sides?”')},use(it){if(it==='uv'){st.uvSeen=true;api.sfx.ok();api.say('Hidden writing glows under the UV light!');return true}}},
        {name:'Locker 1',x:510,y:70,w:80,h:290,say:'Locker 1. Locked, and not yours.'},{name:'Locker 3',x:690,y:70,w:80,h:290,say:'Locker 3. Someone stuck a “KEEP OUT” sticker on it.'},
        {name:'Locker 2',x:600,y:70,w:80,h:290,fn(){if(!st.locker)api.zoom(box=>{box.append(el('h4',null,'🔒 Locker 2 padlock'),el('p',null,'A 3-digit combination lock.'));api.dials(box,'locker','0123456789'.split(''),3,['3','4','6'],()=>{st.locker=true;api.close();api.say('The padlock snaps open. There’s a flashlight inside!')})});else if(!st.flashTaken){st.flashTaken=true;api.add('flash','You take the flashlight. It’s a UV one, but there are no batteries in it.');api.refresh()}else api.say('Sam’s locker. Smells like old sandwiches.')}}]}},
    api=>{const st=api.st;return{name:'Student desks',svg:eRoom('#cfe3d4','#b98b5e')+
      eR(60,120,110,110,'#e9e0c8')+`<circle cx="115" cy="160" r="30" fill="#4DA3E0" stroke="#1D1A2F" stroke-width="4"/><path d="M95 150q20 -10 30 10t10 20" fill="#2BB673" stroke="#1D1A2F" stroke-width="3"/><path d="M115 190v30M95 222h40" stroke="#1D1A2F" stroke-width="5"/>`+
      [0,1,2].map(i=>{const x=200+i*150;return eR(x,250,120,20,'#d9a86a')+`<path d="M${x+12} 270v80M${x+108} 270v80" stroke="#1D1A2F" stroke-width="6"/>`+eR(x+30,290,60,60,'#6a8fc0')}).join('')+
      eR(660,270,80,90,'#9aa3b5')+`<path d="M656 270h88" stroke="#1D1A2F" stroke-width="6"/>`+(st.note?'':`<circle cx="690" cy="262" r="12" fill="#fffdf6" stroke="#1D1A2F" stroke-width="3"/>`)+eR(560,200,70,70,'#F2352A',"rx='10'")+`<path d="M575 200v-12h40v12" fill="none" stroke="#1D1A2F" stroke-width="4"/>`,
      spots:[{name:'Globe',x:60,y:120,w:110,h:110,say:'You spin the globe. It stops on the Pacific Ocean. Helpful.'},{name:'Desks',x:200,y:240,w:420,h:120,say:'Someone carved “MR. B IS BORING” into a desk. Bold.'},{name:'Backpack',x:560,y:190,w:70,h:80,say:'Somebody’s backpack. Just homework. Not today.'},
        {name:'Trash can',x:650,y:240,w:100,h:120,fn(){if(!st.note){st.note=true;api.add('note','You dig a crumpled note out of the trash. Click it twice in your items to read it.');api.refresh()}else api.say('Just old gum wrappers.')}}]}}]};
const ESC_LAB={id:'esc_lab',title:'The Lab',
  intro:'You volunteered to tidy Dr. Vex’s lab. Then the lights went red and the door sealed itself. The panel by the door wants a 3-colour sequence.',
  outro:'The blast door hisses open. Dr. Vex’s voice crackles over the speakers: “Impressive. You’re hired.” You run.',
  items:{slide:{icon:'🧫',name:'Sample slide',desc:'A glass slide with something smeared on it. It goes under a microscope.'},fuse:{icon:'🔌',name:'Fuse',desc:'A big glass fuse.'},chart:{icon:'🎨',name:'Colour chart',desc:'',read:'<p style="font-size:18px;line-height:1.8">🔴 + 🔵 = 🟣 purple<br>🔵 + 🟡 = 🟢 green<br>🔴 + 🟡 = 🟠 orange</p>'}},
  init:()=>({fridge:false,slideTaken:false,slideIn:false,term:false,safe:false,fuseTaken:false,chartTaken:false,fused:false}),
  hint(st){if(!st.slideTaken)return'Scientists keep samples cold. Check the fridge.';if(!st.slideIn)return'Put the sample slide under the microscope.';if(!st.term)return'The sticky note in the fridge says the password is what you see under the microscope. Type it into the computer.';if(!st.safe)return'The computer says: count the bubbles in each beaker, left to right. That’s the safe code.';if(!st.fuseTaken)return'Take the things from the safe.';if(!st.fused)return'Put the fuse into the empty slot of the fuse box by the door.';return'The whiteboard shows three colour mixes. Mix them in your head (or read the colour chart) and press the answers on the door panel in order.'},
  walls:[
    api=>{const st=api.st;const tile=[...Array(10)].map((_,i)=>`<path d="M${i*80} 0V360" stroke="#c4ccd8" stroke-width="2"/>`).join('')+[...Array(5)].map((_,i)=>`<path d="M0 ${i*80}H800" stroke="#c4ccd8" stroke-width="2"/>`).join('');return{name:'Blast door',svg:eRoom('#dfe6ee','#8c95a8',tile)+`<rect width="800" height="450" fill="#ff2a2a" opacity=".08"/>`+
      eR(280,80,220,280,'#8a93a6')+`${[0,1,2,3,4,5,6].map(i=>`<path d="M${280+i*32} 80l-20 30" stroke="#FFD23F" stroke-width="10"/>`).join('')}`+eR(300,120,180,220,'#9aa3b5')+`<path d="M390 120V340" stroke="#1D1A2F" stroke-width="4"/>`+eT(390,240,20,'☣','#F2352A')+
      eR(530,160,100,140,'#3a3f4d')+`<rect x="545" y="172" width="70" height="22" fill="${st.fused?'#2BB673':'#111'}" stroke="#1D1A2F" stroke-width="3"/>`+['#F2352A','#FF9F43','#FFD23F','#2BB673','#2d6fd6','#8b5cf6'].map((c2,i)=>`<circle cx="${560+(i%2)*40}" cy="${214+Math.floor(i/2)*28}" r="10" fill="${c2}" stroke="#1D1A2F" stroke-width="3" opacity="${st.fused?1:.35}"/>`).join('')+
      eR(660,150,100,130,'#6f7d8c')+eT(710,175,13,'FUSES','#fffdf6')+[0,1,2].map(i=>eR(676+i*24,190,18,64,i===1&&!st.fused?'#1D1A2F':'#c8d6e6')).join('')+`<circle cx="120" cy="60" r="26" fill="#ff4a3a" stroke="#1D1A2F" stroke-width="4"/>`,
      spots:[{name:'Blast door',x:280,y:80,w:220,h:280,say:'Sealed. Half a metre of steel. Not budging.'},{name:'Alarm light',x:90,y:30,w:60,h:60,say:'WEE-OO WEE-OO. Very calming.'},
        {name:'Door panel',x:530,y:160,w:100,h:140,fn(){if(!st.fused){api.say('The panel is dead. The fuse box next to it has an empty slot.');return}api.zoom(box=>{box.append(el('h4',null,'🚪 Exit sequence'),el('p',null,'Press 3 colours in the right order.'));api.seq(box,[['red','#F2352A'],['orange','#FF9F43'],['yellow','#FFD23F'],['green','#2BB673'],['blue','#2d6fd6'],['purple','#8b5cf6']],3,['purple','green','orange'],()=>api.win())})}},
        {name:'Fuse box',x:660,y:150,w:100,h:130,fn(){api.say(st.fused?'All three fuses are in. The panel has power.':'Three fuse slots. The middle one is empty.')},use(it){if(it==='fuse'&&!st.fused){st.fused=true;api.remove('fuse');api.sfx.ok();api.say('The fuse clicks in. The door panel lights up!');return true}}}]}},
    api=>{const st=api.st;const BK=[['#2BB673',3],['#FF8FB1',1],['#4DA3E0',4],['#FFD23F',2]];return{name:'Lab bench',svg:eRoom('#dfe6ee','#8c95a8')+
      eR(40,262,560,24,'#e8e4da')+`<path d="M60 286v74M580 286v74" stroke="#1D1A2F" stroke-width="8"/>`+
      BK.map(([col,n],i)=>{const x=90+i*110;return`<path d="M${x-8} 150h16v40l30 72h-76l30 -72z" fill="#eef6ff" stroke="#1D1A2F" stroke-width="4" stroke-linejoin="round"/><path d="M${x-26} 220h52l16 42h-84z" fill="${col}"/>`+[...Array(n)].map((_,k)=>`<circle cx="${x-12+k*8}" cy="${206-k*14}" r="5" fill="#fff" stroke="#1D1A2F" stroke-width="2"/>`).join('')}).join('')+
      `<path d="M500 262h60M520 262v-80l-20 -30M540 182a24 24 0 1 0 -40 -10" fill="none" stroke="#1D1A2F" stroke-width="8"/><rect x="505" y="130" width="22" height="40" fill="#3a3f4d" stroke="#1D1A2F" stroke-width="3" transform="rotate(-30 516 150)"/>`+(st.slideIn?`<rect x="498" y="190" width="44" height="8" fill="#bfe3ff" stroke="#1D1A2F" stroke-width="2"/>`:'')+
      eR(630,110,130,130,'#6f7d8c')+(st.safe?eR(640,120,110,110,'#2a3350')+(st.fuseTaken?'':eT(675,190,30,'🔌'))+(st.chartTaken?'':eT(720,190,30,'🎨')):`<circle cx="695" cy="175" r="30" fill="#9aa3b5" stroke="#1D1A2F" stroke-width="4"/><path d="M695 150v10M695 190v10M670 175h10M710 175h10" stroke="#1D1A2F" stroke-width="4"/>`),
      spots:BK.map(([col,n],i)=>({name:'Beaker '+(i+1),x:50+i*110,y:140,w:84,h:124,say:'A bubbling beaker. You count '+n+' bubble'+(n>1?'s':'')+' rising.'})).concat([
        {name:'Microscope',x:490,y:120,w:90,h:142,fn(){if(!st.slideIn){api.say('A microscope. It needs a sample slide.');return}api.zoom(box=>{box.append(el('h4',null,'🔬 Under the microscope'),el('div',{html:'<svg viewBox="0 0 300 300" width="260" height="260"><circle cx="150" cy="150" r="140" fill="#f4ffe8" stroke="#1D1A2F" stroke-width="8"/>'+escDots('GENE',150,150)+'</svg>'}),el('p',null,'The cells have clumped into letters…'))})},use(it){if(it==='slide'&&!st.slideIn){st.slideIn=true;api.remove('slide');api.sfx.ok();api.say('You slide the sample under the lens. Take a look.');return true}}},
        {name:'Safe',x:630,y:110,w:130,h:130,fn(){if(!st.safe){api.zoom(box=>{box.append(el('h4',null,'🔒 Wall safe'),el('p',null,'4-digit code.'));api.dials(box,'safe','0123456789'.split(''),4,['3','1','4','2'],()=>{st.safe=true;api.close();api.say('The safe swings open. There’s a fuse and a colour chart inside.')})});return}
          if(!st.fuseTaken){st.fuseTaken=true;api.add('fuse','You take the fuse.');api.refresh();return}if(!st.chartTaken){st.chartTaken=true;api.add('chart','You take the colour chart. Click it twice to read it.');api.refresh();return}api.say('The safe is empty.')}}])}},
    api=>{const st=api.st;return{name:'Computer and whiteboard',svg:eRoom('#dfe6ee','#8c95a8')+
      eR(80,250,320,24,'#6f7d8c')+`<path d="M100 274v86M380 274v86" stroke="#1D1A2F" stroke-width="8"/>`+eR(110,100,260,150,'#3a3f4d')+`<rect x="126" y="114" width="228" height="112" fill="${st.term?'#0f3a24':'#0b1a33'}"/>`+
      (st.term?eT(240,150,15,'ACCESS GRANTED','#6EE7B7')+eT(240,176,13,'SAFE CODE = BUBBLES','#6EE7B7')+eT(240,196,13,'IN EACH BEAKER, L TO R','#6EE7B7'):eT(240,160,16,'PASSWORD: _ _ _ _','#7FC8F8')+eT(240,190,12,'hint: look closer','#4a6a9a'))+`<path d="M220 250v-24h40v24" fill="#6f7d8c" stroke="#1D1A2F" stroke-width="4"/>`+
      eR(440,60,320,230,'#fffdf6')+eT(600,94,20,'EXIT SEQUENCE')+[['#F2352A','#2d6fd6'],['#2d6fd6','#FFD23F'],['#F2352A','#FFD23F']].map(([a,b],i)=>{const y=140+i*50;return eT(470,y+8,20,(i+1)+'.')+`<circle cx="520" cy="${y}" r="16" fill="${a}" stroke="#1D1A2F" stroke-width="3"/>`+eT(560,y+8,26,'+')+`<circle cx="600" cy="${y}" r="16" fill="${b}" stroke="#1D1A2F" stroke-width="3"/>`+eT(640,y+8,26,'=')+eT(690,y+10,28,'?','#F2352A')}).join(''),
      spots:[{name:'Computer',x:110,y:100,w:260,h:150,fn(){if(st.term){api.say('ACCESS GRANTED. Safe code = the bubbles in each beaker, left to right.');return}api.zoom(box=>{box.append(el('h4',null,'💻 Dr. Vex’s computer'),el('p',null,'Enter the 4-letter password.'));api.dials(box,'term','ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split(''),4,['G','E','N','E'],()=>{st.term=true;api.close();api.say('ACCESS GRANTED. A message appears on the screen.')},'Log in')})}},
        {name:'Whiteboard',x:440,y:60,w:320,h:230,say:'Three colour mixes. Each answer is one button on the exit panel.'}]}},
    api=>{const st=api.st;return{name:'Storage',svg:eRoom('#dfe6ee','#8c95a8')+
      eR(80,70,180,290,'#f4f7fb')+(st.fridge?eR(90,80,160,270,'#dff2ff')+`<path d="M90 170h160M90 260h160" stroke="#1D1A2F" stroke-width="4"/>`+(st.slideTaken?'':eT(150,160,34,'🧫'))+eR(180,110,58,50,'#FFD23F')+eT(209,140,11,'NOTE'):`<path d="M80 160h180" stroke="#1D1A2F" stroke-width="4"/><path d="M240 100v40M240 190v60" stroke="#1D1A2F" stroke-width="6" stroke-linecap="round"/>`+eT(170,230,16,'BIO SAMPLES')+eT(170,262,26,'☣','#F2352A'))+
      eR(320,90,220,20,'#8a93a6')+eR(320,190,220,20,'#8a93a6')+['🧪','⚗️','🧴','🧪'].map((e,i)=>eT(350+i*52,84,34,e)).join('')+['🦴','💀','🧠'].map((e,i)=>eT(360+i*70,184,38,e)).join('')+
      eR(590,230,170,40,'#c8d6e6')+`<path d="M660 230v-50h40" fill="none" stroke="#1D1A2F" stroke-width="6"/>`+eR(600,270,150,90,'#9aa3b5'),
      spots:[{name:'Fridge',x:80,y:70,w:180,h:290,fn(){if(!st.fridge){st.fridge=true;api.sfx.ok();api.say('The fridge door swings open. Cold air, a sample slide and a sticky note.');api.refresh();return}if(!st.slideTaken){st.slideTaken=true;api.add('slide','You take the sample slide.');api.refresh();return}api.say('Leftover sandwiches labelled “DO NOT EAT (EXPERIMENT)”.')}},
        {name:'Sticky note',x:178,y:108,w:62,h:54,fn(){if(!st.fridge){api.say('A fridge labelled BIO SAMPLES.');return}api.zoom(box=>box.append(el('h4',null,'🟨 Sticky note'),el('p',{style:'font:700 20px/1.5 \'Comic Sans MS\',cursive'},'Password = whatever you see under the microscope. - V')))}},
        {name:'Shelves',x:320,y:40,w:220,h:170,say:'Beakers, a skull and a brain in a jar. Normal lab stuff.'},{name:'Sink',x:590,y:170,w:170,h:190,say:'An emergency eyewash sink. Your eyes are fine. Your situation is not.'}]}}]};
function escDots(word,cx,cy){const F={G:['01110','10000','10111','10001','01110'],E:['11111','10000','11110','10000','11111'],N:['10001','11001','10101','10011','10001']};let s='';const w=word.length*6-1,sz=8;word.split('').forEach((ch,k)=>{F[ch].forEach((row,r)=>row.split('').forEach((b,q)=>{if(b==='1')s+=`<circle cx="${cx-(w*sz)/2+(k*6+q)*sz+4}" cy="${cy-20+r*sz}" r="3.6" fill="#2BB673" stroke="#1D1A2F" stroke-width="1"/>`}))});for(let i=0;i<30;i++){const a=Math.random()*6.28,r=40+Math.random()*90;s+=`<circle cx="${cx+Math.cos(a)*r}" cy="${cy+Math.sin(a)*r}" r="${2+Math.random()*3}" fill="#9fd6a0" opacity=".6"/>`}return s}
const ESC_TOMB={id:'esc_tomb',title:'Pharaoh’s Tomb',
  intro:'Your torch went out and the tomb entrance slammed shut behind you. The great stone door won’t move. Somewhere in here is the way out.',
  outro:'The stone door grinds open and desert sunlight pours in. You escape with nothing but sand in your shoes and a great story.',
  items:{torch:{icon:'🪵',name:'Unlit torch',desc:'A wooden torch. It needs fire.'},ltorch:{icon:'🔥',name:'Lit torch',desc:'A burning torch. It lights up dark places.'},lever:{icon:'🦯',name:'Bronze lever',desc:'A long bronze handle, like part of a mechanism.'},scarab:{icon:'🪲',name:'Golden scarab',desc:'A heavy golden beetle. It looks like it fits into something.'},papyrus:{icon:'📜',name:'Papyrus',desc:'',read:'<p style="font:700 19px/1.6 Georgia,serif;background:#f3e2b3;border:2px solid #b8934a;padding:12px">To leave the tomb, follow the sun god Ra on his journey:<br><b>dawn, noon, dusk, night.</b></p>'}},
  init:()=>({torchTaken:false,jars:[],jarsDone:false,leverTaken:false,sarco:false,scarabTaken:false,papTaken:false,placed:false}),
  combine(a,b,api){return false},
  hint(st,api){if(!st.torchTaken)return'Grab the torch from the wall of hieroglyphs.';if(!api.has('ltorch')&&!st.placed&&!st.sarco&&!api.has('scarab'))return'Use the torch on the burning brazier to light it.';if(!st.jarsDone)return'The hieroglyph wall shows four heads in order, I to IV. Lift the jar lids in that order.';if(!st.leverTaken)return'Take what was hidden under the last jar.';if(!st.sarco)return'Fit the lever into the slot on the side of the sarcophagus.';if(!st.scarabTaken||!st.papTaken)return'Take everything from the open sarcophagus.';if(!st.placed)return'Put the golden scarab into the socket on the stone door.';return'Read the papyrus, then look at the mural in the dark passage (you’ll need the lit torch) to see which symbol means dawn, noon, dusk and night.'},
  walls:[
    api=>{const st=api.st;const S=['🪲','☀️','🐦','👁️','🌙'];const cur=st.locks.door||[0,0,0,0];const blocks=[...Array(6)].map((_,r)=>[...Array(9)].map((_,q)=>`<rect x="${q*92-(r%2)*46}" y="${r*60}" width="92" height="60" fill="none" stroke="#b8934a" stroke-width="2"/>`).join('')).join('');return{name:'The stone door',svg:eRoom('#d9b77a','#a07c45',blocks)+
      eR(240,50,320,310,'#bf9a5a')+`<path d="M240 50L400 20L560 50" fill="#a88748" stroke="#1D1A2F" stroke-width="4"/>`+`<ellipse cx="400" cy="110" rx="34" ry="26" fill="${st.placed?'#FFD23F':'#5a4526'}" stroke="#1D1A2F" stroke-width="4"/>`+(st.placed?eT(400,122,30,'🪲'):'')+
      [0,1,2,3].map(i=>`<circle cx="${298+i*68}" cy="250" r="28" fill="#8a6a36" stroke="#1D1A2F" stroke-width="4"/>`+eT(298+i*68,262,30,S[cur[i]])).join('')+eT(400,180,16,'𓂀 THE WAY OF RA 𓂀','#5a4526'),
      spots:[{name:'Stone door',x:240,y:50,w:320,h:150,say:'A huge stone door carved with the words “THE WAY OF RA”.'},{name:'Scarab socket',x:360,y:80,w:80,h:60,fn(){api.say(st.placed?'The golden scarab sits in the socket.':'An empty socket shaped like a beetle.')},use(it){if(it==='scarab'&&!st.placed){st.placed=true;api.remove('scarab');api.sfx.ok();api.say('The scarab clicks into place. The dials on the door loosen!');return true}}},
        {name:'Symbol dials',x:260,y:210,w:280,h:80,fn(){if(!st.placed){api.say('The four dials are stuck fast. There’s an empty beetle-shaped socket above them.');return}api.zoom(box=>{box.append(el('h4',null,'𓂀 The door dials'),el('p',null,'Turn the four dials.'));api.dials(box,'door',S,4,['🪲','☀️','🐦','👁️'],()=>api.win(),'Push the door')})}}]}},
    api=>{const st=api.st;const P=[['🦅','I'],['🧑','II'],['🐺','III'],['🐒','IV']];return{name:'Hieroglyph wall',svg:eRoom('#d9b77a','#a07c45')+
      P.map(([e,n],i)=>{const x=150+i*150;return eR(x,70,130,210,'#e9d3a0')+eT(x+65,165,64,e)+eT(x+65,250,26,n,'#8a6a36')+`<path d="M${x+15} 190h100M${x+15} 205h100" stroke="#b8934a" stroke-width="4"/>`}).join('')+
      eR(40,120,70,20,'#6b4a22')+(st.torchTaken?'':`<rect x="66" y="60" width="16" height="90" fill="#8a5a2b" stroke="#1D1A2F" stroke-width="3"/><ellipse cx="74" cy="58" rx="12" ry="8" fill="#5a4526"/>`),
      spots:P.map(([e,n],i)=>({name:'Panel '+n,x:150+i*150,y:70,w:130,h:210,say:'Panel '+n+'. The four guardians of the jars, in order: falcon, human, jackal, baboon.'})).concat([{name:'Torch',x:40,y:50,w:80,h:100,fn(){if(!st.torchTaken){st.torchTaken=true;api.add('torch','You take the torch from its holder. It’s not lit.');api.refresh()}else api.say('An empty torch holder.')}}])}},
    api=>{const st=api.st;const J=[['🐺','jackal'],['🦅','falcon'],['🐒','baboon'],['🧑','human']],ORD=['falcon','human','jackal','baboon'];return{name:'Sarcophagus',svg:eRoom('#d9b77a','#a07c45')+
      eR(30,240,260,20,'#8a6a36')+J.map(([e,id],i)=>{const x=65+i*62,up=st.jars.includes(id)||st.jarsDone;return`<path d="M${x-22} 238q-6 -60 8 -80h28q14 20 8 80z" fill="#e9d3a0" stroke="#1D1A2F" stroke-width="4"/>`+eT(x,up?112:150,30,e)+(up?`<ellipse cx="${x}" cy="160" rx="16" ry="5" fill="#3a2a14"/>`:'')}).join('')+(st.jarsDone&&!st.leverTaken?eT(303,232,26,'🦯'):'')+
      (st.sarco?`<rect x="330" y="230" width="380" height="110" rx="30" fill="#2a1f10" stroke="#1D1A2F" stroke-width="4"/>`+(st.scarabTaken?'':eT(470,300,40,'🪲'))+(st.papTaken?'':eT(580,300,40,'📜'))+`<rect x="560" y="150" width="200" height="70" rx="30" fill="#2d6fd6" stroke="#1D1A2F" stroke-width="4" transform="rotate(12 660 185)"/>`:
        `<rect x="330" y="200" width="380" height="140" rx="40" fill="#2d6fd6" stroke="#1D1A2F" stroke-width="4"/>${[0,1,2,3,4,5].map(i=>`<path d="M${370+i*55} 204v132" stroke="#FFD23F" stroke-width="10"/>`).join('')}<ellipse cx="370" cy="270" rx="36" ry="46" fill="#FFD23F" stroke="#1D1A2F" stroke-width="4"/>`)+eR(720,260,40,60,'#5a4526')+`<rect x="733" y="272" width="14" height="36" fill="${st.sarco?'#b8934a':'#1D1A2F'}"/>`,
      spots:J.map(([e,id],i)=>({name:'Canopic jar ('+id+')',x:40+i*62,y:100,w:52,h:140,fn(){if(st.jarsDone){api.say('The jar lids are all lifted. The jars are empty.');return}
          st.jars.push(id);api.sfx.click();if(st.jars.some((x,k)=>x!==ORD[k])){st.jars=[];api.sfx.no();api.say('RUMBLE. The lids slam back down. Wrong order.')}else if(st.jars.length===4){st.jarsDone=true;api.sfx.ok();api.say('All four lids lifted in order. Something glints behind the jars: a bronze lever!')}else api.say('You lift the '+id+' lid.');api.refresh()}})).concat([
        {name:'Bronze lever',x:282,y:196,w:44,h:44,fn(){if(st.jarsDone&&!st.leverTaken){st.leverTaken=true;api.add('lever','You take the bronze lever.');api.refresh()}else api.say(st.leverTaken?'Nothing else here.':'Just sand.')}},
        {name:'Sarcophagus',x:330,y:190,w:380,h:150,fn(){if(!st.sarco){api.say('The lid is far too heavy to push. There’s a slot on the side, like a lever should go in it.');return}if(!st.scarabTaken){st.scarabTaken=true;api.add('scarab','You lift out a golden scarab.');api.refresh();return}if(!st.papTaken){st.papTaken=true;api.add('papyrus','You take the papyrus scroll. Click it twice to read it.');api.refresh();return}api.say('Just a very old, very rude mummy.')},use(it){if(it==='lever'&&!st.sarco){st.sarco=true;api.remove('lever');api.sfx.ok();api.say('You pull the lever. Stone grinds as the heavy lid slides aside!');return true}}},
        {name:'Lever slot',x:715,y:250,w:50,h:80,fn(){api.say(st.sarco?'The lever is jammed in, holding the mechanism open.':'A slot for a lever.')},use(it){if(it==='lever'&&!st.sarco){st.sarco=true;api.remove('lever');api.sfx.ok();api.say('You pull the lever. Stone grinds as the heavy lid slides aside!');return true}}}])}},
    api=>{const st=api.st;const lit=api.has('ltorch');const M=[['🪲','DAWN'],['☀️','NOON'],['🐦','DUSK'],['👁️','NIGHT']];return{name:'Dark passage',svg:eRoom('#d9b77a','#a07c45')+
      eR(230,60,520,280,'#e9d3a0')+M.map(([e,t],i)=>{const x=295+i*130;return eT(x,190,64,e)+eT(x,250,20,t,'#8a6a36')}).join('')+eT(490,110,20,'THE JOURNEY OF RA','#8a6a36')+
      (lit?`<radialGradient id="tg"><stop offset="0" stop-color="#000" stop-opacity="0"/><stop offset="1" stop-color="#000" stop-opacity=".45"/></radialGradient><rect x="200" width="600" height="450" fill="url(#tg)"/>`:`<rect x="200" width="600" height="450" fill="#0b0805"/>`+eT(500,230,22,'It’s pitch black down here.','#5a4526'))+
      `<path d="M70 360l30 -90h60l30 90z" fill="#5a4526" stroke="#1D1A2F" stroke-width="4"/><path d="M95 270q35 -80 70 0" fill="#FF7A2A" stroke="#1D1A2F" stroke-width="3"/><path d="M112 270q18 -46 36 0" fill="#FFD23F"/>`,
      spots:[{name:'Brazier',x:60,y:180,w:140,h:180,fn(){api.say('A brazier. The fire is still burning. Lucky.')},use(it){if(it==='torch'){api.remove('torch');api.add('ltorch','You light the torch in the brazier. Now you can see in the dark!');return true}}},
        {name:'Passage mural',x:230,y:60,w:520,h:280,fn(){if(!lit){api.say('Too dark to see anything. You need light.');return}api.zoom(box=>{box.append(el('h4',null,'☀️ The journey of Ra'),el('div',{html:'<p style="font-size:30px;line-height:1.5">🪲 Dawn → ☀️ Noon → 🐦 Dusk → 👁️ Night</p>'}),el('p',null,'The sun rolls up like a beetle at dawn, burns at noon, flies away at dusk and watches at night.'))})}}]}}]};
const ESC_ROOMS=[ESC_CLASS,ESC_LAB,ESC_TOMB];
