/* lib/physics.js: code shared by several games (from src/heroes/physics.js) */
let matterP=null;
function loadMatter(){if(window.Matter)return Promise.resolve(window.Matter);if(matterP)return matterP;matterP=new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/matter-js@0.19.0/build/matter.min.js';s.onload=()=>res(window.Matter);s.onerror=()=>{matterP=null;rej(new Error('physics failed'))};document.head.append(s)});return matterP}
function withMatter(root,c,start){const ld=el('div',{class:'g3load'},el('b',null,'Loading physics…'),el('small',null,'Warming up the smashing engine.'));root.append(ld);let dead=false,cleanup=null;
  loadMatter().then(()=>{if(dead)return;ld.remove();try{cleanup=start()}catch(err){root.append(el('p',{class:'hint'},'This game hit an error: '+err.message));console.error(err)}}).catch(()=>{if(dead)return;ld.innerHTML='';ld.append(el('b',null,'Couldn’t load the physics engine'),el('small',null,'Check your internet connection, then reopen this game.'))});
  return()=>{dead=true;cleanup&&cleanup()}}
const PMAT={glass:{col:'#9fd6ff',hp:3,d:.0012,pts:15,snd:'glass'},wood:{col:'#FF9F43',hp:10,d:.0016,pts:10,snd:'wood'},brick:{col:'#F2352A',hp:15,d:.0022,pts:12,snd:'thud'},stone:{col:'#8c86a3',hp:26,d:.003,pts:20,snd:'thud'},concrete:{col:'#d8d4e4',hp:34,d:.0032,pts:25,snd:'thud'},plastic:{col:'#B9A7FF',hp:6,d:.001,pts:12,snd:'wood'},ceramic:{col:'#FF8FB1',hp:2.2,d:.0014,pts:25,snd:'glass'},tv:{col:'#3a3552',hp:5,d:.0018,pts:40,snd:'glass'}};
function PhysWorld(root,c,o){const Mt=window.Matter;const{Engine,Bodies,Composite,Body,Events,Vector,Query}=Mt;const W=o.w||960,H=o.h||600;
  const cv=el('canvas',{class:'board',width:W,height:H,style:'width:100%;cursor:'+(o.cursor||'crosshair')});root.append(cv);const x=cv.getContext('2d');
  const engine=Engine.create();engine.positionIterations=8;engine.velocityIterations=6;const world=engine.world;
  const pw={Mt,engine,world,cv,x,W,H,pops:[],frags:[],dust:[],steps:[],draws:[],under:[],broke:null,t:0,shake:0};
  pw.add=b=>{Composite.add(world,b);return b};pw.remove=b=>{Composite.remove(world,b)};
  pw.ground=(y,col)=>{const g=pw.add(Bodies.rectangle(W/2,y+60,W*3,120,{isStatic:true,friction:.9}));g.plugin.col=col||'#5A5470';g.plugin.ground=1;return g};
  pw.wall=(xx)=>{const w=pw.add(Bodies.rectangle(xx,H/2-400,100,H+1200,{isStatic:true}));w.plugin.hidden=1;return w};
  pw.block=(bx0,by,w,h,mat,opt)=>{const m=PMAT[mat];const b=pw.add(Bodies.rectangle(bx0,by,w,h,Object.assign({density:m.d,friction:.7,restitution:.05,frictionAir:.005},opt||{})));b.plugin.mat=mat;b.plugin.hp=b.plugin.max=m.hp*Math.sqrt(w*h/1600);b.plugin.col=m.col;b.plugin.brk=1;b.plugin.w=w;b.plugin.h=h;return b};
  pw.pop=(t,px,py,col,big)=>{pw.pops.push({t,x:px,y:py,col:col||'#FFD23F',l:.9,r:(Math.random()-.5)*.4,big})};
  pw.puff=(px,py,n,col)=>{for(let i=0;i<(n||6);i++)pw.dust.push({x:px,y:py,vx:(Math.random()-.5)*4,vy:(Math.random()-.5)*4-1,r:4+Math.random()*8,l:.6+Math.random()*.4,col:col||'rgba(216,212,228,.9)'})};
  const toBreak=[];
  function hit(t,oth,rv){if(!t.plugin.brk||t.isStatic||t.plugin.dead)return;const om=oth.isStatic?t.mass*1.5:oth.mass;const dmg=Math.max(0,rv-(o.thresh||2.2))*Math.min(5,om/t.mass+.25)*(oth.plugin.power||1)*(o.dmgMul||1);if(dmg<=0)return;t.plugin.hp-=dmg;if(t.plugin.hp<=0){t.plugin.dead=1;toBreak.push(t)}}
  Events.on(engine,'collisionStart',e=>{for(const p of e.pairs){const a=p.bodyA.parent,b=p.bodyB.parent;if(a.plugin.frag&&b.plugin.frag)continue;const rv=Vector.magnitude(Vector.sub(a.velocity,b.velocity));if(rv<1.5)continue;hit(a,b,rv);hit(b,a,rv);if(o.onHit)o.onHit(a,b,rv,p)}});
  pw.shatter=(b,quiet)=>{if(b.plugin.gone)return;b.plugin.gone=1;pw.remove(b);const m=PMAT[b.plugin.mat]||{col:b.plugin.col,pts:5,snd:'thud'};const w=b.plugin.w||30,h=b.plugin.h||30;const n=clamp(Math.round(w*h/500),3,9);
    for(let i=0;i<n;i++){const s=Math.max(5,Math.sqrt(w*h/n)*.75);const lx=(Math.random()-.5)*w*.7,ly=(Math.random()-.5)*h*.7;const ca=Math.cos(b.angle),sa=Math.sin(b.angle);const f=Bodies.polygon(b.position.x+lx*ca-ly*sa,b.position.y+lx*sa+ly*ca,3+rand(2),s*.6,{density:.001,frictionAir:.01,collisionFilter:{group:-7}});Body.setVelocity(f,{x:b.velocity.x+(Math.random()-.5)*6,y:b.velocity.y+(Math.random()-.5)*6-2});Body.setAngularVelocity(f,(Math.random()-.5)*.4);f.plugin.frag=1;f.plugin.col=b.plugin.col;f.plugin.l=2.2+Math.random();pw.add(f);pw.frags.push(f)}
    pw.puff(b.position.x,b.position.y,6);if(!quiet){if(m.snd==='glass'){noise(.18,'highpass',3000,.12);beep(2400+Math.random()*800,.05,'triangle',.03)}else if(m.snd==='wood')noise(.14,'bandpass',900,.14);else noise(.2,'lowpass',400,.18)}
    if(pw.broke)pw.broke(b,m)};
  pw.explode=(px,py,R,pow,dmgR)=>{pw.shake=Math.max(pw.shake,14);noise(.6,'lowpass',260,.4);pw.pop(pick(['KA-BOOM!','BLAM!','KRAKOOM!']),px,py-20,'#FFD23F',1);for(let i=0;i<22;i++)pw.dust.push({x:px,y:py,vx:(Math.random()-.5)*14,vy:(Math.random()-.5)*14,r:6+Math.random()*14,l:.5+Math.random()*.5,col:pick(['#FFD23F','#FF9F43','#F2352A','rgba(90,84,112,.8)'])});
    Composite.allBodies(world).forEach(b=>{if(b.isStatic)return;const d=Vector.sub(b.position,{x:px,y:py});const L=Vector.magnitude(d)||1;if(L>R)return;const k=(1-L/R);if(b.plugin.brk&&L<(dmgR||R*.35)){b.plugin.hp-=40*k+10;if(b.plugin.hp<=0&&!b.plugin.dead){b.plugin.dead=1;toBreak.push(b)}}Body.setVelocity(b,{x:b.velocity.x+d.x/L*pow*k,y:b.velocity.y+d.y/L*pow*k-pow*k*.3});Body.setAngularVelocity(b,b.angularVelocity+(Math.random()-.5)*.3*k)})};
  function drawBody(b){if(b.plugin.hidden)return;if(b.plugin.emoji){x.save();x.globalAlpha=b.plugin.l!=null&&b.plugin.l<1?Math.max(0,b.plugin.l):1;x.translate(b.position.x,b.position.y);x.rotate(b.angle+(b.plugin.erot||0));x.font=(b.plugin.esz||32)+'px sans-serif';x.textAlign='center';x.textBaseline='middle';x.fillText(b.plugin.emoji,0,b.plugin.eoy||0);x.restore();x.globalAlpha=1;return}if(b.plugin.draw){b.plugin.draw(x,b);if(b.plugin.face)b.plugin.face(x,b);return}const parts=b.parts.length>1?b.parts.slice(1):[b];x.globalAlpha=b.plugin.frag?clamp(b.plugin.l,0,1):1;
    parts.forEach(p=>{x.beginPath();if(p.circleRadius){x.arc(p.position.x,p.position.y,p.circleRadius,0,7)}else{const v=p.vertices;x.moveTo(v[0].x,v[0].y);for(let i=1;i<v.length;i++)x.lineTo(v[i].x,v[i].y);x.closePath()}x.fillStyle=p.plugin.col||b.plugin.col||'#8c86a3';x.fill();x.lineWidth=b.plugin.frag?2:3;x.strokeStyle='#1D1A2F';x.stroke()});
    if(b.plugin.brk&&b.plugin.hp<b.plugin.max*.6&&!b.circleRadius){x.save();x.translate(b.position.x,b.position.y);x.rotate(b.angle);x.strokeStyle='rgba(29,26,47,.6)';x.lineWidth=2;x.beginPath();const w=(b.plugin.w||20)/2,h=(b.plugin.h||20)/2;x.moveTo(-w*.6,-h*.5);x.lineTo(w*.1,h*.1);x.lineTo(-w*.1,h*.6);x.moveTo(w*.1,h*.1);x.lineTo(w*.6,-h*.3);x.stroke();x.restore()}
    if(b.plugin.mat==='glass'&&!b.plugin.frag){x.save();x.translate(b.position.x,b.position.y);x.rotate(b.angle);x.strokeStyle='rgba(255,255,255,.8)';x.lineWidth=2;x.beginPath();const w=(b.plugin.w||20)/2,h=(b.plugin.h||20)/2;x.moveTo(-w*.5,h*.4);x.lineTo(w*.2,-h*.5);x.stroke();x.restore()}
    if(b.plugin.face)b.plugin.face(x,b);x.globalAlpha=1}
  pw.draw=()=>{x.save();if(pw.shake>0){x.translate((Math.random()-.5)*pw.shake,(Math.random()-.5)*pw.shake);pw.shake*=.85;if(pw.shake<.5)pw.shake=0}
    const g=x.createLinearGradient(0,0,0,H);g.addColorStop(0,o.sky||'#7FC8F8');g.addColorStop(1,o.sky2||'#FFE9B8');x.fillStyle=g;x.fillRect(-20,-20,W+40,H+40);x.fillStyle='rgba(255,255,255,.25)';for(let yy=0;yy<H;yy+=14)for(let xx=(yy/14%2)*7;xx<W;xx+=14){x.beginPath();x.arc(xx,yy,1+yy/H*2.2,0,7);x.fill()}
    pw.under.forEach(f=>f(x));Composite.allBodies(world).forEach(drawBody);pw.draws.forEach(f=>f(x));
    pw.dust.forEach(d=>{x.globalAlpha=clamp(d.l,0,1);x.fillStyle=d.col;x.beginPath();x.arc(d.x,d.y,d.r*(1.4-d.l*.4),0,7);x.fill()});x.globalAlpha=1;
    pw.pops.forEach(p=>{const k=1-p.l/.9;x.save();x.translate(p.x,p.y-k*30);x.rotate(p.r);const s=(p.big?1.6:1)*(k<.2?k/.2*1.2:1);x.scale(s,s);x.globalAlpha=clamp(p.l*2,0,1);x.font='32px "Bagel Fat One", "Arial Black", sans-serif';x.textAlign='center';x.lineWidth=6;x.strokeStyle='#1D1A2F';x.strokeText(p.t,0,0);x.fillStyle=p.col;x.fillText(p.t,0,0);x.restore()});x.globalAlpha=1;x.restore()};
  let acc=0;c.loop(dt=>{acc=Math.min(acc+dt,50);while(acc>=16.667){Engine.update(engine,16.667);pw.t+=16.667;pw.steps.forEach(f=>f());while(toBreak.length)pw.shatter(toBreak.shift());acc-=16.667}
    const s=dt/1000;for(let i=pw.frags.length-1;i>=0;i--){const f=pw.frags[i];f.plugin.l-=s;if(f.plugin.l<=0||f.position.y>H+200){pw.remove(f);pw.frags.splice(i,1)}}
    for(let i=pw.dust.length-1;i>=0;i--){const d=pw.dust[i];d.l-=s;d.x+=d.vx;d.y+=d.vy;d.vx*=.92;d.vy*=.92;if(d.l<=0)pw.dust.splice(i,1)}for(let i=pw.pops.length-1;i>=0;i--){pw.pops[i].l-=s;if(pw.pops[i].l<=0)pw.pops.splice(i,1)}pw.draw()});
  pw.pos=e=>canvasPos(cv,e);
  pw.clear=()=>{Composite.clear(world,false,true);pw.frags=[];pw.dust=[];pw.pops=[]};
  return pw}
function phBanner(x,W,H,t1,t2){x.fillStyle='rgba(29,26,47,.78)';x.fillRect(0,H/2-70,W,140);x.textAlign='center';x.font='44px "Bagel Fat One", sans-serif';x.lineWidth=6;x.strokeStyle='#1D1A2F';x.strokeText(t1,W/2,H/2);x.fillStyle='#FFD23F';x.fillText(t1,W/2,H/2);x.fillStyle='#FFFDF6';x.font='600 20px Figtree, sans-serif';x.fillText(t2,W/2,H/2+40)}
function towerAt(pw,cx,base,floors,wid,mats){const bs=[];let y=base;const colW=18,colH=64,slab=16;for(let f=0;f<floors;f++){const m=mats?pick(mats):pick(['wood','brick','stone','concrete']);bs.push(pw.block(cx-wid/2+colW/2,y-colH/2,colW,colH,m));bs.push(pw.block(cx+wid/2-colW/2,y-colH/2,colW,colH,m));if(wid>90){bs.push(pw.block(cx,y-colH/2,10,colH-4,'glass'))}y-=colH;bs.push(pw.block(cx,y-slab/2,wid+8,slab,f%2?'concrete':m));y-=slab}if(Math.random()<.6)bs.push(pw.block(cx,y-14,wid*.5,28,'glass'));return bs}
