// Builds js/catalog-lite.js from js/catalog.js: the same games without card art and blurbs. Game pages load this
// smaller file (the homepage keeps the full catalog). It still has everything the player needs on a game page:
// names for the random button, sections, page addresses, difficulty/leaderboard flags and score formats.
// Run after any change to js/catalog.js (tools/new-game.cjs runs it for you).
// It also writes js/catalog-art.js (just the card art, by id), which game pages load in the background so the
// random-game spinner can show every game's picture.
// Usage: node tools/catalog-lite.cjs
const fs = require('fs'), path = require('path');
const ROOT = path.join(__dirname, '..');
const KEEP = ['id', 'name', 'kind', 'tint', 'url', 'levels', 'wide', 'big', 'major', 'lower', 'tags', 'noLb'];
const lines = fs.readFileSync(path.join(ROOT, 'js/catalog.js'), 'utf8').split('\n').filter(l => l.startsWith('{"id"'));
const art = {};
const out = lines.map(l => {
  const body = l.replace(/,\s*$/, '');
  const fm = body.match(/,"fmt":([\s\S]*)\}$/);
  const o = JSON.parse(fm ? body.slice(0, fm.index) + '}' : body);
  const am = body.match(/"art":("(?:[^"\\]|\\.)*")/);
  if (am) art[o.id] = JSON.parse(am[1]);
  const lite = {}; for (const k of KEEP) if (o[k] != null) lite[k] = o[k];
  let s = JSON.stringify(lite);
  if (fm) s = s.slice(0, -1) + ',"fmt":' + fm[1] + '}';
  return s;
});
const src = '/* catalog-lite.js: generated by tools/catalog-lite.cjs from catalog.js (no card art or blurbs). Loaded by game pages. */\nG.push(\n' + out.join(',\n') + '\n);\n';
fs.writeFileSync(path.join(ROOT, 'js/catalog-lite.js'), src);
console.log('catalog-lite.js:', out.length, 'games,', Math.round(src.length / 1024), 'KB');
const artSrc = '/* catalog-art.js: generated by tools/catalog-lite.cjs. Card art by game id, loaded lazily by game pages. */\nwindow.GART=' + JSON.stringify(art) + ';\n';
fs.writeFileSync(path.join(ROOT, 'js/catalog-art.js'), artSrc);
console.log('catalog-art.js:', Object.keys(art).length, 'pictures,', Math.round(artSrc.length / 1024), 'KB');
